Indri: indri::lang::QueryTFWalker Class Reference
indri::lang::QueryTFWalker Class Reference
#include <QueryTFWalker.hpp>
Public Member Functions
QueryTFWalker (std::vector< indri::server::QueryServer * > &servers)
~QueryTFWalker ()
void after (indri::lang::RawScorerNode *scorer)
void after (indri::lang::PlusNode *plus)
void after (indri::lang::WPlusNode *plus)
Private Attributes
std::map< lemur::api::TERMID_T,
std::vector
< indri::lang::RawScorerNode * > > _nodeMap
std::vector
< indri::server::QueryServer * > & _servers
Constructor & Destructor Documentation
indri::lang::QueryTFWalker::QueryTFWalker (std::vector< indri::server::QueryServer * > & servers) [inline]
indri::lang::QueryTFWalker::~QueryTFWalker () [inline]
Member Function Documentation
void indri::lang::QueryTFWalker::after (indri::lang::WPlusNode * plus) [inline, virtual]
Reimplemented from indri::lang::Walker.
References indri::lang::WeightedCombinationNode::getChildren(), indri::lang::RawScorerNode::getSmoothing(), and indri::lang::RawScorerNode::setSmoothing().
void indri::lang::QueryTFWalker::after (indri::lang::PlusNode * plus) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _nodeMap.
void indri::lang::QueryTFWalker::after (indri::lang::RawScorerNode * scorer) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _nodeMap, _servers, and indri::lang::RawScorerNode::queryText().
Member Data Documentation
std::map< lemur::api::TERMID_T, std::vector<indri::lang::RawScorerNode*> > indri::lang::QueryTFWalker::_nodeMap [private]
Referenced by after().
std::vector<indri::server::QueryServer*>& indri::lang::QueryTFWalker::_servers [private]
Referenced by after().
The documentation for this class was generated from the following file:
QueryTFWalker.hpp