Indri: indri::infnet::DocumentStructureHolderNode Class Reference
indri::infnet::DocumentStructureHolderNode Class Reference
#include <DocumentStructureHolderNode.hpp>
Public Member Functions
DocumentStructureHolderNode (const std::string &name)
~DocumentStructureHolderNode ()
void prepare (lemur::api::DOCID_T documentID)
lemur::api::DOCID_T nextCandidateDocument ()
const std::string & getName () const
indri::index::DocumentStructure * getDocumentStructure ()
void indexChanged (indri::index::Index &index)
Private Attributes
indri::index::Index * _index
lemur::api::DOCID_T _nextDocument
indri::index::TermListFileIterator * _docIter
lemur::api::DOCID_T _docIterID
std::string _name
indri::index::DocumentStructure * _documentStructure
Constructor & Destructor Documentation
indri::infnet::DocumentStructureHolderNode::DocumentStructureHolderNode (const std::string & name)
indri::infnet::DocumentStructureHolderNode::~DocumentStructureHolderNode ()
References _docIter, and _documentStructure.
Member Function Documentation
indri::index::DocumentStructure * indri::infnet::DocumentStructureHolderNode::getDocumentStructure ()
References _documentStructure.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::infnet::ShrinkageBeliefNode::hasMatch(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), and indri::infnet::ShrinkageBeliefNode::score().
const std::string & indri::infnet::DocumentStructureHolderNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::DocumentStructureHolderNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _docIter, _docIterID, _documentStructure, _index, _nextDocument, indri::index::TermListFileIterator::startIteration(), and indri::index::Index::termListFileIterator().
Referenced by indri::infnet::InferenceNetwork::_indexChanged().
lemur::api::DOCID_T indri::infnet::DocumentStructureHolderNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _nextDocument.
void indri::infnet::DocumentStructureHolderNode::prepare (lemur::api::DOCID_T documentID)
References _docIter, _docIterID, _documentStructure, _index, _nextDocument, indri::index::TermListFileIterator::currentEntry(), indri::index::Index::documentMaximum(), indri::index::DocumentStructure::loadStructure(), and indri::index::TermListFileIterator::nextEntry().
Referenced by indri::infnet::InferenceNetwork::_moveToDocument().
Member Data Documentation
indri::index::TermListFileIterator* indri::infnet::DocumentStructureHolderNode::_docIter [private]
Referenced by indexChanged(), prepare(), and ~DocumentStructureHolderNode().
lemur::api::DOCID_T indri::infnet::DocumentStructureHolderNode::_docIterID [private]
Referenced by indexChanged(), and prepare().
indri::index::DocumentStructure* indri::infnet::DocumentStructureHolderNode::_documentStructure [private]
Referenced by getDocumentStructure(), indexChanged(), prepare(), and ~DocumentStructureHolderNode().
indri::index::Index* indri::infnet::DocumentStructureHolderNode::_index [private]
Referenced by indexChanged(), and prepare().
std::string indri::infnet::DocumentStructureHolderNode::_name [private]
Referenced by getName().
lemur::api::DOCID_T indri::infnet::DocumentStructureHolderNode::_nextDocument [private]
Referenced by indexChanged(), nextCandidateDocument(), and prepare().
The documentation for this class was generated from the following files:
DocumentStructureHolderNode.hpp
DocumentStructureHolderNode.cpp