Indri: indri::lang::NestedExtentInside Class Reference
indri::lang::NestedExtentInside Class Reference
#include <QuerySpec.hpp>
Public Member Functions
NestedExtentInside (RawExtentNode *inner, RawExtentNode *outer)
NestedExtentInside (Unpacker &unpacker)
bool operator== (Node &o)
std::string typeName () const
UINT64 hashCode () const
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::NestedExtentInside::NestedExtentInside (RawExtentNode * inner, RawExtentNode * outer) [inline]
Referenced by copy().
indri::lang::NestedExtentInside::NestedExtentInside (Unpacker & unpacker) [inline]
Member Function Documentation
Node* indri::lang::NestedExtentInside::copy (Copier & copier) [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References indri::lang::ExtentInside::_inner, indri::lang::ExtentInside::_outer, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), NestedExtentInside(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
UINT64 indri::lang::NestedExtentInside::hashCode () const [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References indri::lang::ExtentInside::_inner, and indri::lang::Node::hashCode().
bool indri::lang::NestedExtentInside::operator== (Node & o) [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References indri::lang::ExtentInside::_inner, and indri::lang::ExtentInside::_outer.
std::string indri::lang::NestedExtentInside::typeName () const [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
The documentation for this class was generated from the following file:
QuerySpec.hpp