Indri: indri::index::DocListMemoryBuilder Class Reference
indri::index::DocListMemoryBuilder Class Reference
#include <DocListMemoryBuilder.hpp>
Public Types
typedef
DocListMemoryBuilderIterator iterator
Public Member Functions
DocListMemoryBuilder (indri::utility::RegionAllocator *allocator)
~DocListMemoryBuilder ()
const DocListMemoryBuilder & operator= (DocListMemoryBuilder &other)
void startDocument (int docID)
void addLocation (int location)
void endDocument ()
void clear ()
void flush ()
bool empty ()
int documentFrequency () const
int termFrequency () const
size_t memorySize () const
Private Member Functions
void _safeAddLocation (int position)
size_t _roundUp (size_t amount)
void _grow ()
void _terminateDocument ()
Private Attributes
int _documentFrequency
int _termFrequency
indri::utility::greedy_vector
< DocListMemoryBuilderSegment, 4 > _lists
char * _list
char * _listBegin
char * _listEnd
char * _documentPointer
char * _locationCountPointer
int _lastLocation
int _lastDocument
int _lastTermFrequency
indri::utility::RegionAllocator * _allocator
Friends
class DocListMemoryBuilderIterator
Member Typedef Documentation
typedef DocListMemoryBuilderIterator indri::index::DocListMemoryBuilder::iterator
Constructor & Destructor Documentation
indri::index::DocListMemoryBuilder::DocListMemoryBuilder (indri::utility::RegionAllocator * allocator)
indri::index::DocListMemoryBuilder::~DocListMemoryBuilder ()
Member Function Documentation
void indri::index::DocListMemoryBuilder::_grow () [private]
References _allocator, _documentPointer, _list, _listBegin, _listEnd, _lists, _locationCountPointer, _roundUp(), indri::utility::RegionAllocator::allocate(), indri::utility::greedy_vector< _Type, _Count >::back(), GROW_TIMES, LOCATION_SPACE, MIN_SIZE, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by addLocation(), endDocument(), flush(), and startDocument().
size_t indri::index::DocListMemoryBuilder::_roundUp (size_t amount) [private]
References GROW_TIMES, and MIN_SIZE.
Referenced by _grow().
void indri::index::DocListMemoryBuilder::_safeAddLocation (int position) [inline, private]
References _lastLocation, _list, _listBegin, _listEnd, _locationCountPointer, and _termFrequency.
Referenced by addLocation().
void indri::index::DocListMemoryBuilder::_terminateDocument () [inline, private]
References _documentFrequency, _documentPointer, _lastLocation, _lastTermFrequency, _list, _listBegin, _listEnd, _locationCountPointer, and _termFrequency.
Referenced by endDocument(), and flush().
void indri::index::DocListMemoryBuilder::addLocation (int location)
References _grow(), _lastLocation, _list, _listEnd, _safeAddLocation(), and LOCATION_SPACE.
Referenced by indri::index::MemoryIndex::addDocument().
void indri::index::DocListMemoryBuilder::clear ()
int indri::index::DocListMemoryBuilder::documentFrequency () const
References _documentFrequency.
bool indri::index::DocListMemoryBuilder::empty ()
void indri::index::DocListMemoryBuilder::endDocument ()
References _grow(), _lastTermFrequency, _list, _listEnd, _termFrequency, _terminateDocument(), and TERMINATE_SPACE.
Referenced by indri::index::MemoryIndex::addDocument().
void indri::index::DocListMemoryBuilder::flush ()
References _documentPointer, _grow(), _lastTermFrequency, _list, _listEnd, _lists, _locationCountPointer, _termFrequency, _terminateDocument(), indri::utility::greedy_vector< _Type, _Count >::back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::index::DocListMemoryBuilderIterator::reset().
size_t indri::index::DocListMemoryBuilder::memorySize () const
References _lists, GROW_TIMES, MIN_SIZE, and indri::utility::greedy_vector< _Type, _Count >::size().
const DocListMemoryBuilder& indri::index::DocListMemoryBuilder::operator= (DocListMemoryBuilder & other)
void indri::index::DocListMemoryBuilder::startDocument (int docID)
References _documentPointer, _grow(), _lastDocument, _lastLocation, _list, _listEnd, _locationCountPointer, and PLENTY_OF_SPACE.
Referenced by indri::index::MemoryIndex::addDocument().
int indri::index::DocListMemoryBuilder::termFrequency () const
References _termFrequency.
Referenced by indri::index::MemoryIndex::addDocument().
Friends And Related Function Documentation
friend class DocListMemoryBuilderIterator [friend]
Member Data Documentation
indri::utility::RegionAllocator* indri::index::DocListMemoryBuilder::_allocator [private]
Referenced by _grow().
int indri::index::DocListMemoryBuilder::_documentFrequency [private]
Referenced by _terminateDocument(), and documentFrequency().
char* indri::index::DocListMemoryBuilder::_documentPointer [private]
Referenced by _grow(), _terminateDocument(), flush(), and startDocument().
int indri::index::DocListMemoryBuilder::_lastDocument [private]
Referenced by startDocument().
int indri::index::DocListMemoryBuilder::_lastLocation [private]
Referenced by _safeAddLocation(), _terminateDocument(), addLocation(), and startDocument().
int indri::index::DocListMemoryBuilder::_lastTermFrequency [private]
Referenced by _terminateDocument(), endDocument(), and flush().
char* indri::index::DocListMemoryBuilder::_list [private]
Referenced by _grow(), _safeAddLocation(), _terminateDocument(), addLocation(), endDocument(), flush(), and startDocument().
char* indri::index::DocListMemoryBuilder::_listBegin [private]
Referenced by _grow(), _safeAddLocation(), and _terminateDocument().
char* indri::index::DocListMemoryBuilder::_listEnd [private]
Referenced by _grow(), _safeAddLocation(), _terminateDocument(), addLocation(), endDocument(), flush(), and startDocument().
indri::utility::greedy_vector< DocListMemoryBuilderSegment, 4 > indri::index::DocListMemoryBuilder::_lists [private]
Referenced by _grow(), flush(), memorySize(), and indri::index::DocListMemoryBuilderIterator::reset().
char* indri::index::DocListMemoryBuilder::_locationCountPointer [private]
Referenced by _grow(), _safeAddLocation(), _terminateDocument(), flush(), and startDocument().
int indri::index::DocListMemoryBuilder::_termFrequency [private]
Referenced by _safeAddLocation(), _terminateDocument(), endDocument(), flush(), and termFrequency().
The documentation for this class was generated from the following files:
DocListMemoryBuilder.hpp
DocListMemoryBuilder.cpp