Indri: indri::query::TermScoreFunctionFactory Class Reference
indri::query::TermScoreFunctionFactory Class Reference
#include <TermScoreFunctionFactory.hpp>
Static Public Member Functions
static TermScoreFunction * get (const std::string &spec, double occurences, double contextSize, int documentOccurrences=0, int documentCount=0)
Member Function Documentation
indri::query::TermScoreFunction * indri::query::TermScoreFunctionFactory::get (const std::string & spec, double occurences, double contextSize, int documentOccurrences = 0, int documentCount = 0) [static]
References indri::api::Parameters::exists(), indri::api::Parameters::get(), and termscorefunctionfactory_parse().
Referenced by indri::infnet::InferenceNetworkBuilder::_buildTermScoreFunction(), and indri::query::RelevanceModel::_scoreGrams().
The documentation for this class was generated from the following files:
TermScoreFunctionFactory.hpp
TermScoreFunctionFactory.cpp