Indri: indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker Class Reference
indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker Class Reference
Public Member Functions
SubtreeWalker ()
bool isComputable ()
std::vector
< indri::lang::IndexTerm * > & getTerms ()
indri::lang::Field * getField ()
bool hasContext () const
void defaultBefore (indri::lang::Node *node)
void before (indri::lang::ContextCounterNode *contextNode)
void before (indri::lang::ExtentAnd *extentAndNode)
void before (indri::lang::Field *fieldNode)
void before (indri::lang::IndexTerm *termNode)
void before (indri::lang::ExtentInside *insideNode)
Private Attributes
bool _computable
bool _hasContext
std::vector
< indri::lang::IndexTerm * > _terms
indri::lang::Field * _field
Constructor & Destructor Documentation
indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::SubtreeWalker () [inline]
Member Function Documentation
void indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before (indri::lang::ExtentInside * insideNode) [inline, virtual]
Reimplemented from indri::lang::Walker.
void indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before (indri::lang::IndexTerm * termNode) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _terms.
void indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before (indri::lang::Field * fieldNode) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _computable, and _field.
void indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before (indri::lang::ExtentAnd * extentAndNode) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _computable, and indri::lang::ExtentAnd::getChildren().
void indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before (indri::lang::ContextCounterNode * contextNode) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _hasContext, and indri::lang::ContextCounterNode::getContext().
void indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::defaultBefore (indri::lang::Node * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _computable.
indri::lang::Field* indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::getField () [inline]
References _field.
Referenced by indri::lang::ContextSimpleCountCollectorCopier::after().
std::vector<indri::lang::IndexTerm*>& indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::getTerms () [inline]
References _terms.
Referenced by indri::lang::ContextSimpleCountCollectorCopier::after().
bool indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::hasContext () const [inline]
References _hasContext.
Referenced by indri::lang::ContextSimpleCountCollectorCopier::after().
bool indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::isComputable () [inline]
References _computable, and _terms.
Referenced by indri::lang::ContextSimpleCountCollectorCopier::after().
Member Data Documentation
bool indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::_computable [private]
Referenced by before(), defaultBefore(), and isComputable().
indri::lang::Field* indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::_field [private]
Referenced by before(), and getField().
bool indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::_hasContext [private]
Referenced by before(), and hasContext().
std::vector<indri::lang::IndexTerm*> indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::_terms [private]
Referenced by before(), getTerms(), and isComputable().
The documentation for this class was generated from the following file:
ContextSimpleCountCollectorCopier.hpp