Indri: indri::infnet::PriorNode Class Reference
indri::infnet::PriorNode Class Reference
#include <PriorNode.hpp>
Public Member Functions
PriorNode (const std::string &name, class InferenceNetwork &network, int listID)
~PriorNode ()
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
double maximumScore ()
double maximumBackgroundScore ()
const std::string & getName () const
Private Attributes
indri::utility::greedy_vector
< bool > _matches
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
std::string _name
class InferenceNetwork & _network
int _listID
indri::collection::PriorListIterator * _iterator
Constructor & Destructor Documentation
indri::infnet::PriorNode::PriorNode (const std::string & name, class InferenceNetwork & network, int listID)
indri::infnet::PriorNode::~PriorNode ()
Member Function Documentation
void indri::infnet::PriorNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _scores, indri::infnet::Annotator::add(), indri::index::Extent::end, score(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::PriorNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::PriorNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _matches, indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::PriorNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
void indri::infnet::PriorNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _iterator, _listID, _network, and indri::infnet::InferenceNetwork::getPriorIterator().
double indri::infnet::PriorNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_HUGE_SCORE.
double indri::infnet::PriorNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_HUGE_SCORE.
lemur::api::DOCID_T indri::infnet::PriorNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::PriorNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _iterator, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::collection::PriorListIterator::currentEntry(), indri::api::ScoredExtentResult::document, indri::collection::PriorListIterator::finished(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::api::ScoredExtentResult::score.
Referenced by annotate().
Member Data Documentation
indri::collection::PriorListIterator* indri::infnet::PriorNode::_iterator [private]
Referenced by indexChanged(), and score().
int indri::infnet::PriorNode::_listID [private]
Referenced by indexChanged().
indri::utility::greedy_vector<bool> indri::infnet::PriorNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::PriorNode::_name [private]
Referenced by getName().
class InferenceNetwork& indri::infnet::PriorNode::_network [private]
Referenced by indexChanged().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::PriorNode::_scores [private]
Referenced by annotate(), and score().
The documentation for this class was generated from the following files:
PriorNode.hpp
PriorNode.cpp