Indri: indri::parse::AnchorTextAnnotator Class Reference
indri::parse::AnchorTextAnnotator Class Reference
#include <AnchorTextAnnotator.hpp>
Public Member Functions
AnchorTextAnnotator ()
~AnchorTextAnnotator ()
void open (const std::string &anchorFile)
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
Private Member Functions
bool _readLine (char *beginLine, size_t max)
void _readDocumentHeader ()
void _fetchText (indri::utility::greedy_vector< TagExtent * > &tags, indri::utility::greedy_vector< char * > &terms)
bool _matchingDocno (indri::api::ParsedDocument *document)
Private Attributes
gzFile _in
indri::utility::Buffer _gzbuffer
indri::parse::Tokenizer * tokenizer
indri::parse::TokenizedDocument * tokenized
char _docno [DOCNO_SIZE]
char * linkLine
int _count
indri::utility::Buffer _buffer
ObjectHandler
< indri::api::ParsedDocument > * _handler
Detailed Description
Reads anchor text in from files created by the combiner, and adds the text to the end of the parsed document
Constructor & Destructor Documentation
indri::parse::AnchorTextAnnotator::AnchorTextAnnotator () [inline]
References _handler, _in, indri::parse::TokenizerFactory::get(), linkLine, LINKLINE_SIZE, and tokenizer.
indri::parse::AnchorTextAnnotator::~AnchorTextAnnotator () [inline]
References _in, linkLine, and tokenizer.
Member Function Documentation
void indri::parse::AnchorTextAnnotator::_fetchText (indri::utility::greedy_vector< TagExtent * > & tags, indri::utility::greedy_vector< char * > & terms) [inline, private]
References _buffer, _count, _readLine(), indri::parse::TagExtent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::UnparsedDocument::content, indri::parse::UnparsedDocument::contentLength, indri::parse::TagExtent::end, indri::utility::greedy_vector< _Type, _Count >::end(), LINE_SIZE, linkLine, LINKLINE_SIZE, indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::parse::TagExtent::parent, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::parse::TokenizedDocument::terms, indri::parse::UnparsedDocument::text, indri::parse::UnparsedDocument::textLength, indri::parse::Tokenizer::tokenize(), tokenized, tokenizer, and indri::utility::Buffer::write().
Referenced by transform().
bool indri::parse::AnchorTextAnnotator::_matchingDocno (indri::api::ParsedDocument * document) [inline, private]
References _docno, indri::api::ParsedDocument::metadata, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by transform().
void indri::parse::AnchorTextAnnotator::_readDocumentHeader () [inline, private]
References _count, _docno, _readLine(), DOCNO_SIZE, and LINE_SIZE.
Referenced by open(), and transform().
bool indri::parse::AnchorTextAnnotator::_readLine (char * beginLine, size_t max) [inline, private]
References _gzbuffer, _in, indri::utility::Buffer::front(), indri::utility::Buffer::grow(), GZ_BUFFER_SIZE, indri::utility::Buffer::position(), indri::utility::Buffer::size(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by _fetchText(), and _readDocumentHeader().
void indri::parse::AnchorTextAnnotator::handle (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::AnchorTextAnnotator::open (const std::string & anchorFile) [inline]
References _buffer, _gzbuffer, _in, _readDocumentHeader(), and indri::utility::Buffer::clear().
Referenced by indri::api::IndexEnvironment::_createAnnotators().
void indri::parse::AnchorTextAnnotator::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [inline, virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument* indri::parse::AnchorTextAnnotator::transform (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _buffer, _fetchText(), _gzbuffer, _matchingDocno(), _readDocumentHeader(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::TagExtent::begin, BUFFER_SIZE, indri::utility::Buffer::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::parse::TagExtent::end, indri::utility::Buffer::grow(), GZ_BUFFER_SIZE, indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::parse::TagExtent::parent, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::tags, and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
indri::utility::Buffer indri::parse::AnchorTextAnnotator::_buffer [private]
Referenced by _fetchText(), open(), and transform().
int indri::parse::AnchorTextAnnotator::_count [private]
Referenced by _fetchText(), and _readDocumentHeader().
char indri::parse::AnchorTextAnnotator::_docno[DOCNO_SIZE] [private]
Referenced by _matchingDocno(), and _readDocumentHeader().
indri::utility::Buffer indri::parse::AnchorTextAnnotator::_gzbuffer [private]
Referenced by _readLine(), open(), and transform().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::AnchorTextAnnotator::_handler [private]
Referenced by AnchorTextAnnotator(), handle(), and setHandler().
gzFile indri::parse::AnchorTextAnnotator::_in [private]
Referenced by _readLine(), AnchorTextAnnotator(), open(), and ~AnchorTextAnnotator().
char* indri::parse::AnchorTextAnnotator::linkLine [private]
Referenced by _fetchText(), AnchorTextAnnotator(), and ~AnchorTextAnnotator().
indri::parse::TokenizedDocument* indri::parse::AnchorTextAnnotator::tokenized [private]
Referenced by _fetchText().
indri::parse::Tokenizer* indri::parse::AnchorTextAnnotator::tokenizer [private]
Referenced by _fetchText(), AnchorTextAnnotator(), and ~AnchorTextAnnotator().
The documentation for this class was generated from the following file:
AnchorTextAnnotator.hpp