Indri: indri::api::QueryParserFactory Class Reference
indri::api::QueryParserFactory Class Reference
#include <QueryParserFactory.hpp>
Static Public Member Functions
static QueryParserWrapper * get (const std::string &query, const std::string &parserType="indri")
Create an instance of the appropriate query parser.
Detailed Description
Create instances of appropriate query lexer/parsers
Member Function Documentation
QueryParserWrapper * indri::api::QueryParserFactory::get (const std::string & query, const std::string & parserType = "indri") [static]
Create an instance of the appropriate query parser.
Parameters:
query the query string to give to the lexer.
parserType the type of query parser to create. Default is indri.
Referenced by indri::api::QueryEnvironment::_expCount(), indri::api::QueryEnvironment::expressionList(), and indri::api::QueryEnvironment::runQuery().
The documentation for this class was generated from the following files:
QueryParserFactory.hpp
QueryParserFactory.cpp