Indri: FieldModifier Class Reference
FieldModifier Class Reference
Public Member Functions
FieldModifier ()
~FieldModifier ()
void processFields (indri::api::Parameters &param)
Private Member Functions
void _mergeFields ()
void _mergeData ()
Private Attributes
indri::parse::TagList tl
indri::utility::IndriTimer g_timer
indri::api::ParsedDocument * parsed
indri::utility::Buffer termBuffer
indri::index::Index * _index
indri::index::TermListFileIterator * _docIter
indri::parse::FileClassEnvironment * fce
std::vector< std::string > removeNames
indri::api::Parameters repo
indri::api::Parameters addFields
bool adding
Constructor & Destructor Documentation
FieldModifier::FieldModifier () [inline]
References indri::utility::Buffer::grow(), and termBuffer.
FieldModifier::~FieldModifier () [inline]
References _docIter, and fce.
Member Function Documentation
void FieldModifier::_mergeData () [inline, private]
References _docIter, _index, indri::parse::TagList::addTag(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::FieldExtent::begin, indri::utility::Buffer::clear(), indri::parse::TagList::clear(), indri::index::TermListFileIterator::currentEntry(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::FieldExtent::end, indri::parse::TagList::endTag(), indri::index::Index::field(), indri::utility::Buffer::grow(), parsed, indri::api::ParsedDocument::positions, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::tags, termBuffer, indri::api::ParsedDocument::terms, indri::api::ParsedDocument::text, indri::api::ParsedDocument::textLength, tl, indri::utility::Buffer::write(), and indri::parse::TagList::writeTagList().
Referenced by processFields().
void FieldModifier::_mergeFields () [inline, private]
References addFields, adding, indri::api::Parameters::append(), indri::api::Parameters::exists(), indri::api::Parameters::get(), indri::api::Parameters::remove(), removeNames, repo, indri::api::Parameters::set(), and indri::api::Parameters::size().
Referenced by processFields().
void FieldModifier::processFields (indri::api::Parameters & param) [inline]
these need to be combined with existing.
References _docIter, _index, _mergeData(), _mergeFields(), indri::collection::Repository::addDocument(), addFields, adding, indri::collection::Repository::close(), indri::collection::Repository::collection(), indri::file::Path::combine(), indri::parse::FileClassEnvironment::conflater, indri::collection::Repository::create(), indri::index::DeletedDocumentList::deletedCount(), indri::collection::Repository::deletedList(), indri::index::Index::documentCount(), indri::api::Parameters::exists(), fce, g_timer, indri::parse::FileClassEnvironmentFactory::get(), indri::api::Parameters::get(), indri::collection::Repository::indexes(), indri::api::Parameters::loadFile(), indri::index::TermListFileIterator::nextEntry(), indri::parse::OffsetAnnotationAnnotator::open(), indri::collection::Repository::openRead(), parsed, indri::utility::IndriTimer::printElapsedSeconds(), indri::file::Path::remove(), removeNames, indri::file::Path::rename(), repo, indri::api::Parameters::set(), indri::parse::OffsetAnnotationAnnotator::setConflater(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::Parameters::size(), indri::utility::IndriTimer::start(), indri::index::TermListFileIterator::startIteration(), indri::api::ParsedDocument::tags, indri::index::Index::termListFileIterator(), and indri::parse::OffsetAnnotationAnnotator::transform().
Referenced by main().
Member Data Documentation
indri::index::TermListFileIterator* FieldModifier::_docIter [private]
Referenced by _mergeData(), processFields(), and ~FieldModifier().
indri::index::Index* FieldModifier::_index [private]
Referenced by _mergeData(), and processFields().
indri::api::Parameters FieldModifier::addFields [private]
Referenced by _mergeFields(), and processFields().
bool FieldModifier::adding [private]
Referenced by _mergeFields(), and processFields().
indri::parse::FileClassEnvironment* FieldModifier::fce [private]
Referenced by processFields(), and ~FieldModifier().
indri::utility::IndriTimer FieldModifier::g_timer [private]
Referenced by processFields().
indri::api::ParsedDocument* FieldModifier::parsed [private]
Referenced by _mergeData(), and processFields().
std::vector<std::string> FieldModifier::removeNames [private]
Referenced by _mergeFields(), and processFields().
indri::api::Parameters FieldModifier::repo [private]
Referenced by _mergeFields(), and processFields().
indri::utility::Buffer FieldModifier::termBuffer [private]
Referenced by _mergeData(), and FieldModifier().
indri::parse::TagList FieldModifier::tl [private]
Referenced by _mergeData().
The documentation for this class was generated from the following file:
ModifyFields.cpp