Indri: indri::infnet::WeightedExtentOrNode Class Reference
indri::infnet::WeightedExtentOrNode Class Reference
#include <WeightedExtentOrNode.hpp>
Public Member Functions
WeightedExtentOrNode (const std::string &name, std::vector< ListIteratorNode * > &children, const std::vector< double > &weights)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
void indexChanged (indri::index::Index &index)
lemur::api::DOCID_T nextCandidateDocument ()
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
std::vector< ListIteratorNode * > _children
std::vector< double > _weights
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
Constructor & Destructor Documentation
indri::infnet::WeightedExtentOrNode::WeightedExtentOrNode (const std::string & name, std::vector< ListIteratorNode * > & children, const std::vector< double > & weights)
References _weights.
Member Function Documentation
void indri::infnet::WeightedExtentOrNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, indri::infnet::Annotator::addMatches(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::contains(), and indri::utility::greedy_vector< _Type, _Count >::end().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::WeightedExtentOrNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::WeightedExtentOrNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::WeightedExtentOrNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, indri::index::Extent::begin, and indri::index::Extent::end.
lemur::api::DOCID_T indri::infnet::WeightedExtentOrNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
void indri::infnet::WeightedExtentOrNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, _weights, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::infnet::ListIteratorNode::extents(), indri::infnet::ListIteratorNode::initpointer(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::index::Extent::weight.
Member Data Documentation
std::vector<ListIteratorNode*> indri::infnet::WeightedExtentOrNode::_children [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::WeightedExtentOrNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
std::string indri::infnet::WeightedExtentOrNode::_name [private]
Referenced by getName().
std::vector<double> indri::infnet::WeightedExtentOrNode::_weights [private]
Referenced by prepare(), and WeightedExtentOrNode().
The documentation for this class was generated from the following files:
WeightedExtentOrNode.hpp
WeightedExtentOrNode.cpp