Indri: indri::thread::UtilityThread Class Reference
indri::thread::UtilityThread Class Reference
#include <UtilityThread.hpp>
Public Member Functions
UtilityThread ()
virtual ~UtilityThread ()
virtual bool hasWork ()=0
virtual UINT64 work ()=0
virtual UINT64 initialize ()=0
virtual void deinitialize ()=0
virtual void run ()
virtual void start ()
virtual void signal ()
virtual void join ()
Private Attributes
Thread * _thread
Mutex _lock
ConditionVariable _quit
volatile bool _runThread
Constructor & Destructor Documentation
indri::thread::UtilityThread::UtilityThread ()
virtual indri::thread::UtilityThread::~UtilityThread () [inline, virtual]
Member Function Documentation
virtual void indri::thread::UtilityThread::deinitialize () [pure virtual]
Implemented in indri::collection::RepositoryLoadThread, indri::collection::RepositoryMaintenanceThread, and QueryThread.
Referenced by run().
virtual bool indri::thread::UtilityThread::hasWork () [pure virtual]
Implemented in indri::collection::RepositoryLoadThread, indri::collection::RepositoryMaintenanceThread, and QueryThread.
Referenced by run().
virtual UINT64 indri::thread::UtilityThread::initialize () [pure virtual]
Implemented in indri::collection::RepositoryLoadThread, indri::collection::RepositoryMaintenanceThread, and QueryThread.
Referenced by run().
void indri::thread::UtilityThread::join () [virtual]
References _thread, indri::thread::Thread::join(), and signal().
Referenced by indri::collection::Repository::_stopThreads().
void indri::thread::UtilityThread::run () [virtual]
References _lock, _quit, _runThread, deinitialize(), hasWork(), initialize(), indri::thread::ConditionVariable::wait(), and work().
void indri::thread::UtilityThread::signal () [virtual]
References _quit, _runThread, and indri::thread::ConditionVariable::notifyAll().
Referenced by indri::collection::Repository::_stopThreads(), and join().
void indri::thread::UtilityThread::start () [virtual]
References _runThread, _thread, and utility_thread_run().
Referenced by QueryThread::_printResults(), and indri::collection::Repository::_startThreads().
virtual UINT64 indri::thread::UtilityThread::work () [pure virtual]
Implemented in indri::collection::RepositoryLoadThread, indri::collection::RepositoryMaintenanceThread, and QueryThread.
Referenced by run().
Member Data Documentation
Mutex indri::thread::UtilityThread::_lock [private]
Referenced by run().
ConditionVariable indri::thread::UtilityThread::_quit [private]
Referenced by run(), and signal().
volatile bool indri::thread::UtilityThread::_runThread [private]
Referenced by run(), signal(), and start().
Thread* indri::thread::UtilityThread::_thread [private]
Referenced by join(), and start().
The documentation for this class was generated from the following files:
UtilityThread.hpp
UtilityThread.cpp