Indri: indri::infnet::ScoredExtentAccumulator Class Reference
indri::infnet::ScoredExtentAccumulator Class Reference
#include <ScoredExtentAccumulator.hpp>
Public Member Functions
ScoredExtentAccumulator (std::string name, BeliefNode *belief, int resultsRequested=-1)
void evaluate (lemur::api::DOCID_T documentID, int documentLength)
lemur::api::DOCID_T nextCandidateDocument ()
const std::string & getName () const
const EvaluatorNode::MResults & getResults ()
void indexChanged (indri::index::Index &index)
Private Attributes
BeliefNode * _belief
SkippingCapableNode * _skipping
std::priority_queue
< indri::api::ScoredExtentResult > _scores
std::vector
< indri::api::ScoredExtentResult > _finalScores
int _resultsRequested
std::string _name
EvaluatorNode::MResults _results
Constructor & Destructor Documentation
indri::infnet::ScoredExtentAccumulator::ScoredExtentAccumulator (std::string name, BeliefNode * belief, int resultsRequested = -1) [inline]
References _skipping, and indri::api::Parameters::instance().
Member Function Documentation
void indri::infnet::ScoredExtentAccumulator::evaluate (lemur::api::DOCID_T documentID, int documentLength) [inline, virtual]
Implements indri::infnet::EvaluatorNode.
References _belief, _resultsRequested, _scores, _skipping, indri::infnet::BeliefNode::hasMatch(), indri::infnet::BeliefNode::score(), indri::infnet::SkippingCapableNode::setThreshold(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string& indri::infnet::ScoredExtentAccumulator::getName () const [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const EvaluatorNode::MResults& indri::infnet::ScoredExtentAccumulator::getResults () [inline, virtual]
Implements indri::infnet::EvaluatorNode.
References _results, and _scores.
void indri::infnet::ScoredExtentAccumulator::indexChanged (indri::index::Index & index) [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
lemur::api::DOCID_T indri::infnet::ScoredExtentAccumulator::nextCandidateDocument () [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _belief, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
Member Data Documentation
BeliefNode* indri::infnet::ScoredExtentAccumulator::_belief [private]
Referenced by evaluate(), and nextCandidateDocument().
std::vector<indri::api::ScoredExtentResult> indri::infnet::ScoredExtentAccumulator::_finalScores [private]
std::string indri::infnet::ScoredExtentAccumulator::_name [private]
Referenced by getName().
EvaluatorNode::MResults indri::infnet::ScoredExtentAccumulator::_results [private]
Referenced by getResults().
int indri::infnet::ScoredExtentAccumulator::_resultsRequested [private]
Referenced by evaluate().
std::priority_queue<indri::api::ScoredExtentResult> indri::infnet::ScoredExtentAccumulator::_scores [private]
Referenced by evaluate(), and getResults().
SkippingCapableNode* indri::infnet::ScoredExtentAccumulator::_skipping [private]
Referenced by evaluate(), and ScoredExtentAccumulator().
The documentation for this class was generated from the following file:
ScoredExtentAccumulator.hpp