Indri: indri::lang::Copier Class Reference
indri::lang::Copier Class Reference
#include <Copier.hpp>
Public Member Functions
virtual ~Copier ()
virtual void defaultBefore (class Node *oldNode)
virtual class Node * defaultAfter (class Node *oldNode, class Node *newNode)
virtual void before (class IndexTerm *oldNode)
virtual class Node * after (class IndexTerm *oldNode, class IndexTerm *newNode)
virtual void before (class Field *oldNode)
virtual class Node * after (class Field *oldNode, class Field *newNode)
virtual void before (class ExtentInside *oldNode)
virtual class Node * after (class ExtentInside *oldNode, class ExtentInside *newNode)
virtual void before (class WeightedExtentOr *oldNode)
virtual class Node * after (class WeightedExtentOr *oldNode, class WeightedExtentOr *newNode)
virtual void before (class ExtentOr *oldNode)
virtual class Node * after (class ExtentOr *oldNode, class ExtentOr *newNode)
virtual void before (class ExtentAnd *oldNode)
virtual class Node * after (class ExtentAnd *oldNode, class ExtentAnd *newNode)
virtual void before (class BAndNode *oldNode)
virtual class Node * after (class BAndNode *oldNode, class BAndNode *newNode)
virtual void before (class UWNode *oldNode)
virtual class Node * after (class UWNode *oldNode, class UWNode *newNode)
virtual void before (class ODNode *oldNode)
virtual class Node * after (class ODNode *oldNode, class ODNode *newNode)
virtual void before (class FilReqNode *oldNode)
virtual class Node * after (class FilReqNode *oldNode, class FilReqNode *newNode)
virtual void before (class FilRejNode *oldNode)
virtual class Node * after (class FilRejNode *oldNode, class FilRejNode *newNode)
virtual void before (class FieldLessNode *oldNode)
virtual class Node * after (class FieldLessNode *oldNode, class FieldLessNode *newNode)
virtual void before (class FieldGreaterNode *oldNode)
virtual class Node * after (class FieldGreaterNode *oldNode, class FieldGreaterNode *newNode)
virtual void before (class FieldBetweenNode *oldNode)
virtual class Node * after (class FieldBetweenNode *oldNode, class FieldBetweenNode *newNode)
virtual void before (class FieldEqualsNode *oldNode)
virtual class Node * after (class FieldEqualsNode *oldNode, class FieldEqualsNode *newNode)
virtual void before (class RawScorerNode *oldNode)
virtual class Node * after (class RawScorerNode *oldNode, class RawScorerNode *newNode)
virtual void before (class TermFrequencyScorerNode *oldNode)
virtual class Node * after (class TermFrequencyScorerNode *oldNode, class TermFrequencyScorerNode *newNode)
virtual void before (class CachedFrequencyScorerNode *oldNode)
virtual class Node * after (class CachedFrequencyScorerNode *oldNode, class CachedFrequencyScorerNode *newNode)
virtual void before (class PriorNode *oldNode)
virtual class Node * after (class PriorNode *oldNode, class PriorNode *newNode)
virtual void before (class OrNode *oldNode)
virtual class Node * after (class OrNode *oldNode, class OrNode *newNode)
virtual void before (class NotNode *oldNode)
virtual class Node * after (class NotNode *oldNode, class NotNode *newNode)
virtual void before (class MaxNode *oldNode)
virtual class Node * after (class MaxNode *oldNode, class MaxNode *newNode)
virtual void before (class CombineNode *oldNode)
virtual class Node * after (class CombineNode *oldNode, class CombineNode *newNode)
virtual void before (class WAndNode *oldNode)
virtual class Node * after (class WAndNode *oldNode, class WAndNode *newNode)
virtual void before (class WSumNode *oldNode)
virtual class Node * after (class WSumNode *oldNode, class WSumNode *newNode)
virtual void before (class WeightNode *oldNode)
virtual class Node * after (class WeightNode *oldNode, class WeightNode *newNode)
virtual void before (class ExtentRestriction *oldNode)
virtual class Node * after (class ExtentRestriction *oldNode, class ExtentRestriction *newNode)
virtual void before (class FixedPassage *oldNode)
virtual class Node * after (class FixedPassage *oldNode, class FixedPassage *newNode)
virtual void before (class FilterNode *oldNode)
virtual class Node * after (class FilterNode *oldNode, class FilterNode *newNode)
virtual void before (class ListAccumulator *oldNode)
virtual class Node * after (class ListAccumulator *oldNode, class ListAccumulator *newNode)
virtual void before (class ContextCounterNode *oldNode)
virtual class Node * after (class ContextCounterNode *oldNode, class ContextCounterNode *newNode)
virtual void before (class ContextSimpleCounterNode *oldNode)
virtual class Node * after (class ContextSimpleCounterNode *oldNode, class ContextSimpleCounterNode *newNode)
virtual void before (class ScoreAccumulatorNode *oldNode)
virtual class Node * after (class ScoreAccumulatorNode *oldNode, class ScoreAccumulatorNode *newNode)
virtual void before (class AnnotatorNode *oldNode)
virtual class Node * after (class AnnotatorNode *oldNode, class AnnotatorNode *newNode)
virtual void before (class FieldWildcard *oldNode)
virtual class Node * after (class FieldWildcard *oldNode, class FieldWildcard *newNode)
virtual void before (class NestedExtentInside *oldNode)
virtual class Node * after (class NestedExtentInside *oldNode, class NestedExtentInside *newNode)
virtual void before (class NestedRawScorerNode *oldNode)
virtual class Node * after (class NestedRawScorerNode *oldNode, class NestedRawScorerNode *newNode)
virtual void before (class ExtentEnforcement *oldNode)
virtual class Node * after (class ExtentEnforcement *oldNode, class ExtentEnforcement *newNode)
virtual void before (class ContextInclusionNode *oldNode)
virtual class Node * after (class ContextInclusionNode *oldNode, class ContextInclusionNode *newNode)
virtual void before (class LengthPrior *oldNode)
virtual class Node * after (class LengthPrior *oldNode, class LengthPrior *newNode)
virtual void before (class DocumentStructureNode *oldNode)
virtual class Node * after (class DocumentStructureNode *oldNode, class DocumentStructureNode *newNode)
virtual void before (class ShrinkageScorerNode *oldNode)
virtual class Node * after (class ShrinkageScorerNode *oldNode, class ShrinkageScorerNode *newNode)
virtual void before (class ExtentDescendant *oldNode)
virtual class Node * after (class ExtentDescendant *oldNode, class ExtentDescendant *newNode)
virtual void before (class ExtentChild *oldNode)
virtual class Node * after (class ExtentChild *oldNode, class ExtentChild *newNode)
virtual void before (class ExtentParent *oldNode)
virtual class Node * after (class ExtentParent *oldNode, class ExtentParent *newNode)
virtual void before (class WildcardTerm *oldNode)
virtual class Node * after (class WildcardTerm *oldNode, class WildcardTerm *newNode)
virtual void before (class PlusNode *oldNode)
virtual class Node * after (class PlusNode *oldNode, class PlusNode *newNode)
virtual void before (class WPlusNode *oldNode)
virtual class Node * after (class WPlusNode *oldNode, class WPlusNode *newNode)
Constructor & Destructor Documentation
indri::lang::Copier::~Copier () [virtual]
Member Function Documentation
Node * indri::lang::Copier::after (class WPlusNode * oldNode, class WPlusNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class PlusNode * oldNode, class PlusNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class WildcardTerm * oldNode, class WildcardTerm * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentParent * oldNode, class ExtentParent * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentChild * oldNode, class ExtentChild * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentDescendant * oldNode, class ExtentDescendant * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ShrinkageScorerNode * oldNode, class ShrinkageScorerNode * newNode) [virtual]
Reimplemented in indri::lang::ContextCountGraphCopier, and indri::lang::NoContextCountGraphCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class DocumentStructureNode * oldNode, class DocumentStructureNode * newNode) [virtual]
Reimplemented in indri::lang::DagCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class LengthPrior * oldNode, class LengthPrior * newNode) [virtual]
Reimplemented in indri::lang::UnnecessaryNodeRemoverCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class ContextInclusionNode * oldNode, class ContextInclusionNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentEnforcement * oldNode, class ExtentEnforcement * newNode) [virtual]
Reimplemented in indri::lang::ExtentRestrictionModelAnnotatorCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class NestedRawScorerNode * oldNode, class NestedRawScorerNode * newNode) [virtual]
Reimplemented in indri::lang::ContextCountGraphCopier, indri::lang::NoContextCountGraphCopier, indri::lang::ExtentRestrictionModelAnnotatorCopier, and indri::lang::FrequencyListCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class NestedExtentInside * oldNode, class NestedExtentInside * newNode) [virtual]
Reimplemented in indri::lang::DagCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class FieldWildcard * oldNode, class FieldWildcard * newNode) [virtual]
Reimplemented in indri::lang::DagCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class AnnotatorNode * oldNode, class AnnotatorNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ScoreAccumulatorNode * oldNode, class ScoreAccumulatorNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ContextSimpleCounterNode * oldNode, class ContextSimpleCounterNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ContextCounterNode * oldNode, class ContextCounterNode * newNode) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class ListAccumulator * oldNode, class ListAccumulator * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FilterNode * oldNode, class FilterNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FixedPassage * oldNode, class FixedPassage * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentRestriction * oldNode, class ExtentRestriction * newNode) [virtual]
Reimplemented in indri::lang::NoContextCountGraphCopier, and indri::lang::ExtentRestrictionModelAnnotatorCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class WeightNode * oldNode, class WeightNode * newNode) [virtual]
Reimplemented in indri::lang::WeightFoldingCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class WSumNode * oldNode, class WSumNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class WAndNode * oldNode, class WAndNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class CombineNode * oldNode, class CombineNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class MaxNode * oldNode, class MaxNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class NotNode * oldNode, class NotNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class OrNode * oldNode, class OrNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class PriorNode * oldNode, class PriorNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class CachedFrequencyScorerNode * oldNode, class CachedFrequencyScorerNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class TermFrequencyScorerNode * oldNode, class TermFrequencyScorerNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class RawScorerNode * oldNode, class RawScorerNode * newNode) [virtual]
Reimplemented in indri::lang::ContextCountGraphCopier, indri::lang::NoContextCountGraphCopier, indri::lang::ContextCountGraphExtractor, indri::lang::ExtentRestrictionModelAnnotatorCopier, and indri::lang::FrequencyListCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class FieldEqualsNode * oldNode, class FieldEqualsNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FieldBetweenNode * oldNode, class FieldBetweenNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FieldGreaterNode * oldNode, class FieldGreaterNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FieldLessNode * oldNode, class FieldLessNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FilRejNode * oldNode, class FilRejNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class FilReqNode * oldNode, class FilReqNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ODNode * oldNode, class ODNode * newNode) [virtual]
Reimplemented in indri::lang::DagCopier, and indri::lang::UnnecessaryNodeRemoverCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class UWNode * oldNode, class UWNode * newNode) [virtual]
Reimplemented in indri::lang::DagCopier, and indri::lang::UnnecessaryNodeRemoverCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class BAndNode * oldNode, class BAndNode * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentAnd * oldNode, class ExtentAnd * newNode) [virtual]
Reimplemented in indri::lang::DagCopier, and indri::lang::UnnecessaryNodeRemoverCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentOr * oldNode, class ExtentOr * newNode) [virtual]
Reimplemented in indri::lang::DagCopier, and indri::lang::UnnecessaryNodeRemoverCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class WeightedExtentOr * oldNode, class WeightedExtentOr * newNode) [virtual]
References defaultAfter().
Node * indri::lang::Copier::after (class ExtentInside * oldNode, class ExtentInside * newNode) [virtual]
Reimplemented in indri::lang::DagCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class Field * oldNode, class Field * newNode) [virtual]
Reimplemented in indri::lang::DagCopier.
References defaultAfter().
Node * indri::lang::Copier::after (class IndexTerm * oldNode, class IndexTerm * newNode) [virtual]
Reimplemented in indri::lang::DagCopier, and indri::lang::FrequencyListCopier.
References defaultAfter().
Referenced by indri::lang::ContextInclusionNode::_copy(), indri::lang::WeightedCombinationNode::_copy(), indri::lang::UnweightedCombinationNode::_copy(), indri::lang::WildcardTerm::copy(), indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::ShrinkageScorerNode::copy(), indri::lang::DocumentStructureNode::copy(), indri::lang::LengthPrior::copy(), indri::lang::ExtentEnforcement::copy(), indri::lang::NestedRawScorerNode::copy(), indri::lang::NestedExtentInside::copy(), indri::lang::FieldWildcard::copy(), indri::lang::AnnotatorNode::copy(), indri::lang::ScoreAccumulatorNode::copy(), indri::lang::ContextSimpleCounterNode::copy(), indri::lang::ContextCounterNode::copy(), indri::lang::ListAccumulator::copy(), indri::lang::FilterNode::copy(), indri::lang::FixedPassage::copy(), indri::lang::ExtentRestriction::copy(), indri::lang::NotNode::copy(), indri::lang::PriorNode::copy(), indri::lang::CachedFrequencyScorerNode::copy(), indri::lang::TermFrequencyScorerNode::copy(), indri::lang::RawScorerNode::copy(), indri::lang::FieldEqualsNode::copy(), indri::lang::FieldBetweenNode::copy(), indri::lang::FieldGreaterNode::copy(), indri::lang::FieldLessNode::copy(), indri::lang::FilRejNode::copy(), indri::lang::FilReqNode::copy(), indri::lang::ODNode::copy(), indri::lang::UWNode::copy(), indri::lang::BAndNode::copy(), indri::lang::ExtentAnd::copy(), indri::lang::ExtentOr::copy(), indri::lang::WeightedExtentOr::copy(), indri::lang::ExtentInside::copy(), indri::lang::Field::copy(), and indri::lang::IndexTerm::copy().
void indri::lang::Copier::before (class WPlusNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class PlusNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class WildcardTerm * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ExtentParent * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ExtentChild * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ExtentDescendant * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ShrinkageScorerNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class DocumentStructureNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class LengthPrior * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ContextInclusionNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ExtentEnforcement * oldNode) [virtual]
Reimplemented in indri::lang::ExtentRestrictionModelAnnotatorCopier, and indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class NestedRawScorerNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class NestedExtentInside * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class FieldWildcard * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class AnnotatorNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ScoreAccumulatorNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ContextSimpleCounterNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ContextCounterNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class ListAccumulator * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class FilterNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class FixedPassage * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class ExtentRestriction * oldNode) [virtual]
Reimplemented in indri::lang::ExtentRestrictionModelAnnotatorCopier, and indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class WeightNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class WSumNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class WAndNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class CombineNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class MaxNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class NotNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class OrNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class PriorNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class CachedFrequencyScorerNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class TermFrequencyScorerNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class RawScorerNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class FieldEqualsNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class FieldBetweenNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class FieldGreaterNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class FieldLessNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class FilRejNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class FilReqNode * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class ODNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class UWNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class BAndNode * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class ExtentAnd * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class ExtentOr * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class WeightedExtentOr * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class ExtentInside * oldNode) [virtual]
Reimplemented in indri::lang::FrequencyListCopier.
References defaultBefore().
void indri::lang::Copier::before (class Field * oldNode) [virtual]
References defaultBefore().
void indri::lang::Copier::before (class IndexTerm * oldNode) [virtual]
References defaultBefore().
Referenced by indri::lang::ContextInclusionNode::_copy(), indri::lang::WeightedCombinationNode::_copy(), indri::lang::UnweightedCombinationNode::_copy(), indri::lang::WildcardTerm::copy(), indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::ShrinkageScorerNode::copy(), indri::lang::DocumentStructureNode::copy(), indri::lang::LengthPrior::copy(), indri::lang::ExtentEnforcement::copy(), indri::lang::NestedRawScorerNode::copy(), indri::lang::NestedExtentInside::copy(), indri::lang::FieldWildcard::copy(), indri::lang::AnnotatorNode::copy(), indri::lang::ScoreAccumulatorNode::copy(), indri::lang::ContextSimpleCounterNode::copy(), indri::lang::ContextCounterNode::copy(), indri::lang::ListAccumulator::copy(), indri::lang::FilterNode::copy(), indri::lang::FixedPassage::copy(), indri::lang::ExtentRestriction::copy(), indri::lang::NotNode::copy(), indri::lang::PriorNode::copy(), indri::lang::CachedFrequencyScorerNode::copy(), indri::lang::TermFrequencyScorerNode::copy(), indri::lang::RawScorerNode::copy(), indri::lang::FieldEqualsNode::copy(), indri::lang::FieldBetweenNode::copy(), indri::lang::FieldGreaterNode::copy(), indri::lang::FieldLessNode::copy(), indri::lang::FilRejNode::copy(), indri::lang::FilReqNode::copy(), indri::lang::ODNode::copy(), indri::lang::UWNode::copy(), indri::lang::BAndNode::copy(), indri::lang::ExtentAnd::copy(), indri::lang::ExtentOr::copy(), indri::lang::WeightedExtentOr::copy(), indri::lang::ExtentInside::copy(), indri::lang::Field::copy(), and indri::lang::IndexTerm::copy().
Node * indri::lang::Copier::defaultAfter (class Node * oldNode, class Node * newNode) [virtual]
Reimplemented in indri::lang::ContextCountGraphCopier, indri::lang::NoContextCountGraphCopier, indri::lang::ContextSimpleCountCollectorCopier, indri::lang::DagCopier, indri::lang::ExtentRestrictionModelAnnotatorCopier, indri::lang::FrequencyListCopier, indri::lang::SimpleCopier, indri::lang::UnnecessaryNodeRemoverCopier, and indri::lang::WeightFoldingCopier.
Referenced by after().
void indri::lang::Copier::defaultBefore (class Node * oldNode) [virtual]
Referenced by before().
The documentation for this class was generated from the following files:
Copier.hpp
Copier.cpp