Indri: indri::parse::ArabicStemmerTransformation Class Reference
indri::parse::ArabicStemmerTransformation Class Reference
#include <ArabicStemmerTransformation.hpp>
Public Member Functions
ArabicStemmerTransformation (indri::api::Parameters &parameters)
~ArabicStemmerTransformation ()
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
Private Member Functions
char * _getBuffer (size_t length)
const char * _getBufferEnd () const
indri::api::ParsedDocument * _restart (indri::api::ParsedDocument *document, size_t lastIndex, char *endOfStemming)
indri::api::ParsedDocument * _processTerms (indri::api::ParsedDocument *document, size_t start, char *stem, const char *end)
char * _growBuffer (size_t length, char *oldEnd)
Private Attributes
char * _stemBuffer
size_t _stemBufferSize
ObjectHandler
< indri::api::ParsedDocument > * _handler
Arabic_Stemmer_utf8 * stemmer
Constructor & Destructor Documentation
indri::parse::ArabicStemmerTransformation::ArabicStemmerTransformation (indri::api::Parameters & parameters)
References _stemBuffer, _stemBufferSize, indri::api::Parameters::get(), and stemmer.
indri::parse::ArabicStemmerTransformation::~ArabicStemmerTransformation ()
References _stemBuffer, and stemmer.
Member Function Documentation
char * indri::parse::ArabicStemmerTransformation::_getBuffer (size_t length) [private]
References _stemBuffer, and _stemBufferSize.
Referenced by _restart(), and transform().
const char * indri::parse::ArabicStemmerTransformation::_getBufferEnd () const [private]
References _stemBuffer, and _stemBufferSize.
Referenced by _restart(), and transform().
char * indri::parse::ArabicStemmerTransformation::_growBuffer (size_t length, char * oldEnd) [private]
References _stemBuffer, and _stemBufferSize.
Referenced by _restart().
indri::api::ParsedDocument * indri::parse::ArabicStemmerTransformation::_processTerms (indri::api::ParsedDocument * document, size_t start, char * stem, const char * end) [private]
References _restart(), indri::atomic::increment(), indri::utility::greedy_vector< _Type, _Count >::size(), stemmer, indri::parse::Arabic_Stemmer_utf8::stemTerm(), and indri::api::ParsedDocument::terms.
Referenced by _restart(), and transform().
indri::api::ParsedDocument * indri::parse::ArabicStemmerTransformation::_restart (indri::api::ParsedDocument * document, size_t lastIndex, char * endOfStemming) [private]
References _getBuffer(), _getBufferEnd(), _growBuffer(), _processTerms(), _stemBuffer, indri::utility::greedy_vector< _Type, _Count >::size(), STEM_MAX_WORD_LENGTH, and indri::api::ParsedDocument::terms.
Referenced by _processTerms().
void indri::parse::ArabicStemmerTransformation::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::ArabicStemmerTransformation::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::ArabicStemmerTransformation::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _getBuffer(), _getBufferEnd(), _processTerms(), indri::utility::greedy_vector< _Type, _Count >::size(), STEM_EXTRA_SPACE, STEM_MAX_WORD_LENGTH, and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
ObjectHandler<indri::api::ParsedDocument>* indri::parse::ArabicStemmerTransformation::_handler [private]
Referenced by handle(), and setHandler().
char* indri::parse::ArabicStemmerTransformation::_stemBuffer [private]
Referenced by _getBuffer(), _getBufferEnd(), _growBuffer(), _restart(), ArabicStemmerTransformation(), and ~ArabicStemmerTransformation().
size_t indri::parse::ArabicStemmerTransformation::_stemBufferSize [private]
Referenced by _getBuffer(), _getBufferEnd(), _growBuffer(), and ArabicStemmerTransformation().
Arabic_Stemmer_utf8* indri::parse::ArabicStemmerTransformation::stemmer [private]
Referenced by _processTerms(), ArabicStemmerTransformation(), and ~ArabicStemmerTransformation().
The documentation for this class was generated from the following files:
ArabicStemmerTransformation.hpp
ArabicStemmerTransformation.cpp