Indri: indri::lang::FieldBetweenNode Class Reference
indri::lang::FieldBetweenNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FieldBetweenNode (RawExtentNode *field, INT64 low, INT64 high)
FieldBetweenNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
INT64 getLow () const
INT64 getHigh () const
RawExtentNode * getField ()
bool operator== (Node &node)
Node * copy (Copier &copier)
void walk (Walker &walker)
void pack (Packer &packer)
Private Attributes
RawExtentNode * _field
INT64 _low
INT64 _high
Constructor & Destructor Documentation
indri::lang::FieldBetweenNode::FieldBetweenNode (RawExtentNode * field, INT64 low, INT64 high) [inline]
Referenced by copy().
indri::lang::FieldBetweenNode::FieldBetweenNode (Unpacker & unpacker) [inline]
References _field, _high, _low, indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getRawExtentNode().
Member Function Documentation
Node* indri::lang::FieldBetweenNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _field, _high, _low, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and FieldBetweenNode().
RawExtentNode* indri::lang::FieldBetweenNode::getField () [inline]
References _field.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
INT64 indri::lang::FieldBetweenNode::getHigh () const [inline]
References _high.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
INT64 indri::lang::FieldBetweenNode::getLow () const [inline]
References _low.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
UINT64 indri::lang::FieldBetweenNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _field, _high, _low, and indri::lang::Node::hashCode().
bool indri::lang::FieldBetweenNode::operator== (Node & node) [inline]
References _field, _high, _low, getField(), getHigh(), and getLow().
void indri::lang::FieldBetweenNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _field, _high, _low, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::FieldBetweenNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _field, _high, _low, and indri::lang::Node::queryText().
std::string indri::lang::FieldBetweenNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FieldBetweenNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _field, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
RawExtentNode* indri::lang::FieldBetweenNode::_field [private]
Referenced by copy(), FieldBetweenNode(), getField(), hashCode(), operator==(), pack(), queryText(), and walk().
INT64 indri::lang::FieldBetweenNode::_high [private]
Referenced by copy(), FieldBetweenNode(), getHigh(), hashCode(), operator==(), pack(), and queryText().
INT64 indri::lang::FieldBetweenNode::_low [private]
Referenced by copy(), FieldBetweenNode(), getLow(), hashCode(), operator==(), pack(), and queryText().
The documentation for this class was generated from the following file:
QuerySpec.hpp