Indri: indri::lang::ExtentEnforcement Class Reference
indri::lang::ExtentEnforcement Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ExtentEnforcement (Unpacker &unpacker)
ExtentEnforcement (ScoredExtentNode *child, RawExtentNode *field)
std::string typeName () const
UINT64 hashCode () const
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::ExtentEnforcement::ExtentEnforcement (Unpacker & unpacker) [inline]
Referenced by copy().
indri::lang::ExtentEnforcement::ExtentEnforcement (ScoredExtentNode * child, RawExtentNode * field) [inline]
Member Function Documentation
Node* indri::lang::ExtentEnforcement::copy (Copier & copier) [inline, virtual]
Reimplemented from indri::lang::ExtentRestriction.
References indri::lang::ExtentRestriction::_child, indri::lang::ExtentRestriction::_field, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), ExtentEnforcement(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
UINT64 indri::lang::ExtentEnforcement::hashCode () const [inline, virtual]
Reimplemented from indri::lang::ExtentRestriction.
References indri::lang::ExtentRestriction::_child, indri::lang::ExtentRestriction::_field, and indri::lang::Node::hashCode().
std::string indri::lang::ExtentEnforcement::typeName () const [inline, virtual]
Reimplemented from indri::lang::ExtentRestriction.
The documentation for this class was generated from the following file:
QuerySpec.hpp