Indri: NexiParser Class Reference
NexiParser Class Reference
#include <NexiParser.hpp>
Public Member Functions
void init (NexiLexer *lexer)
void setShrinkage (bool shrink)
void initializeASTFactory (ANTLR_USE_NAMESPACE(antlr) ASTFactory &factory)
NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer &tokenBuf)
NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenStream &lexer)
NexiParser (const ANTLR_USE_NAMESPACE(antlr) ParserSharedInputState &state)
int getNumTokens () const
const char * getTokenName (int type) const
const char *const * getTokenNames () const
indri::lang::ScoredExtentNode * query ()
indri::lang::NestedExtentInside * path ()
indri::lang::RawExtentNode * field ()
indri::lang::ScoredExtentNode * clause ()
indri::lang::ScoredExtentNode * termList ()
indri::lang::ScoredExtentNode * term ()
indri::lang::ScoredExtentNode * filter ()
indri::lang::UnweightedCombinationNode * logical ()
indri::lang::ScoredExtentNode * aboutClause ()
indri::lang::RawExtentNode * arithmeticClause ()
indri::lang::ScoredExtentNode * filterParens ()
INT64 number ()
indri::lang::ScoredExtentNode * unrestrictedTerm ()
indri::lang::RawExtentNode * rawText ()
indri::lang::ODNode * odNode ()
ANTLR_USE_NAMESPACE (antlr) RefAST getAST()
Protected Member Functions
NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer &tokenBuf, int k)
NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenStream &lexer, int k)
ANTLR_USE_NAMESPACE (antlr) RefAST returnAST
Static Private Member Functions
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_0
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_1
Private Attributes
std::vector< indri::lang::Node * > _nodes
indri::utility::VectorDeleter
< indri::lang::Node * > _deleter
bool _shrinkage
Static Private Attributes
static const char * tokenNames []
static const int NUM_TOKENS = 44
static const unsigned long _tokenSet_0_data_ [] = { 6358288UL, 2UL, 0UL, 0UL }
static const unsigned long _tokenSet_1_data_ []
Constructor & Destructor Documentation
NexiParser::NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer & tokenBuf, int k) [protected]
NexiParser::NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer & tokenBuf)
NexiParser::NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenStream & lexer, int k) [protected]
NexiParser::NexiParser (ANTLR_USE_NAMESPACE(antlr) TokenStream & lexer)
NexiParser::NexiParser (const ANTLR_USE_NAMESPACE(antlr) ParserSharedInputState & state)
Member Function Documentation
indri::lang::ScoredExtentNode * NexiParser::aboutClause ()
References _nodes, ABOUT, indri::lang::UnweightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, field(), indri::lang::ExtentInside::getInner(), O_PAREN, path(), indri::lang::ExtentInside::setInner(), SLASH, and termList().
Referenced by filter().
static const NexiParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const NexiParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
NexiParser::ANTLR_USE_NAMESPACE (antlr) [protected]
NexiParser::ANTLR_USE_NAMESPACE (antlr) [inline]
Referenced by aboutClause(), arithmeticClause(), clause(), field(), filter(), logical(), number(), odNode(), path(), query(), rawText(), term(), termList(), and unrestrictedTerm().
indri::lang::RawExtentNode * NexiParser::arithmeticClause ()
References _nodes, ANTLR_USE_NAMESPACE(), EQUALS, field(), indri::lang::ExtentInside::getInner(), GREATER, GREATEREQ, LESS, LESSEQ, number(), path(), indri::lang::ExtentInside::setInner(), and TERM.
Referenced by filter().
indri::lang::ScoredExtentNode * NexiParser::clause ()
References indri::lang::UnweightedCombinationNode::addChild(), AND, ANTLR_USE_NAMESPACE(), C_PAREN, C_SQUARE, filter(), logical(), and OR.
Referenced by filterParens(), and query().
indri::lang::RawExtentNode * NexiParser::field ()
References _nodes, indri::lang::ExtentOr::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, O_PAREN, TERM, and WILD.
Referenced by aboutClause(), arithmeticClause(), path(), and query().
indri::lang::ScoredExtentNode * NexiParser::filter ()
References _nodes, _shrinkage, ABOUT, aboutClause(), indri::lang::UnweightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), arithmeticClause(), filterParens(), and O_PAREN.
Referenced by clause().
indri::lang::ScoredExtentNode * NexiParser::filterParens ()
References C_PAREN, clause(), and O_PAREN.
Referenced by filter().
int NexiParser::getNumTokens () const [inline]
References NUM_TOKENS.
const char* NexiParser::getTokenName (int type) const [inline]
References tokenNames.
const char* const* NexiParser::getTokenNames () const [inline]
References tokenNames.
void NexiParser::init (NexiLexer * lexer) [inline]
References indri::utility::VectorDeleter< VectorType >::setVector().
void NexiParser::initializeASTFactory (ANTLR_USE_NAMESPACE(antlr) ASTFactory & factory)
indri::lang::UnweightedCombinationNode * NexiParser::logical ()
References _nodes, AND, ANTLR_USE_NAMESPACE(), and OR.
Referenced by clause().
INT64 NexiParser::number ()
References ANTLR_USE_NAMESPACE(), NUMBER, and string_to_i64().
Referenced by arithmeticClause().
indri::lang::ODNode * NexiParser::odNode ()
References _nodes, indri::lang::ODNode::addChild(), ANTLR_USE_NAMESPACE(), and rawText().
Referenced by unrestrictedTerm().
indri::lang::NestedExtentInside * NexiParser::path ()
References _nodes, ANTLR_USE_NAMESPACE(), field(), O_PAREN, indri::lang::ExtentInside::setInner(), SLASH, TERM, and WILD.
Referenced by aboutClause(), arithmeticClause(), and query().
indri::lang::ScoredExtentNode * NexiParser::query ()
References _nodes, ABOUT, indri::lang::ContextInclusionNode::addChild(), ANTLR_USE_NAMESPACE(), C_SQUARE, clause(), DBL_QUOTE, field(), FLOAT, indri::lang::ExtentInside::getInner(), MINUS, NUMBER, O_SQUARE, path(), PLUS, indri::lang::ExtentInside::setInner(), SLASH, TERM, and termList().
indri::lang::RawExtentNode * NexiParser::rawText ()
References _nodes, ABOUT, ANTLR_USE_NAMESPACE(), FLOAT, NUMBER, and TERM.
Referenced by odNode(), and unrestrictedTerm().
void NexiParser::setShrinkage (bool shrink) [inline]
indri::lang::ScoredExtentNode * NexiParser::term ()
References _nodes, ABOUT, ANTLR_USE_NAMESPACE(), DBL_QUOTE, FLOAT, MINUS, NUMBER, PLUS, indri::lang::NotNode::setChild(), TERM, and unrestrictedTerm().
Referenced by termList().
indri::lang::ScoredExtentNode * NexiParser::termList ()
References _nodes, ABOUT, indri::lang::UnweightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, DBL_QUOTE, FLOAT, MINUS, NUMBER, PLUS, TERM, and term().
Referenced by aboutClause(), and query().
indri::lang::ScoredExtentNode * NexiParser::unrestrictedTerm ()
References _nodes, _shrinkage, ABOUT, ANTLR_USE_NAMESPACE(), DBL_QUOTE, FLOAT, NUMBER, odNode(), rawText(), and TERM.
Referenced by term().
Member Data Documentation
indri::utility::VectorDeleter<indri::lang::Node*> NexiParser::_deleter [private]
std::vector<indri::lang::Node*> NexiParser::_nodes [private]
Referenced by aboutClause(), arithmeticClause(), field(), filter(), logical(), odNode(), path(), query(), rawText(), term(), termList(), and unrestrictedTerm().
bool NexiParser::_shrinkage [private]
Referenced by filter(), and unrestrictedTerm().
const unsigned long NexiParser::_tokenSet_0_data_ = { 6358288UL, 2UL, 0UL, 0UL } [static, private]
const unsigned long NexiParser::_tokenSet_1_data_[] [static, private]
const int NexiParser::NUM_TOKENS = 44 [static, private]
Referenced by getNumTokens().
const char * NexiParser::tokenNames [static, private]
Referenced by getTokenName(), and getTokenNames().
The documentation for this class was generated from the following files:
NexiParser.hpp
NexiParser.cpp