Indri: indri::index::TermListFileIterator Class Reference
indri::index::TermListFileIterator Class Reference
#include <TermListFileIterator.hpp>
Public Member Functions
virtual ~TermListFileIterator ()
virtual void startIteration ()=0
virtual bool nextEntry ()=0
virtual bool nextEntry (lemur::api::DOCID_T documentID)=0
virtual bool finished ()=0
virtual TermList * currentEntry ()=0
Constructor & Destructor Documentation
virtual indri::index::TermListFileIterator::~TermListFileIterator () [inline, virtual]
Member Function Documentation
virtual TermList* indri::index::TermListFileIterator::currentEntry () [pure virtual]
Implemented in indri::index::DiskTermListFileIterator, and indri::index::MemoryIndexTermListFileIterator.
Referenced by FieldModifier::_mergeData(), indri::index::IndexWriter::_writeDirectLists(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::DocumentStructureHolderNode::prepare(), and validate().
virtual bool indri::index::TermListFileIterator::finished () [pure virtual]
Implemented in indri::index::DiskTermListFileIterator, and indri::index::MemoryIndexTermListFileIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), and validate().
virtual bool indri::index::TermListFileIterator::nextEntry (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::index::DiskTermListFileIterator, and indri::index::MemoryIndexTermListFileIterator.
virtual bool indri::index::TermListFileIterator::nextEntry () [pure virtual]
Implemented in indri::index::DiskTermListFileIterator, and indri::index::MemoryIndexTermListFileIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::DocumentStructureHolderNode::prepare(), FieldModifier::processFields(), and validate().
virtual void indri::index::TermListFileIterator::startIteration () [pure virtual]
Implemented in indri::index::DiskTermListFileIterator, and indri::index::MemoryIndexTermListFileIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::infnet::FieldWildcardNode::indexChanged(), indri::infnet::DocumentStructureHolderNode::indexChanged(), FieldModifier::processFields(), and validate().
The documentation for this class was generated from the following file:
TermListFileIterator.hpp