Indri: indri::index::TermRecorder Class Reference
indri::index::TermRecorder Class Reference
#include <TermRecorder.hpp>
Classes
struct less
Public Member Functions
void add (int sequence, const char *term)
void sort ()
void buildMap (std::vector< lemur::api::TERMID_T > &map, TermRecorder &other, std::vector< std::pair< const char *, lemur::api::TERMID_T > > *missing=0)
std::vector< std::pair< size_t,
lemur::api::TERMID_T > > & pairs ()
indri::utility::Buffer & buffer ()
int memorySize ()
Private Attributes
indri::utility::Buffer _buffer
std::vector< std::pair< size_t,
lemur::api::TERMID_T > > _pairs
Member Function Documentation
void indri::index::TermRecorder::add (int sequence, const char * term) [inline]
References _buffer, _pairs, indri::utility::Buffer::front(), and indri::utility::Buffer::write().
Referenced by indri::index::IndexWriter::_storeMatchInformation(), and indri::index::IndexWriter::_writeDirectLists().
indri::utility::Buffer& indri::index::TermRecorder::buffer () [inline]
References _buffer.
Referenced by indri::index::IndexWriter::_buildTermTranslator().
void indri::index::TermRecorder::buildMap (std::vector< lemur::api::TERMID_T > & map, TermRecorder & other, std::vector< std::pair< const char *, lemur::api::TERMID_T > > * missing = 0) [inline]
References _buffer, _pairs, and indri::utility::Buffer::front().
int indri::index::TermRecorder::memorySize () [inline]
References _buffer, _pairs, and indri::utility::Buffer::position().
std::vector< std::pair<size_t, lemur::api::TERMID_T> >& indri::index::TermRecorder::pairs () [inline]
References _pairs.
Referenced by indri::index::IndexWriter::_buildTermTranslator().
void indri::index::TermRecorder::sort () [inline]
References _buffer, _pairs, and indri::utility::Buffer::front().
Referenced by indri::index::IndexWriter::_buildTermTranslator().
Member Data Documentation
indri::utility::Buffer indri::index::TermRecorder::_buffer [private]
Referenced by add(), buffer(), buildMap(), memorySize(), and sort().
std::vector< std::pair<size_t, lemur::api::TERMID_T> > indri::index::TermRecorder::_pairs [private]
Referenced by add(), buildMap(), memorySize(), pairs(), and sort().
The documentation for this class was generated from the following file:
TermRecorder.hpp