Indri: indri::index::CombinedVocabularyIterator Class Reference
indri::index::CombinedVocabularyIterator Class Reference
#include <CombinedVocabularyIterator.hpp>
Public Member Functions
CombinedVocabularyIterator (VocabularyIterator *first, VocabularyIterator *second, int secondBase)
~CombinedVocabularyIterator ()
void startIteration ()
bool nextEntry ()
bool nextEntry (const char *skipTo)
DiskTermData * currentEntry ()
bool finished ()
Private Attributes
VocabularyIterator * _first
VocabularyIterator * _second
int _secondBase
bool _finished
bool _usingSecond
Constructor & Destructor Documentation
indri::index::CombinedVocabularyIterator::CombinedVocabularyIterator (VocabularyIterator * first, VocabularyIterator * second, int secondBase)
indri::index::CombinedVocabularyIterator::~CombinedVocabularyIterator ()
References _first, and _second.
Member Function Documentation
indri::index::DiskTermData * indri::index::CombinedVocabularyIterator::currentEntry () [virtual]
Implements indri::index::VocabularyIterator.
References _finished, _first, _second, _usingSecond, and indri::index::VocabularyIterator::currentEntry().
bool indri::index::CombinedVocabularyIterator::finished () [virtual]
Implements indri::index::VocabularyIterator.
References _second, _usingSecond, and indri::index::VocabularyIterator::finished().
bool indri::index::CombinedVocabularyIterator::nextEntry (const char * skipTo) [virtual]
Implements indri::index::VocabularyIterator.
References _first, _second, _secondBase, _usingSecond, indri::index::VocabularyIterator::currentEntry(), indri::index::VocabularyIterator::nextEntry(), indri::index::VocabularyIterator::startIteration(), and indri::index::DiskTermData::termID.
bool indri::index::CombinedVocabularyIterator::nextEntry () [virtual]
Implements indri::index::VocabularyIterator.
References _first, _second, _secondBase, _usingSecond, indri::index::VocabularyIterator::currentEntry(), indri::index::VocabularyIterator::nextEntry(), indri::index::VocabularyIterator::startIteration(), and indri::index::DiskTermData::termID.
void indri::index::CombinedVocabularyIterator::startIteration () [virtual]
Implements indri::index::VocabularyIterator.
References _finished, _first, _second, _usingSecond, indri::index::VocabularyIterator::finished(), and indri::index::VocabularyIterator::startIteration().
Member Data Documentation
bool indri::index::CombinedVocabularyIterator::_finished [private]
Referenced by currentEntry(), and startIteration().
VocabularyIterator* indri::index::CombinedVocabularyIterator::_first [private]
Referenced by currentEntry(), nextEntry(), startIteration(), and ~CombinedVocabularyIterator().
VocabularyIterator* indri::index::CombinedVocabularyIterator::_second [private]
Referenced by currentEntry(), finished(), nextEntry(), startIteration(), and ~CombinedVocabularyIterator().
int indri::index::CombinedVocabularyIterator::_secondBase [private]
Referenced by nextEntry().
bool indri::index::CombinedVocabularyIterator::_usingSecond [private]
Referenced by currentEntry(), finished(), nextEntry(), and startIteration().
The documentation for this class was generated from the following files:
CombinedVocabularyIterator.hpp
CombinedVocabularyIterator.cpp