Indri: indri::parse::Porter_Stemmer Class Reference
indri::parse::Porter_Stemmer Class Reference
#include <Porter_Stemmer.hpp>
Public Member Functions
int porter_stem (char *p, int i, int j)
stem a term using the Porter algorithm. Performs case normalization on its input argument.
Private Member Functions
bool cons (int i)
int m ()
bool vowelinstem ()
bool doublec (int j)
bool cvc (int i)
bool ends (const char *s)
void setto (const char *s)
void r (const char *s)
void step1ab ()
void step1c ()
void step2 ()
void step3 ()
void step4 ()
void step5 ()
Private Attributes
indri::thread::Mutex _stemLock
char * b
int k
int k0
int j
Member Function Documentation
bool indri::parse::Porter_Stemmer::cons (int i) [private]
References b, and k0.
Referenced by cvc(), doublec(), m(), and vowelinstem().
bool indri::parse::Porter_Stemmer::cvc (int i) [private]
References b, cons(), and k0.
Referenced by step1ab(), and step5().
bool indri::parse::Porter_Stemmer::doublec (int j) [private]
References b, cons(), and k0.
Referenced by step1ab(), and step5().
bool indri::parse::Porter_Stemmer::ends (const char * s) [private]
References b, j, k, and k0.
Referenced by step1ab(), step1c(), step2(), step3(), and step4().
int indri::parse::Porter_Stemmer::m () [private]
References cons(), j, and k0.
Referenced by r(), step1ab(), step4(), and step5().
int indri::parse::Porter_Stemmer::porter_stem (char * p, int i, int j)
stem a term using the Porter algorithm. Performs case normalization on its input argument.
Parameters:
p the term to stem
i the starting index to stem from (typically 0).
j the ending index (inclusive) to stem to (typically the last character of the string).
Returns:
the new end point of the string.
References _stemLock, b, k, k0, step1ab(), step1c(), step2(), step3(), step4(), and step5().
Referenced by indri::parse::PorterStemmerTransformation::transform().
void indri::parse::Porter_Stemmer::r (const char * s) [private]
References m(), and setto().
Referenced by step2(), and step3().
void indri::parse::Porter_Stemmer::setto (const char * s) [private]
References b, j, and k.
Referenced by r(), and step1ab().
void indri::parse::Porter_Stemmer::step1ab () [private]
References b, cvc(), doublec(), ends(), j, k, m(), setto(), and vowelinstem().
Referenced by porter_stem().
void indri::parse::Porter_Stemmer::step1c () [private]
References b, ends(), k, and vowelinstem().
Referenced by porter_stem().
void indri::parse::Porter_Stemmer::step2 () [private]
References b, ends(), k, and r().
Referenced by porter_stem().
void indri::parse::Porter_Stemmer::step3 () [private]
References b, ends(), k, and r().
Referenced by porter_stem().
void indri::parse::Porter_Stemmer::step4 () [private]
References b, ends(), j, k, and m().
Referenced by porter_stem().
void indri::parse::Porter_Stemmer::step5 () [private]
References b, cvc(), doublec(), j, k, and m().
Referenced by porter_stem().
bool indri::parse::Porter_Stemmer::vowelinstem () [private]
References cons(), j, and k0.
Referenced by step1ab(), and step1c().
Member Data Documentation
indri::thread::Mutex indri::parse::Porter_Stemmer::_stemLock [private]
Referenced by porter_stem().
char* indri::parse::Porter_Stemmer::b [private]
Referenced by cons(), cvc(), doublec(), ends(), porter_stem(), setto(), step1ab(), step1c(), step2(), step3(), step4(), and step5().
int indri::parse::Porter_Stemmer::j [private]
Referenced by ends(), m(), setto(), step1ab(), step4(), step5(), and vowelinstem().
int indri::parse::Porter_Stemmer::k [private]
Referenced by ends(), porter_stem(), setto(), step1ab(), step1c(), step2(), step3(), step4(), and step5().
int indri::parse::Porter_Stemmer::k0 [private]
Referenced by cons(), cvc(), doublec(), ends(), m(), porter_stem(), and vowelinstem().
The documentation for this class was generated from the following files:
Porter_Stemmer.hpp
Porter_Stemmer.cpp