Indri: indri::infnet::NullListNode Class Reference
indri::infnet::NullListNode Class Reference
#include <NullListNode.hpp>
Public Member Functions
NullListNode (const std::string &name, bool stopword)
bool isStopword () const
const std::string & getName () const
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
bool _stopword
Constructor & Destructor Documentation
indri::infnet::NullListNode::NullListNode (const std::string & name, bool stopword)
Member Function Documentation
void indri::infnet::NullListNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::NullListNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::NullListNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::NullListNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
bool indri::infnet::NullListNode::isStopword () const
References _stopword.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and inferencenetworkbuilder_is_stopword().
lemur::api::DOCID_T indri::infnet::NullListNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
void indri::infnet::NullListNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References indri::infnet::ListIteratorNode::initpointer().
Member Data Documentation
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::NullListNode::_extents [private]
Referenced by extents().
std::string indri::infnet::NullListNode::_name [private]
Referenced by getName().
bool indri::infnet::NullListNode::_stopword [private]
Referenced by isStopword().
The documentation for this class was generated from the following files:
NullListNode.hpp
NullListNode.cpp