Indri: indri::index::Index Class Reference
indri::index::Index Class Reference
#include <Index.hpp>
Classes
struct FieldDescription
Field data.
Public Member Functions
virtual ~Index ()
virtual void close ()=0
virtual lemur::api::DOCID_T documentBase ()=0
virtual lemur::api::DOCID_T documentMaximum ()=0
The documentMaximum is at least one greater than the largest documentID used in this index.
virtual lemur::api::TERMID_T term (const char *term)=0
virtual lemur::api::TERMID_T term (const std::string &term)=0
virtual std::string term (lemur::api::TERMID_T termID)=0
virtual int field (const char *fieldName)=0
virtual int field (const std::string &fieldName)=0
virtual std::string field (int fieldID)=0
virtual int documentLength (lemur::api::DOCID_T documentID)=0
virtual UINT64 documentCount ()=0
virtual UINT64 documentCount (const std::string &term)=0
virtual UINT64 uniqueTermCount ()=0
virtual UINT64 termCount (const std::string &term)=0
virtual UINT64 termCount ()=0
virtual UINT64 fieldTermCount (const std::string &field)=0
virtual UINT64 fieldTermCount (const std::string &field, const std::string &term)=0
virtual UINT64 fieldDocumentCount (const std::string &field)=0
virtual UINT64 fieldDocumentCount (const std::string &field, const std::string &term)=0
virtual DocListIterator * docListIterator (lemur::api::TERMID_T termID)=0
virtual DocListIterator * docListIterator (const std::string &term)=0
virtual DocListFileIterator * docListFileIterator ()=0
virtual DocExtentListIterator * fieldListIterator (int fieldID)=0
virtual DocExtentListIterator * fieldListIterator (const std::string &field)=0
virtual const TermList * termList (lemur::api::DOCID_T documentID)=0
virtual TermListFileIterator * termListFileIterator ()=0
virtual DocumentDataIterator * documentDataIterator ()=0
virtual VocabularyIterator * frequentVocabularyIterator ()=0
virtual VocabularyIterator * infrequentVocabularyIterator ()=0
virtual VocabularyIterator * vocabularyIterator ()=0
virtual indri::thread::Lockable * iteratorLock ()=0
virtual indri::thread::Lockable * statisticsLock ()=0
Constructor & Destructor Documentation
virtual indri::index::Index::~Index () [inline, virtual]
Member Function Documentation
virtual void indri::index::Index::close () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual DocListFileIterator* indri::index::Index::docListFileIterator () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by print_invfile(), and indri::index::WriterIndexContext::WriterIndexContext().
virtual DocListIterator* indri::index::Index::docListIterator (const std::string & term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual DocListIterator* indri::index::Index::docListIterator (lemur::api::TERMID_T termID) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::InferenceNetwork::_indexChanged(), print_term_counts(), and print_term_positions().
virtual lemur::api::DOCID_T indri::index::Index::documentBase () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::InferenceNetwork::_evaluateIndex(), and indri::index::IndexWriter::_writeDirectLists().
virtual UINT64 indri::index::Index::documentCount (const std::string & term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual UINT64 indri::index::Index::documentCount () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::ContextSimpleCountAccumulator::_computeCounts(), indri::infnet::ContextCountAccumulator::indexChanged(), print_invfile(), print_vocabulary(), FieldModifier::processFields(), and validate().
virtual DocumentDataIterator* indri::index::Index::documentDataIterator () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::index::IndexWriter::_writeDirectLists().
virtual int indri::index::Index::documentLength (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::infnet::InferenceNetwork::_evaluateDocument(), indri::server::LocalQueryServer::documentLength(), print_field_positions(), print_term_counts(), print_term_positions(), and validate().
virtual lemur::api::DOCID_T indri::index::Index::documentMaximum () [pure virtual]
The documentMaximum is at least one greater than the largest documentID used in this index.
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::collection::Repository::_addMemoryIndex(), indri::infnet::InferenceNetwork::_evaluateIndex(), indri::infnet::ContextSimpleCountAccumulator::indexChanged(), indri::infnet::FieldWildcardNode::prepare(), and indri::infnet::DocumentStructureHolderNode::prepare().
virtual std::string indri::index::Index::field (int fieldID) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual int indri::index::Index::field (const std::string & fieldName) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual int indri::index::Index::field (const char * fieldName) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::index::DocumentStructure::_constructNodePath(), FieldModifier::_mergeData(), indri::index::DocumentStructure::fieldId(), and indri::infnet::ShrinkageBeliefNode::indexChanged().
virtual UINT64 indri::index::Index::fieldDocumentCount (const std::string & field, const std::string & term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual UINT64 indri::index::Index::fieldDocumentCount (const std::string & field) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::ContextSimpleCountAccumulator::_computeCounts().
virtual DocExtentListIterator* indri::index::Index::fieldListIterator (const std::string & field) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual DocExtentListIterator* indri::index::Index::fieldListIterator (int fieldID) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::InferenceNetwork::_indexChanged(), and print_field_positions().
virtual UINT64 indri::index::Index::fieldTermCount (const std::string & field, const std::string & term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual UINT64 indri::index::Index::fieldTermCount (const std::string & field) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::ContextSimpleCountAccumulator::_computeCounts().
virtual VocabularyIterator* indri::index::Index::frequentVocabularyIterator () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::index::IndexWriter::_writeDirectLists().
virtual VocabularyIterator* indri::index::Index::infrequentVocabularyIterator () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual indri::thread::Lockable* indri::index::Index::iteratorLock () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::InferenceNetwork::evaluate(), print_field_positions(), print_term_counts(), print_term_positions(), indri::index::WriterIndexContext::WriterIndexContext(), and indri::index::WriterIndexContext::~WriterIndexContext().
virtual indri::thread::Lockable* indri::index::Index::statisticsLock () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::server::LocalQueryServer::documentLength(), indri::server::LocalQueryServer::documentVectors(), indri::infnet::InferenceNetwork::evaluate(), indri::server::LocalQueryServer::termID(), and indri::server::LocalQueryServer::termName().
virtual std::string indri::index::Index::term (lemur::api::TERMID_T termID) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual lemur::api::TERMID_T indri::index::Index::term (const std::string & term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual lemur::api::TERMID_T indri::index::Index::term (const char * term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::server::LocalQueryServer::termID(), and indri::server::LocalQueryServer::termName().
virtual UINT64 indri::index::Index::termCount () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
virtual UINT64 indri::index::Index::termCount (const std::string & term) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::ContextSimpleCountAccumulator::_computeCounts(), indri::infnet::ContextCountAccumulator::indexChanged(), print_invfile(), and print_vocabulary().
virtual const TermList* indri::index::Index::termList (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::server::LocalQueryServer::documentVectors(), indri::server::LocalQueryServer::pathNames(), and validate().
virtual TermListFileIterator* indri::index::Index::termListFileIterator () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::infnet::FieldWildcardNode::indexChanged(), indri::infnet::DocumentStructureHolderNode::indexChanged(), FieldModifier::processFields(), and validate().
virtual UINT64 indri::index::Index::uniqueTermCount () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::index::IndexWriter::_buildTermTranslator(), indri::collection::Repository::_mergeMemory(), and print_repository_stats().
virtual VocabularyIterator* indri::index::Index::vocabularyIterator () [pure virtual]
Implemented in indri::index::DiskIndex, and indri::index::MemoryIndex.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and print_vocabulary().
The documentation for this class was generated from the following file:
Index.hpp