Indri: indri::lang::NotNode Class Reference
indri::lang::NotNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
NotNode ()
NotNode (ScoredExtentNode *child)
NotNode (Unpacker &unpacker)
std::string typeName () const
ScoredExtentNode * getChild ()
void setChild (ScoredExtentNode *child)
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
void pack (Packer &packer)
Node * copy (Copier &copier)
Private Attributes
ScoredExtentNode * _child
Constructor & Destructor Documentation
indri::lang::NotNode::NotNode () [inline]
References _child.
Referenced by copy().
indri::lang::NotNode::NotNode (ScoredExtentNode * child) [inline]
References _child.
indri::lang::NotNode::NotNode (Unpacker & unpacker) [inline]
References _child, and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
Node* indri::lang::NotNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _child, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), indri::lang::Node::nodeName(), NotNode(), and indri::lang::Node::setNodeName().
ScoredExtentNode* indri::lang::NotNode::getChild () [inline]
References _child.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::NotNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _child, and indri::lang::Node::hashCode().
void indri::lang::NotNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _child, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::NotNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _child, and indri::lang::Node::queryText().
void indri::lang::NotNode::setChild (ScoredExtentNode * child) [inline]
References _child.
Referenced by QueryParser::notNode(), and NexiParser::term().
std::string indri::lang::NotNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::NotNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _child, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::NotNode::_child [private]
Referenced by copy(), getChild(), hashCode(), NotNode(), pack(), queryText(), setChild(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp