Indri: QueryLexer Class Reference
QueryLexer Class Reference
#include <QueryLexer.hpp>
Public Member Functions
void init ()
void setNumbers (bool f)
bool getCaseSensitiveLiterals () const
QueryLexer (ANTLR_USE_NAMESPACE(std) istream &in)
QueryLexer (ANTLR_USE_NAMESPACE(antlr) InputBuffer &ib)
QueryLexer (const ANTLR_USE_NAMESPACE(antlr) LexerSharedInputState &state)
ANTLR_USE_NAMESPACE (antlr) RefToken nextToken()
void mSTAR (bool _createToken)
void mO_PAREN (bool _createToken)
void mC_PAREN (bool _createToken)
void mO_ANGLE (bool _createToken)
void mC_ANGLE (bool _createToken)
void mO_SQUARE (bool _createToken)
void mC_SQUARE (bool _createToken)
void mO_BRACE (bool _createToken)
void mC_BRACE (bool _createToken)
void mDBL_QUOTE (bool _createToken)
void mQUOTE (bool _createToken)
void mDOT (bool _createToken)
void mCOMMA (bool _createToken)
void mSLASH (bool _createToken)
void mB_SLASH (bool _createToken)
void mDASH (bool _createToken)
void mSPACE_DASH (bool _createToken)
void mCOLON (bool _createToken)
void mTERM (bool _createToken)
void mOPERATOR (bool _createToken)
void mJUNK (bool _createToken)
Protected Member Functions
void mTAB (bool _createToken)
void mCR (bool _createToken)
void mLF (bool _createToken)
void mSPACE (bool _createToken)
void mHIGH_CHAR (bool _createToken)
void mDIGIT (bool _createToken)
void mASCII_LETTER (bool _createToken)
void mSAFE_LETTER (bool _createToken)
void mSAFE_CHAR (bool _createToken)
void mBASESIXFOUR_CHAR (bool _createToken)
void mTEXT_TERM (bool _createToken)
void mNUMBER (bool _createToken)
void mFLOAT (bool _createToken)
void mENCODED_QUOTED_TERM (bool _createToken)
void mENCODED_TERM (bool _createToken)
Private Member Functions
void initLiterals ()
Static Private Member Functions
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_0
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_1
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_2
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_3
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_4
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_5
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_6
Private Attributes
bool _numbers
Static Private Attributes
static const unsigned long _tokenSet_0_data_ [] = { 0UL, 67043328UL, 2281701374UL, 134217726UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL }
static const unsigned long _tokenSet_1_data_ []
static const unsigned long _tokenSet_2_data_ []
static const unsigned long _tokenSet_3_data_ []
static const unsigned long _tokenSet_4_data_ []
static const unsigned long _tokenSet_5_data_ []
static const unsigned long _tokenSet_6_data_ []
Constructor & Destructor Documentation
QueryLexer::QueryLexer (ANTLR_USE_NAMESPACE(std) istream & in)
References initLiterals().
QueryLexer::QueryLexer (ANTLR_USE_NAMESPACE(antlr) InputBuffer & ib)
References initLiterals().
QueryLexer::QueryLexer (const ANTLR_USE_NAMESPACE(antlr) LexerSharedInputState & state)
References initLiterals().
Member Function Documentation
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
QueryLexer::ANTLR_USE_NAMESPACE (antlr)
Referenced by mASCII_LETTER(), mB_SLASH(), mBASESIXFOUR_CHAR(), mC_ANGLE(), mC_BRACE(), mC_PAREN(), mC_SQUARE(), mCOLON(), mCOMMA(), mCR(), mDASH(), mDBL_QUOTE(), mDIGIT(), mDOT(), mENCODED_QUOTED_TERM(), mENCODED_TERM(), mFLOAT(), mHIGH_CHAR(), mJUNK(), mLF(), mNUMBER(), mO_ANGLE(), mO_BRACE(), mO_PAREN(), mO_SQUARE(), mOPERATOR(), mQUOTE(), mSAFE_CHAR(), mSAFE_LETTER(), mSLASH(), mSPACE(), mSPACE_DASH(), mSTAR(), mTAB(), mTERM(), and mTEXT_TERM().
bool QueryLexer::getCaseSensitiveLiterals () const [inline]
void QueryLexer::init () [inline]
void QueryLexer::initLiterals () [private]
Referenced by QueryLexer().
void QueryLexer::mASCII_LETTER (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and ASCII_LETTER.
Referenced by mOPERATOR().
void QueryLexer::mB_SLASH (bool _createToken)
References ANTLR_USE_NAMESPACE(), and B_SLASH.
void QueryLexer::mBASESIXFOUR_CHAR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and BASESIXFOUR_CHAR.
Referenced by mENCODED_QUOTED_TERM(), and mENCODED_TERM().
void QueryLexer::mC_ANGLE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and C_ANGLE.
void QueryLexer::mC_BRACE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and C_BRACE.
void QueryLexer::mC_PAREN (bool _createToken)
References ANTLR_USE_NAMESPACE(), and C_PAREN.
Referenced by mENCODED_QUOTED_TERM(), and mENCODED_TERM().
void QueryLexer::mC_SQUARE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and C_SQUARE.
void QueryLexer::mCOLON (bool _createToken)
References ANTLR_USE_NAMESPACE(), and COLON.
void QueryLexer::mCOMMA (bool _createToken)
References ANTLR_USE_NAMESPACE(), and COMMA.
void QueryLexer::mCR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and CR.
Referenced by mJUNK().
void QueryLexer::mDASH (bool _createToken)
References ANTLR_USE_NAMESPACE(), and DASH.
void QueryLexer::mDBL_QUOTE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and DBL_QUOTE.
void QueryLexer::mDIGIT (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and DIGIT.
Referenced by mTERM().
void QueryLexer::mDOT (bool _createToken)
References ANTLR_USE_NAMESPACE(), and DOT.
Referenced by mFLOAT().
void QueryLexer::mENCODED_QUOTED_TERM (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), ENCODED_QUOTED_TERM, mBASESIXFOUR_CHAR(), mC_PAREN(), mO_PAREN(), mSPACE(), and mTAB().
Referenced by mOPERATOR().
void QueryLexer::mENCODED_TERM (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), ENCODED_TERM, mBASESIXFOUR_CHAR(), mC_PAREN(), mO_PAREN(), mSPACE(), and mTAB().
Referenced by mOPERATOR().
void QueryLexer::mFLOAT (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), FLOAT, and mDOT().
Referenced by mTERM().
void QueryLexer::mHIGH_CHAR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and HIGH_CHAR.
Referenced by mTERM(), and mTEXT_TERM().
void QueryLexer::mJUNK (bool _createToken)
References ANTLR_USE_NAMESPACE(), JUNK, mCR(), mLF(), mSPACE(), and mTAB().
void QueryLexer::mLF (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and LF.
Referenced by mJUNK().
void QueryLexer::mNUMBER (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and NUMBER.
Referenced by mTERM().
void QueryLexer::mO_ANGLE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and O_ANGLE.
void QueryLexer::mO_BRACE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and O_BRACE.
void QueryLexer::mO_PAREN (bool _createToken)
References ANTLR_USE_NAMESPACE(), and O_PAREN.
Referenced by mENCODED_QUOTED_TERM(), and mENCODED_TERM().
void QueryLexer::mO_SQUARE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and O_SQUARE.
void QueryLexer::mOPERATOR (bool _createToken)
References ANTLR_USE_NAMESPACE(), ENCODED_QUOTED_TERM, ENCODED_TERM, mASCII_LETTER(), mENCODED_QUOTED_TERM(), mENCODED_TERM(), and OPERATOR.
void QueryLexer::mQUOTE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and QUOTE.
void QueryLexer::mSAFE_CHAR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and SAFE_CHAR.
Referenced by mTEXT_TERM().
void QueryLexer::mSAFE_LETTER (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and SAFE_LETTER.
Referenced by mTERM().
void QueryLexer::mSLASH (bool _createToken)
References ANTLR_USE_NAMESPACE(), and SLASH.
void QueryLexer::mSPACE (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and SPACE.
Referenced by mENCODED_QUOTED_TERM(), mENCODED_TERM(), and mJUNK().
void QueryLexer::mSPACE_DASH (bool _createToken)
References ANTLR_USE_NAMESPACE(), and SPACE_DASH.
void QueryLexer::mSTAR (bool _createToken)
References ANTLR_USE_NAMESPACE(), and STAR.
void QueryLexer::mTAB (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and TAB.
Referenced by mENCODED_QUOTED_TERM(), mENCODED_TERM(), and mJUNK().
void QueryLexer::mTERM (bool _createToken)
References ANTLR_USE_NAMESPACE(), FLOAT, mDIGIT(), mFLOAT(), mHIGH_CHAR(), mNUMBER(), mSAFE_LETTER(), mTEXT_TERM(), NUMBER, and TERM.
void QueryLexer::mTEXT_TERM (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), mHIGH_CHAR(), mSAFE_CHAR(), and TEXT_TERM.
Referenced by mTERM().
void QueryLexer::setNumbers (bool f) [inline]
Member Data Documentation
bool QueryLexer::_numbers [private]
const unsigned long QueryLexer::_tokenSet_0_data_ = { 0UL, 67043328UL, 2281701374UL, 134217726UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL } [static, private]
const unsigned long QueryLexer::_tokenSet_1_data_[] [static, private]
const unsigned long QueryLexer::_tokenSet_2_data_[] [static, private]
const unsigned long QueryLexer::_tokenSet_3_data_[] [static, private]
const unsigned long QueryLexer::_tokenSet_4_data_[] [static, private]
const unsigned long QueryLexer::_tokenSet_5_data_[] [static, private]
const unsigned long QueryLexer::_tokenSet_6_data_[] [static, private]
The documentation for this class was generated from the following files:
QueryLexer.hpp
QueryLexer.cpp