Indri: indri::infnet::InferenceNetworkBuilder Class Reference
indri::infnet::InferenceNetworkBuilder Class Reference
#include <InferenceNetworkBuilder.hpp>
Public Member Functions
InferenceNetworkBuilder (indri::collection::Repository &repository, indri::lang::ListCache &cache, int resultsRequested, int maxWildcardTerms=DEFAULT_MAX_WILDCARD_TERMS)
~InferenceNetworkBuilder ()
InferenceNetwork * getNetwork ()
void defaultAfter (indri::lang::Node *node)
void after (indri::lang::IndexTerm *term)
void after (indri::lang::Field *field)
void after (indri::lang::ExtentAnd *extentAnd)
void after (indri::lang::ExtentOr *extentOr)
void after (indri::lang::WeightedExtentOr *weightedExtentOr)
void after (indri::lang::ExtentInside *extentInside)
void after (indri::lang::BAndNode *uwNode)
void after (indri::lang::ODNode *odNode)
void after (indri::lang::UWNode *uwNode)
void after (indri::lang::FilRejNode *uwNode)
void after (indri::lang::FilReqNode *uwNode)
void after (indri::lang::ContextCounterNode *contextCounterNode)
void after (indri::lang::ContextSimpleCounterNode *contextSimpleCounterNode)
void after (indri::lang::ListAccumulator *listAccumulator)
void after (indri::lang::ScoreAccumulatorNode *scoreAccumulatorNode)
void after (indri::lang::AnnotatorNode *annotatorNode)
void after (indri::lang::TermFrequencyScorerNode *termScorerNode)
void after (indri::lang::CachedFrequencyScorerNode *cachedScorerNode)
void after (indri::lang::RawScorerNode *rawScorerNode)
void after (indri::lang::ExtentRestriction *erNode)
void after (indri::lang::FixedPassage *fpNode)
void after (indri::lang::PriorNode *priorNode)
void after (indri::lang::WeightNode *weightNode)
void after (indri::lang::CombineNode *combineNode)
void after (indri::lang::PlusNode *plusNode)
void after (indri::lang::WPlusNode *plusNode)
void after (indri::lang::OrNode *orNode)
void after (indri::lang::NotNode *notSpecNode)
void after (indri::lang::MaxNode *maxNode)
void after (indri::lang::WAndNode *wandNode)
void after (indri::lang::WSumNode *wsumNode)
void after (indri::lang::FieldLessNode *flNode)
void after (indri::lang::FieldGreaterNode *fgNode)
void after (indri::lang::FieldBetweenNode *fbNode)
void after (indri::lang::FieldEqualsNode *fbNode)
void after (indri::lang::FilterNode *filterNode)
void after (indri::lang::FieldWildcard *fieldWildcard)
void after (indri::lang::ContextInclusionNode *contextInclusionNode)
void after (indri::lang::LengthPrior *lengthPrior)
void after (indri::lang::DocumentStructureNode *docStruct)
void after (indri::lang::ShrinkageScorerNode *shrinkageScorerNode)
void after (indri::lang::ExtentDescendant *extentInside)
void after (indri::lang::ExtentChild *extentInside)
void after (indri::lang::ExtentParent *extentInside)
void after (indri::lang::WildcardTerm *wildcardTerm)
Static Public Attributes
static const int DEFAULT_MAX_WILDCARD_TERMS = 100
Private Member Functions
template<typename _To , typename _From >
std::vector< _To * > _translate (const std::vector< _From * > &children)
indri::query::TermScoreFunction * _buildTermScoreFunction (const std::string &smoothing, double occurrences, double contextSize, int documentOccurrences, int documentCount) const
void _after (indri::lang::NestedExtentInside *extentInside)
void _after (indri::lang::NestedRawScorerNode *rawScorerNode)
void _after (indri::lang::ShrinkageScorerNode *shrinkageScorerNode)
void _after (indri::lang::ExtentEnforcement *eeNode)
void _after (indri::lang::ExtentDescendant *extentInside)
void _after (indri::lang::ExtentChild *extentInside)
void _after (indri::lang::ExtentParent *extentInside)
Private Attributes
std::map< indri::lang::Node
*, InferenceNetworkNode * > _nodeMap
InferenceNetwork * _network
indri::collection::Repository & _repository
indri::lang::ListCache & _cache
int _resultsRequested
int _maxWildcardTerms
Constructor & Destructor Documentation
indri::infnet::InferenceNetworkBuilder::InferenceNetworkBuilder (indri::collection::Repository & repository, indri::lang::ListCache & cache, int resultsRequested, int maxWildcardTerms = DEFAULT_MAX_WILDCARD_TERMS)
indri::infnet::InferenceNetworkBuilder::~InferenceNetworkBuilder ()
References _network.
Member Function Documentation
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::ExtentParent * extentInside) [private]
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::ExtentParent::getDocumentStructure(), indri::lang::ExtentInside::getInner(), indri::lang::ExtentInside::getOuter(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::ExtentChild * extentInside) [private]
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::ExtentChild::getDocumentStructure(), indri::lang::ExtentInside::getInner(), indri::lang::ExtentInside::getOuter(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::ExtentDescendant * extentInside) [private]
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::ExtentDescendant::getDocumentStructure(), indri::lang::ExtentInside::getInner(), indri::lang::ExtentInside::getOuter(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::ExtentEnforcement * eeNode) [private]
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::ExtentRestriction::getChild(), indri::lang::ExtentRestriction::getField(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::ShrinkageScorerNode * shrinkageScorerNode) [private]
References _buildTermScoreFunction(), _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::InferenceNetwork::addScoreFunction(), indri::infnet::ShrinkageBeliefNode::addShrinkageRule(), indri::lang::RawScorerNode::getContext(), indri::lang::RawScorerNode::getContextSize(), indri::lang::ShrinkageScorerNode::getDocumentStructure(), indri::lang::RawScorerNode::getOccurrences(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::ShrinkageScorerNode::getShrinkageRules(), indri::lang::RawScorerNode::getSmoothing(), INDRI_HUGE_SCORE, and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::NestedRawScorerNode * rawScorerNode) [private]
References _buildTermScoreFunction(), _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::InferenceNetwork::addListNode(), indri::infnet::InferenceNetwork::addScoreFunction(), indri::lang::RawScorerNode::getContext(), indri::lang::RawScorerNode::getContextSize(), indri::lang::RawScorerNode::getDocumentCount(), indri::lang::RawScorerNode::getDocumentOccurrences(), indri::lang::RawScorerNode::getOccurrences(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::RawScorerNode::getSmoothing(), INDRI_HUGE_SCORE, and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::_after (indri::lang::NestedExtentInside * extentInside) [private]
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::ExtentInside::getInner(), indri::lang::ExtentInside::getOuter(), and indri::lang::Node::nodeName().
Referenced by after().
indri::query::TermScoreFunction * indri::infnet::InferenceNetworkBuilder::_buildTermScoreFunction (const std::string & smoothing, double occurrences, double contextSize, int documentOccurrences, int documentCount) const [private]
References indri::query::TermScoreFunctionFactory::get().
Referenced by _after(), and after().
template<typename _To , typename _From > std::vector<_To*> indri::infnet::InferenceNetworkBuilder::_translate (const std::vector< _From * > & children) [inline, private]
References _nodeMap.
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::WildcardTerm * wildcardTerm) [virtual]
Reimplemented from indri::lang::Walker.
References _maxWildcardTerms, _network, _nodeMap, _repository, indri::infnet::InferenceNetwork::addDocIterator(), indri::infnet::InferenceNetwork::addListNode(), indri::index::VocabularyIterator::currentEntry(), indri::lang::WildcardTerm::getTerm(), indri::collection::Repository::indexes(), indri::index::VocabularyIterator::nextEntry(), indri::lang::Node::nodeName(), indri::index::VocabularyIterator::startIteration(), indri::index::TermData::term, indri::index::DiskTermData::termData, and indri::index::Index::vocabularyIterator().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentParent * extentInside) [virtual]
Reimplemented from indri::lang::Walker.
References _after().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentChild * extentInside) [virtual]
Reimplemented from indri::lang::Walker.
References _after().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentDescendant * extentInside) [virtual]
Reimplemented from indri::lang::Walker.
References _after().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ShrinkageScorerNode * shrinkageScorerNode) [virtual]
Reimplemented from indri::lang::Walker.
References _after().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::DocumentStructureNode * docStruct) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addDocumentStructureHolderNode(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::LengthPrior * lengthPrior) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::LengthPrior::getChild(), indri::lang::LengthPrior::getExponent(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ContextInclusionNode * contextInclusionNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::ContextInclusionNode::getChildren(), indri::lang::ContextInclusionNode::getPreserveExtentsChild(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FieldWildcard * fieldWildcard) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FilterNode * filterNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::FilterNode::getChild(), indri::lang::FilterNode::getDocuments(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FieldEqualsNode * fbNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::FieldEqualsNode::getConstant(), indri::lang::FieldEqualsNode::getField(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FieldBetweenNode * fbNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::FieldBetweenNode::getField(), indri::lang::FieldBetweenNode::getHigh(), indri::lang::FieldBetweenNode::getLow(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FieldGreaterNode * fgNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::FieldGreaterNode::getConstant(), indri::lang::FieldGreaterNode::getField(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FieldLessNode * flNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::FieldLessNode::getConstant(), indri::lang::FieldLessNode::getField(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::WSumNode * wsumNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::WeightedSumNode::addChild(), indri::lang::WeightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::WAndNode * wandNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::WeightedAndNode::addChild(), indri::infnet::WeightedAndNode::doneAddingChildren(), indri::lang::WeightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::MaxNode * maxNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::UnweightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::NotNode * notSpecNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::NotNode::getChild(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::OrNode * orNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::UnweightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::WPlusNode * plusNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::WPlusNode::addChild(), indri::lang::WeightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::PlusNode * plusNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::UnweightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::CombineNode * combineNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::UnweightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::WeightNode * weightNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::WeightedAndNode::addChild(), indri::infnet::WeightedAndNode::doneAddingChildren(), indri::lang::WeightedCombinationNode::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::PriorNode * priorNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::InferenceNetwork::addPriorIterator(), indri::lang::PriorNode::getPriorName(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FixedPassage * fpNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::FixedPassage::getChild(), indri::lang::FixedPassage::getIncrement(), indri::lang::FixedPassage::getWindowSize(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentRestriction * erNode) [virtual]
Reimplemented from indri::lang::Walker.
References _after(), _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::ExtentRestriction::getChild(), indri::lang::ExtentRestriction::getField(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::RawScorerNode * rawScorerNode) [virtual]
Reimplemented from indri::lang::Walker.
References _after(), _buildTermScoreFunction(), _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::InferenceNetwork::addListNode(), indri::infnet::InferenceNetwork::addScoreFunction(), indri::lang::FieldBelowWalker::fieldBelow(), indri::lang::RawScorerNode::getContext(), indri::lang::RawScorerNode::getContextSize(), indri::lang::RawScorerNode::getDocumentCount(), indri::lang::RawScorerNode::getDocumentOccurrences(), indri::lang::RawScorerNode::getOccurrences(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::RawScorerNode::getSmoothing(), INDRI_HUGE_SCORE, and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::CachedFrequencyScorerNode * cachedScorerNode) [virtual]
Reimplemented from indri::lang::Walker.
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::TermFrequencyScorerNode * termScorerNode) [virtual]
Reimplemented from indri::lang::Walker.
References _buildTermScoreFunction(), _network, _nodeMap, _repository, indri::infnet::InferenceNetwork::addBeliefNode(), indri::infnet::InferenceNetwork::addDocIterator(), indri::infnet::InferenceNetwork::addScoreFunction(), indri::lang::TermFrequencyScorerNode::getContextSize(), indri::lang::TermFrequencyScorerNode::getDocumentCount(), indri::lang::TermFrequencyScorerNode::getDocumentOccurrences(), indri::lang::TermFrequencyScorerNode::getOccurrences(), indri::lang::TermFrequencyScorerNode::getSmoothing(), indri::lang::TermFrequencyScorerNode::getStemmed(), indri::lang::TermFrequencyScorerNode::getText(), indri::lang::Node::nodeName(), and indri::collection::Repository::processTerm().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::AnnotatorNode * annotatorNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addComplexEvaluatorNode(), indri::infnet::InferenceNetwork::addEvaluatorNode(), indri::lang::AnnotatorNode::getChild(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ScoreAccumulatorNode * scoreAccumulatorNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, _resultsRequested, indri::infnet::InferenceNetwork::addComplexEvaluatorNode(), indri::infnet::InferenceNetwork::addEvaluatorNode(), indri::lang::ScoreAccumulatorNode::getChild(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ListAccumulator * listAccumulator) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addComplexEvaluatorNode(), indri::infnet::InferenceNetwork::addEvaluatorNode(), indri::lang::ListAccumulator::getRawExtent(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ContextSimpleCounterNode * contextSimpleCounterNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addEvaluatorNode(), indri::lang::ContextSimpleCounterNode::context(), indri::lang::ContextSimpleCounterNode::field(), indri::lang::Node::nodeName(), and indri::lang::ContextSimpleCounterNode::terms().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ContextCounterNode * contextCounterNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addComplexEvaluatorNode(), indri::infnet::InferenceNetwork::addEvaluatorNode(), indri::lang::ContextCounterNode::getContext(), indri::lang::ContextCounterNode::getRawExtent(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FilReqNode * uwNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::FilReqNode::getFilter(), indri::lang::FilReqNode::getRequired(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::FilRejNode * uwNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addBeliefNode(), indri::lang::FilRejNode::getDisallowed(), indri::lang::FilRejNode::getFilter(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::UWNode * uwNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::UWNode::getChildren(), indri::lang::UWNode::getWindowSize(), indri::infnet::NullListNode::isStopword(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ODNode * odNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::lang::ODNode::getChildren(), indri::lang::ODNode::getWindowSize(), inferencenetworkbuilder_build_ordered_window(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::BAndNode * uwNode) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::BAndNode::getChildren(), indri::infnet::NullListNode::isStopword(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentInside * extentInside) [virtual]
Reimplemented from indri::lang::Walker.
References _after(), _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::FieldBelowWalker::fieldBelow(), indri::lang::ExtentInside::getInner(), indri::lang::ExtentInside::getOuter(), indri::lang::Node::nodeName(), and indri::lang::ExtentInside::walk().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::WeightedExtentOr * weightedExtentOr) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::WeightedExtentOr::getChildren(), indri::lang::WeightedExtentOr::getWeights(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentOr * extentOr) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::ExtentOr::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::ExtentAnd * extentAnd) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addListNode(), indri::lang::ExtentAnd::getChildren(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::Field * field) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, indri::infnet::InferenceNetwork::addFieldIterator(), indri::infnet::InferenceNetwork::addListNode(), indri::lang::Field::getFieldName(), and indri::lang::Node::nodeName().
void indri::infnet::InferenceNetworkBuilder::after (indri::lang::IndexTerm * term) [virtual]
Reimplemented from indri::lang::Walker.
References _network, _nodeMap, _repository, indri::infnet::InferenceNetwork::addDocIterator(), indri::infnet::InferenceNetwork::addListNode(), indri::lang::IndexTerm::getStemmed(), indri::lang::IndexTerm::getText(), indri::lang::Node::nodeName(), and indri::collection::Repository::processTerm().
void indri::infnet::InferenceNetworkBuilder::defaultAfter (indri::lang::Node * node) [virtual]
Reimplemented from indri::lang::Walker.
indri::infnet::InferenceNetwork * indri::infnet::InferenceNetworkBuilder::getNetwork ()
References _network.
Referenced by indri::server::LocalQueryServer::runQuery().
Member Data Documentation
indri::lang::ListCache& indri::infnet::InferenceNetworkBuilder::_cache [private]
int indri::infnet::InferenceNetworkBuilder::_maxWildcardTerms [private]
Referenced by after().
InferenceNetwork* indri::infnet::InferenceNetworkBuilder::_network [private]
Referenced by _after(), after(), getNetwork(), and ~InferenceNetworkBuilder().
std::map< indri::lang::Node*, InferenceNetworkNode* > indri::infnet::InferenceNetworkBuilder::_nodeMap [private]
Referenced by _after(), _translate(), and after().
indri::collection::Repository& indri::infnet::InferenceNetworkBuilder::_repository [private]
Referenced by after().
int indri::infnet::InferenceNetworkBuilder::_resultsRequested [private]
Referenced by after().
const int indri::infnet::InferenceNetworkBuilder::DEFAULT_MAX_WILDCARD_TERMS = 100 [static]
The documentation for this class was generated from the following files:
InferenceNetworkBuilder.hpp
InferenceNetworkBuilder.cpp