Indri: indri::api::Parameters Class Reference
indri::api::Parameters Class Reference
#include <Parameters.hpp>
Classes
struct parameter_value
Container for parameter values.
Public Member Functions
Parameters ()
Create.
Parameters (const Parameters &other)
Parameters (parameter_value *value)
Parameters (const std::string &path, parameter_value *value)
~Parameters ()
Clean up.
operator double ()
operator bool ()
operator int ()
operator INT64 ()
operator std::string ()
const Parameters & operator= (const Parameters &other)
Parameters get (size_t index)
Parameters get (const std::string &name)
Parameters get (const char *name)
bool get (const std::string &name, bool def)
int get (const std::string &name, int def)
double get (const std::string &name, double def)
INT64 get (const std::string &name, INT64 def)
std::string get (const std::string &name, const char *def)
std::string get (const std::string &name, const std::string &def)
Parameters operator[] (size_t index)
Parameters operator[] (const std::string &path)
Parameters operator[] (const char *path)
Parameters append (const std::string &path)
void remove (const std::string &path)
void set (const std::string &name, bool value)
void set (const std::string &name, const char *value)
void set (const std::string &name, const std::string &value)
void set (const std::string &name, int value)
void set (const std::string &name, UINT64 value)
void set (const std::string &name, INT64 value)
void set (const std::string &name, double value)
void set (const std::string &value)
void clear ()
Clear the parameter tree.
size_t size ()
bool exists (size_t index)
bool exists (const std::string &name)
indri::xml::XMLNode * toXML ()
void load (const std::string &text)
void loadFile (const std::string &filename)
void loadCommandLine (int argc, char **argv)
void write (std::string &text)
void writeFile (const std::string &filename)
Static Public Member Functions
static Parameters & instance ()
Return the singleton instance of the Parameters class.
Protected Member Functions
parameter_value * _getRoot ()
parameter_value * _getPath (const std::string &path, Parameters::parameter_value *last, int offset=0)
parameter_value * _createPath (const std::string &path)
void _parseNextSegment (std::string &segment, int &arrayIndex, int &endOffset, const std::string &path, int beginOffset)
parameter_value * _getSegment (const std::string &segment, int arrayIndex, Parameters::parameter_value *from)
void _loadXML (class indri::xml::XMLNode *node)
void _fillXML (class indri::xml::XMLNode *node)
INT64 _multiplier (const std::string &value)
bool _isBoolean (const std::string &value)
bool _asBoolean (const std::string &value)
Protected Attributes
parameter_value * _collection
bool _owned
Detailed Description
Parameters class for Indri index and retrieval methods. Provides a map of key value pairs, where the key is a string and the values can be one of double, int, INT64, string, or a Parameters object, encapsulated in a parameter_value struct.
Constructor & Destructor Documentation
indri::api::Parameters::Parameters ()
Create.
Referenced by append(), get(), and instance().
indri::api::Parameters::Parameters (const Parameters & other)
Clone
Parameters:
other the object to copy.
indri::api::Parameters::Parameters (parameter_value * value)
Initialize with a parameter_value
Parameters:
value the item to insert.
indri::api::Parameters::Parameters (const std::string & path, parameter_value * value)
Initialize with a key path and parameter_value
Parameters:
path the key.
value the item to insert for that key.
indri::api::Parameters::~Parameters ()
Clean up.
References _collection, and _owned.
Member Function Documentation
bool indri::api::Parameters::_asBoolean (const std::string & value) [inline, protected]
Referenced by operator bool(), operator int(), and operator INT64().
indri::api::Parameters::parameter_value * indri::api::Parameters::_createPath (const std::string & path) [protected]
References _getRoot(), _getSegment(), _parseNextSegment(), indri::api::Parameters::parameter_value::array, indri::api::Parameters::parameter_value::convertToArray(), and indri::api::Parameters::parameter_value::table.
Referenced by append(), and set().
void indri::api::Parameters::_fillXML (class indri::xml::XMLNode * node) [protected]
References _fillXML(), _getRoot(), indri::xml::XMLNode::addChild(), indri::api::Parameters::parameter_value::array, indri::xml::XMLNode::setValue(), indri::api::Parameters::parameter_value::table, and indri::api::Parameters::parameter_value::value.
Referenced by _fillXML(), and toXML().
indri::api::Parameters::parameter_value * indri::api::Parameters::_getPath (const std::string & path, Parameters::parameter_value * last, int offset = 0) [protected]
References _getSegment(), and _parseNextSegment().
Referenced by exists(), get(), and remove().
indri::api::Parameters::parameter_value * indri::api::Parameters::_getRoot () [protected]
References _collection.
Referenced by _createPath(), _fillXML(), clear(), exists(), get(), operator bool(), operator double(), operator int(), operator INT64(), operator std::string(), remove(), set(), and size().
indri::api::Parameters::parameter_value * indri::api::Parameters::_getSegment (const std::string & segment, int arrayIndex, Parameters::parameter_value * from) [protected]
References indri::api::Parameters::parameter_value::array, and indri::api::Parameters::parameter_value::table.
Referenced by _createPath(), and _getPath().
bool indri::api::Parameters::_isBoolean (const std::string & value) [inline, protected]
Referenced by operator int(), and operator INT64().
void indri::api::Parameters::_loadXML (class indri::xml::XMLNode * node) [protected]
References _loadXML(), append(), exists(), indri::xml::XMLNode::getAttribute(), indri::xml::XMLNode::getChildren(), indri::xml::XMLNode::getName(), and indri::xml::XMLNode::getValue().
Referenced by _loadXML(), load(), and loadFile().
INT64 indri::api::Parameters::_multiplier (const std::string & value) [inline, protected]
Referenced by operator int(), and operator INT64().
void indri::api::Parameters::_parseNextSegment (std::string & segment, int & arrayIndex, int & endOffset, const std::string & path, int beginOffset) [protected]
Referenced by _createPath(), _getPath(), and remove().
indri::api::Parameters indri::api::Parameters::append (const std::string & path)
Create a new empty parameter_value for the key given in path
Parameters:
path the key to create the value for
Returns:
the Parameters object initialized with the new value.
References _createPath(), indri::api::Parameters::parameter_value::array, indri::api::Parameters::parameter_value::convertToArray(), and Parameters().
Referenced by _loadXML(), FieldModifier::_mergeFields(), indri::index::IndexWriter::_writeManifest(), indri::collection::Repository::_writeParameters(), indri::collection::CompressedCollection::create(), java_parameters_array_of_strings(), java_parameters_map(), loadCommandLine(), main(), indri::api::IndexEnvironment::setIndexedFields(), indri::api::IndexEnvironment::setMetadataIndexedFields(), indri::api::IndexEnvironment::setNumericField(), indri::api::IndexEnvironment::setOrdinalField(), indri::api::IndexEnvironment::setParentalField(), indri::api::QueryEnvironment::setScoringRules(), indri::api::QueryEnvironment::setStopwords(), and indri::api::IndexEnvironment::setStopwords().
void indri::api::Parameters::clear ()
Clear the parameter tree.
References _getRoot(), and indri::api::Parameters::parameter_value::clear().
Referenced by indri::collection::Repository::_writeParameters(), and indri::collection::Repository::close().
bool indri::api::Parameters::exists (const std::string & name)
Parameters:
name the key to probe.
Returns:
true if an entry exists for this key, false otherwise.
References _getPath(), and _getRoot().
bool indri::api::Parameters::exists (size_t index)
Parameters:
index the index to probe.
Returns:
true if an entry exists for this index, false otherwise.
References size().
Referenced by indri::collection::Repository::_buildChain(), indri::collection::Repository::_buildFields(), indri::collection::Repository::_copyParameters(), indri::collection::Repository::_fieldNames(), indri::lang::SmoothingAnnotatorWalker::_loadSmoothingRules(), _loadXML(), FieldModifier::_mergeFields(), indri::collection::Repository::_openIndexes(), indri::index::DiskIndex::_readManifest(), copy_parameters_to_string_vector(), indri::collection::Repository::create(), CSharp_Parameters_exists__SWIG_0(), indri::query::TermScoreFunctionFactory::get(), get(), QueryThread::initialize(), indri::parse::KrovetzStemmerTransformation::KrovetzStemmerTransformation(), main(), indri::collection::Repository::merge(), indri::parse::NormalizationTransformation::NormalizationTransformation(), indri::collection::CompressedCollection::open(), open_indexes(), indri::collection::CompressedCollection::openRead(), FieldModifier::processFields(), indri::query::QueryExpander::QueryExpander(), require_parameter(), indri::api::QueryEnvironment::runQuery(), indri::api::IndexEnvironment::setIndexedFields(), indri::api::IndexEnvironment::setMetadataIndexedFields(), indri::api::IndexEnvironment::setNumericField(), indri::api::IndexEnvironment::setOrdinalField(), indri::api::IndexEnvironment::setParentalField(), indri::infnet::ShrinkageBeliefNode::setSmoothing(), indri::query::ReformulateQuery::transform(), usage(), and QueryThread::work().
std::string indri::api::Parameters::get (const std::string & name, const std::string & def)
Retrieve the entry associated with name.
Parameters:
name the key value.
def the default value for the key
Returns:
the value associated with the key or def if no entry exists.
References exists().
std::string indri::api::Parameters::get (const std::string & name, const char * def)
References exists().
INT64 indri::api::Parameters::get (const std::string & name, INT64 def)
Retrieve the entry associated with name.
Parameters:
name the key value.
def the default value for the key
Returns:
the value associated with the key or def if no entry exists.
References exists().
double indri::api::Parameters::get (const std::string & name, double def)
Retrieve the entry associated with name.
Parameters:
name the key value.
def the default value for the key
Returns:
the value associated with the key or def if no entry exists.
References exists().
int indri::api::Parameters::get (const std::string & name, int def)
Retrieve the entry associated with name.
Parameters:
name the key value.
def the default value for the key
Returns:
the value associated with the key or def if no entry exists.
References exists().
bool indri::api::Parameters::get (const std::string & name, bool def)
References exists().
indri::api::Parameters indri::api::Parameters::get (const char * name)
Retrieve the entry associated with name.
Parameters:
name the key value.
Returns:
a Parameters object.
indri::api::Parameters indri::api::Parameters::get (const std::string & name)
Retrieve the entry associated with name.
Parameters:
name the key value.
Returns:
a Parameters object.
References _getPath(), _getRoot(), exists(), and Parameters().
indri::api::Parameters indri::api::Parameters::get (size_t index)
Retrieve the n'th entry.
Parameters:
index the index of the entry to retrieve.
Returns:
a Parameters object.
References _getRoot(), indri::api::Parameters::parameter_value::array, exists(), and Parameters().
Referenced by indri::collection::Repository::_buildChain(), indri::collection::Repository::_buildFields(), FieldModifier::_mergeFields(), indri::collection::Repository::_openIndexes(), indri::index::DiskIndex::_readManifest(), indri::collection::Repository::_stemmerName(), indri::parse::ArabicStemmerTransformation::ArabicStemmerTransformation(), indri::collection::Repository::create(), indri::query::TFIDFExpander::expand(), indri::query::RMExpander::expand(), indri::query::PonteExpander::expand(), indri::query::ReformulateQuery::generateCMUFDMQuery(), indri::query::ReformulateQuery::generateFDMQuery(), indri::query::ReformulateQuery::generateSDMQuery(), indri::query::TermScoreFunctionFactory::get(), QueryThread::initialize(), main(), indri::collection::Repository::open(), indri::collection::CompressedCollection::open(), indri::collection::Repository::openRead(), process_numeric_fields(), process_ordinal_fields(), process_parental_fields(), FieldModifier::processFields(), indri::api::QueryEnvironment::runQuery(), indri::api::IndexEnvironment::setMetadataIndexedFields(), indri::infnet::ShrinkageBeliefNode::setSmoothing(), indri::api::QueryEnvironment::setStopwords(), indri::api::IndexEnvironment::setStopwords(), and indri::query::ReformulateQuery::transform().
indri::api::Parameters & indri::api::Parameters::instance () [static]
Return the singleton instance of the Parameters class.
References Parameters().
Referenced by CSharp_Parameters_instance(), indri::infnet::WeightedAndNode::indexChanged(), indri::infnet::TermFrequencyBeliefNode::indexChanged(), indri::infnet::ContextInclusionAndNode::indexChanged(), indri::server::LocalQueryServer::LocalQueryServer(), main(), and indri::infnet::ScoredExtentAccumulator::ScoredExtentAccumulator().
void indri::api::Parameters::load (const std::string & text)
Initialize from a string
Parameters:
text the text to parse
References _loadXML(), and indri::xml::XMLReader::read().
void indri::api::Parameters::loadCommandLine (int argc, char ** argv)
Initialize from the command line
Parameters:
argc the number of command line arguments
argv the command line arguments
References append(), loadFile(), and set().
Referenced by main().
void indri::api::Parameters::loadFile (const std::string & filename)
Initialize from a file
Parameters:
filename the filename to parse
References _loadXML(), input(), and indri::xml::XMLReader::read().
Referenced by indri::index::DiskIndex::_readManifest(), loadCommandLine(), indri::collection::Repository::merge(), indri::collection::Repository::open(), indri::collection::CompressedCollection::open(), indri::collection::Repository::openRead(), indri::collection::CompressedCollection::openRead(), and FieldModifier::processFields().
indri::api::Parameters::operator bool () [inline]
References _asBoolean(), _getRoot(), and indri::api::Parameters::parameter_value::getValue().
indri::api::Parameters::operator double () [inline]
Returns:
the value of the parameter as a double
References _getRoot(), and indri::api::Parameters::parameter_value::getValue().
indri::api::Parameters::operator int () [inline]
Converts the value to an int, scaling by the multiplier if supplied. Valid values are (case insensitive) K = 1000, M = 1000000, G = 1000000000.
Returns:
the value of the parameter as an int
References _asBoolean(), _getRoot(), _isBoolean(), _multiplier(), and indri::api::Parameters::parameter_value::getValue().
indri::api::Parameters::operator INT64 () [inline]
Converts the value to an INT64, scaling by the multiplier if supplied. Valid values are (case insensitive) K = 1000, M = 1000000, G = 1000000000.
Returns:
the value of the parameter as an INT64
References _asBoolean(), _getRoot(), _isBoolean(), _multiplier(), indri::api::Parameters::parameter_value::getValue(), and string_to_i64().
indri::api::Parameters::operator std::string () [inline]
Returns:
the value of the parameter as a string
References _getRoot(), and indri::api::Parameters::parameter_value::getValue().
const Parameters& indri::api::Parameters::operator= (const Parameters & other) [inline]
assignment via deep copy.
Parameters:
other the item to copy.
Returns:
this object
References _collection, indri::api::Parameters::parameter_value::array, indri::utility::delete_map_contents(), indri::utility::delete_vector_contents(), indri::api::Parameters::parameter_value::table, and indri::api::Parameters::parameter_value::value.
indri::api::Parameters indri::api::Parameters::operator[] (const char * path)
Retrieve the entry indexed by path.
Parameters:
path the key of the entry to retrieve.
Returns:
a Parameters object.
indri::api::Parameters indri::api::Parameters::operator[] (const std::string & path)
Retrieve the entry indexed by path.
Parameters:
path the key of the entry to retrieve.
Returns:
a Parameters object.
indri::api::Parameters indri::api::Parameters::operator[] (size_t index)
Retrieve the n'th entry.
Parameters:
index the index of the entry to retrieve.
Returns:
a Parameters object.
void indri::api::Parameters::remove (const std::string & path)
Remove an entry from the table. Does nothing if the key does not exist.
Parameters:
path the key to remove.
References _getPath(), _getRoot(), _parseNextSegment(), indri::api::Parameters::parameter_value::array, and indri::api::Parameters::parameter_value::table.
Referenced by FieldModifier::_mergeFields().
void indri::api::Parameters::set (const std::string & value)
Set the value of the Parameters object
Parameters:
value the value
References _getRoot(), and indri::api::Parameters::parameter_value::value.
void indri::api::Parameters::set (const std::string & name, double value)
Set the value for the given key.
Parameters:
name the key
value the value
void indri::api::Parameters::set (const std::string & name, INT64 value)
Set the value for the given key.
Parameters:
name the key
value the value
References i64_to_string().
void indri::api::Parameters::set (const std::string & name, UINT64 value)
Set the value for the given key.
Parameters:
name the key
value the value
References i64_to_string().
void indri::api::Parameters::set (const std::string & name, int value)
Set the value for the given key.
Parameters:
name the key
value the value
void indri::api::Parameters::set (const std::string & name, const std::string & value)
Set the value for the given key.
Parameters:
name the key
value the value
References _createPath(), and indri::api::Parameters::parameter_value::value.
void indri::api::Parameters::set (const std::string & name, const char * value)
References _createPath(), and indri::api::Parameters::parameter_value::value.
void indri::api::Parameters::set (const std::string & name, bool value)
Referenced by indri::collection::Repository::_copyParameters(), FieldModifier::_mergeFields(), _parseSmoothing(), indri::index::IndexWriter::_writeManifest(), indri::collection::Repository::_writeMergedManifest(), indri::collection::Repository::_writeParameters(), indri::collection::CompressedCollection::create(), QueryThread::initialize(), java_parameters_map(), loadCommandLine(), main(), FieldModifier::processFields(), indri::api::QueryEnvironment::setBaseline(), indri::api::IndexEnvironment::setIndexedFields(), indri::api::IndexEnvironment::setInjectURL(), indri::api::QueryEnvironment::setMemory(), indri::api::IndexEnvironment::setMemory(), indri::api::IndexEnvironment::setMetadataIndexedFields(), indri::api::IndexEnvironment::setNormalization(), indri::api::IndexEnvironment::setNumericField(), indri::api::IndexEnvironment::setOrdinalField(), indri::api::IndexEnvironment::setParentalField(), indri::api::QueryEnvironment::setScoringRules(), indri::api::QueryEnvironment::setSingleBackgroundModel(), indri::infnet::ShrinkageBeliefNode::setSmoothing(), indri::api::IndexEnvironment::setStemmer(), indri::api::QueryEnvironment::setStopwords(), indri::api::IndexEnvironment::setStopwords(), indri::api::IndexEnvironment::setStoreDocs(), and termscorefunctionfactory_parse().
size_t indri::api::Parameters::size ()
Returns:
the size of the object.
References _getRoot(), indri::api::Parameters::parameter_value::array, indri::api::Parameters::parameter_value::table, and indri::api::Parameters::parameter_value::value.
Referenced by indri::collection::Repository::_buildFields(), indri::collection::Repository::_fieldNames(), indri::lang::SmoothingAnnotatorWalker::_loadSmoothingRules(), FieldModifier::_mergeFields(), indri::collection::Repository::_openIndexes(), indri::index::DiskIndex::_readManifest(), copy_parameters_to_string_vector(), indri::collection::Repository::create(), exists(), QueryThread::initialize(), indri::parse::KrovetzStemmerTransformation::KrovetzStemmerTransformation(), main(), indri::collection::Repository::merge(), indri::parse::NormalizationTransformation::NormalizationTransformation(), indri::collection::CompressedCollection::open(), open_indexes(), indri::collection::CompressedCollection::openRead(), process_numeric_fields(), process_ordinal_fields(), process_parental_fields(), FieldModifier::processFields(), push_queue(), indri::query::QueryExpander::QueryExpander(), indri::parse::StopperTransformation::read(), indri::api::IndexEnvironment::setIndexedFields(), indri::api::IndexEnvironment::setNumericField(), indri::api::IndexEnvironment::setOrdinalField(), indri::api::IndexEnvironment::setParentalField(), and indri::query::ReformulateQuery::transform().
indri::xml::XMLNode * indri::api::Parameters::toXML ()
Convert to XML
Returns:
an indri::xml::XMLNode containing the parameters
References _fillXML().
Referenced by write().
void indri::api::Parameters::write (std::string & text)
Write the Parameters table to the given string
Parameters:
text the string to write into.
References toXML().
Referenced by writeFile().
void indri::api::Parameters::writeFile (const std::string & filename)
Write the Parameters table to the given filename
Parameters:
filename the filename to write into.
References write().
Referenced by indri::index::IndexWriter::_writeManifest(), indri::collection::Repository::_writeMergedManifest(), indri::collection::Repository::_writeParameters(), and indri::collection::CompressedCollection::create().
Member Data Documentation
parameter_value* indri::api::Parameters::_collection [protected]
Referenced by _getRoot(), operator=(), and ~Parameters().
bool indri::api::Parameters::_owned [protected]
Referenced by ~Parameters().
The documentation for this class was generated from the following files:
Parameters.hpp
Parameters.cpp