Indri: indri::collection::RepositoryLoadThread Class Reference
indri::collection::RepositoryLoadThread Class Reference
#include <RepositoryLoadThread.hpp>
Public Member Functions
RepositoryLoadThread (class Repository &repository, UINT64 memory)
UINT64 initialize ()
void deinitialize ()
UINT64 work ()
bool hasWork ()
Private Attributes
class Repository & _repository
UINT64 _memory
Constructor & Destructor Documentation
indri::collection::RepositoryLoadThread::RepositoryLoadThread (class Repository & repository, UINT64 memory)
Member Function Documentation
void indri::collection::RepositoryLoadThread::deinitialize () [virtual]
Implements indri::thread::UtilityThread.
bool indri::collection::RepositoryLoadThread::hasWork () [virtual]
Implements indri::thread::UtilityThread.
UINT64 indri::collection::RepositoryLoadThread::initialize () [virtual]
Implements indri::thread::UtilityThread.
References FIVE_SECONDS.
UINT64 indri::collection::RepositoryLoadThread::work () [virtual]
Implements indri::thread::UtilityThread.
References indri::collection::Repository::_incrementLoad(), _memory, _repository, indri::collection::Repository::_setThrashing(), FIVE_SECONDS, HALF_SECOND, indri::collection::Repository::indexes(), indri::index::DiskIndex::MAX_DOCLENGTHS_CACHE, and indri::index::MemoryIndex::memorySize().
Member Data Documentation
UINT64 indri::collection::RepositoryLoadThread::_memory [private]
Referenced by work().
class Repository& indri::collection::RepositoryLoadThread::_repository [private]
Referenced by work().
The documentation for this class was generated from the following files:
RepositoryLoadThread.hpp
RepositoryLoadThread.cpp