Indri: indri::lang::UnweightedCombinationNode Class Reference
indri::lang::UnweightedCombinationNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
const std::vector
< ScoredExtentNode * > & getChildren ()
void addChild (ScoredExtentNode *scoredNode)
void pack (Packer &packer)
Protected Member Functions
void _unpack (Unpacker &unpacker)
UINT64 _hashCode () const
template<class _ThisType >
void _walk (_ThisType *ptr, Walker &walker)
template<class _ThisType >
Node * _copy (_ThisType *ptr, Copier &copier)
void _childText (std::stringstream &qtext) const
Protected Attributes
std::vector< ScoredExtentNode * > _children
Member Function Documentation
void indri::lang::UnweightedCombinationNode::_childText (std::stringstream & qtext) const [inline, protected]
References _children.
Referenced by indri::lang::PlusNode::queryText(), indri::lang::CombineNode::queryText(), indri::lang::MaxNode::queryText(), and indri::lang::OrNode::queryText().
template<class _ThisType > Node* indri::lang::UnweightedCombinationNode::_copy (_ThisType * ptr, Copier & copier) [inline, protected]
References _children, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and indri::lang::Node::nodeName().
Referenced by indri::lang::PlusNode::copy(), indri::lang::CombineNode::copy(), indri::lang::MaxNode::copy(), and indri::lang::OrNode::copy().
UINT64 indri::lang::UnweightedCombinationNode::_hashCode () const [inline, protected]
References _children.
Referenced by indri::lang::PlusNode::hashCode(), indri::lang::CombineNode::hashCode(), indri::lang::MaxNode::hashCode(), and indri::lang::OrNode::hashCode().
void indri::lang::UnweightedCombinationNode::_unpack (Unpacker & unpacker) [inline, protected]
References _children, and indri::lang::Unpacker::getScoredExtentVector().
Referenced by indri::lang::CombineNode::CombineNode(), indri::lang::MaxNode::MaxNode(), indri::lang::OrNode::OrNode(), and indri::lang::PlusNode::PlusNode().
template<class _ThisType > void indri::lang::UnweightedCombinationNode::_walk (_ThisType * ptr, Walker & walker) [inline, protected]
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::PlusNode::walk(), indri::lang::CombineNode::walk(), indri::lang::MaxNode::walk(), and indri::lang::OrNode::walk().
void indri::lang::UnweightedCombinationNode::addChild (ScoredExtentNode * scoredNode) [inline]
References _children.
Referenced by NexiParser::aboutClause(), NexiParser::clause(), NexiParser::filter(), QueryParser::query(), NexiParser::termList(), and QueryParser::unweightedList().
const std::vector<ScoredExtentNode*>& indri::lang::UnweightedCombinationNode::getChildren () [inline]
References _children.
Referenced by indri::lang::WeightFoldingCopier::after(), and indri::infnet::InferenceNetworkBuilder::after().
void indri::lang::UnweightedCombinationNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
Member Data Documentation
std::vector<ScoredExtentNode*> indri::lang::UnweightedCombinationNode::_children [protected]
Referenced by _childText(), _copy(), _hashCode(), _unpack(), _walk(), addChild(), getChildren(), and pack().
The documentation for this class was generated from the following file:
QuerySpec.hpp