Indri: indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator > Class Template Reference
indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator > Class Template Reference
#include <HashTable.hpp>
Public Types
typedef HashBucket< _Key, _Value > bucket_type
typedef _Key key_type
typedef _Value value_type
typedef _HashFunction hash_type
typedef _Comparator compare_type
typedef class
HashTableIterator< _Key,
_Value, _Comparator > iterator
Public Member Functions
HashTable (size_t size=16384, indri::utility::RegionAllocator *allocator=0)
~HashTable ()
_Value * find (const _Key &k) const
_Value * insert (const _Key &k)
_Value * insert (const _Key &k, const _Value &v)
void remove (const _Key &k)
void clear ()
const iterator & end ()
iterator begin ()
size_t size ()
Private Member Functions
void _deleteBucket (bucket_type *b)
bucket_type * _newBucket (const _Key &k, bucket_type *p)
bucket_type * _newBucket (const _Key &k, const _Value &v, bucket_type *p)
bucket_type ** _parentBucket (const _Key &k) const
Private Attributes
indri::utility::RegionAllocator * _allocator
bucket_type ** _table
hash_type _hash
compare_type _compare
size_t _buckets
iterator _end
size_t _count
Friends
class HashTableIterator< _Key, _Value, _Comparator >
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>>
class indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >
Member Typedef Documentation
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> typedef HashBucket<_Key, _Value> indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::bucket_type
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> typedef _Comparator indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::compare_type
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> typedef _HashFunction indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::hash_type
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> typedef class HashTableIterator< _Key, _Value, _Comparator > indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::iterator
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> typedef _Key indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::key_type
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> typedef _Value indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::value_type
Constructor & Destructor Documentation
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::HashTable (size_t size = 16384, indri::utility::RegionAllocator * allocator = 0) [inline]
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::~HashTable () [inline]
Member Function Documentation
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> void indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_deleteBucket (bucket_type * b) [inline, private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::clear(), and indri::utility::HashTable< const char *, term_entry * >::remove().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> bucket_type* indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_newBucket (const _Key & k, const _Value & v, bucket_type * p) [inline, private]
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> bucket_type* indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_newBucket (const _Key & k, bucket_type * p) [inline, private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::insert().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> bucket_type** indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_parentBucket (const _Key & k) const [inline, private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::find(), indri::utility::HashTable< const char *, term_entry * >::insert(), and indri::utility::HashTable< const char *, term_entry * >::remove().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> iterator indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin () [inline]
Referenced by indri::parse::OffsetMetadataAnnotator::_cleanup(), indri::parse::OffsetAnnotationAnnotator::_cleanup(), indri::parse::Combiner::_hashToCorpusTable(), indri::parse::Conflater::_lookup(), indri::query::RelevanceModel::_scoreGrams(), indri::query::RelevanceModel::_sortGrams(), indri::parse::Combiner::_writeCorpusTable(), indri::collection::CompressedCollection::append(), indri::collection::CompressedCollection::close(), indri::parse::Combiner::combineRedirectDestinationBucket(), indri::collection::CompressedCollection::compact(), keys_to_vector(), indri::parse::Combiner::sortCorpusFiles(), indri::file::BulkTreeReader::~BulkTreeReader(), indri::parse::Conflater::~Conflater(), indri::query::RelevanceModel::~RelevanceModel(), and indri::parse::TaggedTextParser::~TaggedTextParser().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> void indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::clear () [inline]
Referenced by indri::parse::OffsetMetadataAnnotator::_cleanup(), indri::parse::OffsetAnnotationAnnotator::_cleanup(), indri::collection::CompressedCollection::close(), indri::parse::WARCRecord::readRecord(), indri::parse::Combiner::sortCorpusFiles(), and indri::utility::HashTable< const char *, term_entry * >::~HashTable().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> const iterator& indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end () [inline]
Referenced by indri::parse::OffsetMetadataAnnotator::_cleanup(), indri::parse::OffsetAnnotationAnnotator::_cleanup(), indri::parse::Combiner::_hashToCorpusTable(), indri::parse::Conflater::_lookup(), indri::query::RelevanceModel::_scoreGrams(), indri::query::RelevanceModel::_sortGrams(), indri::parse::Combiner::_writeCorpusTable(), indri::collection::CompressedCollection::append(), indri::collection::CompressedCollection::close(), indri::parse::Combiner::combineRedirectDestinationBucket(), indri::collection::CompressedCollection::compact(), keys_to_vector(), indri::parse::Combiner::sortCorpusFiles(), indri::file::BulkTreeReader::~BulkTreeReader(), indri::parse::Conflater::~Conflater(), indri::query::RelevanceModel::~RelevanceModel(), and indri::parse::TaggedTextParser::~TaggedTextParser().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> _Value* indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find (const _Key & k) const [inline]
Referenced by indri::index::IndexWriter::_buildTermTranslator(), indri::collection::CompressedCollection::_copyForwardLookup(), indri::collection::CompressedCollection::_copyReverseLookup(), indri::query::RelevanceModel::_countGrams(), indri::file::BulkTreeReader::_fetch(), indri::index::MemoryIndex::_fieldID(), indri::parse::TaggedTextParser::_findTag(), indri::parse::OffsetAnnotationAnnotator::_getAttribute(), indri::parse::OffsetAnnotationAnnotator::_getTag(), indri::parse::Combiner::_hashToCorpusTable(), indri::parse::Conflater::_lookup(), indri::index::MemoryIndex::_lookupTerm(), indri::parse::Combiner::_readLinks(), indri::parse::Combiner::_readRedirects(), indri::index::MemoryIndex::_writeFieldExtents(), indri::collection::CompressedCollection::addDocument(), indri::parse::Combiner::combineRedirectDestinationBucket(), indri::parse::Conflater::Conflater(), indri::index::MemoryIndex::docListIterator(), indri::index::MemoryIndex::documentCount(), indri::index::MemoryIndex::fieldDocumentCount(), indri::index::MemoryIndex::fieldTermCount(), indri::parse::WARCRecord::getMetadata(), indri::parse::OffsetMetadataAnnotator::open(), indri::parse::OffsetAnnotationAnnotator::open(), indri::parse::OffsetAnnotationAnnotator::readAnnotationTags(), indri::collection::CompressedCollection::retrieveIDByMetadatum(), indri::collection::CompressedCollection::retrieveMetadatum(), indri::parse::OffsetAnnotationAnnotator::setTags(), indri::parse::Combiner::sortCorpusFiles(), indri::index::MemoryIndex::term(), indri::index::MemoryIndex::termCount(), indri::parse::UTF8CaseNormalizationTransformation::transform(), indri::parse::OffsetMetadataAnnotator::transform(), and indri::parse::OffsetAnnotationAnnotator::transform().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> _Value* indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert (const _Key & k, const _Value & v) [inline]
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> _Value* indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert (const _Key & k) [inline]
Referenced by indri::parse::TaggedTextParser::_buildTag(), indri::index::IndexWriter::_buildTermTranslator(), indri::query::RelevanceModel::_countGrams(), indri::file::BulkTreeReader::_fetch(), indri::parse::Combiner::_hashToCorpusTable(), indri::parse::UTF8CaseNormalizationTransformation::_initHT(), indri::index::MemoryIndex::_lookupTerm(), indri::parse::Combiner::_readDocBucket(), indri::parse::Combiner::_readRedirects(), indri::index::MemoryIndex::_writeFieldExtents(), indri::parse::Conflater::Conflater(), indri::collection::CompressedCollection::create(), indri::index::MemoryIndex::MemoryIndex(), indri::parse::OffsetMetadataAnnotator::open(), indri::parse::OffsetAnnotationAnnotator::open(), indri::collection::CompressedCollection::open(), indri::collection::CompressedCollection::openRead(), indri::parse::OffsetAnnotationAnnotator::readAnnotationTags(), indri::parse::WARCRecord::readHeader(), indri::parse::OffsetAnnotationAnnotator::setTags(), indri::parse::Combiner::sortCorpusFiles(), and indri::parse::UTF8Transcoder::store_interval().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> void indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::remove (const _Key & k) [inline]
Referenced by indri::file::BulkTreeReader::_fetch(), and indri::parse::Combiner::_readRedirects().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> size_t indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::size () [inline]
Referenced by indri::file::BulkTreeReader::_fetch(), indri::parse::UTF8Transcoder::_initHT(), indri::parse::UTF8CaseNormalizationTransformation::_initHT(), and indri::utility::HashTable< const char *, term_entry * >::HashTable().
Friends And Related Function Documentation
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> friend class HashTableIterator< _Key, _Value, _Comparator > [friend]
Member Data Documentation
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> indri::utility::RegionAllocator* indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_allocator [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::_deleteBucket(), indri::utility::HashTable< const char *, term_entry * >::_newBucket(), indri::utility::HashTable< const char *, term_entry * >::clear(), and indri::utility::HashTable< const char *, term_entry * >::HashTable().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> size_t indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_buckets [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::_parentBucket(), indri::utility::HashTable< const char *, term_entry * >::begin(), indri::utility::HashTable< const char *, term_entry * >::clear(), and indri::utility::HashTable< const char *, term_entry * >::HashTable().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> compare_type indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_compare [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::find(), and indri::utility::HashTable< const char *, term_entry * >::remove().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> size_t indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_count [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::clear(), indri::utility::HashTable< const char *, term_entry * >::HashTable(), indri::utility::HashTable< const char *, term_entry * >::insert(), indri::utility::HashTable< const char *, term_entry * >::remove(), and indri::utility::HashTable< const char *, term_entry * >::size().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> iterator indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_end [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::end().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> hash_type indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_hash [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::_parentBucket().
template<class _Key, class _Value, class _HashFunction = GenericHash<_Key>, class _Comparator = GenericComparator<_Key>> bucket_type** indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::_table [private]
Referenced by indri::utility::HashTable< const char *, term_entry * >::_parentBucket(), indri::utility::HashTable< const char *, term_entry * >::begin(), indri::utility::HashTable< const char *, term_entry * >::clear(), indri::utility::HashTable< const char *, term_entry * >::HashTable(), and indri::utility::HashTable< const char *, term_entry * >::~HashTable().
The documentation for this class was generated from the following file:
HashTable.hpp