Indri: indri::lang::WeightedExtentOr Class Reference
indri::lang::WeightedExtentOr Class Reference
#include <QuerySpec.hpp>
Public Member Functions
WeightedExtentOr ()
WeightedExtentOr (const std::vector< double > &weights, const std::vector< RawExtentNode * > &children)
WeightedExtentOr (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void addChild (double weight, RawExtentNode *child)
std::vector< RawExtentNode * > & getChildren ()
std::vector< double > & getWeights ()
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
std::vector< RawExtentNode * > _children
std::vector< double > _weights
Constructor & Destructor Documentation
indri::lang::WeightedExtentOr::WeightedExtentOr () [inline]
Referenced by copy().
indri::lang::WeightedExtentOr::WeightedExtentOr (const std::vector< double > & weights, const std::vector< RawExtentNode * > & children) [inline]
indri::lang::WeightedExtentOr::WeightedExtentOr (Unpacker & unpacker) [inline]
References _children, _weights, indri::lang::Unpacker::getDoubleVector(), and indri::lang::Unpacker::getRawExtentVector().
Member Function Documentation
void indri::lang::WeightedExtentOr::addChild (double weight, RawExtentNode * child) [inline]
References _children, and _weights.
Referenced by copy(), and QueryParser::wsynNode().
Node* indri::lang::WeightedExtentOr::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _children, _weights, addChild(), indri::lang::Copier::after(), indri::lang::Copier::before(), and WeightedExtentOr().
std::vector<RawExtentNode*>& indri::lang::WeightedExtentOr::getChildren () [inline]
References _children.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
std::vector<double>& indri::lang::WeightedExtentOr::getWeights () [inline]
References _weights.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::WeightedExtentOr::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _children, and _weights.
bool indri::lang::WeightedExtentOr::operator== (Node & node) [inline]
void indri::lang::WeightedExtentOr::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, _weights, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::WeightedExtentOr::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _children.
std::string indri::lang::WeightedExtentOr::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::WeightedExtentOr::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
std::vector<RawExtentNode*> indri::lang::WeightedExtentOr::_children [private]
Referenced by addChild(), copy(), getChildren(), hashCode(), pack(), queryText(), walk(), and WeightedExtentOr().
std::vector<double> indri::lang::WeightedExtentOr::_weights [private]
Referenced by addChild(), copy(), getWeights(), hashCode(), pack(), and WeightedExtentOr().
The documentation for this class was generated from the following file:
QuerySpec.hpp