Indri: indri::parse::PageRank Class Reference
indri::parse::PageRank Class Reference
#include <PageRank.hpp>
Public Member Functions
PageRank (const std::string &corpusPath, const std::string &linkPath, UINT64 colLen=0)
PageRank (const std::string &corpusPath, const std::string &linkPath, const std::string &indexPath)
~PageRank ()
void computePageRank (const std::string &outputFile, const int maxIters=10, const int docsPerIter=1000, const double c=0.7)
void writeRaw (const std::string &dest, const std::string &fawFile)
void writePriors (const std::string &dest, const std::string &priorFile)
void writeRanks (const std::string &dest, const std::string &ranksFile)
void indexPageRank (const std::string &outputFile, const int maxIters=100, const double c=0.85)
Private Types
typedef std::map< std::string,
float > PageRankVector
typedef std::map< std::string,
std::pair< int, std::vector
< std::string > > > Links
Private Member Functions
void _swap (std::string &a, std::string &b)
bool _readLine (char *beginLine)
void _computeColLen ()
float _readPageRankFromFile (std::ifstream &src, const std::string &sourceDoc)
void _writePageRankToFile (std::ofstream &src, const std::string &destDoc, const float pr)
void _computeOutDegrees (Links &links)
void _doPageRankIter (const int docsPerIter, const std::string &srcFile, const std::string &destFile)
void _updatePageRank (std::ifstream &src, std::ofstream &dest, Links &links)
void _raw2int (std::vector< pagerank > &)
void _ranks2int (std::vector< prEntry > &ranks)
void _loadRanks (const std::string &dest, std::vector< pagerank > &pageranks)
Private Attributes
indri::utility::Buffer _gzbuffer
gzFile _in
float * prTable
const std::string _corpusPath
const std::string _linkPath
double _c
UINT64 _colLen
indri::collection::Repository _repository
Static Private Attributes
static const double _intToProb [11]
Member Typedef Documentation
typedef std::map< std::string, std::pair< int, std::vector< std::string > > > indri::parse::PageRank::Links [private]
typedef std::map< std::string, float > indri::parse::PageRank::PageRankVector [private]
Constructor & Destructor Documentation
indri::parse::PageRank::PageRank (const std::string & corpusPath, const std::string & linkPath, UINT64 colLen = 0) [inline]
References _colLen, and _computeColLen().
indri::parse::PageRank::PageRank (const std::string & corpusPath, const std::string & linkPath, const std::string & indexPath) [inline]
References _colLen, _repository, indri::collection::Repository::indexes(), and indri::collection::Repository::openRead().
indri::parse::PageRank::~PageRank () [inline]
References _in, and prTable.
Member Function Documentation
void indri::parse::PageRank::_computeColLen () [private]
References _colLen, _corpusPath, indri::parse::TaggedDocumentIterator::close(), indri::file::FileTreeIterator::end(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::TaggedDocumentIterator::open(), and indri::parse::TaggedDocumentIterator::setTags().
Referenced by PageRank().
void indri::parse::PageRank::_computeOutDegrees (Links & links) [private]
References _in, _linkPath, _readLine(), indri::file::FileTreeIterator::end(), and input().
Referenced by _doPageRankIter().
void indri::parse::PageRank::_doPageRankIter (const int docsPerIter, const std::string & srcFile, const std::string & destFile) [private]
References _computeOutDegrees(), _corpusPath, _in, _linkPath, _readLine(), _updatePageRank(), indri::file::Path::combine(), indri::file::FileTreeIterator::end(), input(), and indri::file::Path::relative().
Referenced by computePageRank().
void indri::parse::PageRank::_loadRanks (const std::string & dest, std::vector< pagerank > & pageranks) [private]
References indri::parse::pagerank::doc, and indri::parse::pagerank::val.
Referenced by writePriors(), writeRanks(), and writeRaw().
void indri::parse::PageRank::_ranks2int (std::vector< prEntry > & ranks) [private]
Referenced by writePriors(), writeRanks(), and writeRaw().
void indri::parse::PageRank::_raw2int (std::vector< pagerank > & ranks) [private]
Referenced by writePriors(), and writeRanks().
bool indri::parse::PageRank::_readLine (char * beginLine) [private]
References _gzbuffer, _in, indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::position(), indri::utility::Buffer::size(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by _computeOutDegrees(), _doPageRankIter(), and indexPageRank().
float indri::parse::PageRank::_readPageRankFromFile (std::ifstream & src, const std::string & sourceDoc) [private]
References _c, and _colLen.
Referenced by _updatePageRank().
void indri::parse::PageRank::_swap (std::string & a, std::string & b) [inline, private]
Referenced by computePageRank().
void indri::parse::PageRank::_updatePageRank (std::ifstream & src, std::ofstream & dest, Links & links) [private]
References _c, _colLen, _readPageRankFromFile(), and _writePageRankToFile().
Referenced by _doPageRankIter().
void indri::parse::PageRank::_writePageRankToFile (std::ofstream & src, const std::string & destDoc, const float pr) [private]
Referenced by _updatePageRank().
void indri::parse::PageRank::computePageRank (const std::string & outputFile, const int maxIters = 10, const int docsPerIter = 1000, const double c = 0.7)
References _c, _doPageRankIter(), and _swap().
Referenced by main().
void indri::parse::PageRank::indexPageRank (const std::string & outputFile, const int maxIters = 100, const double c = 0.85)
References _c, _colLen, _corpusPath, _in, _linkPath, _readLine(), _repository, indri::file::File::close(), indri::collection::Repository::collection(), indri::file::Path::combine(), indri::file::File::create(), indri::file::FileTreeIterator::end(), indri::file::SequentialWriteBuffer::flush(), input(), indri::file::File::openRead(), prTable, indri::file::SequentialReadBuffer::read(), indri::file::Path::relative(), indri::file::SequentialWriteBuffer::tell(), and indri::file::SequentialWriteBuffer::write().
Referenced by main().
void indri::parse::PageRank::writePriors (const std::string & dest, const std::string & priorFile)
References _colLen, _intToProb, _loadRanks(), _ranks2int(), _raw2int(), _repository, indri::collection::Repository::collection(), indri::parse::prEntry::doc, prTable, and indri::parse::prEntry::val.
Referenced by main().
void indri::parse::PageRank::writeRanks (const std::string & dest, const std::string & ranksFile)
References _colLen, _loadRanks(), _ranks2int(), _raw2int(), _repository, indri::collection::Repository::collection(), indri::parse::prEntry::doc, prTable, and indri::parse::prEntry::val.
Referenced by main().
void indri::parse::PageRank::writeRaw (const std::string & dest, const std::string & fawFile)
References _colLen, _loadRanks(), _ranks2int(), _repository, indri::collection::Repository::collection(), indri::parse::prEntry::doc, prTable, and indri::parse::prEntry::val.
Referenced by main().
Member Data Documentation
double indri::parse::PageRank::_c [private]
Referenced by _readPageRankFromFile(), _updatePageRank(), computePageRank(), and indexPageRank().
UINT64 indri::parse::PageRank::_colLen [private]
Referenced by _computeColLen(), _readPageRankFromFile(), _updatePageRank(), indexPageRank(), PageRank(), writePriors(), writeRanks(), and writeRaw().
const std::string indri::parse::PageRank::_corpusPath [private]
Referenced by _computeColLen(), _doPageRankIter(), and indexPageRank().
indri::utility::Buffer indri::parse::PageRank::_gzbuffer [private]
Referenced by _readLine().
gzFile indri::parse::PageRank::_in [private]
Referenced by _computeOutDegrees(), _doPageRankIter(), _readLine(), indexPageRank(), and ~PageRank().
const double indri::parse::PageRank::_intToProb [static, private]
Initial value:
 {log(2.21916E-10),
                                          log(2.21916E-10),
                                          log(5.61952E-10),
                                          log(1.94786E-09),
                                          log(3.62742E-09),
                                          log(1.00745E-08),
                                          log(1.97616E-08),
                                          log(3.46944E-08),
                                          log(4.39146E-08),
                                          log(1.74226E-07),
                                          log(2.28983E-07) }
Referenced by writePriors().
const std::string indri::parse::PageRank::_linkPath [private]
Referenced by _computeOutDegrees(), _doPageRankIter(), and indexPageRank().
indri::collection::Repository indri::parse::PageRank::_repository [private]
Referenced by indexPageRank(), PageRank(), writePriors(), writeRanks(), and writeRaw().
float* indri::parse::PageRank::prTable [private]
Referenced by indexPageRank(), writePriors(), writeRanks(), writeRaw(), and ~PageRank().
The documentation for this class was generated from the following files:
PageRank.hpp
PageRank.cpp