Indri: indri::infnet::NotNode Class Reference
indri::infnet::NotNode Class Reference
#include <NotNode.hpp>
Public Member Functions
NotNode (const std::string &name, BeliefNode *child)
double maximumBackgroundScore ()
double maximumScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
virtual void setSiblingsFlag (int f)
Private Attributes
BeliefNode * _child
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _extents
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::NotNode::NotNode (const std::string & name, BeliefNode * child)
Member Function Documentation
void indri::infnet::NotNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _child, indri::infnet::Annotator::add(), and indri::infnet::BeliefNode::annotate().
const std::string & indri::infnet::NotNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::NotNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _matches, indri::infnet::BeliefNode::hasMatch(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::NotNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::hasMatch().
void indri::infnet::NotNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::NotNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::maximumBackgroundScore().
double indri::infnet::NotNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
lemur::api::DOCID_T indri::infnet::NotNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::NotNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _extents, indri::index::Extent::begin, indri::api::ScoredExtentResult::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::index::Extent::end, indri::api::ScoredExtentResult::end, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, indri::infnet::BeliefNode::score(), and indri::utility::greedy_vector< _Type, _Count >::size().
virtual void indri::infnet::NotNode::setSiblingsFlag (int f) [inline, virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _child, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
BeliefNode* indri::infnet::NotNode::_child [private]
Referenced by annotate(), hasMatch(), maximumBackgroundScore(), score(), and setSiblingsFlag().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::NotNode::_extents [private]
Referenced by score().
indri::utility::greedy_vector<bool> indri::infnet::NotNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::NotNode::_name [private]
Referenced by getName().
The documentation for this class was generated from the following files:
NotNode.hpp
NotNode.cpp