Indri: indri::index::DiskDocListIterator Class Reference
indri::index::DiskDocListIterator Class Reference
#include <DiskDocListIterator.hpp>
Public Member Functions
DiskDocListIterator (indri::file::SequentialReadBuffer *buffer, UINT64 startOffset, int fieldCount)
~DiskDocListIterator ()
void setStartOffset (UINT64 startOffset, TermData *termData)
const
indri::utility::greedy_vector
< TopDocument > & topDocuments ()
void startIteration ()
bool nextEntry ()
bool nextEntry (lemur::api::DOCID_T documentID)
DocumentData * currentEntry ()
bool finished ()
bool isFrequent () const
TermData * termData ()
Private Member Functions
void _readEntry ()
void _readSkip ()
void _readTopdocs ()
void _readTermData (int headerLength)
Private Attributes
const char * _list
const char * _listEnd
lemur::api::DOCID_T _skipDocument
indri::file::SequentialReadBuffer * _file
UINT64 _startOffset
UINT64 _endOffset
bool _hasTopdocs
bool _isFrequent
indri::utility::greedy_vector
< TopDocument > _topdocs
DocumentData _data
DocumentData * _result
TermData * _termData
bool _ownTermData
char _term [lemur::file::Keyfile::MAX_KEY_LENGTH+1]
int _fieldCount
Constructor & Destructor Documentation
indri::index::DiskDocListIterator::DiskDocListIterator (indri::file::SequentialReadBuffer * buffer, UINT64 startOffset, int fieldCount)
indri::index::DiskDocListIterator::~DiskDocListIterator ()
References _file, _ownTermData, and _termData.
Member Function Documentation
void indri::index::DiskDocListIterator::_readEntry () [inline, private]
References _data, _list, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListIterator::DocumentData::document, indri::index::DocListIterator::DocumentData::positions, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by nextEntry(), and startIteration().
void indri::index::DiskDocListIterator::_readSkip () [inline, private]
References _data, _file, _list, _listEnd, _skipDocument, indri::index::DocListIterator::DocumentData::document, and indri::file::SequentialReadBuffer::read().
Referenced by nextEntry(), and startIteration().
void indri::index::DiskDocListIterator::_readTermData (int headerLength) [private]
References _fieldCount, _file, _ownTermData, _term, _termData, indri::utility::Buffer::front(), indri::file::SequentialReadBuffer::position(), indri::utility::Buffer::position(), indri::file::SequentialReadBuffer::read(), indri::file::SequentialReadBuffer::seek(), termdata_decompress(), termdata_size(), and indri::utility::Buffer::write().
Referenced by startIteration().
void indri::index::DiskDocListIterator::_readTopdocs () [private]
References _file, _hasTopdocs, _topdocs, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::file::SequentialReadBuffer::read().
Referenced by startIteration().
indri::index::DiskDocListIterator::DocumentData * indri::index::DiskDocListIterator::currentEntry () [virtual]
Implements indri::index::DocListIterator.
References _result.
bool indri::index::DiskDocListIterator::finished () [virtual]
Implements indri::index::DocListIterator.
References _result.
bool indri::index::DiskDocListIterator::isFrequent () const
References _isFrequent.
Referenced by indri::index::IndexWriter::_storeMatchInformation().
bool indri::index::DiskDocListIterator::nextEntry (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::DocListIterator.
References _data, _readSkip(), _skipDocument, indri::index::DocListIterator::DocumentData::document, and nextEntry().
bool indri::index::DiskDocListIterator::nextEntry () [virtual]
Implements indri::index::DocListIterator.
References _list, _listEnd, _readEntry(), _readSkip(), _result, and _skipDocument.
Referenced by nextEntry().
void indri::index::DiskDocListIterator::setStartOffset (UINT64 startOffset, TermData * termData)
References _file, _ownTermData, _startOffset, _termData, _topdocs, indri::utility::greedy_vector< _Type, _Count >::clear(), and indri::file::SequentialReadBuffer::seek().
Referenced by indri::index::DiskDocListFileIterator::_readEntry().
void indri::index::DiskDocListIterator::startIteration () [virtual]
Implements indri::index::DocListIterator.
References _data, _file, _hasTopdocs, _isFrequent, _list, _listEnd, _readEntry(), _readSkip(), _readTermData(), _readTopdocs(), _result, _skipDocument, _startOffset, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::parse::CharClass::control, indri::index::DocListIterator::DocumentData::document, indri::index::DocListIterator::DocumentData::positions, indri::file::SequentialReadBuffer::read(), and indri::file::SequentialReadBuffer::seek().
Referenced by indri::index::DiskDocListFileIterator::_readEntry().
indri::index::TermData * indri::index::DiskDocListIterator::termData () [virtual]
Implements indri::index::DocListIterator.
References _termData.
const indri::utility::greedy_vector< indri::index::DocListIterator::TopDocument > & indri::index::DiskDocListIterator::topDocuments () [virtual]
Implements indri::index::DocListIterator.
References _topdocs.
Member Data Documentation
DocumentData indri::index::DiskDocListIterator::_data [private]
Referenced by _readEntry(), _readSkip(), nextEntry(), and startIteration().
UINT64 indri::index::DiskDocListIterator::_endOffset [private]
int indri::index::DiskDocListIterator::_fieldCount [private]
Referenced by _readTermData().
indri::file::SequentialReadBuffer* indri::index::DiskDocListIterator::_file [private]
Referenced by _readSkip(), _readTermData(), _readTopdocs(), setStartOffset(), startIteration(), and ~DiskDocListIterator().
bool indri::index::DiskDocListIterator::_hasTopdocs [private]
Referenced by _readTopdocs(), and startIteration().
bool indri::index::DiskDocListIterator::_isFrequent [private]
Referenced by isFrequent(), and startIteration().
const char* indri::index::DiskDocListIterator::_list [private]
Referenced by _readEntry(), _readSkip(), nextEntry(), and startIteration().
const char* indri::index::DiskDocListIterator::_listEnd [private]
Referenced by _readSkip(), nextEntry(), and startIteration().
bool indri::index::DiskDocListIterator::_ownTermData [private]
Referenced by _readTermData(), setStartOffset(), and ~DiskDocListIterator().
DocumentData* indri::index::DiskDocListIterator::_result [private]
Referenced by currentEntry(), finished(), nextEntry(), and startIteration().
lemur::api::DOCID_T indri::index::DiskDocListIterator::_skipDocument [private]
Referenced by _readSkip(), nextEntry(), and startIteration().
UINT64 indri::index::DiskDocListIterator::_startOffset [private]
Referenced by setStartOffset(), and startIteration().
char indri::index::DiskDocListIterator::_term[lemur::file::Keyfile::MAX_KEY_LENGTH+1] [private]
Referenced by _readTermData().
TermData* indri::index::DiskDocListIterator::_termData [private]
Referenced by _readTermData(), setStartOffset(), termData(), and ~DiskDocListIterator().
indri::utility::greedy_vector<TopDocument> indri::index::DiskDocListIterator::_topdocs [private]
Referenced by _readTopdocs(), setStartOffset(), and topDocuments().
The documentation for this class was generated from the following files:
DiskDocListIterator.hpp
DiskDocListIterator.cpp