Indri: indri::collection::RepositoryMaintenanceThread Class Reference
indri::collection::RepositoryMaintenanceThread Class Reference
#include <RepositoryMaintenanceThread.hpp>
Public Member Functions
RepositoryMaintenanceThread (class Repository &repository, UINT64 memory)
UINT64 initialize ()
UINT64 work ()
bool hasWork ()
void deinitialize ()
void write ()
void merge ()
Private Types
enum { WRITE, MERGE, TRIM }
Private Attributes
class Repository & _repository
indri::thread::Mutex _requestLock
std::queue< int > _requests
UINT64 _memory
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
WRITE
MERGE
TRIM
Constructor & Destructor Documentation
indri::collection::RepositoryMaintenanceThread::RepositoryMaintenanceThread (class Repository & repository, UINT64 memory)
Member Function Documentation
void indri::collection::RepositoryMaintenanceThread::deinitialize () [virtual]
Implements indri::thread::UtilityThread.
bool indri::collection::RepositoryMaintenanceThread::hasWork () [virtual]
Implements indri::thread::UtilityThread.
References _requestLock, and _requests.
UINT64 indri::collection::RepositoryMaintenanceThread::initialize () [virtual]
Implements indri::thread::UtilityThread.
References TIME_DELAY.
void indri::collection::RepositoryMaintenanceThread::merge ()
References _requestLock, _requests, and MERGE.
Referenced by indri::collection::Repository::merge(), and work().
UINT64 indri::collection::RepositoryMaintenanceThread::work () [virtual]
Implements indri::thread::UtilityThread.
References _memory, indri::collection::Repository::_merge(), indri::collection::Repository::_mergeFiles(), _repository, _requestLock, _requests, indri::collection::Repository::_setThrashing(), indri::collection::Repository::_timeSinceThrashing(), indri::collection::Repository::_trim(), indri::collection::Repository::_write(), indri::collection::Repository::documentLoad(), indri::collection::Repository::indexes(), maintenance_should_merge(), maintenance_should_trim(), indri::index::DiskIndex::MAX_DOCLENGTHS_CACHE, indri::index::MemoryIndex::memorySize(), MERGE, merge(), MERGE_FILE_LIMIT, indri::collection::Repository::queryLoad(), SHORT_TIME_DELAY, TIME_DELAY, TRIM, trim(), WRITE, and write().
void indri::collection::RepositoryMaintenanceThread::write ()
References _requestLock, _requests, and WRITE.
Referenced by work(), and indri::collection::Repository::write().
Member Data Documentation
UINT64 indri::collection::RepositoryMaintenanceThread::_memory [private]
Referenced by work().
class Repository& indri::collection::RepositoryMaintenanceThread::_repository [private]
Referenced by work().
indri::thread::Mutex indri::collection::RepositoryMaintenanceThread::_requestLock [private]
Referenced by hasWork(), merge(), work(), and write().
std::queue<int> indri::collection::RepositoryMaintenanceThread::_requests [private]
Referenced by hasWork(), merge(), work(), and write().
The documentation for this class was generated from the following files:
RepositoryMaintenanceThread.hpp
RepositoryMaintenanceThread.cpp