Indri: indri::parse::KrovetzStemmer Class Reference
indri::parse::KrovetzStemmer Class Reference
#include <KrovetzStemmer.hpp>
Classes
struct cacheEntry
Two term hashtable entry for caching across calls.
struct dictEntry
Dictionary table entry.
struct eqstr
Public Member Functions
KrovetzStemmer ()
~KrovetzStemmer ()
char * kstem_stemmer (char *term)
stem a term using the Krovetz algorithm. The stem returned may be longer than the input term. May return a pointer to the private attribute stem. Performs case normalization on its input argument. Return values should be copied before calling the method again.
int kstem_stem_tobuffer (char *term, char *buffer)
stem a term using the Krovetz algorithm into the specified buffer. The stem returned may be longer than the input term. Performs case normalization on its input argument.
void kstem_add_table_entry (const char *variant, const char *word, bool exc=false)
Add an entry to the stemmer's dictionary table.
Static Public Attributes
static const int MAX_WORD_LENGTH = 25
maximum number of characters in a word to be stemmed.
Private Types
typedef struct
indri::parse::KrovetzStemmer::dictEntry dictEntry
Dictionary table entry.
typedef struct
indri::parse::KrovetzStemmer::cacheEntry cacheEntry
Two term hashtable entry for caching across calls.
typedef hash_map< const char
*, dictEntry, hash< const char * >
, eqstr > dictTable
Private Member Functions
bool ends (const char *s, int sufflen)
void setsuff (const char *str, int length)
dictEntry * getdep (char *word)
bool lookup (char *word)
bool cons (int i)
bool vowelinstem ()
bool vowel (int i)
bool doublec (int i)
void plural ()
void past_tense ()
void aspect ()
void ion_endings ()
void er_and_or_endings ()
void ly_endings ()
void al_endings ()
void ive_endings ()
void ize_endings ()
void ment_endings ()
void ity_endings ()
void ble_endings ()
void ness_endings ()
void ism_endings ()
void ic_endings ()
void ncy_endings ()
void nce_endings ()
void loadTables ()
Private Attributes
indri::thread::Mutex _stemLock
lock for protecting stem calls
dictTable dictEntries
cacheEntry * stemCache
int stemhtsize
int k
int j
char * word
char stem [MAX_WORD_LENGTH]
Member Typedef Documentation
typedef struct indri::parse::KrovetzStemmer::cacheEntry indri::parse::KrovetzStemmer::cacheEntry [private]
Two term hashtable entry for caching across calls.
typedef struct indri::parse::KrovetzStemmer::dictEntry indri::parse::KrovetzStemmer::dictEntry [private]
Dictionary table entry.
typedef hash_map<const char *, dictEntry, hash<const char *>, eqstr> indri::parse::KrovetzStemmer::dictTable [private]
Constructor & Destructor Documentation
indri::parse::KrovetzStemmer::KrovetzStemmer ()
References indri::parse::KrovetzStemmer::cacheEntry::flag, loadTables(), indri::parse::KrovetzStemmer::cacheEntry::stem1, indri::parse::KrovetzStemmer::cacheEntry::stem2, stemCache, stemhtsize, indri::parse::KrovetzStemmer::cacheEntry::word1, and indri::parse::KrovetzStemmer::cacheEntry::word2.
indri::parse::KrovetzStemmer::~KrovetzStemmer ()
References stemCache.
Member Function Documentation
void indri::parse::KrovetzStemmer::al_endings () [inline, private]
References doublec(), ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::aspect () [inline, private]
References cons(), doublec(), ends_in, indri::parse::KrovetzStemmer::dictEntry::exception, getdep(), j, k, lookup(), vowelinstem(), word, and wordlength.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ble_endings () [inline, private]
References doublec(), ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
bool indri::parse::KrovetzStemmer::cons (int i) [inline, private]
References word.
Referenced by aspect(), doublec(), and vowel().
bool indri::parse::KrovetzStemmer::doublec (int i) [inline, private]
References cons(), and word.
Referenced by al_endings(), aspect(), ble_endings(), er_and_or_endings(), ize_endings(), and past_tense().
bool indri::parse::KrovetzStemmer::ends (const char * s, int sufflen) [inline, private]
References j, k, word, and wordlength.
void indri::parse::KrovetzStemmer::er_and_or_endings () [inline, private]
References doublec(), ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
KrovetzStemmer::dictEntry * indri::parse::KrovetzStemmer::getdep (char * word) [inline, private]
References dictEntries.
Referenced by aspect(), kstem_stem_tobuffer(), lookup(), and past_tense().
void indri::parse::KrovetzStemmer::ic_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ion_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ism_endings () [inline, private]
References ends_in, j, k, and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ity_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ive_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ize_endings () [inline, private]
References doublec(), ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::kstem_add_table_entry (const char * variant, const char * word, bool exc = false)
Add an entry to the stemmer's dictionary table.
Parameters:
variant the spelling for the entry.
word the stem to use for the variant. If "", the variant stems to itself.
exc Is the word an exception to the spelling rules.
References dictEntries, indri::parse::KrovetzStemmer::dictEntry::exception, and indri::parse::KrovetzStemmer::dictEntry::root.
Referenced by indri::parse::KrovetzStemmerTransformation::KrovetzStemmerTransformation(), and loadTables().
int indri::parse::KrovetzStemmer::kstem_stem_tobuffer (char * term, char * buffer)
stem a term using the Krovetz algorithm into the specified buffer. The stem returned may be longer than the input term. Performs case normalization on its input argument.
Parameters:
term the term to stem
buffer the buffer to hold the stemmed term. The buffer should be at MAX_WORD_LENGTH or larger.
Returns:
the number of characters written to the buffer, including the terminating '\0'. If 0, the caller should use the value in term.
References al_endings(), aspect(), ble_endings(), er_and_or_endings(), indri::parse::KrovetzStemmer::cacheEntry::flag, getdep(), ic_endings(), ion_endings(), ism_endings(), ity_endings(), ive_endings(), ize_endings(), k, ly_endings(), MAX_WORD_LENGTH, ment_endings(), nce_endings(), ncy_endings(), ness_endings(), past_tense(), plural(), indri::parse::KrovetzStemmer::dictEntry::root, stemCache, stemhash, and word.
Referenced by indri::parse::KrovetzStemmerTransformation::_processTerms(), and kstem_stemmer().
char * indri::parse::KrovetzStemmer::kstem_stemmer (char * term)
stem a term using the Krovetz algorithm. The stem returned may be longer than the input term. May return a pointer to the private attribute stem. Performs case normalization on its input argument. Return values should be copied before calling the method again.
Parameters:
term the term to stem
Returns:
the stemmed term or the original term if no stemming was performed.
References kstem_stem_tobuffer(), and stem.
void indri::parse::KrovetzStemmer::loadTables () [private]
References indri::parse::conflations, indri::parse::exceptions, indri::parse::headwords, kstem_add_table_entry(), indri::parse::conflation_pair::variant, and word.
Referenced by KrovetzStemmer().
bool indri::parse::KrovetzStemmer::lookup (char * word) [inline, private]
References getdep().
Referenced by al_endings(), aspect(), ble_endings(), er_and_or_endings(), ic_endings(), ion_endings(), ity_endings(), ive_endings(), ize_endings(), ly_endings(), ment_endings(), nce_endings(), ncy_endings(), past_tense(), and plural().
void indri::parse::KrovetzStemmer::ly_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ment_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::nce_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ncy_endings () [inline, private]
References ends_in, j, k, lookup(), and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::ness_endings () [inline, private]
References ends_in, j, k, and word.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::past_tense () [inline, private]
References doublec(), ends_in, indri::parse::KrovetzStemmer::dictEntry::exception, getdep(), j, k, lookup(), setsuffix, vowelinstem(), word, and wordlength.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::plural () [inline, private]
References ends_in, final_c, j, k, lookup(), penult_c, setsuffix, word, and wordlength.
Referenced by kstem_stem_tobuffer().
void indri::parse::KrovetzStemmer::setsuff (const char * str, int length) [inline, private]
References j, k, and word.
bool indri::parse::KrovetzStemmer::vowel (int i) [inline, private]
References cons().
Referenced by vowelinstem().
bool indri::parse::KrovetzStemmer::vowelinstem () [inline, private]
References stemlength, and vowel().
Referenced by aspect(), and past_tense().
Member Data Documentation
indri::thread::Mutex indri::parse::KrovetzStemmer::_stemLock [private]
lock for protecting stem calls
dictTable indri::parse::KrovetzStemmer::dictEntries [private]
Referenced by getdep(), and kstem_add_table_entry().
int indri::parse::KrovetzStemmer::j [private]
Referenced by al_endings(), aspect(), ble_endings(), ends(), er_and_or_endings(), ic_endings(), ion_endings(), ism_endings(), ity_endings(), ive_endings(), ize_endings(), ly_endings(), ment_endings(), nce_endings(), ncy_endings(), ness_endings(), past_tense(), plural(), and setsuff().
int indri::parse::KrovetzStemmer::k [private]
Referenced by al_endings(), aspect(), ble_endings(), ends(), er_and_or_endings(), ic_endings(), ion_endings(), ism_endings(), ity_endings(), ive_endings(), ize_endings(), kstem_stem_tobuffer(), ly_endings(), ment_endings(), nce_endings(), ncy_endings(), ness_endings(), past_tense(), plural(), and setsuff().
const int indri::parse::KrovetzStemmer::MAX_WORD_LENGTH = 25 [static]
maximum number of characters in a word to be stemmed.
Referenced by kstem_stem_tobuffer().
char indri::parse::KrovetzStemmer::stem[MAX_WORD_LENGTH] [private]
Referenced by kstem_stemmer().
cacheEntry* indri::parse::KrovetzStemmer::stemCache [private]
Referenced by KrovetzStemmer(), kstem_stem_tobuffer(), and ~KrovetzStemmer().
int indri::parse::KrovetzStemmer::stemhtsize [private]
Referenced by KrovetzStemmer().
char* indri::parse::KrovetzStemmer::word [private]
Referenced by al_endings(), aspect(), ble_endings(), cons(), doublec(), ends(), er_and_or_endings(), ic_endings(), ion_endings(), ism_endings(), ity_endings(), ive_endings(), ize_endings(), kstem_stem_tobuffer(), loadTables(), ly_endings(), ment_endings(), nce_endings(), ncy_endings(), ness_endings(), past_tense(), plural(), and setsuff().
The documentation for this class was generated from the following files:
KrovetzStemmer.hpp
KrovetzStemmer.cpp