Indri: indri::parse::UTF8CaseNormalizationTransformation Class Reference
indri::parse::UTF8CaseNormalizationTransformation Class Reference
#include <UTF8CaseNormalizationTransformation.hpp>
Public Member Functions
UTF8CaseNormalizationTransformation ()
~UTF8CaseNormalizationTransformation ()
void handle (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
Private Member Functions
void _initHT ()
Private Attributes
ObjectHandler
< indri::api::ParsedDocument > * _handler
UTF8Transcoder _transcoder
std::vector< char * > _buffers_allocated
indri::utility::HashTable
< UINT64, UINT64 > _downcase
Constructor & Destructor Documentation
indri::parse::UTF8CaseNormalizationTransformation::UTF8CaseNormalizationTransformation ()
References _initHT().
indri::parse::UTF8CaseNormalizationTransformation::~UTF8CaseNormalizationTransformation ()
References _buffers_allocated.
Member Function Documentation
void indri::parse::UTF8CaseNormalizationTransformation::_initHT () [private]
References _downcase, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), case_pair::lower, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::size(), and case_pair::upper.
Referenced by UTF8CaseNormalizationTransformation().
void indri::parse::UTF8CaseNormalizationTransformation::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::UTF8CaseNormalizationTransformation::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::UTF8CaseNormalizationTransformation::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _buffers_allocated, _downcase, _transcoder, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::terms, indri::parse::UTF8Transcoder::utf8_decode(), and indri::parse::UTF8Transcoder::utf8_encode().
Referenced by handle().
Member Data Documentation
std::vector<char*> indri::parse::UTF8CaseNormalizationTransformation::_buffers_allocated [private]
Referenced by transform(), and ~UTF8CaseNormalizationTransformation().
indri::utility::HashTable<UINT64,UINT64> indri::parse::UTF8CaseNormalizationTransformation::_downcase [private]
Referenced by _initHT(), and transform().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::UTF8CaseNormalizationTransformation::_handler [private]
Referenced by handle(), and setHandler().
UTF8Transcoder indri::parse::UTF8CaseNormalizationTransformation::_transcoder [private]
Referenced by transform().
The documentation for this class was generated from the following files:
UTF8CaseNormalizationTransformation.hpp
UTF8CaseNormalizationTransformation.cpp