Indri: indri::net::NetworkListener Class Reference
indri::net::NetworkListener Class Reference
#include <NetworkListener.hpp>
Public Member Functions
NetworkListener ()
~NetworkListener ()
bool listen (unsigned int port)
NetworkStream * accept ()
void close ()
Private Attributes
socket_t _socket
Constructor & Destructor Documentation
indri::net::NetworkListener::NetworkListener () [inline]
indri::net::NetworkListener::~NetworkListener () [inline]
References close().
Member Function Documentation
NetworkStream* indri::net::NetworkListener::accept () [inline]
References _socket.
Referenced by main().
void indri::net::NetworkListener::close () [inline]
References _socket.
Referenced by listen(), and ~NetworkListener().
bool indri::net::NetworkListener::listen (unsigned int port) [inline]
References _socket, close(), and i64_to_string().
Referenced by main().
Member Data Documentation
socket_t indri::net::NetworkListener::_socket [private]
Referenced by accept(), close(), and listen().
The documentation for this class was generated from the following file:
NetworkListener.hpp