Indri: indri::lang::LengthPrior Class Reference
indri::lang::LengthPrior Class Reference
#include <QuerySpec.hpp>
Public Member Functions
LengthPrior (ScoredExtentNode *child, double exponent)
LengthPrior (Unpacker &unpacker)
std::string queryText () const
std::string nodeType ()
void setExponent (double exponent)
double getExponent ()
ScoredExtentNode * getChild ()
virtual UINT64 hashCode () const
void walk (Walker &walker)
indri::lang::Node * copy (Copier &copier)
void pack (Packer &packer)
Private Attributes
double _exponent
ScoredExtentNode * _child
Constructor & Destructor Documentation
indri::lang::LengthPrior::LengthPrior (ScoredExtentNode * child, double exponent) [inline]
Referenced by copy().
indri::lang::LengthPrior::LengthPrior (Unpacker & unpacker) [inline]
References _child, _exponent, indri::lang::Unpacker::getDouble(), and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
indri::lang::Node* indri::lang::LengthPrior::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _child, _exponent, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and LengthPrior().
ScoredExtentNode* indri::lang::LengthPrior::getChild () [inline]
References _child.
Referenced by indri::lang::UnnecessaryNodeRemoverCopier::after(), and indri::infnet::InferenceNetworkBuilder::after().
double indri::lang::LengthPrior::getExponent () [inline]
References _exponent.
Referenced by indri::lang::UnnecessaryNodeRemoverCopier::after(), and indri::infnet::InferenceNetworkBuilder::after().
virtual UINT64 indri::lang::LengthPrior::hashCode () const [inline, virtual]
Implements indri::lang::Node.
std::string indri::lang::LengthPrior::nodeType () [inline]
void indri::lang::LengthPrior::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _child, _exponent, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::LengthPrior::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _exponent.
void indri::lang::LengthPrior::setExponent (double exponent) [inline]
References _exponent.
Referenced by indri::lang::SmoothingAnnotatorWalker::after().
void indri::lang::LengthPrior::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _child, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::LengthPrior::_child [private]
Referenced by copy(), getChild(), LengthPrior(), pack(), and walk().
double indri::lang::LengthPrior::_exponent [private]
Referenced by copy(), getExponent(), LengthPrior(), pack(), queryText(), and setExponent().
The documentation for this class was generated from the following file:
QuerySpec.hpp