Indri: indri::file::BulkTreeReader Class Reference
indri::file::BulkTreeReader Class Reference
#include <BulkTree.hpp>
Public Member Functions
BulkTreeReader ()
BulkTreeReader (File &file)
BulkTreeReader (File &file, UINT64 length)
~BulkTreeReader ()
void openRead (const std::string &filename)
bool get (const char *key, char *value, int &actual, int valueLength)
bool get (const char *key, int keyLength, char *value, int &actual, int valueLength)
bool get (UINT32 key, char *value, int &actual, int valueLength)
void close ()
BulkTreeIterator * iterator ()
BulkTreeIterator * findFirst (const char *key)
Private Member Functions
BulkBlock * _fetch (UINT32 id)
Private Attributes
File * _file
UINT64 _fileLength
bool _ownFile
BulkBlock * _head
BulkBlock * _tail
indri::utility::HashTable
< UINT32, BulkBlock * > _cache
Constructor & Destructor Documentation
indri::file::BulkTreeReader::BulkTreeReader ()
indri::file::BulkTreeReader::BulkTreeReader (File & file)
indri::file::BulkTreeReader::BulkTreeReader (File & file, UINT64 length)
indri::file::BulkTreeReader::~BulkTreeReader ()
References _cache, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Member Function Documentation
indri::file::BulkBlock * indri::file::BulkTreeReader::_fetch (UINT32 id) [private]
References _cache, _file, _fileLength, _head, _tail, indri::file::BulkBlock::data(), indri::file::BulkBlock::dataSize(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::file::BulkBlock::getID(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::file::BulkBlock::link(), indri::file::BulkBlock::previous(), indri::file::File::read(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::remove(), indri::file::BulkBlock::setID(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::size(), and indri::file::BulkBlock::unlink().
Referenced by findFirst(), and get().
void indri::file::BulkTreeReader::close ()
References _file, _ownFile, and indri::file::File::close().
Referenced by indri::index::IndexWriter::_closeFiles(), and indri::index::DiskIndex::close().
indri::file::BulkTreeIterator * indri::file::BulkTreeReader::findFirst (const char * key)
Fetchs an iterator that is positioned at the first position of the key (or at the position where the key would be if it does not exist)
Parameters:
key the key to find the first occurence of
Returns:
an iterator at the position of the first occurance (or NULL on error)
References _fetch(), _file, _fileLength, BULK_BLOCK_SIZE, indri::file::BulkBlock::findGreater(), indri::file::BulkBlock::findIndexOf(), indri::file::BulkBlock::getID(), and indri::file::BulkBlock::leaf().
Referenced by indri::index::DiskKeyfileVocabularyIterator::nextEntry().
bool indri::file::BulkTreeReader::get (UINT32 key, char * value, int & actual, int valueLength)
bool indri::file::BulkTreeReader::get (const char * key, int keyLength, char * value, int & actual, int valueLength)
References _fetch(), _fileLength, BULK_BLOCK_SIZE, indri::file::BulkBlock::find(), indri::file::BulkBlock::findGreater(), and indri::file::BulkBlock::leaf().
bool indri::file::BulkTreeReader::get (const char * key, char * value, int & actual, int valueLength)
Referenced by indri::index::DiskIndex::_fetchTermData(), indri::index::IndexWriter::_lookupTermID(), and indri::file::BulkTreeWriter::get().
indri::file::BulkTreeIterator * indri::file::BulkTreeReader::iterator ()
References _file.
Referenced by indri::index::DiskKeyfileVocabularyIterator::DiskKeyfileVocabularyIterator().
void indri::file::BulkTreeReader::openRead (const std::string & filename)
References _file, _fileLength, _ownFile, indri::file::File::openRead(), and indri::file::File::size().
Referenced by indri::index::IndexWriter::_openTermsReaders(), and indri::index::DiskIndex::open().
Member Data Documentation
indri::utility::HashTable< UINT32, BulkBlock* > indri::file::BulkTreeReader::_cache [private]
Referenced by _fetch(), and ~BulkTreeReader().
File* indri::file::BulkTreeReader::_file [private]
Referenced by _fetch(), close(), findFirst(), iterator(), and openRead().
UINT64 indri::file::BulkTreeReader::_fileLength [private]
Referenced by _fetch(), findFirst(), get(), and openRead().
BulkBlock* indri::file::BulkTreeReader::_head [private]
Referenced by _fetch().
bool indri::file::BulkTreeReader::_ownFile [private]
Referenced by close(), and openRead().
BulkBlock* indri::file::BulkTreeReader::_tail [private]
Referenced by _fetch().
The documentation for this class was generated from the following files:
BulkTree.hpp
BulkTree.cpp