Indri: indri::lang::FilReqNode Class Reference
indri::lang::FilReqNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FilReqNode (RawExtentNode *filter, ScoredExtentNode *required)
FilReqNode (Unpacker &unpacker)
std::string typeName () const
UINT64 hashCode () const
std::string queryText () const
RawExtentNode * getFilter ()
ScoredExtentNode * getRequired ()
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
RawExtentNode * _filter
ScoredExtentNode * _required
Constructor & Destructor Documentation
indri::lang::FilReqNode::FilReqNode (RawExtentNode * filter, ScoredExtentNode * required) [inline]
References _filter, and _required.
Referenced by copy().
indri::lang::FilReqNode::FilReqNode (Unpacker & unpacker) [inline]
References _filter, _required, indri::lang::Unpacker::getRawExtentNode(), and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
Node* indri::lang::FilReqNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _filter, _required, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and FilReqNode().
RawExtentNode* indri::lang::FilReqNode::getFilter () [inline]
References _filter.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
ScoredExtentNode* indri::lang::FilReqNode::getRequired () [inline]
References _required.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
UINT64 indri::lang::FilReqNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _filter, _required, and indri::lang::Node::hashCode().
bool indri::lang::FilReqNode::operator== (Node & node) [inline]
References _filter, _required, getFilter(), and getRequired().
void indri::lang::FilReqNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _filter, _required, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::FilReqNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _filter, _required, and indri::lang::Node::queryText().
std::string indri::lang::FilReqNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FilReqNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _filter, _required, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
RawExtentNode* indri::lang::FilReqNode::_filter [private]
Referenced by copy(), FilReqNode(), getFilter(), hashCode(), operator==(), pack(), queryText(), and walk().
ScoredExtentNode* indri::lang::FilReqNode::_required [private]
Referenced by copy(), FilReqNode(), getRequired(), hashCode(), operator==(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp