Indri: indri::server::NetworkServerProxyDocumentsResponse Class Reference
indri::server::NetworkServerProxyDocumentsResponse Class Reference
Public Member Functions
NetworkServerProxyDocumentsResponse (indri::net::NetworkMessageStream *stream)
~NetworkServerProxyDocumentsResponse ()
std::vector
< indri::api::ParsedDocument * > & getResults ()
Private Attributes
indri::net::NetworkMessageStream * _stream
std::vector
< indri::api::ParsedDocument * > _documents
Constructor & Destructor Documentation
indri::server::NetworkServerProxyDocumentsResponse::NetworkServerProxyDocumentsResponse (indri::net::NetworkMessageStream * stream) [inline]
indri::server::NetworkServerProxyDocumentsResponse::~NetworkServerProxyDocumentsResponse () [inline]
References _stream, indri::net::NetworkMessageStream::mutex(), and indri::thread::Lockable::unlock().
Member Function Documentation
std::vector<indri::api::ParsedDocument*>& indri::server::NetworkServerProxyDocumentsResponse::getResults () [inline, virtual]
Implements indri::server::QueryServerDocumentsResponse.
References _documents, _stream, base64_decode(), indri::parse::TermExtent::begin, indri::api::ParsedDocument::content, indri::api::ParsedDocument::contentLength, indri::utility::Buffer::detach(), indri::parse::TermExtent::end, indri::utility::Buffer::front(), indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), indri::net::XMLReplyReceiver::getReply(), indri::xml::XMLNode::getValue(), indri::parse::MetadataPair::key, indri::api::ParsedDocument::metadata, indri::utility::Buffer::position(), indri::api::ParsedDocument::positions, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), string_to_i64(), indri::api::ParsedDocument::text, indri::api::ParsedDocument::textLength, indri::utility::Buffer::unwrite(), indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, indri::net::XMLReplyReceiver::wait(), and indri::utility::Buffer::write().
Member Data Documentation
std::vector<indri::api::ParsedDocument*> indri::server::NetworkServerProxyDocumentsResponse::_documents [private]
Referenced by getResults().
indri::net::NetworkMessageStream* indri::server::NetworkServerProxyDocumentsResponse::_stream [private]
Referenced by getResults(), and ~NetworkServerProxyDocumentsResponse().
The documentation for this class was generated from the following file:
NetworkServerProxy.cpp