Indri: indri::parse::PorterStemmerTransformation Class Reference
indri::parse::PorterStemmerTransformation Class Reference
#include <PorterStemmerTransformation.hpp>
Public Member Functions
PorterStemmerTransformation ()
~PorterStemmerTransformation ()
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
Private Attributes
ObjectHandler
< indri::api::ParsedDocument > * _handler
Porter_Stemmer * stemmer
Constructor & Destructor Documentation
indri::parse::PorterStemmerTransformation::PorterStemmerTransformation ()
References stemmer.
indri::parse::PorterStemmerTransformation::~PorterStemmerTransformation ()
References stemmer.
Member Function Documentation
void indri::parse::PorterStemmerTransformation::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::PorterStemmerTransformation::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::PorterStemmerTransformation::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References indri::parse::Porter_Stemmer::porter_stem(), indri::utility::greedy_vector< _Type, _Count >::size(), stemmer, and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
ObjectHandler<indri::api::ParsedDocument>* indri::parse::PorterStemmerTransformation::_handler [private]
Referenced by handle(), and setHandler().
Porter_Stemmer* indri::parse::PorterStemmerTransformation::stemmer [private]
Referenced by PorterStemmerTransformation(), transform(), and ~PorterStemmerTransformation().
The documentation for this class was generated from the following files:
PorterStemmerTransformation.hpp
PorterStemmerTransformation.cpp