Indri: QueryParser Class Reference
QueryParser Class Reference
#include <QueryParser.hpp>
Public Member Functions
void init (QueryLexer *lexer)
void initializeASTFactory (ANTLR_USE_NAMESPACE(antlr) ASTFactory &factory)
QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer &tokenBuf)
QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenStream &lexer)
QueryParser (const ANTLR_USE_NAMESPACE(antlr) ParserSharedInputState &state)
int getNumTokens () const
const char * getTokenName (int type) const
const char *const * getTokenNames () const
indri::lang::ScoredExtentNode * query ()
indri::lang::ScoredExtentNode * scoredExtentNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * weightNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * combineNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * orNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * notNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * wandNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * wsumNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * maxNode (indri::lang::RawExtentNode *ou)
indri::lang::PriorNode * priorNode ()
indri::lang::FilRejNode * filrejNode (indri::lang::RawExtentNode *ou)
indri::lang::FilReqNode * filreqNode (indri::lang::RawExtentNode *ou)
indri::lang::FilReqNode * scoreifNode (indri::lang::RawExtentNode *ou)
indri::lang::FilRejNode * scoreifnotNode (indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * scoredRaw (indri::lang::RawExtentNode *ou)
RawExtentNode * qualifiedTerm ()
ExtentOr * context_list (indri::lang::RawExtentNode *ou)
indri::lang::RawExtentNode * unqualifiedTerm ()
indri::lang::ScoredExtentNode * weightedList (indri::lang::WeightedCombinationNode *wn, indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * extentRestriction (indri::lang::ScoredExtentNode *sn, indri::lang::RawExtentNode *ou)
double floating ()
indri::lang::ScoredExtentNode * sumList (indri::lang::WSumNode *wn, indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * unweightedList (indri::lang::UnweightedCombinationNode *cn, indri::lang::RawExtentNode *ou)
indri::lang::ScoredExtentNode * sumNode (indri::lang::RawExtentNode *ou)
indri::lang::WeightedExtentOr * wsynNode ()
RawExtentNode * unscoredTerm ()
indri::lang::ODNode * odNode ()
indri::lang::UWNode * uwNode ()
indri::lang::BAndNode * bandNode ()
indri::lang::Field * anyField ()
std::string fieldNameString ()
indri::lang::ExtentAnd * field_list ()
indri::lang::FieldLessNode * dateBefore ()
indri::lang::FieldGreaterNode * dateAfter ()
indri::lang::FieldBetweenNode * dateBetween ()
indri::lang::FieldEqualsNode * dateEquals ()
indri::lang::ExtentOr * synonym_list ()
indri::lang::ExtentOr * synonym_list_brace ()
indri::lang::ExtentOr * synonym_list_alt ()
indri::lang::FieldLessNode * lessNode ()
indri::lang::FieldGreaterNode * greaterNode ()
indri::lang::FieldBetweenNode * betweenNode ()
indri::lang::FieldEqualsNode * equalsNode ()
indri::lang::IndexTerm * rawText ()
indri::lang::ODNode * hyphenTerm ()
indri::lang::WildcardTerm * wildcardOpNode ()
indri::lang::IndexTerm * hyphenate ()
std::string fstring ()
indri::lang::ExtentInside * path ()
indri::lang::ExtentInside * pathOperator ()
indri::lang::Field * field_restriction ()
UINT64 date ()
UINT64 slashDate ()
UINT64 spaceDate ()
UINT64 dashDate ()
INT64 number ()
ANTLR_USE_NAMESPACE (antlr) RefAST getAST()
Protected Member Functions
QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer &tokenBuf, int k)
QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenStream &lexer, int k)
ANTLR_USE_NAMESPACE (antlr) RefAST returnAST
Private Member Functions
indri::lang::RawExtentNode * innerMost (indri::lang::ScoredExtentNode *sr)
Static Private Member Functions
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_0
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_1
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_2
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_3
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_4
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_5
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_6
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_7
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_8
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_9
Private Attributes
std::vector< indri::lang::Node * > _nodes
indri::utility::VectorDeleter
< indri::lang::Node * > _deleter
Static Private Attributes
static const char * tokenNames []
static const int NUM_TOKENS = 69
static const unsigned long _tokenSet_0_data_ [] = { 4294967264UL, 791621UL, 15UL, 0UL, 0UL, 0UL, 0UL, 0UL }
static const unsigned long _tokenSet_1_data_ []
static const unsigned long _tokenSet_2_data_ []
static const unsigned long _tokenSet_3_data_ []
static const unsigned long _tokenSet_4_data_ []
static const unsigned long _tokenSet_5_data_ []
static const unsigned long _tokenSet_6_data_ []
static const unsigned long _tokenSet_7_data_ []
static const unsigned long _tokenSet_8_data_ []
static const unsigned long _tokenSet_9_data_ []
Constructor & Destructor Documentation
QueryParser::QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer & tokenBuf, int k) [protected]
QueryParser::QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenBuffer & tokenBuf)
QueryParser::QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenStream & lexer, int k) [protected]
QueryParser::QueryParser (ANTLR_USE_NAMESPACE(antlr) TokenStream & lexer)
QueryParser::QueryParser (const ANTLR_USE_NAMESPACE(antlr) ParserSharedInputState & state)
Member Function Documentation
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const QueryParser::ANTLR_USE_NAMESPACE (antlr) [static, private]
QueryParser::ANTLR_USE_NAMESPACE (antlr) [protected]
QueryParser::ANTLR_USE_NAMESPACE (antlr) [inline]
Referenced by anyField(), bandNode(), context_list(), dashDate(), date(), extentRestriction(), fieldNameString(), floating(), fstring(), hyphenate(), hyphenTerm(), notNode(), number(), odNode(), path(), pathOperator(), priorNode(), query(), rawText(), scoredExtentNode(), scoredRaw(), slashDate(), spaceDate(), sumList(), synonym_list(), synonym_list_alt(), synonym_list_brace(), unqualifiedTerm(), unscoredTerm(), unweightedList(), uwNode(), weightedList(), and wsynNode().
indri::lang::Field * QueryParser::anyField ()
References _nodes, ANTLR_USE_NAMESPACE(), ANY, C_PAREN, COLON, fieldNameString(), and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::BAndNode * QueryParser::bandNode ()
References _nodes, indri::lang::BAndNode::addChild(), ANTLR_USE_NAMESPACE(), BAND, C_PAREN, O_PAREN, and unscoredTerm().
Referenced by unqualifiedTerm().
indri::lang::FieldBetweenNode * QueryParser::betweenNode ()
References _nodes, BETWEEN, C_PAREN, fieldNameString(), number(), and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::ScoredExtentNode * QueryParser::combineNode (indri::lang::RawExtentNode * ou)
References _nodes, COMBINE, and unweightedList().
Referenced by scoredExtentNode().
ExtentOr * QueryParser::context_list (indri::lang::RawExtentNode * ou)
References _nodes, ANTLR_USE_NAMESPACE(), C_PAREN, COMMA, DOT, fieldNameString(), O_PAREN, path(), indri::lang::ExtentInside::setOuter(), and TERM.
Referenced by scoredRaw().
UINT64 QueryParser::dashDate ()
References ANTLR_USE_NAMESPACE(), indri::parse::DateParse::convertDate(), DASH, NUMBER, and TERM.
Referenced by date().
UINT64 QueryParser::date ()
References ANTLR_USE_NAMESPACE(), DASH, dashDate(), NUMBER, SLASH, slashDate(), spaceDate(), and TERM.
Referenced by dateAfter(), dateBefore(), dateBetween(), and dateEquals().
indri::lang::FieldGreaterNode * QueryParser::dateAfter ()
References _nodes, C_PAREN, date(), DATEAFTER, and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::FieldLessNode * QueryParser::dateBefore ()
References _nodes, C_PAREN, date(), DATEBEFORE, and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::FieldBetweenNode * QueryParser::dateBetween ()
References _nodes, C_PAREN, date(), DATEBETWEEN, and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::FieldEqualsNode * QueryParser::dateEquals ()
References _nodes, C_PAREN, date(), DATEEQUALS, and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::FieldEqualsNode * QueryParser::equalsNode ()
References _nodes, C_PAREN, EQUALS, fieldNameString(), number(), and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::ScoredExtentNode * QueryParser::extentRestriction (indri::lang::ScoredExtentNode * sn, indri::lang::RawExtentNode * ou)
References _nodes, ANTLR_USE_NAMESPACE(), C_SQUARE, COLON, DOT, fieldNameString(), indri::atomic::increment(), NUMBER, O_SQUARE, path(), indri::lang::ExtentInside::setOuter(), and TERM.
Referenced by notNode(), sumList(), unweightedList(), and weightedList().
indri::lang::ExtentAnd * QueryParser::field_list ()
References _nodes, indri::lang::ExtentAnd::addChild(), COMMA, and fieldNameString().
Referenced by qualifiedTerm().
indri::lang::Field * QueryParser::field_restriction ()
References _nodes, C_SQUARE, fieldNameString(), and O_SQUARE.
std::string QueryParser::fieldNameString ()
References ANTLR_USE_NAMESPACE(), DASH, fstring(), NUMBER, and TERM.
Referenced by anyField(), betweenNode(), context_list(), equalsNode(), extentRestriction(), field_list(), field_restriction(), greaterNode(), lessNode(), and path().
indri::lang::FilRejNode * QueryParser::filrejNode (indri::lang::RawExtentNode * ou)
References _nodes, C_PAREN, FILREJ, O_PAREN, scoredExtentNode(), and unscoredTerm().
Referenced by scoredExtentNode().
indri::lang::FilReqNode * QueryParser::filreqNode (indri::lang::RawExtentNode * ou)
References _nodes, C_PAREN, FILREQ, O_PAREN, scoredExtentNode(), and unscoredTerm().
Referenced by scoredExtentNode().
double QueryParser::floating ()
References ANTLR_USE_NAMESPACE(), DASH, FLOAT, NUMBER, and SPACE_DASH.
Referenced by weightedList(), and wsynNode().
std::string QueryParser::fstring ()
References ANTLR_USE_NAMESPACE(), NUMBER, and TERM.
Referenced by fieldNameString().
int QueryParser::getNumTokens () const [inline]
References NUM_TOKENS.
const char* QueryParser::getTokenName (int type) const [inline]
References tokenNames.
const char* const* QueryParser::getTokenNames () const [inline]
References tokenNames.
indri::lang::FieldGreaterNode * QueryParser::greaterNode ()
References _nodes, C_PAREN, fieldNameString(), GREATER, number(), and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::IndexTerm * QueryParser::hyphenate ()
References _nodes, ANTLR_USE_NAMESPACE(), NUMBER, and TERM.
Referenced by hyphenTerm().
indri::lang::ODNode * QueryParser::hyphenTerm ()
References _nodes, indri::lang::ODNode::addChild(), ANTLR_USE_NAMESPACE(), DASH, hyphenate(), NUMBER, indri::lang::ODNode::setWindowSize(), and TERM.
Referenced by unqualifiedTerm().
void QueryParser::init (QueryLexer * lexer) [inline]
References indri::utility::VectorDeleter< VectorType >::setVector().
void QueryParser::initializeASTFactory (ANTLR_USE_NAMESPACE(antlr) ASTFactory & factory)
indri::lang::RawExtentNode* QueryParser::innerMost (indri::lang::ScoredExtentNode * sr) [inline, private]
References indri::lang::ExtentRestriction::getField(), and indri::lang::ExtentInside::getInner().
Referenced by sumList(), unweightedList(), and weightedList().
indri::lang::FieldLessNode * QueryParser::lessNode ()
References _nodes, C_PAREN, fieldNameString(), LESS, number(), and O_PAREN.
Referenced by unqualifiedTerm().
indri::lang::ScoredExtentNode * QueryParser::maxNode (indri::lang::RawExtentNode * ou)
References _nodes, MAX, and unweightedList().
Referenced by scoredExtentNode().
indri::lang::ScoredExtentNode * QueryParser::notNode (indri::lang::RawExtentNode * ou)
References _nodes, ANTLR_USE_NAMESPACE(), C_PAREN, extentRestriction(), NOT, O_PAREN, O_SQUARE, scoredExtentNode(), and indri::lang::NotNode::setChild().
Referenced by scoredExtentNode().
INT64 QueryParser::number ()
References ANTLR_USE_NAMESPACE(), DASH, NUMBER, SPACE_DASH, and string_to_i64().
Referenced by betweenNode(), equalsNode(), greaterNode(), and lessNode().
indri::lang::ODNode * QueryParser::odNode ()
References _nodes, indri::lang::ODNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, NUMBER, O_PAREN, OD, OPERATOR, indri::lang::ODNode::setWindowSize(), and unscoredTerm().
Referenced by unqualifiedTerm().
indri::lang::ScoredExtentNode * QueryParser::orNode (indri::lang::RawExtentNode * ou)
References _nodes, OR, and unweightedList().
Referenced by scoredExtentNode().
indri::lang::ExtentInside * QueryParser::path ()
References _nodes, ANTLR_USE_NAMESPACE(), B_SLASH, fieldNameString(), indri::lang::ExtentInside::getInner(), O_BRACE, pathOperator(), indri::lang::ExtentInside::setInner(), indri::lang::ExtentInside::setOuter(), and SLASH.
Referenced by context_list(), and extentRestriction().
indri::lang::ExtentInside * QueryParser::pathOperator ()
References _nodes, ANTLR_USE_NAMESPACE(), B_SLASH, O_BRACE, SLASH, and TERM.
Referenced by path().
indri::lang::PriorNode * QueryParser::priorNode ()
References _nodes, ANTLR_USE_NAMESPACE(), C_PAREN, O_PAREN, PRIOR, and TERM.
Referenced by scoredExtentNode().
RawExtentNode * QueryParser::qualifiedTerm ()
References _nodes, DOT, field_list(), and unqualifiedTerm().
Referenced by scoredRaw(), and unscoredTerm().
indri::lang::ScoredExtentNode * QueryParser::query ()
References _nodes, indri::lang::UnweightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), ANY, BAND, BETWEEN, COMBINE, DASH, DATEAFTER, DATEBEFORE, DATEBETWEEN, DATEEQUALS, DBL_QUOTE, ENCODED_QUOTED_TERM, ENCODED_TERM, EQUALS, FILREJ, FILREQ, FLOAT, GREATER, LESS, MAX, NOT, NUMBER, O_ANGLE, O_BRACE, OD, OPERATOR, OR, PRIOR, scoredExtentNode(), SCOREIF, SCOREIFNOT, SPACE_DASH, SYN, TERM, UW, WAND, WCARD, WEIGHT, WSUM, and WSYN.
indri::lang::IndexTerm * QueryParser::rawText ()
References _nodes, ANTLR_USE_NAMESPACE(), base64_decode_string(), DASH, DBL_QUOTE, ENCODED_QUOTED_TERM, ENCODED_TERM, FLOAT, NUMBER, indri::lang::IndexTerm::setStemmed(), SPACE_DASH, and TERM.
Referenced by unqualifiedTerm(), and wildcardOpNode().
indri::lang::ScoredExtentNode * QueryParser::scoredExtentNode (indri::lang::RawExtentNode * ou)
References ANTLR_USE_NAMESPACE(), ANY, BAND, BETWEEN, COMBINE, combineNode(), DASH, DATEAFTER, DATEBEFORE, DATEBETWEEN, DATEEQUALS, DBL_QUOTE, ENCODED_QUOTED_TERM, ENCODED_TERM, EQUALS, FILREJ, filrejNode(), FILREQ, filreqNode(), FLOAT, GREATER, LESS, MAX, maxNode(), NOT, notNode(), NUMBER, O_ANGLE, O_BRACE, OD, OPERATOR, OR, orNode(), PRIOR, priorNode(), scoredRaw(), SCOREIF, scoreifNode(), SCOREIFNOT, scoreifnotNode(), SPACE_DASH, SYN, TERM, UW, WAND, wandNode(), WCARD, WEIGHT, weightNode(), WSUM, wsumNode(), and WSYN.
Referenced by filrejNode(), filreqNode(), notNode(), query(), scoreifNode(), scoreifnotNode(), sumList(), unweightedList(), and weightedList().
indri::lang::ScoredExtentNode * QueryParser::scoredRaw (indri::lang::RawExtentNode * ou)
References _nodes, ANTLR_USE_NAMESPACE(), context_list(), DOT, qualifiedTerm(), and unqualifiedTerm().
Referenced by scoredExtentNode().
indri::lang::FilReqNode * QueryParser::scoreifNode (indri::lang::RawExtentNode * ou)
References _nodes, C_PAREN, O_PAREN, scoredExtentNode(), SCOREIF, and unscoredTerm().
Referenced by scoredExtentNode().
indri::lang::FilRejNode * QueryParser::scoreifnotNode (indri::lang::RawExtentNode * ou)
References _nodes, C_PAREN, O_PAREN, scoredExtentNode(), SCOREIFNOT, and unscoredTerm().
Referenced by scoredExtentNode().
UINT64 QueryParser::slashDate ()
References ANTLR_USE_NAMESPACE(), indri::parse::DateParse::convertDate(), NUMBER, and SLASH.
Referenced by date().
UINT64 QueryParser::spaceDate ()
References ANTLR_USE_NAMESPACE(), indri::parse::DateParse::convertDate(), NUMBER, and TERM.
Referenced by date().
indri::lang::ScoredExtentNode * QueryParser::sumList (indri::lang::WSumNode * wn, indri::lang::RawExtentNode * ou)
References indri::lang::WeightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, extentRestriction(), innerMost(), O_PAREN, O_SQUARE, and scoredExtentNode().
Referenced by sumNode().
indri::lang::ScoredExtentNode * QueryParser::sumNode (indri::lang::RawExtentNode * ou)
References _nodes, SUM, and sumList().
indri::lang::ExtentOr * QueryParser::synonym_list ()
References _nodes, indri::lang::ExtentOr::addChild(), ANTLR_USE_NAMESPACE(), C_ANGLE, O_ANGLE, and unscoredTerm().
Referenced by unqualifiedTerm().
indri::lang::ExtentOr * QueryParser::synonym_list_alt ()
References _nodes, indri::lang::ExtentOr::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, O_PAREN, SYN, and unscoredTerm().
Referenced by unqualifiedTerm().
indri::lang::ExtentOr * QueryParser::synonym_list_brace ()
References _nodes, indri::lang::ExtentOr::addChild(), ANTLR_USE_NAMESPACE(), C_BRACE, O_BRACE, and unscoredTerm().
Referenced by unqualifiedTerm().
indri::lang::RawExtentNode * QueryParser::unqualifiedTerm ()
References _nodes, ANTLR_USE_NAMESPACE(), ANY, anyField(), BAND, bandNode(), BETWEEN, betweenNode(), DASH, dateAfter(), DATEAFTER, dateBefore(), DATEBEFORE, dateBetween(), DATEBETWEEN, dateEquals(), DATEEQUALS, EQUALS, equalsNode(), FLOAT, indri::lang::IndexTerm::getText(), GREATER, greaterNode(), hyphenTerm(), LESS, lessNode(), NEGATIVE_NUMBER, NUMBER, O_ANGLE, O_BRACE, OD, odNode(), OPERATOR, rawText(), SPACE_DASH, STAR, SYN, synonym_list(), synonym_list_alt(), synonym_list_brace(), TERM, TEXT_TERM, UW, uwNode(), WCARD, wildcardOpNode(), WSYN, and wsynNode().
Referenced by qualifiedTerm(), scoredRaw(), and unscoredTerm().
RawExtentNode * QueryParser::unscoredTerm ()
References ANTLR_USE_NAMESPACE(), qualifiedTerm(), and unqualifiedTerm().
Referenced by bandNode(), filrejNode(), filreqNode(), odNode(), scoreifNode(), scoreifnotNode(), synonym_list(), synonym_list_alt(), synonym_list_brace(), uwNode(), and wsynNode().
indri::lang::ScoredExtentNode * QueryParser::unweightedList (indri::lang::UnweightedCombinationNode * cn, indri::lang::RawExtentNode * ou)
References indri::lang::UnweightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, extentRestriction(), innerMost(), O_PAREN, O_SQUARE, and scoredExtentNode().
Referenced by combineNode(), maxNode(), and orNode().
indri::lang::UWNode * QueryParser::uwNode ()
References _nodes, indri::lang::UWNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, NUMBER, O_PAREN, indri::lang::UWNode::setWindowSize(), unscoredTerm(), and UW.
Referenced by unqualifiedTerm().
indri::lang::ScoredExtentNode * QueryParser::wandNode (indri::lang::RawExtentNode * ou)
References _nodes, WAND, and weightedList().
Referenced by scoredExtentNode().
indri::lang::ScoredExtentNode * QueryParser::weightedList (indri::lang::WeightedCombinationNode * wn, indri::lang::RawExtentNode * ou)
References indri::lang::WeightedCombinationNode::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, extentRestriction(), floating(), innerMost(), O_PAREN, O_SQUARE, and scoredExtentNode().
Referenced by wandNode(), weightNode(), and wsumNode().
indri::lang::ScoredExtentNode * QueryParser::weightNode (indri::lang::RawExtentNode * ou)
References _nodes, WEIGHT, and weightedList().
Referenced by scoredExtentNode().
indri::lang::WildcardTerm * QueryParser::wildcardOpNode ()
References _nodes, C_PAREN, indri::lang::IndexTerm::getText(), O_PAREN, rawText(), indri::lang::WildcardTerm::setTerm(), and WCARD.
Referenced by unqualifiedTerm().
indri::lang::ScoredExtentNode * QueryParser::wsumNode (indri::lang::RawExtentNode * ou)
References _nodes, weightedList(), and WSUM.
Referenced by scoredExtentNode().
indri::lang::WeightedExtentOr * QueryParser::wsynNode ()
References _nodes, indri::lang::WeightedExtentOr::addChild(), ANTLR_USE_NAMESPACE(), C_PAREN, floating(), O_PAREN, unscoredTerm(), and WSYN.
Referenced by unqualifiedTerm().
Member Data Documentation
indri::utility::VectorDeleter<indri::lang::Node*> QueryParser::_deleter [private]
std::vector<indri::lang::Node*> QueryParser::_nodes [private]
Referenced by anyField(), bandNode(), betweenNode(), combineNode(), context_list(), dateAfter(), dateBefore(), dateBetween(), dateEquals(), equalsNode(), extentRestriction(), field_list(), field_restriction(), filrejNode(), filreqNode(), greaterNode(), hyphenate(), hyphenTerm(), lessNode(), maxNode(), notNode(), odNode(), orNode(), path(), pathOperator(), priorNode(), qualifiedTerm(), query(), rawText(), scoredRaw(), scoreifNode(), scoreifnotNode(), sumNode(), synonym_list(), synonym_list_alt(), synonym_list_brace(), unqualifiedTerm(), uwNode(), wandNode(), weightNode(), wildcardOpNode(), wsumNode(), and wsynNode().
const unsigned long QueryParser::_tokenSet_0_data_ = { 4294967264UL, 791621UL, 15UL, 0UL, 0UL, 0UL, 0UL, 0UL } [static, private]
const unsigned long QueryParser::_tokenSet_1_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_2_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_3_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_4_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_5_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_6_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_7_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_8_data_[] [static, private]
const unsigned long QueryParser::_tokenSet_9_data_[] [static, private]
const int QueryParser::NUM_TOKENS = 69 [static, private]
Referenced by getNumTokens().
const char * QueryParser::tokenNames [static, private]
Referenced by getTokenName(), and getTokenNames().
The documentation for this class was generated from the following files:
QueryParser.hpp
QueryParser.cpp