Indri: indri::parse::ParserFactory Class Reference
indri::parse::ParserFactory Class Reference
#include <ParserFactory.hpp>
Public Member Functions
~ParserFactory ()
Static Public Member Functions
static std::string preferredName (const std::string &name)
The idea here is to admit as many names as possible (including possibly misspellings).
static indri::parse::Parser * get (const std::string &name)
static indri::parse::Parser * get (const std::string &name, const std::vector< std::string > &includeTags, const std::vector< std::string > &excludeTags, const std::vector< std::string > &indexTags, const std::vector< std::string > &metadataTags, const std::map< ConflationPattern *, std::string > &conflations)
Constructor & Destructor Documentation
indri::parse::ParserFactory::~ParserFactory ()
Member Function Documentation
indri::parse::Parser * indri::parse::ParserFactory::get (const std::string & name, const std::vector< std::string > & includeTags, const std::vector< std::string > & excludeTags, const std::vector< std::string > & indexTags, const std::vector< std::string > & metadataTags, const std::map< ConflationPattern *, std::string > & conflations) [static]
References PARSER_HTML, PARSER_TEXT, PARSER_XML, preferredName(), and indri::parse::Parser::setTags().
indri::parse::Parser * indri::parse::ParserFactory::get (const std::string & name) [static]
Referenced by build_file_class_environment().
std::string indri::parse::ParserFactory::preferredName (const std::string & name) [static]
The idea here is to admit as many names as possible (including possibly misspellings).
References PARSER_HTML, PARSER_TEXT, and PARSER_XML.
Referenced by get().
The documentation for this class was generated from the following files:
ParserFactory.hpp
ParserFactory.cpp