Indri: indri::index::MemoryDocumentDataIterator Class Reference
indri::index::MemoryDocumentDataIterator Class Reference
#include <MemoryDocumentDataIterator.hpp>
Public Member Functions
MemoryDocumentDataIterator (const std::vector< DocumentData > &documentData)
~MemoryDocumentDataIterator ()
void startIteration ()
bool nextEntry ()
const DocumentData * currentEntry ()
bool finished ()
Private Attributes
const std::vector< DocumentData > & _dataVector
std::vector< DocumentData >
::const_iterator _iterator
Constructor & Destructor Documentation
indri::index::MemoryDocumentDataIterator::MemoryDocumentDataIterator (const std::vector< DocumentData > & documentData)
indri::index::MemoryDocumentDataIterator::~MemoryDocumentDataIterator ()
Member Function Documentation
const indri::index::DocumentData * indri::index::MemoryDocumentDataIterator::currentEntry () [virtual]
Implements indri::index::DocumentDataIterator.
References finished().
bool indri::index::MemoryDocumentDataIterator::finished () [virtual]
Implements indri::index::DocumentDataIterator.
References _dataVector, and _iterator.
Referenced by currentEntry(), and nextEntry().
bool indri::index::MemoryDocumentDataIterator::nextEntry () [virtual]
Implements indri::index::DocumentDataIterator.
References _iterator, and finished().
void indri::index::MemoryDocumentDataIterator::startIteration () [virtual]
Implements indri::index::DocumentDataIterator.
References _dataVector, and _iterator.
Member Data Documentation
const std::vector<DocumentData>& indri::index::MemoryDocumentDataIterator::_dataVector [private]
Referenced by finished(), and startIteration().
std::vector<DocumentData>::const_iterator indri::index::MemoryDocumentDataIterator::_iterator [private]
Referenced by finished(), nextEntry(), and startIteration().
The documentation for this class was generated from the following files:
MemoryDocumentDataIterator.hpp
MemoryDocumentDataIterator.cpp