Indri: indri::net::NetworkStream Class Reference
indri::net::NetworkStream Class Reference
#include <NetworkStream.hpp>
Public Member Functions
NetworkStream ()
NetworkStream (socket_t s)
~NetworkStream ()
std::string peer ()
bool connect (const std::string &name, unsigned int port)
bool connect (const char *name, unsigned int port)
void close ()
int write (const void *buffer, size_t length)
int read (void *buffer, size_t length)
int blockingRead (void *buffer, size_t length)
int blockingWrite (const void *buffer, unsigned int length)
bool alive ()
Private Member Functions
struct sockaddr_in _getSockaddr (const char *name, unsigned int port)
Private Attributes
socket_t _socket
Constructor & Destructor Documentation
indri::net::NetworkStream::NetworkStream () [inline]
indri::net::NetworkStream::NetworkStream (socket_t s) [inline]
indri::net::NetworkStream::~NetworkStream () [inline]
References close().
Member Function Documentation
struct sockaddr_in indri::net::NetworkStream::_getSockaddr (const char * name, unsigned int port) [inline, read, private]
Referenced by connect().
bool indri::net::NetworkStream::alive () [inline]
References _socket.
Referenced by indri::net::NetworkMessageStream::alive().
int indri::net::NetworkStream::blockingRead (void * buffer, size_t length) [inline]
References close(), and read().
Referenced by indri::net::NetworkMessageStream::read().
int indri::net::NetworkStream::blockingWrite (const void * buffer, unsigned int length) [inline]
References close(), and write().
Referenced by indri::net::NetworkMessageStream::reply(), and indri::net::NetworkMessageStream::request().
void indri::net::NetworkStream::close () [inline]
References _socket.
Referenced by blockingRead(), blockingWrite(), connect(), indri::net::NetworkMessageStream::read(), write(), and ~NetworkStream().
bool indri::net::NetworkStream::connect (const char * name, unsigned int port) [inline]
References _getSockaddr(), _socket, close(), and connect().
bool indri::net::NetworkStream::connect (const std::string & name, unsigned int port) [inline]
Referenced by indri::api::QueryEnvironment::addServer(), and connect().
std::string indri::net::NetworkStream::peer () [inline]
References _socket.
Referenced by connection_thread().
int indri::net::NetworkStream::read (void * buffer, size_t length) [inline]
References _socket.
Referenced by blockingRead(), and indri::net::NetworkMessageStream::read().
int indri::net::NetworkStream::write (const void * buffer, size_t length) [inline]
References _socket, and close().
Referenced by blockingWrite(), indri::net::NetworkMessageStream::error(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), and indri::net::NetworkMessageStream::request().
Member Data Documentation
socket_t indri::net::NetworkStream::_socket [private]
Referenced by alive(), close(), connect(), peer(), read(), and write().
The documentation for this class was generated from the following file:
NetworkStream.hpp