Indri: indri::query::RMExpander Class Reference
indri::query::RMExpander Class Reference
#include <RMExpander.hpp>
Public Member Functions
RMExpander (indri::api::QueryEnvironment *env, indri::api::Parameters &param)
virtual std::string expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > &results)
Constructor & Destructor Documentation
indri::query::RMExpander::RMExpander (indri::api::QueryEnvironment * env, indri::api::Parameters & param)
Member Function Documentation
std::string indri::query::RMExpander::expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > & results) [virtual]
Implements indri::query::QueryExpander.
References indri::query::QueryExpander::_env, indri::query::QueryExpander::_param, indri::query::QueryExpander::buildQuery(), indri::query::RelevanceModel::generate(), indri::api::Parameters::get(), and indri::query::RelevanceModel::getGrams().
The documentation for this class was generated from the following files:
RMExpander.hpp
RMExpander.cpp