Indri: indri::lang::ScoreAccumulatorNode Class Reference
indri::lang::ScoreAccumulatorNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ScoreAccumulatorNode (ScoredExtentNode *scoredNode)
ScoreAccumulatorNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
ScoredExtentNode * getChild ()
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
ScoredExtentNode * _scoredNode
Constructor & Destructor Documentation
indri::lang::ScoreAccumulatorNode::ScoreAccumulatorNode (ScoredExtentNode * scoredNode) [inline]
Referenced by copy().
indri::lang::ScoreAccumulatorNode::ScoreAccumulatorNode (Unpacker & unpacker) [inline]
References _scoredNode, and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
Node* indri::lang::ScoreAccumulatorNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), indri::lang::Node::nodeName(), ScoreAccumulatorNode(), and indri::lang::Node::setNodeName().
ScoredExtentNode* indri::lang::ScoreAccumulatorNode::getChild () [inline]
References _scoredNode.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::ScoreAccumulatorNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
void indri::lang::ScoreAccumulatorNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ScoreAccumulatorNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, and indri::lang::Node::queryText().
std::string indri::lang::ScoreAccumulatorNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ScoreAccumulatorNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::ScoreAccumulatorNode::_scoredNode [private]
Referenced by copy(), getChild(), pack(), queryText(), ScoreAccumulatorNode(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp