Indri: indri::xml::XMLWriter Class Reference
indri::xml::XMLWriter Class Reference
#include <XMLWriter.hpp>
Public Member Functions
XMLWriter (XMLNode *node)
void write (std::string &output)
Private Member Functions
void _writeChar (char ch, std::string &output) const
void _writeTabs (int tabs, std::string &output) const
void _writeTag (const std::string &tag, const std::map< std::string, std::string > &attributes, std::string &output, bool opening) const
void _writeEndOfLine (std::string &output) const
void _writeXML (int tabs, const XMLNode *node, std::string &output) const
Private Attributes
XMLNode * _node
Constructor & Destructor Documentation
indri::xml::XMLWriter::XMLWriter (XMLNode * node)
Member Function Documentation
void indri::xml::XMLWriter::_writeChar (char ch, std::string & output) const [private]
Referenced by _writeEndOfLine(), _writeTabs(), and _writeTag().
void indri::xml::XMLWriter::_writeEndOfLine (std::string & output) const [private]
References _writeChar().
Referenced by _writeXML().
void indri::xml::XMLWriter::_writeTabs (int tabs, std::string & output) const [private]
References _writeChar().
Referenced by _writeXML().
void indri::xml::XMLWriter::_writeTag (const std::string & tag, const std::map< std::string, std::string > & attributes, std::string & output, bool opening) const [private]
References _writeChar().
Referenced by _writeXML().
void indri::xml::XMLWriter::_writeXML (int tabs, const XMLNode * node, std::string & output) const [private]
References _writeEndOfLine(), _writeTabs(), _writeTag(), indri::xml::XMLNode::getAttributes(), indri::xml::XMLNode::getChildren(), indri::xml::XMLNode::getName(), and indri::xml::XMLNode::getValue().
Referenced by write().
void indri::xml::XMLWriter::write (std::string & output)
References _node, and _writeXML().
Referenced by indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::request(), and indri::lang::Packer::toString().
Member Data Documentation
XMLNode* indri::xml::XMLWriter::_node [private]
Referenced by write().
The documentation for this class was generated from the following files:
XMLWriter.hpp
XMLWriter.cpp