Indri: indri::file::Path Class Reference
indri::file::Path Class Reference
#include <Path.hpp>
Static Public Member Functions
static void create (const std::string &path)
static bool isFile (const std::string &path)
static bool isDirectory (const std::string &path)
static bool exists (const std::string &path)
static void remove (const std::string &path)
static void rename (const std::string &oldPath, const std::string &newPath)
static void make (const std::string &path)
static std::string trim (const std::string &path)
static std::string relative (const std::string &basePath, const std::string absolutePath)
static char pathSeparator ()
static std::string combine (const std::string &root, const std::string &addition)
static std::string extension (const std::string &path)
static std::string directory (const std::string &path)
static std::string filename (const std::string &path)
static std::string basename (const std::string &path)
Member Function Documentation
std::string indri::file::Path::basename (const std::string & path) [static]
References path_last_separator().
std::string indri::file::Path::combine (const std::string & root, const std::string & addition) [static]
References PATH_SEPARATOR.
Referenced by indri::collection::Repository::_checkpoint(), indri::index::IndexWriter::_closeFiles(), indri::index::IndexWriter::_constructFiles(), indri::file::DirectoryIterator::_copyCurrent(), indri::api::IndexEnvironment::_createAnnotators(), indri::parse::PageRank::_doPageRankIter(), indri::collection::Repository::_mergeBitmaps(), indri::collection::Repository::_mergeClosedIndexes(), indri::collection::Repository::_mergeCompressedCollections(), indri::collection::Repository::_mergeStage(), indri::collection::Repository::_openPriors(), indri::parse::Combiner::_openReadBuckets(), indri::index::IndexWriter::_openTermsReaders(), indri::parse::Combiner::_openWriteBuckets(), indri::parse::Combiner::_readRedirects(), _recoverRepository(), indri::parse::Combiner::_writeCorpusTable(), indri::collection::Repository::_writeMergedManifest(), indri::collection::Repository::close(), collect_harvest_paths(), indri::parse::Combiner::combineBucket(), combineOutputFile(), indri::parse::Combiner::combineRedirectDestinationBucket(), indri::parse::Combiner::combineRedirectDestinationBuckets(), combineSortedFiles(), indri::collection::CompressedCollection::compact(), indri::collection::Repository::create(), indri::collection::CompressedCollection::create(), indri::parse::Combiner::createBuckets(), indri::collection::Repository::exists(), getFinalHarvestPath(), harvest_anchor_text(), indri::parse::Combiner::hashRedirectTargets(), indri::parse::PageRank::indexPageRank(), install_prior(), main(), indri::collection::Repository::merge(), indri::collection::Repository::open(), indri::index::DiskIndex::open(), indri::collection::CompressedCollection::open(), indri::collection::Repository::openRead(), indri::collection::CompressedCollection::openRead(), FieldModifier::processFields(), and indri::parse::Combiner::sortCorpusFiles().
void indri::file::Path::create (const std::string & path) [static]
Referenced by indri::index::IndexWriter::_constructFiles().
std::string indri::file::Path::directory (const std::string & path) [static]
References path_last_separator().
Referenced by indri::parse::Combiner::_writeCorpusTable(), indri::parse::AnchorTextWriter::AnchorTextWriter(), collect_harvest_paths(), combineSortedFiles(), getFinalHarvestPath(), harvest_anchor_text(), make(), and indri::parse::Combiner::sortCorpusFiles().
bool indri::file::Path::exists (const std::string & path) [static]
Referenced by indri::collection::Repository::_checkpoint(), indri::collection::Repository::_cleanAndCreateDirectory(), _recoverRepository(), indri::collection::Repository::close(), indri::collection::Repository::create(), install_prior(), main(), rename(), and indri::index::DeletedDocumentList::write().
std::string indri::file::Path::extension (const std::string & path) [static]
References path_last_separator().
Referenced by indri::api::IndexEnvironment::addFile(), and main().
std::string indri::file::Path::filename (const std::string & path) [static]
References path_last_separator().
Referenced by collect_harvest_paths(), combineOutputFile(), combineSortedFiles(), and harvest_anchor_text().
bool indri::file::Path::isDirectory (const std::string & path) [static]
Referenced by indri::api::IndexEnvironment::_createAnnotators(), indri::file::FileTreeIterator::_next(), indri::collection::Repository::_openPriors(), collect_harvest_paths(), combineSortedFiles(), indri::file::FileTreeIterator::FileTreeIterator(), harvest_anchor_text(), main(), and make().
bool indri::file::Path::isFile (const std::string & path) [static]
Referenced by indri::file::FileTreeIterator::_next(), indri::parse::OffsetMetadataAnnotator::open(), and remove().
void indri::file::Path::make (const std::string & path) [static]
References directory(), and isDirectory().
Referenced by indri::parse::Combiner::_writeCorpusTable(), indri::parse::AnchorTextWriter::AnchorTextWriter(), combineSortedFiles(), harvest_anchor_text(), install_prior(), main(), and indri::parse::Combiner::sortCorpusFiles().
char indri::file::Path::pathSeparator () [static]
References PATH_SEPARATOR.
std::string indri::file::Path::relative (const std::string & basePath, const std::string absolutePath) [static]
References PATH_SEPARATOR.
Referenced by indri::api::IndexEnvironment::_createAnnotators(), indri::parse::PageRank::_doPageRankIter(), indri::parse::Combiner::hashToBuckets(), indri::parse::PageRank::indexPageRank(), and indri::parse::Combiner::sortCorpusFiles().
void indri::file::Path::remove (const std::string & path) [static]
References indri::file::DirectoryIterator::base(), indri::file::DirectoryIterator::close(), indri::file::DirectoryIterator::end(), and isFile().
Referenced by indri::collection::Repository::_cleanAndCreateDirectory(), indri::collection::Repository::_mergeStage(), _recoverRepository(), indri::collection::Repository::_remove(), main(), FieldModifier::processFields(), and indri::index::DeletedDocumentList::write().
void indri::file::Path::rename (const std::string & oldPath, const std::string & newPath) [static]
References exists().
Referenced by indri::collection::CompressedCollection::compact(), and FieldModifier::processFields().
std::string indri::file::Path::trim (const std::string & path) [static]
References PATH_SEPARATOR.
The documentation for this class was generated from the following files:
Path.hpp
Path.cpp