Indri: indri::file::SequentialReadBuffer Class Reference
indri::file::SequentialReadBuffer Class Reference
#include <SequentialReadBuffer.hpp>
Public Member Functions
SequentialReadBuffer (File &file)
SequentialReadBuffer (File &file, size_t length)
void cache (UINT64 position, size_t length)
size_t read (void *buffer, UINT64 position, size_t length)
size_t read (void *buffer, size_t length)
const void * peek (size_t length)
const void * read (size_t length)
void seek (UINT64 position)
void clear ()
UINT64 position ()
Private Attributes
File & _file
UINT64 _position
InternalFileBuffer _current
Constructor & Destructor Documentation
indri::file::SequentialReadBuffer::SequentialReadBuffer (File & file) [inline]
indri::file::SequentialReadBuffer::SequentialReadBuffer (File & file, size_t length) [inline]
Member Function Documentation
void indri::file::SequentialReadBuffer::cache (UINT64 position, size_t length) [inline]
References _current, _file, _position, indri::file::InternalFileBuffer::buffer, indri::utility::Buffer::clear(), indri::file::InternalFileBuffer::filePosition, indri::utility::Buffer::grow(), indri::file::File::read(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by indri::index::DiskIndex::open(), and peek().
void indri::file::SequentialReadBuffer::clear () [inline]
References _current, _position, indri::file::InternalFileBuffer::buffer, indri::utility::Buffer::clear(), and indri::file::InternalFileBuffer::filePosition.
const void* indri::file::SequentialReadBuffer::peek (size_t length) [inline]
References _current, _position, indri::file::InternalFileBuffer::buffer, cache(), indri::file::InternalFileBuffer::filePosition, indri::utility::Buffer::front(), indri::utility::Buffer::position(), and indri::utility::Buffer::size().
Referenced by read().
UINT64 indri::file::SequentialReadBuffer::position () [inline]
References _position.
Referenced by indri::index::DiskDocListFileIterator::_readEntry(), indri::index::DiskDocListIterator::_readTermData(), MergeFile::finished(), indri::index::DiskTermListFileIterator::nextEntry(), indri::index::DiskDocumentDataIterator::nextEntry(), and indri::index::DiskDocListFileIterator::nextEntry().
const void* indri::file::SequentialReadBuffer::read (size_t length) [inline]
References _position, and peek().
size_t indri::file::SequentialReadBuffer::read (void * buffer, size_t length) [inline]
References read().
size_t indri::file::SequentialReadBuffer::read (void * buffer, UINT64 position, size_t length) [inline]
References _current, indri::file::InternalFileBuffer::buffer, indri::file::InternalFileBuffer::filePosition, indri::utility::Buffer::front(), indri::utility::Buffer::position(), and seek().
Referenced by indri::collection::CompressedCollection::_copyStorageEntry(), indri::index::DiskDocListFileIterator::_readEntry(), indri::index::DiskDocListIterator::_readSkip(), indri::index::DiskDocExtentListIterator::_readSkip(), indri::index::DiskDocListIterator::_readTermData(), indri::index::DiskDocListIterator::_readTopdocs(), compress_file(), indri::index::DiskIndex::documentLength(), indri::parse::PageRank::indexPageRank(), indri::collection::PriorListIterator::nextEntry(), indri::index::DiskTermListFileIterator::nextEntry(), indri::index::DiskDocumentDataIterator::nextEntry(), read(), MergeFile::read(), MergeFile::readScore(), indri::collection::PriorListIterator::startIteration(), indri::index::DiskDocumentDataIterator::startIteration(), indri::index::DiskDocListIterator::startIteration(), and indri::index::DiskDocExtentListIterator::startIteration().
void indri::file::SequentialReadBuffer::seek (UINT64 position) [inline]
References _position.
Referenced by indri::collection::CompressedCollection::_copyStorageEntry(), indri::index::DiskDocListIterator::_readTermData(), extract_compression_table(), indri::collection::PriorListIterator::nextEntry(), read(), indri::index::DiskDocListIterator::setStartOffset(), indri::index::DiskDocExtentListIterator::setStartOffset(), indri::collection::PriorListIterator::startIteration(), indri::index::DiskDocumentDataIterator::startIteration(), indri::index::DiskDocListIterator::startIteration(), and indri::index::DiskDocExtentListIterator::startIteration().
Member Data Documentation
InternalFileBuffer indri::file::SequentialReadBuffer::_current [private]
Referenced by cache(), clear(), peek(), and read().
File& indri::file::SequentialReadBuffer::_file [private]
Referenced by cache().
UINT64 indri::file::SequentialReadBuffer::_position [private]
Referenced by cache(), clear(), peek(), position(), read(), and seek().
The documentation for this class was generated from the following file:
SequentialReadBuffer.hpp