Indri: indri::index::DocListFileIterator Class Reference
indri::index::DocListFileIterator Class Reference
#include <DocListFileIterator.hpp>
Classes
struct DocListData
struct iterator_greater
Public Member Functions
virtual ~DocListFileIterator ()
virtual bool finished () const =0
virtual void startIteration ()=0
virtual bool nextEntry ()=0
virtual DocListData * currentEntry ()=0
virtual const DocListData * currentEntry () const =0
Constructor & Destructor Documentation
virtual indri::index::DocListFileIterator::~DocListFileIterator () [inline, virtual]
Member Function Documentation
virtual const DocListData* indri::index::DocListFileIterator::currentEntry () const [pure virtual]
Implemented in indri::index::DiskDocListFileIterator, and indri::index::MemoryIndexDocListFileIterator.
virtual DocListData* indri::index::DocListFileIterator::currentEntry () [pure virtual]
Implemented in indri::index::DiskDocListFileIterator, and indri::index::MemoryIndexDocListFileIterator.
Referenced by indri::index::WriterIndexContext::greater::_compareDocuments(), indri::index::WriterIndexContext::greater::_compareTerms(), indri::index::IndexWriter::_fetchMatchingInvertedLists(), indri::index::DocListFileIterator::iterator_greater::operator()(), and print_invfile().
virtual bool indri::index::DocListFileIterator::finished () const [pure virtual]
Implemented in indri::index::DiskDocListFileIterator, and indri::index::MemoryIndexDocListFileIterator.
Referenced by indri::index::WriterIndexContext::greater::operator()(), indri::index::DocListFileIterator::iterator_greater::operator()(), and print_invfile().
virtual bool indri::index::DocListFileIterator::nextEntry () [pure virtual]
Implemented in indri::index::DiskDocListFileIterator, and indri::index::MemoryIndexDocListFileIterator.
Referenced by print_invfile().
virtual void indri::index::DocListFileIterator::startIteration () [pure virtual]
Implemented in indri::index::DiskDocListFileIterator, and indri::index::MemoryIndexDocListFileIterator.
Referenced by print_invfile(), and indri::index::WriterIndexContext::WriterIndexContext().
The documentation for this class was generated from the following file:
DocListFileIterator.hpp