Indri: indri::index::DiskDocExtentListIterator Class Reference
indri::index::DiskDocExtentListIterator Class Reference
#include <DiskDocExtentListIterator.hpp>
Public Member Functions
DiskDocExtentListIterator (indri::file::SequentialReadBuffer *buffer, UINT64 startOffset)
~DiskDocExtentListIterator ()
void setStartOffset (UINT64 startOffset)
bool finished () const
void startIteration ()
bool nextEntry ()
bool nextEntry (lemur::api::DOCID_T documentID)
DocumentExtentData * currentEntry ()
Private Member Functions
void _readEntry ()
void _readSkip ()
Private Attributes
const char * _list
const char * _listEnd
int _skipDocument
indri::file::SequentialReadBuffer * _file
UINT64 _startOffset
bool _numeric
bool _ordinal
bool _parental
DocumentExtentData _data
bool _finished
Constructor & Destructor Documentation
indri::index::DiskDocExtentListIterator::DiskDocExtentListIterator (indri::file::SequentialReadBuffer * buffer, UINT64 startOffset)
indri::index::DiskDocExtentListIterator::~DiskDocExtentListIterator ()
References _file.
Member Function Documentation
void indri::index::DiskDocExtentListIterator::_readEntry () [private]
References _data, _list, _numeric, _ordinal, _parental, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocExtentListIterator::DocumentExtentData::document, indri::index::Extent::end, indri::index::DocExtentListIterator::DocumentExtentData::extents, indri::index::Extent::number, indri::index::DocExtentListIterator::DocumentExtentData::numbers, indri::index::Extent::ordinal, indri::index::Extent::parent, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::index::Extent::weight.
Referenced by nextEntry().
void indri::index::DiskDocExtentListIterator::_readSkip () [private]
References _data, _file, _list, _listEnd, _skipDocument, indri::index::DocExtentListIterator::DocumentExtentData::document, and indri::file::SequentialReadBuffer::read().
Referenced by nextEntry(), and startIteration().
indri::index::DiskDocExtentListIterator::DocumentExtentData * indri::index::DiskDocExtentListIterator::currentEntry () [virtual]
Implements indri::index::DocExtentListIterator.
References _data, and finished().
bool indri::index::DiskDocExtentListIterator::finished () const [virtual]
Implements indri::index::DocExtentListIterator.
References _finished.
Referenced by currentEntry().
bool indri::index::DiskDocExtentListIterator::nextEntry (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::DocExtentListIterator.
References _data, _finished, _list, _listEnd, _readEntry(), _readSkip(), _skipDocument, and indri::index::DocExtentListIterator::DocumentExtentData::document.
bool indri::index::DiskDocExtentListIterator::nextEntry () [virtual]
Implements indri::index::DocExtentListIterator.
References _finished, _list, _listEnd, _readEntry(), _readSkip(), and _skipDocument.
Referenced by startIteration().
void indri::index::DiskDocExtentListIterator::setStartOffset (UINT64 startOffset)
References _file, _startOffset, and indri::file::SequentialReadBuffer::seek().
void indri::index::DiskDocExtentListIterator::startIteration () [virtual]
Implements indri::index::DocExtentListIterator.
References _data, _file, _finished, _list, _listEnd, _numeric, _ordinal, _parental, _readSkip(), _skipDocument, _startOffset, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::parse::CharClass::control, indri::index::DocExtentListIterator::DocumentExtentData::document, indri::index::DocExtentListIterator::DocumentExtentData::extents, nextEntry(), indri::index::DocExtentListIterator::DocumentExtentData::numbers, indri::file::SequentialReadBuffer::read(), and indri::file::SequentialReadBuffer::seek().
Member Data Documentation
DocumentExtentData indri::index::DiskDocExtentListIterator::_data [private]
Referenced by _readEntry(), _readSkip(), currentEntry(), nextEntry(), and startIteration().
indri::file::SequentialReadBuffer* indri::index::DiskDocExtentListIterator::_file [private]
Referenced by _readSkip(), setStartOffset(), startIteration(), and ~DiskDocExtentListIterator().
bool indri::index::DiskDocExtentListIterator::_finished [private]
Referenced by finished(), nextEntry(), and startIteration().
const char* indri::index::DiskDocExtentListIterator::_list [private]
Referenced by _readEntry(), _readSkip(), nextEntry(), and startIteration().
const char* indri::index::DiskDocExtentListIterator::_listEnd [private]
Referenced by _readSkip(), nextEntry(), and startIteration().
bool indri::index::DiskDocExtentListIterator::_numeric [private]
Referenced by _readEntry(), and startIteration().
bool indri::index::DiskDocExtentListIterator::_ordinal [private]
Referenced by _readEntry(), and startIteration().
bool indri::index::DiskDocExtentListIterator::_parental [private]
Referenced by _readEntry(), and startIteration().
int indri::index::DiskDocExtentListIterator::_skipDocument [private]
Referenced by _readSkip(), nextEntry(), and startIteration().
UINT64 indri::index::DiskDocExtentListIterator::_startOffset [private]
Referenced by setStartOffset(), and startIteration().
The documentation for this class was generated from the following files:
DiskDocExtentListIterator.hpp
DiskDocExtentListIterator.cpp