Indri: indri::api::QueryParserWrapper Class Reference
indri::api::QueryParserWrapper Class Reference
#include <QueryParserFactory.hpp>
Public Member Functions
virtual ~QueryParserWrapper ()
virtual
indri::lang::ScoredExtentNode * query ()=0
Detailed Description
wrapper class for antlr generated parser/lexer combination.
Constructor & Destructor Documentation
virtual indri::api::QueryParserWrapper::~QueryParserWrapper () [inline, virtual]
Member Function Documentation
virtual indri::lang::ScoredExtentNode* indri::api::QueryParserWrapper::query () [pure virtual]
Implemented in indri::api::_Wrapper< _lexType, _parseType >.
Referenced by indri::api::QueryEnvironment::_expCount(), indri::api::QueryEnvironment::expressionList(), and indri::api::QueryEnvironment::runQuery().
The documentation for this class was generated from the following file:
QueryParserFactory.hpp