Indri: indri::parse::URLTextAnnotator Class Reference
indri::parse::URLTextAnnotator Class Reference
#include <URLTextAnnotator.hpp>
Public Member Functions
URLTextAnnotator ()
~URLTextAnnotator ()
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
Private Attributes
indri::utility::Buffer _buffer
ObjectHandler
< indri::api::ParsedDocument > * _handler
Detailed Description
Reads the URL text from the metadata field, parses it, and adds it to the document text for indexing.
Constructor & Destructor Documentation
indri::parse::URLTextAnnotator::URLTextAnnotator () [inline]
References _handler.
indri::parse::URLTextAnnotator::~URLTextAnnotator () [inline]
Member Function Documentation
void indri::parse::URLTextAnnotator::handle (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::URLTextAnnotator::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [inline, virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument* indri::parse::URLTextAnnotator::transform (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _buffer, indri::parse::TagExtent::begin, indri::parse::TermExtent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::Buffer::clear(), indri::parse::TagExtent::end, indri::parse::TermExtent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::utility::Buffer::grow(), indri::api::ParsedDocument::metadata, indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::api::ParsedDocument::positions, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::tags, indri::api::ParsedDocument::terms, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
Referenced by handle().
Member Data Documentation
indri::utility::Buffer indri::parse::URLTextAnnotator::_buffer [private]
Referenced by transform().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::URLTextAnnotator::_handler [private]
Referenced by handle(), setHandler(), and URLTextAnnotator().
The documentation for this class was generated from the following file:
URLTextAnnotator.hpp