Indri: indri::parse::FileClassEnvironmentFactory Class Reference
indri::parse::FileClassEnvironmentFactory Class Reference
#include <FileClassEnvironmentFactory.hpp>
Classes
struct Specification
Parsing information for a file class. Used to create a FileClassEnvironment.
Public Member Functions
~FileClassEnvironmentFactory ()
FileClassEnvironment * get (const std::string &name)
Make an instance of a named FileClassEnvironment. Caller is responsible for deleting the pointer.
FileClassEnvironmentFactory::Specification * getFileClassSpec (const std::string &name)
Make an instance of a named Specification, suitable for modifying an existing FileClassEnvironment. Caller is responsible for deleting the pointer.
void addFileClass (const FileClassEnvironmentFactory::Specification &spec)
Add parsing information for a file class.
void addFileClass (const std::string &name, const std::string &iterator, const std::string &parser, const std::string &tokenizer, const std::string &startDocTag, const std::string &endDocTag, const std::string &endMetadataTag, const std::vector< std::string > &include, const std::vector< std::string > &exclude, const std::vector< std::string > &index, const std::vector< std::string > &metadata, const std::map< indri::parse::ConflationPattern *, std::string > &conflations)
Add parsing information for a file class.
Private Attributes
std::map< std::string, struct
FileClassEnvironmentFactory::Specification * > _userTable
Constructor & Destructor Documentation
indri::parse::FileClassEnvironmentFactory::~FileClassEnvironmentFactory ()
References _userTable.
Member Function Documentation
void indri::parse::FileClassEnvironmentFactory::addFileClass (const std::string & name, const std::string & iterator, const std::string & parser, const std::string & tokenizer, const std::string & startDocTag, const std::string & endDocTag, const std::string & endMetadataTag, const std::vector< std::string > & include, const std::vector< std::string > & exclude, const std::vector< std::string > & index, const std::vector< std::string > & metadata, const std::map< indri::parse::ConflationPattern *, std::string > & conflations)
Add parsing information for a file class.
Parameters:
name name of this file class, eg trecweb
iterator document iterator for this file class
parser document parser for this file class
tokenizer document tokenizer for this file class
startDocTag tag indicating start of a document
endDocTag tag indicating the end of a document
endMetadataTag tag indicating the end of the metadata fields
include default tags whose contents should be included in the index
exclude tags whose contents should be excluded from the index
index tags that should be forwarded to the index for tag extents
metadata tags whose contents should be indexed as metadata
conflations tags that should be conflated
References _userTable, indri::parse::FileClassEnvironmentFactory::Specification::conflations, indri::parse::FileClassEnvironmentFactory::Specification::endDocTag, indri::parse::FileClassEnvironmentFactory::Specification::endMetadataTag, indri::parse::FileClassEnvironmentFactory::Specification::exclude, indri::parse::FileClassEnvironmentFactory::Specification::include, indri::parse::FileClassEnvironmentFactory::Specification::index, indri::parse::FileClassEnvironmentFactory::Specification::iterator, indri::parse::FileClassEnvironmentFactory::Specification::metadata, indri::parse::FileClassEnvironmentFactory::Specification::name, indri::parse::FileClassEnvironmentFactory::Specification::parser, indri::parse::FileClassEnvironmentFactory::Specification::startDocTag, and indri::parse::FileClassEnvironmentFactory::Specification::tokenizer.
void indri::parse::FileClassEnvironmentFactory::addFileClass (const FileClassEnvironmentFactory::Specification & spec)
Add parsing information for a file class.
Parameters:
spec the specification for this FileClassEnvironment
References _userTable, and indri::parse::FileClassEnvironmentFactory::Specification::name.
Referenced by indri::api::IndexEnvironment::addFileClass().
indri::parse::FileClassEnvironment * indri::parse::FileClassEnvironmentFactory::get (const std::string & name)
Make an instance of a named FileClassEnvironment. Caller is responsible for deleting the pointer.
Parameters:
name the name of the FileClassEnvironment
Returns:
an initialized instance of the named FileClassEnvironment, or NULL if the name is not found.
References _canonicalExtension(), _userTable, build_file_class_environment(), and file_class_environment_spec::name.
Referenced by indri::api::IndexEnvironment::_getParsingContext(), and FieldModifier::processFields().
indri::parse::FileClassEnvironmentFactory::Specification * indri::parse::FileClassEnvironmentFactory::getFileClassSpec (const std::string & name)
Make an instance of a named Specification, suitable for modifying an existing FileClassEnvironment. Caller is responsible for deleting the pointer.
Parameters:
name the name of the Specification
Returns:
an initialized instance of the named Specification, or NULL if the name is not found.
References _canonicalExtension(), _userTable, indri::parse::FileClassEnvironmentFactory::Specification::conflations, file_class_environment_spec::conflations, indri::parse::conflations, copy_string_tuples_to_map(), copy_strings_to_vector(), file_class_environment_spec::endDocTag, indri::parse::FileClassEnvironmentFactory::Specification::endDocTag, file_class_environment_spec::endMetadataTag, indri::parse::FileClassEnvironmentFactory::Specification::endMetadataTag, indri::parse::FileClassEnvironmentFactory::Specification::exclude, file_class_environment_spec::excludeTags, indri::parse::FileClassEnvironmentFactory::Specification::include, file_class_environment_spec::includeTags, indri::parse::FileClassEnvironmentFactory::Specification::index, file_class_environment_spec::indexTags, file_class_environment_spec::iterator, indri::parse::FileClassEnvironmentFactory::Specification::iterator, indri::parse::FileClassEnvironmentFactory::Specification::metadata, file_class_environment_spec::metadataTags, indri::parse::FileClassEnvironmentFactory::Specification::name, file_class_environment_spec::name, file_class_environment_spec::parser, indri::parse::FileClassEnvironmentFactory::Specification::parser, file_class_environment_spec::startDocTag, indri::parse::FileClassEnvironmentFactory::Specification::startDocTag, file_class_environment_spec::tokenizer, and indri::parse::FileClassEnvironmentFactory::Specification::tokenizer.
Referenced by indri::api::IndexEnvironment::getFileClassSpec().
Member Data Documentation
std::map<std::string, struct FileClassEnvironmentFactory::Specification*> indri::parse::FileClassEnvironmentFactory::_userTable [private]
Referenced by addFileClass(), get(), getFileClassSpec(), and ~FileClassEnvironmentFactory().
The documentation for this class was generated from the following files:
FileClassEnvironmentFactory.hpp
FileClassEnvironmentFactory.cpp