Indri: indri::file::BulkTreeWriter Class Reference
indri::file::BulkTreeWriter Class Reference
#include <BulkTree.hpp>
Public Member Functions
BulkTreeWriter ()
~BulkTreeWriter ()
void close ()
void create (const std::string &filename)
void put (const char *key, const char *value, int valueLength)
void put (UINT32 key, const char *value, int valueLength)
void put (const char *key, int keyLength, const char *value, int valueLength)
bool get (const char *key, int keyLength, char *value, int &actual, int valueLength)
bool get (UINT32 key, char *value, int &actual, int valueLength)
bool get (const char *key, char *value, int &actual, int valueLength)
void flush ()
Public Attributes
std::vector< BulkBlock * > _blocks
File _file
SequentialWriteBuffer _write
Private Member Functions
void _flush (int blockIndex)
void _flushAll ()
Private Attributes
UINT32 _blockID
int _flushLevel
Constructor & Destructor Documentation
indri::file::BulkTreeWriter::BulkTreeWriter ()
References _blockID, _blocks, and _flushLevel.
indri::file::BulkTreeWriter::~BulkTreeWriter ()
References _blocks, and indri::utility::delete_vector_contents().
Member Function Documentation
void indri::file::BulkTreeWriter::_flush (int blockIndex) [private]
References _blockID, _blocks, _flushLevel, _write, indri::file::BulkBlock::clear(), indri::file::BulkBlock::data(), indri::file::BulkBlock::dataSize(), indri::file::BulkBlock::insertFirstKey(), and indri::file::SequentialWriteBuffer::write().
Referenced by _flushAll(), and put().
void indri::file::BulkTreeWriter::_flushAll () [private]
References _blocks, _flush(), and _flushLevel.
Referenced by close(), and flush().
void indri::file::BulkTreeWriter::close ()
References _file, _flushAll(), _write, indri::file::File::close(), and indri::file::SequentialWriteBuffer::flush().
Referenced by indri::index::IndexWriter::_writeInvertedLists().
void indri::file::BulkTreeWriter::create (const std::string & filename)
References _file, and indri::file::File::create().
Referenced by indri::index::IndexWriter::_constructFiles().
void indri::file::BulkTreeWriter::flush ()
References _flushAll(), _write, and indri::file::SequentialWriteBuffer::flush().
bool indri::file::BulkTreeWriter::get (const char * key, char * value, int & actual, int valueLength)
References _blockID, _file, indri::file::BulkBlock::dataSize(), and indri::file::BulkTreeReader::get().
bool indri::file::BulkTreeWriter::get (UINT32 key, char * value, int & actual, int valueLength)
References _blockID, _file, indri::file::BulkBlock::dataSize(), and indri::file::BulkTreeReader::get().
bool indri::file::BulkTreeWriter::get (const char * key, int keyLength, char * value, int & actual, int valueLength)
References _blockID, _file, indri::file::BulkBlock::dataSize(), and indri::file::BulkTreeReader::get().
void indri::file::BulkTreeWriter::put (const char * key, int keyLength, const char * value, int valueLength)
References _blocks, and _flush().
void indri::file::BulkTreeWriter::put (UINT32 key, const char * value, int valueLength)
References put().
void indri::file::BulkTreeWriter::put (const char * key, const char * value, int valueLength)
Referenced by indri::index::IndexWriter::_storeIdEntry(), indri::index::IndexWriter::_storeStringEntry(), and put().
Member Data Documentation
UINT32 indri::file::BulkTreeWriter::_blockID [private]
Referenced by _flush(), BulkTreeWriter(), and get().
std::vector<BulkBlock*> indri::file::BulkTreeWriter::_blocks
Referenced by _flush(), _flushAll(), BulkTreeWriter(), put(), and ~BulkTreeWriter().
File indri::file::BulkTreeWriter::_file
Referenced by close(), create(), and get().
int indri::file::BulkTreeWriter::_flushLevel [private]
Referenced by _flush(), _flushAll(), and BulkTreeWriter().
SequentialWriteBuffer indri::file::BulkTreeWriter::_write
Referenced by _flush(), close(), and flush().
The documentation for this class was generated from the following files:
BulkTree.hpp
BulkTree.cpp