Indri: indri::server::QueryServerResponse Class Reference
indri::server::QueryServerResponse Class Reference
#include <QueryServer.hpp>
Public Member Functions
virtual ~QueryServerResponse ()
virtual
indri::infnet::InferenceNetwork::MAllResults & getResults ()=0
Constructor & Destructor Documentation
virtual indri::server::QueryServerResponse::~QueryServerResponse () [inline, virtual]
Member Function Documentation
virtual indri::infnet::InferenceNetwork::MAllResults& indri::server::QueryServerResponse::getResults () [pure virtual]
Implemented in indri::server::LocalQueryServerResponse, and indri::server::NetworkServerProxyResponse.
Referenced by indri::net::NetworkServerStub::_handleQuery(), indri::api::QueryEnvironment::_mergeQueryResults(), and indri::api::QueryEnvironment::_sumServerQuery().
The documentation for this class was generated from the following file:
QueryServer.hpp