Indri: indri::infnet::Annotator Class Reference
indri::infnet::Annotator Class Reference
#include <Annotator.hpp>
Public Member Functions
Annotator (const std::string &name, BeliefNode *belief)
void add (InferenceNetworkNode *node, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
void addMatches (indri::utility::greedy_vector< indri::index::Extent > &extents, InferenceNetworkNode *node, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
void evaluate (lemur::api::DOCID_T documentID, int documentLength)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
EvaluatorNode::MResults & getResults ()
const std::string & getName () const
const EvaluatorNode::MResults & getResults () const
Private Attributes
BeliefNode * _belief
EvaluatorNode::MResults _annotations
std::string _name
std::map< std::string,
std::set
< indri::api::ScoredExtentResult,
indri::api::ScoredExtentResult::score_greater > > _seen
Constructor & Destructor Documentation
indri::infnet::Annotator::Annotator (const std::string & name, BeliefNode * belief)
Member Function Documentation
void indri::infnet::Annotator::add (InferenceNetworkNode * node, lemur::api::DOCID_T documentID, indri::index::Extent & extent)
References _annotations, _seen, indri::api::ScoredExtentResult::document, indri::infnet::InferenceNetworkNode::getName(), and indri::api::ScoredExtentResult::score.
Referenced by addMatches(), indri::infnet::WPlusNode::annotate(), indri::infnet::WeightedSumNode::annotate(), indri::infnet::WeightedAndNode::annotate(), indri::infnet::ShrinkageBeliefNode::annotate(), indri::infnet::PriorNode::annotate(), indri::infnet::PlusNode::annotate(), indri::infnet::OrNode::annotate(), indri::infnet::NotNode::annotate(), indri::infnet::NestedListBeliefNode::annotate(), indri::infnet::MaxNode::annotate(), indri::infnet::ListBeliefNode::annotate(), indri::infnet::LengthPriorNode::annotate(), indri::infnet::FixedPassageNode::annotate(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), and indri::infnet::ContextInclusionAndNode::annotate().
void indri::infnet::Annotator::addMatches (indri::utility::greedy_vector< indri::index::Extent > & extents, InferenceNetworkNode * node, lemur::api::DOCID_T documentID, indri::index::Extent & extent)
References add(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::infnet::WeightedExtentOrNode::annotate(), indri::infnet::UnorderedWindowNode::annotate(), indri::infnet::OrderedWindowNode::annotate(), indri::infnet::NestedExtentInsideNode::annotate(), indri::infnet::FieldWildcardNode::annotate(), indri::infnet::FieldLessNode::annotate(), indri::infnet::FieldIteratorNode::annotate(), indri::infnet::FieldGreaterNode::annotate(), indri::infnet::FieldEqualsNode::annotate(), indri::infnet::FieldBetweenNode::annotate(), indri::infnet::ExtentParentNode::annotate(), indri::infnet::ExtentOrNode::annotate(), indri::infnet::ExtentInsideNode::annotate(), indri::infnet::ExtentDescendantNode::annotate(), indri::infnet::ExtentChildNode::annotate(), indri::infnet::ExtentAndNode::annotate(), indri::infnet::DocListIteratorNode::annotate(), and indri::infnet::BooleanAndNode::annotate().
void indri::infnet::Annotator::evaluate (lemur::api::DOCID_T documentID, int documentLength) [virtual]
Implements indri::infnet::EvaluatorNode.
References _belief, and indri::infnet::BeliefNode::annotate().
const std::string & indri::infnet::Annotator::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::infnet::EvaluatorNode::MResults & indri::infnet::Annotator::getResults () const
References _annotations.
indri::infnet::EvaluatorNode::MResults & indri::infnet::Annotator::getResults () [virtual]
Implements indri::infnet::EvaluatorNode.
References _annotations.
void indri::infnet::Annotator::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
lemur::api::DOCID_T indri::infnet::Annotator::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _belief, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
Member Data Documentation
EvaluatorNode::MResults indri::infnet::Annotator::_annotations [private]
Referenced by add(), and getResults().
BeliefNode* indri::infnet::Annotator::_belief [private]
Referenced by evaluate(), and nextCandidateDocument().
std::string indri::infnet::Annotator::_name [private]
Referenced by getName().
std::map<std::string, std::set<indri::api::ScoredExtentResult, indri::api::ScoredExtentResult::score_greater> > indri::infnet::Annotator::_seen [private]
Referenced by add().
The documentation for this class was generated from the following files:
Annotator.hpp
Annotator.cpp