Indri: indri::parse::TaggedDocumentIterator Class Reference
indri::parse::TaggedDocumentIterator Class Reference
#include <TaggedDocumentIterator.hpp>
Public Member Functions
TaggedDocumentIterator ()
~TaggedDocumentIterator ()
void setTags (const char *startDoc, const char *endDoc, const char *endMetadata)
void open (const std::string &filename)
void close ()
UnparsedDocument * nextDocument ()
Private Member Functions
bool _readLine (char *&beginLine, size_t &lineLength)
Private Attributes
UnparsedDocument _document
gzFile _in
indri::utility::Buffer _buffer
indri::utility::Buffer _metaBuffer
std::string _lastMetadataTag
std::string _fileName
const char * _startDocTag
const char * _endDocTag
const char * _endMetadataTag
int _startDocTagLength
int _endDocTagLength
int _endMetadataTagLength
Constructor & Destructor Documentation
indri::parse::TaggedDocumentIterator::TaggedDocumentIterator ()
References _endDocTag, _endDocTagLength, _endMetadataTag, _endMetadataTagLength, _in, _startDocTag, and _startDocTagLength.
indri::parse::TaggedDocumentIterator::~TaggedDocumentIterator ()
References close().
Member Function Documentation
bool indri::parse::TaggedDocumentIterator::_readLine (char *& beginLine, size_t & lineLength) [private]
References _buffer, _in, indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::position(), indri::utility::Buffer::size(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by nextDocument().
void indri::parse::TaggedDocumentIterator::close () [virtual]
Implements indri::parse::DocumentIterator.
References _in.
Referenced by indri::parse::PageRank::_computeColLen(), and ~TaggedDocumentIterator().
indri::parse::UnparsedDocument * indri::parse::TaggedDocumentIterator::nextDocument () [virtual]
Implements indri::parse::DocumentIterator.
References _buffer, _document, _endDocTag, _endDocTagLength, _endMetadataTag, _endMetadataTagLength, _fileName, _metaBuffer, _readLine(), _startDocTag, _startDocTagLength, indri::utility::greedy_vector< _Type, _Count >::back(), metadata_range::beginTag, metadata_range::beginText, indri::utility::Buffer::clear(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::parse::UnparsedDocument::content, indri::parse::UnparsedDocument::contentLength, indri::utility::greedy_vector< _Type, _Count >::end(), metadata_range::endTag, metadata_range::endText, indri::utility::greedy_vector< _Type, _Count >::erase(), indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::parse::UnparsedDocument::metadata, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::parse::MetadataPair::stripValue(), indri::parse::UnparsedDocument::text, indri::parse::UnparsedDocument::textLength, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
Referenced by indri::parse::PageRank::_computeColLen().
void indri::parse::TaggedDocumentIterator::open (const std::string & filename) [virtual]
Implements indri::parse::DocumentIterator.
References _fileName, and _in.
Referenced by indri::parse::PageRank::_computeColLen().
void indri::parse::TaggedDocumentIterator::setTags (const char * startDoc, const char * endDoc, const char * endMetadata)
References _endDocTag, _endDocTagLength, _endMetadataTag, _endMetadataTagLength, _startDocTag, and _startDocTagLength.
Referenced by indri::parse::PageRank::_computeColLen(), and indri::parse::DocumentIteratorFactory::get().
Member Data Documentation
indri::utility::Buffer indri::parse::TaggedDocumentIterator::_buffer [private]
Referenced by _readLine(), and nextDocument().
UnparsedDocument indri::parse::TaggedDocumentIterator::_document [private]
Referenced by nextDocument().
const char* indri::parse::TaggedDocumentIterator::_endDocTag [private]
Referenced by nextDocument(), setTags(), and TaggedDocumentIterator().
int indri::parse::TaggedDocumentIterator::_endDocTagLength [private]
Referenced by nextDocument(), setTags(), and TaggedDocumentIterator().
const char* indri::parse::TaggedDocumentIterator::_endMetadataTag [private]
Referenced by nextDocument(), setTags(), and TaggedDocumentIterator().
int indri::parse::TaggedDocumentIterator::_endMetadataTagLength [private]
Referenced by nextDocument(), setTags(), and TaggedDocumentIterator().
std::string indri::parse::TaggedDocumentIterator::_fileName [private]
Referenced by nextDocument(), and open().
gzFile indri::parse::TaggedDocumentIterator::_in [private]
Referenced by _readLine(), close(), open(), and TaggedDocumentIterator().
std::string indri::parse::TaggedDocumentIterator::_lastMetadataTag [private]
indri::utility::Buffer indri::parse::TaggedDocumentIterator::_metaBuffer [private]
Referenced by nextDocument().
const char* indri::parse::TaggedDocumentIterator::_startDocTag [private]
Referenced by nextDocument(), setTags(), and TaggedDocumentIterator().
int indri::parse::TaggedDocumentIterator::_startDocTagLength [private]
Referenced by nextDocument(), setTags(), and TaggedDocumentIterator().
The documentation for this class was generated from the following files:
TaggedDocumentIterator.hpp
TaggedDocumentIterator.cpp