Indri: indri::infnet::DocListIteratorNode Class Reference
indri::infnet::DocListIteratorNode Class Reference
#include <DocListIteratorNode.hpp>
Public Member Functions
DocListIteratorNode (const std::string &name, class InferenceNetwork &network, int listID)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
void indexChanged (indri::index::Index &index, class InferenceNetwork *network)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
const std::string & getName () const
void annotate (Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
indri::index::DocListIterator * _list
class InferenceNetwork & _network
int _listID
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
Constructor & Destructor Documentation
indri::infnet::DocListIteratorNode::DocListIteratorNode (const std::string & name, class InferenceNetwork & network, int listID)
Member Function Documentation
void indri::infnet::DocListIteratorNode::annotate (Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, indri::infnet::ListIteratorNode::_lastExtent, indri::infnet::Annotator::addMatches(), and indri::index::Extent::contains().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::DocListIteratorNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::DocListIteratorNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::DocListIteratorNode::indexChanged (indri::index::Index & index, class InferenceNetwork * network)
void indri::infnet::DocListIteratorNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, _list, _listID, _network, indri::index::Extent::begin, indri::index::Extent::end, and indri::infnet::InferenceNetwork::getDocIterator().
lemur::api::DOCID_T indri::infnet::DocListIteratorNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _list, indri::index::DocListIterator::currentEntry(), and indri::index::DocListIterator::DocumentData::document.
void indri::infnet::DocListIteratorNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _extents, indri::infnet::ListIteratorNode::_lastExtent, _list, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListIterator::currentEntry(), indri::index::DocListIterator::DocumentData::document, indri::index::Extent::end, indri::infnet::ListIteratorNode::initpointer(), indri::index::DocListIterator::DocumentData::positions, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::DocListIteratorNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
indri::index::DocListIterator* indri::infnet::DocListIteratorNode::_list [private]
Referenced by indexChanged(), nextCandidateDocument(), and prepare().
int indri::infnet::DocListIteratorNode::_listID [private]
Referenced by indexChanged().
std::string indri::infnet::DocListIteratorNode::_name [private]
Referenced by getName().
class InferenceNetwork& indri::infnet::DocListIteratorNode::_network [private]
Referenced by indexChanged().
The documentation for this class was generated from the following files:
DocListIteratorNode.hpp
DocListIteratorNode.cpp