Indri: indri::infnet::ExtentAndNode Class Reference
indri::infnet::ExtentAndNode Class Reference
#include <ExtentAndNode.hpp>
Public Member Functions
ExtentAndNode (const std::string &name, std::vector< ListIteratorNode * > &children)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Member Functions
void _and (indri::utility::greedy_vector< indri::index::Extent > &out, const indri::utility::greedy_vector< indri::index::Extent > &one, const indri::utility::greedy_vector< indri::index::Extent > &two)
Private Attributes
std::vector< ListIteratorNode * > _children
indri::utility::greedy_vector
< indri::index::Extent > _extents
indri::utility::greedy_vector
< indri::index::Extent > _partialExtents
std::string _name
Constructor & Destructor Documentation
indri::infnet::ExtentAndNode::ExtentAndNode (const std::string & name, std::vector< ListIteratorNode * > & children)
Member Function Documentation
void indri::infnet::ExtentAndNode::_and (indri::utility::greedy_vector< indri::index::Extent > & out, const indri::utility::greedy_vector< indri::index::Extent > & one, const indri::utility::greedy_vector< indri::index::Extent > & two) [private]
References _extents, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by prepare().
void indri::infnet::ExtentAndNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, and indri::infnet::Annotator::addMatches().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::ExtentAndNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
Referenced by prepare().
const std::string & indri::infnet::ExtentAndNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::ExtentAndNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
lemur::api::DOCID_T indri::infnet::ExtentAndNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
void indri::infnet::ExtentAndNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _and(), _children, _extents, indri::utility::greedy_vector< _Type, _Count >::clear(), extents(), and indri::infnet::ListIteratorNode::initpointer().
Member Data Documentation
std::vector<ListIteratorNode*> indri::infnet::ExtentAndNode::_children [private]
Referenced by nextCandidateDocument(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::ExtentAndNode::_extents [private]
Referenced by _and(), annotate(), extents(), and prepare().
std::string indri::infnet::ExtentAndNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::ExtentAndNode::_partialExtents [private]
The documentation for this class was generated from the following files:
ExtentAndNode.hpp
ExtentAndNode.cpp