Indri: indri::lang::WildcardTerm Class Reference
indri::lang::WildcardTerm Class Reference
#include <QuerySpec.hpp>
Public Member Functions
WildcardTerm ()
WildcardTerm (std::string text)
WildcardTerm (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void setTerm (std::string term)
std::string getTerm ()
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Member Functions
void normalizeTerm ()
Private Attributes
std::string _normalizedTerm
Constructor & Destructor Documentation
indri::lang::WildcardTerm::WildcardTerm () [inline]
Referenced by copy().
indri::lang::WildcardTerm::WildcardTerm (std::string text) [inline]
References normalizeTerm().
indri::lang::WildcardTerm::WildcardTerm (Unpacker & unpacker) [inline]
References _normalizedTerm, and indri::lang::Unpacker::getString().
Member Function Documentation
Node* indri::lang::WildcardTerm::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _normalizedTerm, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), indri::lang::Node::setNodeName(), and WildcardTerm().
std::string indri::lang::WildcardTerm::getTerm () [inline]
References _normalizedTerm.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
UINT64 indri::lang::WildcardTerm::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _normalizedTerm.
void indri::lang::WildcardTerm::normalizeTerm () [inline, private]
References _normalizedTerm.
Referenced by setTerm(), and WildcardTerm().
bool indri::lang::WildcardTerm::operator== (Node & node) [inline]
References _normalizedTerm, and getTerm().
void indri::lang::WildcardTerm::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _normalizedTerm, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::WildcardTerm::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _normalizedTerm.
void indri::lang::WildcardTerm::setTerm (std::string term) [inline]
References _normalizedTerm, and normalizeTerm().
Referenced by QueryParser::wildcardOpNode().
std::string indri::lang::WildcardTerm::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::WildcardTerm::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
std::string indri::lang::WildcardTerm::_normalizedTerm [private]
Referenced by copy(), getTerm(), hashCode(), normalizeTerm(), operator==(), pack(), queryText(), setTerm(), and WildcardTerm().
The documentation for this class was generated from the following file:
QuerySpec.hpp