Indri: indri::lang::FixedPassage Class Reference
indri::lang::FixedPassage Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FixedPassage (Unpacker &unpacker)
FixedPassage (ScoredExtentNode *child, int windowSize, int increment)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
ScoredExtentNode * getChild ()
int getWindowSize ()
int getIncrement ()
void setChild (ScoredExtentNode *child)
void setWindowSize (int windowSize)
void setIncrement (int increment)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
ScoredExtentNode * _child
int _windowSize
int _increment
Constructor & Destructor Documentation
indri::lang::FixedPassage::FixedPassage (Unpacker & unpacker) [inline]
References _child, _increment, _windowSize, indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getScoredExtentNode().
Referenced by copy().
indri::lang::FixedPassage::FixedPassage (ScoredExtentNode * child, int windowSize, int increment) [inline]
Member Function Documentation
Node* indri::lang::FixedPassage::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _child, _increment, _windowSize, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), FixedPassage(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
ScoredExtentNode* indri::lang::FixedPassage::getChild () [inline]
References _child.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::lang::FixedPassage::getIncrement () [inline]
References _increment.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::lang::FixedPassage::getWindowSize () [inline]
References _windowSize.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::FixedPassage::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _child, _increment, _windowSize, and indri::lang::Node::hashCode().
void indri::lang::FixedPassage::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _child, _increment, _windowSize, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::FixedPassage::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _child, _increment, _windowSize, and indri::lang::Node::queryText().
void indri::lang::FixedPassage::setChild (ScoredExtentNode * child) [inline]
References _child.
void indri::lang::FixedPassage::setIncrement (int increment) [inline]
References _increment.
void indri::lang::FixedPassage::setWindowSize (int windowSize) [inline]
References _windowSize.
std::string indri::lang::FixedPassage::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FixedPassage::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _child, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::FixedPassage::_child [private]
Referenced by copy(), FixedPassage(), getChild(), hashCode(), pack(), queryText(), setChild(), and walk().
int indri::lang::FixedPassage::_increment [private]
Referenced by copy(), FixedPassage(), getIncrement(), hashCode(), pack(), queryText(), and setIncrement().
int indri::lang::FixedPassage::_windowSize [private]
Referenced by copy(), FixedPassage(), getWindowSize(), hashCode(), pack(), queryText(), and setWindowSize().
The documentation for this class was generated from the following file:
QuerySpec.hpp