Indri: indri::index::DocExtentListMemoryBuilderIterator Class Reference
indri::index::DocExtentListMemoryBuilderIterator Class Reference
#include <DocExtentListMemoryBuilder.hpp>
Public Member Functions
void reset (const indri::utility::greedy_vector< DocExtentListMemoryBuilderSegment, 4 > &lists, bool numeric, bool ordinal, bool parental)
void reset (class DocExtentListMemoryBuilder &builder)
DocExtentListMemoryBuilderIterator (const class DocExtentListMemoryBuilder &builder)
void startIteration ()
bool finished () const
bool nextEntry (lemur::api::DOCID_T documentID)
bool nextEntry ()
indri::index::DocExtentListIterator::DocumentExtentData * currentEntry ()
Private Attributes
const
indri::utility::greedy_vector
< DocExtentListMemoryBuilderSegment, 4 > * _lists
indri::utility::greedy_vector
< DocExtentListMemoryBuilderSegment, 4 >
::const_iterator _current
indri::index::DocExtentListIterator::DocumentExtentData _data
const char * _list
const char * _listEnd
bool _numeric
bool _ordinal
bool _parental
bool _finished
Constructor & Destructor Documentation
indri::index::DocExtentListMemoryBuilderIterator::DocExtentListMemoryBuilderIterator (const class DocExtentListMemoryBuilder & builder)
References indri::index::DocExtentListMemoryBuilder::_lists, indri::index::DocExtentListMemoryBuilder::_numeric, indri::index::DocExtentListMemoryBuilder::_ordinal, indri::index::DocExtentListMemoryBuilder::_parental, and reset().
Member Function Documentation
indri::index::DocExtentListIterator::DocumentExtentData * indri::index::DocExtentListMemoryBuilderIterator::currentEntry () [virtual]
Implements indri::index::DocExtentListIterator.
References _data, and _finished.
bool indri::index::DocExtentListMemoryBuilderIterator::finished () const [virtual]
Implements indri::index::DocExtentListIterator.
References _finished.
bool indri::index::DocExtentListMemoryBuilderIterator::nextEntry () [virtual]
Implements indri::index::DocExtentListIterator.
References _current, _data, _finished, _list, _listEnd, _lists, _numeric, _ordinal, _parental, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocExtentListIterator::DocumentExtentData::document, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::index::DocExtentListIterator::DocumentExtentData::extents, indri::index::DocExtentListIterator::DocumentExtentData::numbers, indri::index::Extent::ordinal, indri::index::Extent::parent, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::index::Extent::weight.
Referenced by nextEntry(), reset(), and startIteration().
bool indri::index::DocExtentListMemoryBuilderIterator::nextEntry (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::DocExtentListIterator.
References _data, indri::index::DocExtentListIterator::DocumentExtentData::document, and nextEntry().
void indri::index::DocExtentListMemoryBuilderIterator::reset (class DocExtentListMemoryBuilder & builder)
References indri::index::DocExtentListMemoryBuilder::_lists, indri::index::DocExtentListMemoryBuilder::_numeric, indri::index::DocExtentListMemoryBuilder::_ordinal, indri::index::DocExtentListMemoryBuilder::_parental, indri::index::DocExtentListMemoryBuilder::flush(), and reset().
void indri::index::DocExtentListMemoryBuilderIterator::reset (const indri::utility::greedy_vector< DocExtentListMemoryBuilderSegment, 4 > & lists, bool numeric, bool ordinal, bool parental)
References _current, _data, _finished, _list, _listEnd, _lists, _numeric, _ordinal, _parental, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocExtentListIterator::DocumentExtentData::document, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::DocExtentListIterator::DocumentExtentData::extents, nextEntry(), and indri::index::DocExtentListIterator::DocumentExtentData::numbers.
Referenced by DocExtentListMemoryBuilderIterator(), and reset().
void indri::index::DocExtentListMemoryBuilderIterator::startIteration () [virtual]
Implements indri::index::DocExtentListIterator.
References _current, _data, _list, _listEnd, _lists, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocExtentListIterator::DocumentExtentData::document, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::DocExtentListIterator::DocumentExtentData::extents, nextEntry(), and indri::index::DocExtentListIterator::DocumentExtentData::numbers.
Member Data Documentation
indri::utility::greedy_vector< DocExtentListMemoryBuilderSegment, 4 >::const_iterator indri::index::DocExtentListMemoryBuilderIterator::_current [private]
Referenced by nextEntry(), reset(), and startIteration().
indri::index::DocExtentListIterator::DocumentExtentData indri::index::DocExtentListMemoryBuilderIterator::_data [private]
Referenced by currentEntry(), nextEntry(), reset(), and startIteration().
bool indri::index::DocExtentListMemoryBuilderIterator::_finished [private]
Referenced by currentEntry(), finished(), nextEntry(), and reset().
const char* indri::index::DocExtentListMemoryBuilderIterator::_list [private]
Referenced by nextEntry(), reset(), and startIteration().
const char* indri::index::DocExtentListMemoryBuilderIterator::_listEnd [private]
Referenced by nextEntry(), reset(), and startIteration().
const indri::utility::greedy_vector< DocExtentListMemoryBuilderSegment, 4 >* indri::index::DocExtentListMemoryBuilderIterator::_lists [private]
Referenced by nextEntry(), reset(), and startIteration().
bool indri::index::DocExtentListMemoryBuilderIterator::_numeric [private]
Referenced by nextEntry(), and reset().
bool indri::index::DocExtentListMemoryBuilderIterator::_ordinal [private]
Referenced by nextEntry(), and reset().
bool indri::index::DocExtentListMemoryBuilderIterator::_parental [private]
Referenced by nextEntry(), and reset().
The documentation for this class was generated from the following files:
DocExtentListMemoryBuilder.hpp
DocExtentListMemoryBuilderIterator.cpp