Indri: indri::utility::greedy_vector< _Type, _Count > Class Template Reference
indri::utility::greedy_vector< _Type, _Count > Class Template Reference
Public Types
typedef _Type * iterator
typedef const _Type * const_iterator
typedef _Type & reference
typedef const _Type & const_reference
Public Member Functions
greedy_vector ()
template<typename _VectorType >
greedy_vector (const _VectorType &other)
greedy_vector (const my_type &other)
greedy_vector (size_t storageCount)
~greedy_vector ()
size_t size () const
size_t capacity () const
void reserve (size_t space)
void resize (size_t newSize, const _Type &prototype)
void resize (size_t newSize)
void push_back (const _Type &object)
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
_Type & operator[] (size_t index)
const _Type & operator[] (size_t index) const
reference at (size_t index)
const_reference at (size_t index) const
reference front ()
reference back ()
const_reference front () const
const_reference back () const
template<typename _Iter >
void append (const _Iter otherBegin, const _Iter otherEnd)
template<typename _Iter >
void assign (const _Iter otherBegin, const _Iter otherEnd)
my_type & operator= (const my_type &other)
template<typename _VectorType >
my_type & operator= (const _VectorType &other)
void erase (iterator spot)
void erase (iterator start, iterator finish)
void clear ()
Private Types
typedef greedy_vector< _Type,
_Count > my_type
Private Member Functions
void _allocate (size_t newSpace)
void _more_space ()
void _grow (size_t newSize, const _Type &prototype)
template<typename _Iter >
void _copy (_Type *start, _Iter other, _Iter otherEnd)
void _shrink (size_t newSize)
void _subscript_gripe ()
Private Attributes
LEMUR_PREALIGN char _stack[sizeof(_Type)*_Count] LEMUR_POSTALIGN
_Type * _array
size_t _size
size_t _space
template<typename _Type, int _Count = 16>
class indri::utility::greedy_vector< _Type, _Count >
Member Typedef Documentation
template<typename _Type, int _Count = 16> typedef const _Type* indri::utility::greedy_vector< _Type, _Count >::const_iterator
template<typename _Type, int _Count = 16> typedef const _Type& indri::utility::greedy_vector< _Type, _Count >::const_reference
template<typename _Type, int _Count = 16> typedef _Type* indri::utility::greedy_vector< _Type, _Count >::iterator
template<typename _Type, int _Count = 16> typedef greedy_vector<_Type, _Count> indri::utility::greedy_vector< _Type, _Count >::my_type [private]
template<typename _Type, int _Count = 16> typedef _Type& indri::utility::greedy_vector< _Type, _Count >::reference
Constructor & Destructor Documentation
template<typename _Type, int _Count = 16> indri::utility::greedy_vector< _Type, _Count >::greedy_vector () [inline]
template<typename _Type, int _Count = 16> template<typename _VectorType > indri::utility::greedy_vector< _Type, _Count >::greedy_vector (const _VectorType & other) [inline]
template<typename _Type, int _Count = 16> indri::utility::greedy_vector< _Type, _Count >::greedy_vector (const my_type & other) [inline]
template<typename _Type, int _Count = 16> indri::utility::greedy_vector< _Type, _Count >::greedy_vector (size_t storageCount) [inline, explicit]
template<typename _Type, int _Count = 16> indri::utility::greedy_vector< _Type, _Count >::~greedy_vector () [inline]
Member Function Documentation
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::_allocate (size_t newSpace) [inline, private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::_more_space(), indri::utility::greedy_vector< std::pair< int, int > >::greedy_vector(), and indri::utility::greedy_vector< std::pair< int, int > >::reserve().
template<typename _Type, int _Count = 16> template<typename _Iter > void indri::utility::greedy_vector< _Type, _Count >::_copy (_Type * start, _Iter other, _Iter otherEnd) [inline, private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::append(), and indri::utility::greedy_vector< std::pair< int, int > >::assign().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::_grow (size_t newSize, const _Type & prototype) [inline, private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::resize().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::_more_space () [inline, private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::_grow(), indri::utility::greedy_vector< std::pair< int, int > >::append(), indri::utility::greedy_vector< std::pair< int, int > >::assign(), and indri::utility::greedy_vector< std::pair< int, int > >::push_back().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::_shrink (size_t newSize) [inline, private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::resize().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::_subscript_gripe () [inline, private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::at().
template<typename _Type, int _Count = 16> template<typename _Iter > void indri::utility::greedy_vector< _Type, _Count >::append (const _Iter otherBegin, const _Iter otherEnd) [inline]
Referenced by indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), indri::infnet::ExtentOrNode::prepare(), indri::infnet::ExtentRestrictionNode::score(), and indri::infnet::ExtentEnforcementNode::score().
template<typename _Type, int _Count = 16> template<typename _Iter > void indri::utility::greedy_vector< _Type, _Count >::assign (const _Iter otherBegin, const _Iter otherEnd) [inline]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::greedy_vector(), indri_utility_greedy_vector_Sl_char_Sm__Sg__GetRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__GetRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__GetRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__GetRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__GetRange(), and indri::utility::greedy_vector< std::pair< int, int > >::operator=().
template<typename _Type, int _Count = 16> const_reference indri::utility::greedy_vector< _Type, _Count >::at (size_t index) const [inline]
template<typename _Type, int _Count = 16> reference indri::utility::greedy_vector< _Type, _Count >::at (size_t index) [inline]
template<typename _Type, int _Count = 16> const_reference indri::utility::greedy_vector< _Type, _Count >::back () const [inline]
template<typename _Type, int _Count = 16> reference indri::utility::greedy_vector< _Type, _Count >::back () [inline]
Referenced by indri::query::RelevanceModel::_countGrams(), indri::index::DocListMemoryBuilder::_grow(), indri::index::DocExtentListMemoryBuilder::_grow(), indri::index::DocListMemoryBuilder::flush(), indri::index::DocExtentListMemoryBuilder::flush(), indri::infnet::TermFrequencyBeliefNode::indexChanged(), indri::parse::TaggedDocumentIterator::nextDocument(), and indri::parse::TagList::writeTagList().
template<typename _Type, int _Count = 16> iterator indri::utility::greedy_vector< _Type, _Count >::begin () [inline]
template<typename _Type, int _Count = 16> const_iterator indri::utility::greedy_vector< _Type, _Count >::begin () const [inline]
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::infnet::ExtentAndNode::_and(), indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::parse::OffsetMetadataAnnotator::_cleanup(), indri::infnet::ListBeliefNode::_contextOccurrences(), indri::net::NetworkServerStub::_encodeDocument(), indri::parse::AnchorTextAnnotator::_fetchText(), indri::parse::Conflater::_lookup(), FieldModifier::_mergeData(), indri::infnet::InferenceNetwork::_moveDocListIterators(), indri::index::MemoryIndex::_removeClosedTags(), indri::utility::greedy_vector< std::pair< int, int > >::_shrink(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::MemoryIndex::_writeFieldExtents(), indri::index::IndexWriter::_writeStatistics(), indri::index::MemoryIndex::addDocument(), indri::infnet::Annotator::addMatches(), indri::infnet::WeightedExtentOrNode::annotate(), indri::infnet::UnorderedWindowNode::annotate(), indri::infnet::OrderedWindowNode::annotate(), indri::infnet::NestedListBeliefNode::annotate(), indri::infnet::NestedExtentInsideNode::annotate(), indri::infnet::ListBeliefNode::annotate(), indri::infnet::FilterRequireNode::annotate(), indri::infnet::FilterRejectNode::annotate(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentParentNode::annotate(), indri::infnet::ExtentOrNode::annotate(), indri::infnet::ExtentInsideNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), indri::infnet::ExtentDescendantNode::annotate(), indri::infnet::ExtentChildNode::annotate(), indri::index::DocumentStructure::begin(), indri::api::SnippetBuilder::build(), indri::infnet::CachedFrequencyBeliefNode::CachedFrequencyBeliefNode(), indri::index::DocumentStructure::childrenBegin(), indri::index::DocumentStructure::childrenEnd(), indri::utility::greedy_vector< std::pair< int, int > >::clear(), indri::parse::OffsetAnnotationAnnotator::convert_annotations(), indri::infnet::ContextCountAccumulator::evaluate(), indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), indri::utility::greedy_vector< std::pair< int, int > >::front(), indri::utility::greedy_vector< std::pair< int, int > >::greedy_vector(), indri::parse::AnchorTextWriter::handle(), indri::parse::AnchorTextHarvester::handle(), indri::parse::HTMLParser::handleTag(), indri::infnet::NestedListBeliefNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), indri::infnet::WeightedAndNode::indexChanged(), indri::infnet::ContextInclusionAndNode::indexChanged(), indri_utility_greedy_vector_Sl_char_Sm__Sg__AddRange(), indri_utility_greedy_vector_Sl_char_Sm__Sg__InsertRange(), indri_utility_greedy_vector_Sl_char_Sm__Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__SetRange(), indri::index::DocumentStructure::loadStructure(), indri::infnet::ListIteratorNode::matches(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::utility::greedy_vector< std::pair< int, int > >::operator=(), indri::parse::TaggedTextParser::parse(), parseddocument_copy(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::OrderedWindowNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentOrNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), print_document_data(), print_field_positions(), indri::index::DocListMemoryBuilderIterator::reset(), indri::index::DocExtentListMemoryBuilderIterator::reset(), indri::collection::CompressedCollection::retrieveMetadatum(), indri::infnet::LengthPriorNode::score(), indri::infnet::FixedPassageNode::score(), indri::infnet::FilterRequireNode::score(), indri::infnet::FilterRejectNode::score(), indri::infnet::ExtentRestrictionNode::score(), indri::infnet::ExtentEnforcementNode::score(), indri::index::DocListMemoryBuilderIterator::startIteration(), indri::index::DocExtentListMemoryBuilderIterator::startIteration(), indri::parse::URLTextAnnotator::transform(), indri::parse::OffsetAnnotationAnnotator::transform(), indri::parse::AnchorTextAnnotator::transform(), and indri::index::TermList::write().
template<typename _Type, int _Count = 16> size_t indri::utility::greedy_vector< _Type, _Count >::capacity () const [inline]
Referenced by CSharp_AttributeValuePairVector_capacity(), CSharp_Char_pVector_capacity(), CSharp_MetadataPairVector_capacity(), CSharp_TagExtentVector_capacity(), and CSharp_TermExtentVector_capacity().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::clear () [inline]
Referenced by indri::infnet::ExtentAndNode::_and(), indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::infnet::FixedPassageNode::_buildSubextents(), indri::index::DocumentStructure::_computeTopDownOrder(), indri::index::IndexWriter::_fetchMatchingInvertedLists(), indri::infnet::InferenceNetwork::_indexChanged(), indri::infnet::InferenceNetwork::_moveDocListIterators(), indri::index::DiskDocListIterator::_readEntry(), indri::index::DiskDocExtentListIterator::_readEntry(), indri::index::DiskDocListIterator::_readTopdocs(), indri::index::IndexWriter::_storeFrequentTerms(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), indri::utility::greedy_vector< std::pair< int, int > >::assign(), indri::index::TermList::clear(), indri::parse::TagList::clear(), indri::parse::Conflater::conflate(), indri::infnet::WPlusNode::hasMatch(), indri::infnet::WeightedSumNode::hasMatch(), indri::infnet::WeightedAndNode::hasMatch(), indri::infnet::ShrinkageBeliefNode::hasMatch(), indri::infnet::PlusNode::hasMatch(), indri::infnet::OrNode::hasMatch(), indri::infnet::NestedListBeliefNode::hasMatch(), indri::infnet::MaxNode::hasMatch(), indri::infnet::ListBeliefNode::hasMatch(), indri::infnet::FixedPassageNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), indri::infnet::FilterNode::hasMatch(), indri::infnet::ExtentRestrictionNode::hasMatch(), indri::infnet::ExtentEnforcementNode::hasMatch(), indri::infnet::ContextInclusionAndNode::hasMatch(), indri::infnet::WeightedAndNode::indexChanged(), indri::infnet::ContextInclusionAndNode::indexChanged(), indri::index::DocumentStructure::loadStructure(), indri::infnet::ListIteratorNode::matches(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::parse::WARCDocumentIterator::nextDocument(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::index::DocListMemoryBuilderIterator::nextEntry(), indri::index::DocExtentListMemoryBuilderIterator::nextEntry(), indri::parse::TaggedTextParser::parse(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::OrderedWindowNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::FieldLessNode::prepare(), indri::infnet::FieldIteratorNode::prepare(), indri::infnet::FieldGreaterNode::prepare(), indri::infnet::FieldEqualsNode::prepare(), indri::infnet::FieldBetweenNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentOrNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), indri::infnet::ExtentAndNode::prepare(), indri::infnet::DocListIteratorNode::prepare(), indri::infnet::BooleanAndNode::prepare(), indri::index::DocListMemoryBuilderIterator::reset(), indri::index::DocExtentListMemoryBuilderIterator::reset(), indri::infnet::WPlusNode::score(), indri::infnet::WeightedSumNode::score(), indri::infnet::WeightedAndNode::score(), indri::infnet::TermFrequencyBeliefNode::score(), indri::infnet::ShrinkageBeliefNode::score(), indri::infnet::PriorNode::score(), indri::infnet::PlusNode::score(), indri::infnet::OrNode::score(), indri::infnet::NullScorerNode::score(), indri::infnet::NotNode::score(), indri::infnet::NestedListBeliefNode::score(), indri::infnet::MaxNode::score(), indri::infnet::ListBeliefNode::score(), indri::infnet::LengthPriorNode::score(), indri::infnet::FixedPassageNode::score(), indri::infnet::FilterRequireNode::score(), indri::infnet::FilterRejectNode::score(), indri::infnet::ExtentRestrictionNode::score(), indri::infnet::ExtentEnforcementNode::score(), indri::infnet::ContextInclusionAndNode::score(), indri::infnet::CachedFrequencyBeliefNode::score(), indri::index::DiskDocListIterator::setStartOffset(), indri::collection::PriorListIterator::startIteration(), indri::index::DocListMemoryBuilderIterator::startIteration(), indri::index::DocExtentListMemoryBuilderIterator::startIteration(), indri::index::DiskDocListIterator::startIteration(), indri::index::DiskDocExtentListIterator::startIteration(), and indri::index::DocumentStructure::topDownOrder().
template<typename _Type, int _Count = 16> iterator indri::utility::greedy_vector< _Type, _Count >::end () [inline]
template<typename _Type, int _Count = 16> const_iterator indri::utility::greedy_vector< _Type, _Count >::end () const [inline]
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::infnet::ExtentAndNode::_and(), indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::parse::OffsetMetadataAnnotator::_cleanup(), indri::infnet::NestedListBeliefNode::_contextOccurrences(), indri::infnet::ListBeliefNode::_contextOccurrences(), indri::infnet::NestedListBeliefNode::_documentOccurrences(), indri::infnet::ListBeliefNode::_documentOccurrences(), indri::net::NetworkServerStub::_encodeDocument(), indri::parse::AnchorTextAnnotator::_fetchText(), indri::parse::Conflater::_lookup(), FieldModifier::_mergeData(), indri::infnet::InferenceNetwork::_moveDocListIterators(), indri::utility::greedy_vector< std::pair< int, int > >::_shrink(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::MemoryIndex::_writeFieldExtents(), indri::index::IndexWriter::_writeStatistics(), indri::index::MemoryIndex::addDocument(), indri::infnet::Annotator::addMatches(), indri::infnet::WeightedExtentOrNode::annotate(), indri::infnet::UnorderedWindowNode::annotate(), indri::infnet::ShrinkageBeliefNode::annotate(), indri::infnet::OrderedWindowNode::annotate(), indri::infnet::NestedListBeliefNode::annotate(), indri::infnet::NestedExtentInsideNode::annotate(), indri::infnet::ListBeliefNode::annotate(), indri::infnet::FilterRequireNode::annotate(), indri::infnet::FilterRejectNode::annotate(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentParentNode::annotate(), indri::infnet::ExtentOrNode::annotate(), indri::infnet::ExtentInsideNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), indri::infnet::ExtentDescendantNode::annotate(), indri::infnet::ExtentChildNode::annotate(), indri::utility::greedy_vector< std::pair< int, int > >::back(), indri::api::SnippetBuilder::build(), indri::index::DocumentStructure::childrenBegin(), indri::index::DocumentStructure::childrenEnd(), indri::utility::greedy_vector< std::pair< int, int > >::clear(), indri::parse::OffsetAnnotationAnnotator::convert_annotations(), indri::index::DocumentStructure::end(), indri::utility::greedy_vector< std::pair< int, int > >::erase(), indri::infnet::ContextCountAccumulator::evaluate(), indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), indri::utility::greedy_vector< std::pair< int, int > >::greedy_vector(), indri::parse::AnchorTextWriter::handle(), indri::parse::AnchorTextHarvester::handle(), indri::parse::HTMLParser::handleTag(), indri::infnet::NestedListBeliefNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), indri::infnet::WeightedAndNode::indexChanged(), indri::infnet::ContextInclusionAndNode::indexChanged(), indri_utility_greedy_vector_Sl_char_Sm__Sg__AddRange(), indri_utility_greedy_vector_Sl_char_Sm__Sg__InsertRange(), indri_utility_greedy_vector_Sl_char_Sm__Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__AddRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__InsertRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__SetRange(), indri::index::DocumentStructure::loadStructure(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::infnet::CachedFrequencyBeliefNode::nextCandidateDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::index::DocListMemoryBuilderIterator::nextEntry(), indri::index::DocExtentListMemoryBuilderIterator::nextEntry(), indri::utility::greedy_vector< std::pair< int, int > >::operator=(), indri::parse::TaggedTextParser::parse(), parseddocument_copy(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::OrderedWindowNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentOrNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), print_document_data(), print_field_positions(), indri::index::DocListMemoryBuilderIterator::reset(), indri::index::DocExtentListMemoryBuilderIterator::reset(), indri::collection::CompressedCollection::retrieveMetadatum(), indri::infnet::LengthPriorNode::score(), indri::infnet::FixedPassageNode::score(), indri::infnet::FilterRequireNode::score(), indri::infnet::FilterRejectNode::score(), indri::infnet::ExtentRestrictionNode::score(), indri::infnet::ExtentEnforcementNode::score(), indri::infnet::CachedFrequencyBeliefNode::score(), indri::index::DocListMemoryBuilderIterator::startIteration(), indri::index::DocExtentListMemoryBuilderIterator::startIteration(), indri::parse::URLTextAnnotator::transform(), indri::parse::OffsetAnnotationAnnotator::transform(), indri::parse::AnchorTextAnnotator::transform(), and indri::index::TermList::write().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::erase (iterator start, iterator finish) [inline]
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::erase (iterator spot) [inline]
Referenced by indri::index::MemoryIndex::_removeClosedTags(), indri::utility::greedy_vector< std::pair< int, int > >::_shrink(), indri::utility::greedy_vector< std::pair< int, int > >::clear(), indri::utility::greedy_vector< std::pair< int, int > >::erase(), and indri::parse::TaggedDocumentIterator::nextDocument().
template<typename _Type, int _Count = 16> const_reference indri::utility::greedy_vector< _Type, _Count >::front () const [inline]
template<typename _Type, int _Count = 16> reference indri::utility::greedy_vector< _Type, _Count >::front () [inline]
Referenced by indri::collection::CompressedCollection::addDocument(), and indri::infnet::TermFrequencyBeliefNode::indexChanged().
template<typename _Type, int _Count = 16> template<typename _VectorType > my_type& indri::utility::greedy_vector< _Type, _Count >::operator= (const _VectorType & other) [inline]
template<typename _Type, int _Count = 16> my_type& indri::utility::greedy_vector< _Type, _Count >::operator= (const my_type & other) [inline]
template<typename _Type, int _Count = 16> const _Type& indri::utility::greedy_vector< _Type, _Count >::operator[] (size_t index) const [inline]
template<typename _Type, int _Count = 16> _Type& indri::utility::greedy_vector< _Type, _Count >::operator[] (size_t index) [inline]
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::push_back (const _Type & object) [inline]
Referenced by indri::index::MemoryIndex::_addOpenTags(), indri::infnet::FixedPassageNode::_addSubextents(), indri::infnet::ExtentAndNode::_and(), indri::index::DocumentStructure::_computeTopDownOrder(), indri::parse::MboxDocumentIterator::_copyMetadata(), indri::index::IndexWriter::_fetchMatchingInvertedLists(), indri::parse::AnchorTextAnnotator::_fetchText(), indri::index::DocListMemoryBuilder::_grow(), indri::index::DocExtentListMemoryBuilder::_grow(), FieldModifier::_mergeData(), indri::infnet::InferenceNetwork::_moveDocListIterators(), indri::index::DiskDocListIterator::_readEntry(), indri::index::DiskDocExtentListIterator::_readEntry(), indri::collection::CompressedCollection::_readPositions(), indri::index::DiskDocListIterator::_readTopdocs(), indri::index::IndexWriter::_storeMatchInformation(), indri::collection::CompressedCollection::addDocument(), indri::index::TermList::addField(), indri::parse::TagList::addTag(), indri::index::TermList::addTerm(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::parse::HTMLParser::handleTag(), indri::infnet::WeightedAndNode::indexChanged(), indri::infnet::ContextInclusionAndNode::indexChanged(), indri_utility_greedy_vector_Sl_char_Sm__Sg__Repeat(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Repeat(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Repeat(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Repeat(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Repeat(), indri::parse::HTMLParser::initialize(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), indri::infnet::ListIteratorNode::matches(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::parse::WARCDocumentIterator::nextDocument(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::index::DocListMemoryBuilderIterator::nextEntry(), indri::index::DocExtentListMemoryBuilderIterator::nextEntry(), indri::parse::HTMLParser::normalizeURL(), indri::parse::OffsetMetadataAnnotator::open(), indri::parse::OffsetAnnotationAnnotator::open(), indri::parse::TaggedTextParser::parse(), indri::parse::RawTextParser::parseDocument(), indri::api::QueryEnvironment::pathNames(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::OrderedWindowNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::FieldLessNode::prepare(), indri::infnet::FieldGreaterNode::prepare(), indri::infnet::FieldEqualsNode::prepare(), indri::infnet::FieldBetweenNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), indri::infnet::DocListIteratorNode::prepare(), indri::infnet::BooleanAndNode::prepare(), indri::collection::Repository::processTerm(), indri::index::TermList::read(), indri::parse::OffsetAnnotationAnnotator::readAnnotationTags(), indri::collection::CompressedCollection::retrieve(), indri::infnet::WPlusNode::score(), indri::infnet::WeightedSumNode::score(), indri::infnet::WeightedAndNode::score(), indri::infnet::TermFrequencyBeliefNode::score(), indri::infnet::ShrinkageBeliefNode::score(), indri::infnet::PriorNode::score(), indri::infnet::PlusNode::score(), indri::infnet::OrNode::score(), indri::infnet::NullScorerNode::score(), indri::infnet::NotNode::score(), indri::infnet::NestedListBeliefNode::score(), indri::infnet::MaxNode::score(), indri::infnet::ListBeliefNode::score(), indri::infnet::LengthPriorNode::score(), indri::infnet::FixedPassageNode::score(), indri::infnet::ExtentRestrictionNode::score(), indri::infnet::ExtentEnforcementNode::score(), indri::infnet::ContextInclusionAndNode::score(), indri::infnet::CachedFrequencyBeliefNode::score(), indri::collection::PriorListIterator::startIteration(), indri::index::DocumentStructure::topDownOrder(), indri::parse::URLTextAnnotator::transform(), indri::parse::OffsetMetadataAnnotator::transform(), indri::parse::OffsetAnnotationAnnotator::transform(), indri::parse::AnchorTextAnnotator::transform(), indri::parse::TagList::writeMetadataList(), and indri::parse::TagList::writeTagList().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::reserve (size_t space) [inline]
Referenced by new_indri_utility_greedy_vector_Sl_char_Sm__Sg___SWIG_1(), new_indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg___SWIG_1(), new_indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_1(), new_indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg___SWIG_1(), and new_indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg___SWIG_1().
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::resize (size_t newSize) [inline]
template<typename _Type, int _Count = 16> void indri::utility::greedy_vector< _Type, _Count >::resize (size_t newSize, const _Type & prototype) [inline]
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::collection::CompressedCollection::addDocument(), indri::infnet::WPlusNode::hasMatch(), indri::infnet::WeightedSumNode::hasMatch(), indri::infnet::WeightedAndNode::hasMatch(), indri::infnet::TermFrequencyBeliefNode::hasMatch(), indri::infnet::ShrinkageBeliefNode::hasMatch(), indri::infnet::PriorNode::hasMatch(), indri::infnet::PlusNode::hasMatch(), indri::infnet::OrNode::hasMatch(), indri::infnet::NotNode::hasMatch(), indri::infnet::NestedListBeliefNode::hasMatch(), indri::infnet::MaxNode::hasMatch(), indri::infnet::ListBeliefNode::hasMatch(), indri::infnet::FixedPassageNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), indri::infnet::FilterNode::hasMatch(), indri::infnet::ExtentRestrictionNode::hasMatch(), indri::infnet::ExtentEnforcementNode::hasMatch(), indri::infnet::ContextInclusionAndNode::hasMatch(), indri::infnet::CachedFrequencyBeliefNode::hasMatch(), indri::index::DocumentStructure::loadStructure(), and indri::utility::greedy_vector< std::pair< int, int > >::resize().
template<typename _Type, int _Count = 16> size_t indri::utility::greedy_vector< _Type, _Count >::size () const [inline]
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::index::MemoryIndex::_addOpenTags(), indri::infnet::FixedPassageNode::_buildSubextents(), indri::index::DocumentStructure::_computeTopDownOrder(), indri::infnet::NestedListBeliefNode::_contextLength(), indri::infnet::ListBeliefNode::_contextLength(), indri::infnet::NestedListBeliefNode::_contextOccurrences(), indri::infnet::ListBeliefNode::_contextOccurrences(), indri::infnet::NestedListBeliefNode::_documentOccurrences(), indri::infnet::ListBeliefNode::_documentOccurrences(), indri::net::NetworkServerStub::_encodeDocument(), indri::parse::AnchorTextAnnotator::_fetchText(), indri::parse::OffsetMetadataAnnotator::_getDocno(), indri::parse::OffsetAnnotationAnnotator::_getDocno(), indri::index::DocListMemoryBuilder::_grow(), indri::index::DocExtentListMemoryBuilder::_grow(), indri::parse::AnchorTextAnnotator::_matchingDocno(), FieldModifier::_mergeData(), indri::infnet::InferenceNetwork::_moveDocListIterators(), indri::parse::KrovetzStemmerTransformation::_processTerms(), indri::parse::ArabicStemmerTransformation::_processTerms(), indri::index::IndexWriter::_pushInvertedLists(), indri::index::MemoryIndex::_removeClosedTags(), indri::parse::KrovetzStemmerTransformation::_restart(), indri::parse::ArabicStemmerTransformation::_restart(), indri::query::RelevanceModel::_scoreGrams(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_storeMatchInformation(), indri::index::IndexWriter::_writeDirectLists(), indri::index::MemoryIndex::_writeDocumentTermList(), indri::index::MemoryIndex::_writeFieldExtents(), indri::index::IndexWriter::_writeFieldList(), indri::collection::CompressedCollection::_writePositions(), indri::index::MemoryIndex::addDocument(), indri::collection::CompressedCollection::addDocument(), indri::api::IndexEnvironment::addFile(), indri::infnet::Annotator::addMatches(), indri::parse::TagList::addTag(), indri::infnet::ShrinkageBeliefNode::annotate(), indri::infnet::PriorNode::annotate(), indri::infnet::NestedListBeliefNode::annotate(), indri::infnet::NestedExtentInsideNode::annotate(), indri::infnet::MaxNode::annotate(), indri::infnet::ListBeliefNode::annotate(), indri::infnet::FixedPassageNode::annotate(), indri::infnet::FilterRejectNode::annotate(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentParentNode::annotate(), indri::infnet::ExtentInsideNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), indri::infnet::ExtentDescendantNode::annotate(), indri::infnet::ExtentChildNode::annotate(), indri::api::SnippetBuilder::build(), indri::parse::OffsetAnnotationAnnotator::convert_annotations(), CSharp_AttributeValuePairVector_size(), CSharp_Char_pVector_size(), CSharp_MetadataPairVector_size(), CSharp_TagExtentVector_size(), CSharp_TermExtentVector_size(), indri::infnet::ScoredExtentAccumulator::evaluate(), indri::infnet::ListAccumulator::evaluate(), indri::infnet::ContextCountAccumulator::evaluate(), indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), indri::index::DocListMemoryBuilder::flush(), indri::index::DocExtentListMemoryBuilder::flush(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::parse::AnchorTextWriter::handle(), indri::parse::AnchorTextHarvester::handle(), indri::parse::HTMLParser::handleTag(), indri::infnet::WPlusNode::hasMatch(), indri::infnet::WeightedSumNode::hasMatch(), indri::infnet::WeightedAndNode::hasMatch(), indri::infnet::TermFrequencyBeliefNode::hasMatch(), indri::infnet::ShrinkageBeliefNode::hasMatch(), indri::infnet::PriorNode::hasMatch(), indri::infnet::PlusNode::hasMatch(), indri::infnet::OrNode::hasMatch(), indri::infnet::NotNode::hasMatch(), indri::infnet::NestedListBeliefNode::hasMatch(), indri::infnet::MaxNode::hasMatch(), indri::infnet::ListBeliefNode::hasMatch(), indri::infnet::FixedPassageNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), indri::infnet::FilterNode::hasMatch(), indri::infnet::ExtentRestrictionNode::hasMatch(), indri::infnet::ExtentEnforcementNode::hasMatch(), indri::infnet::ContextInclusionAndNode::hasMatch(), indri::infnet::CachedFrequencyBeliefNode::hasMatch(), indri::infnet::WeightedAndNode::indexChanged(), indri::infnet::TermFrequencyBeliefNode::indexChanged(), indri::infnet::ContextInclusionAndNode::indexChanged(), indri_utility_greedy_vector_Sl_char_Sm__Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__SetRange(), indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__SetRange(), indri::parse::HTMLParser::initialize(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), indri::index::DocumentStructure::loadStructure(), indri::infnet::ListIteratorNode::matches(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::index::DocListMemoryBuilder::memorySize(), indri::index::DocExtentListMemoryBuilder::memorySize(), indri::infnet::WeightedAndNode::nextCandidateDocument(), indri::infnet::ContextInclusionAndNode::nextCandidateDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::parse::HTMLParser::normalizeURL(), indri::parse::TaggedTextParser::parse(), parseddocument_copy(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::FieldLessNode::prepare(), indri::infnet::FieldGreaterNode::prepare(), indri::infnet::FieldEqualsNode::prepare(), indri::infnet::FieldBetweenNode::prepare(), indri::infnet::DocListIteratorNode::prepare(), indri::infnet::BooleanAndNode::prepare(), print_document_data(), print_field_positions(), print_invfile(), print_term_counts(), print_term_positions(), FieldModifier::processFields(), indri::infnet::WPlusNode::score(), indri::infnet::WeightedSumNode::score(), indri::infnet::WeightedAndNode::score(), indri::infnet::TermFrequencyBeliefNode::score(), indri::infnet::PlusNode::score(), indri::infnet::OrNode::score(), indri::infnet::NotNode::score(), indri::infnet::MaxNode::score(), indri::infnet::LengthPriorNode::score(), indri::infnet::FixedPassageNode::score(), indri::infnet::FilterRejectNode::score(), indri::infnet::ExtentRestrictionNode::score(), indri::infnet::ExtentEnforcementNode::score(), indri::infnet::ContextInclusionAndNode::score(), indri::infnet::ListIteratorNode::sortbegin(), indri::infnet::ListIteratorNode::sortparent(), indri::index::DocumentStructure::topDownOrder(), indri::parse::UTF8CaseNormalizationTransformation::transform(), indri::parse::URLTextAnnotator::transform(), indri::parse::StopperTransformation::transform(), indri::parse::PorterStemmerTransformation::transform(), indri::parse::OffsetMetadataAnnotator::transform(), indri::parse::NumericFieldAnnotator::transform(), indri::parse::NormalizationTransformation::transform(), indri::parse::KrovetzStemmerTransformation::transform(), indri::parse::ArabicStemmerTransformation::transform(), indri::parse::AnchorTextAnnotator::transform(), indri::infnet::UWNodeChildLess(), validate(), indri::index::TermList::write(), indri::parse::TagList::writeMetadataList(), indri::parse::TagList::writeTagList(), indri::index::DocExtentListMemoryBuilder::~DocExtentListMemoryBuilder(), and indri::parse::TaggedTextParser::~TaggedTextParser().
Member Data Documentation
template<typename _Type, int _Count = 16> _Type* indri::utility::greedy_vector< _Type, _Count >::_array [private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::_allocate(), indri::utility::greedy_vector< std::pair< int, int > >::_grow(), indri::utility::greedy_vector< std::pair< int, int > >::append(), indri::utility::greedy_vector< std::pair< int, int > >::assign(), indri::utility::greedy_vector< std::pair< int, int > >::at(), indri::utility::greedy_vector< std::pair< int, int > >::begin(), indri::utility::greedy_vector< std::pair< int, int > >::end(), indri::utility::greedy_vector< std::pair< int, int > >::erase(), indri::utility::greedy_vector< std::pair< int, int > >::operator[](), indri::utility::greedy_vector< std::pair< int, int > >::push_back(), and indri::utility::greedy_vector< std::pair< int, int > >::~greedy_vector().
template<typename _Type, int _Count = 16> size_t indri::utility::greedy_vector< _Type, _Count >::_size [private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::_allocate(), indri::utility::greedy_vector< std::pair< int, int > >::_grow(), indri::utility::greedy_vector< std::pair< int, int > >::_shrink(), indri::utility::greedy_vector< std::pair< int, int > >::append(), indri::utility::greedy_vector< std::pair< int, int > >::assign(), indri::utility::greedy_vector< std::pair< int, int > >::at(), indri::utility::greedy_vector< std::pair< int, int > >::end(), indri::utility::greedy_vector< std::pair< int, int > >::erase(), indri::utility::greedy_vector< std::pair< int, int > >::operator[](), indri::utility::greedy_vector< std::pair< int, int > >::push_back(), indri::utility::greedy_vector< std::pair< int, int > >::resize(), indri::utility::greedy_vector< std::pair< int, int > >::size(), and indri::utility::greedy_vector< std::pair< int, int > >::~greedy_vector().
template<typename _Type, int _Count = 16> size_t indri::utility::greedy_vector< _Type, _Count >::_space [private]
Referenced by indri::utility::greedy_vector< std::pair< int, int > >::_allocate(), indri::utility::greedy_vector< std::pair< int, int > >::_grow(), indri::utility::greedy_vector< std::pair< int, int > >::_more_space(), indri::utility::greedy_vector< std::pair< int, int > >::append(), indri::utility::greedy_vector< std::pair< int, int > >::assign(), indri::utility::greedy_vector< std::pair< int, int > >::capacity(), indri::utility::greedy_vector< std::pair< int, int > >::greedy_vector(), indri::utility::greedy_vector< std::pair< int, int > >::push_back(), and indri::utility::greedy_vector< std::pair< int, int > >::reserve().
template<typename _Type, int _Count = 16> LEMUR_PREALIGN char _stack [ sizeof(_Type) * _Count ] indri::utility::greedy_vector< _Type, _Count >::LEMUR_POSTALIGN [private]
The documentation for this class was generated from the following file:
greedy_vector