Indri: indri::server::LocalQueryServer Class Reference
indri::server::LocalQueryServer Class Reference
#include <LocalQueryServer.hpp>
Public Member Functions
LocalQueryServer (indri::collection::Repository &repository)
QueryServerResponse * runQuery (std::vector< indri::lang::Node * > &roots, int resultsRequested, bool optimize)
indri::api::ParsedDocument * document (lemur::api::DOCID_T documentID)
std::string documentMetadatum (lemur::api::DOCID_T documentID, const std::string &attributeName)
QueryServerDocumentIDsResponse * documentIDsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)
QueryServerDocumentsResponse * documentsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)
QueryServerDocumentsResponse * documents (const std::vector< lemur::api::DOCID_T > &documentIDs)
QueryServerMetadataResponse * documentMetadata (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::string &attributeName)
QueryServerMetadataResponse * pathNames (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::vector< int > &pathBegins, const std::vector< int > &pathEnds)
INT64 termCount ()
INT64 termCount (const std::string &term)
INT64 termCountUnique ()
INT64 stemCount (const std::string &stem)
std::string termName (lemur::api::TERMID_T term)
lemur::api::TERMID_T termID (const std::string &term)
std::string stemTerm (const std::string &term)
std::vector< std::string > fieldList ()
INT64 termFieldCount (const std::string &term, const std::string &field)
INT64 stemFieldCount (const std::string &stem, const std::string &field)
int documentLength (lemur::api::DOCID_T documentID)
INT64 documentCount ()
INT64 documentCount (const std::string &term)
INT64 documentStemCount (const std::string &term)
QueryServerVectorsResponse * documentVectors (const std::vector< lemur::api::DOCID_T > &documentIDs)
void setMaxWildcardTerms (int maxTerms)
sets the maximum number of terms to be generated for a wildcard term. If the synonym list is greater than this, an exception will be thrown
Private Member Functions
indri::index::Index * _indexWithDocument (indri::collection::Repository::index_state &state, lemur::api::DOCID_T documentID)
Private Attributes
bool _optimizeParameter
indri::collection::Repository & _repository
indri::lang::ListCache _cache
int _maxWildcardMatchesPerTerm
Constructor & Destructor Documentation
indri::server::LocalQueryServer::LocalQueryServer (indri::collection::Repository & repository)
References _optimizeParameter, and indri::api::Parameters::instance().
Member Function Documentation
indri::index::Index * indri::server::LocalQueryServer::_indexWithDocument (indri::collection::Repository::index_state & state, lemur::api::DOCID_T documentID) [private]
Referenced by documentLength(), documentVectors(), and pathNames().
indri::api::ParsedDocument * indri::server::LocalQueryServer::document (lemur::api::DOCID_T documentID)
References _repository, indri::collection::Repository::collection(), and indri::collection::CompressedCollection::retrieve().
Referenced by documents().
INT64 indri::server::LocalQueryServer::documentCount (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _repository, documentStemCount(), and indri::collection::Repository::processTerm().
INT64 indri::server::LocalQueryServer::documentCount () [virtual]
Implements indri::server::QueryServer.
References _repository, indri::index::DeletedDocumentList::deletedCount(), indri::collection::Repository::deletedList(), and indri::collection::Repository::indexes().
Referenced by print_repository_stats().
indri::server::QueryServerDocumentIDsResponse * indri::server::LocalQueryServer::documentIDsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues) [virtual]
Implements indri::server::QueryServer.
References _repository, indri::collection::Repository::collection(), documents(), and indri::collection::CompressedCollection::retrieveIDByMetadatum().
int indri::server::LocalQueryServer::documentLength (lemur::api::DOCID_T documentID) [virtual]
Implements indri::server::QueryServer.
References _indexWithDocument(), _repository, indri::index::Index::documentLength(), indri::collection::Repository::indexes(), and indri::index::Index::statisticsLock().
indri::server::QueryServerMetadataResponse * indri::server::LocalQueryServer::documentMetadata (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::string & attributeName) [virtual]
Implements indri::server::QueryServer.
References documentMetadatum().
std::string indri::server::LocalQueryServer::documentMetadatum (lemur::api::DOCID_T documentID, const std::string & attributeName)
References _repository, indri::collection::Repository::collection(), and indri::collection::CompressedCollection::retrieveMetadatum().
Referenced by documentMetadata().
indri::server::QueryServerDocumentsResponse * indri::server::LocalQueryServer::documents (const std::vector< lemur::api::DOCID_T > & documentIDs) [virtual]
Implements indri::server::QueryServer.
References document().
Referenced by documentIDsFromMetadata(), and documentsFromMetadata().
indri::server::QueryServerDocumentsResponse * indri::server::LocalQueryServer::documentsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues) [virtual]
Implements indri::server::QueryServer.
References _repository, indri::collection::Repository::collection(), documents(), and indri::collection::CompressedCollection::retrieveByMetadatum().
INT64 indri::server::LocalQueryServer::documentStemCount (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::indexes().
Referenced by documentCount().
indri::server::QueryServerVectorsResponse * indri::server::LocalQueryServer::documentVectors (const std::vector< lemur::api::DOCID_T > & documentIDs) [virtual]
Implements indri::server::QueryServer.
References _indexWithDocument(), _repository, indri::server::LocalQueryServerVectorsResponse::addVector(), indri::collection::Repository::indexes(), indri::index::Index::statisticsLock(), and indri::index::Index::termList().
Referenced by print_document_vector().
std::vector< std::string > indri::server::LocalQueryServer::fieldList () [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::fields().
Referenced by print_repository_stats().
indri::server::QueryServerMetadataResponse * indri::server::LocalQueryServer::pathNames (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::vector< int > & pathBegins, const std::vector< int > & pathEnds) [virtual]
Implements indri::server::QueryServer.
References _indexWithDocument(), _repository, indri::index::TermList::fields(), indri::index::DocumentStructure::findLeaf(), indri::collection::Repository::indexes(), indri::index::DocumentStructure::loadStructure(), indri::index::DocumentStructure::path(), indri::index::DocumentStructure::setIndex(), and indri::index::Index::termList().
indri::server::QueryServerResponse * indri::server::LocalQueryServer::runQuery (std::vector< indri::lang::Node * > & roots, int resultsRequested, bool optimize) [virtual]
Implements indri::server::QueryServer.
References _cache, _maxWildcardMatchesPerTerm, _optimizeParameter, _repository, indri::infnet::InferenceNetwork::evaluate(), indri::infnet::InferenceNetworkBuilder::getNetwork(), and indri::lang::ApplyCopiers< T, NodeType >::roots().
void indri::server::LocalQueryServer::setMaxWildcardTerms (int maxTerms) [virtual]
sets the maximum number of terms to be generated for a wildcard term. If the synonym list is greater than this, an exception will be thrown
Parameters:
maxTerms the maximum number of terms
Implements indri::server::QueryServer.
References _maxWildcardMatchesPerTerm.
INT64 indri::server::LocalQueryServer::stemCount (const std::string & stem) [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::indexes().
Referenced by termCount().
INT64 indri::server::LocalQueryServer::stemFieldCount (const std::string & stem, const std::string & field) [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::indexes().
Referenced by termFieldCount().
std::string indri::server::LocalQueryServer::stemTerm (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::processTerm().
INT64 indri::server::LocalQueryServer::termCount (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _repository, indri::collection::Repository::processTerm(), and stemCount().
INT64 indri::server::LocalQueryServer::termCount () [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::indexes().
Referenced by print_field_positions(), print_repository_stats(), print_term_counts(), and print_term_positions().
INT64 indri::server::LocalQueryServer::termCountUnique () [virtual]
Implements indri::server::QueryServer.
References _repository, and indri::collection::Repository::indexes().
INT64 indri::server::LocalQueryServer::termFieldCount (const std::string & term, const std::string & field) [virtual]
Implements indri::server::QueryServer.
References _repository, indri::collection::Repository::processTerm(), and stemFieldCount().
lemur::api::TERMID_T indri::server::LocalQueryServer::termID (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _repository, indri::collection::Repository::indexes(), indri::collection::Repository::processTerm(), indri::index::Index::statisticsLock(), and indri::index::Index::term().
std::string indri::server::LocalQueryServer::termName (lemur::api::TERMID_T term) [virtual]
Implements indri::server::QueryServer.
References _repository, indri::collection::Repository::indexes(), indri::index::Index::statisticsLock(), and indri::index::Index::term().
Member Data Documentation
indri::lang::ListCache indri::server::LocalQueryServer::_cache [private]
Referenced by runQuery().
int indri::server::LocalQueryServer::_maxWildcardMatchesPerTerm [private]
Referenced by runQuery(), and setMaxWildcardTerms().
bool indri::server::LocalQueryServer::_optimizeParameter [private]
Referenced by LocalQueryServer(), and runQuery().
indri::collection::Repository& indri::server::LocalQueryServer::_repository [private]
Referenced by document(), documentCount(), documentIDsFromMetadata(), documentLength(), documentMetadatum(), documentsFromMetadata(), documentStemCount(), documentVectors(), fieldList(), pathNames(), runQuery(), stemCount(), stemFieldCount(), stemTerm(), termCount(), termCountUnique(), termFieldCount(), termID(), and termName().
The documentation for this class was generated from the following files:
LocalQueryServer.hpp
LocalQueryServer.cpp