Indri: indri::query::QueryExpander Class Reference
indri::query::QueryExpander Class Reference
#include <QueryExpander.hpp>
Public Member Functions
QueryExpander (indri::api::QueryEnvironment *env, indri::api::Parameters &param)
virtual ~QueryExpander ()
std::vector
< indri::api::ScoredExtentResult > runExpandedQuery (std::string originalQuery, int resultsRequested, bool verbose=false)
virtual std::string expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > &results)=0
Protected Member Functions
std::vector
< indri::api::DocumentVector * > getDocumentVectors (std::vector< indri::api::ScoredExtentResult > &results, int rmDocs)
std::vector< std::string > * getVocabulary (std::vector< indri::api::ScoredExtentResult > &results, int rmDocs)
std::vector< std::string > * getVocabulary (std::vector< indri::api::DocumentVector * > &docVectors)
std::string buildQuery (const std::string &originalQuery, double originalWeight, const std::vector< std::pair< std::string, double > > &expansionTerms, int termCount)
UINT64 getCF (const std::string &term)
Protected Attributes
indri::api::QueryEnvironment * _env
indri::api::Parameters _param
std::map< std::string, bool > _stopwords
Private Attributes
std::map< std::string, UINT64 > _cf_cache
Constructor & Destructor Documentation
indri::query::QueryExpander::QueryExpander (indri::api::QueryEnvironment * env, indri::api::Parameters & param)
References _env, _param, _stopwords, indri::api::Parameters::exists(), and indri::api::Parameters::size().
virtual indri::query::QueryExpander::~QueryExpander () [inline, virtual]
Member Function Documentation
std::string indri::query::QueryExpander::buildQuery (const std::string & originalQuery, double originalWeight, const std::vector< std::pair< std::string, double > > & expansionTerms, int termCount) [protected]
References _stopwords.
Referenced by indri::query::RMExpander::expand(), and indri::query::PonteExpander::expand().
virtual std::string indri::query::QueryExpander::expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > & results) [pure virtual]
Implemented in indri::query::PonteExpander, indri::query::RMExpander, and indri::query::TFIDFExpander.
Referenced by QueryThread::_runQuery(), and runExpandedQuery().
UINT64 indri::query::QueryExpander::getCF (const std::string & term) [protected]
References _cf_cache, _env, and indri::api::QueryEnvironment::stemCount().
Referenced by indri::query::PonteExpander::expand().
std::vector< indri::api::DocumentVector * > indri::query::QueryExpander::getDocumentVectors (std::vector< indri::api::ScoredExtentResult > & results, int rmDocs) [protected]
References _env, and indri::api::QueryEnvironment::documentVectors().
Referenced by indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), and getVocabulary().
std::vector< std::string > * indri::query::QueryExpander::getVocabulary (std::vector< indri::api::DocumentVector * > & docVectors) [protected]
References indri::api::DocumentVector::positions(), and indri::api::DocumentVector::stems().
std::vector< std::string > * indri::query::QueryExpander::getVocabulary (std::vector< indri::api::ScoredExtentResult > & results, int rmDocs) [protected]
References indri::utility::delete_vector_contents(), and getDocumentVectors().
Referenced by indri::query::TFIDFExpander::expand(), and indri::query::PonteExpander::expand().
std::vector< indri::api::ScoredExtentResult > indri::query::QueryExpander::runExpandedQuery (std::string originalQuery, int resultsRequested, bool verbose = false)
References _env, expand(), and indri::api::QueryEnvironment::runQuery().
Member Data Documentation
std::map<std::string, UINT64> indri::query::QueryExpander::_cf_cache [private]
Referenced by getCF().
indri::api::QueryEnvironment* indri::query::QueryExpander::_env [protected]
Referenced by indri::query::TFIDFExpander::expand(), indri::query::RMExpander::expand(), indri::query::PonteExpander::expand(), getCF(), getDocumentVectors(), QueryExpander(), and runExpandedQuery().
indri::api::Parameters indri::query::QueryExpander::_param [protected]
Referenced by indri::query::TFIDFExpander::expand(), indri::query::RMExpander::expand(), indri::query::PonteExpander::expand(), and QueryExpander().
std::map< std::string, bool > indri::query::QueryExpander::_stopwords [protected]
Referenced by indri::query::TFIDFExpander::_buildQuery(), buildQuery(), and QueryExpander().
The documentation for this class was generated from the following files:
QueryExpander.hpp
QueryExpander.cpp