Indri: indri::index::DiskTermListFileIterator Class Reference
indri::index::DiskTermListFileIterator Class Reference
#include <DiskTermListFileIterator.hpp>
Public Member Functions
DiskTermListFileIterator (indri::file::File &termListFile)
void startIteration ()
TermList * currentEntry ()
bool nextEntry ()
bool nextEntry (lemur::api::DOCID_T documentID)
bool finished ()
Private Attributes
TermList _termList
indri::file::File & _termListFile
indri::file::SequentialReadBuffer _buffer
UINT64 _fileSize
bool _finished
int _currentDocument
Constructor & Destructor Documentation
indri::index::DiskTermListFileIterator::DiskTermListFileIterator (indri::file::File & termListFile)
Member Function Documentation
indri::index::TermList * indri::index::DiskTermListFileIterator::currentEntry () [virtual]
Implements indri::index::TermListFileIterator.
References _termList, and finished().
bool indri::index::DiskTermListFileIterator::finished () [virtual]
Implements indri::index::TermListFileIterator.
References _finished.
Referenced by currentEntry().
bool indri::index::DiskTermListFileIterator::nextEntry (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::TermListFileIterator.
References _buffer, _currentDocument, _fileSize, _finished, _termList, indri::file::SequentialReadBuffer::position(), indri::index::TermList::read(), and indri::file::SequentialReadBuffer::read().
bool indri::index::DiskTermListFileIterator::nextEntry () [virtual]
Implements indri::index::TermListFileIterator.
References _buffer, _currentDocument, _fileSize, _finished, _termList, indri::file::SequentialReadBuffer::position(), indri::index::TermList::read(), and indri::file::SequentialReadBuffer::read().
Referenced by startIteration().
void indri::index::DiskTermListFileIterator::startIteration () [virtual]
Implements indri::index::TermListFileIterator.
References _finished, and nextEntry().
Member Data Documentation
indri::file::SequentialReadBuffer indri::index::DiskTermListFileIterator::_buffer [private]
Referenced by nextEntry().
int indri::index::DiskTermListFileIterator::_currentDocument [private]
Referenced by nextEntry().
UINT64 indri::index::DiskTermListFileIterator::_fileSize [private]
Referenced by nextEntry().
bool indri::index::DiskTermListFileIterator::_finished [private]
Referenced by finished(), nextEntry(), and startIteration().
TermList indri::index::DiskTermListFileIterator::_termList [private]
Referenced by currentEntry(), and nextEntry().
indri::file::File& indri::index::DiskTermListFileIterator::_termListFile [private]
The documentation for this class was generated from the following files:
DiskTermListFileIterator.hpp
DiskTermListFileIterator.cpp