Indri: indri::infnet::FilterNode Class Reference
indri::infnet::FilterNode Class Reference
#include <FilterNode.hpp>
Public Member Functions
FilterNode (const std::string &name, BeliefNode *child, const std::vector< lemur::api::DOCID_T > &documents)
virtual void setSiblingsFlag (int f)
lemur::api::DOCID_T nextCandidateDocument ()
void annotate (Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
double maximumScore ()
double maximumBackgroundScore ()
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
void indexChanged (indri::index::Index &index)
const std::string & getName () const
Private Attributes
BeliefNode * _belief
std::vector< lemur::api::DOCID_T > _documents
std::string _name
int _index
indri::utility::greedy_vector
< bool > _matches
Constructor & Destructor Documentation
indri::infnet::FilterNode::FilterNode (const std::string & name, BeliefNode * child, const std::vector< lemur::api::DOCID_T > & documents) [inline]
References _belief, _documents, _index, and _name.
Member Function Documentation
void indri::infnet::FilterNode::annotate (Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _belief, and indri::infnet::BeliefNode::annotate().
const std::string& indri::infnet::FilterNode::getName () const [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector<bool>& indri::infnet::FilterNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _documents, _index, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::FilterNode::hasMatch (lemur::api::DOCID_T documentID) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _documents, and _index.
void indri::infnet::FilterNode::indexChanged (indri::index::Index & index) [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _index.
double indri::infnet::FilterNode::maximumBackgroundScore () [inline, virtual]
Implements indri::infnet::BeliefNode.
References _belief, and indri::infnet::BeliefNode::maximumBackgroundScore().
double indri::infnet::FilterNode::maximumScore () [inline, virtual]
Implements indri::infnet::BeliefNode.
References _belief, and indri::infnet::BeliefNode::maximumScore().
lemur::api::DOCID_T indri::infnet::FilterNode::nextCandidateDocument () [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _documents, and _index.
const indri::utility::greedy_vector<indri::api::ScoredExtentResult>& indri::infnet::FilterNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _belief, and indri::infnet::BeliefNode::score().
virtual void indri::infnet::FilterNode::setSiblingsFlag (int f) [inline, virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _belief, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
BeliefNode* indri::infnet::FilterNode::_belief [private]
Referenced by annotate(), FilterNode(), maximumBackgroundScore(), maximumScore(), score(), and setSiblingsFlag().
std::vector<lemur::api::DOCID_T> indri::infnet::FilterNode::_documents [private]
Referenced by FilterNode(), hasMatch(), and nextCandidateDocument().
int indri::infnet::FilterNode::_index [private]
Referenced by FilterNode(), hasMatch(), indexChanged(), and nextCandidateDocument().
indri::utility::greedy_vector<bool> indri::infnet::FilterNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::FilterNode::_name [private]
Referenced by FilterNode(), and getName().
The documentation for this class was generated from the following file:
FilterNode.hpp