Indri: indri::lang::WSumNode Class Reference
indri::lang::WSumNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
WSumNode ()
WSumNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::WSumNode::WSumNode () [inline]
indri::lang::WSumNode::WSumNode (Unpacker & unpacker) [inline]
References indri::lang::WeightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::WSumNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_copy().
UINT64 indri::lang::WSumNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_hashCode().
std::string indri::lang::WSumNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_childText().
std::string indri::lang::WSumNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::WSumNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp