Indri: indri::infnet::InferenceNetworkNode Class Reference
indri::infnet::InferenceNetworkNode Class Reference
#include <InferenceNetworkNode.hpp>
Public Member Functions
virtual ~InferenceNetworkNode ()
virtual lemur::api::DOCID_T nextCandidateDocument ()=0
virtual void indexChanged (indri::index::Index &index)=0
virtual const std::string & getName () const =0
Constructor & Destructor Documentation
virtual indri::infnet::InferenceNetworkNode::~InferenceNetworkNode () [inline, virtual]
Member Function Documentation
virtual const std::string& indri::infnet::InferenceNetworkNode::getName () const [pure virtual]
Implemented in indri::infnet::Annotator, indri::infnet::BooleanAndNode, indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextCountAccumulator, indri::infnet::ContextInclusionAndNode, indri::infnet::ContextSimpleCountAccumulator, indri::infnet::DocListIteratorNode, indri::infnet::DocumentStructureHolderNode, indri::infnet::ExtentAndNode, indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentInsideNode, indri::infnet::ExtentOrNode, indri::infnet::ExtentParentNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FieldBetweenNode, indri::infnet::FieldEqualsNode, indri::infnet::FieldGreaterNode, indri::infnet::FieldIteratorNode, indri::infnet::FieldLessNode, indri::infnet::FieldWildcardNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListAccumulator, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedExtentInsideNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullListNode, indri::infnet::NullScorerNode, indri::infnet::OrderedWindowNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ScoredExtentAccumulator, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::UnorderedWindowNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedExtentOrNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::Annotator::add().
virtual void indri::infnet::InferenceNetworkNode::indexChanged (indri::index::Index & index) [pure virtual]
Implemented in indri::infnet::Annotator, indri::infnet::BooleanAndNode, indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextCountAccumulator, indri::infnet::ContextInclusionAndNode, indri::infnet::ContextSimpleCountAccumulator, indri::infnet::DocListIteratorNode, indri::infnet::DocumentStructureHolderNode, indri::infnet::ExtentAndNode, indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentInsideNode, indri::infnet::ExtentOrNode, indri::infnet::ExtentParentNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FieldBetweenNode, indri::infnet::FieldEqualsNode, indri::infnet::FieldGreaterNode, indri::infnet::FieldIteratorNode, indri::infnet::FieldLessNode, indri::infnet::FieldWildcardNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListAccumulator, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedExtentInsideNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullListNode, indri::infnet::NullScorerNode, indri::infnet::OrderedWindowNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ScoredExtentAccumulator, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::UnorderedWindowNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedExtentOrNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
virtual lemur::api::DOCID_T indri::infnet::InferenceNetworkNode::nextCandidateDocument () [pure virtual]
Implemented in indri::infnet::Annotator, indri::infnet::BooleanAndNode, indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextCountAccumulator, indri::infnet::ContextInclusionAndNode, indri::infnet::ContextSimpleCountAccumulator, indri::infnet::DocListIteratorNode, indri::infnet::DocumentStructureHolderNode, indri::infnet::ExtentAndNode, indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentInsideNode, indri::infnet::ExtentOrNode, indri::infnet::ExtentParentNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FieldBetweenNode, indri::infnet::FieldEqualsNode, indri::infnet::FieldGreaterNode, indri::infnet::FieldIteratorNode, indri::infnet::FieldLessNode, indri::infnet::FieldWildcardNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListAccumulator, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedExtentInsideNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullListNode, indri::infnet::NullScorerNode, indri::infnet::OrderedWindowNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ScoredExtentAccumulator, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::UnorderedWindowNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedExtentOrNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::ShrinkageBeliefNode::nextCandidateDocument(), indri::infnet::ScoredExtentAccumulator::nextCandidateDocument(), indri::infnet::NestedListBeliefNode::nextCandidateDocument(), indri::infnet::NestedExtentInsideNode::nextCandidateDocument(), indri::infnet::ListBeliefNode::nextCandidateDocument(), indri::infnet::ListAccumulator::nextCandidateDocument(), indri::infnet::LengthPriorNode::nextCandidateDocument(), indri::infnet::FixedPassageNode::nextCandidateDocument(), indri::infnet::FilterRequireNode::nextCandidateDocument(), indri::infnet::FilterRejectNode::nextCandidateDocument(), indri::infnet::ExtentRestrictionNode::nextCandidateDocument(), indri::infnet::ExtentParentNode::nextCandidateDocument(), indri::infnet::ExtentInsideNode::nextCandidateDocument(), indri::infnet::ExtentEnforcementNode::nextCandidateDocument(), indri::infnet::ExtentDescendantNode::nextCandidateDocument(), indri::infnet::ExtentChildNode::nextCandidateDocument(), indri::infnet::ContextCountAccumulator::nextCandidateDocument(), and indri::infnet::Annotator::nextCandidateDocument().
The documentation for this class was generated from the following file:
InferenceNetworkNode.hpp