Indri: indri::lang::ExtentAnd Class Reference
indri::lang::ExtentAnd Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ExtentAnd ()
ExtentAnd (const std::vector< RawExtentNode * > &children)
ExtentAnd (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void addChild (RawExtentNode *node)
std::vector< RawExtentNode * > & getChildren ()
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
std::vector< RawExtentNode * > _children
Constructor & Destructor Documentation
indri::lang::ExtentAnd::ExtentAnd () [inline]
Referenced by copy().
indri::lang::ExtentAnd::ExtentAnd (const std::vector< RawExtentNode * > & children) [inline]
indri::lang::ExtentAnd::ExtentAnd (Unpacker & unpacker) [inline]
References _children, and indri::lang::Unpacker::getRawExtentVector().
Member Function Documentation
void indri::lang::ExtentAnd::addChild (RawExtentNode * node) [inline]
References _children.
Referenced by copy(), and QueryParser::field_list().
Node* indri::lang::ExtentAnd::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _children, addChild(), indri::lang::Copier::after(), indri::lang::Copier::before(), ExtentAnd(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
std::vector<RawExtentNode*>& indri::lang::ExtentAnd::getChildren () [inline]
References _children.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before().
UINT64 indri::lang::ExtentAnd::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _children.
bool indri::lang::ExtentAnd::operator== (Node & node) [inline]
References _children, and unordered_equal().
void indri::lang::ExtentAnd::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ExtentAnd::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _children.
std::string indri::lang::ExtentAnd::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ExtentAnd::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::UnnecessaryNodeRemoverCopier::after().
Member Data Documentation
std::vector<RawExtentNode*> indri::lang::ExtentAnd::_children [private]
Referenced by addChild(), copy(), ExtentAnd(), getChildren(), hashCode(), operator==(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp