Indri: indri::query::RelevanceModel Class Reference
indri::query::RelevanceModel Class Reference
#include <RelevanceModel.hpp>
Classes
struct Gram
struct GramCounts
Public Member Functions
RelevanceModel (indri::api::QueryEnvironment &environment, const std::string &smoothing, int maxGrams, int documents)
~RelevanceModel ()
void generate (const std::string &query)
void generate (const std::string &query, const std::vector< indri::api::ScoredExtentResult > &results)
const std::vector
< indri::api::ScoredExtentResult > & getQueryResults () const
const std::vector< Gram * > & getGrams () const
Private Types
typedef
indri::utility::HashTable
< Gram *, GramCounts
*, Gram::hash,
Gram::string_comparator > HGram
Private Member Functions
void _countGrams ()
void _scoreGrams ()
void _sortGrams ()
void _extractDocuments ()
Private Attributes
indri::api::QueryEnvironment & _environment
int _maxGrams
std::string _smoothing
int _documents
HGram _gramTable
std::vector
< indri::api::ScoredExtentResult > _results
std::vector< lemur::api::DOCID_T > _documentIDs
std::vector< Gram * > _grams
std::vector
< indri::api::DocumentVector * > _vectors
Member Typedef Documentation
typedef indri::utility::HashTable< Gram*, GramCounts*, Gram::hash, Gram::string_comparator > indri::query::RelevanceModel::HGram [private]
Constructor & Destructor Documentation
indri::query::RelevanceModel::RelevanceModel (indri::api::QueryEnvironment & environment, const std::string & smoothing, int maxGrams, int documents)
indri::query::RelevanceModel::~RelevanceModel ()
References _gramTable, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Member Function Documentation
void indri::query::RelevanceModel::_countGrams () [private]
References _gramTable, _maxGrams, _results, _vectors, indri::utility::greedy_vector< _Type, _Count >::back(), indri::api::ScoredExtentResult::begin, indri::query::RelevanceModel::GramCounts::counts, indri::api::ScoredExtentResult::end, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::query::RelevanceModel::GramCounts::gram, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), isValidWord(), indri::api::DocumentVector::positions(), indri::api::DocumentVector::stems(), and indri::query::RelevanceModel::Gram::terms.
Referenced by generate().
void indri::query::RelevanceModel::_extractDocuments () [private]
References _documentIDs, and _results.
Referenced by generate().
void indri::query::RelevanceModel::_scoreGrams () [private]
References _environment, _gramTable, _results, _smoothing, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::query::RelevanceModel::GramCounts::counts, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::api::QueryEnvironment::expressionCount(), indri::query::TermScoreFunctionFactory::get(), indri::query::TermScoreFunction::scoreOccurrence(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::QueryEnvironment::stemCount(), indri::api::QueryEnvironment::termCount(), indri::query::RelevanceModel::Gram::terms, and indri::query::RelevanceModel::Gram::weight.
Referenced by generate().
void indri::query::RelevanceModel::_sortGrams () [private]
References _grams, _gramTable, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Referenced by generate().
void indri::query::RelevanceModel::generate (const std::string & query, const std::vector< indri::api::ScoredExtentResult > & results)
References _countGrams(), _documentIDs, _environment, _extractDocuments(), _grams, _logtoposterior(), _results, _scoreGrams(), _sortGrams(), _vectors, and indri::api::QueryEnvironment::documentVectors().
void indri::query::RelevanceModel::generate (const std::string & query)
References _countGrams(), _documentIDs, _documents, _environment, _extractDocuments(), _grams, _logtoposterior(), _results, _scoreGrams(), _sortGrams(), _vectors, indri::api::QueryEnvironment::documentVectors(), and indri::api::QueryEnvironment::runQuery().
Referenced by indri::query::RMExpander::expand(), and main().
const std::vector< indri::query::RelevanceModel::Gram * > & indri::query::RelevanceModel::getGrams () const
References _grams.
Referenced by indri::query::RMExpander::expand(), and main().
const std::vector< indri::api::ScoredExtentResult > & indri::query::RelevanceModel::getQueryResults () const
References _results.
Member Data Documentation
std::vector<lemur::api::DOCID_T> indri::query::RelevanceModel::_documentIDs [private]
Referenced by _extractDocuments(), and generate().
int indri::query::RelevanceModel::_documents [private]
Referenced by generate().
indri::api::QueryEnvironment& indri::query::RelevanceModel::_environment [private]
Referenced by _scoreGrams(), and generate().
std::vector<Gram*> indri::query::RelevanceModel::_grams [private]
Referenced by _sortGrams(), generate(), and getGrams().
HGram indri::query::RelevanceModel::_gramTable [private]
Referenced by _countGrams(), _scoreGrams(), _sortGrams(), and ~RelevanceModel().
int indri::query::RelevanceModel::_maxGrams [private]
Referenced by _countGrams().
std::vector<indri::api::ScoredExtentResult> indri::query::RelevanceModel::_results [private]
Referenced by _countGrams(), _extractDocuments(), _scoreGrams(), generate(), and getQueryResults().
std::string indri::query::RelevanceModel::_smoothing [private]
Referenced by _scoreGrams().
std::vector<indri::api::DocumentVector*> indri::query::RelevanceModel::_vectors [private]
Referenced by _countGrams(), and generate().
The documentation for this class was generated from the following files:
RelevanceModel.hpp
RelevanceModel.cpp