Indri: indri::lang::FieldLessNode Class Reference
indri::lang::FieldLessNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FieldLessNode (RawExtentNode *field, INT64 constant)
FieldLessNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
INT64 getConstant () const
RawExtentNode * getField ()
bool operator== (Node &node)
Node * copy (Copier &copier)
void walk (Walker &walker)
void pack (Packer &packer)
Private Attributes
RawExtentNode * _field
INT64 _constant
Constructor & Destructor Documentation
indri::lang::FieldLessNode::FieldLessNode (RawExtentNode * field, INT64 constant) [inline]
Referenced by copy().
indri::lang::FieldLessNode::FieldLessNode (Unpacker & unpacker) [inline]
References _constant, _field, indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getRawExtentNode().
Member Function Documentation
Node* indri::lang::FieldLessNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _constant, _field, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and FieldLessNode().
INT64 indri::lang::FieldLessNode::getConstant () const [inline]
References _constant.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
RawExtentNode* indri::lang::FieldLessNode::getField () [inline]
References _field.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
UINT64 indri::lang::FieldLessNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _constant, _field, and indri::lang::Node::hashCode().
bool indri::lang::FieldLessNode::operator== (Node & node) [inline]
References _constant, _field, getConstant(), and getField().
void indri::lang::FieldLessNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _constant, _field, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::FieldLessNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _constant, _field, and indri::lang::Node::queryText().
std::string indri::lang::FieldLessNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FieldLessNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _field, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
INT64 indri::lang::FieldLessNode::_constant [private]
Referenced by copy(), FieldLessNode(), getConstant(), hashCode(), operator==(), pack(), and queryText().
RawExtentNode* indri::lang::FieldLessNode::_field [private]
Referenced by copy(), FieldLessNode(), getField(), hashCode(), operator==(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp