Indri: indri::query::PonteExpander Class Reference
indri::query::PonteExpander Class Reference
#include <PonteExpander.hpp>
Public Member Functions
PonteExpander (indri::api::QueryEnvironment *env, indri::api::Parameters &param)
virtual std::string expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > &results)
Constructor & Destructor Documentation
indri::query::PonteExpander::PonteExpander (indri::api::QueryEnvironment * env, indri::api::Parameters & param)
Member Function Documentation
std::string indri::query::PonteExpander::expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > & results) [virtual]
Implements indri::query::QueryExpander.
References indri::query::QueryExpander::_env, indri::query::QueryExpander::_param, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::query::QueryExpander::buildQuery(), PonteTerm::collection, indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::Parameters::get(), indri::query::QueryExpander::getCF(), indri::query::QueryExpander::getDocumentVectors(), indri::query::QueryExpander::getVocabulary(), indri::api::DocumentVector::positions(), PonteTerm::relevance, indri::query::DirichletTermScoreFunction::scoreOccurrence(), indri::utility::greedy_vector< _Type, _Count >::size(), PonteTerm::stem, indri::api::DocumentVector::stems(), and indri::api::QueryEnvironment::termCount().
The documentation for this class was generated from the following files:
PonteExpander.hpp
PonteExpander.cpp