Indri: indri::thread::ScopedMonitor Class Reference
indri::thread::ScopedMonitor Class Reference
#include <ScopedMonitor.hpp>
Public Member Functions
ScopedMonitor (Mutex &mutex, ConditionVariable &condition)
~ScopedMonitor ()
void wait ()
void notifyOne ()
void notifyAll ()
Private Attributes
Mutex & _mutex
ConditionVariable & _condition
Constructor & Destructor Documentation
indri::thread::ScopedMonitor::ScopedMonitor (Mutex & mutex, ConditionVariable & condition) [inline]
References _mutex, and indri::thread::Mutex::lock().
indri::thread::ScopedMonitor::~ScopedMonitor () [inline]
References _mutex, and indri::thread::Mutex::unlock().
Member Function Documentation
void indri::thread::ScopedMonitor::notifyAll () [inline]
References _condition, and indri::thread::ConditionVariable::notifyAll().
void indri::thread::ScopedMonitor::notifyOne () [inline]
References _condition, and indri::thread::ConditionVariable::notifyOne().
void indri::thread::ScopedMonitor::wait () [inline]
References _condition, _mutex, and indri::thread::ConditionVariable::wait().
Member Data Documentation
ConditionVariable& indri::thread::ScopedMonitor::_condition [private]
Referenced by notifyAll(), notifyOne(), and wait().
Mutex& indri::thread::ScopedMonitor::_mutex [private]
Referenced by ScopedMonitor(), wait(), and ~ScopedMonitor().
The documentation for this class was generated from the following file:
ScopedMonitor.hpp