Indri: Indri::MetadataPairSTDVector Class Reference
Indri::MetadataPairSTDVector Class Reference
Classes
class MetadataPairSTDVectorEnumerator
Public Member Functions
virtual void Dispose ()
MetadataPairSTDVector (System.Collections.ICollection c)
void CopyTo (MetadataPair[] array)
void CopyTo (MetadataPair[] array, int arrayIndex)
void CopyTo (int index, MetadataPair[] array, int arrayIndex, int count)
MetadataPairSTDVectorEnumerator GetEnumerator ()
void Clear ()
void Add (MetadataPair x)
MetadataPairSTDVector ()
MetadataPairSTDVector (MetadataPairSTDVector other)
MetadataPairSTDVector (int capacity)
void AddRange (MetadataPairSTDVector values)
MetadataPairSTDVector GetRange (int index, int count)
void Insert (int index, MetadataPair x)
void InsertRange (int index, MetadataPairSTDVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, MetadataPairSTDVector values)
Static Public Member Functions
static MetadataPairSTDVector Repeat (MetadataPair value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
MetadataPair this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal MetadataPairSTDVector (IntPtr cPtr, bool cMemoryOwn)
~MetadataPairSTDVector ()
System.Collections.Generic.IEnumerator
< MetadataPair >
System.Collections.Generic.IEnumerable
< MetadataPair >. GetEnumerator ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
MetadataPair getitemcopy (int index)
MetadataPair getitem (int index)
void setitem (int index, MetadataPair val)
Static Private Member Functions
static internal HandleRef getCPtr (MetadataPairSTDVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::MetadataPairSTDVector::MetadataPairSTDVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::MetadataPairSTDVector::~MetadataPairSTDVector () [inline, private]
References Dispose().
Indri::MetadataPairSTDVector::MetadataPairSTDVector (System.Collections.ICollection c) [inline]
References Add().
Indri::MetadataPairSTDVector::MetadataPairSTDVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::MetadataPairSTDVector::MetadataPairSTDVector (MetadataPairSTDVector other) [inline]
Indri::MetadataPairSTDVector::MetadataPairSTDVector (int capacity) [inline]
Member Function Documentation
void Indri::MetadataPairSTDVector::Add (MetadataPair x) [inline]
References swigCPtr.
Referenced by MetadataPairSTDVector().
void Indri::MetadataPairSTDVector::AddRange (MetadataPairSTDVector values) [inline]
References swigCPtr.
uint Indri::MetadataPairSTDVector::capacity () [inline, private]
References swigCPtr.
void Indri::MetadataPairSTDVector::Clear () [inline]
References swigCPtr.
void Indri::MetadataPairSTDVector::CopyTo (int index, MetadataPair[] array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::MetadataPairSTDVector::CopyTo (MetadataPair[] array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::MetadataPairSTDVector::CopyTo (MetadataPair[] array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::MetadataPairSTDVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~MetadataPairSTDVector().
static internal HandleRef Indri::MetadataPairSTDVector::getCPtr (MetadataPairSTDVector obj) [inline, static, private]
References swigCPtr.
MetadataPairSTDVectorEnumerator Indri::MetadataPairSTDVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::MetadataPairSTDVector::GetEnumerator () [inline, private]
System.Collections.Generic.IEnumerator<MetadataPair> System.Collections.Generic.IEnumerable<MetadataPair>. Indri::MetadataPairSTDVector::GetEnumerator () [inline, private]
MetadataPair Indri::MetadataPairSTDVector::getitem (int index) [inline, private]
References swigCPtr.
MetadataPair Indri::MetadataPairSTDVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
MetadataPairSTDVector Indri::MetadataPairSTDVector::GetRange (int index, int count) [inline]
References MetadataPairSTDVector(), and swigCPtr.
void Indri::MetadataPairSTDVector::Insert (int index, MetadataPair x) [inline]
References swigCPtr.
void Indri::MetadataPairSTDVector::InsertRange (int index, MetadataPairSTDVector values) [inline]
References swigCPtr.
void Indri::MetadataPairSTDVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::MetadataPairSTDVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static MetadataPairSTDVector Indri::MetadataPairSTDVector::Repeat (MetadataPair value, int count) [inline, static]
References MetadataPairSTDVector().
void Indri::MetadataPairSTDVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::MetadataPairSTDVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::MetadataPairSTDVector::Reverse () [inline]
References swigCPtr.
void Indri::MetadataPairSTDVector::setitem (int index, MetadataPair val) [inline, private]
References swigCPtr.
void Indri::MetadataPairSTDVector::SetRange (int index, MetadataPairSTDVector values) [inline]
References swigCPtr.
uint Indri::MetadataPairSTDVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::MetadataPairSTDVector::MetadataPairSTDVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::MetadataPairSTDVector::swigCMemOwn [protected]
Referenced by Dispose(), and MetadataPairSTDVector().
HandleRef Indri::MetadataPairSTDVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), MetadataPairSTDVector(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::MetadataPairSTDVector::Capacity [get, set]
int Indri::MetadataPairSTDVector::Count [get]
Referenced by CopyTo(), Indri::MetadataPairSTDVector::MetadataPairSTDVectorEnumerator::MetadataPairSTDVectorEnumerator(), Indri::MetadataPairSTDVector::MetadataPairSTDVectorEnumerator::MoveNext(), and Indri::MetadataPairSTDVector::MetadataPairSTDVectorEnumerator::Reset().
bool Indri::MetadataPairSTDVector::IsFixedSize [get]
bool Indri::MetadataPairSTDVector::IsReadOnly [get]
bool Indri::MetadataPairSTDVector::IsSynchronized [get]
MetadataPair Indri::MetadataPairSTDVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
MetadataPairSTDVector.cs