Indri: indri::lang::UnnecessaryNodeRemoverCopier Class Reference
indri::lang::UnnecessaryNodeRemoverCopier Class Reference
#include <UnnecessaryNodeRemoverCopier.hpp>
Classes
class SingleChildWalker
Public Member Functions
~UnnecessaryNodeRemoverCopier ()
indri::lang::Node * defaultAfter (indri::lang::Node *old, indri::lang::Node *newNode)
indri::lang::Node * after (indri::lang::ExtentAnd *oldAnd, indri::lang::ExtentAnd *newAnd)
indri::lang::Node * after (indri::lang::ExtentOr *oldOr, indri::lang::ExtentOr *newOr)
indri::lang::Node * after (indri::lang::ODNode *oldOD, indri::lang::ODNode *newOD)
indri::lang::Node * after (indri::lang::UWNode *oldUW, indri::lang::UWNode *newUW)
indri::lang::Node * after (indri::lang::LengthPrior *oldLP, indri::lang::LengthPrior *newLP)
Protected Attributes
std::vector< indri::lang::Node * > _nodes
Constructor & Destructor Documentation
indri::lang::UnnecessaryNodeRemoverCopier::~UnnecessaryNodeRemoverCopier () [inline]
References _nodes, and indri::utility::delete_vector_contents().
Member Function Documentation
indri::lang::Node* indri::lang::UnnecessaryNodeRemoverCopier::after (indri::lang::LengthPrior * oldLP, indri::lang::LengthPrior * newLP) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, indri::lang::LengthPrior::getChild(), and indri::lang::LengthPrior::getExponent().
indri::lang::Node* indri::lang::UnnecessaryNodeRemoverCopier::after (indri::lang::UWNode * oldUW, indri::lang::UWNode * newUW) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::getChild(), indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::onlyOneChild(), and indri::lang::UWNode::walk().
indri::lang::Node* indri::lang::UnnecessaryNodeRemoverCopier::after (indri::lang::ODNode * oldOD, indri::lang::ODNode * newOD) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::getChild(), indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::onlyOneChild(), and indri::lang::ODNode::walk().
indri::lang::Node* indri::lang::UnnecessaryNodeRemoverCopier::after (indri::lang::ExtentOr * oldOr, indri::lang::ExtentOr * newOr) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::getChild(), indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::onlyOneChild(), and indri::lang::ExtentOr::walk().
indri::lang::Node* indri::lang::UnnecessaryNodeRemoverCopier::after (indri::lang::ExtentAnd * oldAnd, indri::lang::ExtentAnd * newAnd) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::getChild(), indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker::onlyOneChild(), and indri::lang::ExtentAnd::walk().
indri::lang::Node* indri::lang::UnnecessaryNodeRemoverCopier::defaultAfter (indri::lang::Node * old, indri::lang::Node * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes.
Member Data Documentation
std::vector<indri::lang::Node*> indri::lang::UnnecessaryNodeRemoverCopier::_nodes [protected]
Referenced by after(), defaultAfter(), and ~UnnecessaryNodeRemoverCopier().
The documentation for this class was generated from the following file:
UnnecessaryNodeRemoverCopier.hpp