Indri: indri::lang::RawScorerNode Class Reference
indri::lang::RawScorerNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
RawScorerNode (RawExtentNode *raw, RawExtentNode *context, std::string smoothing="method:dirichlet,mu:2500")
RawScorerNode (Unpacker &unpacker)
virtual std::string typeName () const
std::string queryText () const
virtual UINT64 hashCode () const
double getOccurrences () const
double getContextSize () const
int getDocumentOccurrences () const
int getDocumentCount () const
const std::string & getSmoothing () const
void setStatistics (double occurrences, double contextSize, int documentOccurrences, int documentCount)
void setContext (RawExtentNode *context)
void setRawExtent (RawExtentNode *rawExtent)
void setSmoothing (const std::string &smoothing)
RawExtentNode * getContext ()
RawExtentNode * getRawExtent ()
void pack (Packer &packer)
void walk (Walker &walker)
virtual Node * copy (Copier &copier)
Protected Attributes
double _occurrences
double _contextSize
double _maximumContextFraction
int _documentOccurrences
int _documentCount
RawExtentNode * _raw
RawExtentNode * _context
std::string _smoothing
Constructor & Destructor Documentation
indri::lang::RawScorerNode::RawScorerNode (RawExtentNode * raw, RawExtentNode * context, std::string smoothing = "method:dirichlet,mu:2500") [inline]
References _context, _contextSize, _documentCount, _documentOccurrences, _occurrences, _raw, and _smoothing.
Referenced by copy().
indri::lang::RawScorerNode::RawScorerNode (Unpacker & unpacker) [inline]
References _context, _contextSize, _documentCount, _documentOccurrences, _occurrences, _raw, _smoothing, indri::lang::Unpacker::getDouble(), indri::lang::Unpacker::getInteger(), indri::lang::Unpacker::getRawExtentNode(), and indri::lang::Unpacker::getString().
Member Function Documentation
virtual Node* indri::lang::RawScorerNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::NestedRawScorerNode, and indri::lang::ShrinkageScorerNode.
References _context, _raw, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and RawScorerNode().
RawExtentNode* indri::lang::RawScorerNode::getContext () [inline]
References _context.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::api::QueryEnvironment::_expCount(), indri::lang::SmoothingAnnotatorWalker::after(), indri::infnet::InferenceNetworkBuilder::after(), indri::lang::FrequencyListCopier::after(), indri::lang::ExtentRestrictionModelAnnotatorCopier::after(), indri::lang::NoContextCountGraphCopier::after(), and indri::lang::ContextCountGraphCopier::after().
double indri::lang::RawScorerNode::getContextSize () const [inline]
References _contextSize.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::FrequencyListCopier::after().
int indri::lang::RawScorerNode::getDocumentCount () const [inline]
References _documentCount.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::FrequencyListCopier::after().
int indri::lang::RawScorerNode::getDocumentOccurrences () const [inline]
References _documentOccurrences.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::FrequencyListCopier::after().
double indri::lang::RawScorerNode::getOccurrences () const [inline]
References _occurrences.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::FrequencyListCopier::after().
RawExtentNode* indri::lang::RawScorerNode::getRawExtent () [inline]
References _raw.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::api::QueryEnvironment::_expCount(), indri::lang::SmoothingAnnotatorWalker::after(), indri::infnet::InferenceNetworkBuilder::after(), indri::lang::FrequencyListCopier::after(), indri::lang::NoContextCountGraphCopier::after(), indri::lang::ContextCountGraphCopier::after(), and indri::api::QueryEnvironment::expressionList().
const std::string& indri::lang::RawScorerNode::getSmoothing () const [inline]
References _smoothing.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::lang::QueryTFWalker::after(), indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::FrequencyListCopier::after().
virtual UINT64 indri::lang::RawScorerNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::NestedRawScorerNode, and indri::lang::ShrinkageScorerNode.
References _context, _raw, _smoothing, and indri::lang::Node::hashCode().
void indri::lang::RawScorerNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::ShrinkageScorerNode.
References _context, _contextSize, _documentCount, _documentOccurrences, _occurrences, _raw, _smoothing, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::RawScorerNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::ShrinkageScorerNode.
References _context, _raw, and indri::lang::Node::queryText().
Referenced by indri::lang::QueryTFWalker::after().
void indri::lang::RawScorerNode::setContext (RawExtentNode * context) [inline]
References _context.
Referenced by indri::lang::ExtentRestrictionModelAnnotatorCopier::after().
void indri::lang::RawScorerNode::setRawExtent (RawExtentNode * rawExtent) [inline]
References _raw.
void indri::lang::RawScorerNode::setSmoothing (const std::string & smoothing) [inline]
References _smoothing.
Referenced by indri::lang::SmoothingAnnotatorWalker::after(), and indri::lang::QueryTFWalker::after().
void indri::lang::RawScorerNode::setStatistics (double occurrences, double contextSize, int documentOccurrences, int documentCount) [inline]
References _contextSize, _documentCount, _documentOccurrences, and _occurrences.
virtual std::string indri::lang::RawScorerNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
Reimplemented in indri::lang::NestedRawScorerNode, and indri::lang::ShrinkageScorerNode.
void indri::lang::RawScorerNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::ShrinkageScorerNode.
References _context, _raw, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
RawExtentNode* indri::lang::RawScorerNode::_context [protected]
Referenced by indri::lang::NestedRawScorerNode::copy(), copy(), getContext(), indri::lang::ShrinkageScorerNode::hashCode(), indri::lang::NestedRawScorerNode::hashCode(), hashCode(), pack(), queryText(), RawScorerNode(), setContext(), and walk().
double indri::lang::RawScorerNode::_contextSize [protected]
Referenced by getContextSize(), indri::lang::ShrinkageScorerNode::pack(), pack(), RawScorerNode(), setStatistics(), and indri::lang::ShrinkageScorerNode::ShrinkageScorerNode().
int indri::lang::RawScorerNode::_documentCount [protected]
Referenced by getDocumentCount(), pack(), RawScorerNode(), and setStatistics().
int indri::lang::RawScorerNode::_documentOccurrences [protected]
Referenced by getDocumentOccurrences(), pack(), RawScorerNode(), and setStatistics().
double indri::lang::RawScorerNode::_maximumContextFraction [protected]
double indri::lang::RawScorerNode::_occurrences [protected]
Referenced by getOccurrences(), indri::lang::ShrinkageScorerNode::pack(), pack(), RawScorerNode(), setStatistics(), and indri::lang::ShrinkageScorerNode::ShrinkageScorerNode().
RawExtentNode* indri::lang::RawScorerNode::_raw [protected]
Referenced by indri::lang::ShrinkageScorerNode::copy(), indri::lang::NestedRawScorerNode::copy(), copy(), getRawExtent(), indri::lang::ShrinkageScorerNode::hashCode(), indri::lang::NestedRawScorerNode::hashCode(), hashCode(), indri::lang::ShrinkageScorerNode::pack(), pack(), indri::lang::ShrinkageScorerNode::queryText(), queryText(), RawScorerNode(), setRawExtent(), indri::lang::ShrinkageScorerNode::ShrinkageScorerNode(), indri::lang::ShrinkageScorerNode::walk(), and walk().
std::string indri::lang::RawScorerNode::_smoothing [protected]
Referenced by getSmoothing(), indri::lang::ShrinkageScorerNode::hashCode(), indri::lang::NestedRawScorerNode::hashCode(), hashCode(), indri::lang::ShrinkageScorerNode::pack(), pack(), RawScorerNode(), setSmoothing(), and indri::lang::ShrinkageScorerNode::ShrinkageScorerNode().
The documentation for this class was generated from the following file:
QuerySpec.hpp