Indri: indri::parse::StopperTransformation Class Reference
indri::parse::StopperTransformation Class Reference
#include <StopperTransformation.hpp>
Classes
struct eqstr
Public Member Functions
StopperTransformation ()
StopperTransformation (const std::vector< std::string > &stopwords)
StopperTransformation (const std::vector< const char * > &stopwords)
StopperTransformation (const std::vector< char * > &stopwords)
StopperTransformation (indri::api::Parameters &stopwords)
~StopperTransformation ()
void read (const std::vector< std::string > &stopwords)
void read (const std::vector< const char * > &stopwords)
void read (const std::vector< char * > &stopwords)
void read (const std::string &filename)
void read (indri::api::Parameters &stopwords)
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void handle (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
Private Types
typedef hash_set< char *, hash
< char * >, eqstr > dictTable
Private Attributes
ObjectHandler
< indri::api::ParsedDocument > * _handler
dictTable _table
Member Typedef Documentation
typedef hash_set<char *, hash<char *>, eqstr> indri::parse::StopperTransformation::dictTable [private]
Constructor & Destructor Documentation
indri::parse::StopperTransformation::StopperTransformation ()
indri::parse::StopperTransformation::StopperTransformation (const std::vector< std::string > & stopwords)
References read().
indri::parse::StopperTransformation::StopperTransformation (const std::vector< const char * > & stopwords)
References read().
indri::parse::StopperTransformation::StopperTransformation (const std::vector< char * > & stopwords)
References read().
indri::parse::StopperTransformation::StopperTransformation (indri::api::Parameters & stopwords)
References read().
indri::parse::StopperTransformation::~StopperTransformation ()
Member Function Documentation
void indri::parse::StopperTransformation::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::StopperTransformation::read (indri::api::Parameters & stopwords)
References _table, and indri::api::Parameters::size().
void indri::parse::StopperTransformation::read (const std::string & filename)
References _table.
void indri::parse::StopperTransformation::read (const std::vector< char * > & stopwords)
References _table.
void indri::parse::StopperTransformation::read (const std::vector< const char * > & stopwords)
References _table.
void indri::parse::StopperTransformation::read (const std::vector< std::string > & stopwords)
References _table.
Referenced by StopperTransformation().
void indri::parse::StopperTransformation::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::StopperTransformation::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _table, indri::utility::greedy_vector< _Type, _Count >::size(), and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
ObjectHandler<indri::api::ParsedDocument>* indri::parse::StopperTransformation::_handler [private]
Referenced by handle(), and setHandler().
dictTable indri::parse::StopperTransformation::_table [private]
Referenced by read(), and transform().
The documentation for this class was generated from the following files:
StopperTransformation.hpp
StopperTransformation.cpp