Indri: indri::infnet::FieldWildcardNode Class Reference
indri::infnet::FieldWildcardNode Class Reference
#include <FieldWildcardNode.hpp>
Public Member Functions
FieldWildcardNode (const std::string &name)
~FieldWildcardNode ()
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
void indexChanged (indri::index::Index &index)
Private Attributes
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
indri::index::Index * _index
lemur::api::DOCID_T _nextDocument
indri::index::TermListFileIterator * _docIter
int _docIterID
Constructor & Destructor Documentation
indri::infnet::FieldWildcardNode::FieldWildcardNode (const std::string & name)
indri::infnet::FieldWildcardNode::~FieldWildcardNode ()
References _docIter.
Member Function Documentation
void indri::infnet::FieldWildcardNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, and indri::infnet::Annotator::addMatches().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::FieldWildcardNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::FieldWildcardNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::FieldWildcardNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _docIter, _docIterID, _index, _nextDocument, indri::index::TermListFileIterator::startIteration(), and indri::index::Index::termListFileIterator().
lemur::api::DOCID_T indri::infnet::FieldWildcardNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _nextDocument.
void indri::infnet::FieldWildcardNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _docIter, _docIterID, _extents, _index, _nextDocument, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::TermListFileIterator::currentEntry(), indri::index::Index::documentMaximum(), indri::index::Extent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::TermList::fields(), indri::infnet::ListIteratorNode::initpointer(), indri::index::TermListFileIterator::nextEntry(), and indri::utility::greedy_vector< _Type, _Count >::push_back().
Member Data Documentation
indri::index::TermListFileIterator* indri::infnet::FieldWildcardNode::_docIter [private]
Referenced by indexChanged(), prepare(), and ~FieldWildcardNode().
int indri::infnet::FieldWildcardNode::_docIterID [private]
Referenced by indexChanged(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::FieldWildcardNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
indri::index::Index* indri::infnet::FieldWildcardNode::_index [private]
Referenced by indexChanged(), and prepare().
std::string indri::infnet::FieldWildcardNode::_name [private]
Referenced by getName().
lemur::api::DOCID_T indri::infnet::FieldWildcardNode::_nextDocument [private]
Referenced by indexChanged(), nextCandidateDocument(), and prepare().
The documentation for this class was generated from the following files:
FieldWildcardNode.hpp
FieldWildcardNode.cpp