Indri: indri::infnet::ListIteratorNode Class Reference
indri::infnet::ListIteratorNode Class Reference
#include <ListIteratorNode.hpp>
Public Member Functions
void initpointer ()
initializes the last position pointer for matching child siblings
void sortparent (indri::utility::greedy_vector< indri::index::Extent > &extents)
sorts the extents by the parent IDs (if available)
void sortbegin (indri::utility::greedy_vector< indri::index::Extent > &extents)
sorts the extents by the beginning extent position (if available)
virtual void prepare (lemur::api::DOCID_T documentID)=0
sets up as much as we can with just the document ID
virtual const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()=0
returns a list of intervals describing positions of children
virtual void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)=0
annotate any results from this node from position begin to position end
virtual const
indri::utility::greedy_vector
< indri::index::Extent > & matches (indri::index::Extent &extent)
Protected Attributes
indri::utility::greedy_vector
< indri::index::Extent > _matches
int _lastpos
indri::index::Extent _lastExtent
Member Function Documentation
virtual void indri::infnet::ListIteratorNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [pure virtual]
annotate any results from this node from position begin to position end
Implemented in indri::infnet::BooleanAndNode, indri::infnet::DocListIteratorNode, indri::infnet::ExtentAndNode, indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, indri::infnet::ExtentInsideNode, indri::infnet::ExtentOrNode, indri::infnet::ExtentParentNode, indri::infnet::FieldBetweenNode, indri::infnet::FieldEqualsNode, indri::infnet::FieldGreaterNode, indri::infnet::FieldIteratorNode, indri::infnet::FieldLessNode, indri::infnet::FieldWildcardNode, indri::infnet::NestedExtentInsideNode, indri::infnet::NullListNode, indri::infnet::OrderedWindowNode, indri::infnet::UnorderedWindowNode, and indri::infnet::WeightedExtentOrNode.
Referenced by indri::infnet::ShrinkageBeliefNode::annotate(), indri::infnet::NestedListBeliefNode::annotate(), indri::infnet::NestedExtentInsideNode::annotate(), indri::infnet::ListBeliefNode::annotate(), indri::infnet::FilterRequireNode::annotate(), indri::infnet::FilterRejectNode::annotate(), indri::infnet::ExtentParentNode::annotate(), indri::infnet::ExtentInsideNode::annotate(), indri::infnet::ExtentDescendantNode::annotate(), and indri::infnet::ExtentChildNode::annotate().
virtual const indri::utility::greedy_vector<indri::index::Extent>& indri::infnet::ListIteratorNode::extents () [pure virtual]
returns a list of intervals describing positions of children
Implemented in indri::infnet::BooleanAndNode, indri::infnet::DocListIteratorNode, indri::infnet::ExtentAndNode, indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, indri::infnet::ExtentInsideNode, indri::infnet::ExtentOrNode, indri::infnet::ExtentParentNode, indri::infnet::FieldBetweenNode, indri::infnet::FieldEqualsNode, indri::infnet::FieldGreaterNode, indri::infnet::FieldIteratorNode, indri::infnet::FieldLessNode, indri::infnet::FieldWildcardNode, indri::infnet::NestedExtentInsideNode, indri::infnet::NullListNode, indri::infnet::OrderedWindowNode, indri::infnet::UnorderedWindowNode, and indri::infnet::WeightedExtentOrNode.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::infnet::NestedListBeliefNode::_contextLength(), indri::infnet::ListBeliefNode::_contextLength(), indri::infnet::NestedListBeliefNode::_contextOccurrences(), indri::infnet::ListBeliefNode::_contextOccurrences(), indri::infnet::NestedListBeliefNode::_documentOccurrences(), indri::infnet::ListBeliefNode::_documentOccurrences(), indri::infnet::ShrinkageBeliefNode::annotate(), indri::infnet::NestedListBeliefNode::annotate(), indri::infnet::ListBeliefNode::annotate(), indri::infnet::FilterRequireNode::annotate(), indri::infnet::FilterRejectNode::annotate(), indri::infnet::ListAccumulator::evaluate(), indri::infnet::ContextCountAccumulator::evaluate(), indri::infnet::ShrinkageBeliefNode::hasMatch(), indri::infnet::NestedListBeliefNode::hasMatch(), indri::infnet::ListBeliefNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), matches(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), indri::infnet::FilterRequireNode::score(), indri::infnet::FilterRejectNode::score(), and indri::infnet::UWNodeChildLess().
void indri::infnet::ListIteratorNode::initpointer () [inline]
initializes the last position pointer for matching child siblings
References _lastpos.
Referenced by indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::OrderedWindowNode::prepare(), indri::infnet::NullListNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::FieldWildcardNode::prepare(), indri::infnet::FieldLessNode::prepare(), indri::infnet::FieldIteratorNode::prepare(), indri::infnet::FieldGreaterNode::prepare(), indri::infnet::FieldEqualsNode::prepare(), indri::infnet::FieldBetweenNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentOrNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), indri::infnet::ExtentAndNode::prepare(), indri::infnet::DocListIteratorNode::prepare(), and indri::infnet::BooleanAndNode::prepare().
virtual const indri::utility::greedy_vector<indri::index::Extent>& indri::infnet::ListIteratorNode::matches (indri::index::Extent & extent) [inline, virtual]
Reimplemented in indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, and indri::infnet::ExtentParentNode.
References _lastpos, _matches, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Extent::end, extents(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), indri::infnet::ExtentRestrictionNode::hasMatch(), indri::infnet::ExtentEnforcementNode::hasMatch(), indri::infnet::ExtentRestrictionNode::score(), and indri::infnet::ExtentEnforcementNode::score().
virtual void indri::infnet::ListIteratorNode::prepare (lemur::api::DOCID_T documentID) [pure virtual]
sets up as much as we can with just the document ID
Implemented in indri::infnet::BooleanAndNode, indri::infnet::DocListIteratorNode, indri::infnet::ExtentAndNode, indri::infnet::ExtentChildNode, indri::infnet::ExtentDescendantNode, indri::infnet::ExtentInsideNode, indri::infnet::ExtentOrNode, indri::infnet::ExtentParentNode, indri::infnet::FieldBetweenNode, indri::infnet::FieldEqualsNode, indri::infnet::FieldGreaterNode, indri::infnet::FieldIteratorNode, indri::infnet::FieldLessNode, indri::infnet::FieldWildcardNode, indri::infnet::NestedExtentInsideNode, indri::infnet::NullListNode, indri::infnet::OrderedWindowNode, indri::infnet::UnorderedWindowNode, and indri::infnet::WeightedExtentOrNode.
void indri::infnet::ListIteratorNode::sortbegin (indri::utility::greedy_vector< indri::index::Extent > & extents) [inline]
sorts the extents by the beginning extent position (if available)
References indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::ListIteratorNode::sortparent (indri::utility::greedy_vector< indri::index::Extent > & extents) [inline]
sorts the extents by the parent IDs (if available)
References indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::infnet::ExtentChildNode::prepare().
Member Data Documentation
indri::index::Extent indri::infnet::ListIteratorNode::_lastExtent [protected]
Referenced by indri::infnet::WeightedExtentOrNode::annotate(), indri::infnet::UnorderedWindowNode::annotate(), indri::infnet::OrderedWindowNode::annotate(), indri::infnet::NestedExtentInsideNode::annotate(), indri::infnet::ExtentParentNode::annotate(), indri::infnet::ExtentOrNode::annotate(), indri::infnet::ExtentInsideNode::annotate(), indri::infnet::ExtentDescendantNode::annotate(), indri::infnet::ExtentChildNode::annotate(), indri::infnet::DocListIteratorNode::annotate(), indri::infnet::WeightedExtentOrNode::indexChanged(), indri::infnet::UnorderedWindowNode::indexChanged(), indri::infnet::OrderedWindowNode::indexChanged(), indri::infnet::NestedExtentInsideNode::indexChanged(), indri::infnet::ExtentParentNode::indexChanged(), indri::infnet::ExtentOrNode::indexChanged(), indri::infnet::ExtentInsideNode::indexChanged(), indri::infnet::ExtentDescendantNode::indexChanged(), indri::infnet::ExtentChildNode::indexChanged(), indri::infnet::DocListIteratorNode::indexChanged(), indri::infnet::WeightedExtentOrNode::prepare(), indri::infnet::UnorderedWindowNode::prepare(), indri::infnet::OrderedWindowNode::prepare(), indri::infnet::NestedExtentInsideNode::prepare(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentOrNode::prepare(), indri::infnet::ExtentInsideNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), and indri::infnet::DocListIteratorNode::prepare().
int indri::infnet::ListIteratorNode::_lastpos [protected]
Referenced by initpointer(), matches(), and indri::infnet::ExtentChildNode::matches().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::ListIteratorNode::_matches [protected]
Referenced by matches(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), and indri::infnet::ExtentChildNode::matches().
The documentation for this class was generated from the following file:
ListIteratorNode.hpp