Indri: indri::infnet::FieldIteratorNode Class Reference
indri::infnet::FieldIteratorNode Class Reference
#include <FieldIteratorNode.hpp>
Public Member Functions
FieldIteratorNode (const std::string &name, class InferenceNetwork &network, int fieldID)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
const
indri::utility::greedy_vector
< INT64 > & numbers ()
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
class
indri::index::DocExtentListIterator * _list
int _listID
indri::utility::greedy_vector
< indri::index::Extent > _extents
indri::utility::greedy_vector
< INT64 > _numbers
class InferenceNetwork & _network
std::string _name
Constructor & Destructor Documentation
indri::infnet::FieldIteratorNode::FieldIteratorNode (const std::string & name, class InferenceNetwork & network, int fieldID)
Member Function Documentation
void indri::infnet::FieldIteratorNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, and indri::infnet::Annotator::addMatches().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::FieldIteratorNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
Referenced by indri::infnet::FieldLessNode::prepare(), indri::infnet::FieldGreaterNode::prepare(), indri::infnet::FieldEqualsNode::prepare(), and indri::infnet::FieldBetweenNode::prepare().
const std::string & indri::infnet::FieldIteratorNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::FieldIteratorNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _list, _listID, _network, indri::infnet::InferenceNetwork::getFieldIterator(), and indri::index::DocExtentListIterator::startIteration().
lemur::api::DOCID_T indri::infnet::FieldIteratorNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _list, indri::index::DocExtentListIterator::currentEntry(), and indri::index::DocExtentListIterator::DocumentExtentData::document.
Referenced by indri::infnet::FieldLessNode::nextCandidateDocument(), indri::infnet::FieldGreaterNode::nextCandidateDocument(), indri::infnet::FieldEqualsNode::nextCandidateDocument(), and indri::infnet::FieldBetweenNode::nextCandidateDocument().
const indri::utility::greedy_vector< INT64 > & indri::infnet::FieldIteratorNode::numbers ()
References _numbers.
Referenced by indri::infnet::FieldLessNode::prepare(), indri::infnet::FieldGreaterNode::prepare(), indri::infnet::FieldEqualsNode::prepare(), and indri::infnet::FieldBetweenNode::prepare().
void indri::infnet::FieldIteratorNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _extents, _list, _numbers, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocExtentListIterator::currentEntry(), indri::index::DocExtentListIterator::DocumentExtentData::document, indri::index::DocExtentListIterator::DocumentExtentData::extents, indri::infnet::ListIteratorNode::initpointer(), and indri::index::DocExtentListIterator::DocumentExtentData::numbers.
Member Data Documentation
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::FieldIteratorNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
class indri::index::DocExtentListIterator* indri::infnet::FieldIteratorNode::_list [private]
Referenced by indexChanged(), nextCandidateDocument(), and prepare().
int indri::infnet::FieldIteratorNode::_listID [private]
Referenced by indexChanged().
std::string indri::infnet::FieldIteratorNode::_name [private]
Referenced by getName().
class InferenceNetwork& indri::infnet::FieldIteratorNode::_network [private]
Referenced by indexChanged().
indri::utility::greedy_vector<INT64> indri::infnet::FieldIteratorNode::_numbers [private]
Referenced by numbers(), and prepare().
The documentation for this class was generated from the following files:
FieldIteratorNode.hpp
FieldIteratorNode.cpp