Indri: indri::parse::TokenizerFactory Class Reference
indri::parse::TokenizerFactory Class Reference
#include <TokenizerFactory.hpp>
Public Member Functions
~TokenizerFactory ()
Static Public Member Functions
static std::string preferredName (const std::string &name)
The idea here is to admit as many names as possible (including possibly misspellings).
static indri::parse::Tokenizer * get (const std::string &name)
Constructor & Destructor Documentation
indri::parse::TokenizerFactory::~TokenizerFactory ()
Member Function Documentation
indri::parse::Tokenizer * indri::parse::TokenizerFactory::get (const std::string & name) [static]
References preferredName(), TOKENIZER_CHAR, TOKENIZER_CHAR_NO_MARKUP, TOKENIZER_WORD, and TOKENIZER_WORD_NO_MARKUP.
Referenced by indri::parse::AnchorTextAnnotator::AnchorTextAnnotator(), build_file_class_environment(), and harvest_anchor_text().
std::string indri::parse::TokenizerFactory::preferredName (const std::string & name) [static]
The idea here is to admit as many names as possible (including possibly misspellings).
References TOKENIZER_CHAR, TOKENIZER_CHAR_NO_MARKUP, TOKENIZER_WORD, and TOKENIZER_WORD_NO_MARKUP.
Referenced by get().
The documentation for this class was generated from the following files:
TokenizerFactory.hpp
TokenizerFactory.cpp