Indri: indri::lang::ShrinkageScorerNode Class Reference
indri::lang::ShrinkageScorerNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ShrinkageScorerNode (RawExtentNode *raw, DocumentStructureNode *documentStructure, std::string smoothing="method:dirichlet,mu:2500")
ShrinkageScorerNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
void addShrinkageRule (std::string rule)
std::vector< std::string > getShrinkageRules ()
void setDocumentStructure (DocumentStructureNode *docStruct)
DocumentStructureNode * getDocumentStructure ()
UINT64 hashCode () const
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
DocumentStructureNode * _documentStructure
std::vector< std::string > _shrinkageRules
Constructor & Destructor Documentation
indri::lang::ShrinkageScorerNode::ShrinkageScorerNode (RawExtentNode * raw, DocumentStructureNode * documentStructure, std::string smoothing = "method:dirichlet,mu:2500") [inline]
Referenced by copy().
indri::lang::ShrinkageScorerNode::ShrinkageScorerNode (Unpacker & unpacker) [inline]
References indri::lang::RawScorerNode::_contextSize, _documentStructure, indri::lang::RawScorerNode::_occurrences, indri::lang::RawScorerNode::_raw, _shrinkageRules, indri::lang::RawScorerNode::_smoothing, indri::lang::Unpacker::getDocumentStructureNode(), indri::lang::Unpacker::getDouble(), indri::lang::Unpacker::getRawExtentNode(), indri::lang::Unpacker::getString(), and indri::lang::Unpacker::getStringVector().
Member Function Documentation
void indri::lang::ShrinkageScorerNode::addShrinkageRule (std::string rule) [inline]
References _shrinkageRules.
Node* indri::lang::ShrinkageScorerNode::copy (Copier & copier) [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References _documentStructure, indri::lang::RawScorerNode::_raw, _shrinkageRules, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::DocumentStructureNode::copy(), indri::lang::Node::copy(), and ShrinkageScorerNode().
DocumentStructureNode* indri::lang::ShrinkageScorerNode::getDocumentStructure () [inline]
References _documentStructure.
Referenced by indri::infnet::InferenceNetworkBuilder::_after().
std::vector<std::string> indri::lang::ShrinkageScorerNode::getShrinkageRules () [inline]
References _shrinkageRules.
Referenced by indri::infnet::InferenceNetworkBuilder::_after().
UINT64 indri::lang::ShrinkageScorerNode::hashCode () const [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References indri::lang::RawScorerNode::_context, indri::lang::RawScorerNode::_raw, indri::lang::RawScorerNode::_smoothing, and indri::lang::Node::hashCode().
void indri::lang::ShrinkageScorerNode::pack (Packer & packer) [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References indri::lang::RawScorerNode::_contextSize, _documentStructure, indri::lang::RawScorerNode::_occurrences, indri::lang::RawScorerNode::_raw, _shrinkageRules, indri::lang::RawScorerNode::_smoothing, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ShrinkageScorerNode::queryText () const [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References indri::lang::RawScorerNode::_raw, and indri::lang::Node::queryText().
void indri::lang::ShrinkageScorerNode::setDocumentStructure (DocumentStructureNode * docStruct) [inline]
References _documentStructure.
std::string indri::lang::ShrinkageScorerNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
void indri::lang::ShrinkageScorerNode::walk (Walker & walker) [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References _documentStructure, indri::lang::RawScorerNode::_raw, indri::lang::Walker::after(), indri::lang::Walker::before(), indri::lang::DocumentStructureNode::walk(), and indri::lang::Node::walk().
Member Data Documentation
DocumentStructureNode* indri::lang::ShrinkageScorerNode::_documentStructure [private]
Referenced by copy(), getDocumentStructure(), pack(), setDocumentStructure(), ShrinkageScorerNode(), and walk().
std::vector<std::string> indri::lang::ShrinkageScorerNode::_shrinkageRules [private]
Referenced by addShrinkageRule(), copy(), getShrinkageRules(), pack(), and ShrinkageScorerNode().
The documentation for this class was generated from the following file:
QuerySpec.hpp