Indri: indri::parse::KrovetzStemmerTransformation Class Reference
indri::parse::KrovetzStemmerTransformation Class Reference
#include <KrovetzStemmerTransformation.hpp>
Public Member Functions
KrovetzStemmerTransformation (indri::api::Parameters &parameters)
~KrovetzStemmerTransformation ()
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
Static Public Attributes
static bool _indri_kstem_loaded
Private Member Functions
char * _getBuffer (size_t length)
const char * _getBufferEnd () const
indri::api::ParsedDocument * _restart (indri::api::ParsedDocument *document, size_t lastIndex, char *endOfStemming)
indri::api::ParsedDocument * _processTerms (indri::api::ParsedDocument *document, size_t start, char *stem, const char *end)
char * _growBuffer (size_t length, char *oldEnd)
Private Attributes
KrovetzStemmer * stemmer
char * _stemBuffer
size_t _stemBufferSize
ObjectHandler
< indri::api::ParsedDocument > * _handler
Constructor & Destructor Documentation
indri::parse::KrovetzStemmerTransformation::KrovetzStemmerTransformation (indri::api::Parameters & parameters)
References _stemBuffer, _stemBufferSize, indri::api::Parameters::exists(), indri::parse::KrovetzStemmer::kstem_add_table_entry(), indri::api::Parameters::size(), and stemmer.
indri::parse::KrovetzStemmerTransformation::~KrovetzStemmerTransformation ()
References _stemBuffer, and stemmer.
Member Function Documentation
char * indri::parse::KrovetzStemmerTransformation::_getBuffer (size_t length) [private]
References _stemBuffer, and _stemBufferSize.
Referenced by _restart(), and transform().
const char * indri::parse::KrovetzStemmerTransformation::_getBufferEnd () const [private]
References _stemBuffer, and _stemBufferSize.
Referenced by _restart(), and transform().
char * indri::parse::KrovetzStemmerTransformation::_growBuffer (size_t length, char * oldEnd) [private]
References _stemBuffer, and _stemBufferSize.
Referenced by _restart().
indri::api::ParsedDocument * indri::parse::KrovetzStemmerTransformation::_processTerms (indri::api::ParsedDocument * document, size_t start, char * stem, const char * end) [private]
References _restart(), indri::atomic::increment(), indri::parse::KrovetzStemmer::kstem_stem_tobuffer(), indri::utility::greedy_vector< _Type, _Count >::size(), stemmer, and indri::api::ParsedDocument::terms.
Referenced by _restart(), and transform().
indri::api::ParsedDocument * indri::parse::KrovetzStemmerTransformation::_restart (indri::api::ParsedDocument * document, size_t lastIndex, char * endOfStemming) [private]
References _getBuffer(), _getBufferEnd(), _growBuffer(), _processTerms(), _stemBuffer, KSTEM_MAX_WORD_LENGTH, indri::utility::greedy_vector< _Type, _Count >::size(), and indri::api::ParsedDocument::terms.
Referenced by _processTerms().
void indri::parse::KrovetzStemmerTransformation::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::KrovetzStemmerTransformation::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::KrovetzStemmerTransformation::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _getBuffer(), _getBufferEnd(), _processTerms(), KSTEM_EXTRA_SPACE, KSTEM_MAX_WORD_LENGTH, indri::utility::greedy_vector< _Type, _Count >::size(), and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
ObjectHandler<indri::api::ParsedDocument>* indri::parse::KrovetzStemmerTransformation::_handler [private]
Referenced by handle(), and setHandler().
bool indri::parse::KrovetzStemmerTransformation::_indri_kstem_loaded [static]
char* indri::parse::KrovetzStemmerTransformation::_stemBuffer [private]
Referenced by _getBuffer(), _getBufferEnd(), _growBuffer(), _restart(), KrovetzStemmerTransformation(), and ~KrovetzStemmerTransformation().
size_t indri::parse::KrovetzStemmerTransformation::_stemBufferSize [private]
Referenced by _getBuffer(), _getBufferEnd(), _growBuffer(), and KrovetzStemmerTransformation().
KrovetzStemmer* indri::parse::KrovetzStemmerTransformation::stemmer [private]
Referenced by _processTerms(), KrovetzStemmerTransformation(), and ~KrovetzStemmerTransformation().
The documentation for this class was generated from the following files:
KrovetzStemmerTransformation.hpp
KrovetzStemmerTransformation.cpp