Indri: indri::lang::Walker Class Reference
indri::lang::Walker Class Reference
#include <Walker.hpp>
Public Member Functions
virtual ~Walker ()
virtual void defaultBefore (class Node *n)
virtual void defaultAfter (class Node *n)
virtual void before (class IndexTerm *n)
virtual void after (class IndexTerm *n)
virtual void before (class Field *n)
virtual void after (class Field *n)
virtual void before (class ExtentInside *n)
virtual void after (class ExtentInside *n)
virtual void before (class WeightedExtentOr *n)
virtual void after (class WeightedExtentOr *n)
virtual void before (class ExtentOr *n)
virtual void after (class ExtentOr *n)
virtual void before (class ExtentAnd *n)
virtual void after (class ExtentAnd *n)
virtual void before (class BAndNode *n)
virtual void after (class BAndNode *n)
virtual void before (class UWNode *n)
virtual void after (class UWNode *n)
virtual void before (class ODNode *n)
virtual void after (class ODNode *n)
virtual void before (class FilReqNode *n)
virtual void after (class FilReqNode *n)
virtual void before (class FilRejNode *n)
virtual void after (class FilRejNode *n)
virtual void before (class FieldLessNode *n)
virtual void after (class FieldLessNode *n)
virtual void before (class FieldGreaterNode *n)
virtual void after (class FieldGreaterNode *n)
virtual void before (class FieldBetweenNode *n)
virtual void after (class FieldBetweenNode *n)
virtual void before (class FieldEqualsNode *n)
virtual void after (class FieldEqualsNode *n)
virtual void before (class RawScorerNode *n)
virtual void after (class RawScorerNode *n)
virtual void before (class TermFrequencyScorerNode *n)
virtual void after (class TermFrequencyScorerNode *n)
virtual void before (class CachedFrequencyScorerNode *n)
virtual void after (class CachedFrequencyScorerNode *n)
virtual void before (class PriorNode *n)
virtual void after (class PriorNode *n)
virtual void before (class OrNode *n)
virtual void after (class OrNode *n)
virtual void before (class NotNode *n)
virtual void after (class NotNode *n)
virtual void before (class MaxNode *n)
virtual void after (class MaxNode *n)
virtual void before (class CombineNode *n)
virtual void after (class CombineNode *n)
virtual void before (class WAndNode *n)
virtual void after (class WAndNode *n)
virtual void before (class WSumNode *n)
virtual void after (class WSumNode *n)
virtual void before (class WeightNode *n)
virtual void after (class WeightNode *n)
virtual void before (class ExtentRestriction *n)
virtual void after (class ExtentRestriction *n)
virtual void before (class FixedPassage *n)
virtual void after (class FixedPassage *n)
virtual void before (class FilterNode *n)
virtual void after (class FilterNode *n)
virtual void before (class ListAccumulator *n)
virtual void after (class ListAccumulator *n)
virtual void before (class ContextCounterNode *n)
virtual void after (class ContextCounterNode *n)
virtual void before (class ContextSimpleCounterNode *n)
virtual void after (class ContextSimpleCounterNode *n)
virtual void before (class ScoreAccumulatorNode *n)
virtual void after (class ScoreAccumulatorNode *n)
virtual void before (class AnnotatorNode *n)
virtual void after (class AnnotatorNode *n)
virtual void before (class FieldWildcard *n)
virtual void after (class FieldWildcard *n)
virtual void before (class NestedExtentInside *n)
virtual void after (class NestedExtentInside *n)
virtual void before (class NestedRawScorerNode *n)
virtual void after (class NestedRawScorerNode *n)
virtual void before (class ExtentEnforcement *n)
virtual void after (class ExtentEnforcement *n)
virtual void before (class ContextInclusionNode *n)
virtual void after (class ContextInclusionNode *n)
virtual void before (class LengthPrior *n)
virtual void after (class LengthPrior *n)
virtual void before (class DocumentStructureNode *n)
virtual void after (class DocumentStructureNode *n)
virtual void before (class ShrinkageScorerNode *n)
virtual void after (class ShrinkageScorerNode *n)
virtual void before (class ExtentDescendant *n)
virtual void after (class ExtentDescendant *n)
virtual void before (class ExtentChild *n)
virtual void after (class ExtentChild *n)
virtual void before (class ExtentParent *n)
virtual void after (class ExtentParent *n)
virtual void before (class WildcardTerm *n)
virtual void after (class WildcardTerm *n)
virtual void before (class PlusNode *n)
virtual void after (class PlusNode *n)
virtual void before (class WPlusNode *n)
virtual void after (class WPlusNode *n)
Constructor & Destructor Documentation
indri::lang::Walker::~Walker () [virtual]
Member Function Documentation
void indri::lang::Walker::after (class WPlusNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder, and indri::lang::QueryTFWalker.
References defaultAfter().
void indri::lang::Walker::after (class PlusNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder, and indri::lang::QueryTFWalker.
References defaultAfter().
void indri::lang::Walker::after (class WildcardTerm * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentParent * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentChild * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentDescendant * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ShrinkageScorerNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder, indri::lang::RawScorerNodeExtractor, and indri::lang::SmoothingAnnotatorWalker.
References defaultAfter().
void indri::lang::Walker::after (class DocumentStructureNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class LengthPrior * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder, and indri::lang::SmoothingAnnotatorWalker.
References defaultAfter().
void indri::lang::Walker::after (class ContextInclusionNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentEnforcement * n) [virtual]
References defaultAfter().
void indri::lang::Walker::after (class NestedRawScorerNode * n) [virtual]
Reimplemented in indri::lang::RawScorerNodeExtractor, and indri::lang::SmoothingAnnotatorWalker.
References defaultAfter().
void indri::lang::Walker::after (class NestedExtentInside * n) [virtual]
References defaultAfter().
void indri::lang::Walker::after (class FieldWildcard * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class AnnotatorNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ScoreAccumulatorNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ContextSimpleCounterNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ContextCounterNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ListAccumulator * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FilterNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FixedPassage * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentRestriction * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class WeightNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class WSumNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class WAndNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class CombineNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class MaxNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class NotNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class OrNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class PriorNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class CachedFrequencyScorerNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class TermFrequencyScorerNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class RawScorerNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder, indri::lang::QueryTFWalker, indri::lang::RawScorerNodeExtractor, and indri::lang::SmoothingAnnotatorWalker.
References defaultAfter().
void indri::lang::Walker::after (class FieldEqualsNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FieldBetweenNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FieldGreaterNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FieldLessNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FilRejNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class FilReqNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ODNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class UWNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class BAndNode * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentAnd * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentOr * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class WeightedExtentOr * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class ExtentInside * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class Field * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
void indri::lang::Walker::after (class IndexTerm * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder.
References defaultAfter().
Referenced by indri::lang::ContextInclusionNode::_walk(), indri::lang::WeightedCombinationNode::_walk(), indri::lang::UnweightedCombinationNode::_walk(), indri::lang::WildcardTerm::walk(), indri::lang::ExtentParent::walk(), indri::lang::ExtentChild::walk(), indri::lang::ExtentDescendant::walk(), indri::lang::ShrinkageScorerNode::walk(), indri::lang::DocumentStructureNode::walk(), indri::lang::LengthPrior::walk(), indri::lang::FieldWildcard::walk(), indri::lang::AnnotatorNode::walk(), indri::lang::ScoreAccumulatorNode::walk(), indri::lang::ContextSimpleCounterNode::walk(), indri::lang::ContextCounterNode::walk(), indri::lang::ListAccumulator::walk(), indri::lang::FilterNode::walk(), indri::lang::FixedPassage::walk(), indri::lang::ExtentRestriction::walk(), indri::lang::NotNode::walk(), indri::lang::PriorNode::walk(), indri::lang::CachedFrequencyScorerNode::walk(), indri::lang::TermFrequencyScorerNode::walk(), indri::lang::RawScorerNode::walk(), indri::lang::FieldEqualsNode::walk(), indri::lang::FieldBetweenNode::walk(), indri::lang::FieldGreaterNode::walk(), indri::lang::FieldLessNode::walk(), indri::lang::FilRejNode::walk(), indri::lang::FilReqNode::walk(), indri::lang::ODNode::walk(), indri::lang::UWNode::walk(), indri::lang::BAndNode::walk(), indri::lang::ExtentAnd::walk(), indri::lang::ExtentOr::walk(), indri::lang::WeightedExtentOr::walk(), indri::lang::ExtentInside::walk(), indri::lang::Field::walk(), and indri::lang::IndexTerm::walk().
void indri::lang::Walker::before (class WPlusNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class PlusNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class WildcardTerm * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentParent * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentChild * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentDescendant * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ShrinkageScorerNode * n) [virtual]
Reimplemented in indri::lang::RawScorerNodeExtractor.
References defaultBefore().
void indri::lang::Walker::before (class DocumentStructureNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class LengthPrior * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ContextInclusionNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentEnforcement * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class NestedRawScorerNode * n) [virtual]
Reimplemented in indri::lang::RawScorerNodeExtractor.
References defaultBefore().
void indri::lang::Walker::before (class NestedExtentInside * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FieldWildcard * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class AnnotatorNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ScoreAccumulatorNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ContextSimpleCounterNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ContextCounterNode * n) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker.
References defaultBefore().
void indri::lang::Walker::before (class ListAccumulator * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FilterNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FixedPassage * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentRestriction * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class WeightNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class WSumNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class WAndNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class CombineNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class MaxNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class NotNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class OrNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class PriorNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class CachedFrequencyScorerNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class TermFrequencyScorerNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class RawScorerNode * n) [virtual]
Reimplemented in indri::lang::RawScorerNodeExtractor.
References defaultBefore().
void indri::lang::Walker::before (class FieldEqualsNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FieldBetweenNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FieldGreaterNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FieldLessNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FilRejNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class FilReqNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ODNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class UWNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class BAndNode * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentAnd * n) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker.
References defaultBefore().
void indri::lang::Walker::before (class ExtentOr * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class WeightedExtentOr * n) [virtual]
References defaultBefore().
void indri::lang::Walker::before (class ExtentInside * n) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker.
References defaultBefore().
void indri::lang::Walker::before (class Field * n) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker, indri::lang::FieldBelowWalker, and indri::lang::TreePrinterWalker.
References defaultBefore().
void indri::lang::Walker::before (class IndexTerm * n) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker, and indri::lang::TreePrinterWalker.
References defaultBefore().
Referenced by indri::lang::ContextInclusionNode::_walk(), indri::lang::WeightedCombinationNode::_walk(), indri::lang::UnweightedCombinationNode::_walk(), indri::lang::WildcardTerm::walk(), indri::lang::ExtentParent::walk(), indri::lang::ExtentChild::walk(), indri::lang::ExtentDescendant::walk(), indri::lang::ShrinkageScorerNode::walk(), indri::lang::DocumentStructureNode::walk(), indri::lang::LengthPrior::walk(), indri::lang::FieldWildcard::walk(), indri::lang::AnnotatorNode::walk(), indri::lang::ScoreAccumulatorNode::walk(), indri::lang::ContextSimpleCounterNode::walk(), indri::lang::ContextCounterNode::walk(), indri::lang::ListAccumulator::walk(), indri::lang::FilterNode::walk(), indri::lang::FixedPassage::walk(), indri::lang::ExtentRestriction::walk(), indri::lang::NotNode::walk(), indri::lang::PriorNode::walk(), indri::lang::CachedFrequencyScorerNode::walk(), indri::lang::TermFrequencyScorerNode::walk(), indri::lang::RawScorerNode::walk(), indri::lang::FieldEqualsNode::walk(), indri::lang::FieldBetweenNode::walk(), indri::lang::FieldGreaterNode::walk(), indri::lang::FieldLessNode::walk(), indri::lang::FilRejNode::walk(), indri::lang::FilReqNode::walk(), indri::lang::ODNode::walk(), indri::lang::UWNode::walk(), indri::lang::BAndNode::walk(), indri::lang::ExtentAnd::walk(), indri::lang::ExtentOr::walk(), indri::lang::WeightedExtentOr::walk(), indri::lang::ExtentInside::walk(), indri::lang::Field::walk(), and indri::lang::IndexTerm::walk().
void indri::lang::Walker::defaultAfter (class Node * n) [virtual]
Reimplemented in indri::infnet::InferenceNetworkBuilder, indri::lang::TreePrinterWalker, indri::lang::QueryNodeBuilder, and indri::lang::Printer.
Referenced by after().
void indri::lang::Walker::defaultBefore (class Node * n) [virtual]
Reimplemented in indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker, indri::lang::RawScorerNodeExtractor, indri::lang::TreePrinterWalker, indri::lang::UnnecessaryNodeRemoverCopier::SingleChildWalker, indri::lang::QueryNodeBuilder, and indri::lang::Printer.
Referenced by before().
The documentation for this class was generated from the following files:
Walker.hpp
Walker.cpp