Indri: indri::index::VocabularyIterator Class Reference
indri::index::VocabularyIterator Class Reference
#include <VocabularyIterator.hpp>
Public Member Functions
virtual ~VocabularyIterator ()
virtual void startIteration ()=0
virtual bool finished ()=0
virtual bool nextEntry ()=0
virtual bool nextEntry (const char *skipTo)=0
virtual bool nextEntry (std::string skipTo)
virtual DiskTermData * currentEntry ()=0
Constructor & Destructor Documentation
virtual indri::index::VocabularyIterator::~VocabularyIterator () [inline, virtual]
Member Function Documentation
virtual DiskTermData* indri::index::VocabularyIterator::currentEntry () [pure virtual]
Implemented in indri::index::CombinedVocabularyIterator, indri::index::DiskFrequentVocabularyIterator, indri::index::DiskKeyfileVocabularyIterator, and indri::index::MemoryIndexVocabularyIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::infnet::InferenceNetworkBuilder::after(), indri::index::CombinedVocabularyIterator::currentEntry(), indri::index::CombinedVocabularyIterator::nextEntry(), and print_vocabulary().
virtual bool indri::index::VocabularyIterator::finished () [pure virtual]
Implemented in indri::index::CombinedVocabularyIterator, indri::index::DiskFrequentVocabularyIterator, indri::index::DiskKeyfileVocabularyIterator, and indri::index::MemoryIndexVocabularyIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::index::CombinedVocabularyIterator::finished(), print_vocabulary(), and indri::index::CombinedVocabularyIterator::startIteration().
virtual bool indri::index::VocabularyIterator::nextEntry (std::string skipTo) [inline, virtual]
References nextEntry().
virtual bool indri::index::VocabularyIterator::nextEntry (const char * skipTo) [pure virtual]
Implemented in indri::index::CombinedVocabularyIterator, indri::index::DiskFrequentVocabularyIterator, indri::index::DiskKeyfileVocabularyIterator, and indri::index::MemoryIndexVocabularyIterator.
virtual bool indri::index::VocabularyIterator::nextEntry () [pure virtual]
Implemented in indri::index::CombinedVocabularyIterator, indri::index::DiskFrequentVocabularyIterator, indri::index::DiskKeyfileVocabularyIterator, and indri::index::MemoryIndexVocabularyIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::infnet::InferenceNetworkBuilder::after(), nextEntry(), indri::index::CombinedVocabularyIterator::nextEntry(), and print_vocabulary().
virtual void indri::index::VocabularyIterator::startIteration () [pure virtual]
Implemented in indri::index::CombinedVocabularyIterator, indri::index::DiskFrequentVocabularyIterator, indri::index::DiskKeyfileVocabularyIterator, and indri::index::MemoryIndexVocabularyIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::infnet::InferenceNetworkBuilder::after(), indri::index::CombinedVocabularyIterator::nextEntry(), print_vocabulary(), and indri::index::CombinedVocabularyIterator::startIteration().
The documentation for this class was generated from the following file:
VocabularyIterator.hpp