Indri: indri::index::MemoryIndex Class Reference
indri::index::MemoryIndex Class Reference
#include <MemoryIndex.hpp>
Classes
struct term_entry
Public Member Functions
MemoryIndex ()
MemoryIndex (lemur::api::DOCID_T docBase)
MemoryIndex (lemur::api::DOCID_T docBase, const std::vector< Index::FieldDescription > &fields)
~MemoryIndex ()
void close ()
lemur::api::DOCID_T documentBase ()
lemur::api::DOCID_T documentMaximum ()
The documentMaximum is at least one greater than the largest documentID used in this index.
lemur::api::TERMID_T term (const std::string &t)
lemur::api::TERMID_T term (const char *t)
std::string term (lemur::api::TERMID_T termID)
int field (const char *fieldName)
int field (const std::string &fieldName)
std::string field (int fieldID)
int documentLength (lemur::api::DOCID_T documentID)
UINT64 documentCount ()
UINT64 documentCount (const std::string &term)
UINT64 uniqueTermCount ()
UINT64 termCount (const std::string &term)
UINT64 termCount ()
UINT64 fieldTermCount (const std::string &field)
UINT64 fieldTermCount (const std::string &field, const std::string &term)
UINT64 fieldDocumentCount (const std::string &field)
UINT64 fieldDocumentCount (const std::string &field, const std::string &term)
DocListIterator * docListIterator (lemur::api::TERMID_T termID)
DocListIterator * docListIterator (const std::string &term)
DocListFileIterator * docListFileIterator ()
DocExtentListIterator * fieldListIterator (int fieldID)
DocExtentListIterator * fieldListIterator (const std::string &field)
const TermList * termList (lemur::api::DOCID_T documentID)
TermListFileIterator * termListFileIterator ()
VocabularyIterator * vocabularyIterator ()
VocabularyIterator * frequentVocabularyIterator ()
VocabularyIterator * infrequentVocabularyIterator ()
DocumentDataIterator * documentDataIterator ()
indri::thread::Lockable * iteratorLock ()
indri::thread::Lockable * statisticsLock ()
lemur::api::DOCID_T addDocument (indri::api::ParsedDocument &document)
size_t memorySize ()
Private Member Functions
void _addOpenTags (indri::utility::greedy_vector< indri::parse::TagExtent * > &indexedTags, indri::utility::greedy_vector< indri::parse::TagExtent * > &openTags, indri::utility::greedy_vector< indri::parse::TagExtent * > &extents, unsigned int &extentIndex, unsigned int position)
void _removeClosedTags (indri::utility::greedy_vector< indri::parse::TagExtent * > &tags, unsigned int position)
void _writeFieldExtents (lemur::api::DOCID_T documentID, indri::utility::greedy_vector< indri::parse::TagExtent * > &indexedTags)
void _writeDocumentTermList (UINT64 &offset, int &byteLength, lemur::api::DOCID_T documentID, int documentLength, indri::index::TermList &locatedTerms)
void _writeDocumentStatistics (UINT64 offset, int byteLength, int indexedLength, int totalLength, int uniqueTerms)
term_entry * _lookupTerm (const char *term)
void _destroyTerms ()
int _fieldID (const std::string &fieldName)
int _fieldID (const char *fieldName)
Private Attributes
indri::utility::RegionAllocator _allocator
indri::thread::ReadersWritersLock _lock
indri::thread::ReaderLockable _readLock
indri::thread::WriterLockable _writeLock
CorpusStatistics _corpusStatistics
lemur::api::DOCID_T _baseDocumentID
indri::index::TermList _termList
indri::utility::greedy_vector
< term_entry * > _seenTerms
indri::utility::HashTable
< const char *, term_entry * > _stringToTerm
std::vector< term_entry * > _idToTerm
indri::utility::HashTable
< const char *, int > _fieldLookup
std::vector< FieldStatistics > _fieldData
std::vector
< indri::index::DocExtentListMemoryBuilder * > _fieldLists
std::vector
< indri::index::DocumentData > _documentData
std::list
< indri::utility::Buffer * > _termLists
UINT64 _termListsBaseOffset
Constructor & Destructor Documentation
indri::index::MemoryIndex::MemoryIndex ()
References _corpusStatistics, _termListsBaseOffset, indri::index::CorpusStatistics::baseDocument, and indri::index::CorpusStatistics::maximumDocument.
indri::index::MemoryIndex::MemoryIndex (lemur::api::DOCID_T docBase)
References _corpusStatistics, _termListsBaseOffset, indri::index::CorpusStatistics::baseDocument, and indri::index::CorpusStatistics::maximumDocument.
indri::index::MemoryIndex::MemoryIndex (lemur::api::DOCID_T docBase, const std::vector< Index::FieldDescription > & fields)
References _corpusStatistics, _fieldData, _fieldLists, _fieldLookup, _termListsBaseOffset, indri::index::CorpusStatistics::baseDocument, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), and indri::index::CorpusStatistics::maximumDocument.
indri::index::MemoryIndex::~MemoryIndex ()
References _destroyTerms(), _fieldLists, and _termLists.
Member Function Documentation
void indri::index::MemoryIndex::_addOpenTags (indri::utility::greedy_vector< indri::parse::TagExtent * > & indexedTags, indri::utility::greedy_vector< indri::parse::TagExtent * > & openTags, indri::utility::greedy_vector< indri::parse::TagExtent * > & extents, unsigned int & extentIndex, unsigned int position) [private]
References _fieldID(), indri::parse::TagExtent::begin, indri::parse::TagExtent::name, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by addDocument().
void indri::index::MemoryIndex::_destroyTerms () [private]
References _fieldData, _idToTerm, indri::index::MemoryIndex::term_entry::termData, and termdata_destruct().
Referenced by ~MemoryIndex().
int indri::index::MemoryIndex::_fieldID (const char * fieldName) [private]
References _fieldLookup, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
int indri::index::MemoryIndex::_fieldID (const std::string & fieldName) [private]
Referenced by _addOpenTags(), _writeFieldExtents(), addDocument(), field(), fieldDocumentCount(), fieldListIterator(), and fieldTermCount().
indri::index::MemoryIndex::term_entry * indri::index::MemoryIndex::_lookupTerm (const char * term) [private]
References _allocator, _corpusStatistics, _fieldData, _idToTerm, _stringToTerm, indri::utility::RegionAllocator::allocate(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::index::TermData::term, termdata_construct(), termdata_size(), and indri::index::CorpusStatistics::uniqueTerms.
Referenced by addDocument().
void indri::index::MemoryIndex::_removeClosedTags (indri::utility::greedy_vector< indri::parse::TagExtent * > & tags, unsigned int position) [private]
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::erase(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by addDocument().
void indri::index::MemoryIndex::_writeDocumentStatistics (UINT64 offset, int byteLength, int indexedLength, int totalLength, int uniqueTerms) [private]
References _documentData, indri::index::DocumentData::byteLength, indri::index::DocumentData::indexedLength, indri::index::DocumentData::offset, indri::index::DocumentData::totalLength, and indri::index::DocumentData::uniqueTermCount.
Referenced by addDocument().
void indri::index::MemoryIndex::_writeDocumentTermList (UINT64 & offset, int & byteLength, lemur::api::DOCID_T documentID, int documentLength, indri::index::TermList & locatedTerms) [private]
References _termLists, _termListsBaseOffset, indri::index::TermList::fields(), ONE_MEGABYTE, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::TermList::terms(), and indri::index::TermList::write().
Referenced by addDocument().
void indri::index::MemoryIndex::_writeFieldExtents (lemur::api::DOCID_T documentID, indri::utility::greedy_vector< indri::parse::TagExtent * > & indexedTags) [private]
References _fieldID(), _fieldLists, _termList, indri::parse::TagExtent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::TagExtent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::TermList::fields(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::parse::TagExtent::parent, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by addDocument().
lemur::api::DOCID_T indri::index::MemoryIndex::addDocument (indri::api::ParsedDocument & document)
References _addOpenTags(), _corpusStatistics, _fieldData, _fieldID(), _lookupTerm(), _removeClosedTags(), _termList, _writeDocumentStatistics(), _writeDocumentTermList(), _writeFieldExtents(), _writeLock, indri::index::DocListMemoryBuilder::addLocation(), indri::index::FieldStatistics::addOccurrence(), indri::index::TermFieldStatistics::addOccurrence(), indri::index::TermList::addTerm(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::TermList::clear(), indri::index::MemoryIndex::term_entry::clearMark(), indri::index::TermData::corpus, indri::index::TermFieldStatistics::documentCount, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::DocListMemoryBuilder::endDocument(), field(), indri::index::TermData::fields, indri::index::MemoryIndex::term_entry::hasNext(), indri::index::MemoryIndex::term_entry::list, indri::index::MemoryIndex::term_entry::mark(), indri::index::MemoryIndex::term_entry::marked(), indri::index::TermData::maxDocumentLength, indri::index::CorpusStatistics::maximumDocument, indri::index::TermData::minDocumentLength, indri::index::MemoryIndex::term_entry::next, indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DocListMemoryBuilder::startDocument(), indri::api::ParsedDocument::tags, indri::index::MemoryIndex::term_entry::termData, indri::index::DocListMemoryBuilder::termFrequency(), indri::index::MemoryIndex::term_entry::termID, indri::api::ParsedDocument::terms, indri::index::TermFieldStatistics::totalCount, indri::index::CorpusStatistics::totalDocuments, and indri::index::CorpusStatistics::totalTerms.
void indri::index::MemoryIndex::close () [virtual]
Implements indri::index::Index.
indri::index::DocListFileIterator * indri::index::MemoryIndex::docListFileIterator () [virtual]
Implements indri::index::Index.
References _idToTerm.
indri::index::DocListIterator * indri::index::MemoryIndex::docListIterator (const std::string & term) [virtual]
Implements indri::index::Index.
References _stringToTerm, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
indri::index::DocListIterator * indri::index::MemoryIndex::docListIterator (lemur::api::TERMID_T termID) [virtual]
Implements indri::index::Index.
References _corpusStatistics, _idToTerm, indri::index::MemoryIndex::term_entry::list, indri::index::MemoryIndex::term_entry::termData, and indri::index::CorpusStatistics::uniqueTerms.
lemur::api::DOCID_T indri::index::MemoryIndex::documentBase () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::baseDocument.
Referenced by termList().
UINT64 indri::index::MemoryIndex::documentCount (const std::string & term) [virtual]
Implements indri::index::Index.
References _stringToTerm, indri::index::TermData::corpus, indri::index::TermFieldStatistics::documentCount, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), and indri::index::MemoryIndex::term_entry::termData.
UINT64 indri::index::MemoryIndex::documentCount () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::totalDocuments.
indri::index::DocumentDataIterator * indri::index::MemoryIndex::documentDataIterator () [virtual]
Implements indri::index::Index.
References _documentData.
int indri::index::MemoryIndex::documentLength (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::Index.
References _corpusStatistics, _documentData, and indri::index::CorpusStatistics::baseDocument.
lemur::api::DOCID_T indri::index::MemoryIndex::documentMaximum () [virtual]
The documentMaximum is at least one greater than the largest documentID used in this index.
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::maximumDocument.
std::string indri::index::MemoryIndex::field (int fieldID) [virtual]
Implements indri::index::Index.
References _fieldData.
int indri::index::MemoryIndex::field (const std::string & fieldName) [virtual]
Implements indri::index::Index.
References field().
int indri::index::MemoryIndex::field (const char * fieldName) [virtual]
Implements indri::index::Index.
References _fieldID().
Referenced by addDocument(), and field().
UINT64 indri::index::MemoryIndex::fieldDocumentCount (const std::string & field, const std::string & term) [virtual]
Implements indri::index::Index.
References _fieldID(), _stringToTerm, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
UINT64 indri::index::MemoryIndex::fieldDocumentCount (const std::string & field) [virtual]
Implements indri::index::Index.
References _fieldData, and _fieldID().
indri::index::DocExtentListIterator * indri::index::MemoryIndex::fieldListIterator (const std::string & field) [virtual]
Implements indri::index::Index.
References _fieldData, _fieldID(), _fieldLists, and indri::index::DocExtentListMemoryBuilder::getIterator().
indri::index::DocExtentListIterator * indri::index::MemoryIndex::fieldListIterator (int fieldID) [virtual]
Implements indri::index::Index.
References _fieldData, _fieldLists, and indri::index::DocExtentListMemoryBuilder::getIterator().
UINT64 indri::index::MemoryIndex::fieldTermCount (const std::string & field, const std::string & term) [virtual]
Implements indri::index::Index.
References _fieldID(), _stringToTerm, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
UINT64 indri::index::MemoryIndex::fieldTermCount (const std::string & field) [virtual]
Implements indri::index::Index.
References _fieldData, and _fieldID().
indri::index::VocabularyIterator * indri::index::MemoryIndex::frequentVocabularyIterator () [virtual]
Implements indri::index::Index.
References _idToTerm.
indri::index::VocabularyIterator * indri::index::MemoryIndex::infrequentVocabularyIterator () [virtual]
Implements indri::index::Index.
indri::thread::Lockable * indri::index::MemoryIndex::iteratorLock () [virtual]
Implements indri::index::Index.
References _readLock.
size_t indri::index::MemoryIndex::memorySize ()
References _allocator, _documentData, _fieldLists, _readLock, _termLists, and indri::utility::RegionAllocator::allocatedBytes().
Referenced by indri::collection::RepositoryMaintenanceThread::work(), and indri::collection::RepositoryLoadThread::work().
indri::thread::Lockable * indri::index::MemoryIndex::statisticsLock () [virtual]
Implements indri::index::Index.
std::string indri::index::MemoryIndex::term (lemur::api::TERMID_T termID) [virtual]
Implements indri::index::Index.
References _idToTerm, and indri::index::MemoryIndex::term_entry::term.
lemur::api::TERMID_T indri::index::MemoryIndex::term (const char * t) [virtual]
Implements indri::index::Index.
References _stringToTerm, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), and indri::index::MemoryIndex::term_entry::termID.
lemur::api::TERMID_T indri::index::MemoryIndex::term (const std::string & t) [virtual]
Implements indri::index::Index.
References _stringToTerm, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), and indri::index::MemoryIndex::term_entry::termID.
UINT64 indri::index::MemoryIndex::termCount () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::totalTerms.
UINT64 indri::index::MemoryIndex::termCount (const std::string & term) [virtual]
Implements indri::index::Index.
References _stringToTerm, indri::index::TermData::corpus, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::index::MemoryIndex::term_entry::termData, and indri::index::TermFieldStatistics::totalCount.
const indri::index::TermList * indri::index::MemoryIndex::termList (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::Index.
References _documentData, _termLists, indri::index::DocumentData::byteLength, documentBase(), indri::utility::Buffer::front(), indri::index::DocumentData::offset, indri::utility::Buffer::position(), and indri::index::TermList::read().
indri::index::TermListFileIterator * indri::index::MemoryIndex::termListFileIterator () [virtual]
Implements indri::index::Index.
References _documentData, and _termLists.
UINT64 indri::index::MemoryIndex::uniqueTermCount () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::uniqueTerms.
indri::index::VocabularyIterator * indri::index::MemoryIndex::vocabularyIterator () [virtual]
Implements indri::index::Index.
References _idToTerm.
Member Data Documentation
indri::utility::RegionAllocator indri::index::MemoryIndex::_allocator [private]
Referenced by _lookupTerm(), and memorySize().
lemur::api::DOCID_T indri::index::MemoryIndex::_baseDocumentID [private]
CorpusStatistics indri::index::MemoryIndex::_corpusStatistics [private]
Referenced by _lookupTerm(), addDocument(), docListIterator(), documentBase(), documentCount(), documentLength(), documentMaximum(), MemoryIndex(), termCount(), and uniqueTermCount().
std::vector<indri::index::DocumentData> indri::index::MemoryIndex::_documentData [private]
Referenced by _writeDocumentStatistics(), documentDataIterator(), documentLength(), memorySize(), termList(), and termListFileIterator().
std::vector<FieldStatistics> indri::index::MemoryIndex::_fieldData [private]
Referenced by _destroyTerms(), _lookupTerm(), addDocument(), field(), fieldDocumentCount(), fieldListIterator(), fieldTermCount(), and MemoryIndex().
std::vector<indri::index::DocExtentListMemoryBuilder*> indri::index::MemoryIndex::_fieldLists [private]
Referenced by _writeFieldExtents(), fieldListIterator(), MemoryIndex(), memorySize(), and ~MemoryIndex().
indri::utility::HashTable<const char*, int> indri::index::MemoryIndex::_fieldLookup [private]
Referenced by _fieldID(), and MemoryIndex().
std::vector<term_entry*> indri::index::MemoryIndex::_idToTerm [private]
Referenced by _destroyTerms(), _lookupTerm(), docListFileIterator(), docListIterator(), frequentVocabularyIterator(), term(), and vocabularyIterator().
indri::thread::ReadersWritersLock indri::index::MemoryIndex::_lock [private]
indri::thread::ReaderLockable indri::index::MemoryIndex::_readLock [private]
Referenced by iteratorLock(), and memorySize().
indri::utility::greedy_vector<term_entry*> indri::index::MemoryIndex::_seenTerms [private]
indri::utility::HashTable<const char*, term_entry*> indri::index::MemoryIndex::_stringToTerm [private]
Referenced by _lookupTerm(), docListIterator(), documentCount(), fieldDocumentCount(), fieldTermCount(), term(), and termCount().
indri::index::TermList indri::index::MemoryIndex::_termList [private]
Referenced by _writeFieldExtents(), and addDocument().
std::list<indri::utility::Buffer*> indri::index::MemoryIndex::_termLists [private]
Referenced by _writeDocumentTermList(), memorySize(), termList(), termListFileIterator(), and ~MemoryIndex().
UINT64 indri::index::MemoryIndex::_termListsBaseOffset [private]
Referenced by _writeDocumentTermList(), and MemoryIndex().
indri::thread::WriterLockable indri::index::MemoryIndex::_writeLock [private]
Referenced by addDocument().
The documentation for this class was generated from the following files:
MemoryIndex.hpp
MemoryIndex.cpp