Indri: indri::parse::DocumentIteratorFactory Class Reference
indri::parse::DocumentIteratorFactory Class Reference
#include <DocumentIteratorFactory.hpp>
Public Member Functions
~DocumentIteratorFactory ()
Static Public Member Functions
static DocumentIterator * get (const std::string &type)
static DocumentIterator * get (const std::string &type, const char *startDocTag, const char *endDocTag, const char *startMetadataTag)
static std::string preferredName (const std::string &type)
Constructor & Destructor Documentation
indri::parse::DocumentIteratorFactory::~DocumentIteratorFactory ()
Member Function Documentation
indri::parse::DocumentIterator * indri::parse::DocumentIteratorFactory::get (const std::string & type, const char * startDocTag, const char * endDocTag, const char * startMetadataTag) [static]
References preferredName(), indri::parse::TaggedDocumentIterator::setTags(), TYPE_MBOX, TYPE_PDF, TYPE_PPT, TYPE_TAGGED, TYPE_TEXT, TYPE_WARC, and TYPE_WORD.
indri::parse::DocumentIterator * indri::parse::DocumentIteratorFactory::get (const std::string & type) [static]
Referenced by build_file_class_environment().
std::string indri::parse::DocumentIteratorFactory::preferredName (const std::string & type) [static]
References TYPE_MBOX, TYPE_PDF, TYPE_PPT, TYPE_TAGGED, TYPE_TEXT, TYPE_WARC, and TYPE_WORD.
Referenced by get().
The documentation for this class was generated from the following files:
DocumentIteratorFactory.hpp
DocumentIteratorFactory.cpp