Indri: indri::parse::Arabic_Stemmer_utf8 Class Reference
indri::parse::Arabic_Stemmer_utf8 Class Reference
#include <Arabic_Stemmer_utf8.hpp>
Classes
struct eqstr
struct ltstr_unicode
struct stem_info_u_t
struct uint64Hasher
Public Member Functions
Arabic_Stemmer_utf8 (std::string stemFunc)
~Arabic_Stemmer_utf8 ()
void stemTerm (char *, char *)
Private Types
typedef hash_map< UINT64,
UINT64, uint64Hasher, eqstr > transitionTable
Private Member Functions
void createStemmerTransitionTables ()
void arabic_stop_unicode (UINT64 *, UINT64 *)
void no_stem_unicode (UINT64 *, UINT64 *)
void arabic_norm2_unicode (UINT64 *, UINT64 *)
void arabic_norm2_stop_unicode (UINT64 *, UINT64 *)
void arabic_light10_unicode (UINT64 *, UINT64 *)
void arabic_light10_stop_unicode (UINT64 *, UINT64 *)
bool on_stop_list_unicode (UINT64 *word)
void remove_definite_articles_unicode (UINT64 *word, UINT64 *result)
void remove_all_suffixes_unicode (UINT64 *word, UINT64 *result, size_t lenlimit)
Private Attributes
UTF8Transcoder _transcoder
void(Arabic_Stemmer_utf8::* stem_fct_unicode)(UINT64 *, UINT64 *)
std::set< const UINT64
*, ltstr_unicode > stop_words_set_unicode
transitionTable normCharTable
transitionTable norm3CharTable
transitionTable arabicVowelTable
Static Private Attributes
static stem_info_u_t stemtable_unicode []
static const UINT64 * allDefArticles [] = {defArticle0,defArticle1,defArticle2,defArticle3,defArticle4,defArticle5,NULL}
static const UINT64 defArticle0 [] = {0x0627,0x0644,NULL }
static const UINT64 defArticle1 [] = {0x0648,0x0627,0x0644,NULL }
static const UINT64 defArticle2 [] = {0x0628,0x0627,0x0644,NULL }
static const UINT64 defArticle3 [] = {0x0643,0x0627,0x0644,NULL }
static const UINT64 defArticle4 [] = {0x0641,0x0627,0x0644,NULL }
static const UINT64 defArticle5 [] = {0x0644,0x0644,NULL }
static const UINT64 * allSuffixes [] = {suffix0,suffix1,suffix2,suffix3,suffix4,suffix5,suffix6,suffix7,suffix8,suffix9,NULL}
static const UINT64 suffix0 [] = {0x0647,0x0627,NULL }
static const UINT64 suffix1 [] = {0x0627,0x0646,NULL }
static const UINT64 suffix2 [] = {0x0627,0x062A,NULL }
static const UINT64 suffix3 [] = {0x0648,0x0646,NULL }
static const UINT64 suffix4 [] = {0x064A,0x0646,NULL }
static const UINT64 suffix5 [] = {0x064A,0x0647,NULL }
static const UINT64 suffix6 [] = {0x064A,0x0629,NULL }
static const UINT64 suffix7 [] = {0x0647,NULL }
static const UINT64 suffix8 [] = {0x0629,NULL }
static const UINT64 suffix9 [] = {0x064A,NULL }
static const UINT64 * allStopWords [] = {stopWord0,stopWord1,stopWord2,stopWord3,stopWord4,stopWord5,stopWord6,stopWord7,stopWord8,stopWord9,stopWord10,stopWord11,stopWord12,stopWord13,stopWord14,stopWord15,stopWord16,stopWord17,stopWord18,stopWord19,stopWord20,stopWord21,stopWord22,stopWord23,stopWord24,stopWord25,stopWord26,stopWord27,stopWord28,stopWord29,stopWord30,stopWord31,stopWord32,stopWord33,stopWord34,stopWord35,stopWord36,stopWord37,stopWord38,stopWord39,stopWord40,stopWord41,stopWord42,stopWord43,stopWord44,stopWord45,stopWord46,stopWord47,stopWord48,stopWord49,stopWord50,stopWord51,stopWord52,stopWord53,stopWord54,stopWord55,stopWord56,stopWord57,stopWord58,stopWord59,stopWord60,stopWord61,stopWord62,stopWord63,stopWord64,stopWord65,stopWord66,stopWord67,stopWord68,stopWord69,stopWord70,stopWord71,stopWord72,stopWord73,stopWord74,stopWord75,stopWord76,stopWord77,stopWord78,stopWord79,stopWord80,stopWord81,stopWord82,stopWord83,stopWord84,stopWord85,stopWord86,stopWord87,stopWord88,stopWord89,stopWord90,stopWord91,stopWord92,stopWord93,stopWord94,stopWord95,stopWord96,stopWord97,stopWord98,stopWord99,stopWord100,stopWord101,stopWord102,stopWord103,stopWord104,stopWord105,stopWord106,stopWord107,stopWord108,stopWord109,stopWord110,stopWord111,stopWord112,stopWord113,stopWord114,stopWord115,stopWord116,stopWord117,stopWord118,stopWord119,stopWord120,stopWord121,stopWord122,stopWord123,stopWord124,stopWord125,stopWord126,stopWord127,stopWord128,stopWord129,stopWord130,stopWord131,stopWord132,stopWord133,stopWord134,stopWord135,stopWord136,stopWord137,stopWord138,stopWord139,stopWord140,stopWord141,stopWord142,stopWord143,stopWord144,stopWord145,stopWord146,stopWord147,stopWord148,stopWord149,stopWord150,stopWord151,stopWord152,stopWord153,stopWord154,stopWord155,stopWord156,stopWord157,stopWord158,stopWord159,stopWord160,stopWord161,stopWord162,stopWord163,stopWord164,stopWord165,stopWord166,stopWord167,NULL}
static const UINT64 stopWord0 [] = {0x0627,0x0646,NULL }
static const UINT64 stopWord1 [] = {0x0628,0x0639,0x062F,NULL }
static const UINT64 stopWord2 [] = {0x0636,0x062F,NULL }
static const UINT64 stopWord3 [] = {0x064A,0x0644,0x064A,NULL }
static const UINT64 stopWord4 [] = {0x0627,0x0644,0x0649,NULL }
static const UINT64 stopWord5 [] = {0x0641,0x064A,NULL }
static const UINT64 stopWord6 [] = {0x0645,0x0646,NULL }
static const UINT64 stopWord7 [] = {0x062D,0x062A,0x0649,NULL }
static const UINT64 stopWord8 [] = {0x0648,0x0647,0x0648,NULL }
static const UINT64 stopWord9 [] = {0x064A,0x0643,0x0648,0x0646,NULL }
static const UINT64 stopWord10 [] = {0x0628,0x0647,NULL }
static const UINT64 stopWord11 [] = {0x0648,0x0644,0x064A,0x0633,NULL }
static const UINT64 stopWord12 [] = {0x0623,0x062D,0x062F,NULL }
static const UINT64 stopWord13 [] = {0x0639,0x0644,0x0649,NULL }
static const UINT64 stopWord14 [] = {0x0648,0x0643,0x0627,0x0646,NULL }
static const UINT64 stopWord15 [] = {0x062A,0x0644,0x0643,NULL }
static const UINT64 stopWord16 [] = {0x0643,0x0630,0x0644,0x0643,NULL }
static const UINT64 stopWord17 [] = {0x0627,0x0644,0x062A,0x064A,NULL }
static const UINT64 stopWord18 [] = {0x0648,0x0628,0x064A,0x0646,NULL }
static const UINT64 stopWord19 [] = {0x0641,0x064A,0x0647,0x0627,NULL }
static const UINT64 stopWord20 [] = {0x0639,0x0644,0x064A,0x0647,0x0627,NULL }
static const UINT64 stopWord21 [] = {0x0625,0x0646,NULL }
static const UINT64 stopWord22 [] = {0x0648,0x0639,0x0644,0x0649,NULL }
static const UINT64 stopWord23 [] = {0x0644,0x0643,0x0646,NULL }
static const UINT64 stopWord24 [] = {0x0639,0x0646,NULL }
static const UINT64 stopWord25 [] = {0x0645,0x0633,0x0627,0x0621,NULL }
static const UINT64 stopWord26 [] = {0x0644,0x064A,0x0633,NULL }
static const UINT64 stopWord27 [] = {0x0645,0x0646,0x0630,NULL }
static const UINT64 stopWord28 [] = {0x0627,0x0644,0x0630,0x064A,NULL }
static const UINT64 stopWord29 [] = {0x0623,0x0645,0x0627,NULL }
static const UINT64 stopWord30 [] = {0x062D,0x064A,0x0646,NULL }
static const UINT64 stopWord31 [] = {0x0648,0x0645,0x0646,NULL }
static const UINT64 stopWord32 [] = {0x0644,0x0627,NULL }
static const UINT64 stopWord33 [] = {0x0644,0x064A,0x0633,0x0628,NULL }
static const UINT64 stopWord34 [] = {0x0648,0x0643,0x0627,0x0646,0x062A,NULL }
static const UINT64 stopWord35 [] = {0x0623,0x064A,NULL }
static const UINT64 stopWord36 [] = {0x0645,0x0627,NULL }
static const UINT64 stopWord37 [] = {0x0639,0x0646,0x0647,NULL }
static const UINT64 stopWord38 [] = {0x062D,0x0648,0x0644,NULL }
static const UINT64 stopWord39 [] = {0x062F,0x0648,0x0646,NULL }
static const UINT64 stopWord40 [] = {0x0645,0x0639,NULL }
static const UINT64 stopWord41 [] = {0x0644,0x0643,0x0646,0x0647,NULL }
static const UINT64 stopWord42 [] = {0x0648,0x0644,0x0643,0x0646,NULL }
static const UINT64 stopWord43 [] = {0x0644,0x0647,NULL }
static const UINT64 stopWord44 [] = {0x0647,0x0630,0x0627,NULL }
static const UINT64 stopWord45 [] = {0x0648,0x0627,0x0644,0x062A,0x064A,NULL }
static const UINT64 stopWord46 [] = {0x0641,0x0642,0x0637,NULL }
static const UINT64 stopWord47 [] = {0x062B,0x0645,NULL }
static const UINT64 stopWord48 [] = {0x0647,0x0630,0x0647,NULL }
static const UINT64 stopWord49 [] = {0x0623,0x0646,0x0647,NULL }
static const UINT64 stopWord50 [] = {0x062A,0x0643,0x0648,0x0646,NULL }
static const UINT64 stopWord51 [] = {0x0642,0x062F,NULL }
static const UINT64 stopWord52 [] = {0x0628,0x064A,0x0646,NULL }
static const UINT64 stopWord53 [] = {0x062C,0x062F,0x0627,NULL }
static const UINT64 stopWord54 [] = {0x0644,0x0646,NULL }
static const UINT64 stopWord55 [] = {0x0646,0x062D,0x0648,NULL }
static const UINT64 stopWord56 [] = {0x0643,0x0627,0x0646,NULL }
static const UINT64 stopWord57 [] = {0x0644,0x0647,0x0645,NULL }
static const UINT64 stopWord58 [] = {0x0644,0x0623,0x0646,NULL }
static const UINT64 stopWord59 [] = {0x0627,0x0644,0x064A,0x0648,0x0645,NULL }
static const UINT64 stopWord60 [] = {0x0644,0x0645,NULL }
static const UINT64 stopWord61 [] = {0x0647,0x0624,0x0644,0x0627,0x0621,NULL }
static const UINT64 stopWord62 [] = {0x0641,0x0625,0x0646,NULL }
static const UINT64 stopWord63 [] = {0x0641,0x064A,0x0647,NULL }
static const UINT64 stopWord64 [] = {0x0630,0x0644,0x0643,NULL }
static const UINT64 stopWord65 [] = {0x0644,0x0648,NULL }
static const UINT64 stopWord66 [] = {0x0639,0x0646,0x062F,NULL }
static const UINT64 stopWord67 [] = {0x0627,0x0644,0x0644,0x0630,0x064A,0x0646,NULL }
static const UINT64 stopWord68 [] = {0x0643,0x0644,NULL }
static const UINT64 stopWord69 [] = {0x0628,0x062F,NULL }
static const UINT64 stopWord70 [] = {0x0644,0x062F,0x0649,NULL }
static const UINT64 stopWord71 [] = {0x0648,0x062B,0x064A,NULL }
static const UINT64 stopWord72 [] = {0x0623,0x0646,NULL }
static const UINT64 stopWord73 [] = {0x0648,0x0645,0x0639,NULL }
static const UINT64 stopWord74 [] = {0x0641,0x0642,0x062F,NULL }
static const UINT64 stopWord75 [] = {0x0628,0x0644,NULL }
static const UINT64 stopWord76 [] = {0x0647,0x0648,NULL }
static const UINT64 stopWord77 [] = {0x0639,0x0646,0x0647,0x0627,NULL }
static const UINT64 stopWord78 [] = {0x0645,0x0646,0x0647,NULL }
static const UINT64 stopWord79 [] = {0x0628,0x0647,0x0627,NULL }
static const UINT64 stopWord80 [] = {0x0648,0x0641,0x064A,NULL }
static const UINT64 stopWord81 [] = {0x0641,0x0647,0x0648,NULL }
static const UINT64 stopWord82 [] = {0x062A,0x062D,0x062A,NULL }
static const UINT64 stopWord83 [] = {0x0644,0x0647,0x0627,NULL }
static const UINT64 stopWord84 [] = {0x0623,0x0648,NULL }
static const UINT64 stopWord85 [] = {0x0625,0x0630,NULL }
static const UINT64 stopWord86 [] = {0x0639,0x0644,0x064A,NULL }
static const UINT64 stopWord87 [] = {0x0639,0x0644,0x064A,0x0647,NULL }
static const UINT64 stopWord88 [] = {0x0643,0x0645,0x0627,NULL }
static const UINT64 stopWord89 [] = {0x0643,0x064A,0x0641,NULL }
static const UINT64 stopWord90 [] = {0x0647,0x0646,0x0627,NULL }
static const UINT64 stopWord91 [] = {0x0648,0x0642,0x062F,NULL }
static const UINT64 stopWord92 [] = {0x0643,0x0627,0x0646,0x062A,NULL }
static const UINT64 stopWord93 [] = {0x0644,0x0630,0x0644,0x0643,NULL }
static const UINT64 stopWord94 [] = {0x0623,0x0645,0x0627,0x0645,NULL }
static const UINT64 stopWord95 [] = {0x0647,0x0646,0x0627,0x0643,NULL }
static const UINT64 stopWord96 [] = {0x0642,0x0628,0x0644,NULL }
static const UINT64 stopWord97 [] = {0x0645,0x0639,0x0647,NULL }
static const UINT64 stopWord98 [] = {0x064A,0x0648,0x0645,NULL }
static const UINT64 stopWord99 [] = {0x0645,0x0646,0x0647,0x0627,NULL }
static const UINT64 stopWord100 [] = {0x0625,0x0644,0x0649,NULL }
static const UINT64 stopWord101 [] = {0x0625,0x0630,0x0627,NULL }
static const UINT64 stopWord102 [] = {0x0647,0x0644,NULL }
static const UINT64 stopWord103 [] = {0x062D,0x064A,0x062B,NULL }
static const UINT64 stopWord104 [] = {0x0647,0x064A,NULL }
static const UINT64 stopWord105 [] = {0x0627,0x0630,0x0627,NULL }
static const UINT64 stopWord106 [] = {0x0627,0x0648,NULL }
static const UINT64 stopWord107 [] = {0x0648,NULL }
static const UINT64 stopWord108 [] = {0x0645,0x0627,NULL }
static const UINT64 stopWord109 [] = {0x0644,0x0627,NULL }
static const UINT64 stopWord110 [] = {0x0627,0x0644,0x064A,NULL }
static const UINT64 stopWord111 [] = {0x0625,0x0644,0x064A,NULL }
static const UINT64 stopWord112 [] = {0x0645,0x0627,0x0632,0x0627,0x0644,NULL }
static const UINT64 stopWord113 [] = {0x0644,0x0627,0x0632,0x0627,0x0644,NULL }
static const UINT64 stopWord114 [] = {0x0644,0x0627,0x064A,0x0632,0x0627,0x0644,NULL }
static const UINT64 stopWord115 [] = {0x0645,0x0627,0x064A,0x0632,0x0627,0x0644,NULL }
static const UINT64 stopWord116 [] = {0x0627,0x0635,0x0628,0x062D,NULL }
static const UINT64 stopWord117 [] = {0x0623,0x0635,0x0628,0x062D,NULL }
static const UINT64 stopWord118 [] = {0x0623,0x0645,0x0633,0x0649,NULL }
static const UINT64 stopWord119 [] = {0x0627,0x0645,0x0633,0x0649,NULL }
static const UINT64 stopWord120 [] = {0x0623,0x0636,0x062D,0x0649,NULL }
static const UINT64 stopWord121 [] = {0x0627,0x0636,0x062D,0x0649,NULL }
static const UINT64 stopWord122 [] = {0x0638,0x0644,NULL }
static const UINT64 stopWord123 [] = {0x0645,0x0627,0x0628,0x0631,0x062D,NULL }
static const UINT64 stopWord124 [] = {0x0645,0x0627,0x0641,0x062A,0x0626,NULL }
static const UINT64 stopWord125 [] = {0x0645,0x0627,0x0627,0x0646,0x0641,0x0643,NULL }
static const UINT64 stopWord126 [] = {0x0628,0x0627,0x062A,NULL }
static const UINT64 stopWord127 [] = {0x0635,0x0627,0x0631,NULL }
static const UINT64 stopWord128 [] = {0x0644,0x064A,0x0633,NULL }
static const UINT64 stopWord129 [] = {0x0625,0x0646,NULL }
static const UINT64 stopWord130 [] = {0x0643,0x0623,0x0646,NULL }
static const UINT64 stopWord131 [] = {0x0644,0x064A,0x062A,NULL }
static const UINT64 stopWord132 [] = {0x0644,0x0639,0x0644,NULL }
static const UINT64 stopWord133 [] = {0x0644,0x0627,0x0633,0x064A,0x0645,0x0627,NULL }
static const UINT64 stopWord134 [] = {0x0648,0x0644,0x0627,0x064A,0x0632,0x0627,0x0644,NULL }
static const UINT64 stopWord135 [] = {0x0627,0x0644,0x062D,0x0627,0x0644,0x064A,NULL }
static const UINT64 stopWord136 [] = {0x0636,0x0645,0x0646,NULL }
static const UINT64 stopWord137 [] = {0x0627,0x0648,0x0644,NULL }
static const UINT64 stopWord138 [] = {0x0648,0x0644,0x0647,NULL }
static const UINT64 stopWord139 [] = {0x0630,0x0627,0x062A,NULL }
static const UINT64 stopWord140 [] = {0x0627,0x064A,NULL }
static const UINT64 stopWord141 [] = {0x0628,0x062F,0x0644,0x0627,NULL }
static const UINT64 stopWord142 [] = {0x0627,0x0644,0x064A,0x0647,0x0627,NULL }
static const UINT64 stopWord143 [] = {0x0627,0x0646,0x0647,NULL }
static const UINT64 stopWord144 [] = {0x0627,0x0644,0x0630,0x064A,0x0646,NULL }
static const UINT64 stopWord145 [] = {0x0641,0x0627,0x0646,0x0647,NULL }
static const UINT64 stopWord146 [] = {0x0648,0x0627,0x0646,NULL }
static const UINT64 stopWord147 [] = {0x0648,0x0627,0x0644,0x0630,0x064A,NULL }
static const UINT64 stopWord148 [] = {0x0648,0x0647,0x0630,0x0627,NULL }
static const UINT64 stopWord149 [] = {0x0644,0x0647,0x0630,0x0627,NULL }
static const UINT64 stopWord150 [] = {0x0627,0x0644,0x0627,NULL }
static const UINT64 stopWord151 [] = {0x0641,0x0643,0x0627,0x0646,NULL }
static const UINT64 stopWord152 [] = {0x0633,0x062A,0x0643,0x0648,0x0646,NULL }
static const UINT64 stopWord153 [] = {0x0645,0x0645,0x0627,NULL }
static const UINT64 stopWord154 [] = {0x0623,0x0628,0x0648,NULL }
static const UINT64 stopWord155 [] = {0x0628,0x0625,0x0646,NULL }
static const UINT64 stopWord156 [] = {0x0627,0x0644,0x0630,0x064A,NULL }
static const UINT64 stopWord157 [] = {0x0627,0x0644,0x064A,0x0647,NULL }
static const UINT64 stopWord158 [] = {0x064A,0x0645,0x0643,0x0646,NULL }
static const UINT64 stopWord159 [] = {0x0628,0x0647,0x0630,0x0627,NULL }
static const UINT64 stopWord160 [] = {0x0644,0x062F,0x064A,NULL }
static const UINT64 stopWord161 [] = {0x0648,0x0623,0x0646,NULL }
static const UINT64 stopWord162 [] = {0x0648,0x0647,0x064A,NULL }
static const UINT64 stopWord163 [] = {0x0648,0x0623,0x0628,0x0648,NULL }
static const UINT64 stopWord164 [] = {0x0622,0x0644,NULL }
static const UINT64 stopWord165 [] = {0x0627,0x0644,0x0630,0x064A,NULL }
static const UINT64 stopWord166 [] = {0x0647,0x0646,NULL }
static const UINT64 stopWord167 [] = {0x0627,0x0644,0x0630,0x0649,NULL }
static UINT64 allArabicChars []
static UINT64 normChars []
static UINT64 norm3Chars []
static UINT64 arabicVowelChars []
Member Typedef Documentation
typedef hash_map<UINT64, UINT64, uint64Hasher, eqstr> indri::parse::Arabic_Stemmer_utf8::transitionTable [private]
Constructor & Destructor Documentation
indri::parse::Arabic_Stemmer_utf8::Arabic_Stemmer_utf8 (std::string stemFunc)
References allStopWords, createStemmerTransitionTables(), NUMSTEMMERS, indri::parse::Arabic_Stemmer_utf8::stem_info_u_t::stem_fct_unicode, stem_fct_unicode, stemtable_unicode, and stop_words_set_unicode.
indri::parse::Arabic_Stemmer_utf8::~Arabic_Stemmer_utf8 ()
Member Function Documentation
void indri::parse::Arabic_Stemmer_utf8::arabic_light10_stop_unicode (UINT64 * word, UINT64 * result) [private]
References arabic_norm2_unicode(), CHAR_NULL, CHAR_WAW, on_stop_list_unicode(), remove_all_suffixes_unicode(), remove_definite_articles_unicode(), indri::parse::Uint64Comp::u_strcpy(), indri::parse::Uint64Comp::u_strdup(), and indri::parse::Uint64Comp::u_strlen().
void indri::parse::Arabic_Stemmer_utf8::arabic_light10_unicode (UINT64 * word, UINT64 * result) [private]
References arabic_norm2_unicode(), CHAR_NULL, CHAR_WAW, remove_all_suffixes_unicode(), remove_definite_articles_unicode(), indri::parse::Uint64Comp::u_strcpy(), indri::parse::Uint64Comp::u_strdup(), and indri::parse::Uint64Comp::u_strlen().
void indri::parse::Arabic_Stemmer_utf8::arabic_norm2_stop_unicode (UINT64 * word, UINT64 * result) [private]
References arabic_norm2_unicode(), CHAR_NULL, and on_stop_list_unicode().
void indri::parse::Arabic_Stemmer_utf8::arabic_norm2_unicode (UINT64 * word, UINT64 * result) [private]
References ARABIC_RANGE_HIGH, CHAR_NULL, and normCharTable.
Referenced by arabic_light10_stop_unicode(), arabic_light10_unicode(), and arabic_norm2_stop_unicode().
void indri::parse::Arabic_Stemmer_utf8::arabic_stop_unicode (UINT64 * word, UINT64 * result) [private]
References CHAR_NULL, on_stop_list_unicode(), and indri::parse::Uint64Comp::u_strcpy().
void indri::parse::Arabic_Stemmer_utf8::createStemmerTransitionTables () [private]
References allArabicChars, arabicVowelChars, arabicVowelTable, norm3Chars, norm3CharTable, normChars, and normCharTable.
Referenced by Arabic_Stemmer_utf8().
void indri::parse::Arabic_Stemmer_utf8::no_stem_unicode (UINT64 * word, UINT64 * result) [private]
References indri::parse::Uint64Comp::u_strcpy().
bool indri::parse::Arabic_Stemmer_utf8::on_stop_list_unicode (UINT64 * word) [private]
References stop_words_set_unicode.
Referenced by arabic_light10_stop_unicode(), arabic_norm2_stop_unicode(), and arabic_stop_unicode().
void indri::parse::Arabic_Stemmer_utf8::remove_all_suffixes_unicode (UINT64 * word, UINT64 * result, size_t lenlimit) [private]
References allSuffixes, CHAR_NULL, indri::parse::Uint64Comp::u_strcpy(), indri::parse::Uint64Comp::u_strlen(), and indri::parse::Uint64Comp::u_strncmp().
Referenced by arabic_light10_stop_unicode(), and arabic_light10_unicode().
void indri::parse::Arabic_Stemmer_utf8::remove_definite_articles_unicode (UINT64 * word, UINT64 * result) [private]
References allDefArticles, indri::parse::Uint64Comp::u_strcpy(), indri::parse::Uint64Comp::u_strlen(), and indri::parse::Uint64Comp::u_strncmp().
Referenced by arabic_light10_stop_unicode(), and arabic_light10_unicode().
void indri::parse::Arabic_Stemmer_utf8::stemTerm (char * word, char * result)
References _transcoder, stem_fct_unicode, indri::parse::UTF8Transcoder::utf8_decode(), and indri::parse::UTF8Transcoder::utf8_encode().
Referenced by indri::parse::ArabicStemmerTransformation::_processTerms().
Member Data Documentation
UTF8Transcoder indri::parse::Arabic_Stemmer_utf8::_transcoder [private]
Referenced by stemTerm().
UINT64 indri::parse::Arabic_Stemmer_utf8::allArabicChars [static, private]
Referenced by createStemmerTransitionTables().
const UINT64 * indri::parse::Arabic_Stemmer_utf8::allDefArticles = {defArticle0,defArticle1,defArticle2,defArticle3,defArticle4,defArticle5,NULL} [static, private]
Referenced by remove_definite_articles_unicode().
const UINT64 * indri::parse::Arabic_Stemmer_utf8::allStopWords = {stopWord0,stopWord1,stopWord2,stopWord3,stopWord4,stopWord5,stopWord6,stopWord7,stopWord8,stopWord9,stopWord10,stopWord11,stopWord12,stopWord13,stopWord14,stopWord15,stopWord16,stopWord17,stopWord18,stopWord19,stopWord20,stopWord21,stopWord22,stopWord23,stopWord24,stopWord25,stopWord26,stopWord27,stopWord28,stopWord29,stopWord30,stopWord31,stopWord32,stopWord33,stopWord34,stopWord35,stopWord36,stopWord37,stopWord38,stopWord39,stopWord40,stopWord41,stopWord42,stopWord43,stopWord44,stopWord45,stopWord46,stopWord47,stopWord48,stopWord49,stopWord50,stopWord51,stopWord52,stopWord53,stopWord54,stopWord55,stopWord56,stopWord57,stopWord58,stopWord59,stopWord60,stopWord61,stopWord62,stopWord63,stopWord64,stopWord65,stopWord66,stopWord67,stopWord68,stopWord69,stopWord70,stopWord71,stopWord72,stopWord73,stopWord74,stopWord75,stopWord76,stopWord77,stopWord78,stopWord79,stopWord80,stopWord81,stopWord82,stopWord83,stopWord84,stopWord85,stopWord86,stopWord87,stopWord88,stopWord89,stopWord90,stopWord91,stopWord92,stopWord93,stopWord94,stopWord95,stopWord96,stopWord97,stopWord98,stopWord99,stopWord100,stopWord101,stopWord102,stopWord103,stopWord104,stopWord105,stopWord106,stopWord107,stopWord108,stopWord109,stopWord110,stopWord111,stopWord112,stopWord113,stopWord114,stopWord115,stopWord116,stopWord117,stopWord118,stopWord119,stopWord120,stopWord121,stopWord122,stopWord123,stopWord124,stopWord125,stopWord126,stopWord127,stopWord128,stopWord129,stopWord130,stopWord131,stopWord132,stopWord133,stopWord134,stopWord135,stopWord136,stopWord137,stopWord138,stopWord139,stopWord140,stopWord141,stopWord142,stopWord143,stopWord144,stopWord145,stopWord146,stopWord147,stopWord148,stopWord149,stopWord150,stopWord151,stopWord152,stopWord153,stopWord154,stopWord155,stopWord156,stopWord157,stopWord158,stopWord159,stopWord160,stopWord161,stopWord162,stopWord163,stopWord164,stopWord165,stopWord166,stopWord167,NULL} [static, private]
Referenced by Arabic_Stemmer_utf8().
const UINT64 * indri::parse::Arabic_Stemmer_utf8::allSuffixes = {suffix0,suffix1,suffix2,suffix3,suffix4,suffix5,suffix6,suffix7,suffix8,suffix9,NULL} [static, private]
Referenced by remove_all_suffixes_unicode().
UINT64 indri::parse::Arabic_Stemmer_utf8::arabicVowelChars [static, private]
Referenced by createStemmerTransitionTables().
transitionTable indri::parse::Arabic_Stemmer_utf8::arabicVowelTable [private]
Referenced by createStemmerTransitionTables().
const UINT64 indri::parse::Arabic_Stemmer_utf8::defArticle0 = {0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::defArticle1 = {0x0648,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::defArticle2 = {0x0628,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::defArticle3 = {0x0643,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::defArticle4 = {0x0641,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::defArticle5 = {0x0644,0x0644,NULL } [static, private]
UINT64 indri::parse::Arabic_Stemmer_utf8::norm3Chars [static, private]
Referenced by createStemmerTransitionTables().
transitionTable indri::parse::Arabic_Stemmer_utf8::norm3CharTable [private]
Referenced by createStemmerTransitionTables().
UINT64 indri::parse::Arabic_Stemmer_utf8::normChars [static, private]
Referenced by createStemmerTransitionTables().
transitionTable indri::parse::Arabic_Stemmer_utf8::normCharTable [private]
Referenced by arabic_norm2_unicode(), and createStemmerTransitionTables().
void(Arabic_Stemmer_utf8::* indri::parse::Arabic_Stemmer_utf8::stem_fct_unicode)(UINT64 *, UINT64 *) [private]
Referenced by Arabic_Stemmer_utf8(), and stemTerm().
Arabic_Stemmer_utf8::stem_info_u_t indri::parse::Arabic_Stemmer_utf8::stemtable_unicode [static, private]
Initial value:
 {
      {"none", &Arabic_Stemmer_utf8::no_stem_unicode},
      {"arabic_stop", &Arabic_Stemmer_utf8::arabic_stop_unicode},
      {"arabic_norm2", &Arabic_Stemmer_utf8::arabic_norm2_unicode},
      {"arabic_norm2_stop", &Arabic_Stemmer_utf8::arabic_norm2_stop_unicode},
      {"arabic_light10", &Arabic_Stemmer_utf8::arabic_light10_unicode},
      {"arabic_light10_stop", &Arabic_Stemmer_utf8::arabic_light10_stop_unicode}
    }
Referenced by Arabic_Stemmer_utf8().
std::set<const UINT64 *, ltstr_unicode> indri::parse::Arabic_Stemmer_utf8::stop_words_set_unicode [private]
Referenced by Arabic_Stemmer_utf8(), and on_stop_list_unicode().
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord0 = {0x0627,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord1 = {0x0628,0x0639,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord10 = {0x0628,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord100 = {0x0625,0x0644,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord101 = {0x0625,0x0630,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord102 = {0x0647,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord103 = {0x062D,0x064A,0x062B,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord104 = {0x0647,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord105 = {0x0627,0x0630,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord106 = {0x0627,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord107 = {0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord108 = {0x0645,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord109 = {0x0644,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord11 = {0x0648,0x0644,0x064A,0x0633,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord110 = {0x0627,0x0644,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord111 = {0x0625,0x0644,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord112 = {0x0645,0x0627,0x0632,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord113 = {0x0644,0x0627,0x0632,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord114 = {0x0644,0x0627,0x064A,0x0632,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord115 = {0x0645,0x0627,0x064A,0x0632,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord116 = {0x0627,0x0635,0x0628,0x062D,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord117 = {0x0623,0x0635,0x0628,0x062D,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord118 = {0x0623,0x0645,0x0633,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord119 = {0x0627,0x0645,0x0633,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord12 = {0x0623,0x062D,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord120 = {0x0623,0x0636,0x062D,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord121 = {0x0627,0x0636,0x062D,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord122 = {0x0638,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord123 = {0x0645,0x0627,0x0628,0x0631,0x062D,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord124 = {0x0645,0x0627,0x0641,0x062A,0x0626,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord125 = {0x0645,0x0627,0x0627,0x0646,0x0641,0x0643,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord126 = {0x0628,0x0627,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord127 = {0x0635,0x0627,0x0631,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord128 = {0x0644,0x064A,0x0633,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord129 = {0x0625,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord13 = {0x0639,0x0644,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord130 = {0x0643,0x0623,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord131 = {0x0644,0x064A,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord132 = {0x0644,0x0639,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord133 = {0x0644,0x0627,0x0633,0x064A,0x0645,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord134 = {0x0648,0x0644,0x0627,0x064A,0x0632,0x0627,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord135 = {0x0627,0x0644,0x062D,0x0627,0x0644,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord136 = {0x0636,0x0645,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord137 = {0x0627,0x0648,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord138 = {0x0648,0x0644,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord139 = {0x0630,0x0627,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord14 = {0x0648,0x0643,0x0627,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord140 = {0x0627,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord141 = {0x0628,0x062F,0x0644,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord142 = {0x0627,0x0644,0x064A,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord143 = {0x0627,0x0646,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord144 = {0x0627,0x0644,0x0630,0x064A,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord145 = {0x0641,0x0627,0x0646,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord146 = {0x0648,0x0627,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord147 = {0x0648,0x0627,0x0644,0x0630,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord148 = {0x0648,0x0647,0x0630,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord149 = {0x0644,0x0647,0x0630,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord15 = {0x062A,0x0644,0x0643,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord150 = {0x0627,0x0644,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord151 = {0x0641,0x0643,0x0627,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord152 = {0x0633,0x062A,0x0643,0x0648,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord153 = {0x0645,0x0645,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord154 = {0x0623,0x0628,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord155 = {0x0628,0x0625,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord156 = {0x0627,0x0644,0x0630,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord157 = {0x0627,0x0644,0x064A,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord158 = {0x064A,0x0645,0x0643,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord159 = {0x0628,0x0647,0x0630,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord16 = {0x0643,0x0630,0x0644,0x0643,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord160 = {0x0644,0x062F,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord161 = {0x0648,0x0623,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord162 = {0x0648,0x0647,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord163 = {0x0648,0x0623,0x0628,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord164 = {0x0622,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord165 = {0x0627,0x0644,0x0630,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord166 = {0x0647,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord167 = {0x0627,0x0644,0x0630,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord17 = {0x0627,0x0644,0x062A,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord18 = {0x0648,0x0628,0x064A,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord19 = {0x0641,0x064A,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord2 = {0x0636,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord20 = {0x0639,0x0644,0x064A,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord21 = {0x0625,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord22 = {0x0648,0x0639,0x0644,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord23 = {0x0644,0x0643,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord24 = {0x0639,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord25 = {0x0645,0x0633,0x0627,0x0621,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord26 = {0x0644,0x064A,0x0633,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord27 = {0x0645,0x0646,0x0630,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord28 = {0x0627,0x0644,0x0630,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord29 = {0x0623,0x0645,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord3 = {0x064A,0x0644,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord30 = {0x062D,0x064A,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord31 = {0x0648,0x0645,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord32 = {0x0644,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord33 = {0x0644,0x064A,0x0633,0x0628,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord34 = {0x0648,0x0643,0x0627,0x0646,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord35 = {0x0623,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord36 = {0x0645,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord37 = {0x0639,0x0646,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord38 = {0x062D,0x0648,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord39 = {0x062F,0x0648,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord4 = {0x0627,0x0644,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord40 = {0x0645,0x0639,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord41 = {0x0644,0x0643,0x0646,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord42 = {0x0648,0x0644,0x0643,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord43 = {0x0644,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord44 = {0x0647,0x0630,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord45 = {0x0648,0x0627,0x0644,0x062A,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord46 = {0x0641,0x0642,0x0637,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord47 = {0x062B,0x0645,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord48 = {0x0647,0x0630,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord49 = {0x0623,0x0646,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord5 = {0x0641,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord50 = {0x062A,0x0643,0x0648,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord51 = {0x0642,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord52 = {0x0628,0x064A,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord53 = {0x062C,0x062F,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord54 = {0x0644,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord55 = {0x0646,0x062D,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord56 = {0x0643,0x0627,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord57 = {0x0644,0x0647,0x0645,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord58 = {0x0644,0x0623,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord59 = {0x0627,0x0644,0x064A,0x0648,0x0645,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord6 = {0x0645,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord60 = {0x0644,0x0645,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord61 = {0x0647,0x0624,0x0644,0x0627,0x0621,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord62 = {0x0641,0x0625,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord63 = {0x0641,0x064A,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord64 = {0x0630,0x0644,0x0643,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord65 = {0x0644,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord66 = {0x0639,0x0646,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord67 = {0x0627,0x0644,0x0644,0x0630,0x064A,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord68 = {0x0643,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord69 = {0x0628,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord7 = {0x062D,0x062A,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord70 = {0x0644,0x062F,0x0649,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord71 = {0x0648,0x062B,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord72 = {0x0623,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord73 = {0x0648,0x0645,0x0639,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord74 = {0x0641,0x0642,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord75 = {0x0628,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord76 = {0x0647,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord77 = {0x0639,0x0646,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord78 = {0x0645,0x0646,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord79 = {0x0628,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord8 = {0x0648,0x0647,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord80 = {0x0648,0x0641,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord81 = {0x0641,0x0647,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord82 = {0x062A,0x062D,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord83 = {0x0644,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord84 = {0x0623,0x0648,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord85 = {0x0625,0x0630,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord86 = {0x0639,0x0644,0x064A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord87 = {0x0639,0x0644,0x064A,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord88 = {0x0643,0x0645,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord89 = {0x0643,0x064A,0x0641,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord9 = {0x064A,0x0643,0x0648,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord90 = {0x0647,0x0646,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord91 = {0x0648,0x0642,0x062F,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord92 = {0x0643,0x0627,0x0646,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord93 = {0x0644,0x0630,0x0644,0x0643,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord94 = {0x0623,0x0645,0x0627,0x0645,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord95 = {0x0647,0x0646,0x0627,0x0643,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord96 = {0x0642,0x0628,0x0644,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord97 = {0x0645,0x0639,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord98 = {0x064A,0x0648,0x0645,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::stopWord99 = {0x0645,0x0646,0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix0 = {0x0647,0x0627,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix1 = {0x0627,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix2 = {0x0627,0x062A,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix3 = {0x0648,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix4 = {0x064A,0x0646,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix5 = {0x064A,0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix6 = {0x064A,0x0629,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix7 = {0x0647,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix8 = {0x0629,NULL } [static, private]
const UINT64 indri::parse::Arabic_Stemmer_utf8::suffix9 = {0x064A,NULL } [static, private]
The documentation for this class was generated from the following files:
Arabic_Stemmer_utf8.hpp
Arabic_Stemmer_utf8.cpp