Indri: indri::lang::ExtentRestriction Class Reference
indri::lang::ExtentRestriction Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ExtentRestriction (Unpacker &unpacker)
ExtentRestriction (ScoredExtentNode *child, RawExtentNode *field)
virtual std::string typeName () const
std::string queryText () const
virtual UINT64 hashCode () const
ScoredExtentNode * getChild ()
RawExtentNode * getField ()
void setChild (ScoredExtentNode *child)
void setField (RawExtentNode *field)
void pack (Packer &packer)
void walk (Walker &walker)
virtual Node * copy (Copier &copier)
Protected Attributes
ScoredExtentNode * _child
RawExtentNode * _field
Constructor & Destructor Documentation
indri::lang::ExtentRestriction::ExtentRestriction (Unpacker & unpacker) [inline]
References _child, _field, indri::lang::Unpacker::getRawExtentNode(), and indri::lang::Unpacker::getScoredExtentNode().
Referenced by copy().
indri::lang::ExtentRestriction::ExtentRestriction (ScoredExtentNode * child, RawExtentNode * field) [inline]
Member Function Documentation
virtual Node* indri::lang::ExtentRestriction::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::ExtentEnforcement.
References _child, _field, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), ExtentRestriction(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
ScoredExtentNode* indri::lang::ExtentRestriction::getChild () [inline]
References _child.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), and indri::lang::NoContextCountGraphCopier::after().
RawExtentNode* indri::lang::ExtentRestriction::getField () [inline]
References _field.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), and QueryParser::innerMost().
virtual UINT64 indri::lang::ExtentRestriction::hashCode () const [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::ExtentEnforcement.
References _child, _field, and indri::lang::Node::hashCode().
void indri::lang::ExtentRestriction::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _child, _field, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ExtentRestriction::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _child, _field, and indri::lang::Node::queryText().
void indri::lang::ExtentRestriction::setChild (ScoredExtentNode * child) [inline]
References _child.
void indri::lang::ExtentRestriction::setField (RawExtentNode * field) [inline]
References _field.
virtual std::string indri::lang::ExtentRestriction::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
Reimplemented in indri::lang::ExtentEnforcement.
void indri::lang::ExtentRestriction::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _child, _field, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::ExtentRestriction::_child [protected]
Referenced by indri::lang::ExtentEnforcement::copy(), copy(), ExtentRestriction(), getChild(), indri::lang::ExtentEnforcement::hashCode(), hashCode(), pack(), queryText(), setChild(), and walk().
RawExtentNode* indri::lang::ExtentRestriction::_field [protected]
Referenced by indri::lang::ExtentEnforcement::copy(), copy(), ExtentRestriction(), getField(), indri::lang::ExtentEnforcement::hashCode(), hashCode(), pack(), queryText(), setField(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp