Indri: indri::index::DiskFrequentVocabularyIterator Class Reference
indri::index::DiskFrequentVocabularyIterator Class Reference
#include <DiskFrequentVocabularyIterator.hpp>
Public Member Functions
DiskFrequentVocabularyIterator (indri::file::File &frequentTermsData, int fieldCount)
~DiskFrequentVocabularyIterator ()
void startIteration ()
bool finished ()
bool nextEntry ()
bool nextEntry (const char *skipTo)
DiskTermData * currentEntry ()
Private Attributes
indri::file::File & _file
indri::utility::RVLDecompressStream _stream
indri::utility::Buffer _buffer
const char * _current
int _fieldCount
bool _finished
DiskTermData * _data
char * _dataBuffer
bool _justStartedIteration
Constructor & Destructor Documentation
indri::index::DiskFrequentVocabularyIterator::DiskFrequentVocabularyIterator (indri::file::File & frequentTermsData, int fieldCount)
References _dataBuffer, _fieldCount, and disktermdata_size().
indri::index::DiskFrequentVocabularyIterator::~DiskFrequentVocabularyIterator () [inline]
References _dataBuffer.
Member Function Documentation
indri::index::DiskTermData * indri::index::DiskFrequentVocabularyIterator::currentEntry () [virtual]
Implements indri::index::VocabularyIterator.
References _data, and _finished.
bool indri::index::DiskFrequentVocabularyIterator::finished () [virtual]
Implements indri::index::VocabularyIterator.
References _finished.
bool indri::index::DiskFrequentVocabularyIterator::nextEntry (const char * skipTo) [virtual]
Implements indri::index::VocabularyIterator.
References _data, _dataBuffer, _fieldCount, _finished, _justStartedIteration, _stream, disktermdata_decompress(), indri::utility::RVLDecompressStream::done(), startIteration(), indri::index::TermData::term, indri::index::DiskTermData::termData, indri::index::DiskTermData::WithOffsets, indri::index::DiskTermData::WithString, and indri::index::DiskTermData::WithTermID.
bool indri::index::DiskFrequentVocabularyIterator::nextEntry () [virtual]
Implements indri::index::VocabularyIterator.
References _data, _dataBuffer, _fieldCount, _finished, _justStartedIteration, _stream, disktermdata_decompress(), indri::utility::RVLDecompressStream::done(), indri::index::DiskTermData::WithOffsets, indri::index::DiskTermData::WithString, and indri::index::DiskTermData::WithTermID.
Referenced by startIteration().
void indri::index::DiskFrequentVocabularyIterator::startIteration () [virtual]
Implements indri::index::VocabularyIterator.
References _buffer, _file, _finished, _justStartedIteration, _stream, indri::utility::Buffer::front(), nextEntry(), indri::utility::Buffer::position(), indri::file::File::read(), indri::utility::RVLDecompressStream::setBuffer(), indri::file::File::size(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
Referenced by nextEntry().
Member Data Documentation
indri::utility::Buffer indri::index::DiskFrequentVocabularyIterator::_buffer [private]
Referenced by startIteration().
const char* indri::index::DiskFrequentVocabularyIterator::_current [private]
DiskTermData* indri::index::DiskFrequentVocabularyIterator::_data [private]
Referenced by currentEntry(), and nextEntry().
char* indri::index::DiskFrequentVocabularyIterator::_dataBuffer [private]
Referenced by DiskFrequentVocabularyIterator(), nextEntry(), and ~DiskFrequentVocabularyIterator().
int indri::index::DiskFrequentVocabularyIterator::_fieldCount [private]
Referenced by DiskFrequentVocabularyIterator(), and nextEntry().
indri::file::File& indri::index::DiskFrequentVocabularyIterator::_file [private]
Referenced by startIteration().
bool indri::index::DiskFrequentVocabularyIterator::_finished [private]
Referenced by currentEntry(), finished(), nextEntry(), and startIteration().
bool indri::index::DiskFrequentVocabularyIterator::_justStartedIteration [private]
Referenced by nextEntry(), and startIteration().
indri::utility::RVLDecompressStream indri::index::DiskFrequentVocabularyIterator::_stream [private]
Referenced by nextEntry(), and startIteration().
The documentation for this class was generated from the following files:
DiskFrequentVocabularyIterator.hpp
DiskFrequentVocabularyIterator.cpp