Indri: indri::parse::PDFDocumentExtractor Class Reference
indri::parse::PDFDocumentExtractor Class Reference
#include <PDFDocumentExtractor.hpp>
Public Member Functions
PDFDocumentExtractor ()
~PDFDocumentExtractor ()
void open (const std::string &filename)
UnparsedDocument * nextDocument ()
void appendPdfMetaData (indri::xml::XMLNode *node)
void seekValue (indri::xml::XMLNode *node, std::string &metaTag)
void close ()
Private Attributes
indri::utility::Buffer _documentTextBuffer
UnparsedDocument _unparsedDocument
std::string _documentPath
std::string _title
std::string _author
Constructor & Destructor Documentation
indri::parse::PDFDocumentExtractor::PDFDocumentExtractor ()
References _author, and _title.
indri::parse::PDFDocumentExtractor::~PDFDocumentExtractor ()
Member Function Documentation
void indri::parse::PDFDocumentExtractor::appendPdfMetaData (indri::xml::XMLNode * node)
References _author, _title, indri::xml::XMLNode::getChildren(), indri::xml::XMLNode::getName(), and seekValue().
Referenced by nextDocument().
void indri::parse::PDFDocumentExtractor::close () [virtual]
Implements indri::parse::DocumentIterator.
References _documentPath.
indri::parse::UnparsedDocument * indri::parse::PDFDocumentExtractor::nextDocument () [virtual]
Implements indri::parse::DocumentIterator.
References _author, indri::parse::DocumentIterator::_docnostring, _documentPath, _documentTextBuffer, _title, _unparsedDocument, appendPdfMetaData(), buffer_write(), indri::parse::DocumentIterator::cleanDocno(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::parse::UnparsedDocument::content, indri::parse::UnparsedDocument::contentLength, indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::parse::UnparsedDocument::metadata, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::xml::XMLReader::read(), indri::parse::UnparsedDocument::text, indri::parse::UnparsedDocument::textLength, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
void indri::parse::PDFDocumentExtractor::open (const std::string & filename) [virtual]
Implements indri::parse::DocumentIterator.
References _documentPath, _documentTextBuffer, and indri::utility::Buffer::clear().
void indri::parse::PDFDocumentExtractor::seekValue (indri::xml::XMLNode * node, std::string & metaTag)
References indri::xml::XMLNode::getChildren(), and indri::xml::XMLNode::getValue().
Referenced by appendPdfMetaData().
Member Data Documentation
std::string indri::parse::PDFDocumentExtractor::_author [private]
Referenced by appendPdfMetaData(), nextDocument(), and PDFDocumentExtractor().
std::string indri::parse::PDFDocumentExtractor::_documentPath [private]
Referenced by close(), nextDocument(), and open().
indri::utility::Buffer indri::parse::PDFDocumentExtractor::_documentTextBuffer [private]
Referenced by nextDocument(), and open().
std::string indri::parse::PDFDocumentExtractor::_title [private]
Referenced by appendPdfMetaData(), nextDocument(), and PDFDocumentExtractor().
UnparsedDocument indri::parse::PDFDocumentExtractor::_unparsedDocument [private]
Referenced by nextDocument().
The documentation for this class was generated from the following files:
PDFDocumentExtractor.hpp
PDFDocumentExtractor.cpp