Indri: indri::collection::PriorListIterator Class Reference
indri::collection::PriorListIterator Class Reference
#include <PriorListIterator.hpp>
Classes
struct Entry
Public Member Functions
PriorListIterator (indri::file::SequentialReadBuffer *file)
~PriorListIterator ()
void startIteration ()
void nextEntry ()
void nextEntry (lemur::api::DOCID_T document)
Entry * currentEntry ()
bool finished ()
Private Attributes
indri::file::SequentialReadBuffer * _file
Entry _entry
indri::utility::greedy_vector
< double > _lookup
bool _finished
UINT32 _entryCount
UINT32 _entryLength
UINT32 _tableLength
Constructor & Destructor Documentation
indri::collection::PriorListIterator::PriorListIterator (indri::file::SequentialReadBuffer * file)
indri::collection::PriorListIterator::~PriorListIterator ()
References _file.
Member Function Documentation
indri::collection::PriorListIterator::Entry * indri::collection::PriorListIterator::currentEntry ()
References _entry, and _finished.
Referenced by indri::infnet::PriorNode::score().
bool indri::collection::PriorListIterator::finished ()
References _finished.
Referenced by indri::infnet::PriorNode::score().
void indri::collection::PriorListIterator::nextEntry (lemur::api::DOCID_T document)
References _entry, _entryCount, _entryLength, _file, _finished, _tableLength, indri::collection::PriorListIterator::Entry::document, nextEntry(), and indri::file::SequentialReadBuffer::seek().
void indri::collection::PriorListIterator::nextEntry ()
References _entry, _entryCount, _file, _finished, _lookup, _tableLength, indri::collection::PriorListIterator::Entry::document, indri::file::SequentialReadBuffer::read(), and indri::collection::PriorListIterator::Entry::score.
Referenced by nextEntry(), and startIteration().
void indri::collection::PriorListIterator::startIteration ()
References _entry, _entryCount, _entryLength, _file, _finished, _lookup, _tableLength, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::collection::PriorListIterator::Entry::document, nextEntry(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::file::SequentialReadBuffer::read(), and indri::file::SequentialReadBuffer::seek().
Referenced by indri::infnet::InferenceNetwork::_indexChanged().
Member Data Documentation
Entry indri::collection::PriorListIterator::_entry [private]
Referenced by currentEntry(), nextEntry(), and startIteration().
UINT32 indri::collection::PriorListIterator::_entryCount [private]
Referenced by nextEntry(), and startIteration().
UINT32 indri::collection::PriorListIterator::_entryLength [private]
Referenced by nextEntry(), and startIteration().
indri::file::SequentialReadBuffer* indri::collection::PriorListIterator::_file [private]
Referenced by nextEntry(), startIteration(), and ~PriorListIterator().
bool indri::collection::PriorListIterator::_finished [private]
Referenced by currentEntry(), finished(), nextEntry(), and startIteration().
indri::utility::greedy_vector<double> indri::collection::PriorListIterator::_lookup [private]
Referenced by nextEntry(), and startIteration().
UINT32 indri::collection::PriorListIterator::_tableLength [private]
Referenced by nextEntry(), and startIteration().
The documentation for this class was generated from the following files:
PriorListIterator.hpp
PriorListIterator.cpp