Indri: indri::lang::FieldWildcard Class Reference
indri::lang::FieldWildcard Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FieldWildcard ()
FieldWildcard (Unpacker &unpacker)
bool operator== (Node &o)
std::string typeName () const
std::string queryText () const
void pack (Packer &packer)
void walk (Walker &walker)
UINT64 hashCode () const
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::FieldWildcard::FieldWildcard () [inline]
indri::lang::FieldWildcard::FieldWildcard (Unpacker & unpacker) [inline]
Member Function Documentation
Node* indri::lang::FieldWildcard::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
UINT64 indri::lang::FieldWildcard::hashCode () const [inline, virtual]
Implements indri::lang::Node.
bool indri::lang::FieldWildcard::operator== (Node & o) [inline]
void indri::lang::FieldWildcard::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Packer::after(), and indri::lang::Packer::before().
std::string indri::lang::FieldWildcard::queryText () const [inline, virtual]
Implements indri::lang::Node.
std::string indri::lang::FieldWildcard::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FieldWildcard::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
The documentation for this class was generated from the following file:
QuerySpec.hpp