Indri: indri::api::QueryEnvironment Class Reference
indri::api::QueryEnvironment Class Reference
Principal class for interacting with Indri indexes during retrieval. Provides the API for opening one or more Repository servers, either local or remote. Provides the API for querying the servers with the Indri query language, and additionally requesting aggregate collection statistics.
#include <QueryEnvironment.hpp>
Public Member Functions
QueryEnvironment ()
~QueryEnvironment ()
void setMemory (UINT64 memory)
Set the amount of memory to use.
void setBaseline (const std::string &baseline)
Set whether there should be one single background model or context sensitive models.
void setSingleBackgroundModel (bool background)
void setScoringRules (const std::vector< std::string > &rules)
Set the scoring rules.
void setStopwords (const std::vector< std::string > &stopwords)
Set the stopword list for query processing.
void addServer (const std::string &hostname)
Add a remote server.
void addIndex (const std::string &pathname)
Add a local repository.
void addIndex (class IndexEnvironment &environment)
void close ()
Close the QueryEnvironment.
void removeServer (const std::string &hostname)
Remove a remote server.
void removeIndex (const std::string &pathname)
Remove a local repository.
QueryResults runQuery (QueryRequest &request)
Run an Indri query language query.
std::vector
< indri::api::ScoredExtentResult > runQuery (const std::string &query, int resultsRequested, const std::string &queryType="indri")
Run an Indri query language query.
std::vector
< indri::api::ScoredExtentResult > runQuery (const std::string &query, const std::vector< lemur::api::DOCID_T > &documentSet, int resultsRequested, const std::string &queryType="indri")
Run an Indri query language query.
QueryAnnotation * runAnnotatedQuery (const std::string &query, int resultsRequested, const std::string &queryType="indri")
Run an Indri query language query.
QueryAnnotation * runAnnotatedQuery (const std::string &query, const std::vector< lemur::api::DOCID_T > &documentSet, int resultsRequested, const std::string &queryType="indri")
Run an Indri query language query.
std::vector
< indri::api::ParsedDocument * > documents (const std::vector< lemur::api::DOCID_T > &documentIDs)
Fetch the parsed documents for a given list of document ids. Caller is responsible for deleting the returned elements.
std::vector
< indri::api::ParsedDocument * > documents (const std::vector< indri::api::ScoredExtentResult > &results)
Fetch the parsed documents for a given list of ScoredExtentResults Caller is responsible for deleting the returned elements.
std::vector< std::string > documentMetadata (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::string &attributeName)
Fetch the named metadata attribute for a list of document ids.
std::vector< std::string > documentMetadata (const std::vector< indri::api::ScoredExtentResult > &documentIDs, const std::string &attributeName)
Fetch the named metadata attribute for a list of ScoredExtentResults.
std::vector< std::string > pathNames (const std::vector< indri::api::ScoredExtentResult > &results)
Fetch the XPath names of extents for a list of ScoredExtentResults.
std::vector
< indri::api::ParsedDocument * > documentsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)
Fetch all documents with a metadata key that matches attributeName, with a value matching one of the attributeValues.
std::vector< lemur::api::DOCID_T > documentIDsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValue)
Return a list of document IDs where the document has a metadata key that matches attributeName, with a value matching one of the attributeValues.
std::string stemTerm (const std::string &term)
Return the stem of the term.
INT64 termCountUnique ()
Return total number of unique terms.
INT64 termCount ()
Return total number of terms.
INT64 termCount (const std::string &term)
Return total number of term occurrences.
INT64 stemCount (const std::string &term)
Return total number of stem occurrences.
INT64 termFieldCount (const std::string &term, const std::string &field)
Return total number of term occurrences within a field.
INT64 stemFieldCount (const std::string &term, const std::string &field)
Return total number of stem occurrences within a field.
double expressionCount (const std::string &expression, const std::string &queryType="indri")
Return the total number of times this expression appears in the collection.
double documentExpressionCount (const std::string &expression, const std::string &queryType="indri")
Return the total number of documents this expression appears in the collection.
std::vector< ScoredExtentResult > expressionList (const std::string &expression, const std::string &queryType="indri")
Return all the occurrences of this expression in the collection. Note that the returned vector may be quite large for large collections, and therefore has the very real possibility of exhausting the memory of the machine. Use this method with discretion.
std::vector< std::string > fieldList ()
Return the list of fields.
INT64 documentCount ()
Return total number of documents in the collection.
INT64 documentCount (const std::string &term)
Return total number of documents containing term in the collection.
INT64 documentStemCount (const std::string &stem)
Return total number of documents containing stem in the collection.
int documentLength (lemur::api::DOCID_T documentID)
Return the length of a document.
std::vector< DocumentVector * > documentVectors (const std::vector< lemur::api::DOCID_T > &documentIDs)
Fetch a document vector for a list of documents. Caller responsible for deleting the Vector.
void setMaxWildcardTerms (int maxTerms)
set maximum number of wildcard terms to expand to.
const std::vector
< indri::server::QueryServer * > & getServers () const
return the internal query servers.
void setFormulationParameters (Parameters &p)
set the query reformulation parameters.
std::string reformulateQuery (const std::string &query)
reformulate a query.
Private Member Functions
void _mergeQueryResults (indri::infnet::InferenceNetwork::MAllResults &results, std::vector< indri::server::QueryServerResponse * > &responses)
void _copyStatistics (std::vector< indri::lang::RawScorerNode * > &scorerNodes, indri::infnet::InferenceNetwork::MAllResults &statisticsResults)
std::vector
< indri::server::QueryServerResponse * > _runServerQuery (std::vector< indri::lang::Node * > &roots, int resultsRequested)
void _sumServerQuery (indri::infnet::InferenceNetwork::MAllResults &results, std::vector< indri::lang::Node * > &roots, int resultsRequested)
void _mergeServerQuery (indri::infnet::InferenceNetwork::MAllResults &results, std::vector< indri::lang::Node * > &roots, int resultsRequested)
void _annotateQuery (indri::infnet::InferenceNetwork::MAllResults &results, const std::vector< lemur::api::DOCID_T > &documentIDs, std::string &annotatorName, indri::lang::Node *queryRoot)
std::vector
< indri::api::ScoredExtentResult > _runQuery (indri::infnet::InferenceNetwork::MAllResults &results, const std::string &q, int resultsRequested, const std::vector< lemur::api::DOCID_T > *documentIDs, QueryAnnotation **annotation, const std::string &queryType="indri")
void _scoredQuery (indri::infnet::InferenceNetwork::MAllResults &results, indri::lang::Node *queryRoot, std::string &accumulatorName, int resultsRequested, const std::vector< lemur::api::DOCID_T > *documentSet)
double _expCount (const std::string &expression, const std::string &whichOccurrences, const std::string &queryType="indri")
QueryEnvironment (QueryEnvironment &other)
Private Attributes
indri::api::Parameters reformulatorParams
indri::query::ReformulateQuery * reformulator
std::map< std::string,
std::pair
< indri::server::QueryServer
*, indri::net::NetworkStream * > > _serverNameMap
std::vector
< indri::server::QueryServer * > _servers
std::map< std::string,
std::pair
< indri::server::QueryServer
*, indri::collection::Repository * > > _repositoryNameMap
std::vector
< indri::collection::Repository * > _repositories
std::vector
< indri::net::NetworkStream * > _streams
std::vector
< indri::net::NetworkMessageStream * > _messageStreams
Parameters _parameters
bool _baseline
Detailed Description
Principal class for interacting with Indri indexes during retrieval. Provides the API for opening one or more Repository servers, either local or remote. Provides the API for querying the servers with the Indri query language, and additionally requesting aggregate collection statistics.
Constructor & Destructor Documentation
indri::api::QueryEnvironment::QueryEnvironment (QueryEnvironment & other) [inline, private]
indri::api::QueryEnvironment::QueryEnvironment ()
References reformulator, and reformulatorParams.
indri::api::QueryEnvironment::~QueryEnvironment ()
References close().
Member Function Documentation
void indri::api::QueryEnvironment::_annotateQuery (indri::infnet::InferenceNetwork::MAllResults & results, const std::vector< lemur::api::DOCID_T > & documentIDs, std::string & annotatorName, indri::lang::Node * queryRoot) [private]
Referenced by runQuery().
void indri::api::QueryEnvironment::_copyStatistics (std::vector< indri::lang::RawScorerNode * > & scorerNodes, indri::infnet::InferenceNetwork::MAllResults & statisticsResults) [private]
References documentCount().
Referenced by runQuery().
double indri::api::QueryEnvironment::_expCount (const std::string & expression, const std::string & whichOccurrences, const std::string & queryType = "indri") [private]
References _sumServerQuery(), indri::api::QueryParserFactory::get(), indri::lang::RawScorerNode::getContext(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::Node::nodeName(), indri::api::QueryParserWrapper::query(), and indri::lang::Node::setNodeName().
Referenced by documentExpressionCount(), and expressionCount().
void indri::api::QueryEnvironment::_mergeQueryResults (indri::infnet::InferenceNetwork::MAllResults & results, std::vector< indri::server::QueryServerResponse * > & responses) [private]
References _servers, indri::api::ScoredExtentResult::document, and indri::server::QueryServerResponse::getResults().
Referenced by _mergeServerQuery().
void indri::api::QueryEnvironment::_mergeServerQuery (indri::infnet::InferenceNetwork::MAllResults & results, std::vector< indri::lang::Node * > & roots, int resultsRequested) [private]
References _mergeQueryResults(), and _runServerQuery().
std::vector<indri::api::ScoredExtentResult> indri::api::QueryEnvironment::_runQuery (indri::infnet::InferenceNetwork::MAllResults & results, const std::string & q, int resultsRequested, const std::vector< lemur::api::DOCID_T > * documentIDs, QueryAnnotation ** annotation, const std::string & queryType = "indri") [private]
Referenced by runAnnotatedQuery(), and runQuery().
std::vector< indri::server::QueryServerResponse * > indri::api::QueryEnvironment::_runServerQuery (std::vector< indri::lang::Node * > & roots, int resultsRequested) [private]
References _servers.
Referenced by _mergeServerQuery(), and _sumServerQuery().
void indri::api::QueryEnvironment::_scoredQuery (indri::infnet::InferenceNetwork::MAllResults & results, indri::lang::Node * queryRoot, std::string & accumulatorName, int resultsRequested, const std::vector< lemur::api::DOCID_T > * documentSet) [private]
Referenced by runQuery().
void indri::api::QueryEnvironment::_sumServerQuery (indri::infnet::InferenceNetwork::MAllResults & results, std::vector< indri::lang::Node * > & roots, int resultsRequested) [private]
References _runServerQuery(), and indri::server::QueryServerResponse::getResults().
Referenced by _expCount(), expressionList(), and runQuery().
void indri::api::QueryEnvironment::addIndex (class IndexEnvironment & environment)
Add an IndexEnvironment object. Unlike the other add calls, this one will not close the index when QueryEnvironment::close is called.
Parameters:
environment an IndexEnvironment instance
References indri::api::IndexEnvironment::_repository, and _servers.
void indri::api::QueryEnvironment::addIndex (const std::string & pathname)
Add a local repository.
Parameters:
pathname the path to the repository.
References _parameters, _repositories, _repositoryNameMap, _servers, and indri::collection::Repository::openRead().
Referenced by QueryThread::initialize(), main(), open_indexes(), print_document_expression_count(), print_expression_count(), and print_expression_list().
void indri::api::QueryEnvironment::addServer (const std::string & hostname)
Add a remote server.
Parameters:
hostname the host the server is running on
References _messageStreams, _serverNameMap, _servers, _streams, indri::net::NetworkStream::connect(), and INDRID_PORT.
Referenced by QueryThread::initialize(), and open_indexes().
void indri::api::QueryEnvironment::close ()
Close the QueryEnvironment.
References _messageStreams, _repositories, _servers, _streams, and reformulator.
Referenced by QueryThread::deinitialize(), print_document_expression_count(), print_expression_count(), print_expression_list(), and ~QueryEnvironment().
INT64 indri::api::QueryEnvironment::documentCount (const std::string & term)
Return total number of documents containing term in the collection.
Parameters:
term the term to count documents for.
Returns:
total number of documents containing term in the aggregated collection
References _servers.
INT64 indri::api::QueryEnvironment::documentCount ()
Return total number of documents in the collection.
Returns:
total number of documents in the aggregated collection
References _servers.
Referenced by _copyStatistics(), CSharp_QueryEnvironment_documentCount__SWIG_0(), indri::query::TFIDFExpander::expand(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_10(), print_expression_list(), and runQuery().
double indri::api::QueryEnvironment::documentExpressionCount (const std::string & expression, const std::string & queryType = "indri")
Return the total number of documents this expression appears in the collection.
Parameters:
expression The expression to evaluate, probably an ordered or unordered window expression
References _expCount().
Referenced by print_document_expression_count().
std::vector< DOCID_T > indri::api::QueryEnvironment::documentIDsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValue)
Return a list of document IDs where the document has a metadata key that matches attributeName, with a value matching one of the attributeValues.
Parameters:
attributeName the name of the metadata attribute (e.g. 'url' or 'docno')
attributeValue values that the metadata attribute should match
Returns:
a vector of ParsedDocuments that match the given metadata criteria
References _servers.
Referenced by QueryThread::_runQuery(), and convert_docnoscore_to_binary().
int indri::api::QueryEnvironment::documentLength (lemur::api::DOCID_T documentID)
Return the length of a document.
Parameters:
documentID the document id.
Returns:
length of the document, documentID
References _servers.
Referenced by CSharp_QueryEnvironment_documentLength(), and Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentLength().
std::vector< std::string > indri::api::QueryEnvironment::documentMetadata (const std::vector< indri::api::ScoredExtentResult > & documentIDs, const std::string & attributeName)
Fetch the named metadata attribute for a list of ScoredExtentResults.
Parameters:
documentIDs the list of ScoredExtentResults
attributeName the name of the metadata attribute
Returns:
the vector of string values for that attribute
References documentMetadata().
std::vector<std::string> indri::api::QueryEnvironment::documentMetadata (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::string & attributeName)
Fetch the named metadata attribute for a list of document ids.
Parameters:
documentIDs the list of ids
attributeName the name of the metadata attribute
Returns:
the vector of string values for that attribute
Referenced by QueryThread::_printResultRegion(), and documentMetadata().
std::vector< indri::api::ParsedDocument * > indri::api::QueryEnvironment::documents (const std::vector< indri::api::ScoredExtentResult > & results)
Fetch the parsed documents for a given list of ScoredExtentResults Caller is responsible for deleting the returned elements.
Parameters:
results the list of ScoredExtentResults
Returns:
the vector of ParsedDocument pointers.
References documents().
std::vector<indri::api::ParsedDocument*> indri::api::QueryEnvironment::documents (const std::vector< lemur::api::DOCID_T > & documentIDs)
Fetch the parsed documents for a given list of document ids. Caller is responsible for deleting the returned elements.
Parameters:
documentIDs the list of ids
Returns:
the vector of ParsedDocument pointers.
Referenced by QueryThread::_printResultRegion(), documents(), and runQuery().
std::vector< indri::api::ParsedDocument * > indri::api::QueryEnvironment::documentsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues)
Fetch all documents with a metadata key that matches attributeName, with a value matching one of the attributeValues.
Parameters:
attributeName the name of the metadata attribute (e.g. 'url' or 'docno')
attributeValues values that the metadata attribute should match
Returns:
a vector of ParsedDocuments that match the given metadata criteria
References _servers.
INT64 indri::api::QueryEnvironment::documentStemCount (const std::string & stem)
Return total number of documents containing stem in the collection.
Parameters:
stem the prestemmed term to count documents for.
Returns:
total number of documents containing stem in the aggregated collection
References _servers.
Referenced by indri::query::TFIDFExpander::expand().
std::vector<DocumentVector*> indri::api::QueryEnvironment::documentVectors (const std::vector< lemur::api::DOCID_T > & documentIDs)
Fetch a document vector for a list of documents. Caller responsible for deleting the Vector.
Parameters:
documentIDs the vector of document ids.
Returns:
DocumentVector pointer for the specified document.
Referenced by indri::query::RelevanceModel::generate(), and indri::query::QueryExpander::getDocumentVectors().
double indri::api::QueryEnvironment::expressionCount (const std::string & expression, const std::string & queryType = "indri")
Return the total number of times this expression appears in the collection.
Parameters:
expression The expression to evaluate, probably an ordered or unordered window expression
References _expCount().
Referenced by indri::query::RelevanceModel::_scoreGrams(), and print_expression_count().
std::vector< indri::api::ScoredExtentResult > indri::api::QueryEnvironment::expressionList (const std::string & expression, const std::string & queryType = "indri")
Return all the occurrences of this expression in the collection. Note that the returned vector may be quite large for large collections, and therefore has the very real possibility of exhausting the memory of the machine. Use this method with discretion.
Parameters:
expression The expression to evaluate, probably an ordered or unordered window expression
References _sumServerQuery(), indri::api::QueryParserFactory::get(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::Node::nodeName(), indri::api::QueryParserWrapper::query(), and indri::lang::Node::setNodeName().
Referenced by print_expression_list().
std::vector< std::string > indri::api::QueryEnvironment::fieldList ()
Return the list of fields.
Returns:
vector of field names.
References _servers.
const std::vector<indri::server::QueryServer*>& indri::api::QueryEnvironment::getServers () const [inline]
return the internal query servers.
Returns:
the local and network query servers.
References _servers.
Referenced by indri::query::TFIDFExpander::expand().
std::vector< std::string > indri::api::QueryEnvironment::pathNames (const std::vector< indri::api::ScoredExtentResult > & results)
Fetch the XPath names of extents for a list of ScoredExtentResults.
Parameters:
results the list of ScoredExtentResults
Returns:
the vector of string XPath names for the extents
References _servers, indri::utility::greedy_vector< _Type, _Count >::push_back(), qenv_gather_document_results(), and qenv_scatter_document_ids().
Referenced by QueryThread::_printResultRegion().
std::string indri::api::QueryEnvironment::reformulateQuery (const std::string & query)
reformulate a query.
Parameters:
query the bag of words query to reformulate.
Returns:
the indri query language reformulated query.
References reformulator, and indri::query::ReformulateQuery::transform().
Referenced by main().
void indri::api::QueryEnvironment::removeIndex (const std::string & pathname)
Remove a local repository.
Parameters:
pathname the path to the repository.
References _repositories, _repositoryNameMap, and _servers.
void indri::api::QueryEnvironment::removeServer (const std::string & hostname)
Remove a remote server.
Parameters:
hostname the host the server is running on
References _messageStreams, _serverNameMap, _servers, and _streams.
QueryAnnotation* indri::api::QueryEnvironment::runAnnotatedQuery (const std::string & query, const std::vector< lemur::api::DOCID_T > & documentSet, int resultsRequested, const std::string & queryType = "indri")
Run an Indri query language query.
See also:
QueryAnnotation
Parameters:
query the query to run
documentSet the working set of document ids to evaluate
resultsRequested maximum number of results to return
Returns:
pointer to QueryAnnotations for the query
indri::api::QueryAnnotation * indri::api::QueryEnvironment::runAnnotatedQuery (const std::string & query, int resultsRequested, const std::string & queryType = "indri")
Run an Indri query language query.
See also:
QueryAnnotation
Parameters:
query the query to run
resultsRequested maximum number of results to return
Returns:
pointer to QueryAnnotations for the query
References _runQuery().
Referenced by QueryThread::_runQuery().
std::vector<indri::api::ScoredExtentResult> indri::api::QueryEnvironment::runQuery (const std::string & query, const std::vector< lemur::api::DOCID_T > & documentSet, int resultsRequested, const std::string & queryType = "indri")
Run an Indri query language query.
See also:
ScoredExtentResult
Parameters:
query the query to run
documentSet the working set of document ids to evaluate
resultsRequested maximum number of results to return
Returns:
the vector of ScoredExtentResults for the query
std::vector< indri::api::ScoredExtentResult > indri::api::QueryEnvironment::runQuery (const std::string & query, int resultsRequested, const std::string & queryType = "indri")
Run an Indri query language query.
See also:
ScoredExtentResult
Parameters:
query the query to run
resultsRequested maximum number of results to return
Returns:
the vector of ScoredExtentResults for the query
References _runQuery().
indri::api::QueryResults indri::api::QueryEnvironment::runQuery (QueryRequest & request)
Run an Indri query language query.
Parameters:
request the query to run
Returns:
the QueryResults for the request,
References _annotateQuery(), _copyStatistics(), _getRawNodes(), _parameters, _scoredQuery(), _sumServerQuery(), indri::api::QueryResult::begin, indri::api::SnippetBuilder::build(), indri::lang::Node::copy(), indri::api::QueryResult::docid, indri::api::QueryRequest::docSet, documentCount(), indri::api::QueryResult::documentName, documents(), indri::api::QueryResults::documentsTime, indri::utility::IndriTimer::elapsedTime(), indri::api::QueryResult::end, indri::api::QueryResults::estimatedMatches, indri::api::QueryResults::executeTime, indri::api::Parameters::exists(), indri::api::Parameters::get(), indri::api::QueryParserFactory::get(), indri::api::QueryAnnotation::getQueryTree(), indri::api::QueryAnnotation::getResults(), indri::lang::RawScorerNodeExtractor::getScorerNodes(), indri::api::QueryRequest::HTMLSnippet, indri::api::MetadataPair::key, indri::api::QueryResult::metadata, indri::api::QueryRequest::metadata, indri::api::QueryRequest::options, indri::api::QueryResults::parseTime, indri::api::QueryParserWrapper::query(), indri::api::QueryRequest::query, indri::api::QueryResults::results, indri::api::QueryRequest::resultsRequested, indri::lang::ApplyCopiers< T, NodeType >::roots(), indri::api::QueryResult::score, indri::api::QueryResult::snippet, indri::utility::IndriTimer::start(), indri::api::QueryRequest::startNum, indri::utility::IndriTimer::stop(), indri::api::MetadataPair::value, indri::parse::MetadataPair::value, and indri::lang::Node::walk().
Referenced by QueryThread::_runQuery(), indri::query::RelevanceModel::generate(), and indri::query::QueryExpander::runExpandedQuery().
void indri::api::QueryEnvironment::setBaseline (const std::string & baseline)
Set whether there should be one single background model or context sensitive models.
Parameters:
background true for one background model false for context sensitive models
References _baseline, _parameters, and indri::api::Parameters::set().
Referenced by QueryThread::initialize().
void indri::api::QueryEnvironment::setFormulationParameters (Parameters & p)
set the query reformulation parameters.
Parameters:
p the Parameters object containing the parameters.
References reformulator, reformulatorParams, and indri::query::ReformulateQuery::setParameters().
Referenced by main().
void indri::api::QueryEnvironment::setMaxWildcardTerms (int maxTerms)
set maximum number of wildcard terms to expand to.
Parameters:
maxTerms the maximum number of terms to expand a wildcard operator argument (default 100).
References _servers.
Referenced by QueryThread::initialize().
void indri::api::QueryEnvironment::setMemory (UINT64 memory)
Set the amount of memory to use.
Parameters:
memory number of bytes to allocate
References _parameters, and indri::api::Parameters::set().
void indri::api::QueryEnvironment::setScoringRules (const std::vector< std::string > & rules)
Set the scoring rules.
Parameters:
rules the vector of scoring rules.
References _parameters, indri::api::Parameters::append(), and indri::api::Parameters::set().
Referenced by QueryThread::initialize(), and open_indexes().
void indri::api::QueryEnvironment::setSingleBackgroundModel (bool background)
References _parameters, and indri::api::Parameters::set().
Referenced by QueryThread::initialize().
void indri::api::QueryEnvironment::setStopwords (const std::vector< std::string > & stopwords)
Set the stopword list for query processing.
Parameters:
stopwords the list of stopwords
References _parameters, indri::api::Parameters::append(), indri::api::Parameters::get(), and indri::api::Parameters::set().
Referenced by QueryThread::initialize().
INT64 indri::api::QueryEnvironment::stemCount (const std::string & term)
Return total number of stem occurrences.
Parameters:
term the stem to count
Returns:
total frequency of this stem in the aggregated collection
References _servers.
Referenced by indri::query::RelevanceModel::_scoreGrams(), clarity(), indri::query::QueryExpander::getCF(), and printClarity().
INT64 indri::api::QueryEnvironment::stemFieldCount (const std::string & term, const std::string & field)
Return total number of stem occurrences within a field.
Parameters:
term the stem to count
field the name of the field
Returns:
total frequency of this stem within this field in the aggregated collection
References _servers.
std::string indri::api::QueryEnvironment::stemTerm (const std::string & term)
Return the stem of the term.
Parameters:
term the term to stem
Returns:
the stem of the term
References _servers.
INT64 indri::api::QueryEnvironment::termCount (const std::string & term)
Return total number of term occurrences.
Parameters:
term the term to count
Returns:
total frequency of this term in the aggregated collection
References _servers.
INT64 indri::api::QueryEnvironment::termCount ()
Return total number of terms.
Returns:
total number of terms in the aggregated collection
References _servers.
Referenced by indri::query::RelevanceModel::_scoreGrams(), clarity(), CSharp_QueryEnvironment_termCount__SWIG_0(), indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_10(), print_expression_list(), and printClarity().
INT64 indri::api::QueryEnvironment::termCountUnique ()
Return total number of unique terms.
Returns:
total number of unique terms in the aggregated collection
References _servers.
Referenced by CSharp_QueryEnvironment_termCountUnique(), and Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCountUnique().
INT64 indri::api::QueryEnvironment::termFieldCount (const std::string & term, const std::string & field)
Return total number of term occurrences within a field.
Parameters:
term the term to count
field the name of the field
Returns:
total frequency of this term within this field in the aggregated collection
References _servers.
Member Data Documentation
bool indri::api::QueryEnvironment::_baseline [private]
Referenced by setBaseline().
std::vector<indri::net::NetworkMessageStream*> indri::api::QueryEnvironment::_messageStreams [private]
Referenced by addServer(), close(), and removeServer().
Parameters indri::api::QueryEnvironment::_parameters [private]
Referenced by addIndex(), runQuery(), setBaseline(), setMemory(), setScoringRules(), setSingleBackgroundModel(), and setStopwords().
std::vector<indri::collection::Repository*> indri::api::QueryEnvironment::_repositories [private]
Referenced by addIndex(), close(), and removeIndex().
std::map<std::string, std::pair<indri::server::QueryServer *, indri::collection::Repository *> > indri::api::QueryEnvironment::_repositoryNameMap [private]
Referenced by addIndex(), and removeIndex().
std::map<std::string, std::pair<indri::server::QueryServer *, indri::net::NetworkStream *> > indri::api::QueryEnvironment::_serverNameMap [private]
Referenced by addServer(), and removeServer().
std::vector<indri::server::QueryServer*> indri::api::QueryEnvironment::_servers [private]
Referenced by _mergeQueryResults(), _runServerQuery(), addIndex(), addServer(), close(), documentCount(), documentIDsFromMetadata(), documentLength(), documentsFromMetadata(), documentStemCount(), fieldList(), getServers(), pathNames(), removeIndex(), removeServer(), setMaxWildcardTerms(), stemCount(), stemFieldCount(), stemTerm(), termCount(), termCountUnique(), and termFieldCount().
std::vector<indri::net::NetworkStream*> indri::api::QueryEnvironment::_streams [private]
Referenced by addServer(), close(), and removeServer().
indri::query::ReformulateQuery* indri::api::QueryEnvironment::reformulator [private]
Referenced by close(), QueryEnvironment(), reformulateQuery(), and setFormulationParameters().
indri::api::Parameters indri::api::QueryEnvironment::reformulatorParams [private]
Referenced by QueryEnvironment(), and setFormulationParameters().
The documentation for this class was generated from the following files:
QueryEnvironment.hpp
QueryEnvironment.cpp