Indri: indri::file::BulkTreeIterator Class Reference
indri::file::BulkTreeIterator Class Reference
#include <BulkTree.hpp>
Public Member Functions
BulkTreeIterator (File &file)
BulkTreeIterator (File &file, UINT64 whichBlock, int whichPair)
void startIteration ()
bool finished ()
bool get (char *key, int keyLength, int &keyActual, char *value, int valueLength, int &valueActual)
bool get (UINT32 &key, char *value, int valueLength, int &valueActual)
void nextEntry ()
Private Member Functions
bool readCurrentBlockData ()
Private Attributes
File & _file
UINT64 _fileLength
BulkBlock _block
int _pairIndex
UINT64 _blockIndex
Constructor & Destructor Documentation
indri::file::BulkTreeIterator::BulkTreeIterator (File & file)
References _blockIndex, _fileLength, and _pairIndex.
indri::file::BulkTreeIterator::BulkTreeIterator (File & file, UINT64 whichBlock, int whichPair)
Constructor to point the iterator at a specific entry within the bulk tree. If the parameters are out of bounds, then the iterator will point at the beginning of the tree.
Parameters:
file the bulk tree file
whichBlock the starting block
whichPair the starting index pair
References _block, _blockIndex, _file, _fileLength, _pairIndex, indri::file::BulkBlock::count(), finished(), readCurrentBlockData(), and indri::file::File::size().
Member Function Documentation
bool indri::file::BulkTreeIterator::finished ()
References _blockIndex, _fileLength, and indri::file::BulkBlock::dataSize().
Referenced by indri::index::DiskKeyfileVocabularyIterator::_readData(), BulkTreeIterator(), indri::index::DiskKeyfileVocabularyIterator::currentEntry(), indri::index::DiskKeyfileVocabularyIterator::finished(), get(), indri::index::DiskKeyfileVocabularyIterator::nextEntry(), and nextEntry().
bool indri::file::BulkTreeIterator::get (UINT32 & key, char * value, int valueLength, int & valueActual)
References _block, _pairIndex, finished(), and indri::file::BulkBlock::getIndex().
bool indri::file::BulkTreeIterator::get (char * key, int keyLength, int & keyActual, char * value, int valueLength, int & valueActual)
References _block, _pairIndex, finished(), and indri::file::BulkBlock::getIndex().
Referenced by indri::index::DiskKeyfileVocabularyIterator::_readData().
void indri::file::BulkTreeIterator::nextEntry ()
References _block, _blockIndex, _file, _pairIndex, indri::file::BulkBlock::count(), indri::file::BulkBlock::data(), indri::file::BulkBlock::dataSize(), finished(), indri::file::BulkBlock::leaf(), and indri::file::File::read().
Referenced by indri::index::DiskKeyfileVocabularyIterator::nextEntry(), and startIteration().
bool indri::file::BulkTreeIterator::readCurrentBlockData () [private]
References _block, _blockIndex, _file, indri::file::BulkBlock::data(), indri::file::BulkBlock::dataSize(), and indri::file::File::read().
Referenced by BulkTreeIterator().
void indri::file::BulkTreeIterator::startIteration ()
References _blockIndex, _file, _fileLength, _pairIndex, nextEntry(), and indri::file::File::size().
Referenced by indri::index::DiskKeyfileVocabularyIterator::startIteration().
Member Data Documentation
BulkBlock indri::file::BulkTreeIterator::_block [private]
Referenced by BulkTreeIterator(), get(), nextEntry(), and readCurrentBlockData().
UINT64 indri::file::BulkTreeIterator::_blockIndex [private]
Referenced by BulkTreeIterator(), finished(), nextEntry(), readCurrentBlockData(), and startIteration().
File& indri::file::BulkTreeIterator::_file [private]
Referenced by BulkTreeIterator(), nextEntry(), readCurrentBlockData(), and startIteration().
UINT64 indri::file::BulkTreeIterator::_fileLength [private]
Referenced by BulkTreeIterator(), finished(), and startIteration().
int indri::file::BulkTreeIterator::_pairIndex [private]
Referenced by BulkTreeIterator(), get(), nextEntry(), and startIteration().
The documentation for this class was generated from the following files:
BulkTree.hpp
BulkTree.cpp