Indri: indri::file::File Class Reference
indri::file::File Class Reference
#include <File.hpp>
Public Member Functions
File ()
~File ()
bool create (const std::string &filename)
bool open (const std::string &filename)
bool openRead (const std::string &filename)
bool openTemporary (std::string &filename)
void close ()
size_t read (void *buffer, UINT64 position, size_t length)
size_t write (const void *buffer, UINT64 position, size_t length)
UINT64 size ()
Private Attributes
int _handle
Constructor & Destructor Documentation
indri::file::File::File ()
indri::file::File::~File ()
References close().
Member Function Documentation
void indri::file::File::close ()
References _handle.
Referenced by indri::index::IndexWriter::_closeFiles(), indri::index::IndexWriter::_writeInvertedLists(), indri::index::DiskIndex::close(), indri::collection::CompressedCollection::close(), indri::file::BulkTreeReader::close(), indri::file::BulkTreeWriter::close(), indri::collection::CompressedCollection::compact(), convert_intscore_to_long_binary(), indri::parse::PageRank::indexPageRank(), install_prior(), main(), merge_sorted_runs(), indri::index::DeletedDocumentList::read(), sort_file(), sort_run(), indri::index::DeletedDocumentList::write(), and ~File().
bool indri::file::File::create (const std::string & filename)
References _handle.
Referenced by indri::index::IndexWriter::_constructFiles(), indri::collection::CompressedCollection::compact(), indri::collection::CompressedCollection::create(), indri::file::BulkTreeWriter::create(), indri::parse::PageRank::indexPageRank(), install_prior(), and indri::index::DeletedDocumentList::write().
bool indri::file::File::open (const std::string & filename)
References _handle.
Referenced by indri::collection::CompressedCollection::open(), openRead(), and openTemporary().
bool indri::file::File::openRead (const std::string & filename)
References _handle, and open().
Referenced by indri::collection::Repository::_openPriors(), indri::parse::PageRank::indexPageRank(), merge_sorted_runs(), indri::index::DiskIndex::open(), indri::collection::CompressedCollection::openRead(), indri::file::BulkTreeReader::openRead(), and indri::index::DeletedDocumentList::read().
bool indri::file::File::openTemporary (std::string & filename)
References _handle, and open().
Referenced by main(), and sort_file().
size_t indri::file::File::read (void * buffer, UINT64 position, size_t length)
References _handle.
Referenced by indri::file::BulkTreeReader::_fetch(), indri::file::SequentialReadBuffer::cache(), copy_region(), indri::file::BulkTreeIterator::nextEntry(), indri::index::DeletedDocumentList::read(), indri::file::BulkTreeIterator::readCurrentBlockData(), sort_run(), indri::index::DiskFrequentVocabularyIterator::startIteration(), indri::index::DiskIndex::termList(), and zlib_read_document().
UINT64 indri::file::File::size ()
References _handle.
Referenced by indri::collection::CompressedCollection::append(), indri::file::BulkTreeIterator::BulkTreeIterator(), indri::collection::CompressedCollection::compact(), extract_compression_table(), install_prior(), merge_sorted_runs(), indri::index::DiskIndex::open(), indri::file::BulkTreeReader::openRead(), indri::index::DeletedDocumentList::read(), indri::file::SequentialWriteBuffer::SequentialWriteBuffer(), sort_file(), sort_run(), indri::index::DiskFrequentVocabularyIterator::startIteration(), indri::index::DiskDocumentDataIterator::startIteration(), and indri::file::BulkTreeIterator::startIteration().
size_t indri::file::File::write (const void * buffer, UINT64 position, size_t length)
References _handle.
Referenced by copy_region(), indri::file::SequentialWriteBuffer::flush(), sort_run(), and indri::index::DeletedDocumentList::write().
Member Data Documentation
int indri::file::File::_handle [private]
Referenced by close(), create(), open(), openRead(), openTemporary(), read(), size(), and write().
The documentation for this class was generated from the following files:
File.hpp
File.cpp