Indri: indri::xml::XMLReader Class Reference
indri::xml::XMLReader Class Reference
#include <XMLReader.hpp>
Public Member Functions
XMLNode * read (const char *buffer, size_t length)
XMLNode * read (const std::string &str)
Private Types
enum { TAG_OPEN_TYPE, TAG_CLOSE_TYPE, TAG_OPEN_CLOSE_TYPE, TAG_CDATA_TYPE }
Private Member Functions
int _tryFindChar (char ch, const char *buffer, int start, int finish)
int _findChar (char ch, const char *buffer, int start, int finish)
int _tryFindBeginTag (const char *buffer, int start, int finish)
int _findBeginTag (const char *buffer, int start, int finish)
int _findEndTag (const char *buffer, int start, int finish)
int _tryFindText (const char *buffer, int start, int finish)
int _findText (const char *buffer, int start, int finish)
int _findNotName (const char *buffer, int start, int finish)
int _findSpace (const char *buffer, int start, int finish)
int _readTag (const char *buffer, int bufferStart, int bufferEnd, std::string *tagName, std::map< std::string, std::string > *attributes, int *tagType)
int _findClosingTag (const char *buffer, int start, int end, std::string &openingTagName, bool *tagsBetween)
void _read (XMLNode **parent, const char *buffer, int start, int end)
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
TAG_OPEN_TYPE
TAG_CLOSE_TYPE
TAG_OPEN_CLOSE_TYPE
TAG_CDATA_TYPE
Member Function Documentation
int indri::xml::XMLReader::_findBeginTag (const char * buffer, int start, int finish) [private]
References _tryFindBeginTag().
Referenced by _findClosingTag().
int indri::xml::XMLReader::_findChar (char ch, const char * buffer, int start, int finish) [private]
References _tryFindChar().
Referenced by _findEndTag(), and _readTag().
int indri::xml::XMLReader::_findClosingTag (const char * buffer, int start, int end, std::string & openingTagName, bool * tagsBetween) [private]
References _findBeginTag(), _readTag(), TAG_CDATA_TYPE, TAG_CLOSE_TYPE, and TAG_OPEN_TYPE.
Referenced by _read().
int indri::xml::XMLReader::_findEndTag (const char * buffer, int start, int finish) [private]
References _findChar().
Referenced by _read(), and _readTag().
int indri::xml::XMLReader::_findNotName (const char * buffer, int start, int finish) [private]
Referenced by _readTag().
int indri::xml::XMLReader::_findSpace (const char * buffer, int start, int finish) [private]
int indri::xml::XMLReader::_findText (const char * buffer, int start, int finish) [private]
References _tryFindText().
Referenced by _readTag().
void indri::xml::XMLReader::_read (XMLNode ** parent, const char * buffer, int start, int end) [private]
References _findClosingTag(), _findEndTag(), _readTag(), _tryFindBeginTag(), TAG_CLOSE_TYPE, TAG_OPEN_CLOSE_TYPE, and TAG_OPEN_TYPE.
Referenced by read().
int indri::xml::XMLReader::_readTag (const char * buffer, int bufferStart, int bufferEnd, std::string * tagName, std::map< std::string, std::string > * attributes, int * tagType) [private]
References _findChar(), _findEndTag(), _findNotName(), _findText(), _tryFindText(), TAG_CDATA_TYPE, TAG_CLOSE_TYPE, TAG_OPEN_CLOSE_TYPE, and TAG_OPEN_TYPE.
Referenced by _findClosingTag(), and _read().
int indri::xml::XMLReader::_tryFindBeginTag (const char * buffer, int start, int finish) [private]
References _tryFindChar().
Referenced by _findBeginTag(), and _read().
int indri::xml::XMLReader::_tryFindChar (char ch, const char * buffer, int start, int finish) [private]
Referenced by _findChar(), and _tryFindBeginTag().
int indri::xml::XMLReader::_tryFindText (const char * buffer, int start, int finish) [private]
Referenced by _findText(), and _readTag().
indri::xml::XMLNode * indri::xml::XMLReader::read (const std::string & str)
References read().
indri::xml::XMLNode * indri::xml::XMLReader::read (const char * buffer, size_t length)
References _read().
Referenced by indri::api::Parameters::load(), indri::api::Parameters::loadFile(), indri::parse::PDFDocumentExtractor::nextDocument(), read(), and indri::net::NetworkMessageStream::read().
The documentation for this class was generated from the following files:
XMLReader.hpp
XMLReader.cpp