Indri: indri::infnet::FieldBetweenNode Class Reference
indri::infnet::FieldBetweenNode Class Reference
#include <FieldBetweenNode.hpp>
Public Member Functions
FieldBetweenNode (const std::string &name, class FieldIteratorNode *iterator, INT64 low, INT64 high)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
class FieldIteratorNode * _field
indri::utility::greedy_vector
< indri::index::Extent > _extents
INT64 _low
INT64 _high
std::string _name
Constructor & Destructor Documentation
indri::infnet::FieldBetweenNode::FieldBetweenNode (const std::string & name, class FieldIteratorNode * iterator, INT64 low, INT64 high)
References _field, _high, _low, and _name.
Member Function Documentation
void indri::infnet::FieldBetweenNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, and indri::infnet::Annotator::addMatches().
indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::FieldBetweenNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
Referenced by prepare().
const std::string & indri::infnet::FieldBetweenNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::FieldBetweenNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
lemur::api::DOCID_T indri::infnet::FieldBetweenNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _field, and indri::infnet::FieldIteratorNode::nextCandidateDocument().
void indri::infnet::FieldBetweenNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _extents, _field, _high, _low, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::infnet::FieldIteratorNode::extents(), extents(), indri::infnet::ListIteratorNode::initpointer(), indri::infnet::FieldIteratorNode::numbers(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::FieldBetweenNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
class FieldIteratorNode* indri::infnet::FieldBetweenNode::_field [private]
Referenced by FieldBetweenNode(), nextCandidateDocument(), and prepare().
INT64 indri::infnet::FieldBetweenNode::_high [private]
Referenced by FieldBetweenNode(), and prepare().
INT64 indri::infnet::FieldBetweenNode::_low [private]
Referenced by FieldBetweenNode(), and prepare().
std::string indri::infnet::FieldBetweenNode::_name [private]
Referenced by FieldBetweenNode(), and getName().
The documentation for this class was generated from the following files:
FieldBetweenNode.hpp
FieldBetweenNode.cpp