Indri: indri::file::DirectoryIterator Class Reference
indri::file::DirectoryIterator Class Reference
#include <DirectoryIterator.hpp>
Public Member Functions
DirectoryIterator ()
DirectoryIterator (const std::string &path, bool relative=true)
~DirectoryIterator ()
void operator++ (int)
Moves to the next file in the directory.
void operator++ ()
Moves to the next file in the directory.
bool operator== (const DirectoryIterator &other)
const std::string & operator* ()
const std::string & base () const
void close ()
Closes this iterator, releasing any operating system handles, etc.
Static Public Member Functions
static const DirectoryIterator & end ()
Private Member Functions
void _copyCurrent ()
void _next ()
Private Attributes
bool _relative
std::string _current
void * _platform
std::string _path
Static Private Attributes
static DirectoryIterator _end
Detailed Description
Provides iteration over directory entries.
Constructor & Destructor Documentation
indri::file::DirectoryIterator::DirectoryIterator ()
indri::file::DirectoryIterator::DirectoryIterator (const std::string & path, bool relative = true)
Constructs a DirectoryIterator. The iterator will step through the files in the directory named in the path parameter. If the relative flag is set to true, the iteration returns file names only; otherwise full paths to files are returned.
References _copyCurrent(), _next(), _path, _platform, directoryiterator_current(), directoryiterator_done(), directoryiterator_init(), and trim().
indri::file::DirectoryIterator::~DirectoryIterator ()
References close().
Member Function Documentation
void indri::file::DirectoryIterator::_copyCurrent () [private]
References _current, _path, _platform, _relative, indri::file::Path::combine(), directoryiterator_current(), and trim().
Referenced by _next(), and DirectoryIterator().
void indri::file::DirectoryIterator::_next () [private]
References _copyCurrent(), _platform, directoryiterator_current(), directoryiterator_done(), and directoryiterator_next().
Referenced by DirectoryIterator(), and operator++().
const std::string & indri::file::DirectoryIterator::base () const
Returns the path of this directory (the path passed to the constructor of this object).
References _path.
Referenced by indri::file::Path::remove().
void indri::file::DirectoryIterator::close ()
Closes this iterator, releasing any operating system handles, etc.
References _platform, and directoryiterator_destroy().
Referenced by indri::file::Path::remove(), and ~DirectoryIterator().
const indri::file::DirectoryIterator & indri::file::DirectoryIterator::end () [static]
Placeholder object that indicates a finished iteration. Use this with operator != to tell when iteration is finished.
References _end.
Referenced by indri::file::FileTreeIterator::_next(), indri::file::FileTreeIterator::_nextCandidate(), indri::collection::Repository::_openPriors(), _recoverRepository(), indri::file::FileTreeIterator::FileTreeIterator(), and indri::file::Path::remove().
const std::string & indri::file::DirectoryIterator::operator* ()
Returns the full path to a file in the directory if relative was set to false in the constructor (which is the default). Otherwise, returns only the file name.
References _current.
void indri::file::DirectoryIterator::operator++ ()
Moves to the next file in the directory.
References _next(), _platform, and directoryiterator_done().
void indri::file::DirectoryIterator::operator++ (int)
Moves to the next file in the directory.
References _next(), _platform, and directoryiterator_done().
bool indri::file::DirectoryIterator::operator== (const DirectoryIterator & other)
Used only for comparison with FileTreeIterator::end. If false, the iteration is complete.
References _end, _platform, and directoryiterator_done().
Member Data Documentation
std::string indri::file::DirectoryIterator::_current [private]
Referenced by _copyCurrent(), and operator*().
indri::file::DirectoryIterator indri::file::DirectoryIterator::_end [static, private]
Referenced by end(), and operator==().
std::string indri::file::DirectoryIterator::_path [private]
Referenced by _copyCurrent(), base(), and DirectoryIterator().
void* indri::file::DirectoryIterator::_platform [private]
Referenced by _copyCurrent(), _next(), close(), DirectoryIterator(), operator++(), and operator==().
bool indri::file::DirectoryIterator::_relative [private]
Referenced by _copyCurrent().
The documentation for this class was generated from the following files:
DirectoryIterator.hpp
DirectoryIterator.cpp