Indri: indri::parse::NumericFieldAnnotator Class Reference
indri::parse::NumericFieldAnnotator Class Reference
#include <NumericFieldAnnotator.hpp>
Public Member Functions
NumericFieldAnnotator (std::string &field)
~NumericFieldAnnotator ()
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
Private Attributes
ObjectHandler
< indri::api::ParsedDocument > * _handler
std::string & _field
bool _foundNonNumeric
int _numberCopyLength
char * _numberCopy
Constructor & Destructor Documentation
indri::parse::NumericFieldAnnotator::NumericFieldAnnotator (std::string & field) [inline]
References _numberCopy, and _numberCopyLength.
indri::parse::NumericFieldAnnotator::~NumericFieldAnnotator () [inline]
References _numberCopy.
Member Function Documentation
void indri::parse::NumericFieldAnnotator::handle (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::NumericFieldAnnotator::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [inline, virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument* indri::parse::NumericFieldAnnotator::transform (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _field, _foundNonNumeric, _numberCopy, _numberCopyLength, indri::parse::TagExtent::begin, indri::parse::TagExtent::end, indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::utility::greedy_vector< _Type, _Count >::size(), string_to_i64(), indri::api::ParsedDocument::tags, and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
std::string& indri::parse::NumericFieldAnnotator::_field [private]
Referenced by transform().
bool indri::parse::NumericFieldAnnotator::_foundNonNumeric [private]
Referenced by transform().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::NumericFieldAnnotator::_handler [private]
Referenced by handle(), and setHandler().
char* indri::parse::NumericFieldAnnotator::_numberCopy [private]
Referenced by NumericFieldAnnotator(), transform(), and ~NumericFieldAnnotator().
int indri::parse::NumericFieldAnnotator::_numberCopyLength [private]
Referenced by NumericFieldAnnotator(), and transform().
The documentation for this class was generated from the following file:
NumericFieldAnnotator.hpp