Indri: indri::api::DocumentVector Class Reference
indri::api::DocumentVector Class Reference
#include <DocumentVector.hpp>
Classes
struct Field
Public Member Functions
DocumentVector ()
DocumentVector (indri::index::Index *index, const class indri::index::TermList *termList)
DocumentVector (indri::index::Index *index, const class indri::index::TermList *termList, std::map< int, std::string > &termStringMap)
std::vector< std::string > & stems ()
const std::vector< std::string > & stems () const
std::vector< int > & positions ()
const std::vector< int > & positions () const
std::vector< Field > & fields ()
const std::vector< Field > & fields () const
Private Member Functions
void _init (indri::index::Index *index, const class indri::index::TermList *termList, std::map< int, std::string > *termStringMap)
Private Attributes
std::vector< std::string > _stems
std::vector< int > _positions
std::vector< Field > _fields
Constructor & Destructor Documentation
indri::api::DocumentVector::DocumentVector ()
indri::api::DocumentVector::DocumentVector (indri::index::Index * index, const class indri::index::TermList * termList)
indri::api::DocumentVector::DocumentVector (indri::index::Index * index, const class indri::index::TermList * termList, std::map< int, std::string > & termStringMap)
Member Function Documentation
void indri::api::DocumentVector::_init (indri::index::Index * index, const class indri::index::TermList * termList, std::map< int, std::string > * termStringMap) [private]
const std::vector< indri::api::DocumentVector::Field > & indri::api::DocumentVector::fields () const
References _fields.
std::vector< indri::api::DocumentVector::Field > & indri::api::DocumentVector::fields ()
References _fields.
Referenced by indri::net::NetworkServerStub::_handleDocumentVectors(), CSharp_DocumentVector_fields(), documentvector_copy(), indri::server::NetworkServerProxyVectorsResponse::getResults(), and print_document_vector().
const std::vector< int > & indri::api::DocumentVector::positions () const
References _positions.
std::vector< int > & indri::api::DocumentVector::positions ()
References _positions.
Referenced by indri::query::RelevanceModel::_countGrams(), indri::net::NetworkServerStub::_handleDocumentVectors(), CSharp_DocumentVector_positions(), documentvector_copy(), indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::query::QueryExpander::getVocabulary(), and print_document_vector().
const std::vector< std::string > & indri::api::DocumentVector::stems () const
References _stems.
std::vector< std::string > & indri::api::DocumentVector::stems ()
References _stems.
Referenced by indri::query::RelevanceModel::_countGrams(), indri::net::NetworkServerStub::_handleDocumentVectors(), CSharp_DocumentVector_stems(), documentvector_copy(), indri::query::TFIDFExpander::expand(), indri::query::PonteExpander::expand(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::query::QueryExpander::getVocabulary(), and print_document_vector().
Member Data Documentation
std::vector<Field> indri::api::DocumentVector::_fields [private]
Referenced by fields().
std::vector<int> indri::api::DocumentVector::_positions [private]
Referenced by positions().
std::vector<std::string> indri::api::DocumentVector::_stems [private]
Referenced by stems().
The documentation for this class was generated from the following files:
DocumentVector.hpp
DocumentVector.cpp