Indri: indri::lang::WeightedCombinationNode Class Reference
indri::lang::WeightedCombinationNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
const std::vector< std::pair
< double, ScoredExtentNode * > > & getChildren ()
void addChild (double weight, ScoredExtentNode *scoredNode)
void addChild (const std::string &weight, ScoredExtentNode *scoredNode)
void pack (Packer &packer)
Protected Member Functions
void _unpack (Unpacker &unpacker)
UINT64 _hashCode () const
template<class _ThisType >
void _walk (_ThisType *ptr, Walker &walker)
template<class _ThisType >
Node * _copy (_ThisType *ptr, Copier &copier)
void _childText (std::stringstream &qtext) const
Protected Attributes
std::vector< std::pair< double,
ScoredExtentNode * > > _children
Member Function Documentation
void indri::lang::WeightedCombinationNode::_childText (std::stringstream & qtext) const [inline, protected]
References _children.
Referenced by indri::lang::WPlusNode::queryText(), indri::lang::WeightNode::queryText(), indri::lang::WSumNode::queryText(), and indri::lang::WAndNode::queryText().
template<class _ThisType > Node* indri::lang::WeightedCombinationNode::_copy (_ThisType * ptr, Copier & copier) [inline, protected]
References _children, indri::lang::Copier::after(), indri::lang::Copier::before(), and indri::lang::Node::nodeName().
Referenced by indri::lang::WPlusNode::copy(), indri::lang::WeightNode::copy(), indri::lang::WSumNode::copy(), and indri::lang::WAndNode::copy().
UINT64 indri::lang::WeightedCombinationNode::_hashCode () const [inline, protected]
References _children.
Referenced by indri::lang::WPlusNode::hashCode(), indri::lang::WeightNode::hashCode(), indri::lang::WSumNode::hashCode(), and indri::lang::WAndNode::hashCode().
void indri::lang::WeightedCombinationNode::_unpack (Unpacker & unpacker) [inline, protected]
References _children, indri::lang::Unpacker::getDoubleVector(), and indri::lang::Unpacker::getScoredExtentVector().
Referenced by indri::lang::WAndNode::WAndNode(), indri::lang::WeightNode::WeightNode(), indri::lang::WPlusNode::WPlusNode(), and indri::lang::WSumNode::WSumNode().
template<class _ThisType > void indri::lang::WeightedCombinationNode::_walk (_ThisType * ptr, Walker & walker) [inline, protected]
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::WPlusNode::walk(), indri::lang::WeightNode::walk(), indri::lang::WSumNode::walk(), and indri::lang::WAndNode::walk().
void indri::lang::WeightedCombinationNode::addChild (const std::string & weight, ScoredExtentNode * scoredNode) [inline]
References addChild().
void indri::lang::WeightedCombinationNode::addChild (double weight, ScoredExtentNode * scoredNode) [inline]
References _children.
Referenced by addChild(), indri::lang::WeightFoldingCopier::after(), QueryParser::sumList(), and QueryParser::weightedList().
const std::vector< std::pair<double, ScoredExtentNode*> >& indri::lang::WeightedCombinationNode::getChildren () [inline]
References _children.
Referenced by indri::lang::WeightFoldingCopier::after(), indri::lang::QueryTFWalker::after(), and indri::infnet::InferenceNetworkBuilder::after().
void indri::lang::WeightedCombinationNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
Member Data Documentation
std::vector< std::pair<double, ScoredExtentNode*> > indri::lang::WeightedCombinationNode::_children [protected]
Referenced by _childText(), _copy(), _hashCode(), _unpack(), _walk(), addChild(), getChildren(), and pack().
The documentation for this class was generated from the following file:
QuerySpec.hpp