Indri: indri::server::NetworkServerProxyMetadataResponse Class Reference
indri::server::NetworkServerProxyMetadataResponse Class Reference
Public Member Functions
NetworkServerProxyMetadataResponse (indri::net::NetworkMessageStream *stream)
~NetworkServerProxyMetadataResponse ()
std::vector< std::string > & getResults ()
Private Attributes
std::vector< std::string > _metadata
indri::net::NetworkMessageStream * _stream
Constructor & Destructor Documentation
indri::server::NetworkServerProxyMetadataResponse::NetworkServerProxyMetadataResponse (indri::net::NetworkMessageStream * stream) [inline]
indri::server::NetworkServerProxyMetadataResponse::~NetworkServerProxyMetadataResponse () [inline]
References _stream, indri::net::NetworkMessageStream::mutex(), and indri::thread::Lockable::unlock().
Member Function Documentation
std::vector<std::string>& indri::server::NetworkServerProxyMetadataResponse::getResults () [inline, virtual]
Implements indri::server::QueryServerMetadataResponse.
References _metadata, _stream, base64_decode_string(), indri::utility::Buffer::clear(), indri::xml::XMLNode::getChildren(), indri::net::XMLReplyReceiver::getReply(), indri::xml::XMLNode::getValue(), input(), and indri::net::XMLReplyReceiver::wait().
Member Data Documentation
std::vector<std::string> indri::server::NetworkServerProxyMetadataResponse::_metadata [private]
Referenced by getResults().
indri::net::NetworkMessageStream* indri::server::NetworkServerProxyMetadataResponse::_stream [private]
Referenced by getResults(), and ~NetworkServerProxyMetadataResponse().
The documentation for this class was generated from the following file:
NetworkServerProxy.cpp