Indri: indri::lang::ODNode Class Reference
indri::lang::ODNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ODNode (int windowSize, std::vector< RawExtentNode * > &children)
ODNode ()
ODNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
const std::vector
< RawExtentNode * > & getChildren () const
void setWindowSize (int windowSize)
void setWindowSize (const std::string &windowSize)
int getWindowSize () const
void addChild (RawExtentNode *node)
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
int _windowSize
std::vector< RawExtentNode * > _children
Constructor & Destructor Documentation
indri::lang::ODNode::ODNode (int windowSize, std::vector< RawExtentNode * > & children) [inline]
indri::lang::ODNode::ODNode () [inline]
Referenced by copy().
indri::lang::ODNode::ODNode (Unpacker & unpacker) [inline]
References _children, _windowSize, indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getRawExtentVector().
Member Function Documentation
void indri::lang::ODNode::addChild (RawExtentNode * node) [inline]
References _children.
Referenced by copy(), QueryParser::hyphenTerm(), QueryParser::odNode(), and NexiParser::odNode().
Node* indri::lang::ODNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _children, _windowSize, addChild(), indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), ODNode(), indri::lang::Node::setNodeName(), and setWindowSize().
const std::vector<RawExtentNode*>& indri::lang::ODNode::getChildren () const [inline]
References _children.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::lang::ODNode::getWindowSize () const [inline]
References _windowSize.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::ODNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _children, and _windowSize.
bool indri::lang::ODNode::operator== (Node & node) [inline]
References _children, _windowSize, and equal().
void indri::lang::ODNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, _windowSize, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ODNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _children, and _windowSize.
void indri::lang::ODNode::setWindowSize (const std::string & windowSize) [inline]
References setWindowSize().
void indri::lang::ODNode::setWindowSize (int windowSize) [inline]
References _windowSize.
Referenced by copy(), QueryParser::hyphenTerm(), QueryParser::odNode(), and setWindowSize().
std::string indri::lang::ODNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ODNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::UnnecessaryNodeRemoverCopier::after().
Member Data Documentation
std::vector<RawExtentNode*> indri::lang::ODNode::_children [private]
Referenced by addChild(), copy(), getChildren(), hashCode(), ODNode(), operator==(), pack(), queryText(), and walk().
int indri::lang::ODNode::_windowSize [private]
Referenced by copy(), getWindowSize(), hashCode(), ODNode(), operator==(), pack(), queryText(), and setWindowSize().
The documentation for this class was generated from the following file:
QuerySpec.hpp