Indri: indri::lang::WeightFoldingCopier Class Reference
indri::lang::WeightFoldingCopier Class Reference
#include <WeightFoldingCopier.hpp>
Public Member Functions
~WeightFoldingCopier ()
indri::lang::Node * defaultAfter (indri::lang::Node *old, indri::lang::Node *newNode)
indri::lang::Node * after (indri::lang::WeightNode *oldWeightNode, indri::lang::WeightNode *newWeightNode)
Private Attributes
std::vector< indri::lang::Node * > _nodes
Constructor & Destructor Documentation
indri::lang::WeightFoldingCopier::~WeightFoldingCopier () [inline]
References _nodes, and indri::utility::delete_vector_contents().
Member Function Documentation
indri::lang::Node* indri::lang::WeightFoldingCopier::after (indri::lang::WeightNode * oldWeightNode, indri::lang::WeightNode * newWeightNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, indri::lang::WeightedCombinationNode::addChild(), indri::lang::UnweightedCombinationNode::getChildren(), indri::lang::WeightedCombinationNode::getChildren(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
indri::lang::Node* indri::lang::WeightFoldingCopier::defaultAfter (indri::lang::Node * old, indri::lang::Node * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes.
Member Data Documentation
std::vector<indri::lang::Node*> indri::lang::WeightFoldingCopier::_nodes [private]
Referenced by after(), defaultAfter(), and ~WeightFoldingCopier().
The documentation for this class was generated from the following file:
WeightFoldingCopier.hpp