Indri: Indri::ScoredExtentResultVector Class Reference
Indri::ScoredExtentResultVector Class Reference
Classes
class ScoredExtentResultVectorEnumerator
Public Member Functions
virtual void Dispose ()
ScoredExtentResultVector (System.Collections.ICollection c)
void CopyTo (ScoredExtentResult[] array)
void CopyTo (ScoredExtentResult[] array, int arrayIndex)
void CopyTo (int index, ScoredExtentResult[] array, int arrayIndex, int count)
ScoredExtentResultVectorEnumerator GetEnumerator ()
void Clear ()
void Add (ScoredExtentResult x)
ScoredExtentResultVector ()
ScoredExtentResultVector (ScoredExtentResultVector other)
ScoredExtentResultVector (int capacity)
void AddRange (ScoredExtentResultVector values)
ScoredExtentResultVector GetRange (int index, int count)
void Insert (int index, ScoredExtentResult x)
void InsertRange (int index, ScoredExtentResultVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, ScoredExtentResultVector values)
Static Public Member Functions
static ScoredExtentResultVector Repeat (ScoredExtentResult value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
ScoredExtentResult this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal ScoredExtentResultVector (IntPtr cPtr, bool cMemoryOwn)
~ScoredExtentResultVector ()
System.Collections.Generic.IEnumerator
< ScoredExtentResult >
System.Collections.Generic.IEnumerable
< ScoredExtentResult >. GetEnumerator ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
ScoredExtentResult getitemcopy (int index)
ScoredExtentResult getitem (int index)
void setitem (int index, ScoredExtentResult val)
Static Private Member Functions
static internal HandleRef getCPtr (ScoredExtentResultVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::ScoredExtentResultVector::ScoredExtentResultVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::ScoredExtentResultVector::~ScoredExtentResultVector () [inline, private]
References Dispose().
Indri::ScoredExtentResultVector::ScoredExtentResultVector (System.Collections.ICollection c) [inline]
References Add().
Indri::ScoredExtentResultVector::ScoredExtentResultVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::ScoredExtentResultVector::ScoredExtentResultVector (ScoredExtentResultVector other) [inline]
Indri::ScoredExtentResultVector::ScoredExtentResultVector (int capacity) [inline]
Member Function Documentation
void Indri::ScoredExtentResultVector::Add (ScoredExtentResult x) [inline]
References swigCPtr.
Referenced by ScoredExtentResultVector().
void Indri::ScoredExtentResultVector::AddRange (ScoredExtentResultVector values) [inline]
References swigCPtr.
uint Indri::ScoredExtentResultVector::capacity () [inline, private]
References swigCPtr.
void Indri::ScoredExtentResultVector::Clear () [inline]
References swigCPtr.
void Indri::ScoredExtentResultVector::CopyTo (int index, ScoredExtentResult[] array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::ScoredExtentResultVector::CopyTo (ScoredExtentResult[] array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::ScoredExtentResultVector::CopyTo (ScoredExtentResult[] array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::ScoredExtentResultVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~ScoredExtentResultVector().
static internal HandleRef Indri::ScoredExtentResultVector::getCPtr (ScoredExtentResultVector obj) [inline, static, private]
References swigCPtr.
ScoredExtentResultVectorEnumerator Indri::ScoredExtentResultVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::ScoredExtentResultVector::GetEnumerator () [inline, private]
System.Collections.Generic.IEnumerator<ScoredExtentResult> System.Collections.Generic.IEnumerable<ScoredExtentResult>. Indri::ScoredExtentResultVector::GetEnumerator () [inline, private]
ScoredExtentResult Indri::ScoredExtentResultVector::getitem (int index) [inline, private]
References swigCPtr.
ScoredExtentResult Indri::ScoredExtentResultVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
ScoredExtentResultVector Indri::ScoredExtentResultVector::GetRange (int index, int count) [inline]
References ScoredExtentResultVector(), and swigCPtr.
void Indri::ScoredExtentResultVector::Insert (int index, ScoredExtentResult x) [inline]
References swigCPtr.
void Indri::ScoredExtentResultVector::InsertRange (int index, ScoredExtentResultVector values) [inline]
References swigCPtr.
void Indri::ScoredExtentResultVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::ScoredExtentResultVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static ScoredExtentResultVector Indri::ScoredExtentResultVector::Repeat (ScoredExtentResult value, int count) [inline, static]
References ScoredExtentResultVector().
void Indri::ScoredExtentResultVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::ScoredExtentResultVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::ScoredExtentResultVector::Reverse () [inline]
References swigCPtr.
void Indri::ScoredExtentResultVector::setitem (int index, ScoredExtentResult val) [inline, private]
References swigCPtr.
void Indri::ScoredExtentResultVector::SetRange (int index, ScoredExtentResultVector values) [inline]
References swigCPtr.
uint Indri::ScoredExtentResultVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::ScoredExtentResultVector::ScoredExtentResultVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::ScoredExtentResultVector::swigCMemOwn [protected]
Referenced by Dispose(), and ScoredExtentResultVector().
HandleRef Indri::ScoredExtentResultVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), RemoveAt(), RemoveRange(), reserve(), Reverse(), ScoredExtentResultVector(), setitem(), SetRange(), and size().
Property Documentation
int Indri::ScoredExtentResultVector::Capacity [get, set]
int Indri::ScoredExtentResultVector::Count [get]
Referenced by CopyTo(), Indri::ScoredExtentResultVector::ScoredExtentResultVectorEnumerator::MoveNext(), Indri::ScoredExtentResultVector::ScoredExtentResultVectorEnumerator::Reset(), and Indri::ScoredExtentResultVector::ScoredExtentResultVectorEnumerator::ScoredExtentResultVectorEnumerator().
bool Indri::ScoredExtentResultVector::IsFixedSize [get]
bool Indri::ScoredExtentResultVector::IsReadOnly [get]
bool Indri::ScoredExtentResultVector::IsSynchronized [get]
ScoredExtentResult Indri::ScoredExtentResultVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
ScoredExtentResultVector.cs