Indri: indri::lang::Unpacker Class Reference
indri::lang::Unpacker Class Reference
#include <Unpacker.hpp>
Public Member Functions
Unpacker (indri::xml::XMLNode *root)
~Unpacker ()
std::vector< Node * > unpack ()
std::string getString (const char *stringName)
UINT64 getInteger (const char *name)
double getDouble (const char *name)
RawExtentNode * getRawExtentNode (const char *name)
std::vector< RawExtentNode * > getRawExtentVector (const char *name)
std::vector< ScoredExtentNode * > getScoredExtentVector (const char *name)
std::vector< std::string > getStringVector (const char *name)
std::vector< int > getIntVector (const char *name)
std::vector< lemur::api::DOCID_T > getDocIdVector (const char *name)
std::vector< double > getDoubleVector (const char *name)
ScoredExtentNode * getScoredExtentNode (const char *name)
bool getBoolean (const char *name)
DocumentStructureNode * getDocumentStructureNode (const char *name)
template<class T >
std::vector< T * > getNodeVector (const char *name)
Private Member Functions
Node * _unpack (indri::xml::XMLNode *child)
Private Attributes
indri::xml::XMLNode * _root
std::map< std::string, class
Node * > _nodes
indri::xml::XMLNode * _current
Constructor & Destructor Documentation
indri::lang::Unpacker::Unpacker (indri::xml::XMLNode * root)
indri::lang::Unpacker::~Unpacker ()
References _nodes.
Member Function Documentation
indri::lang::Node * indri::lang::Unpacker::_unpack (indri::xml::XMLNode * child) [private]
References indri::xml::XMLNode::getAttribute(), and indri::lang::Node::setNodeName().
Referenced by unpack().
bool indri::lang::Unpacker::getBoolean (const char * name)
References getInteger().
Referenced by indri::lang::ContextCounterNode::ContextCounterNode(), indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode(), indri::lang::IndexTerm::IndexTerm(), and indri::lang::TermFrequencyScorerNode::TermFrequencyScorerNode().
std::vector< lemur::api::DOCID_T > indri::lang::Unpacker::getDocIdVector (const char * name)
References _current, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), and indri::xml::XMLNode::getValue().
Referenced by indri::lang::FilterNode::FilterNode().
DocumentStructureNode * indri::lang::Unpacker::getDocumentStructureNode (const char * name)
References _current, _nodes, and indri::xml::XMLNode::getChildValue().
Referenced by indri::lang::ExtentChild::ExtentChild(), indri::lang::ExtentDescendant::ExtentDescendant(), indri::lang::ExtentParent::ExtentParent(), and indri::lang::ShrinkageScorerNode::ShrinkageScorerNode().
double indri::lang::Unpacker::getDouble (const char * name)
References _current, and indri::xml::XMLNode::getAttribute().
Referenced by indri::lang::ContextCounterNode::ContextCounterNode(), indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode(), indri::lang::LengthPrior::LengthPrior(), indri::lang::RawScorerNode::RawScorerNode(), indri::lang::ShrinkageScorerNode::ShrinkageScorerNode(), and indri::lang::TermFrequencyScorerNode::TermFrequencyScorerNode().
std::vector< double > indri::lang::Unpacker::getDoubleVector (const char * name)
References _current, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), and indri::xml::XMLNode::getValue().
Referenced by indri::lang::WeightedCombinationNode::_unpack(), and indri::lang::WeightedExtentOr::WeightedExtentOr().
UINT64 indri::lang::Unpacker::getInteger (const char * name)
References _current, indri::xml::XMLNode::getAttribute(), and string_to_i64().
Referenced by indri::lang::ContextCounterNode::ContextCounterNode(), indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode(), indri::lang::FieldBetweenNode::FieldBetweenNode(), indri::lang::FieldEqualsNode::FieldEqualsNode(), indri::lang::FieldGreaterNode::FieldGreaterNode(), indri::lang::FieldLessNode::FieldLessNode(), indri::lang::FixedPassage::FixedPassage(), getBoolean(), indri::lang::ODNode::ODNode(), indri::lang::RawScorerNode::RawScorerNode(), indri::lang::TermFrequencyScorerNode::TermFrequencyScorerNode(), and indri::lang::UWNode::UWNode().
std::vector< int > indri::lang::Unpacker::getIntVector (const char * name)
References _current, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), and indri::xml::XMLNode::getValue().
template<class T > std::vector<T*> indri::lang::Unpacker::getNodeVector (const char * name) [inline]
References _current, _nodes, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), and indri::xml::XMLNode::getValue().
RawExtentNode * indri::lang::Unpacker::getRawExtentNode (const char * name)
References _current, _nodes, and indri::xml::XMLNode::getChildValue().
Referenced by indri::lang::CachedFrequencyScorerNode::CachedFrequencyScorerNode(), indri::lang::ContextCounterNode::ContextCounterNode(), indri::lang::ExtentInside::ExtentInside(), indri::lang::ExtentRestriction::ExtentRestriction(), indri::lang::FieldBetweenNode::FieldBetweenNode(), indri::lang::FieldEqualsNode::FieldEqualsNode(), indri::lang::FieldGreaterNode::FieldGreaterNode(), indri::lang::FieldLessNode::FieldLessNode(), indri::lang::FilRejNode::FilRejNode(), indri::lang::FilReqNode::FilReqNode(), indri::lang::ListAccumulator::ListAccumulator(), indri::lang::RawScorerNode::RawScorerNode(), and indri::lang::ShrinkageScorerNode::ShrinkageScorerNode().
std::vector< RawExtentNode * > indri::lang::Unpacker::getRawExtentVector (const char * name)
Referenced by indri::lang::BAndNode::BAndNode(), indri::lang::ExtentAnd::ExtentAnd(), indri::lang::ExtentOr::ExtentOr(), indri::lang::ODNode::ODNode(), indri::lang::UWNode::UWNode(), and indri::lang::WeightedExtentOr::WeightedExtentOr().
ScoredExtentNode * indri::lang::Unpacker::getScoredExtentNode (const char * name)
References _current, _nodes, and indri::xml::XMLNode::getChildValue().
Referenced by indri::lang::ContextInclusionNode::_unpack(), indri::lang::AnnotatorNode::AnnotatorNode(), indri::lang::ExtentRestriction::ExtentRestriction(), indri::lang::FilRejNode::FilRejNode(), indri::lang::FilReqNode::FilReqNode(), indri::lang::FilterNode::FilterNode(), indri::lang::FixedPassage::FixedPassage(), indri::lang::LengthPrior::LengthPrior(), indri::lang::NotNode::NotNode(), and indri::lang::ScoreAccumulatorNode::ScoreAccumulatorNode().
std::vector< ScoredExtentNode * > indri::lang::Unpacker::getScoredExtentVector (const char * name)
Referenced by indri::lang::ContextInclusionNode::_unpack(), indri::lang::WeightedCombinationNode::_unpack(), and indri::lang::UnweightedCombinationNode::_unpack().
std::string indri::lang::Unpacker::getString (const char * stringName)
References _current, and indri::xml::XMLNode::getAttribute().
Referenced by indri::lang::CachedFrequencyScorerNode::CachedFrequencyScorerNode(), indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode(), indri::lang::Field::Field(), indri::lang::IndexTerm::IndexTerm(), indri::lang::PriorNode::PriorNode(), indri::lang::RawScorerNode::RawScorerNode(), indri::lang::ShrinkageScorerNode::ShrinkageScorerNode(), indri::lang::TermFrequencyScorerNode::TermFrequencyScorerNode(), and indri::lang::WildcardTerm::WildcardTerm().
std::vector< std::string > indri::lang::Unpacker::getStringVector (const char * name)
References _current, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), and indri::xml::XMLNode::getValue().
Referenced by indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode(), and indri::lang::ShrinkageScorerNode::ShrinkageScorerNode().
std::vector< indri::lang::Node * > indri::lang::Unpacker::unpack ()
References _current, _nodes, _root, _unpack(), indri::xml::XMLNode::getAttribute(), indri::xml::XMLNode::getChildren(), and indri::lang::Node::nodeName().
Referenced by indri::net::NetworkServerStub::_handleQuery().
Member Data Documentation
indri::xml::XMLNode* indri::lang::Unpacker::_current [private]
Referenced by getDocIdVector(), getDocumentStructureNode(), getDouble(), getDoubleVector(), getInteger(), getIntVector(), getNodeVector(), getRawExtentNode(), getScoredExtentNode(), getString(), getStringVector(), and unpack().
std::map<std::string, class Node*> indri::lang::Unpacker::_nodes [private]
Referenced by getDocumentStructureNode(), getNodeVector(), getRawExtentNode(), getScoredExtentNode(), unpack(), and ~Unpacker().
indri::xml::XMLNode* indri::lang::Unpacker::_root [private]
Referenced by unpack().
The documentation for this class was generated from the following files:
Unpacker.hpp
Unpacker.cpp
UnpackerInternal.cpp