Indri: indri::file::BulkBlock Class Reference
indri::file::BulkBlock Class Reference
#include <BulkTree.hpp>
Public Member Functions
BulkBlock (bool leaf=false)
~BulkBlock ()
int count ()
bool leaf ()
bool insert (const char *key, int keyLength, const char *data, int dataLength)
bool insertFirstKey (BulkBlock &block, UINT32 blockID)
bool getIndex (int index, char *key, int &keyActual, int keyLength, char *value, int &valueActual, int valueLength)
bool findGreater (const char *key, int keyLength, char *value, int &actualLength, int valueBufferLength)
bool find (const char *key, int keyLength, char *value, int &actualLength, int valueBufferLength)
int findIndexOf (const char *key)
void clear ()
char * data ()
void setID (UINT32 id)
UINT32 getID ()
void link (BulkBlock *previous, BulkBlock *next)
void unlink ()
BulkBlock * previous ()
BulkBlock * next ()
Static Public Member Functions
static UINT64 dataSize ()
Private Member Functions
int _remainingCapacity ()
int _dataEnd ()
int _keyEnd (int index)
int _keyStart (int index)
int _valueStart (int index)
int _valueEnd (int index)
bool _canInsert (int keyLength, int dataLength)
void _storeKeyValueLength (int insertPoint, int keyLength, int valueLength)
int _compare (const char *one, int oneLength, const char *two, int twoLength)
int _find (const char *key, int keyLength, bool &exact)
Private Attributes
char * _buffer
BulkBlock * _previous
BulkBlock * _next
UINT32 _id
Constructor & Destructor Documentation
indri::file::BulkBlock::BulkBlock (bool leaf = false)
References _buffer, _next, _previous, and BULK_BLOCK_SIZE.
indri::file::BulkBlock::~BulkBlock ()
References _buffer.
Member Function Documentation
bool indri::file::BulkBlock::_canInsert (int keyLength, int dataLength) [inline, private]
References _remainingCapacity().
Referenced by insert().
int indri::file::BulkBlock::_compare (const char * one, int oneLength, const char * two, int twoLength) [inline, private]
Referenced by _find().
int indri::file::BulkBlock::_dataEnd () [inline, private]
References _valueEnd(), and count().
Referenced by _remainingCapacity(), and insert().
int indri::file::BulkBlock::_find (const char * key, int keyLength, bool & exact) [inline, private]
References _buffer, _compare(), _keyEnd(), _keyStart(), and count().
Referenced by find(), findGreater(), and findIndexOf().
int indri::file::BulkBlock::_keyEnd (int index) [inline, private]
References _buffer, BULK_BLOCK_SIZE, and count().
Referenced by _find(), _valueStart(), getIndex(), and insertFirstKey().
int indri::file::BulkBlock::_keyStart (int index) [inline, private]
References _valueEnd().
Referenced by _find(), getIndex(), and insertFirstKey().
int indri::file::BulkBlock::_remainingCapacity () [inline, private]
References _dataEnd(), BULK_BLOCK_SIZE, and count().
Referenced by _canInsert().
void indri::file::BulkBlock::_storeKeyValueLength (int insertPoint, int keyLength, int valueLength) [inline, private]
References _buffer, BULK_BLOCK_SIZE, and count().
Referenced by insert().
int indri::file::BulkBlock::_valueEnd (int index) [inline, private]
References _buffer, BULK_BLOCK_SIZE, and count().
Referenced by _dataEnd(), _keyStart(), and getIndex().
int indri::file::BulkBlock::_valueStart (int index) [inline, private]
References _keyEnd().
Referenced by getIndex().
void indri::file::BulkBlock::clear () [inline]
References _buffer, and leaf().
Referenced by indri::file::BulkTreeWriter::_flush().
int indri::file::BulkBlock::count () [inline]
References _buffer.
Referenced by _dataEnd(), _find(), _keyEnd(), _remainingCapacity(), _storeKeyValueLength(), _valueEnd(), indri::file::BulkTreeIterator::BulkTreeIterator(), getIndex(), insertFirstKey(), and indri::file::BulkTreeIterator::nextEntry().
char * indri::file::BulkBlock::data () [inline]
References _buffer.
Referenced by indri::file::BulkTreeReader::_fetch(), indri::file::BulkTreeWriter::_flush(), indri::file::BulkTreeIterator::nextEntry(), and indri::file::BulkTreeIterator::readCurrentBlockData().
UINT64 indri::file::BulkBlock::dataSize () [static]
References BULK_BLOCK_SIZE.
Referenced by indri::file::BulkTreeReader::_fetch(), indri::file::BulkTreeWriter::_flush(), indri::file::BulkTreeIterator::finished(), indri::file::BulkTreeWriter::get(), indri::file::BulkTreeIterator::nextEntry(), and indri::file::BulkTreeIterator::readCurrentBlockData().
bool indri::file::BulkBlock::find (const char * key, int keyLength, char * value, int & actualLength, int valueBufferLength)
References _find(), and getIndex().
Referenced by indri::file::BulkTreeReader::get().
bool indri::file::BulkBlock::findGreater (const char * key, int keyLength, char * value, int & actualLength, int valueBufferLength)
References _find(), and getIndex().
Referenced by indri::file::BulkTreeReader::findFirst(), and indri::file::BulkTreeReader::get().
int indri::file::BulkBlock::findIndexOf (const char * key)
returns the index of the key item (or the index before if the key does not exist)
Parameters:
key the key
Returns:
the index of the key in this block
References _find().
Referenced by indri::file::BulkTreeReader::findFirst().
UINT32 indri::file::BulkBlock::getID ()
References _id.
Referenced by indri::file::BulkTreeReader::_fetch(), and indri::file::BulkTreeReader::findFirst().
bool indri::file::BulkBlock::getIndex (int index, char * key, int & keyActual, int keyLength, char * value, int & valueActual, int valueLength)
References _buffer, _keyEnd(), _keyStart(), _valueEnd(), _valueStart(), and count().
Referenced by find(), findGreater(), and indri::file::BulkTreeIterator::get().
bool indri::file::BulkBlock::insert (const char * key, int keyLength, const char * data, int dataLength)
References _buffer, _canInsert(), _dataEnd(), and _storeKeyValueLength().
Referenced by insertFirstKey().
bool indri::file::BulkBlock::insertFirstKey (BulkBlock & block, UINT32 blockID)
References _buffer, _keyEnd(), _keyStart(), count(), and insert().
Referenced by indri::file::BulkTreeWriter::_flush().
bool indri::file::BulkBlock::leaf () [inline]
References _buffer.
Referenced by clear(), indri::file::BulkTreeReader::findFirst(), indri::file::BulkTreeReader::get(), and indri::file::BulkTreeIterator::nextEntry().
void indri::file::BulkBlock::link (BulkBlock * previous, BulkBlock * next)
References _next, and _previous.
Referenced by indri::file::BulkTreeReader::_fetch().
indri::file::BulkBlock * indri::file::BulkBlock::next ()
References _next.
indri::file::BulkBlock * indri::file::BulkBlock::previous ()
References _previous.
Referenced by indri::file::BulkTreeReader::_fetch().
void indri::file::BulkBlock::setID (UINT32 id)
References _id.
Referenced by indri::file::BulkTreeReader::_fetch().
void indri::file::BulkBlock::unlink ()
References _next, and _previous.
Referenced by indri::file::BulkTreeReader::_fetch().
Member Data Documentation
char* indri::file::BulkBlock::_buffer [private]
Referenced by _find(), _keyEnd(), _storeKeyValueLength(), _valueEnd(), BulkBlock(), clear(), count(), data(), getIndex(), insert(), insertFirstKey(), leaf(), and ~BulkBlock().
UINT32 indri::file::BulkBlock::_id [private]
Referenced by getID(), and setID().
BulkBlock* indri::file::BulkBlock::_next [private]
Referenced by BulkBlock(), link(), next(), and unlink().
BulkBlock* indri::file::BulkBlock::_previous [private]
Referenced by BulkBlock(), link(), previous(), and unlink().
The documentation for this class was generated from the following files:
BulkTree.hpp
BulkTree.cpp