Indri: indri::utility::Buffer Class Reference
indri::utility::Buffer Class Reference
#include <Buffer.hpp>
Public Member Functions
Buffer (size_t length)
Buffer ()
~Buffer ()
size_t size () const
size_t position () const
void clear ()
char * front ()
char * write (size_t length)
void unwrite (size_t length)
void grow (size_t newSize)
void grow ()
size_t remaining ()
void remove (size_t start)
void detach ()
Private Attributes
char * _buffer
size_t _size
size_t _position
Constructor & Destructor Documentation
indri::utility::Buffer::Buffer (size_t length) [inline]
indri::utility::Buffer::Buffer () [inline]
indri::utility::Buffer::~Buffer () [inline]
References _buffer.
Member Function Documentation
void indri::utility::Buffer::clear () [inline]
References _position.
Referenced by FieldModifier::_mergeData(), indri::index::DiskDocListFileIterator::_readEntry(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_storeIdEntry(), indri::index::IndexWriter::_storeStringEntry(), indri::index::IndexWriter::_writeBatch(), indri::index::IndexWriter::_writeDirectLists(), indri::collection::CompressedCollection::_writePositions(), indri::index::IndexWriter::_writeStatistics(), indri::file::SequentialReadBuffer::cache(), indri::file::SequentialReadBuffer::clear(), combineOutputFile(), combineSortedFiles(), indri::file::SequentialWriteBuffer::flush(), indri::server::NetworkServerProxyMetadataResponse::getResults(), indri::parse::HTMLParser::initialize(), keyfile_get(), keyfile_next(), indri::parse::WARCDocumentIterator::nextDocument(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::parse::PDFDocumentExtractor::open(), indri::parse::AnchorTextAnnotator::open(), indri::parse::TaggedTextParser::parse(), indri::index::DeletedDocumentList::read(), indri::parse::WARCRecord::readContent(), indri::parse::WARCRecord::readHeader(), indri::parse::URLTextAnnotator::transform(), and indri::parse::AnchorTextAnnotator::transform().
void indri::utility::Buffer::detach () [inline]
References _buffer, and _size.
Referenced by indri::server::NetworkServerProxyDocumentsResponse::getResults(), and indri::collection::CompressedCollection::retrieve().
char* indri::utility::Buffer::front () [inline]
References _buffer.
Referenced by indri::index::IndexWriter::_buildTermTranslator(), indri::index::DeletedDocumentList::_calculateDeletedCount(), indri::collection::CompressedCollection::_copyForwardLookup(), indri::parse::MboxDocumentIterator::_copyMetadata(), indri::collection::CompressedCollection::_copyReverseLookup(), indri::net::NetworkMessageStream::_findEOL(), indri::index::TermBitmap::_findInBuffer(), indri::index::DiskKeyfileVocabularyIterator::_readData(), indri::index::DiskDocListFileIterator::_readEntry(), indri::parse::WARCRecord::_readLine(), indri::parse::TaggedDocumentIterator::_readLine(), indri::parse::PageRank::_readLine(), indri::parse::AnchorTextAnnotator::_readLine(), indri::index::DiskDocListIterator::_readTermData(), indri::collection::CompressedCollection::_removeForwardLookups(), indri::collection::CompressedCollection::_removeReverseLookups(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_writeBatch(), indri::parse::Combiner::_writeCorpusTable(), indri::index::IndexWriter::_writeDirectLists(), indri::index::TermRecorder::add(), indri::index::DeletedDocumentList::append(), indri::index::TermRecorder::buildMap(), indri::utility::RVLCompressStream::data(), indri::file::SequentialWriteBuffer::flush(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::index::DeletedDocumentList::isDeleted(), indri::index::DeletedDocumentList::read_transaction::isDeleted(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), keyfile_get(), keyfile_next(), indri::index::DeletedDocumentList::markDeleted(), indri::index::DeletedDocumentList::read_transaction::nextCandidateDocument(), indri::parse::WARCDocumentIterator::nextDocument(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::file::SequentialReadBuffer::peek(), indri::file::SequentialReadBuffer::read(), indri::net::NetworkMessageStream::read(), indri::parse::WARCRecord::readContent(), remove_deleted_entries(), indri::collection::CompressedCollection::retrieve(), indri::index::TermRecorder::sort(), indri::index::DiskFrequentVocabularyIterator::startIteration(), indri::index::MemoryIndex::termList(), indri::file::SequentialWriteBuffer::write(), and indri::index::DeletedDocumentList::write().
void indri::utility::Buffer::grow () [inline]
References _size.
Referenced by write().
void indri::utility::Buffer::grow (size_t newSize) [inline]
References _buffer, _position, and _size.
Referenced by indri::collection::CompressedCollection::_copyForwardLookup(), indri::collection::CompressedCollection::_copyReverseLookup(), FieldModifier::_mergeData(), indri::parse::WARCRecord::_readLine(), indri::parse::TaggedDocumentIterator::_readLine(), indri::parse::PageRank::_readLine(), indri::parse::AnchorTextAnnotator::_readLine(), indri::collection::CompressedCollection::_removeForwardLookups(), indri::collection::CompressedCollection::_removeReverseLookups(), indri::collection::CompressedCollection::_writePositions(), indri::file::SequentialReadBuffer::cache(), indri::parse::Conflater::Conflater(), FieldModifier::FieldModifier(), indri::parse::HTMLParser::initialize(), indri::file::InternalFileBuffer::InternalFileBuffer(), keyfile_get(), keyfile_next(), indri::net::NetworkMessageStream::NetworkMessageStream(), indri::parse::TaggedTextParser::parse(), indri::net::NetworkMessageStream::read(), indri::parse::WARCRecord::readContent(), indri::parse::URLTextAnnotator::transform(), indri::parse::AnchorTextAnnotator::transform(), indri::parse::WARCDocumentIterator::WARCDocumentIterator(), and zlib_read_document().
size_t indri::utility::Buffer::position () const [inline]
References _position.
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::index::DeletedDocumentList::_calculateDeletedCount(), indri::collection::CompressedCollection::_copyForwardLookup(), indri::collection::CompressedCollection::_copyReverseLookup(), indri::index::TermBitmap::_findInBuffer(), indri::index::DeletedDocumentList::_grow(), indri::index::DiskDocListFileIterator::_readEntry(), indri::parse::WARCRecord::_readLine(), indri::parse::TaggedDocumentIterator::_readLine(), indri::parse::PageRank::_readLine(), indri::parse::AnchorTextAnnotator::_readLine(), indri::index::DiskDocListIterator::_readTermData(), indri::collection::CompressedCollection::_removeReverseLookups(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_writeBatch(), indri::index::IndexWriter::_writeDirectLists(), indri::index::MemoryIndex::_writeDocumentTermList(), indri::index::IndexWriter::_writeFieldList(), indri::parse::Combiner::url_entry::addLink(), indri::index::DeletedDocumentList::append(), buffer_write(), indri::utility::RVLCompressStream::dataSize(), indri::file::SequentialWriteBuffer::flush(), indri::file::SequentialWriteBuffer::flushRegion(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::index::DeletedDocumentList::isDeleted(), indri::index::DeletedDocumentList::read_transaction::isDeleted(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), indri::index::DeletedDocumentList::markDeleted(), indri::index::TermRecorder::memorySize(), indri::index::DeletedDocumentList::read_transaction::nextCandidateDocument(), indri::parse::WARCDocumentIterator::nextDocument(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::file::SequentialReadBuffer::peek(), indri::file::SequentialReadBuffer::read(), remaining(), remove_deleted_entries(), indri::index::DiskFrequentVocabularyIterator::startIteration(), indri::index::MemoryIndex::termList(), indri::file::SequentialWriteBuffer::unwrite(), indri::file::SequentialWriteBuffer::write(), indri::index::DeletedDocumentList::write(), and zlib_read_document().
size_t indri::utility::Buffer::remaining () [inline]
References position(), and size().
void indri::utility::Buffer::remove (size_t start) [inline]
References _buffer, and _position.
Referenced by indri::net::NetworkMessageStream::_cleanBuffer().
size_t indri::utility::Buffer::size () const [inline]
References _size.
Referenced by indri::index::DiskKeyfileVocabularyIterator::_readData(), indri::parse::WARCRecord::_readLine(), indri::parse::TaggedDocumentIterator::_readLine(), indri::parse::PageRank::_readLine(), indri::parse::AnchorTextAnnotator::_readLine(), indri::collection::CompressedCollection::_removeForwardLookups(), indri::index::DeletedDocumentList::append(), keyfile_get(), keyfile_next(), indri::file::SequentialReadBuffer::peek(), indri::net::NetworkMessageStream::read(), remaining(), indri::index::DiskFrequentVocabularyIterator::startIteration(), indri::file::SequentialWriteBuffer::write(), and zlib_read_document().
void indri::utility::Buffer::unwrite (size_t length) [inline]
References _position.
Referenced by indri::parse::WARCRecord::_readLine(), indri::parse::TaggedDocumentIterator::_readLine(), indri::parse::PageRank::_readLine(), indri::parse::AnchorTextAnnotator::_readLine(), indri::parse::Combiner::url_entry::addLink(), buffer_write(), indri::file::SequentialReadBuffer::cache(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::utility::RVLCompressStream::operator<<(), remove_deleted_entries(), indri::parse::Combiner::sortCorpusFiles(), indri::file::SequentialWriteBuffer::unwrite(), and zlib_read_document().
char* indri::utility::Buffer::write (size_t length) [inline]
References _buffer, _position, _size, and grow().
Referenced by indri::parse::MboxDocumentIterator::_copyMetadata(), indri::collection::CompressedCollection::_copyReverseLookup(), indri::parse::AnchorTextAnnotator::_fetchText(), indri::index::DeletedDocumentList::_grow(), FieldModifier::_mergeData(), indri::index::DiskDocListFileIterator::_readEntry(), indri::parse::WARCRecord::_readLine(), indri::parse::TaggedDocumentIterator::_readLine(), indri::parse::PageRank::_readLine(), indri::parse::AnchorTextAnnotator::_readLine(), indri::index::DiskDocListIterator::_readTermData(), indri::parse::Conflater::_strdup(), indri::index::IndexWriter::_writeDirectLists(), indri::index::TermRecorder::add(), indri::index::TermBitmap::add(), indri::parse::Combiner::url_entry::addLink(), buffer_write(), indri::file::SequentialReadBuffer::cache(), indri::index::DiskKeyfileVocabularyIterator::DiskKeyfileVocabularyIterator(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::parse::HTMLParser::handleTag(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), keyfile_get(), keyfile_next(), indri::parse::WARCDocumentIterator::nextDocument(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::TaggedDocumentIterator::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), indri::parse::MboxDocumentIterator::nextDocument(), indri::utility::RVLCompressStream::operator<<(), indri::net::NetworkMessageStream::read(), indri::index::DeletedDocumentList::read(), indri::parse::WARCRecord::readContent(), indri::parse::Combiner::sortCorpusFiles(), indri::index::DiskFrequentVocabularyIterator::startIteration(), indri::parse::URLTextAnnotator::transform(), indri::file::SequentialWriteBuffer::write(), indri::parse::TagList::writeMetadataList(), and zlib_read_document().
Member Data Documentation
char* indri::utility::Buffer::_buffer [private]
Referenced by detach(), front(), grow(), remove(), write(), and ~Buffer().
size_t indri::utility::Buffer::_position [private]
Referenced by clear(), grow(), position(), remove(), unwrite(), and write().
size_t indri::utility::Buffer::_size [private]
Referenced by detach(), grow(), size(), and write().
The documentation for this class was generated from the following file:
Buffer.hpp