Indri: indri::infnet::CachedFrequencyBeliefNode Class Reference
indri::infnet::CachedFrequencyBeliefNode Class Reference
#include <CachedFrequencyBeliefNode.hpp>
Public Member Functions
CachedFrequencyBeliefNode (const std::string &name, indri::lang::ListCache::CachedList *list, indri::query::TermScoreFunction &scoreFunction, double maximumBackgroundScore, double maximumScore)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumBackgroundScore ()
double maximumScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, int begin, int end, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, int begin, int end)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Attributes
indri::query::TermScoreFunction & _function
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _extents
indri::utility::greedy_vector
< indri::index::DocumentContextCount >
::iterator _iter
indri::utility::greedy_vector
< bool > _matches
indri::lang::ListCache::CachedList * _list
double _maximumBackgroundScore
double _maximumScore
std::string _name
Constructor & Destructor Documentation
indri::infnet::CachedFrequencyBeliefNode::CachedFrequencyBeliefNode (const std::string & name, indri::lang::ListCache::CachedList * list, indri::query::TermScoreFunction & scoreFunction, double maximumBackgroundScore, double maximumScore)
References _iter, _list, indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::lang::ListCache::CachedList::entries.
Member Function Documentation
void indri::infnet::CachedFrequencyBeliefNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, int begin, int end)
const std::string & indri::infnet::CachedFrequencyBeliefNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::CachedFrequencyBeliefNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _matches, indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::CachedFrequencyBeliefNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _iter.
void indri::infnet::CachedFrequencyBeliefNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::CachedFrequencyBeliefNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumBackgroundScore.
double indri::infnet::CachedFrequencyBeliefNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumScore.
lemur::api::DOCID_T indri::infnet::CachedFrequencyBeliefNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _iter, _list, indri::utility::greedy_vector< _Type, _Count >::end(), and indri::lang::ListCache::CachedList::entries.
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::CachedFrequencyBeliefNode::score (lemur::api::DOCID_T documentID, int begin, int end, int documentLength)
References _extents, _function, _iter, _list, _maximumScore, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocumentContextCount::contextSize, indri::index::DocumentContextCount::count, indri::index::DocumentContextCount::document, indri::utility::greedy_vector< _Type, _Count >::end(), indri::lang::ListCache::CachedList::entries, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::query::TermScoreFunction::scoreOccurrence().
Member Data Documentation
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::CachedFrequencyBeliefNode::_extents [private]
Referenced by score().
indri::query::TermScoreFunction& indri::infnet::CachedFrequencyBeliefNode::_function [private]
Referenced by score().
indri::utility::greedy_vector<indri::index::DocumentContextCount>::iterator indri::infnet::CachedFrequencyBeliefNode::_iter [private]
Referenced by CachedFrequencyBeliefNode(), hasMatch(), nextCandidateDocument(), and score().
indri::lang::ListCache::CachedList* indri::infnet::CachedFrequencyBeliefNode::_list [private]
Referenced by CachedFrequencyBeliefNode(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<bool> indri::infnet::CachedFrequencyBeliefNode::_matches [private]
Referenced by hasMatch().
double indri::infnet::CachedFrequencyBeliefNode::_maximumBackgroundScore [private]
Referenced by maximumBackgroundScore().
double indri::infnet::CachedFrequencyBeliefNode::_maximumScore [private]
Referenced by maximumScore(), and score().
std::string indri::infnet::CachedFrequencyBeliefNode::_name [private]
Referenced by getName().
The documentation for this class was generated from the following files:
CachedFrequencyBeliefNode.hpp
CachedFrequencyBeliefNode.cpp