Indri: indri::lang::ContextSimpleCounterNode Class Reference
indri::lang::ContextSimpleCounterNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ContextSimpleCounterNode (const std::vector< std::string > &terms, const std::string &field, const std::string &context)
ContextSimpleCounterNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
bool hasCounts () const
bool hasContextSize () const
double getOccurrences () const
double getContextSize () const
int getDocumentOccurrences () const
int getDocumentCount () const
const std::vector< std::string > & terms () const
const std::string & field () const
const std::string & context () const
void setContextSize (double contextSize)
void setCounts (double occurrences, double contextSize, int documentOccurrences, int documentCount)
Private Attributes
std::vector< std::string > _terms
std::string _field
std::string _context
bool _hasCounts
bool _hasContextSize
double _occurrences
double _contextSize
int _documentOccurrences
int _documentCount
Constructor & Destructor Documentation
indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode (const std::vector< std::string > & terms, const std::string & field, const std::string & context) [inline]
Referenced by copy().
indri::lang::ContextSimpleCounterNode::ContextSimpleCounterNode (Unpacker & unpacker) [inline]
References _context, _contextSize, _documentCount, _documentOccurrences, _field, _hasContextSize, _hasCounts, _occurrences, _terms, indri::lang::Unpacker::getBoolean(), indri::lang::Unpacker::getDouble(), indri::lang::Unpacker::getInteger(), indri::lang::Unpacker::getString(), and indri::lang::Unpacker::getStringVector().
Member Function Documentation
const std::string& indri::lang::ContextSimpleCounterNode::context () const [inline]
References _context.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
Node* indri::lang::ContextSimpleCounterNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Copier::after(), indri::lang::Copier::before(), and ContextSimpleCounterNode().
const std::string& indri::lang::ContextSimpleCounterNode::field () const [inline]
References _field.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
double indri::lang::ContextSimpleCounterNode::getContextSize () const [inline]
References _contextSize.
int indri::lang::ContextSimpleCounterNode::getDocumentCount () const [inline]
References _documentCount.
int indri::lang::ContextSimpleCounterNode::getDocumentOccurrences () const [inline]
References _documentOccurrences.
double indri::lang::ContextSimpleCounterNode::getOccurrences () const [inline]
References _occurrences.
bool indri::lang::ContextSimpleCounterNode::hasContextSize () const [inline]
References _hasContextSize.
bool indri::lang::ContextSimpleCounterNode::hasCounts () const [inline]
References _hasCounts.
UINT64 indri::lang::ContextSimpleCounterNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
void indri::lang::ContextSimpleCounterNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _context, _contextSize, _documentCount, _documentOccurrences, _field, _hasContextSize, _hasCounts, _occurrences, _terms, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ContextSimpleCounterNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
void indri::lang::ContextSimpleCounterNode::setContextSize (double contextSize) [inline]
References _contextSize, and _hasContextSize.
Referenced by setCounts().
void indri::lang::ContextSimpleCounterNode::setCounts (double occurrences, double contextSize, int documentOccurrences, int documentCount) [inline]
References _documentCount, _documentOccurrences, _hasCounts, _occurrences, and setContextSize().
const std::vector<std::string>& indri::lang::ContextSimpleCounterNode::terms () const [inline]
References _terms.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
std::string indri::lang::ContextSimpleCounterNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ContextSimpleCounterNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
std::string indri::lang::ContextSimpleCounterNode::_context [private]
Referenced by context(), ContextSimpleCounterNode(), and pack().
double indri::lang::ContextSimpleCounterNode::_contextSize [private]
Referenced by ContextSimpleCounterNode(), getContextSize(), pack(), and setContextSize().
int indri::lang::ContextSimpleCounterNode::_documentCount [private]
Referenced by ContextSimpleCounterNode(), getDocumentCount(), pack(), and setCounts().
int indri::lang::ContextSimpleCounterNode::_documentOccurrences [private]
Referenced by ContextSimpleCounterNode(), getDocumentOccurrences(), pack(), and setCounts().
std::string indri::lang::ContextSimpleCounterNode::_field [private]
Referenced by ContextSimpleCounterNode(), field(), and pack().
bool indri::lang::ContextSimpleCounterNode::_hasContextSize [private]
Referenced by ContextSimpleCounterNode(), hasContextSize(), pack(), and setContextSize().
bool indri::lang::ContextSimpleCounterNode::_hasCounts [private]
Referenced by ContextSimpleCounterNode(), hasCounts(), pack(), and setCounts().
double indri::lang::ContextSimpleCounterNode::_occurrences [private]
Referenced by ContextSimpleCounterNode(), getOccurrences(), pack(), and setCounts().
std::vector<std::string> indri::lang::ContextSimpleCounterNode::_terms [private]
Referenced by ContextSimpleCounterNode(), pack(), and terms().
The documentation for this class was generated from the following file:
QuerySpec.hpp