Indri: indri::lang::ContextSimpleCountCollectorCopier Class Reference
indri::lang::ContextSimpleCountCollectorCopier Class Reference
#include <ContextSimpleCountCollectorCopier.hpp>
Classes
class SubtreeWalker
Public Member Functions
ContextSimpleCountCollectorCopier (indri::collection::Repository &repository)
~ContextSimpleCountCollectorCopier ()
indri::lang::Node * defaultAfter (indri::lang::Node *oldNode, indri::lang::Node *newNode)
indri::lang::Node * after (indri::lang::ContextCounterNode *contextNode, indri::lang::ContextCounterNode *newNode)
Private Attributes
std::vector< indri::lang::Node * > _newNodes
indri::collection::Repository & _repository
Constructor & Destructor Documentation
indri::lang::ContextSimpleCountCollectorCopier::ContextSimpleCountCollectorCopier (indri::collection::Repository & repository) [inline]
indri::lang::ContextSimpleCountCollectorCopier::~ContextSimpleCountCollectorCopier () [inline]
References _newNodes.
Member Function Documentation
indri::lang::Node* indri::lang::ContextSimpleCountCollectorCopier::after (indri::lang::ContextCounterNode * contextNode, indri::lang::ContextCounterNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _newNodes, _repository, indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::getField(), indri::lang::Field::getFieldName(), indri::lang::IndexTerm::getStemmed(), indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::getTerms(), indri::lang::IndexTerm::getText(), indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::hasContext(), indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::isComputable(), indri::lang::Node::nodeName(), indri::collection::Repository::processTerm(), indri::lang::Node::setNodeName(), and indri::lang::ContextCounterNode::walk().
indri::lang::Node* indri::lang::ContextSimpleCountCollectorCopier::defaultAfter (indri::lang::Node * oldNode, indri::lang::Node * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _newNodes.
Member Data Documentation
std::vector<indri::lang::Node*> indri::lang::ContextSimpleCountCollectorCopier::_newNodes [private]
Referenced by after(), defaultAfter(), and ~ContextSimpleCountCollectorCopier().
indri::collection::Repository& indri::lang::ContextSimpleCountCollectorCopier::_repository [private]
Referenced by after().
The documentation for this class was generated from the following file:
ContextSimpleCountCollectorCopier.hpp