Indri: indri::infnet::OrNode Class Reference
indri::infnet::OrNode Class Reference
#include <OrNode.hpp>
Public Member Functions
OrNode (const std::string &name)
OrNode (const std::string &name, const std::vector< BeliefNode * > &children)
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
double maximumScore ()
double maximumBackgroundScore ()
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
virtual void setSiblingsFlag (int f)
const std::string & getName () const
Private Attributes
std::vector< BeliefNode * > _children
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::OrNode::OrNode (const std::string & name)
indri::infnet::OrNode::OrNode (const std::string & name, const std::vector< BeliefNode * > & children)
References _children.
Member Function Documentation
void indri::infnet::OrNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _children, and indri::infnet::Annotator::add().
const std::string & indri::infnet::OrNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::OrNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::OrNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _children.
void indri::infnet::OrNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::OrNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children, and maximumScore().
Referenced by maximumScore().
double indri::infnet::OrNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children, and maximumBackgroundScore().
Referenced by maximumBackgroundScore().
lemur::api::DOCID_T indri::infnet::OrNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::OrNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::OrNode::setSiblingsFlag (int f) [virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _children.
Member Data Documentation
std::vector<BeliefNode*> indri::infnet::OrNode::_children [private]
Referenced by annotate(), hasMatch(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), OrNode(), score(), and setSiblingsFlag().
indri::utility::greedy_vector<bool> indri::infnet::OrNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::OrNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::OrNode::_scores [private]
Referenced by score().
The documentation for this class was generated from the following files:
OrNode.hpp
OrNode.cpp