Indri: indri::thread::Lockable Class Reference
indri::thread::Lockable Class Reference
#include <Lockable.hpp>
Public Member Functions
virtual ~Lockable ()
virtual void lock ()=0
virtual void unlock ()=0
Constructor & Destructor Documentation
virtual indri::thread::Lockable::~Lockable () [inline, virtual]
Member Function Documentation
virtual void indri::thread::Lockable::lock () [pure virtual]
Implemented in indri::thread::Mutex, indri::thread::ReaderLockable, and indri::thread::WriterLockable.
Referenced by indri::server::NetworkServerProxy::documentIDsFromMetadata(), indri::server::NetworkServerProxy::documentMetadata(), indri::server::NetworkServerProxy::documents(), indri::server::NetworkServerProxy::documentsFromMetadata(), indri::server::NetworkServerProxy::documentVectors(), indri::server::NetworkServerProxy::pathNames(), indri::server::NetworkServerProxy::runQuery(), indri::thread::ScopedLock::ScopedLock(), and indri::index::WriterIndexContext::WriterIndexContext().
virtual void indri::thread::Lockable::unlock () [pure virtual]
Implemented in indri::thread::Mutex, indri::thread::ReaderLockable, and indri::thread::WriterLockable.
Referenced by indri::thread::ScopedLock::unlock(), indri::server::NetworkServerProxyDocumentIDsResponse::~NetworkServerProxyDocumentIDsResponse(), indri::server::NetworkServerProxyDocumentsResponse::~NetworkServerProxyDocumentsResponse(), indri::server::NetworkServerProxyMetadataResponse::~NetworkServerProxyMetadataResponse(), indri::server::NetworkServerProxyResponse::~NetworkServerProxyResponse(), indri::server::NetworkServerProxyVectorsResponse::~NetworkServerProxyVectorsResponse(), indri::thread::ScopedLock::~ScopedLock(), and indri::index::WriterIndexContext::~WriterIndexContext().
The documentation for this class was generated from the following file:
Lockable.hpp