Indri: indri::lang::WeightNode Class Reference
indri::lang::WeightNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
WeightNode ()
WeightNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::WeightNode::WeightNode () [inline]
indri::lang::WeightNode::WeightNode (Unpacker & unpacker) [inline]
References indri::lang::WeightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::WeightNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_copy().
UINT64 indri::lang::WeightNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_hashCode().
std::string indri::lang::WeightNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_childText().
std::string indri::lang::WeightNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::WeightNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp