Indri: indri::infnet::ContextSimpleCountAccumulator Class Reference
indri::infnet::ContextSimpleCountAccumulator Class Reference
#include <ContextSimpleCountAccumulator.hpp>
Public Member Functions
ContextSimpleCountAccumulator (const std::string &nodeName, const std::vector< std::string > &terms, const std::string &field, const std::string &context)
const std::string & getName () const
const EvaluatorNode::MResults & getResults ()
int getDocumentOccurrences () const
int getDocumentCount () const
void indexChanged (indri::index::Index &index)
void evaluate (lemur::api::DOCID_T documentID, int documentLength)
lemur::api::DOCID_T nextCandidateDocument ()
Private Member Functions
void _computeCounts (indri::index::Index &index)
Private Attributes
std::string _name
std::vector< std::string > _terms
std::string _field
std::string _context
UINT64 _occurrences
UINT64 _size
lemur::api::DOCID_T _maximumDocument
int _documentOccurrences
int _documentCount
EvaluatorNode::MResults _results
Constructor & Destructor Documentation
indri::infnet::ContextSimpleCountAccumulator::ContextSimpleCountAccumulator (const std::string & nodeName, const std::vector< std::string > & terms, const std::string & field, const std::string & context)
Member Function Documentation
void indri::infnet::ContextSimpleCountAccumulator::_computeCounts (indri::index::Index & index) [private]
References _context, _documentCount, _documentOccurrences, _field, _occurrences, _size, _terms, indri::index::Index::documentCount(), indri::index::Index::fieldDocumentCount(), indri::index::Index::fieldTermCount(), and indri::index::Index::termCount().
Referenced by indexChanged().
void indri::infnet::ContextSimpleCountAccumulator::evaluate (lemur::api::DOCID_T documentID, int documentLength) [virtual]
Implements indri::infnet::EvaluatorNode.
int indri::infnet::ContextSimpleCountAccumulator::getDocumentCount () const
int indri::infnet::ContextSimpleCountAccumulator::getDocumentOccurrences () const
const std::string & indri::infnet::ContextSimpleCountAccumulator::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::infnet::EvaluatorNode::MResults & indri::infnet::ContextSimpleCountAccumulator::getResults () [virtual]
Implements indri::infnet::EvaluatorNode.
References _documentCount, _documentOccurrences, _occurrences, _results, and _size.
void indri::infnet::ContextSimpleCountAccumulator::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _computeCounts(), _maximumDocument, and indri::index::Index::documentMaximum().
lemur::api::DOCID_T indri::infnet::ContextSimpleCountAccumulator::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
Member Data Documentation
std::string indri::infnet::ContextSimpleCountAccumulator::_context [private]
Referenced by _computeCounts().
int indri::infnet::ContextSimpleCountAccumulator::_documentCount [private]
Referenced by _computeCounts(), and getResults().
int indri::infnet::ContextSimpleCountAccumulator::_documentOccurrences [private]
Referenced by _computeCounts(), and getResults().
std::string indri::infnet::ContextSimpleCountAccumulator::_field [private]
Referenced by _computeCounts().
lemur::api::DOCID_T indri::infnet::ContextSimpleCountAccumulator::_maximumDocument [private]
Referenced by indexChanged().
std::string indri::infnet::ContextSimpleCountAccumulator::_name [private]
Referenced by getName().
UINT64 indri::infnet::ContextSimpleCountAccumulator::_occurrences [private]
Referenced by _computeCounts(), and getResults().
EvaluatorNode::MResults indri::infnet::ContextSimpleCountAccumulator::_results [private]
Referenced by getResults().
UINT64 indri::infnet::ContextSimpleCountAccumulator::_size [private]
Referenced by _computeCounts(), and getResults().
std::vector<std::string> indri::infnet::ContextSimpleCountAccumulator::_terms [private]
Referenced by _computeCounts().
The documentation for this class was generated from the following files:
ContextSimpleCountAccumulator.hpp
ContextSimpleCountAccumulator.cpp