Indri: indri::index::DocExtentListIterator Class Reference
indri::index::DocExtentListIterator Class Reference
#include <DocExtentListIterator.hpp>
Classes
struct DocumentExtentData
Public Member Functions
virtual ~DocExtentListIterator ()
virtual void startIteration ()=0
virtual bool finished () const =0
virtual bool nextEntry ()=0
virtual bool nextEntry (lemur::api::DOCID_T documentID)=0
virtual DocumentExtentData * currentEntry ()=0
Constructor & Destructor Documentation
virtual indri::index::DocExtentListIterator::~DocExtentListIterator () [inline, virtual]
Member Function Documentation
virtual DocumentExtentData* indri::index::DocExtentListIterator::currentEntry () [pure virtual]
Implemented in indri::index::DiskDocExtentListIterator, and indri::index::DocExtentListMemoryBuilderIterator.
Referenced by indri::index::IndexWriter::_writeFieldList(), indri::infnet::FieldIteratorNode::nextCandidateDocument(), and indri::infnet::FieldIteratorNode::prepare().
virtual bool indri::index::DocExtentListIterator::finished () const [pure virtual]
Implemented in indri::index::DiskDocExtentListIterator, and indri::index::DocExtentListMemoryBuilderIterator.
Referenced by indri::index::IndexWriter::_writeFieldList().
virtual bool indri::index::DocExtentListIterator::nextEntry (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::index::DiskDocExtentListIterator, and indri::index::DocExtentListMemoryBuilderIterator.
virtual bool indri::index::DocExtentListIterator::nextEntry () [pure virtual]
Implemented in indri::index::DiskDocExtentListIterator, and indri::index::DocExtentListMemoryBuilderIterator.
Referenced by indri::index::IndexWriter::_writeFieldList().
virtual void indri::index::DocExtentListIterator::startIteration () [pure virtual]
Implemented in indri::index::DiskDocExtentListIterator, and indri::index::DocExtentListMemoryBuilderIterator.
Referenced by indri::infnet::InferenceNetwork::_indexChanged(), indri::index::IndexWriter::_writeFieldList(), and indri::infnet::FieldIteratorNode::indexChanged().
The documentation for this class was generated from the following file:
DocExtentListIterator.hpp