Indri: indri::parse::UTF8Transcoder Class Reference
indri::parse::UTF8Transcoder Class Reference
#include <UTF8Transcoder.hpp>
Public Member Functions
UTF8Transcoder ()
~UTF8Transcoder ()
void utf8_encode (UINT64 code, char *buf, int *octets)
void utf8_decode (const char *buf_in, UINT64 **codes, int *characters, int *malformed, int **offsets, int **lengths)
indri::utility::HashTable
< UINT64, const int > & unicode ()
Private Member Functions
int _count_bytes (unsigned char *buf, int index, int max_index, int how_many)
void store_interval (indri::utility::HashTable< UINT64, const int > &table, UINT64 start, UINT64 end, const int cls)
void _initHT ()
Private Attributes
indri::utility::HashTable
< UINT64, const int > u
Constructor & Destructor Documentation
indri::parse::UTF8Transcoder::UTF8Transcoder ()
References _initHT().
indri::parse::UTF8Transcoder::~UTF8Transcoder ()
Member Function Documentation
int indri::parse::UTF8Transcoder::_count_bytes (unsigned char * buf, int index, int max_index, int how_many) [private]
Referenced by utf8_decode().
void indri::parse::UTF8Transcoder::_initHT () [private]
References intervalEntry::cls, intervalEntry::end, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::size(), intervalEntry::start, store_interval(), and u.
Referenced by UTF8Transcoder().
void indri::parse::UTF8Transcoder::store_interval (indri::utility::HashTable< UINT64, const int > & table, UINT64 start, UINT64 end, const int cls) [private]
References indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert().
Referenced by _initHT().
indri::utility::HashTable<UINT64,const int>& indri::parse::UTF8Transcoder::unicode () [inline]
References u.
void indri::parse::UTF8Transcoder::utf8_decode (const char * buf_in, UINT64 ** codes, int * characters, int * malformed, int ** offsets, int ** lengths)
References _count_bytes().
Referenced by indri::parse::Arabic_Stemmer_utf8::stemTerm(), and indri::parse::UTF8CaseNormalizationTransformation::transform().
void indri::parse::UTF8Transcoder::utf8_encode (UINT64 code, char * buf, int * octets)
Referenced by indri::parse::Arabic_Stemmer_utf8::stemTerm(), and indri::parse::UTF8CaseNormalizationTransformation::transform().
Member Data Documentation
indri::utility::HashTable<UINT64,const int> indri::parse::UTF8Transcoder::u [private]
Referenced by _initHT(), and unicode().
The documentation for this class was generated from the following files:
UTF8Transcoder.hpp
UTF8Transcoder.cpp