Indri: indri::thread::ConditionVariable Class Reference
indri::thread::ConditionVariable Class Reference
#include <ConditionVariable.hpp>
Public Member Functions
ConditionVariable ()
~ConditionVariable ()
void wait (Mutex &mutex)
bool wait (Mutex &mutex, UINT64 microseconds)
void notifyOne ()
void notifyAll ()
Private Attributes
pthread_cond_t _condition
Constructor & Destructor Documentation
indri::thread::ConditionVariable::ConditionVariable () [inline]
References _condition.
indri::thread::ConditionVariable::~ConditionVariable () [inline]
References _condition.
Member Function Documentation
void indri::thread::ConditionVariable::notifyAll () [inline]
References _condition.
Referenced by QueryThread::initialize(), indri::thread::ScopedMonitor::notifyAll(), indri::thread::UtilityThread::signal(), and QueryThread::work().
void indri::thread::ConditionVariable::notifyOne () [inline]
References _condition.
Referenced by indri::thread::ReadersWritersLock::_wakeOthers(), and indri::thread::ScopedMonitor::notifyOne().
bool indri::thread::ConditionVariable::wait (Mutex & mutex, UINT64 microseconds) [inline]
References _condition, indri::thread::Mutex::_mutex, and indri::thread::Mutex::lock().
void indri::thread::ConditionVariable::wait (Mutex & mutex) [inline]
References _condition, indri::thread::Mutex::_mutex, and indri::thread::Mutex::lock().
Referenced by indri::thread::ReadersWritersLock::lockRead(), indri::thread::ReadersWritersLock::lockWrite(), main(), indri::thread::UtilityThread::run(), and indri::thread::ScopedMonitor::wait().
Member Data Documentation
pthread_cond_t indri::thread::ConditionVariable::_condition [private]
Referenced by ConditionVariable(), notifyAll(), notifyOne(), wait(), and ~ConditionVariable().
The documentation for this class was generated from the following file:
ConditionVariable.hpp