Indri: indri::index::DocListIterator Class Reference
indri::index::DocListIterator Class Reference
#include <DocListIterator.hpp>
Classes
struct DocumentData
struct TopDocument
Public Member Functions
virtual ~DocListIterator ()
virtual void startIteration ()=0
virtual TermData * termData ()=0
virtual const
indri::utility::greedy_vector
< TopDocument > & topDocuments ()=0
virtual DocumentData * currentEntry ()=0
virtual bool nextEntry ()=0
virtual bool nextEntry (lemur::api::DOCID_T documentID)=0
virtual bool finished ()=0
Constructor & Destructor Documentation
virtual indri::index::DocListIterator::~DocListIterator () [inline, virtual]
Member Function Documentation
virtual DocumentData* indri::index::DocListIterator::currentEntry () [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::infnet::TermFrequencyBeliefNode::hasMatch(), indri::infnet::TermFrequencyBeliefNode::nextCandidateDocument(), indri::infnet::DocListIteratorNode::nextCandidateDocument(), indri::index::DocListFileIterator::iterator_greater::operator()(), indri::infnet::DocListIteratorNode::prepare(), and indri::infnet::TermFrequencyBeliefNode::score().
virtual bool indri::index::DocListIterator::finished () [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
Referenced by indri::index::IndexWriter::_addInvertedListData().
virtual bool indri::index::DocListIterator::nextEntry (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
virtual bool indri::index::DocListIterator::nextEntry () [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
Referenced by indri::index::IndexWriter::_addInvertedListData().
virtual void indri::index::DocListIterator::startIteration () [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
Referenced by indri::infnet::InferenceNetwork::_indexChanged().
virtual TermData* indri::index::DocListIterator::termData () [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
Referenced by indri::infnet::TermFrequencyBeliefNode::indexChanged().
virtual const indri::utility::greedy_vector<TopDocument>& indri::index::DocListIterator::topDocuments () [pure virtual]
Implemented in indri::index::DiskDocListIterator, and indri::index::DocListMemoryBuilderIterator.
Referenced by indri::infnet::TermFrequencyBeliefNode::indexChanged(), and indri::infnet::TermFrequencyBeliefNode::topdocs().
The documentation for this class was generated from the following file:
DocListIterator.hpp