Indri: indri::infnet::WeightedAndNode Class Reference
indri::infnet::WeightedAndNode Class Reference
#include <WeightedAndNode.hpp>
Classes
struct child_type
Public Member Functions
WeightedAndNode (const std::string &name)
void addChild (double weight, BeliefNode *node)
void doneAddingChildren ()
void setSiblingsFlag (int f)
void setThreshold (double threshold)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Member Functions
void _computeQuorum ()
double _computeMaxScore (unsigned int start)
Private Attributes
std::vector< child_type > _children
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
indri::utility::greedy_vector
< lemur::api::DOCID_T > _candidates
size_t _candidatesIndex
double _threshold
double _recomputeThreshold
int _quorumIndex
Constructor & Destructor Documentation
indri::infnet::WeightedAndNode::WeightedAndNode (const std::string & name) [inline]
Member Function Documentation
double indri::infnet::WeightedAndNode::_computeMaxScore (unsigned int start) [private]
References _children.
Referenced by _computeQuorum().
void indri::infnet::WeightedAndNode::_computeQuorum () [private]
References _children, _computeMaxScore(), _quorumIndex, _recomputeThreshold, _threshold, and maximumScore().
Referenced by addChild(), indexChanged(), and setThreshold().
void indri::infnet::WeightedAndNode::addChild (double weight, BeliefNode * node)
References _children, _computeQuorum(), indri::infnet::WeightedAndNode::child_type::backgroundWeightedScore, indri::infnet::BeliefNode::maximumBackgroundScore(), indri::infnet::BeliefNode::maximumScore(), indri::infnet::WeightedAndNode::child_type::maximumWeightedScore, indri::infnet::WeightedAndNode::child_type::node, indri::infnet::BeliefNode::setSiblingsFlag(), and indri::infnet::WeightedAndNode::child_type::weight.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::WeightedAndNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _children, and indri::infnet::Annotator::add().
void indri::infnet::WeightedAndNode::doneAddingChildren ()
Referenced by indri::infnet::InferenceNetworkBuilder::after().
const std::string & indri::infnet::WeightedAndNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::WeightedAndNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _candidates, _candidatesIndex, _children, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::WeightedAndNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _candidates, _candidatesIndex, _children, and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::WeightedAndNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _candidates, _candidatesIndex, _children, _computeQuorum(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::Parameters::instance(), indri::infnet::TermFrequencyBeliefNode::maximumBackgroundScore(), indri::infnet::TermFrequencyBeliefNode::maximumScore(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::infnet::TermFrequencyBeliefNode::topdocs().
double indri::infnet::WeightedAndNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
double indri::infnet::WeightedAndNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
Referenced by _computeQuorum().
lemur::api::DOCID_T indri::infnet::WeightedAndNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _candidates, _candidatesIndex, _children, _quorumIndex, and indri::utility::greedy_vector< _Type, _Count >::size().
indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::WeightedAndNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _candidates, _candidatesIndex, _children, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::WeightedAndNode::setSiblingsFlag (int f) [virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _children.
void indri::infnet::WeightedAndNode::setThreshold (double threshold) [virtual]
Implements indri::infnet::SkippingCapableNode.
References _computeQuorum(), _recomputeThreshold, and _threshold.
Member Data Documentation
indri::utility::greedy_vector<lemur::api::DOCID_T> indri::infnet::WeightedAndNode::_candidates [private]
Referenced by hasMatch(), indexChanged(), nextCandidateDocument(), and score().
size_t indri::infnet::WeightedAndNode::_candidatesIndex [private]
Referenced by hasMatch(), indexChanged(), nextCandidateDocument(), and score().
std::vector<child_type> indri::infnet::WeightedAndNode::_children [private]
Referenced by _computeMaxScore(), _computeQuorum(), addChild(), annotate(), hasMatch(), indexChanged(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), score(), and setSiblingsFlag().
indri::utility::greedy_vector<bool> indri::infnet::WeightedAndNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::WeightedAndNode::_name [private]
Referenced by getName().
int indri::infnet::WeightedAndNode::_quorumIndex [private]
Referenced by _computeQuorum(), and nextCandidateDocument().
double indri::infnet::WeightedAndNode::_recomputeThreshold [private]
Referenced by _computeQuorum(), and setThreshold().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::WeightedAndNode::_scores [private]
Referenced by score().
double indri::infnet::WeightedAndNode::_threshold [private]
Referenced by _computeQuorum(), and setThreshold().
The documentation for this class was generated from the following files:
WeightedAndNode.hpp
WeightedAndNode.cpp