Indri: indri::utility::RVLCompressStream Class Reference
indri::utility::RVLCompressStream Class Reference
#include <RVLCompressStream.hpp>
Public Member Functions
RVLCompressStream (indri::utility::Buffer &buffer)
const char * data () const
size_t dataSize () const
RVLCompressStream & operator<< (int value)
RVLCompressStream & operator<< (unsigned int value)
RVLCompressStream & operator<< (INT64 value)
RVLCompressStream & operator<< (UINT64 value)
RVLCompressStream & operator<< (float value)
RVLCompressStream & operator<< (const char *value)
Compress a string into the buffer.
Private Attributes
indri::utility::Buffer & _buffer
Detailed Description
Provide RVL compression on a stream.
Constructor & Destructor Documentation
indri::utility::RVLCompressStream::RVLCompressStream (indri::utility::Buffer & buffer) [inline]
Initialize
Parameters:
buffer the buffer to use for compressing
Member Function Documentation
const char* indri::utility::RVLCompressStream::data () const [inline]
Returns:
the buffer
References _buffer, and indri::utility::Buffer::front().
Referenced by indri::index::IndexWriter::_storeIdEntry(), indri::index::IndexWriter::_storeStringEntry(), indri::collection::CompressedCollection::_writePositions(), and indri::index::IndexWriter::_writeStatistics().
size_t indri::utility::RVLCompressStream::dataSize () const [inline]
Returns:
the size of the data in the buffer
References _buffer, and indri::utility::Buffer::position().
Referenced by indri::index::IndexWriter::_storeIdEntry(), indri::index::IndexWriter::_storeStringEntry(), indri::collection::CompressedCollection::_writePositions(), and indri::index::IndexWriter::_writeStatistics().
RVLCompressStream& indri::utility::RVLCompressStream::operator<< (const char * value) [inline]
Compress a string into the buffer.
References _buffer, and indri::utility::Buffer::write().
RVLCompressStream& indri::utility::RVLCompressStream::operator<< (float value) [inline]
Compress a float into the buffer
Parameters:
value the value to compress
References _buffer, and indri::utility::Buffer::write().
RVLCompressStream& indri::utility::RVLCompressStream::operator<< (UINT64 value) [inline]
Compress an UINT64 into the buffer
Parameters:
value the value to compress
References _buffer, indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
RVLCompressStream& indri::utility::RVLCompressStream::operator<< (INT64 value) [inline]
Compress an INT64 into the buffer
Parameters:
value the value to compress
References _buffer, indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
RVLCompressStream& indri::utility::RVLCompressStream::operator<< (unsigned int value) [inline]
Compress an unsigned int into the buffer
Parameters:
value the value to compress
References _buffer, indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
RVLCompressStream& indri::utility::RVLCompressStream::operator<< (int value) [inline]
Compress an int into the buffer
Parameters:
value the value to compress
References _buffer, indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Member Data Documentation
indri::utility::Buffer& indri::utility::RVLCompressStream::_buffer [private]
Referenced by data(), dataSize(), and operator<<().
The documentation for this class was generated from the following file:
RVLCompressStream.hpp