Indri: indri::net::NetworkServerStub Class Reference
indri::net::NetworkServerStub Class Reference
#include <NetworkServerStub.hpp>
Public Member Functions
NetworkServerStub (indri::server::QueryServer *server, NetworkMessageStream *stream)
void request (indri::xml::XMLNode *input)
void reply (indri::xml::XMLNode *input)
void reply (const std::string &name, const void *buffer, unsigned int length)
void replyDone ()
void error (const std::string &error)
void run ()
Private Member Functions
indri::xml::XMLNode * _encodeDocument (const struct indri::api::ParsedDocument *document)
void _decodeMetadataRequest (const class indri::xml::XMLNode *request, std::string &attributeName, std::vector< std::string > &attributeValues)
void _sendDocumentsResponse (class indri::server::QueryServerDocumentsResponse *response)
void _sendNumericResponse (const char *responseName, UINT64 number)
void _handleDocuments (indri::xml::XMLNode *input)
void _handleDocumentMetadata (indri::xml::XMLNode *request)
void _handleDocumentVectors (indri::xml::XMLNode *request)
void _handleDocumentIDsFromMetadata (indri::xml::XMLNode *request)
void _handleDocumentsFromMetadata (indri::xml::XMLNode *request)
void _handleQuery (indri::xml::XMLNode *input)
void _handleTermCount (indri::xml::XMLNode *request)
void _handleTermCountUnique (indri::xml::XMLNode *request)
void _handleStemCountText (indri::xml::XMLNode *request)
void _handleTermCountText (indri::xml::XMLNode *request)
void _handleTermName (indri::xml::XMLNode *request)
void _handleTermID (indri::xml::XMLNode *request)
void _handleStemTerm (indri::xml::XMLNode *request)
void _handleTermFieldCount (indri::xml::XMLNode *request)
void _handleStemFieldCount (indri::xml::XMLNode *request)
void _handleDocumentCount (indri::xml::XMLNode *request)
void _handleDocumentTermCount (indri::xml::XMLNode *request)
void _handleDocumentStemCount (indri::xml::XMLNode *request)
void _handleDocumentLength (indri::xml::XMLNode *request)
void _handleFieldList (indri::xml::XMLNode *request)
void _handlePathNames (indri::xml::XMLNode *request)
void _handleSetMaxWildcardTerms (indri::xml::XMLNode *request)
Private Attributes
indri::server::QueryServer * _server
NetworkMessageStream * _stream
Constructor & Destructor Documentation
indri::net::NetworkServerStub::NetworkServerStub (indri::server::QueryServer * server, NetworkMessageStream * stream)
Member Function Documentation
void indri::net::NetworkServerStub::_decodeMetadataRequest (const class indri::xml::XMLNode * request, std::string & attributeName, std::vector< std::string > & attributeValues) [private]
References indri::xml::XMLNode::getChild(), and indri::xml::XMLNode::getChildValue().
Referenced by _handleDocumentIDsFromMetadata(), and _handleDocumentsFromMetadata().
indri::xml::XMLNode * indri::net::NetworkServerStub::_encodeDocument (const struct indri::api::ParsedDocument * document) [private]
References indri::xml::XMLNode::addChild(), base64_encode(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::api::ParsedDocument::content, indri::api::ParsedDocument::contentLength, indri::utility::greedy_vector< _Type, _Count >::end(), i64_to_string(), indri::api::ParsedDocument::metadata, indri::api::ParsedDocument::positions, indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::text, and indri::api::ParsedDocument::textLength.
Referenced by _sendDocumentsResponse().
void indri::net::NetworkServerStub::_handleDocumentCount (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, and indri::server::QueryServer::documentCount().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentIDsFromMetadata (indri::xml::XMLNode * request) [private]
References _decodeMetadataRequest(), _server, _stream, indri::xml::XMLNode::addChild(), indri::server::QueryServer::documentIDsFromMetadata(), indri::server::QueryServerDocumentIDsResponse::getResults(), i64_to_string(), indri::net::NetworkMessageStream::reply(), and indri::net::NetworkMessageStream::replyDone().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentLength (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::server::QueryServer::documentLength(), indri::xml::XMLNode::getValue(), and string_to_i64().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentMetadata (indri::xml::XMLNode * request) [private]
References _server, _stream, indri::xml::XMLNode::addChild(), base64_encode(), indri::server::QueryServer::documentMetadata(), indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), indri::server::QueryServerMetadataResponse::getResults(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), and string_to_i64().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocuments (indri::xml::XMLNode * input) [private]
References _sendDocumentsResponse(), _server, indri::server::QueryServer::documents(), indri::xml::XMLNode::getChildren(), and string_to_i64().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentsFromMetadata (indri::xml::XMLNode * request) [private]
References _decodeMetadataRequest(), _sendDocumentsResponse(), _server, and indri::server::QueryServer::documentsFromMetadata().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentStemCount (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::server::QueryServer::documentStemCount(), and indri::xml::XMLNode::getValue().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentTermCount (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::server::QueryServer::documentCount(), and indri::xml::XMLNode::getValue().
Referenced by request().
void indri::net::NetworkServerStub::_handleDocumentVectors (indri::xml::XMLNode * request) [private]
References _server, _stream, indri::xml::XMLNode::addChild(), base64_encode(), indri::server::QueryServer::documentVectors(), indri::api::DocumentVector::fields(), indri::xml::XMLNode::getChildren(), indri::server::QueryServerVectorsResponse::getResults(), i64_to_string(), indri::api::DocumentVector::positions(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), indri::api::DocumentVector::stems(), and string_to_i64().
Referenced by request().
void indri::net::NetworkServerStub::_handleFieldList (indri::xml::XMLNode * request) [private]
References _server, _stream, indri::xml::XMLNode::addChild(), indri::server::QueryServer::fieldList(), indri::net::NetworkMessageStream::reply(), and indri::net::NetworkMessageStream::replyDone().
Referenced by request().
void indri::net::NetworkServerStub::_handlePathNames (indri::xml::XMLNode * request) [private]
References _server, _stream, indri::xml::XMLNode::addChild(), base64_encode(), indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), indri::server::QueryServerMetadataResponse::getResults(), indri::server::QueryServer::pathNames(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), and string_to_i64().
Referenced by request().
void indri::net::NetworkServerStub::_handleQuery (indri::xml::XMLNode * input) [private]
References _server, _stream, indri::xml::XMLNode::getAttribute(), indri::server::QueryServerResponse::getResults(), indri::server::QueryServer::runQuery(), string_to_i64(), indri::lang::Unpacker::unpack(), and indri::net::QueryResponsePacker::write().
Referenced by request().
void indri::net::NetworkServerStub::_handleSetMaxWildcardTerms (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::xml::XMLNode::getValue(), indri::server::QueryServer::setMaxWildcardTerms(), and string_to_int().
Referenced by request().
void indri::net::NetworkServerStub::_handleStemCountText (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::xml::XMLNode::getValue(), and indri::server::QueryServer::stemCount().
Referenced by request().
void indri::net::NetworkServerStub::_handleStemFieldCount (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getValue(), and indri::server::QueryServer::stemFieldCount().
Referenced by request().
void indri::net::NetworkServerStub::_handleStemTerm (indri::xml::XMLNode * request) [private]
References _server, _stream, indri::xml::XMLNode::getValue(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), and indri::server::QueryServer::stemTerm().
Referenced by request().
void indri::net::NetworkServerStub::_handleTermCount (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, and indri::server::QueryServer::termCount().
Referenced by request().
void indri::net::NetworkServerStub::_handleTermCountText (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::xml::XMLNode::getValue(), and indri::server::QueryServer::termCount().
Referenced by request().
void indri::net::NetworkServerStub::_handleTermCountUnique (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, and indri::server::QueryServer::termCountUnique().
Referenced by request().
void indri::net::NetworkServerStub::_handleTermFieldCount (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getValue(), and indri::server::QueryServer::termFieldCount().
Referenced by request().
void indri::net::NetworkServerStub::_handleTermID (indri::xml::XMLNode * request) [private]
References _sendNumericResponse(), _server, indri::xml::XMLNode::getValue(), and indri::server::QueryServer::termID().
Referenced by request().
void indri::net::NetworkServerStub::_handleTermName (indri::xml::XMLNode * request) [private]
References _server, _stream, indri::xml::XMLNode::getValue(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), string_to_i64(), and indri::server::QueryServer::termName().
Referenced by request().
void indri::net::NetworkServerStub::_sendDocumentsResponse (class indri::server::QueryServerDocumentsResponse * response) [private]
References _encodeDocument(), _stream, indri::server::QueryServerDocumentsResponse::getResults(), indri::net::NetworkMessageStream::reply(), and indri::net::NetworkMessageStream::replyDone().
Referenced by _handleDocuments(), and _handleDocumentsFromMetadata().
void indri::net::NetworkServerStub::_sendNumericResponse (const char * responseName, UINT64 number) [private]
References _stream, i64_to_string(), indri::net::NetworkMessageStream::reply(), and indri::net::NetworkMessageStream::replyDone().
Referenced by _handleDocumentCount(), _handleDocumentLength(), _handleDocumentStemCount(), _handleDocumentTermCount(), _handleSetMaxWildcardTerms(), _handleStemCountText(), _handleStemFieldCount(), _handleTermCount(), _handleTermCountText(), _handleTermCountUnique(), _handleTermFieldCount(), and _handleTermID().
void indri::net::NetworkServerStub::error (const std::string & error) [virtual]
Implements indri::net::MessageStreamHandler.
void indri::net::NetworkServerStub::reply (const std::string & name, const void * buffer, unsigned int length) [virtual]
Implements indri::net::MessageStreamHandler.
void indri::net::NetworkServerStub::reply (indri::xml::XMLNode * input) [virtual]
Implements indri::net::MessageStreamHandler.
void indri::net::NetworkServerStub::replyDone () [virtual]
Implements indri::net::MessageStreamHandler.
void indri::net::NetworkServerStub::request (indri::xml::XMLNode * input) [virtual]
Implements indri::net::MessageStreamHandler.
References _handleDocumentCount(), _handleDocumentIDsFromMetadata(), _handleDocumentLength(), _handleDocumentMetadata(), _handleDocuments(), _handleDocumentsFromMetadata(), _handleDocumentStemCount(), _handleDocumentTermCount(), _handleDocumentVectors(), _handleFieldList(), _handlePathNames(), _handleQuery(), _handleSetMaxWildcardTerms(), _handleStemCountText(), _handleStemFieldCount(), _handleStemTerm(), _handleTermCount(), _handleTermCountText(), _handleTermCountUnique(), _handleTermFieldCount(), _handleTermID(), _handleTermName(), _stream, indri::net::NetworkMessageStream::error(), and indri::xml::XMLNode::getName().
void indri::net::NetworkServerStub::run ()
References _stream, indri::net::NetworkMessageStream::alive(), and indri::net::NetworkMessageStream::read().
Member Data Documentation
indri::server::QueryServer* indri::net::NetworkServerStub::_server [private]
Referenced by _handleDocumentCount(), _handleDocumentIDsFromMetadata(), _handleDocumentLength(), _handleDocumentMetadata(), _handleDocuments(), _handleDocumentsFromMetadata(), _handleDocumentStemCount(), _handleDocumentTermCount(), _handleDocumentVectors(), _handleFieldList(), _handlePathNames(), _handleQuery(), _handleSetMaxWildcardTerms(), _handleStemCountText(), _handleStemFieldCount(), _handleStemTerm(), _handleTermCount(), _handleTermCountText(), _handleTermCountUnique(), _handleTermFieldCount(), _handleTermID(), and _handleTermName().
NetworkMessageStream* indri::net::NetworkServerStub::_stream [private]
Referenced by _handleDocumentIDsFromMetadata(), _handleDocumentMetadata(), _handleDocumentVectors(), _handleFieldList(), _handlePathNames(), _handleQuery(), _handleStemTerm(), _handleTermName(), _sendDocumentsResponse(), _sendNumericResponse(), request(), and run().
The documentation for this class was generated from the following files:
NetworkServerStub.hpp
NetworkServerStub.cpp