Indri: indri::infnet::NestedListBeliefNode Class Reference
indri::infnet::NestedListBeliefNode Class Reference
#include <NestedListBeliefNode.hpp>
Public Member Functions
NestedListBeliefNode (const std::string &name, ListIteratorNode &child, ListIteratorNode *context, ListIteratorNode *raw, indri::query::TermScoreFunction &scoreFunction, double maximumBackgroundScore, double maximumScore)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumBackgroundScore ()
double maximumScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Member Functions
int _contextLength (int begin, int end)
double _contextOccurrences (int begin, int end)
double _documentOccurrences ()
Private Attributes
ListIteratorNode & _list
ListIteratorNode * _context
ListIteratorNode * _raw
double _maximumScore
double _maximumBackgroundScore
indri::query::TermScoreFunction & _scoreFunction
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
bool _documentSmoothing
Constructor & Destructor Documentation
indri::infnet::NestedListBeliefNode::NestedListBeliefNode (const std::string & name, ListIteratorNode & child, ListIteratorNode * context, ListIteratorNode * raw, indri::query::TermScoreFunction & scoreFunction, double maximumBackgroundScore, double maximumScore)
References _maximumScore, and INDRI_HUGE_SCORE.
Member Function Documentation
int indri::infnet::NestedListBeliefNode::_contextLength (int begin, int end) [inline, private]
References _context, indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by score().
double indri::infnet::NestedListBeliefNode::_contextOccurrences (int begin, int end) [inline, private]
References _list, indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by score().
double indri::infnet::NestedListBeliefNode::_documentOccurrences () [inline, private]
References _raw, indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by score().
void indri::infnet::NestedListBeliefNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _list, indri::infnet::Annotator::add(), indri::infnet::ListIteratorNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::NestedListBeliefNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::NestedListBeliefNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _list, _matches, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::NestedListBeliefNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _list, indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::NestedListBeliefNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::NestedListBeliefNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumBackgroundScore.
double indri::infnet::NestedListBeliefNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumScore.
lemur::api::DOCID_T indri::infnet::NestedListBeliefNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _list, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::NestedListBeliefNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _contextLength(), _contextOccurrences(), _documentOccurrences(), _raw, _scoreFunction, _scores, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::index::Extent::end, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::query::TermScoreFunction::scoreOccurrence().
Member Data Documentation
ListIteratorNode* indri::infnet::NestedListBeliefNode::_context [private]
Referenced by _contextLength().
bool indri::infnet::NestedListBeliefNode::_documentSmoothing [private]
ListIteratorNode& indri::infnet::NestedListBeliefNode::_list [private]
Referenced by _contextOccurrences(), annotate(), hasMatch(), and nextCandidateDocument().
indri::utility::greedy_vector<bool> indri::infnet::NestedListBeliefNode::_matches [private]
Referenced by hasMatch().
double indri::infnet::NestedListBeliefNode::_maximumBackgroundScore [private]
Referenced by maximumBackgroundScore().
double indri::infnet::NestedListBeliefNode::_maximumScore [private]
Referenced by maximumScore(), and NestedListBeliefNode().
std::string indri::infnet::NestedListBeliefNode::_name [private]
Referenced by getName().
ListIteratorNode* indri::infnet::NestedListBeliefNode::_raw [private]
Referenced by _documentOccurrences(), and score().
indri::query::TermScoreFunction& indri::infnet::NestedListBeliefNode::_scoreFunction [private]
Referenced by score().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::NestedListBeliefNode::_scores [private]
Referenced by score().
The documentation for this class was generated from the following files:
NestedListBeliefNode.hpp
NestedListBeliefNode.cpp