Indri: indri::lang::ContextInclusionNode Class Reference
indri::lang::ContextInclusionNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ContextInclusionNode ()
ContextInclusionNode (Unpacker &unpacker)
const std::vector
< ScoredExtentNode * > & getChildren ()
ScoredExtentNode * getPreserveExtentsChild ()
void addChild (ScoredExtentNode *scoredNode, bool preserveExtents=false)
std::string typeName () const
std::string queryText () const
virtual UINT64 hashCode () const
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Protected Member Functions
void _unpack (Unpacker &unpacker)
UINT64 _hashCode () const
template<class _ThisType >
void _walk (_ThisType *ptr, Walker &walker)
template<class _ThisType >
Node * _copy (_ThisType *ptr, Copier &copier)
void _childText (std::stringstream &qtext) const
Protected Attributes
std::vector< ScoredExtentNode * > _children
ScoredExtentNode * _preserveExtentsChild
Constructor & Destructor Documentation
indri::lang::ContextInclusionNode::ContextInclusionNode () [inline]
indri::lang::ContextInclusionNode::ContextInclusionNode (Unpacker & unpacker) [inline]
References _unpack().
Member Function Documentation
void indri::lang::ContextInclusionNode::_childText (std::stringstream & qtext) const [inline, protected]
References _children, _preserveExtentsChild, and indri::lang::Node::queryText().
Referenced by queryText().
template<class _ThisType > Node* indri::lang::ContextInclusionNode::_copy (_ThisType * ptr, Copier & copier) [inline, protected]
References _children, _preserveExtentsChild, indri::lang::Copier::after(), indri::lang::Copier::before(), copy(), and indri::lang::Node::nodeName().
Referenced by copy().
UINT64 indri::lang::ContextInclusionNode::_hashCode () const [inline, protected]
References _children.
Referenced by hashCode().
void indri::lang::ContextInclusionNode::_unpack (Unpacker & unpacker) [inline, protected]
References _children, _preserveExtentsChild, indri::lang::Unpacker::getScoredExtentNode(), and indri::lang::Unpacker::getScoredExtentVector().
Referenced by ContextInclusionNode().
template<class _ThisType > void indri::lang::ContextInclusionNode::_walk (_ThisType * ptr, Walker & walker) [inline, protected]
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by walk().
void indri::lang::ContextInclusionNode::addChild (ScoredExtentNode * scoredNode, bool preserveExtents = false) [inline]
References _children, and _preserveExtentsChild.
Referenced by NexiParser::query().
Node* indri::lang::ContextInclusionNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _copy().
Referenced by _copy().
const std::vector<ScoredExtentNode*>& indri::lang::ContextInclusionNode::getChildren () [inline]
References _children.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
ScoredExtentNode* indri::lang::ContextInclusionNode::getPreserveExtentsChild () [inline]
References _preserveExtentsChild.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
virtual UINT64 indri::lang::ContextInclusionNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _hashCode().
void indri::lang::ContextInclusionNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, _preserveExtentsChild, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ContextInclusionNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _childText().
std::string indri::lang::ContextInclusionNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ContextInclusionNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _walk().
Member Data Documentation
std::vector<ScoredExtentNode*> indri::lang::ContextInclusionNode::_children [protected]
Referenced by _childText(), _copy(), _hashCode(), _unpack(), _walk(), addChild(), getChildren(), and pack().
ScoredExtentNode* indri::lang::ContextInclusionNode::_preserveExtentsChild [protected]
Referenced by _childText(), _copy(), _unpack(), addChild(), getPreserveExtentsChild(), and pack().
The documentation for this class was generated from the following file:
QuerySpec.hpp