Indri: indri::lang::OrNode Class Reference
indri::lang::OrNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
OrNode ()
OrNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::OrNode::OrNode () [inline]
indri::lang::OrNode::OrNode (Unpacker & unpacker) [inline]
References indri::lang::UnweightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::OrNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_copy().
UINT64 indri::lang::OrNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_hashCode().
std::string indri::lang::OrNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_childText().
std::string indri::lang::OrNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::OrNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp