Indri: indri::infnet::BooleanAndNode Class Reference
indri::infnet::BooleanAndNode Class Reference
#include <BooleanAndNode.hpp>
Public Member Functions
BooleanAndNode (const std::string &name, std::vector< ListIteratorNode * > &children)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
std::vector< ListIteratorNode * > _lists
std::string _name
indri::utility::greedy_vector
< indri::index::Extent > _extents
Constructor & Destructor Documentation
indri::infnet::BooleanAndNode::BooleanAndNode (const std::string & name, std::vector< ListIteratorNode * > & children)
Member Function Documentation
void indri::infnet::BooleanAndNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, and indri::infnet::Annotator::addMatches().
indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::BooleanAndNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
Referenced by prepare().
const std::string & indri::infnet::BooleanAndNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::BooleanAndNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
lemur::api::DOCID_T indri::infnet::BooleanAndNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _lists.
void indri::infnet::BooleanAndNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _extents, _lists, indri::utility::greedy_vector< _Type, _Count >::clear(), extents(), indri::infnet::ListIteratorNode::initpointer(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::BooleanAndNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
std::vector<ListIteratorNode*> indri::infnet::BooleanAndNode::_lists [private]
Referenced by nextCandidateDocument(), and prepare().
std::string indri::infnet::BooleanAndNode::_name [private]
Referenced by getName().
The documentation for this class was generated from the following files:
BooleanAndNode.hpp
BooleanAndNode.cpp