Indri: indri::collection::CompressedCollection Class Reference
indri::collection::CompressedCollection Class Reference
#include <CompressedCollection.hpp>
Public Member Functions
CompressedCollection ()
~CompressedCollection ()
void create (const std::string &fileName)
void create (const std::string &fileName, const std::vector< std::string > &indexedFields)
void create (const std::string &fileName, const std::vector< std::string > &forwardIndexedFields, const std::vector< std::string > &reverseIndexedFields, bool storeDocs=true)
void reopen (const std::string &fileName)
void open (const std::string &fileName)
void openRead (const std::string &fileName)
void close ()
bool exists (lemur::api::DOCID_T documentID)
indri::api::ParsedDocument * retrieve (lemur::api::DOCID_T documentID)
std::string retrieveMetadatum (lemur::api::DOCID_T documentID, const std::string &attributeName)
std::vector
< indri::api::ParsedDocument * > retrieveByMetadatum (const std::string &attributeName, const std::string &value)
std::vector< lemur::api::DOCID_T > retrieveIDByMetadatum (const std::string &attributeName, const std::string &value)
void addDocument (lemur::api::DOCID_T documentID, indri::api::ParsedDocument *document)
void compact (indri::index::DeletedDocumentList &deletedList)
void append (indri::collection::CompressedCollection &other, indri::index::DeletedDocumentList &deletedList, lemur::api::DOCID_T documentOffset)
std::vector< std::string > forwardFields ()
std::vector< std::string > reverseFields ()
Private Member Functions
void _writePositions (indri::api::ParsedDocument *document, int &keyLength, int &valueLength)
void _writeMetadataItem (indri::api::ParsedDocument *document, int i, int &keyLength, int &valueLength)
void _writeText (indri::api::ParsedDocument *document, int &keyLength, int &valueLength)
void _writeContent (indri::api::ParsedDocument *document, int &keyLength, int &valueLength)
void _writeContentLength (indri::api::ParsedDocument *document, int &keyLength, int &valueLength)
void _readPositions (indri::api::ParsedDocument *document, const void *positionData, int positionDataLength)
void _removeForwardLookups (indri::index::DeletedDocumentList &deletedList, lemur::file::Keyfile &keyfile)
void _removeReverseLookups (indri::index::DeletedDocumentList &deletedList, lemur::file::Keyfile &keyfile)
void _copyForwardLookup (const std::string &name, lemur::file::Keyfile &other, indri::index::DeletedDocumentList &deletedList, lemur::api::DOCID_T documentOffset)
void _copyReverseLookup (const std::string &name, lemur::file::Keyfile &other, indri::index::DeletedDocumentList &deletedList, lemur::api::DOCID_T documentOffset)
void _copyStorageEntry (indri::file::SequentialReadBuffer *input, indri::file::SequentialWriteBuffer *output, int key, UINT64 position, UINT64 length, lemur::file::Keyfile &lookup)
void _copyStorageData (indri::file::SequentialReadBuffer *input, indri::file::SequentialWriteBuffer *output, indri::index::DeletedDocumentList &deletedList, lemur::api::DOCID_T documentOffset, lemur::file::Keyfile &sourceLookup, lemur::file::Keyfile &destLookup, UINT64 storageLength)
void _copyForwardLookup (const std::string &name, lemur::file::Keyfile &other, lemur::api::DOCID_T documentOffset)
Private Attributes
indri::thread::Mutex _lock
std::string _basePath
lemur::file::Keyfile _lookup
indri::file::File _storage
indri::file::SequentialWriteBuffer * _output
indri::utility::Buffer _positionsBuffer
z_stream_p _stream
indri::utility::HashTable
< const char
*, lemur::file::Keyfile * > _reverseLookups
indri::utility::HashTable
< const char
*, lemur::file::Keyfile * > _forwardLookups
String_set * _strings
bool _storeDocs
Constructor & Destructor Documentation
indri::collection::CompressedCollection::CompressedCollection ()
References _output, _stream, _strings, zlib_alloc(), and zlib_free().
indri::collection::CompressedCollection::~CompressedCollection ()
References _output, _stream, _strings, and close().
Member Function Documentation
void indri::collection::CompressedCollection::_copyForwardLookup (const std::string & name, lemur::file::Keyfile & other, lemur::api::DOCID_T documentOffset) [private]
void indri::collection::CompressedCollection::_copyForwardLookup (const std::string & name, lemur::file::Keyfile & other, indri::index::DeletedDocumentList & deletedList, lemur::api::DOCID_T documentOffset) [private]
References _forwardLookups, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::Buffer::front(), indri::index::DeletedDocumentList::getReadTransaction(), indri::utility::Buffer::grow(), indri::index::DeletedDocumentList::read_transaction::isDeleted(), keyfile_next(), and indri::utility::Buffer::position().
Referenced by append().
void indri::collection::CompressedCollection::_copyReverseLookup (const std::string & name, lemur::file::Keyfile & other, indri::index::DeletedDocumentList & deletedList, lemur::api::DOCID_T documentOffset) [private]
References _reverseLookups, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::Buffer::front(), indri::utility::Buffer::grow(), keyfile_get(), keyfile_next(), indri::utility::Buffer::position(), remove_deleted_entries(), and indri::utility::Buffer::write().
Referenced by append().
void indri::collection::CompressedCollection::_copyStorageData (indri::file::SequentialReadBuffer * input, indri::file::SequentialWriteBuffer * output, indri::index::DeletedDocumentList & deletedList, lemur::api::DOCID_T documentOffset, lemur::file::Keyfile & sourceLookup, lemur::file::Keyfile & destLookup, UINT64 storageLength) [private]
References _copyStorageEntry(), indri::file::SequentialWriteBuffer::flush(), and indri::index::DeletedDocumentList::isDeleted().
Referenced by append(), and compact().
void indri::collection::CompressedCollection::_copyStorageEntry (indri::file::SequentialReadBuffer * input, indri::file::SequentialWriteBuffer * output, int key, UINT64 position, UINT64 length, lemur::file::Keyfile & lookup) [private]
References indri::file::SequentialReadBuffer::read(), indri::file::SequentialReadBuffer::seek(), indri::file::SequentialWriteBuffer::tell(), and indri::file::SequentialWriteBuffer::write().
Referenced by _copyStorageData().
void indri::collection::CompressedCollection::_readPositions (indri::api::ParsedDocument * document, const void * positionData, int positionDataLength) [private]
References indri::parse::TermExtent::begin, indri::utility::RVLDecompressStream::done(), indri::parse::TermExtent::end, indri::api::ParsedDocument::positions, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by retrieve().
void indri::collection::CompressedCollection::_removeForwardLookups (indri::index::DeletedDocumentList & deletedList, lemur::file::Keyfile & keyfile) [private]
References indri::utility::Buffer::front(), indri::index::DeletedDocumentList::getReadTransaction(), indri::utility::Buffer::grow(), indri::index::DeletedDocumentList::isDeleted(), and indri::utility::Buffer::size().
Referenced by compact().
void indri::collection::CompressedCollection::_removeReverseLookups (indri::index::DeletedDocumentList & deletedList, lemur::file::Keyfile & keyfile) [private]
References indri::utility::Buffer::front(), indri::index::DeletedDocumentList::getReadTransaction(), indri::utility::Buffer::grow(), keyfile_next(), indri::utility::Buffer::position(), and remove_deleted_entries().
Referenced by compact().
void indri::collection::CompressedCollection::_writeContent (indri::api::ParsedDocument * document, int & keyLength, int & valueLength) [private]
References _output, _stream, indri::api::ParsedDocument::content, CONTENT_KEY, indri::api::ParsedDocument::text, and zlib_deflate().
Referenced by addDocument().
void indri::collection::CompressedCollection::_writeContentLength (indri::api::ParsedDocument * document, int & keyLength, int & valueLength) [private]
References _output, _stream, indri::api::ParsedDocument::contentLength, CONTENTLENGTH_KEY, and zlib_deflate().
Referenced by addDocument().
void indri::collection::CompressedCollection::_writeMetadataItem (indri::api::ParsedDocument * document, int i, int & keyLength, int & valueLength) [private]
References _output, _stream, indri::api::ParsedDocument::metadata, and zlib_deflate().
Referenced by addDocument().
void indri::collection::CompressedCollection::_writePositions (indri::api::ParsedDocument * document, int & keyLength, int & valueLength) [private]
References _output, _positionsBuffer, _stream, indri::parse::TermExtent::begin, indri::utility::Buffer::clear(), indri::utility::RVLCompressStream::data(), indri::utility::RVLCompressStream::dataSize(), indri::parse::TermExtent::end, indri::utility::Buffer::grow(), indri::api::ParsedDocument::positions, POSITIONS_KEY, indri::utility::greedy_vector< _Type, _Count >::size(), and zlib_deflate().
Referenced by addDocument().
void indri::collection::CompressedCollection::_writeText (indri::api::ParsedDocument * document, int & keyLength, int & valueLength) [private]
References _output, _stream, indri::api::ParsedDocument::text, TEXT_KEY, indri::api::ParsedDocument::textLength, and zlib_deflate().
Referenced by addDocument().
void indri::collection::CompressedCollection::addDocument (lemur::api::DOCID_T documentID, indri::api::ParsedDocument * document) [virtual]
Implements indri::collection::Collection.
References _forwardLookups, _lock, _lookup, _output, _reverseLookups, _storeDocs, _stream, _writeContent(), _writeContentLength(), _writeMetadataItem(), _writePositions(), _writeText(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::greedy_vector< _Type, _Count >::front(), indri::api::ParsedDocument::metadata, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::resize(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::file::SequentialWriteBuffer::tell(), zlib_alloc(), zlib_deflate_finish(), and zlib_free().
Referenced by indri::collection::Repository::addDocument().
void indri::collection::CompressedCollection::append (indri::collection::CompressedCollection & other, indri::index::DeletedDocumentList & deletedList, lemur::api::DOCID_T documentOffset)
References _copyForwardLookup(), _copyReverseLookup(), _copyStorageData(), _forwardLookups, _lock, _lookup, _output, _reverseLookups, _storage, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::file::SequentialWriteBuffer::flush(), input(), and indri::file::File::size().
void indri::collection::CompressedCollection::close ()
References _forwardLookups, _lookup, _output, _reverseLookups, _storage, _strings, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::clear(), indri::file::File::close(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), and indri::file::SequentialWriteBuffer::flush().
Referenced by indri::collection::Repository::_mergeCompressedCollections(), compact(), reopen(), and ~CompressedCollection().
void indri::collection::CompressedCollection::compact (indri::index::DeletedDocumentList & deletedList)
References _basePath, _copyStorageData(), _forwardLookups, _lock, _lookup, _output, _removeForwardLookups(), _removeReverseLookups(), _reverseLookups, _storage, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), close(), indri::file::File::close(), indri::file::Path::combine(), indri::file::File::create(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::file::SequentialWriteBuffer::flush(), input(), open(), indri::file::Path::rename(), and indri::file::File::size().
Referenced by _recoverRepository(), and indri::collection::Repository::compact().
void indri::collection::CompressedCollection::create (const std::string & fileName, const std::vector< std::string > & forwardIndexedFields, const std::vector< std::string > & reverseIndexedFields, bool storeDocs = true)
References _basePath, _forwardLookups, _lookup, _output, _reverseLookups, _storage, _storeDocs, _strings, indri::api::Parameters::append(), indri::file::Path::combine(), indri::file::File::create(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::api::Parameters::set(), and indri::api::Parameters::writeFile().
void indri::collection::CompressedCollection::create (const std::string & fileName, const std::vector< std::string > & indexedFields)
References create().
void indri::collection::CompressedCollection::create (const std::string & fileName)
Referenced by indri::collection::Repository::create(), and create().
bool indri::collection::CompressedCollection::exists (lemur::api::DOCID_T documentID)
References _lock, and _lookup.
Referenced by _recoverRepository().
std::vector< std::string > indri::collection::CompressedCollection::forwardFields ()
References _forwardLookups, and keys_to_vector().
Referenced by indri::collection::Repository::_mergeCompressedCollections().
void indri::collection::CompressedCollection::open (const std::string & fileName)
References _basePath, _forwardLookups, _lookup, _output, _reverseLookups, _storage, _storeDocs, _strings, indri::file::Path::combine(), indri::api::Parameters::exists(), indri::api::Parameters::get(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::api::Parameters::loadFile(), indri::file::File::open(), and indri::api::Parameters::size().
Referenced by compact(), indri::collection::Repository::open(), and reopen().
void indri::collection::CompressedCollection::openRead (const std::string & fileName)
References _basePath, _forwardLookups, _lookup, _reverseLookups, _storage, _strings, indri::file::Path::combine(), indri::api::Parameters::exists(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::api::Parameters::loadFile(), indri::file::File::openRead(), and indri::api::Parameters::size().
Referenced by indri::collection::Repository::_mergeCompressedCollections(), and indri::collection::Repository::openRead().
void indri::collection::CompressedCollection::reopen (const std::string & fileName)
References _lock, close(), and open().
Referenced by indri::collection::Repository::_checkpoint().
indri::api::ParsedDocument * indri::collection::CompressedCollection::retrieve (lemur::api::DOCID_T documentID) [virtual]
Implements indri::collection::Collection.
References _lock, _lookup, _output, _readPositions(), _storage, indri::api::ParsedDocument::content, CONTENT_KEY, indri::api::ParsedDocument::contentLength, CONTENTLENGTH_KEY, copy_quad(), indri::utility::Buffer::detach(), indri::file::SequentialWriteBuffer::flush(), indri::utility::Buffer::front(), i64_to_string(), indri::parse::MetadataPair::key, indri::api::ParsedDocument::metadata, POSITIONS_KEY, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ParsedDocument::text, TEXT_KEY, indri::api::ParsedDocument::textLength, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, zlib_alloc(), zlib_free(), and zlib_read_document().
Referenced by indri::server::LocalQueryServer::document(), print_document_data(), print_document_text(), retrieveByMetadatum(), and retrieveMetadatum().
std::vector< indri::api::ParsedDocument * > indri::collection::CompressedCollection::retrieveByMetadatum (const std::string & attributeName, const std::string & value)
References retrieve(), and retrieveIDByMetadatum().
Referenced by indri::server::LocalQueryServer::documentsFromMetadata().
std::vector< lemur::api::DOCID_T > indri::collection::CompressedCollection::retrieveIDByMetadatum (const std::string & attributeName, const std::string & value)
References _lock, _reverseLookups, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
Referenced by indri::server::LocalQueryServer::documentIDsFromMetadata(), print_document_id(), and retrieveByMetadatum().
std::string indri::collection::CompressedCollection::retrieveMetadatum (lemur::api::DOCID_T documentID, const std::string & attributeName)
References _forwardLookups, _lock, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::api::ParsedDocument::metadata, retrieve(), indri::thread::ScopedLock::unlock(), and indri::parse::MetadataPair::value.
Referenced by indri::server::LocalQueryServer::documentMetadatum(), and print_document_name().
std::vector< std::string > indri::collection::CompressedCollection::reverseFields ()
References _reverseLookups, and keys_to_vector().
Referenced by indri::collection::Repository::_mergeCompressedCollections().
Member Data Documentation
std::string indri::collection::CompressedCollection::_basePath [private]
Referenced by compact(), create(), open(), and openRead().
indri::utility::HashTable<const char*, lemur::file::Keyfile*> indri::collection::CompressedCollection::_forwardLookups [private]
Referenced by _copyForwardLookup(), addDocument(), append(), close(), compact(), create(), forwardFields(), open(), openRead(), and retrieveMetadatum().
indri::thread::Mutex indri::collection::CompressedCollection::_lock [private]
Referenced by addDocument(), append(), compact(), exists(), reopen(), retrieve(), retrieveIDByMetadatum(), and retrieveMetadatum().
lemur::file::Keyfile indri::collection::CompressedCollection::_lookup [private]
Referenced by addDocument(), append(), close(), compact(), create(), exists(), open(), openRead(), and retrieve().
indri::file::SequentialWriteBuffer* indri::collection::CompressedCollection::_output [private]
Referenced by _writeContent(), _writeContentLength(), _writeMetadataItem(), _writePositions(), _writeText(), addDocument(), append(), close(), compact(), CompressedCollection(), create(), open(), retrieve(), and ~CompressedCollection().
indri::utility::Buffer indri::collection::CompressedCollection::_positionsBuffer [private]
Referenced by _writePositions().
indri::utility::HashTable<const char*, lemur::file::Keyfile*> indri::collection::CompressedCollection::_reverseLookups [private]
Referenced by _copyReverseLookup(), addDocument(), append(), close(), compact(), create(), open(), openRead(), retrieveIDByMetadatum(), and reverseFields().
indri::file::File indri::collection::CompressedCollection::_storage [private]
Referenced by append(), close(), compact(), create(), open(), openRead(), and retrieve().
bool indri::collection::CompressedCollection::_storeDocs [private]
Referenced by addDocument(), create(), and open().
z_stream_p indri::collection::CompressedCollection::_stream [private]
Referenced by _writeContent(), _writeContentLength(), _writeMetadataItem(), _writePositions(), _writeText(), addDocument(), CompressedCollection(), and ~CompressedCollection().
String_set* indri::collection::CompressedCollection::_strings [private]
Referenced by close(), CompressedCollection(), create(), open(), openRead(), and ~CompressedCollection().
The documentation for this class was generated from the following files:
CompressedCollection.hpp
CompressedCollection.cpp