Indri: indri::infnet::WPlusNode Class Reference
indri::infnet::WPlusNode Class Reference
#include <WPlusNode.hpp>
Public Member Functions
WPlusNode (const std::string &name)
void addChild (double weight, BeliefNode *child)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Attributes
std::vector< BeliefNode * > _children
std::vector< double > _weights
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::WPlusNode::WPlusNode (const std::string & name) [inline]
Member Function Documentation
void indri::infnet::WPlusNode::addChild (double weight, BeliefNode * child)
References _children, and _weights.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::WPlusNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _children, and indri::infnet::Annotator::add().
const std::string & indri::infnet::WPlusNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::WPlusNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::WPlusNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _children.
void indri::infnet::WPlusNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::WPlusNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
double indri::infnet::WPlusNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
lemur::api::DOCID_T indri::infnet::WPlusNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::WPlusNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
std::vector<BeliefNode*> indri::infnet::WPlusNode::_children [private]
Referenced by addChild(), annotate(), hasMatch(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<bool> indri::infnet::WPlusNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::WPlusNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::WPlusNode::_scores [private]
Referenced by score().
std::vector<double> indri::infnet::WPlusNode::_weights [private]
Referenced by addChild().
The documentation for this class was generated from the following files:
WPlusNode.hpp
WPlusNode.cpp