Indri: indri::parse::Combiner Class Reference
indri::parse::Combiner Class Reference
#include <Combiner.hpp>
Classes
struct strcompst
struct strhash
struct url_entry
Public Member Functions
Combiner (int bins=10)
void combineRedirectDestinationBuckets (const std::string &tmpPath)
void combineBuckets (const std::string &outputPath, const std::string &tmpPath)
void hashRedirectTargets (const std::string &bucketPath, const std::string &redirectsPath)
void hashToBuckets (const std::string &bucketPath, const std::string &inputPath)
void sortCorpusFiles (const std::string &outputPath, const std::string &preSortPath, const std::string &inputPath)
Private Types
typedef
indri::utility::HashTable
< char *, url_entry *, strhash,
strcompst > UrlEntryTable
typedef
indri::utility::HashTable
< char *, std::vector
< url_entry * >, strhash,
strcompst > UrlEntryVectorTable
Private Member Functions
url_entry * _newUrlEntry (const char *url, const char *corpusPath, const char *docNo)
void _deleteUrlEntry (void *buffer)
void _readLinks (UrlEntryTable &urlTable, std::ifstream &linkIn)
void _readRedirects (UrlEntryTable &urlTable, const std::string &redirectPath, int number)
void _writeCorpusTable (UrlEntryVectorTable &corpusTable, const std::string &outputPath)
void _hashToCorpusTable (UrlEntryVectorTable &corpusTable, UrlEntryTable &urlTable)
void _openWriteBuckets (std::vector< std::stringstream * > &buffers, std::vector< std::ofstream * > &buckets, const std::string &path, int bins)
void _flushWriteBuffer (std::vector< std::stringstream * > &buffers, std::vector< std::ofstream * > &buckets, bool force, int i)
void _flushWriteBuffers (std::vector< std::stringstream * > &buffers, std::vector< std::ofstream * > &buckets, bool force)
void _closeWriteBuckets (std::vector< std::stringstream * > &buffers, std::vector< std::ofstream * > &buckets)
void _openReadBuckets (std::vector< std::ifstream * > &buckets, const std::string &path, int bins)
void _readDocBucket (UrlEntryTable &urlTable, std::ifstream &docIn)
int hashString (const char *str)
void hashToBuckets (std::ifstream &in, const std::string &path)
void createBuckets (const std::string &tmpPath)
void closeBuckets ()
void combineBucket (const std::string &outputPath, const std::string &tmpPath, int bucket)
void hashToBuckets (const std::string &inputPath)
void combineRedirectDestinationBucket (const std::string &tmpPath, int i, std::vector< std::stringstream * > &outBuffers, std::vector< std::ofstream * > &outputFiles)
Private Attributes
std::vector< std::ofstream * > _docBucketFiles
std::vector< std::ofstream * > _linkBucketFiles
std::vector< std::stringstream * > _docBuckets
std::vector< std::stringstream * > _linkBuckets
int _bins
Member Typedef Documentation
typedef indri::utility::HashTable<char*, url_entry*, strhash, strcompst> indri::parse::Combiner::UrlEntryTable [private]
typedef indri::utility::HashTable<char*, std::vector<url_entry*>, strhash, strcompst> indri::parse::Combiner::UrlEntryVectorTable [private]
Constructor & Destructor Documentation
indri::parse::Combiner::Combiner (int bins = 10) [inline]
Member Function Documentation
void indri::parse::Combiner::_closeWriteBuckets (std::vector< std::stringstream * > & buffers, std::vector< std::ofstream * > & buckets) [private]
References _flushWriteBuffer().
Referenced by hashRedirectTargets().
void indri::parse::Combiner::_deleteUrlEntry (void * buffer) [private]
Referenced by _hashToCorpusTable(), _readRedirects(), _writeCorpusTable(), combineRedirectDestinationBucket(), and sortCorpusFiles().
void indri::parse::Combiner::_flushWriteBuffer (std::vector< std::stringstream * > & buffers, std::vector< std::ofstream * > & buckets, bool force, int i) [private]
References COMBINER_WRITE_BUFFER_SIZE.
Referenced by _closeWriteBuckets(), _flushWriteBuffers(), combineRedirectDestinationBucket(), and hashRedirectTargets().
void indri::parse::Combiner::_flushWriteBuffers (std::vector< std::stringstream * > & buffers, std::vector< std::ofstream * > & buckets, bool force) [private]
References _flushWriteBuffer().
Referenced by hashToBuckets().
void indri::parse::Combiner::_hashToCorpusTable (UrlEntryVectorTable & corpusTable, UrlEntryTable & urlTable) [private]
References _deleteUrlEntry(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::parse::Combiner::url_entry::corpusPath, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), and indri::parse::Combiner::url_entry::linkCount.
Referenced by combineBucket().
indri::parse::Combiner::url_entry * indri::parse::Combiner::_newUrlEntry (const char * url, const char * corpusPath, const char * docNo) [private]
References indri::parse::Combiner::url_entry::corpusPath, indri::parse::Combiner::url_entry::docNo, indri::parse::Combiner::url_entry::linkCount, and indri::parse::Combiner::url_entry::url.
Referenced by _readDocBucket(), _readRedirects(), and sortCorpusFiles().
void indri::parse::Combiner::_openReadBuckets (std::vector< std::ifstream * > & buckets, const std::string & path, int bins) [private]
References _bins, indri::file::Path::combine(), and i64_to_string().
void indri::parse::Combiner::_openWriteBuckets (std::vector< std::stringstream * > & buffers, std::vector< std::ofstream * > & buckets, const std::string & path, int bins) [private]
References _bins, indri::file::Path::combine(), and i64_to_string().
Referenced by combineRedirectDestinationBuckets(), and hashRedirectTargets().
void indri::parse::Combiner::_readDocBucket (UrlEntryTable & urlTable, std::ifstream & docIn) [private]
References _newUrlEntry(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), and indri::parse::Combiner::url_entry::url.
Referenced by combineBucket(), and combineRedirectDestinationBucket().
void indri::parse::Combiner::_readLinks (UrlEntryTable & urlTable, std::ifstream & linkIn) [private]
References indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
Referenced by combineBucket().
void indri::parse::Combiner::_readRedirects (UrlEntryTable & urlTable, const std::string & redirectPath, int number) [private]
References _deleteUrlEntry(), _newUrlEntry(), indri::file::Path::combine(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), i64_to_string(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::remove().
Referenced by combineBucket().
void indri::parse::Combiner::_writeCorpusTable (UrlEntryVectorTable & corpusTable, const std::string & outputPath) [private]
References _deleteUrlEntry(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::file::Path::combine(), indri::file::Path::directory(), indri::parse::Combiner::url_entry::docNo, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::utility::Buffer::front(), i64_to_string(), indri::parse::Combiner::url_entry::linkCount, indri::parse::Combiner::url_entry::linkinfo, indri::file::Path::make(), and indri::parse::Combiner::url_entry::url.
Referenced by combineBucket().
void indri::parse::Combiner::closeBuckets () [private]
References _docBucketFiles, _docBuckets, _linkBucketFiles, and _linkBuckets.
Referenced by hashToBuckets().
void indri::parse::Combiner::combineBucket (const std::string & outputPath, const std::string & tmpPath, int bucket) [private]
References _hashToCorpusTable(), _readDocBucket(), _readLinks(), _readRedirects(), _writeCorpusTable(), indri::file::Path::combine(), and i64_to_string().
Referenced by combineBuckets().
void indri::parse::Combiner::combineBuckets (const std::string & outputPath, const std::string & tmpPath)
References _bins, combineBucket(), indri::utility::IndriTimer::printElapsedSeconds(), and indri::utility::IndriTimer::start().
void indri::parse::Combiner::combineRedirectDestinationBucket (const std::string & tmpPath, int i, std::vector< std::stringstream * > & outBuffers, std::vector< std::ofstream * > & outputFiles) [private]
References _deleteUrlEntry(), _flushWriteBuffer(), _readDocBucket(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::file::Path::combine(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), hashString(), and i64_to_string().
Referenced by combineRedirectDestinationBuckets().
void indri::parse::Combiner::combineRedirectDestinationBuckets (const std::string & tmpPath)
References _bins, _openWriteBuckets(), indri::file::Path::combine(), and combineRedirectDestinationBucket().
void indri::parse::Combiner::createBuckets (const std::string & tmpPath) [private]
References _bins, _docBucketFiles, _docBuckets, _linkBucketFiles, _linkBuckets, indri::file::Path::combine(), and i64_to_string().
Referenced by hashToBuckets().
void indri::parse::Combiner::hashRedirectTargets (const std::string & bucketPath, const std::string & redirectsPath)
References _bins, _closeWriteBuckets(), _flushWriteBuffer(), _openWriteBuckets(), indri::file::Path::combine(), and hashString().
int indri::parse::Combiner::hashString (const char * str) [private]
References _bins.
Referenced by combineRedirectDestinationBucket(), hashRedirectTargets(), and hashToBuckets().
void indri::parse::Combiner::hashToBuckets (const std::string & bucketPath, const std::string & inputPath)
References _docBucketFiles, _docBuckets, _flushWriteBuffers(), _linkBucketFiles, _linkBuckets, closeBuckets(), createBuckets(), indri::file::FileTreeIterator::end(), hashToBuckets(), input(), and indri::file::Path::relative().
void indri::parse::Combiner::hashToBuckets (const std::string & inputPath) [private]
void indri::parse::Combiner::hashToBuckets (std::ifstream & in, const std::string & path) [private]
References _docBucketFiles, _docBuckets, _flushWriteBuffers(), _linkBucketFiles, _linkBuckets, and hashString().
Referenced by hashToBuckets().
void indri::parse::Combiner::sortCorpusFiles (const std::string & outputPath, const std::string & preSortPath, const std::string & inputPath)
References _deleteUrlEntry(), _newUrlEntry(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::clear(), indri::file::Path::combine(), indri::file::Path::directory(), indri::parse::Combiner::url_entry::docNo, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::file::FileTreeIterator::end(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::parse::Combiner::url_entry::linkCount, indri::parse::Combiner::url_entry::linkinfo, indri::file::Path::make(), indri::file::Path::relative(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Member Data Documentation
int indri::parse::Combiner::_bins [private]
Referenced by _openReadBuckets(), _openWriteBuckets(), combineBuckets(), combineRedirectDestinationBuckets(), createBuckets(), hashRedirectTargets(), and hashString().
std::vector< std::ofstream* > indri::parse::Combiner::_docBucketFiles [private]
Referenced by closeBuckets(), createBuckets(), and hashToBuckets().
std::vector< std::stringstream* > indri::parse::Combiner::_docBuckets [private]
Referenced by closeBuckets(), createBuckets(), and hashToBuckets().
std::vector< std::ofstream* > indri::parse::Combiner::_linkBucketFiles [private]
Referenced by closeBuckets(), createBuckets(), and hashToBuckets().
std::vector< std::stringstream* > indri::parse::Combiner::_linkBuckets [private]
Referenced by closeBuckets(), createBuckets(), and hashToBuckets().
The documentation for this class was generated from the following files:
Combiner.hpp
Combiner.cpp