Indri: indri::server::NetworkServerProxyDocumentIDsResponse Class Reference
indri::server::NetworkServerProxyDocumentIDsResponse Class Reference
Public Member Functions
NetworkServerProxyDocumentIDsResponse (indri::net::NetworkMessageStream *stream)
~NetworkServerProxyDocumentIDsResponse ()
std::vector
< lemur::api::DOCID_T > & getResults ()
Public Attributes
std::vector< lemur::api::DOCID_T > _documentIDs
indri::net::NetworkMessageStream * _stream
bool _readResponse
Constructor & Destructor Documentation
indri::server::NetworkServerProxyDocumentIDsResponse::NetworkServerProxyDocumentIDsResponse (indri::net::NetworkMessageStream * stream) [inline]
indri::server::NetworkServerProxyDocumentIDsResponse::~NetworkServerProxyDocumentIDsResponse () [inline]
References _stream, indri::net::NetworkMessageStream::mutex(), and indri::thread::Lockable::unlock().
Member Function Documentation
std::vector<lemur::api::DOCID_T>& indri::server::NetworkServerProxyDocumentIDsResponse::getResults () [inline, virtual]
Implements indri::server::QueryServerDocumentIDsResponse.
References _documentIDs, _readResponse, _stream, indri::xml::XMLNode::getChildren(), indri::net::XMLReplyReceiver::getReply(), indri::xml::XMLNode::getValue(), string_to_i64(), and indri::net::XMLReplyReceiver::wait().
Member Data Documentation
std::vector<lemur::api::DOCID_T> indri::server::NetworkServerProxyDocumentIDsResponse::_documentIDs
Referenced by getResults().
bool indri::server::NetworkServerProxyDocumentIDsResponse::_readResponse
Referenced by getResults().
indri::net::NetworkMessageStream* indri::server::NetworkServerProxyDocumentIDsResponse::_stream
Referenced by getResults(), and ~NetworkServerProxyDocumentIDsResponse().
The documentation for this class was generated from the following file:
NetworkServerProxy.cpp