Indri: indri::infnet::FilterRequireNode Class Reference
indri::infnet::FilterRequireNode Class Reference
#include <FilterRequireNode.hpp>
Public Member Functions
FilterRequireNode (const std::string &name, ListIteratorNode *filter, BeliefNode *required)
double maximumBackgroundScore ()
double maximumScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
virtual void setSiblingsFlag (int f)
Private Attributes
ListIteratorNode * _filter
BeliefNode * _required
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _extents
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::FilterRequireNode::FilterRequireNode (const std::string & name, ListIteratorNode * filter, BeliefNode * required)
References _filter, _name, and _required.
Member Function Documentation
void indri::infnet::FilterRequireNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _filter, _required, indri::infnet::BeliefNode::annotate(), indri::infnet::ListIteratorNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::infnet::ListIteratorNode::extents().
const std::string & indri::infnet::FilterRequireNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::FilterRequireNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _filter, _matches, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::FilterRequireNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _filter, _required, indri::infnet::ListIteratorNode::extents(), indri::infnet::BeliefNode::hasMatch(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::FilterRequireNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::FilterRequireNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _required, and indri::infnet::BeliefNode::maximumBackgroundScore().
double indri::infnet::FilterRequireNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _required, and indri::infnet::BeliefNode::maximumScore().
lemur::api::DOCID_T indri::infnet::FilterRequireNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _filter, _required, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::FilterRequireNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _extents, _filter, _required, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), and indri::infnet::BeliefNode::score().
virtual void indri::infnet::FilterRequireNode::setSiblingsFlag (int f) [inline, virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _required, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::FilterRequireNode::_extents [private]
Referenced by score().
ListIteratorNode* indri::infnet::FilterRequireNode::_filter [private]
Referenced by annotate(), FilterRequireNode(), hasMatch(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<bool> indri::infnet::FilterRequireNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::FilterRequireNode::_name [private]
Referenced by FilterRequireNode(), and getName().
BeliefNode* indri::infnet::FilterRequireNode::_required [private]
Referenced by annotate(), FilterRequireNode(), hasMatch(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), score(), and setSiblingsFlag().
The documentation for this class was generated from the following files:
FilterRequireNode.hpp
FilterRequireNode.cpp