Indri: indri::infnet::ExtentEnforcementNode Class Reference
indri::infnet::ExtentEnforcementNode Class Reference
#include <ExtentEnforcementNode.hpp>
Public Member Functions
ExtentEnforcementNode (const std::string &name, BeliefNode *child, ListIteratorNode *field)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
void setSiblingsFlag (int f)
Private Attributes
BeliefNode * _child
ListIteratorNode * _field
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::ExtentEnforcementNode::ExtentEnforcementNode (const std::string & name, BeliefNode * child, ListIteratorNode * field)
Member Function Documentation
void indri::infnet::ExtentEnforcementNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _field, _scores, indri::infnet::Annotator::add(), indri::infnet::BeliefNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::append(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::infnet::ListIteratorNode::matches(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::ExtentEnforcementNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::ExtentEnforcementNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _field, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::infnet::BeliefNode::hasMatch(), indri::infnet::ListIteratorNode::matches(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::ExtentEnforcementNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::hasMatch().
void indri::infnet::ExtentEnforcementNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::ExtentEnforcementNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_TINY_SCORE.
double indri::infnet::ExtentEnforcementNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_HUGE_SCORE.
lemur::api::DOCID_T indri::infnet::ExtentEnforcementNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _child, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::ExtentEnforcementNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _field, _scores, indri::utility::greedy_vector< _Type, _Count >::append(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::infnet::ListIteratorNode::matches(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, indri::infnet::BeliefNode::score(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::index::Extent::weight.
void indri::infnet::ExtentEnforcementNode::setSiblingsFlag (int f) [virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _child, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
BeliefNode* indri::infnet::ExtentEnforcementNode::_child [private]
Referenced by annotate(), hasMatch(), nextCandidateDocument(), score(), and setSiblingsFlag().
ListIteratorNode* indri::infnet::ExtentEnforcementNode::_field [private]
Referenced by annotate(), hasMatch(), and score().
indri::utility::greedy_vector<bool> indri::infnet::ExtentEnforcementNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::ExtentEnforcementNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::ExtentEnforcementNode::_scores [private]
Referenced by annotate(), and score().
The documentation for this class was generated from the following files:
ExtentEnforcementNode.hpp
ExtentEnforcementNode.cpp