Indri: indri::lang::RawScorerNodeExtractor Class Reference
indri::lang::RawScorerNodeExtractor Class Reference
#include <RawScorerNodeExtractor.hpp>
Public Member Functions
RawScorerNodeExtractor ()
void defaultBefore (indri::lang::Node *n)
void before (indri::lang::RawScorerNode *node)
void after (indri::lang::RawScorerNode *node)
void before (indri::lang::NestedRawScorerNode *node)
void after (indri::lang::NestedRawScorerNode *node)
void before (indri::lang::ShrinkageScorerNode *node)
void after (indri::lang::ShrinkageScorerNode *node)
std::vector
< indri::lang::RawScorerNode * > & getScorerNodes ()
std::vector< indri::lang::Node * > & getReachableNodes ()
Private Attributes
std::vector
< indri::lang::RawScorerNode * > _scorerNodes
std::vector< indri::lang::Node * > _reachableNodes
int _insideCount
Constructor & Destructor Documentation
indri::lang::RawScorerNodeExtractor::RawScorerNodeExtractor () [inline]
Member Function Documentation
void indri::lang::RawScorerNodeExtractor::after (indri::lang::ShrinkageScorerNode * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References after().
void indri::lang::RawScorerNodeExtractor::after (indri::lang::NestedRawScorerNode * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References after().
void indri::lang::RawScorerNodeExtractor::after (indri::lang::RawScorerNode * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _insideCount.
Referenced by after().
void indri::lang::RawScorerNodeExtractor::before (indri::lang::ShrinkageScorerNode * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References before().
void indri::lang::RawScorerNodeExtractor::before (indri::lang::NestedRawScorerNode * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References before().
void indri::lang::RawScorerNodeExtractor::before (indri::lang::RawScorerNode * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _insideCount, _reachableNodes, and _scorerNodes.
Referenced by before().
void indri::lang::RawScorerNodeExtractor::defaultBefore (indri::lang::Node * n) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _insideCount, and _reachableNodes.
std::vector<indri::lang::Node*>& indri::lang::RawScorerNodeExtractor::getReachableNodes () [inline]
References _reachableNodes.
std::vector<indri::lang::RawScorerNode*>& indri::lang::RawScorerNodeExtractor::getScorerNodes () [inline]
References _scorerNodes.
Referenced by indri::api::QueryEnvironment::runQuery().
Member Data Documentation
int indri::lang::RawScorerNodeExtractor::_insideCount [private]
Referenced by after(), before(), and defaultBefore().
std::vector<indri::lang::Node*> indri::lang::RawScorerNodeExtractor::_reachableNodes [private]
Referenced by before(), defaultBefore(), and getReachableNodes().
std::vector<indri::lang::RawScorerNode*> indri::lang::RawScorerNodeExtractor::_scorerNodes [private]
Referenced by before(), and getScorerNodes().
The documentation for this class was generated from the following file:
RawScorerNodeExtractor.hpp