Indri: indri::index::DiskIndex Class Reference
indri::index::DiskIndex Class Reference
#include <DiskIndex.hpp>
Public Types
enum { MAX_DOCLENGTHS_CACHE = 20*1024*1024 }
Public Member Functions
DiskIndex ()
void open (const std::string &base, const std::string &relative)
void close ()
const std::string & path ()
lemur::api::DOCID_T documentBase ()
int field (const char *fieldName)
int field (const std::string &fieldName)
std::string field (int fieldID)
lemur::api::TERMID_T term (const char *term)
lemur::api::TERMID_T term (const std::string &term)
std::string term (lemur::api::TERMID_T termID)
int documentLength (lemur::api::DOCID_T documentID)
UINT64 documentCount ()
UINT64 documentCount (const std::string &term)
lemur::api::DOCID_T documentMaximum ()
The documentMaximum is at least one greater than the largest documentID used in this index.
UINT64 uniqueTermCount ()
UINT64 termCount (const std::string &term)
UINT64 termCount ()
UINT64 fieldTermCount (const std::string &field)
UINT64 fieldTermCount (const std::string &field, const std::string &term)
UINT64 fieldDocumentCount (const std::string &field)
UINT64 fieldDocumentCount (const std::string &field, const std::string &term)
DocListIterator * docListIterator (lemur::api::TERMID_T termID)
DocListIterator * docListIterator (const std::string &term)
DocListFileIterator * docListFileIterator ()
DocExtentListIterator * fieldListIterator (int fieldID)
DocExtentListIterator * fieldListIterator (const std::string &field)
const TermList * termList (lemur::api::DOCID_T documentID)
TermListFileIterator * termListFileIterator ()
VocabularyIterator * vocabularyIterator ()
VocabularyIterator * frequentVocabularyIterator ()
VocabularyIterator * infrequentVocabularyIterator ()
DocumentDataIterator * documentDataIterator ()
indri::thread::Lockable * iteratorLock ()
indri::thread::Lockable * statisticsLock ()
Private Member Functions
indri::index::DiskTermData * _fetchTermData (lemur::api::TERMID_T termID)
indri::index::DiskTermData * _fetchTermData (const char *termString)
void _readManifest (const std::string &manifestPath)
Private Attributes
indri::thread::Mutex _lock
std::string _path
indri::file::BulkTreeReader _frequentStringToTerm
indri::file::BulkTreeReader _infrequentStringToTerm
indri::file::BulkTreeReader _frequentIdToTerm
indri::file::BulkTreeReader _infrequentIdToTerm
indri::file::File _frequentTermsData
indri::file::File _documentLengths
indri::file::File _documentStatistics
indri::file::File _invertedFile
indri::file::File _directFile
indri::file::File _fieldsFile
indri::file::SequentialReadBuffer _lengthsBuffer
std::vector< FieldStatistics > _fieldData
lemur::api::DOCID_T _documentBase
int _infrequentTermBase
CorpusStatistics _corpusStatistics
Member Enumeration Documentation
anonymous enum
Enumerator:
MAX_DOCLENGTHS_CACHE
Maximum size of the cache for the document lengths file.
Constructor & Destructor Documentation
indri::index::DiskIndex::DiskIndex () [inline]
Member Function Documentation
indri::index::DiskTermData * indri::index::DiskIndex::_fetchTermData (const char * termString) [private]
References _fieldData, _frequentStringToTerm, _infrequentStringToTerm, _infrequentTermBase, disktermdata_decompress(), disktermdata_size(), indri::file::BulkTreeReader::get(), indri::index::DiskTermData::termID, indri::index::DiskTermData::WithOffsets, and indri::index::DiskTermData::WithTermID.
indri::index::DiskTermData * indri::index::DiskIndex::_fetchTermData (lemur::api::TERMID_T termID) [private]
References _fieldData, _frequentIdToTerm, _infrequentIdToTerm, _infrequentTermBase, disktermdata_decompress(), disktermdata_size(), indri::file::BulkTreeReader::get(), indri::index::DiskTermData::WithOffsets, and indri::index::DiskTermData::WithString.
Referenced by docListIterator(), documentCount(), fieldDocumentCount(), fieldTermCount(), term(), and termCount().
void indri::index::DiskIndex::_readManifest (const std::string & manifestPath) [private]
References _corpusStatistics, _fieldData, _infrequentTermBase, indri::index::CorpusStatistics::baseDocument, documentCount(), indri::api::Parameters::exists(), field(), indri::api::Parameters::get(), INDRI_DISTRIBUTION, indri::api::Parameters::loadFile(), indri::index::CorpusStatistics::maximumDocument, indri::api::Parameters::size(), indri::index::CorpusStatistics::totalDocuments, indri::index::CorpusStatistics::totalTerms, and indri::index::CorpusStatistics::uniqueTerms.
Referenced by open().
void indri::index::DiskIndex::close () [virtual]
Implements indri::index::Index.
References _directFile, _documentLengths, _documentStatistics, _frequentIdToTerm, _frequentStringToTerm, _frequentTermsData, _infrequentIdToTerm, _infrequentStringToTerm, _invertedFile, indri::file::File::close(), and indri::file::BulkTreeReader::close().
Referenced by indri::collection::Repository::merge().
indri::index::DocListFileIterator * indri::index::DiskIndex::docListFileIterator () [virtual]
Implements indri::index::Index.
References _fieldData, and _invertedFile.
indri::index::DocListIterator * indri::index::DiskIndex::docListIterator (const std::string & term) [virtual]
Implements indri::index::Index.
References _fetchTermData(), _fieldData, _invertedFile, disktermdata_delete(), indri::index::DiskTermData::length, and indri::index::DiskTermData::startOffset.
indri::index::DocListIterator * indri::index::DiskIndex::docListIterator (lemur::api::TERMID_T termID) [virtual]
Implements indri::index::Index.
References _fetchTermData(), _invertedFile, disktermdata_delete(), indri::index::DiskTermData::length, and indri::index::DiskTermData::startOffset.
lemur::api::DOCID_T indri::index::DiskIndex::documentBase () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::baseDocument.
UINT64 indri::index::DiskIndex::documentCount (const std::string & term) [virtual]
Implements indri::index::Index.
References _fetchTermData(), indri::index::TermData::corpus, disktermdata_delete(), indri::index::TermFieldStatistics::documentCount, and indri::index::DiskTermData::termData.
UINT64 indri::index::DiskIndex::documentCount () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::totalDocuments.
Referenced by _readManifest().
indri::index::DocumentDataIterator * indri::index::DiskIndex::documentDataIterator () [virtual]
Implements indri::index::Index.
References _documentStatistics.
int indri::index::DiskIndex::documentLength (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::Index.
References _corpusStatistics, _lengthsBuffer, indri::index::CorpusStatistics::baseDocument, indri::file::SequentialReadBuffer::read(), and indri::index::CorpusStatistics::totalDocuments.
lemur::api::DOCID_T indri::index::DiskIndex::documentMaximum () [virtual]
The documentMaximum is at least one greater than the largest documentID used in this index.
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::maximumDocument.
Referenced by indri::collection::Repository::merge().
std::string indri::index::DiskIndex::field (int fieldID) [virtual]
Implements indri::index::Index.
References _fieldData.
int indri::index::DiskIndex::field (const std::string & fieldName) [virtual]
Implements indri::index::Index.
References field().
int indri::index::DiskIndex::field (const char * fieldName) [virtual]
Implements indri::index::Index.
References _fieldData.
Referenced by _readManifest(), field(), fieldDocumentCount(), fieldListIterator(), and fieldTermCount().
UINT64 indri::index::DiskIndex::fieldDocumentCount (const std::string & field, const std::string & term) [virtual]
Implements indri::index::Index.
References _fetchTermData(), disktermdata_delete(), indri::index::TermFieldStatistics::documentCount, field(), indri::index::TermData::fields, and indri::index::DiskTermData::termData.
UINT64 indri::index::DiskIndex::fieldDocumentCount (const std::string & field) [virtual]
Implements indri::index::Index.
References _fieldData, and field().
indri::index::DocExtentListIterator * indri::index::DiskIndex::fieldListIterator (const std::string & field) [virtual]
Implements indri::index::Index.
References field(), and fieldListIterator().
indri::index::DocExtentListIterator * indri::index::DiskIndex::fieldListIterator (int fieldID) [virtual]
Implements indri::index::Index.
References _fieldData, and _fieldsFile.
Referenced by fieldListIterator().
UINT64 indri::index::DiskIndex::fieldTermCount (const std::string & field, const std::string & term) [virtual]
Implements indri::index::Index.
References _fetchTermData(), disktermdata_delete(), field(), indri::index::TermData::fields, indri::index::DiskTermData::termData, and indri::index::TermFieldStatistics::totalCount.
UINT64 indri::index::DiskIndex::fieldTermCount (const std::string & field) [virtual]
Implements indri::index::Index.
References _fieldData, and field().
indri::index::VocabularyIterator * indri::index::DiskIndex::frequentVocabularyIterator () [virtual]
Implements indri::index::Index.
References _fieldData, and _frequentTermsData.
Referenced by vocabularyIterator().
indri::index::VocabularyIterator * indri::index::DiskIndex::infrequentVocabularyIterator () [virtual]
Implements indri::index::Index.
References _fieldData, _infrequentStringToTerm, _infrequentTermBase, and _lock.
Referenced by vocabularyIterator().
indri::thread::Lockable * indri::index::DiskIndex::iteratorLock () [virtual]
Implements indri::index::Index.
void indri::index::DiskIndex::open (const std::string & base, const std::string & relative)
References _directFile, _documentLengths, _documentStatistics, _fieldsFile, _frequentIdToTerm, _frequentStringToTerm, _frequentTermsData, _infrequentIdToTerm, _infrequentStringToTerm, _invertedFile, _lengthsBuffer, _path, _readManifest(), indri::file::SequentialReadBuffer::cache(), indri::file::Path::combine(), indri::file::File::openRead(), indri::file::BulkTreeReader::openRead(), path(), and indri::file::File::size().
Referenced by indri::collection::Repository::_mergeStage(), indri::collection::Repository::_openIndexes(), and indri::collection::Repository::merge().
const std::string & indri::index::DiskIndex::path ()
References _path.
Referenced by indri::collection::Repository::_mergeStage(), indri::collection::Repository::_writeParameters(), and open().
indri::thread::Lockable * indri::index::DiskIndex::statisticsLock () [virtual]
Implements indri::index::Index.
References _lock.
std::string indri::index::DiskIndex::term (lemur::api::TERMID_T termID) [virtual]
Implements indri::index::Index.
References _fetchTermData(), disktermdata_delete(), indri::index::TermData::term, and indri::index::DiskTermData::termData.
lemur::api::TERMID_T indri::index::DiskIndex::term (const std::string & term) [virtual]
Implements indri::index::Index.
References term().
lemur::api::TERMID_T indri::index::DiskIndex::term (const char * term) [virtual]
Implements indri::index::Index.
References _fetchTermData(), disktermdata_delete(), and indri::index::DiskTermData::termID.
Referenced by term().
UINT64 indri::index::DiskIndex::termCount () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::totalTerms.
UINT64 indri::index::DiskIndex::termCount (const std::string & term) [virtual]
Implements indri::index::Index.
References _fetchTermData(), indri::index::TermData::corpus, disktermdata_delete(), indri::index::DiskTermData::termData, and indri::index::TermFieldStatistics::totalCount.
const indri::index::TermList * indri::index::DiskIndex::termList (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::Index.
References _directFile, _documentStatistics, indri::index::DocumentData::byteLength, indri::index::DocumentData::offset, indri::index::TermList::read(), and indri::file::File::read().
indri::index::TermListFileIterator * indri::index::DiskIndex::termListFileIterator () [virtual]
Implements indri::index::Index.
References _directFile.
UINT64 indri::index::DiskIndex::uniqueTermCount () [virtual]
Implements indri::index::Index.
References _corpusStatistics, and indri::index::CorpusStatistics::uniqueTerms.
indri::index::VocabularyIterator * indri::index::DiskIndex::vocabularyIterator () [virtual]
Implements indri::index::Index.
References _infrequentTermBase, frequentVocabularyIterator(), and infrequentVocabularyIterator().
Member Data Documentation
CorpusStatistics indri::index::DiskIndex::_corpusStatistics [private]
Referenced by _readManifest(), documentBase(), documentCount(), documentLength(), documentMaximum(), termCount(), and uniqueTermCount().
indri::file::File indri::index::DiskIndex::_directFile [private]
Referenced by close(), open(), termList(), and termListFileIterator().
lemur::api::DOCID_T indri::index::DiskIndex::_documentBase [private]
indri::file::File indri::index::DiskIndex::_documentLengths [private]
Referenced by close(), and open().
indri::file::File indri::index::DiskIndex::_documentStatistics [private]
Referenced by close(), documentDataIterator(), open(), and termList().
std::vector<FieldStatistics> indri::index::DiskIndex::_fieldData [private]
Referenced by _fetchTermData(), _readManifest(), docListFileIterator(), docListIterator(), field(), fieldDocumentCount(), fieldListIterator(), fieldTermCount(), frequentVocabularyIterator(), and infrequentVocabularyIterator().
indri::file::File indri::index::DiskIndex::_fieldsFile [private]
Referenced by fieldListIterator(), and open().
indri::file::BulkTreeReader indri::index::DiskIndex::_frequentIdToTerm [private]
Referenced by _fetchTermData(), close(), and open().
indri::file::BulkTreeReader indri::index::DiskIndex::_frequentStringToTerm [private]
Referenced by _fetchTermData(), close(), and open().
indri::file::File indri::index::DiskIndex::_frequentTermsData [private]
Referenced by close(), frequentVocabularyIterator(), and open().
indri::file::BulkTreeReader indri::index::DiskIndex::_infrequentIdToTerm [private]
Referenced by _fetchTermData(), close(), and open().
indri::file::BulkTreeReader indri::index::DiskIndex::_infrequentStringToTerm [private]
Referenced by _fetchTermData(), close(), infrequentVocabularyIterator(), and open().
int indri::index::DiskIndex::_infrequentTermBase [private]
Referenced by _fetchTermData(), _readManifest(), infrequentVocabularyIterator(), and vocabularyIterator().
indri::file::File indri::index::DiskIndex::_invertedFile [private]
Referenced by close(), docListFileIterator(), docListIterator(), and open().
indri::file::SequentialReadBuffer indri::index::DiskIndex::_lengthsBuffer [private]
Referenced by documentLength(), and open().
indri::thread::Mutex indri::index::DiskIndex::_lock [private]
Referenced by infrequentVocabularyIterator(), and statisticsLock().
std::string indri::index::DiskIndex::_path [private]
Referenced by open(), and path().
The documentation for this class was generated from the following files:
DiskIndex.hpp
DiskIndex.cpp