Indri: lemurproject::indri::IndexStatus::action_code Class Reference
lemurproject::indri::IndexStatus::action_code Class Reference
Public Member Functions
final int swigValue ()
String toString ()
Static Public Member Functions
static action_code swigToEnum (int swigValue)
Static Public Attributes
static final action_code FileOpen = new action_code("FileOpen")
static final action_code FileSkip = new action_code("FileSkip")
static final action_code FileError = new action_code("FileError")
static final action_code FileClose = new action_code("FileClose")
static final action_code DocumentCount = new action_code("DocumentCount")
Private Member Functions
action_code (String swigName)
action_code (String swigName, int swigValue)
action_code (String swigName, action_code swigEnum)
Private Attributes
final int swigValue
final String swigName
Static Private Attributes
static action_code[] swigValues = { FileOpen, FileSkip, FileError, FileClose, DocumentCount }
static int swigNext = 0
Constructor & Destructor Documentation
lemurproject::indri::IndexStatus::action_code::action_code (String swigName) [inline, private]
References swigNext, and swigValue().
lemurproject::indri::IndexStatus::action_code::action_code (String swigName, int swigValue) [inline, private]
References swigNext.
lemurproject::indri::IndexStatus::action_code::action_code (String swigName, action_code swigEnum) [inline, private]
References swigNext, and swigValue().
Member Function Documentation
static action_code lemurproject::indri::IndexStatus::action_code::swigToEnum (int swigValue) [inline, static]
References swigValues.
final int lemurproject::indri::IndexStatus::action_code::swigValue () [inline]
Referenced by action_code().
String lemurproject::indri::IndexStatus::action_code::toString () [inline]
References swigName.
Member Data Documentation
final action_code lemurproject::indri::IndexStatus::action_code::DocumentCount = new action_code("DocumentCount") [static]
final action_code lemurproject::indri::IndexStatus::action_code::FileClose = new action_code("FileClose") [static]
final action_code lemurproject::indri::IndexStatus::action_code::FileError = new action_code("FileError") [static]
final action_code lemurproject::indri::IndexStatus::action_code::FileOpen = new action_code("FileOpen") [static]
final action_code lemurproject::indri::IndexStatus::action_code::FileSkip = new action_code("FileSkip") [static]
final String lemurproject::indri::IndexStatus::action_code::swigName [private]
Referenced by toString().
int lemurproject::indri::IndexStatus::action_code::swigNext = 0 [static, private]
Referenced by action_code().
final int lemurproject::indri::IndexStatus::action_code::swigValue [private]
Referenced by action_code().
action_code [] lemurproject::indri::IndexStatus::action_code::swigValues = { FileOpen, FileSkip, FileError, FileClose, DocumentCount } [static, private]
Referenced by swigToEnum().
The documentation for this class was generated from the following file:
IndexStatus.java