Indri: indri::parse::NormalizationTransformation Class Reference
indri::parse::NormalizationTransformation Class Reference
#include <NormalizationTransformation.hpp>
Public Member Functions
NormalizationTransformation (indri::api::Parameters *acronymList=0)
~NormalizationTransformation ()
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
void handle (indri::api::ParsedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
Private Attributes
ObjectHandler
< indri::api::ParsedDocument > * _handler
String_set * _acronyms
Constructor & Destructor Documentation
indri::parse::NormalizationTransformation::NormalizationTransformation (indri::api::Parameters * acronymList = 0)
References _acronyms, indri::api::Parameters::exists(), and indri::api::Parameters::size().
indri::parse::NormalizationTransformation::~NormalizationTransformation ()
References _acronyms.
Member Function Documentation
void indri::parse::NormalizationTransformation::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::NormalizationTransformation::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::NormalizationTransformation::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _acronyms, indri::parse::CharClass::letter, indri::utility::greedy_vector< _Type, _Count >::size(), and indri::api::ParsedDocument::terms.
Referenced by handle().
Member Data Documentation
String_set* indri::parse::NormalizationTransformation::_acronyms [private]
Referenced by NormalizationTransformation(), transform(), and ~NormalizationTransformation().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::NormalizationTransformation::_handler [private]
Referenced by handle(), and setHandler().
The documentation for this class was generated from the following files:
NormalizationTransformation.hpp
NormalizationTransformation.cpp