Indri: indri::lang::DocumentStructureNode Class Reference
indri::lang::DocumentStructureNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
DocumentStructureNode ()
DocumentStructureNode (Unpacker &unpacker)
UINT64 hashCode () const
bool operator== (Node &o)
std::string typeName () const
void pack (Packer &packer)
void walk (Walker &walker)
std::string queryText () const
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::DocumentStructureNode::DocumentStructureNode () [inline]
indri::lang::DocumentStructureNode::DocumentStructureNode (Unpacker & unpacker) [inline]
Member Function Documentation
Node* indri::lang::DocumentStructureNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
Referenced by indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), and indri::lang::ShrinkageScorerNode::copy().
UINT64 indri::lang::DocumentStructureNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
bool indri::lang::DocumentStructureNode::operator== (Node & o) [inline]
void indri::lang::DocumentStructureNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Packer::after(), and indri::lang::Packer::before().
std::string indri::lang::DocumentStructureNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
std::string indri::lang::DocumentStructureNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::DocumentStructureNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::ExtentParent::walk(), indri::lang::ExtentChild::walk(), indri::lang::ExtentDescendant::walk(), and indri::lang::ShrinkageScorerNode::walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp