Indri: indri::infnet::ShrinkageBeliefNode Class Reference
indri::infnet::ShrinkageBeliefNode Class Reference
#include <ShrinkageBeliefNode.hpp>
Classes
struct lt_rule
struct sr
Public Member Functions
ShrinkageBeliefNode (const std::string &name, ListIteratorNode &child, DocumentStructureHolderNode &documentStructureHolderNode, indri::query::TermScoreFunction &scoreFunction, double maximumBackgroundScore, double maximumScore)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumBackgroundScore ()
double maximumScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
void addShrinkageRule (std::string rule)
void setSmoothing (const std::string &stringSpec)
Protected Types
typedef struct
indri::infnet::ShrinkageBeliefNode::sr smoothing_rule
Protected Member Functions
void _buildScoreCache (lemur::api::DOCID_T documentID)
Protected Attributes
ListIteratorNode & _list
DocumentStructureHolderNode & _docStructHolder
double _maximumScore
double _maximumBackgroundScore
indri::query::TermScoreFunction & _scoreFunction
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _results
indri::utility::greedy_vector
< bool > _matches
std::string _name
indri::utility::greedy_vector
< double > _down
indri::utility::greedy_vector
< double > _up
indri::utility::greedy_vector
< double > _base
indri::utility::greedy_vector
< double > _counts
lemur::api::DOCID_T _documentID
std::set< smoothing_rule, lt_rule > _ruleSet
std::map< int, smoothing_rule > _ruleMap
double _parentWeight
double _docWeight
double _otherWeight
bool _recursive
bool _queryLevelCombine
double _defaultScore
std::set< int > _roots
indri::utility::greedy_vector
< int > _topDownOrder
Member Typedef Documentation
typedef struct indri::infnet::ShrinkageBeliefNode::sr indri::infnet::ShrinkageBeliefNode::smoothing_rule [protected]
Constructor & Destructor Documentation
indri::infnet::ShrinkageBeliefNode::ShrinkageBeliefNode (const std::string & name, ListIteratorNode & child, DocumentStructureHolderNode & documentStructureHolderNode, indri::query::TermScoreFunction & scoreFunction, double maximumBackgroundScore, double maximumScore)
References _maximumScore, and INDRI_HUGE_SCORE.
Member Function Documentation
void indri::infnet::ShrinkageBeliefNode::_buildScoreCache (lemur::api::DOCID_T documentID) [protected]
References _base, _counts, _defaultScore, _docStructHolder, _documentID, _docWeight, _down, _list, _otherWeight, _parentWeight, _queryLevelCombine, _recursive, _roots, _ruleMap, _scoreFunction, _topDownOrder, _up, indri::index::DocumentStructure::accumulatedLength(), indri::index::DocumentStructure::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::DocumentStructure::childrenBegin(), indri::index::DocumentStructure::childrenEnd(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Index::documentLength(), indri::index::Extent::end, indri::index::DocumentStructure::end(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), indri::infnet::DocumentStructureHolderNode::getDocumentStructure(), indri::index::DocumentStructure::getIndex(), indri::infnet::ShrinkageBeliefNode::sr::lengthProportional, indri::index::DocumentStructure::nodeCount(), indri::index::DocumentStructure::parent(), indri::utility::greedy_vector< _Type, _Count >::resize(), score(), indri::query::TermScoreFunction::scoreOccurrence(), indri::index::DocumentStructure::topDownOrder(), indri::index::DocumentStructure::type(), indri::infnet::ShrinkageBeliefNode::sr::weight, and indri::index::Extent::weight.
Referenced by hasMatch(), and score().
void indri::infnet::ShrinkageBeliefNode::addShrinkageRule (std::string rule)
References _docWeight, _parentWeight, _queryLevelCombine, _recursive, _ruleSet, indri::infnet::ShrinkageBeliefNode::sr::fieldName, indri::infnet::ShrinkageBeliefNode::sr::lengthProportional, and indri::infnet::ShrinkageBeliefNode::sr::weight.
Referenced by indri::infnet::InferenceNetworkBuilder::_after().
void indri::infnet::ShrinkageBeliefNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _list, indri::infnet::Annotator::add(), indri::infnet::ListIteratorNode::annotate(), indri::index::Extent::begin, indri::index::Extent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::ShrinkageBeliefNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::ShrinkageBeliefNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _buildScoreCache(), _docStructHolder, _down, _matches, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Extent::end, indri::index::DocumentStructure::findLeafs(), indri::infnet::DocumentStructureHolderNode::getDocumentStructure(), indri::index::Extent::ordinal, indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::ShrinkageBeliefNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _list, indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::ShrinkageBeliefNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _ruleMap, _ruleSet, and indri::index::Index::field().
double indri::infnet::ShrinkageBeliefNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumBackgroundScore.
double indri::infnet::ShrinkageBeliefNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumScore.
lemur::api::DOCID_T indri::infnet::ShrinkageBeliefNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _list, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::ShrinkageBeliefNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _buildScoreCache(), _defaultScore, _docStructHolder, _down, _queryLevelCombine, _results, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::index::Extent::end, indri::index::DocumentStructure::findLeafs(), indri::infnet::DocumentStructureHolderNode::getDocumentStructure(), indri::index::DocumentStructure::nodeCount(), indri::index::Extent::ordinal, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::api::ScoredExtentResult::score.
Referenced by _buildScoreCache().
void indri::infnet::ShrinkageBeliefNode::setSmoothing (const std::string & stringSpec)
References _otherWeight, indri::api::Parameters::exists(), indri::api::Parameters::get(), and indri::api::Parameters::set().
Member Data Documentation
indri::utility::greedy_vector<double> indri::infnet::ShrinkageBeliefNode::_base [protected]
Referenced by _buildScoreCache().
indri::utility::greedy_vector<double> indri::infnet::ShrinkageBeliefNode::_counts [protected]
Referenced by _buildScoreCache().
double indri::infnet::ShrinkageBeliefNode::_defaultScore [protected]
Referenced by _buildScoreCache(), and score().
DocumentStructureHolderNode& indri::infnet::ShrinkageBeliefNode::_docStructHolder [protected]
Referenced by _buildScoreCache(), hasMatch(), and score().
lemur::api::DOCID_T indri::infnet::ShrinkageBeliefNode::_documentID [protected]
Referenced by _buildScoreCache().
double indri::infnet::ShrinkageBeliefNode::_docWeight [protected]
Referenced by _buildScoreCache(), and addShrinkageRule().
indri::utility::greedy_vector<double> indri::infnet::ShrinkageBeliefNode::_down [protected]
Referenced by _buildScoreCache(), hasMatch(), and score().
ListIteratorNode& indri::infnet::ShrinkageBeliefNode::_list [protected]
Referenced by _buildScoreCache(), annotate(), hasMatch(), and nextCandidateDocument().
indri::utility::greedy_vector<bool> indri::infnet::ShrinkageBeliefNode::_matches [protected]
Referenced by hasMatch().
double indri::infnet::ShrinkageBeliefNode::_maximumBackgroundScore [protected]
Referenced by maximumBackgroundScore().
double indri::infnet::ShrinkageBeliefNode::_maximumScore [protected]
Referenced by maximumScore(), and ShrinkageBeliefNode().
std::string indri::infnet::ShrinkageBeliefNode::_name [protected]
Referenced by getName().
double indri::infnet::ShrinkageBeliefNode::_otherWeight [protected]
Referenced by _buildScoreCache(), and setSmoothing().
double indri::infnet::ShrinkageBeliefNode::_parentWeight [protected]
Referenced by _buildScoreCache(), and addShrinkageRule().
bool indri::infnet::ShrinkageBeliefNode::_queryLevelCombine [protected]
Referenced by _buildScoreCache(), addShrinkageRule(), and score().
bool indri::infnet::ShrinkageBeliefNode::_recursive [protected]
Referenced by _buildScoreCache(), and addShrinkageRule().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::ShrinkageBeliefNode::_results [protected]
Referenced by score().
std::set<int> indri::infnet::ShrinkageBeliefNode::_roots [protected]
Referenced by _buildScoreCache().
std::map<int, smoothing_rule> indri::infnet::ShrinkageBeliefNode::_ruleMap [protected]
Referenced by _buildScoreCache(), and indexChanged().
std::set<smoothing_rule, lt_rule> indri::infnet::ShrinkageBeliefNode::_ruleSet [protected]
Referenced by addShrinkageRule(), and indexChanged().
indri::query::TermScoreFunction& indri::infnet::ShrinkageBeliefNode::_scoreFunction [protected]
Referenced by _buildScoreCache().
indri::utility::greedy_vector<int> indri::infnet::ShrinkageBeliefNode::_topDownOrder [protected]
Referenced by _buildScoreCache().
indri::utility::greedy_vector<double> indri::infnet::ShrinkageBeliefNode::_up [protected]
Referenced by _buildScoreCache().
The documentation for this class was generated from the following files:
ShrinkageBeliefNode.hpp
ShrinkageBeliefNode.cpp