Indri: indri::parse::DateParse Class Reference
indri::parse::DateParse Class Reference
#include <DateParse.hpp>
Static Public Member Functions
static UINT64 convertDate (const std::string &year, const std::string &month, const std::string &day)
Static Private Member Functions
static int _parseYear (const std::string &year)
static int _parseDay (const std::string &day)
static int _parseMonth (const std::string &month)
Member Function Documentation
static int indri::parse::DateParse::_parseDay (const std::string & day) [inline, static, private]
Referenced by convertDate().
static int indri::parse::DateParse::_parseMonth (const std::string & month) [inline, static, private]
Referenced by convertDate().
static int indri::parse::DateParse::_parseYear (const std::string & year) [inline, static, private]
Referenced by convertDate().
static UINT64 indri::parse::DateParse::convertDate (const std::string & year, const std::string & month, const std::string & day) [inline, static]
References _parseDay(), _parseMonth(), and _parseYear().
Referenced by QueryParser::dashDate(), QueryParser::slashDate(), and QueryParser::spaceDate().
The documentation for this class was generated from the following file:
DateParse.hpp