Indri: Indri::MetadataPairVector Class Reference
Indri::MetadataPairVector Class Reference
Classes
class MetadataPairVectorEnumerator
Public Member Functions
virtual void Dispose ()
MetadataPairVector (System.Collections.ICollection c)
void CopyTo (System.Array array)
void CopyTo (System.Array array, int arrayIndex)
void CopyTo (int index, System.Array array, int arrayIndex, int count)
MetadataPairVectorEnumerator GetEnumerator ()
void Clear ()
void Add (MetadataPair value)
MetadataPairVector ()
MetadataPairVector (int capacity)
void AddRange (MetadataPairVector values)
MetadataPairVector GetRange (int index, int count)
void Insert (int index, MetadataPair value)
void InsertRange (int index, MetadataPairVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, MetadataPairVector values)
Static Public Member Functions
static MetadataPairVector Repeat (MetadataPair value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
MetadataPair this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal MetadataPairVector (IntPtr cPtr, bool cMemoryOwn)
~MetadataPairVector ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
MetadataPair getitemcopy (int index)
MetadataPair getitem (int index)
void setitem (int index, MetadataPair value)
Static Private Member Functions
static internal HandleRef getCPtr (MetadataPairVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::MetadataPairVector::MetadataPairVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::MetadataPairVector::~MetadataPairVector () [inline, private]
References Dispose().
Indri::MetadataPairVector::MetadataPairVector (System.Collections.ICollection c) [inline]
References Add().
Indri::MetadataPairVector::MetadataPairVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::MetadataPairVector::MetadataPairVector (int capacity) [inline]
Member Function Documentation
void Indri::MetadataPairVector::Add (MetadataPair value) [inline]
References swigCPtr.
Referenced by MetadataPairVector().
void Indri::MetadataPairVector::AddRange (MetadataPairVector values) [inline]
References swigCPtr.
uint Indri::MetadataPairVector::capacity () [inline, private]
References swigCPtr.
void Indri::MetadataPairVector::Clear () [inline]
References swigCPtr.
void Indri::MetadataPairVector::CopyTo (int index, System.Array array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::MetadataPairVector::CopyTo (System.Array array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::MetadataPairVector::CopyTo (System.Array array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::MetadataPairVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~MetadataPairVector().
static internal HandleRef Indri::MetadataPairVector::getCPtr (MetadataPairVector obj) [inline, static, private]
References swigCPtr.
MetadataPairVectorEnumerator Indri::MetadataPairVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::MetadataPairVector::GetEnumerator () [inline, private]
MetadataPair Indri::MetadataPairVector::getitem (int index) [inline, private]
References swigCPtr.
MetadataPair Indri::MetadataPairVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
MetadataPairVector Indri::MetadataPairVector::GetRange (int index, int count) [inline]
References MetadataPairVector(), and swigCPtr.
void Indri::MetadataPairVector::Insert (int index, MetadataPair value) [inline]
References swigCPtr.
void Indri::MetadataPairVector::InsertRange (int index, MetadataPairVector values) [inline]
References swigCPtr.
void Indri::MetadataPairVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::MetadataPairVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static MetadataPairVector Indri::MetadataPairVector::Repeat (MetadataPair value, int count) [inline, static]
References MetadataPairVector().
void Indri::MetadataPairVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::MetadataPairVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::MetadataPairVector::Reverse () [inline]
References swigCPtr.
void Indri::MetadataPairVector::setitem (int index, MetadataPair value) [inline, private]
References swigCPtr.
void Indri::MetadataPairVector::SetRange (int index, MetadataPairVector values) [inline]
References swigCPtr.
uint Indri::MetadataPairVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::MetadataPairVector::MetadataPairVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::MetadataPairVector::swigCMemOwn [protected]
Referenced by Dispose(), and MetadataPairVector().
HandleRef Indri::MetadataPairVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), MetadataPairVector(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::MetadataPairVector::Capacity [get, set]
int Indri::MetadataPairVector::Count [get]
Referenced by CopyTo(), Indri::MetadataPairVector::MetadataPairVectorEnumerator::MetadataPairVectorEnumerator(), Indri::MetadataPairVector::MetadataPairVectorEnumerator::MoveNext(), and Indri::MetadataPairVector::MetadataPairVectorEnumerator::Reset().
bool Indri::MetadataPairVector::IsFixedSize [get]
bool Indri::MetadataPairVector::IsReadOnly [get]
bool Indri::MetadataPairVector::IsSynchronized [get]
MetadataPair Indri::MetadataPairVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
MetadataPairVector.cs