Indri: Indri::AttributeValuePairVector Class Reference
Indri::AttributeValuePairVector Class Reference
Classes
class AttributeValuePairVectorEnumerator
Public Member Functions
virtual void Dispose ()
AttributeValuePairVector (System.Collections.ICollection c)
void CopyTo (System.Array array)
void CopyTo (System.Array array, int arrayIndex)
void CopyTo (int index, System.Array array, int arrayIndex, int count)
AttributeValuePairVectorEnumerator GetEnumerator ()
void Clear ()
void Add (AttributeValuePair value)
AttributeValuePairVector ()
AttributeValuePairVector (int capacity)
void AddRange (AttributeValuePairVector values)
AttributeValuePairVector GetRange (int index, int count)
void Insert (int index, AttributeValuePair value)
void InsertRange (int index, AttributeValuePairVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, AttributeValuePairVector values)
Static Public Member Functions
static AttributeValuePairVector Repeat (AttributeValuePair value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
AttributeValuePair this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal AttributeValuePairVector (IntPtr cPtr, bool cMemoryOwn)
~AttributeValuePairVector ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
AttributeValuePair getitemcopy (int index)
AttributeValuePair getitem (int index)
void setitem (int index, AttributeValuePair value)
Static Private Member Functions
static internal HandleRef getCPtr (AttributeValuePairVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::AttributeValuePairVector::AttributeValuePairVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::AttributeValuePairVector::~AttributeValuePairVector () [inline, private]
References Dispose().
Indri::AttributeValuePairVector::AttributeValuePairVector (System.Collections.ICollection c) [inline]
References Add().
Indri::AttributeValuePairVector::AttributeValuePairVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::AttributeValuePairVector::AttributeValuePairVector (int capacity) [inline]
Member Function Documentation
void Indri::AttributeValuePairVector::Add (AttributeValuePair value) [inline]
References swigCPtr.
Referenced by AttributeValuePairVector().
void Indri::AttributeValuePairVector::AddRange (AttributeValuePairVector values) [inline]
References swigCPtr.
uint Indri::AttributeValuePairVector::capacity () [inline, private]
References swigCPtr.
void Indri::AttributeValuePairVector::Clear () [inline]
References swigCPtr.
void Indri::AttributeValuePairVector::CopyTo (int index, System.Array array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::AttributeValuePairVector::CopyTo (System.Array array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::AttributeValuePairVector::CopyTo (System.Array array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::AttributeValuePairVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~AttributeValuePairVector().
static internal HandleRef Indri::AttributeValuePairVector::getCPtr (AttributeValuePairVector obj) [inline, static, private]
References swigCPtr.
AttributeValuePairVectorEnumerator Indri::AttributeValuePairVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::AttributeValuePairVector::GetEnumerator () [inline, private]
AttributeValuePair Indri::AttributeValuePairVector::getitem (int index) [inline, private]
References swigCPtr.
AttributeValuePair Indri::AttributeValuePairVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
AttributeValuePairVector Indri::AttributeValuePairVector::GetRange (int index, int count) [inline]
References AttributeValuePairVector(), and swigCPtr.
void Indri::AttributeValuePairVector::Insert (int index, AttributeValuePair value) [inline]
References swigCPtr.
void Indri::AttributeValuePairVector::InsertRange (int index, AttributeValuePairVector values) [inline]
References swigCPtr.
void Indri::AttributeValuePairVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::AttributeValuePairVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static AttributeValuePairVector Indri::AttributeValuePairVector::Repeat (AttributeValuePair value, int count) [inline, static]
References AttributeValuePairVector().
void Indri::AttributeValuePairVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::AttributeValuePairVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::AttributeValuePairVector::Reverse () [inline]
References swigCPtr.
void Indri::AttributeValuePairVector::setitem (int index, AttributeValuePair value) [inline, private]
References swigCPtr.
void Indri::AttributeValuePairVector::SetRange (int index, AttributeValuePairVector values) [inline]
References swigCPtr.
uint Indri::AttributeValuePairVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::AttributeValuePairVector::AttributeValuePairVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::AttributeValuePairVector::swigCMemOwn [protected]
Referenced by AttributeValuePairVector(), and Dispose().
HandleRef Indri::AttributeValuePairVector::swigCPtr [private]
Referenced by Add(), AddRange(), AttributeValuePairVector(), capacity(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::AttributeValuePairVector::Capacity [get, set]
int Indri::AttributeValuePairVector::Count [get]
Referenced by Indri::AttributeValuePairVector::AttributeValuePairVectorEnumerator::AttributeValuePairVectorEnumerator(), CopyTo(), Indri::AttributeValuePairVector::AttributeValuePairVectorEnumerator::MoveNext(), and Indri::AttributeValuePairVector::AttributeValuePairVectorEnumerator::Reset().
bool Indri::AttributeValuePairVector::IsFixedSize [get]
bool Indri::AttributeValuePairVector::IsReadOnly [get]
bool Indri::AttributeValuePairVector::IsSynchronized [get]
AttributeValuePair Indri::AttributeValuePairVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
AttributeValuePairVector.cs