Indri: indri::lang::Packer Class Reference
indri::lang::Packer Class Reference
#include <Packer.hpp>
Classes
struct node_element
Public Member Functions
Packer ()
~Packer ()
void before (class Node *someNode)
void after (class Node *someNode)
void put (const char *name, bool value)
void put (const char *name, int value)
void put (const char *name, unsigned int value)
void put (const char *name, UINT64 value)
void put (const char *name, INT64 value)
void put (const char *name, double value)
void put (const char *name, const std::string &value)
void put (const char *name, const std::vector< lemur::api::DOCID_T > &value)
void put (const char *name, const std::vector< double > &value)
void put (const char *name, const std::vector< std::string > &value)
void put (const char *name, const std::vector< RawExtentNode * > &value)
void put (const char *name, const std::vector< ScoredExtentNode * > &value)
void put (const char *name, Node *value)
void pack (class indri::lang::Node *root)
void pack (std::vector< class indri::lang::Node * > &roots)
std::string toString ()
indri::xml::XMLNode * xml ()
Private Member Functions
node_element * _getElement (class Node *node)
indri::xml::XMLNode * _getNodeReference (class Node *node, const std::string &name)
Private Attributes
std::map< class Node
*, node_element * > _elements
std::stack< node_element * > _stack
indri::xml::XMLNode * _packedNodes
Constructor & Destructor Documentation
indri::lang::Packer::Packer ()
References _packedNodes.
indri::lang::Packer::~Packer ()
References _elements, _packedNodes, and indri::utility::delete_map_contents().
Member Function Documentation
Packer::node_element * indri::lang::Packer::_getElement (class Node * node) [private]
References _elements.
Referenced by before(), and pack().
indri::xml::XMLNode* indri::lang::Packer::_getNodeReference (class Node * node, const std::string & name) [private]
Referenced by put().
void indri::lang::Packer::after (class Node * someNode)
References _packedNodes, _stack, indri::xml::XMLNode::addAttribute(), indri::xml::XMLNode::addChild(), indri::lang::Packer::node_element::flushed, indri::lang::Packer::node_element::languageNode, indri::lang::Node::nodeName(), indri::lang::Node::typeName(), and indri::lang::Packer::node_element::xmlNode.
Referenced by indri::lang::WildcardTerm::pack(), indri::lang::ShrinkageScorerNode::pack(), indri::lang::DocumentStructureNode::pack(), indri::lang::LengthPrior::pack(), indri::lang::ContextInclusionNode::pack(), indri::lang::FieldWildcard::pack(), indri::lang::AnnotatorNode::pack(), indri::lang::ScoreAccumulatorNode::pack(), indri::lang::ContextSimpleCounterNode::pack(), indri::lang::ContextCounterNode::pack(), indri::lang::ListAccumulator::pack(), indri::lang::FilterNode::pack(), indri::lang::FixedPassage::pack(), indri::lang::ExtentRestriction::pack(), indri::lang::NotNode::pack(), indri::lang::WeightedCombinationNode::pack(), indri::lang::UnweightedCombinationNode::pack(), indri::lang::PriorNode::pack(), indri::lang::CachedFrequencyScorerNode::pack(), indri::lang::TermFrequencyScorerNode::pack(), indri::lang::RawScorerNode::pack(), indri::lang::FieldEqualsNode::pack(), indri::lang::FieldBetweenNode::pack(), indri::lang::FieldGreaterNode::pack(), indri::lang::FieldLessNode::pack(), indri::lang::FilRejNode::pack(), indri::lang::FilReqNode::pack(), indri::lang::ODNode::pack(), indri::lang::UWNode::pack(), indri::lang::BAndNode::pack(), indri::lang::ExtentAnd::pack(), indri::lang::ExtentOr::pack(), indri::lang::WeightedExtentOr::pack(), indri::lang::ExtentInside::pack(), indri::lang::Field::pack(), and indri::lang::IndexTerm::pack().
void indri::lang::Packer::before (class Node * someNode)
References _getElement(), and _stack.
Referenced by indri::lang::WildcardTerm::pack(), indri::lang::ShrinkageScorerNode::pack(), indri::lang::DocumentStructureNode::pack(), indri::lang::LengthPrior::pack(), indri::lang::ContextInclusionNode::pack(), indri::lang::FieldWildcard::pack(), indri::lang::AnnotatorNode::pack(), indri::lang::ScoreAccumulatorNode::pack(), indri::lang::ContextSimpleCounterNode::pack(), indri::lang::ContextCounterNode::pack(), indri::lang::ListAccumulator::pack(), indri::lang::FilterNode::pack(), indri::lang::FixedPassage::pack(), indri::lang::ExtentRestriction::pack(), indri::lang::NotNode::pack(), indri::lang::WeightedCombinationNode::pack(), indri::lang::UnweightedCombinationNode::pack(), indri::lang::PriorNode::pack(), indri::lang::CachedFrequencyScorerNode::pack(), indri::lang::TermFrequencyScorerNode::pack(), indri::lang::RawScorerNode::pack(), indri::lang::FieldEqualsNode::pack(), indri::lang::FieldBetweenNode::pack(), indri::lang::FieldGreaterNode::pack(), indri::lang::FieldLessNode::pack(), indri::lang::FilRejNode::pack(), indri::lang::FilReqNode::pack(), indri::lang::ODNode::pack(), indri::lang::UWNode::pack(), indri::lang::BAndNode::pack(), indri::lang::ExtentAnd::pack(), indri::lang::ExtentOr::pack(), indri::lang::WeightedExtentOr::pack(), indri::lang::ExtentInside::pack(), indri::lang::Field::pack(), and indri::lang::IndexTerm::pack().
void indri::lang::Packer::pack (std::vector< class indri::lang::Node * > & roots)
void indri::lang::Packer::pack (class indri::lang::Node * root)
References _getElement(), indri::xml::XMLNode::addAttribute(), indri::lang::Node::pack(), and indri::lang::Packer::node_element::xmlNode.
Referenced by indri::server::NetworkServerProxy::runQuery().
void indri::lang::Packer::put (const char * name, Node * value)
References _getNodeReference(), and _stack.
void indri::lang::Packer::put (const char * name, const std::vector< ScoredExtentNode * > & value)
void indri::lang::Packer::put (const char * name, const std::vector< RawExtentNode * > & value)
void indri::lang::Packer::put (const char * name, const std::vector< std::string > & value)
void indri::lang::Packer::put (const char * name, const std::vector< double > & value)
void indri::lang::Packer::put (const char * name, const std::vector< lemur::api::DOCID_T > & value)
void indri::lang::Packer::put (const char * name, const std::string & value)
void indri::lang::Packer::put (const char * name, double value)
References _stack.
void indri::lang::Packer::put (const char * name, INT64 value)
References _stack.
void indri::lang::Packer::put (const char * name, UINT64 value)
References put().
void indri::lang::Packer::put (const char * name, unsigned int value)
References put().
void indri::lang::Packer::put (const char * name, int value)
References put().
void indri::lang::Packer::put (const char * name, bool value)
Referenced by indri::lang::WildcardTerm::pack(), indri::lang::ShrinkageScorerNode::pack(), indri::lang::LengthPrior::pack(), indri::lang::ContextInclusionNode::pack(), indri::lang::AnnotatorNode::pack(), indri::lang::ScoreAccumulatorNode::pack(), indri::lang::ContextSimpleCounterNode::pack(), indri::lang::ContextCounterNode::pack(), indri::lang::ListAccumulator::pack(), indri::lang::FilterNode::pack(), indri::lang::FixedPassage::pack(), indri::lang::ExtentRestriction::pack(), indri::lang::NotNode::pack(), indri::lang::WeightedCombinationNode::pack(), indri::lang::UnweightedCombinationNode::pack(), indri::lang::PriorNode::pack(), indri::lang::CachedFrequencyScorerNode::pack(), indri::lang::TermFrequencyScorerNode::pack(), indri::lang::RawScorerNode::pack(), indri::lang::FieldEqualsNode::pack(), indri::lang::FieldBetweenNode::pack(), indri::lang::FieldGreaterNode::pack(), indri::lang::FieldLessNode::pack(), indri::lang::FilRejNode::pack(), indri::lang::FilReqNode::pack(), indri::lang::ODNode::pack(), indri::lang::UWNode::pack(), indri::lang::BAndNode::pack(), indri::lang::ExtentAnd::pack(), indri::lang::ExtentOr::pack(), indri::lang::WeightedExtentOr::pack(), indri::lang::ExtentInside::pack(), indri::lang::Field::pack(), indri::lang::IndexTerm::pack(), and put().
std::string indri::lang::Packer::toString ()
References _packedNodes, and indri::xml::XMLWriter::write().
indri::xml::XMLNode * indri::lang::Packer::xml ()
References _packedNodes.
Referenced by indri::server::NetworkServerProxy::runQuery().
Member Data Documentation
std::map<class Node*, node_element*> indri::lang::Packer::_elements [private]
Referenced by _getElement(), and ~Packer().
indri::xml::XMLNode* indri::lang::Packer::_packedNodes [private]
Referenced by after(), Packer(), toString(), xml(), and ~Packer().
std::stack<node_element*> indri::lang::Packer::_stack [private]
Referenced by after(), before(), and put().
The documentation for this class was generated from the following files:
Packer.hpp
Packer.cpp