Indri: indri::lang::BAndNode Class Reference
indri::lang::BAndNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
BAndNode ()
BAndNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
const std::vector
< RawExtentNode * > & getChildren () const
void addChild (RawExtentNode *node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
std::vector< RawExtentNode * > _children
Constructor & Destructor Documentation
indri::lang::BAndNode::BAndNode () [inline]
Referenced by copy().
indri::lang::BAndNode::BAndNode (Unpacker & unpacker) [inline]
References _children, and indri::lang::Unpacker::getRawExtentVector().
Member Function Documentation
void indri::lang::BAndNode::addChild (RawExtentNode * node) [inline]
References _children.
Referenced by QueryParser::bandNode(), and copy().
Node* indri::lang::BAndNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _children, addChild(), indri::lang::Copier::after(), BAndNode(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
const std::vector<RawExtentNode*>& indri::lang::BAndNode::getChildren () const [inline]
References _children.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::BAndNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _children.
void indri::lang::BAndNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::BAndNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _children.
std::string indri::lang::BAndNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::BAndNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
std::vector<RawExtentNode*> indri::lang::BAndNode::_children [private]
Referenced by addChild(), BAndNode(), copy(), getChildren(), hashCode(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp