Indri: CompressedCollection.cpp File Reference
CompressedCollection.cpp File Reference
#include "indri/CompressedCollection.hpp"
#include "zlib.h"
#include "lemur/string-set.h"
#include "indri/XMLNode.hpp"
#include "lemur/Exception.hpp"
#include "lemur/RVLCompress.hpp"
#include "indri/RVLDecompressStream.hpp"
#include "indri/RVLCompressStream.hpp"
#include "indri/Buffer.hpp"
#include "indri/Path.hpp"
#include "indri/Parameters.hpp"
#include "indri/File.hpp"
#include "indri/ScopedLock.hpp"
#include <algorithm>
Functions
static void * zlib_alloc (void *opaque, uInt items, uInt size)
static void zlib_free (void *opaque, void *address)
static void zlib_deflate (z_stream_s &stream, indri::file::SequentialWriteBuffer *outfile)
static void zlib_deflate_finish (z_stream_s &stream, indri::file::SequentialWriteBuffer *outfile)
static void zlib_read_document (z_stream_s &stream, indri::file::File &infile, UINT64 offset, indri::utility::Buffer &outputBuffer)
static int copy_quad (char *buffer)
static std::vector< std::string > keys_to_vector (indri::utility::HashTable< const char *, lemur::file::Keyfile * > &table)
static bool keyfile_next (lemur::file::Keyfile &keyfile, char *key, int keyLength, indri::utility::Buffer &value)
static bool keyfile_next (lemur::file::Keyfile &keyfile, int &key, indri::utility::Buffer &value)
static void remove_deleted_entries (indri::utility::Buffer &value, indri::index::DeletedDocumentList &deletedList)
static bool keyfile_get (lemur::file::Keyfile &keyfile, int key, indri::utility::Buffer &value)
static bool keyfile_get (lemur::file::Keyfile &keyfile, char *key, indri::utility::Buffer &value)
Variables
const int INPUT_BUFFER_SIZE = 1024
const int OUTPUT_BUFFER_SIZE = 128*1024
const char POSITIONS_KEY [] = "#POSITIONS#"
const char TEXT_KEY [] = "#TEXT#"
const char CONTENT_KEY [] = "#CONTENT#"
const char CONTENTLENGTH_KEY [] = "#CONTENTLENGTH#"
Function Documentation
static int copy_quad (char * buffer) [static]
Referenced by indri::collection::CompressedCollection::retrieve().
static bool keyfile_get (lemur::file::Keyfile & keyfile, char * key, indri::utility::Buffer & value) [static]
References indri::utility::Buffer::clear(), indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
static bool keyfile_get (lemur::file::Keyfile & keyfile, int key, indri::utility::Buffer & value) [static]
References indri::utility::Buffer::clear(), indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
Referenced by indri::collection::CompressedCollection::_copyReverseLookup().
static bool keyfile_next (lemur::file::Keyfile & keyfile, int & key, indri::utility::Buffer & value) [static]
References indri::utility::Buffer::clear(), indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
static bool keyfile_next (lemur::file::Keyfile & keyfile, char * key, int keyLength, indri::utility::Buffer & value) [static]
References indri::utility::Buffer::clear(), indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
Referenced by indri::collection::CompressedCollection::_copyForwardLookup(), indri::collection::CompressedCollection::_copyReverseLookup(), and indri::collection::CompressedCollection::_removeReverseLookups().
static std::vector<std::string> keys_to_vector (indri::utility::HashTable< const char *, lemur::file::Keyfile * > & table) [static]
References indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Referenced by indri::collection::CompressedCollection::forwardFields(), and indri::collection::CompressedCollection::reverseFields().
static void remove_deleted_entries (indri::utility::Buffer & value, indri::index::DeletedDocumentList & deletedList) [static]
References indri::utility::Buffer::front(), indri::index::DeletedDocumentList::isDeleted(), indri::utility::Buffer::position(), and indri::utility::Buffer::unwrite().
Referenced by indri::collection::CompressedCollection::_copyReverseLookup(), and indri::collection::CompressedCollection::_removeReverseLookups().
static void* zlib_alloc (void * opaque, uInt items, uInt size) [static]
Referenced by indri::collection::CompressedCollection::addDocument(), indri::collection::CompressedCollection::CompressedCollection(), and indri::collection::CompressedCollection::retrieve().
static void zlib_deflate (z_stream_s & stream, indri::file::SequentialWriteBuffer * outfile) [static]
References OUTPUT_BUFFER_SIZE, and indri::file::SequentialWriteBuffer::write().
Referenced by indri::collection::CompressedCollection::_writeContent(), indri::collection::CompressedCollection::_writeContentLength(), indri::collection::CompressedCollection::_writeMetadataItem(), indri::collection::CompressedCollection::_writePositions(), and indri::collection::CompressedCollection::_writeText().
static void zlib_deflate_finish (z_stream_s & stream, indri::file::SequentialWriteBuffer * outfile) [static]
References OUTPUT_BUFFER_SIZE, indri::file::SequentialWriteBuffer::unwrite(), and indri::file::SequentialWriteBuffer::write().
Referenced by indri::collection::CompressedCollection::addDocument().
static void zlib_free (void * opaque, void * address) [static]
Referenced by indri::collection::CompressedCollection::addDocument(), indri::collection::CompressedCollection::CompressedCollection(), and indri::collection::CompressedCollection::retrieve().
static void zlib_read_document (z_stream_s & stream, indri::file::File & infile, UINT64 offset, indri::utility::Buffer & outputBuffer) [static]
References indri::utility::Buffer::grow(), INPUT_BUFFER_SIZE, indri::utility::Buffer::position(), indri::file::File::read(), indri::utility::Buffer::size(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by indri::collection::CompressedCollection::retrieve().
Variable Documentation
const char CONTENT_KEY[] = "#CONTENT#"
Referenced by indri::collection::CompressedCollection::_writeContent(), and indri::collection::CompressedCollection::retrieve().
const char CONTENTLENGTH_KEY[] = "#CONTENTLENGTH#"
Referenced by indri::collection::CompressedCollection::_writeContentLength(), and indri::collection::CompressedCollection::retrieve().
const int INPUT_BUFFER_SIZE = 1024
Referenced by zlib_read_document().
const int OUTPUT_BUFFER_SIZE = 128*1024
Referenced by indri::index::IndexWriter::_constructFiles(), indri::index::IndexWriter::_writeDirectLists(), indri::index::IndexWriter::_writeFieldLists(), zlib_deflate(), and zlib_deflate_finish().
const char POSITIONS_KEY[] = "#POSITIONS#"
Referenced by indri::collection::CompressedCollection::_writePositions(), and indri::collection::CompressedCollection::retrieve().
const char TEXT_KEY[] = "#TEXT#"
Referenced by indri::collection::CompressedCollection::_writeText(), and indri::collection::CompressedCollection::retrieve().