Indri: FileClassEnvironmentFactory.cpp File Reference
FileClassEnvironmentFactory.cpp File Reference
#include "indri/FileClassEnvironmentFactory.hpp"
#include "indri/DocumentIteratorFactory.hpp"
#include "indri/ParserFactory.hpp"
#include "indri/TokenizerFactory.hpp"
#include <ctype.h>
#include <map>
#include <vector>
Classes
struct file_class_environment_spec
struct extension_conflations
Functions
static std::string _canonicalExtension (const std::string &name)
static void copy_strings_to_vector (std::vector< std::string > &vec, const char **array)
static void copy_string_tuples_to_map (std::map< indri::parse::ConflationPattern *, std::string > &m, const char **array)
static void cleanup_conflations_map (std::map< indri::parse::ConflationPattern *, std::string > &conflations)
indri::parse::FileClassEnvironment * build_file_class_environment (const file_class_environment_spec *spec)
indri::parse::FileClassEnvironment * build_file_class_environment (const indri::parse::FileClassEnvironmentFactory::Specification *spec)
Variables
static const char * pdf_index_tags [] = { "title", "author", 0 }
static const char * pdf_metadata_tags [] = { "title", "author", 0 }
static const char * html_index_tags [] = { "title", "author", "h1", "h2", "h3", "h4", 0 }
static const char * html_metadata_tags [] = { "title", "author", 0 }
static const char * html_conflations [] = { "h1", NULL, NULL, "heading", "h2", NULL, NULL, "heading", "h3", NULL, NULL, "heading", "h4", NULL, NULL, "heading", 0, 0, 0, 0 }
static const char * trec_include_tags [] = { "text", "hl", "head", "headline", "title", "ttl", "dd", "date", "date_time", "lp", "leadpara", 0 }
static const char * trecalt_include_tags [] = { "text", 0 }
static const char * trecalt_index_tags [] = { "text", 0 }
static const char * trec_metadata_tags [] = { "docno", "title", "author", 0 }
static const char * trec_conflations [] = { "hl", NULL, NULL, "headline", "head", NULL, NULL, "headline", "ttl", NULL, NULL, "title", "dd", NULL, NULL, "date", "date_time", NULL, NULL, "date", 0, 0, 0, 0 }
static const char * trec_index_tags [] = { "author", "hl", "head", "headline", "title", "ttl", "dd", "date_time", "date", 0 }
static const char * html_exclude_tags [] = { "script", "style", 0}
static const char * _html [] = {"html", "htm", 0}
static const char * _txt [] = {"txt", "text", 0}
static const char * _doc [] = {"doc", "docx", 0}
static const char * _ppt [] = {"ppt", "pptx", 0}
static extension_conflations extensions []
static file_class_environment_spec environments []
Function Documentation
static std::string _canonicalExtension (const std::string & name) [static]
References extension_conflations::alternates.
Referenced by indri::parse::FileClassEnvironmentFactory::get(), and indri::parse::FileClassEnvironmentFactory::getFileClassSpec().
indri::parse::FileClassEnvironment* build_file_class_environment (const indri::parse::FileClassEnvironmentFactory::Specification * spec)
References indri::parse::FileClassEnvironment::conflater, indri::parse::FileClassEnvironmentFactory::Specification::conflations, indri::parse::FileClassEnvironmentFactory::Specification::endDocTag, indri::parse::FileClassEnvironmentFactory::Specification::endMetadataTag, indri::parse::FileClassEnvironmentFactory::Specification::exclude, indri::parse::TokenizerFactory::get(), indri::parse::ParserFactory::get(), indri::parse::DocumentIteratorFactory::get(), indri::parse::FileClassEnvironmentFactory::Specification::include, indri::parse::FileClassEnvironmentFactory::Specification::index, indri::parse::FileClassEnvironmentFactory::Specification::iterator, indri::parse::FileClassEnvironment::iterator, indri::parse::FileClassEnvironmentFactory::Specification::metadata, indri::parse::FileClassEnvironmentFactory::Specification::parser, indri::parse::FileClassEnvironment::parser, indri::parse::FileClassEnvironmentFactory::Specification::startDocTag, indri::parse::FileClassEnvironmentFactory::Specification::tokenizer, and indri::parse::FileClassEnvironment::tokenizer.
indri::parse::FileClassEnvironment* build_file_class_environment (const file_class_environment_spec * spec)
References cleanup_conflations_map(), indri::parse::FileClassEnvironment::conflater, file_class_environment_spec::conflations, indri::parse::conflations, copy_string_tuples_to_map(), copy_strings_to_vector(), file_class_environment_spec::endDocTag, file_class_environment_spec::endMetadataTag, file_class_environment_spec::excludeTags, indri::parse::TokenizerFactory::get(), indri::parse::ParserFactory::get(), indri::parse::DocumentIteratorFactory::get(), file_class_environment_spec::includeTags, file_class_environment_spec::indexTags, file_class_environment_spec::iterator, indri::parse::FileClassEnvironment::iterator, file_class_environment_spec::metadataTags, file_class_environment_spec::parser, indri::parse::FileClassEnvironment::parser, file_class_environment_spec::startDocTag, file_class_environment_spec::tokenizer, and indri::parse::FileClassEnvironment::tokenizer.
Referenced by indri::parse::FileClassEnvironmentFactory::get().
static void cleanup_conflations_map (std::map< indri::parse::ConflationPattern *, std::string > & conflations) [static]
Referenced by build_file_class_environment().
static void copy_string_tuples_to_map (std::map< indri::parse::ConflationPattern *, std::string > & m, const char ** array) [static]
References indri::parse::ConflationPattern::attribute_name, indri::parse::ConflationPattern::tag_name, and indri::parse::ConflationPattern::value.
Referenced by build_file_class_environment(), and indri::parse::FileClassEnvironmentFactory::getFileClassSpec().
static void copy_strings_to_vector (std::vector< std::string > & vec, const char ** array) [static]
Referenced by build_file_class_environment(), and indri::parse::FileClassEnvironmentFactory::getFileClassSpec().
Variable Documentation
const char* _doc[] = {"doc", "docx", 0} [static]
const char* _html[] = {"html", "htm", 0} [static]
const char* _ppt[] = {"ppt", "pptx", 0} [static]
const char* _txt[] = {"txt", "text", 0} [static]
file_class_environment_spec environments[] [static]
extension_conflations extensions[] [static]
Initial value:
 {
  _html, _txt, _doc, _ppt, {0}
}
const char* html_conflations[] = { "h1", NULL, NULL, "heading", "h2", NULL, NULL, "heading", "h3", NULL, NULL, "heading", "h4", NULL, NULL, "heading", 0, 0, 0, 0 } [static]
const char* html_exclude_tags[] = { "script", "style", 0} [static]
const char* html_index_tags[] = { "title", "author", "h1", "h2", "h3", "h4", 0 } [static]
const char* html_metadata_tags[] = { "title", "author", 0 } [static]
const char* pdf_index_tags[] = { "title", "author", 0 } [static]
const char* pdf_metadata_tags[] = { "title", "author", 0 } [static]
const char* trec_conflations[] = { "hl", NULL, NULL, "headline", "head", NULL, NULL, "headline", "ttl", NULL, NULL, "title", "dd", NULL, NULL, "date", "date_time", NULL, NULL, "date", 0, 0, 0, 0 } [static]
const char* trec_include_tags[] = { "text", "hl", "head", "headline", "title", "ttl", "dd", "date", "date_time", "lp", "leadpara", 0 } [static]
const char* trec_index_tags[] = { "author", "hl", "head", "headline", "title", "ttl", "dd", "date_time", "date", 0 } [static]
const char* trec_metadata_tags[] = { "docno", "title", "author", 0 } [static]
const char* trecalt_include_tags[] = { "text", 0 } [static]
const char* trecalt_index_tags[] = { "text", 0 } [static]