Indri: harvestlinks.cpp File Reference
harvestlinks.cpp File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <time.h>
#include "indri/Parameters.hpp"
#include "indri/TokenizedDocument.hpp"
#include "indri/ParsedDocument.hpp"
#include "indri/TaggedDocumentIterator.hpp"
#include "indri/WARCDocumentIterator.hpp"
#include "indri/TaggedTextParser.hpp"
#include "indri/HTMLParser.hpp"
#include "indri/TokenizerFactory.hpp"
#include "indri/ConflationPattern.hpp"
#include "indri/AnchorTextHarvester.hpp"
#include "indri/FileTreeIterator.hpp"
#include "indri/Path.hpp"
#include "lemur/Exception.hpp"
#include "indri/Combiner.hpp"
#include "lemur/Keyfile.hpp"
#include "lemur/HarvestSortMerge.hpp"
#include "indri/IndriTimer.hpp"
#include "lemur/SHA1.hpp"
Functions
std::string getFinalHarvestPath (const std::string &corpusPath, const std::string &filePath, const std::string &harvestPath)
static lemur::file::Keyfile * createRedirectKeyfile (const std::string &redirectKeyfilePath, const std::string &redirectPath)
static void harvest_anchor_text_file (const std::string &path, const std::string &linkFilePath, const std::string &docOrderPath, lemur::file::Keyfile *redirectKeyfile, indri::parse::HTMLParser &parser, indri::parse::Tokenizer *tokenizer, lemur::file::Keyfile *keyfile, const std::string &fileClass)
static void harvest_anchor_text (const std::string &corpusPath, const std::string &fileClass, const std::string &harvestPath, const std::string &docUrlNoKeyfilePath, const std::string &preSortPath, const std::string &redirectPath)
static void collect_harvest_paths (const std::string &corpusPath, const std::string &fileClass, const std::string &harvestPath, const std::string &docUrlNoKeyfilePath, const std::string &preSortPath, const std::string &redirectPath)
void combineOutputFile (const std::string &corpusFile, const std::string &sortedPath, const std::string &outputSortedLinkFile, const std::string &docOrderPath, lemur::file::Keyfile *urlKeyfile, FILE *sortedDestFile, lemur::file::Keyfile *docNoKeyfile)
void combineSortedFiles (const std::string &corpusPath, const std::string &harvestPath, const std::string &outputSortedLinkFile, const std::string &preSortPath, const std::string &sortedPath, lemur::file::Keyfile *docNoKeyfile)
void usage ()
int main (int argc, char *argv[])
Variables
std::vector< std::string > harvestedLinkPaths
static indri::utility::IndriTimer g_timer
static lemur::utility::SHA1 SHA1Hasher
char _outputBuffer [5 *1024 *1024]
Function Documentation
static void collect_harvest_paths (const std::string & corpusPath, const std::string & fileClass, const std::string & harvestPath, const std::string & docUrlNoKeyfilePath, const std::string & preSortPath, const std::string & redirectPath) [static]
References indri::file::Path::combine(), indri::file::Path::directory(), indri::file::FileTreeIterator::end(), indri::file::Path::filename(), getFinalHarvestPath(), harvestedLinkPaths, and indri::file::Path::isDirectory().
Referenced by main().
void combineOutputFile (const std::string & corpusFile, const std::string & sortedPath, const std::string & outputSortedLinkFile, const std::string & docOrderPath, lemur::file::Keyfile * urlKeyfile, FILE * sortedDestFile, lemur::file::Keyfile * docNoKeyfile)
References _outputBuffer, indri::utility::Buffer::clear(), indri::file::Path::combine(), indri::file::Path::filename(), and SHA1Hasher.
Referenced by combineSortedFiles().
void combineSortedFiles (const std::string & corpusPath, const std::string & harvestPath, const std::string & outputSortedLinkFile, const std::string & preSortPath, const std::string & sortedPath, lemur::file::Keyfile * docNoKeyfile)
References indri::utility::Buffer::clear(), indri::file::Path::combine(), combineOutputFile(), indri::file::Path::directory(), indri::file::FileTreeIterator::end(), indri::file::Path::filename(), getFinalHarvestPath(), indri::file::Path::isDirectory(), indri::file::Path::make(), and SHA1Hasher.
Referenced by main().
static lemur::file::Keyfile* createRedirectKeyfile (const std::string & redirectKeyfilePath, const std::string & redirectPath) [static]
References SHA1Hasher.
Referenced by harvest_anchor_text().
std::string getFinalHarvestPath (const std::string & corpusPath, const std::string & filePath, const std::string & harvestPath)
References indri::file::Path::combine(), and indri::file::Path::directory().
Referenced by collect_harvest_paths(), combineSortedFiles(), and harvest_anchor_text().
static void harvest_anchor_text (const std::string & corpusPath, const std::string & fileClass, const std::string & harvestPath, const std::string & docUrlNoKeyfilePath, const std::string & preSortPath, const std::string & redirectPath) [static]
References indri::file::Path::combine(), createRedirectKeyfile(), indri::file::Path::directory(), indri::file::FileTreeIterator::end(), indri::file::Path::filename(), indri::parse::TokenizerFactory::get(), getFinalHarvestPath(), harvest_anchor_text_file(), indri::file::Path::isDirectory(), indri::file::Path::make(), and indri::parse::TaggedTextParser::setTags().
Referenced by main().
static void harvest_anchor_text_file (const std::string & path, const std::string & linkFilePath, const std::string & docOrderPath, lemur::file::Keyfile * redirectKeyfile, indri::parse::HTMLParser & parser, indri::parse::Tokenizer * tokenizer, lemur::file::Keyfile * keyfile, const std::string & fileClass) [static]
References indri::parse::DocumentIterator::close(), indri::parse::AnchorTextHarvester::handle(), harvestedLinkPaths, indri::parse::DocumentIterator::nextDocument(), indri::parse::DocumentIterator::open(), indri::parse::TaggedTextParser::parse(), and indri::parse::Tokenizer::tokenize().
Referenced by harvest_anchor_text().
int main (int argc, char * argv[])
References collect_harvest_paths(), indri::file::Path::combine(), combineSortedFiles(), indri::file::Path::exists(), indri::api::Parameters::exists(), indri::api::Parameters::get(), harvest_anchor_text(), harvestedLinkPaths, INDRI_DISTRIBUTION, indri::api::Parameters::instance(), indri::file::Path::isDirectory(), indri::api::Parameters::loadCommandLine(), indri::file::Path::make(), indri::utility::IndriTimer::printElapsedSeconds(), indri::file::Path::remove(), indri::utility::IndriTimer::start(), and usage().
void usage ()
Variable Documentation
char _outputBuffer[5 *1024 *1024]
Referenced by combineOutputFile().
indri::utility::IndriTimer g_timer [static]
std::vector<std::string> harvestedLinkPaths
Referenced by collect_harvest_paths(), harvest_anchor_text_file(), and main().
lemur::utility::SHA1 SHA1Hasher [static]
Referenced by combineOutputFile(), combineSortedFiles(), and createRedirectKeyfile().