Indri: indri_csharp.cpp File Reference
indri_csharp.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "indri/indri-platform.h"
#include "lemur-compat.hpp"
#include "indri/QueryEnvironment.hpp"
#include "indri/QueryExpander.hpp"
#include "indri/RMExpander.hpp"
#include "indri/PonteExpander.hpp"
#include "indri/ScoredExtentResult.hpp"
#include "indri/ParsedDocument.hpp"
#include "indri/IndexEnvironment.hpp"
#include "indri/Parameters.hpp"
#include "indri/ConflationPattern.hpp"
#include "indri/ReformulateQuery.hpp"
#include "Exception.hpp"
#include <string>
#include <stdexcept>
#include <map>
#include <algorithm>
#include <vector>
#include "indri/greedy_vector"
#include "indri/TagList.hpp"
#include "indri_csharp.h"
Classes
struct SWIG_CSharpException_t
struct SWIG_CSharpExceptionArgument_t
Namespaces
namespace indri
namespaces within the indri system
namespace indri::api
Indri API classes for interacting with indri collections.
namespace indri::parse
File input, parsing, stemming, and stopping classes.
Defines
#define SWIGCSHARP
#define SWIG_DIRECTORS
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGINLINE
#define SWIGUNUSED
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGEXPORT
#define SWIGSTDCALL
#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
Typedefs
typedef void(SWIGSTDCALL * SWIG_CSharpExceptionCallback_t)(const char *)
typedef void(SWIGSTDCALL * SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *)
typedef char *(SWIGSTDCALL * SWIG_CSharpStringHelperCallback)(const char *)
typedef
indri::api::DocumentVector::Field indri::api::Field
typedef
indri::parse::FileClassEnvironmentFactory::Specification indri::parse::Specification
Enumerations
enum SWIG_CSharpExceptionCodes {
SWIG_CSharpApplicationException, SWIG_CSharpArithmeticException, SWIG_CSharpDivideByZeroException, SWIG_CSharpIndexOutOfRangeException,
SWIG_CSharpInvalidCastException, SWIG_CSharpInvalidOperationException, SWIG_CSharpIOException, SWIG_CSharpNullReferenceException,
SWIG_CSharpOutOfMemoryException, SWIG_CSharpOverflowException, SWIG_CSharpSystemException
}
enum SWIG_CSharpExceptionArgumentCodes { SWIG_CSharpArgumentException, SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException }
Functions
static void SWIGUNUSED SWIG_CSharpSetPendingException (SWIG_CSharpExceptionCodes code, const char *msg)
static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument (SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name)
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_indri_csharp (SWIG_CSharpExceptionCallback_t applicationCallback, SWIG_CSharpExceptionCallback_t arithmeticCallback, SWIG_CSharpExceptionCallback_t divideByZeroCallback, SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, SWIG_CSharpExceptionCallback_t invalidCastCallback, SWIG_CSharpExceptionCallback_t invalidOperationCallback, SWIG_CSharpExceptionCallback_t ioCallback, SWIG_CSharpExceptionCallback_t nullReferenceCallback, SWIG_CSharpExceptionCallback_t outOfMemoryCallback, SWIG_CSharpExceptionCallback_t overflowCallback, SWIG_CSharpExceptionCallback_t systemCallback)
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_indri_csharp (SWIG_CSharpExceptionArgumentCallback_t argumentCallback, SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback, SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback)
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_indri_csharp (SWIG_CSharpStringHelperCallback callback)
SWIGINTERN void SWIG_CSharpException (int code, const char *msg)
SWIGINTERN std::vector< int > * new_std_vector_Sl_int_Sg___SWIG_2 (int capacity)
SWIGINTERN int std_vector_Sl_int_Sg__getitemcopy (std::vector< int > *self, int index)
SWIGINTERN std::vector< int >
::const_reference std_vector_Sl_int_Sg__getitem (std::vector< int > *self, int index)
SWIGINTERN void std_vector_Sl_int_Sg__setitem (std::vector< int > *self, int index, int const &val)
SWIGINTERN void std_vector_Sl_int_Sg__AddRange (std::vector< int > *self, std::vector< int > const &values)
SWIGINTERN std::vector< int > * std_vector_Sl_int_Sg__GetRange (std::vector< int > *self, int index, int count)
SWIGINTERN void std_vector_Sl_int_Sg__Insert (std::vector< int > *self, int index, int const &x)
SWIGINTERN void std_vector_Sl_int_Sg__InsertRange (std::vector< int > *self, int index, std::vector< int > const &values)
SWIGINTERN void std_vector_Sl_int_Sg__RemoveAt (std::vector< int > *self, int index)
SWIGINTERN void std_vector_Sl_int_Sg__RemoveRange (std::vector< int > *self, int index, int count)
SWIGINTERN std::vector< int > * std_vector_Sl_int_Sg__Repeat (int const &value, int count)
SWIGINTERN void std_vector_Sl_int_Sg__Reverse__SWIG_0 (std::vector< int > *self)
SWIGINTERN void std_vector_Sl_int_Sg__Reverse__SWIG_1 (std::vector< int > *self, int index, int count)
SWIGINTERN void std_vector_Sl_int_Sg__SetRange (std::vector< int > *self, int index, std::vector< int > const &values)
SWIGINTERN bool std_vector_Sl_int_Sg__Contains (std::vector< int > *self, int const &value)
SWIGINTERN int std_vector_Sl_int_Sg__IndexOf (std::vector< int > *self, int const &value)
SWIGINTERN int std_vector_Sl_int_Sg__LastIndexOf (std::vector< int > *self, int const &value)
SWIGINTERN bool std_vector_Sl_int_Sg__Remove (std::vector< int > *self, int const &value)
SWIGINTERN std::vector
< std::string > * new_std_vector_Sl_std_string_Sg___SWIG_2 (int capacity)
SWIGINTERN std::string std_vector_Sl_std_string_Sg__getitemcopy (std::vector< std::string > *self, int index)
SWIGINTERN std::vector
< std::string >
::const_reference std_vector_Sl_std_string_Sg__getitem (std::vector< std::string > *self, int index)
SWIGINTERN void std_vector_Sl_std_string_Sg__setitem (std::vector< std::string > *self, int index, std::string const &val)
SWIGINTERN void std_vector_Sl_std_string_Sg__AddRange (std::vector< std::string > *self, std::vector< std::string > const &values)
SWIGINTERN std::vector
< std::string > * std_vector_Sl_std_string_Sg__GetRange (std::vector< std::string > *self, int index, int count)
SWIGINTERN void std_vector_Sl_std_string_Sg__Insert (std::vector< std::string > *self, int index, std::string const &x)
SWIGINTERN void std_vector_Sl_std_string_Sg__InsertRange (std::vector< std::string > *self, int index, std::vector< std::string > const &values)
SWIGINTERN void std_vector_Sl_std_string_Sg__RemoveAt (std::vector< std::string > *self, int index)
SWIGINTERN void std_vector_Sl_std_string_Sg__RemoveRange (std::vector< std::string > *self, int index, int count)
SWIGINTERN std::vector
< std::string > * std_vector_Sl_std_string_Sg__Repeat (std::string const &value, int count)
SWIGINTERN void std_vector_Sl_std_string_Sg__Reverse__SWIG_0 (std::vector< std::string > *self)
SWIGINTERN void std_vector_Sl_std_string_Sg__Reverse__SWIG_1 (std::vector< std::string > *self, int index, int count)
SWIGINTERN void std_vector_Sl_std_string_Sg__SetRange (std::vector< std::string > *self, int index, std::vector< std::string > const &values)
SWIGINTERN bool std_vector_Sl_std_string_Sg__Contains (std::vector< std::string > *self, std::string const &value)
SWIGINTERN int std_vector_Sl_std_string_Sg__IndexOf (std::vector< std::string > *self, std::string const &value)
SWIGINTERN int std_vector_Sl_std_string_Sg__LastIndexOf (std::vector< std::string > *self, std::string const &value)
SWIGINTERN bool std_vector_Sl_std_string_Sg__Remove (std::vector< std::string > *self, std::string const &value)
SWIGINTERN std::map
< indri::parse::ConflationPattern
*, std::string >::mapped_type
const & std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__getitem (std::map< indri::parse::ConflationPattern *, std::string > *self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const &key)
SWIGINTERN void std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__setitem (std::map< indri::parse::ConflationPattern *, std::string > *self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const &key, std::map< indri::parse::ConflationPattern *, std::string >::mapped_type const &x)
SWIGINTERN bool std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__ContainsKey (std::map< indri::parse::ConflationPattern *, std::string > *self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const &key)
SWIGINTERN void std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__Add (std::map< indri::parse::ConflationPattern *, std::string > *self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const &key, std::map< indri::parse::ConflationPattern *, std::string >::mapped_type const &val)
SWIGINTERN bool std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__Remove (std::map< indri::parse::ConflationPattern *, std::string > *self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const &key)
SWIGINTERN std::map
< indri::parse::ConflationPattern
*, std::string >::iterator * std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__create_iterator_begin (std::map< indri::parse::ConflationPattern *, std::string > *self)
SWIGINTERN std::map
< indri::parse::ConflationPattern
*, std::string >::key_type
const & std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__get_next_key (std::map< indri::parse::ConflationPattern *, std::string > *self, std::map< indri::parse::ConflationPattern *, std::string >::iterator *swigiterator)
SWIGINTERN std::map
< std::string, std::vector
< indri::api::ScoredExtentResult >
>::mapped_type const & std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__getitem (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const &key)
SWIGINTERN void std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__setitem (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const &key, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::mapped_type const &x)
SWIGINTERN bool std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__ContainsKey (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const &key)
SWIGINTERN void std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__Add (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const &key, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::mapped_type const &val)
SWIGINTERN bool std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__Remove (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const &key)
SWIGINTERN std::map
< std::string, std::vector
< indri::api::ScoredExtentResult >
>::iterator * std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__create_iterator_begin (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self)
SWIGINTERN std::map
< std::string, std::vector
< indri::api::ScoredExtentResult >
>::key_type const & std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__get_next_key (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > *self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::iterator *swigiterator)
SWIGINTERN std::vector
< indri::parse::MetadataPair > * new_std_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_2 (int capacity)
SWIGINTERN
indri::parse::MetadataPair std_vector_Sl_indri_parse_MetadataPair_Sg__getitemcopy (std::vector< indri::parse::MetadataPair > *self, int index)
SWIGINTERN std::vector
< indri::parse::MetadataPair >
::const_reference std_vector_Sl_indri_parse_MetadataPair_Sg__getitem (std::vector< indri::parse::MetadataPair > *self, int index)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__setitem (std::vector< indri::parse::MetadataPair > *self, int index, indri::parse::MetadataPair const &val)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__AddRange (std::vector< indri::parse::MetadataPair > *self, std::vector< indri::parse::MetadataPair > const &values)
SWIGINTERN std::vector
< indri::parse::MetadataPair > * std_vector_Sl_indri_parse_MetadataPair_Sg__GetRange (std::vector< indri::parse::MetadataPair > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__Insert (std::vector< indri::parse::MetadataPair > *self, int index, indri::parse::MetadataPair const &x)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange (std::vector< indri::parse::MetadataPair > *self, int index, std::vector< indri::parse::MetadataPair > const &values)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__RemoveAt (std::vector< indri::parse::MetadataPair > *self, int index)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__RemoveRange (std::vector< indri::parse::MetadataPair > *self, int index, int count)
SWIGINTERN std::vector
< indri::parse::MetadataPair > * std_vector_Sl_indri_parse_MetadataPair_Sg__Repeat (indri::parse::MetadataPair const &value, int count)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_0 (std::vector< indri::parse::MetadataPair > *self)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_1 (std::vector< indri::parse::MetadataPair > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__SetRange (std::vector< indri::parse::MetadataPair > *self, int index, std::vector< indri::parse::MetadataPair > const &values)
SWIGINTERN std::vector
< indri::api::ParsedDocument * > * new_std_vector_Sl_indri_api_ParsedDocument_Sm__Sg___SWIG_2 (int capacity)
SWIGINTERN
indri::api::ParsedDocument * std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__getitemcopy (std::vector< indri::api::ParsedDocument * > *self, int index)
SWIGINTERN std::vector
< indri::api::ParsedDocument * >
::const_reference std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__getitem (std::vector< indri::api::ParsedDocument * > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__setitem (std::vector< indri::api::ParsedDocument * > *self, int index, indri::api::ParsedDocument *const &val)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__AddRange (std::vector< indri::api::ParsedDocument * > *self, std::vector< indri::api::ParsedDocument * > const &values)
SWIGINTERN std::vector
< indri::api::ParsedDocument * > * std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__GetRange (std::vector< indri::api::ParsedDocument * > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Insert (std::vector< indri::api::ParsedDocument * > *self, int index, indri::api::ParsedDocument *const &x)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__InsertRange (std::vector< indri::api::ParsedDocument * > *self, int index, std::vector< indri::api::ParsedDocument * > const &values)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__RemoveAt (std::vector< indri::api::ParsedDocument * > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__RemoveRange (std::vector< indri::api::ParsedDocument * > *self, int index, int count)
SWIGINTERN std::vector
< indri::api::ParsedDocument * > * std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Repeat (indri::api::ParsedDocument *const &value, int count)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Reverse__SWIG_0 (std::vector< indri::api::ParsedDocument * > *self)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Reverse__SWIG_1 (std::vector< indri::api::ParsedDocument * > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__SetRange (std::vector< indri::api::ParsedDocument * > *self, int index, std::vector< indri::api::ParsedDocument * > const &values)
SWIGINTERN bool std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Contains (std::vector< indri::api::ParsedDocument * > *self, indri::api::ParsedDocument *const &value)
SWIGINTERN int std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__IndexOf (std::vector< indri::api::ParsedDocument * > *self, indri::api::ParsedDocument *const &value)
SWIGINTERN int std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__LastIndexOf (std::vector< indri::api::ParsedDocument * > *self, indri::api::ParsedDocument *const &value)
SWIGINTERN bool std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Remove (std::vector< indri::api::ParsedDocument * > *self, indri::api::ParsedDocument *const &value)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TermExtent > * new_indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg___SWIG_1 (int capacity)
SWIGINTERN indri::parse::TermExtent indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TermExtent >
::const_reference indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__getitem (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__setitem (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, indri::parse::TermExtent const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__AddRange (indri::utility::greedy_vector< indri::parse::TermExtent > *self, indri::utility::greedy_vector< indri::parse::TermExtent > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TermExtent > * indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__GetRange (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Insert (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, indri::parse::TermExtent const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, indri::utility::greedy_vector< indri::parse::TermExtent > const &values)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, int count)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TermExtent > * indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Repeat (indri::parse::TermExtent const &value, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::TermExtent > *self)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__SetRange (indri::utility::greedy_vector< indri::parse::TermExtent > *self, int index, indri::utility::greedy_vector< indri::parse::TermExtent > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::MetadataPair > * new_indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_1 (int capacity)
SWIGINTERN
indri::parse::MetadataPair indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::MetadataPair >
::const_reference indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__getitem (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__setitem (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, indri::parse::MetadataPair const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__AddRange (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, indri::utility::greedy_vector< indri::parse::MetadataPair > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::MetadataPair > * indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__GetRange (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Insert (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, indri::parse::MetadataPair const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, indri::utility::greedy_vector< indri::parse::MetadataPair > const &values)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, int count)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::MetadataPair > * indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Repeat (indri::parse::MetadataPair const &value, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::MetadataPair > *self)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__SetRange (indri::utility::greedy_vector< indri::parse::MetadataPair > *self, int index, indri::utility::greedy_vector< indri::parse::MetadataPair > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TagExtent > * new_indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg___SWIG_1 (int capacity)
SWIGINTERN indri::parse::TagExtent indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TagExtent >
::const_reference indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__getitem (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__setitem (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, indri::parse::TagExtent const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__AddRange (indri::utility::greedy_vector< indri::parse::TagExtent > *self, indri::utility::greedy_vector< indri::parse::TagExtent > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TagExtent > * indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__GetRange (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Insert (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, indri::parse::TagExtent const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, indri::utility::greedy_vector< indri::parse::TagExtent > const &values)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, int count)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::TagExtent > * indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Repeat (indri::parse::TagExtent const &value, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::TagExtent > *self)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__SetRange (indri::utility::greedy_vector< indri::parse::TagExtent > *self, int index, indri::utility::greedy_vector< indri::parse::TagExtent > const &values)
SWIGINTERN
indri::utility::greedy_vector
< char * > * new_indri_utility_greedy_vector_Sl_char_Sm__Sg___SWIG_1 (int capacity)
SWIGINTERN char * indri_utility_greedy_vector_Sl_char_Sm__Sg__getitemcopy (indri::utility::greedy_vector< char * > *self, int index)
SWIGINTERN
indri::utility::greedy_vector
< char * >::const_reference indri_utility_greedy_vector_Sl_char_Sm__Sg__getitem (indri::utility::greedy_vector< char * > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__setitem (indri::utility::greedy_vector< char * > *self, int index, char const *&value)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__AddRange (indri::utility::greedy_vector< char * > *self, indri::utility::greedy_vector< char * > const &values)
SWIGINTERN
indri::utility::greedy_vector
< char * > * indri_utility_greedy_vector_Sl_char_Sm__Sg__GetRange (indri::utility::greedy_vector< char * > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__Insert (indri::utility::greedy_vector< char * > *self, int index, char const *&value)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__InsertRange (indri::utility::greedy_vector< char * > *self, int index, indri::utility::greedy_vector< char * > const &values)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__RemoveAt (indri::utility::greedy_vector< char * > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__RemoveRange (indri::utility::greedy_vector< char * > *self, int index, int count)
SWIGINTERN
indri::utility::greedy_vector
< char * > * indri_utility_greedy_vector_Sl_char_Sm__Sg__Repeat (char const *&value, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< char * > *self)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< char * > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__SetRange (indri::utility::greedy_vector< char * > *self, int index, indri::utility::greedy_vector< char * > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::AttributeValuePair > * new_indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg___SWIG_1 (int capacity)
SWIGINTERN
indri::parse::AttributeValuePair indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::AttributeValuePair >
::const_reference indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__getitem (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__setitem (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, indri::parse::AttributeValuePair const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__AddRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, indri::utility::greedy_vector< indri::parse::AttributeValuePair > const &values)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::AttributeValuePair > * indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__GetRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Insert (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, indri::parse::AttributeValuePair const &value)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, indri::utility::greedy_vector< indri::parse::AttributeValuePair > const &values)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, int count)
SWIGINTERN
indri::utility::greedy_vector
< indri::parse::AttributeValuePair > * indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Repeat (indri::parse::AttributeValuePair const &value, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, int count)
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__SetRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > *self, int index, indri::utility::greedy_vector< indri::parse::AttributeValuePair > const &values)
SWIGINTERN std::vector
< indri::api::QueryAnnotationNode * > * new_std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg___SWIG_2 (int capacity)
SWIGINTERN
indri::api::QueryAnnotationNode * std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__getitemcopy (std::vector< indri::api::QueryAnnotationNode * > *self, int index)
SWIGINTERN std::vector
< indri::api::QueryAnnotationNode * >
::const_reference std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__getitem (std::vector< indri::api::QueryAnnotationNode * > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__setitem (std::vector< indri::api::QueryAnnotationNode * > *self, int index, indri::api::QueryAnnotationNode *const &val)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__AddRange (std::vector< indri::api::QueryAnnotationNode * > *self, std::vector< indri::api::QueryAnnotationNode * > const &values)
SWIGINTERN std::vector
< indri::api::QueryAnnotationNode * > * std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__GetRange (std::vector< indri::api::QueryAnnotationNode * > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Insert (std::vector< indri::api::QueryAnnotationNode * > *self, int index, indri::api::QueryAnnotationNode *const &x)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__InsertRange (std::vector< indri::api::QueryAnnotationNode * > *self, int index, std::vector< indri::api::QueryAnnotationNode * > const &values)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__RemoveAt (std::vector< indri::api::QueryAnnotationNode * > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__RemoveRange (std::vector< indri::api::QueryAnnotationNode * > *self, int index, int count)
SWIGINTERN std::vector
< indri::api::QueryAnnotationNode * > * std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Repeat (indri::api::QueryAnnotationNode *const &value, int count)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Reverse__SWIG_0 (std::vector< indri::api::QueryAnnotationNode * > *self)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Reverse__SWIG_1 (std::vector< indri::api::QueryAnnotationNode * > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__SetRange (std::vector< indri::api::QueryAnnotationNode * > *self, int index, std::vector< indri::api::QueryAnnotationNode * > const &values)
SWIGINTERN bool std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Contains (std::vector< indri::api::QueryAnnotationNode * > *self, indri::api::QueryAnnotationNode *const &value)
SWIGINTERN int std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__IndexOf (std::vector< indri::api::QueryAnnotationNode * > *self, indri::api::QueryAnnotationNode *const &value)
SWIGINTERN int std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__LastIndexOf (std::vector< indri::api::QueryAnnotationNode * > *self, indri::api::QueryAnnotationNode *const &value)
SWIGINTERN bool std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Remove (std::vector< indri::api::QueryAnnotationNode * > *self, indri::api::QueryAnnotationNode *const &value)
SWIGINTERN std::vector
< indri::api::ScoredExtentResult > * new_std_vector_Sl_indri_api_ScoredExtentResult_Sg___SWIG_2 (int capacity)
SWIGINTERN
indri::api::ScoredExtentResult std_vector_Sl_indri_api_ScoredExtentResult_Sg__getitemcopy (std::vector< indri::api::ScoredExtentResult > *self, int index)
SWIGINTERN std::vector
< indri::api::ScoredExtentResult >
::const_reference std_vector_Sl_indri_api_ScoredExtentResult_Sg__getitem (std::vector< indri::api::ScoredExtentResult > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__setitem (std::vector< indri::api::ScoredExtentResult > *self, int index, indri::api::ScoredExtentResult const &val)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__AddRange (std::vector< indri::api::ScoredExtentResult > *self, std::vector< indri::api::ScoredExtentResult > const &values)
SWIGINTERN std::vector
< indri::api::ScoredExtentResult > * std_vector_Sl_indri_api_ScoredExtentResult_Sg__GetRange (std::vector< indri::api::ScoredExtentResult > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__Insert (std::vector< indri::api::ScoredExtentResult > *self, int index, indri::api::ScoredExtentResult const &x)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__InsertRange (std::vector< indri::api::ScoredExtentResult > *self, int index, std::vector< indri::api::ScoredExtentResult > const &values)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__RemoveAt (std::vector< indri::api::ScoredExtentResult > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__RemoveRange (std::vector< indri::api::ScoredExtentResult > *self, int index, int count)
SWIGINTERN std::vector
< indri::api::ScoredExtentResult > * std_vector_Sl_indri_api_ScoredExtentResult_Sg__Repeat (indri::api::ScoredExtentResult const &value, int count)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__Reverse__SWIG_0 (std::vector< indri::api::ScoredExtentResult > *self)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__Reverse__SWIG_1 (std::vector< indri::api::ScoredExtentResult > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__SetRange (std::vector< indri::api::ScoredExtentResult > *self, int index, std::vector< indri::api::ScoredExtentResult > const &values)
SWIGINTERN std::vector
< indri::api::DocumentVector * > * new_std_vector_Sl_indri_api_DocumentVector_Sm__Sg___SWIG_2 (int capacity)
SWIGINTERN
indri::api::DocumentVector * std_vector_Sl_indri_api_DocumentVector_Sm__Sg__getitemcopy (std::vector< indri::api::DocumentVector * > *self, int index)
SWIGINTERN std::vector
< indri::api::DocumentVector * >
::const_reference std_vector_Sl_indri_api_DocumentVector_Sm__Sg__getitem (std::vector< indri::api::DocumentVector * > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__setitem (std::vector< indri::api::DocumentVector * > *self, int index, indri::api::DocumentVector *const &val)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__AddRange (std::vector< indri::api::DocumentVector * > *self, std::vector< indri::api::DocumentVector * > const &values)
SWIGINTERN std::vector
< indri::api::DocumentVector * > * std_vector_Sl_indri_api_DocumentVector_Sm__Sg__GetRange (std::vector< indri::api::DocumentVector * > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Insert (std::vector< indri::api::DocumentVector * > *self, int index, indri::api::DocumentVector *const &x)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__InsertRange (std::vector< indri::api::DocumentVector * > *self, int index, std::vector< indri::api::DocumentVector * > const &values)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__RemoveAt (std::vector< indri::api::DocumentVector * > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__RemoveRange (std::vector< indri::api::DocumentVector * > *self, int index, int count)
SWIGINTERN std::vector
< indri::api::DocumentVector * > * std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Repeat (indri::api::DocumentVector *const &value, int count)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Reverse__SWIG_0 (std::vector< indri::api::DocumentVector * > *self)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Reverse__SWIG_1 (std::vector< indri::api::DocumentVector * > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__SetRange (std::vector< indri::api::DocumentVector * > *self, int index, std::vector< indri::api::DocumentVector * > const &values)
SWIGINTERN bool std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Contains (std::vector< indri::api::DocumentVector * > *self, indri::api::DocumentVector *const &value)
SWIGINTERN int std_vector_Sl_indri_api_DocumentVector_Sm__Sg__IndexOf (std::vector< indri::api::DocumentVector * > *self, indri::api::DocumentVector *const &value)
SWIGINTERN int std_vector_Sl_indri_api_DocumentVector_Sm__Sg__LastIndexOf (std::vector< indri::api::DocumentVector * > *self, indri::api::DocumentVector *const &value)
SWIGINTERN bool std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Remove (std::vector< indri::api::DocumentVector * > *self, indri::api::DocumentVector *const &value)
SWIGINTERN std::vector
< indri::api::DocumentVector::Field > * new_std_vector_Sl_indri_api_DocumentVector_Field_Sg___SWIG_2 (int capacity)
SWIGINTERN
indri::api::DocumentVector::Field std_vector_Sl_indri_api_DocumentVector_Field_Sg__getitemcopy (std::vector< indri::api::DocumentVector::Field > *self, int index)
SWIGINTERN std::vector
< indri::api::DocumentVector::Field >
::const_reference std_vector_Sl_indri_api_DocumentVector_Field_Sg__getitem (std::vector< indri::api::DocumentVector::Field > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__setitem (std::vector< indri::api::DocumentVector::Field > *self, int index, indri::api::DocumentVector::Field const &val)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__AddRange (std::vector< indri::api::DocumentVector::Field > *self, std::vector< indri::api::DocumentVector::Field > const &values)
SWIGINTERN std::vector
< indri::api::DocumentVector::Field > * std_vector_Sl_indri_api_DocumentVector_Field_Sg__GetRange (std::vector< indri::api::DocumentVector::Field > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__Insert (std::vector< indri::api::DocumentVector::Field > *self, int index, indri::api::DocumentVector::Field const &x)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__InsertRange (std::vector< indri::api::DocumentVector::Field > *self, int index, std::vector< indri::api::DocumentVector::Field > const &values)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__RemoveAt (std::vector< indri::api::DocumentVector::Field > *self, int index)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__RemoveRange (std::vector< indri::api::DocumentVector::Field > *self, int index, int count)
SWIGINTERN std::vector
< indri::api::DocumentVector::Field > * std_vector_Sl_indri_api_DocumentVector_Field_Sg__Repeat (indri::api::DocumentVector::Field const &value, int count)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__Reverse__SWIG_0 (std::vector< indri::api::DocumentVector::Field > *self)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__Reverse__SWIG_1 (std::vector< indri::api::DocumentVector::Field > *self, int index, int count)
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__SetRange (std::vector< indri::api::DocumentVector::Field > *self, int index, std::vector< indri::api::DocumentVector::Field > const &values)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Add (void *jarg1, int jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_IntVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_IntVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_IntVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_IntVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_IntVector__SWIG_2 (int jarg1)
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_setitem (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_IntVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Insert (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_IntVector_Repeat (int jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_IntVector_Contains (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_IndexOf (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_LastIndexOf (void *jarg1, int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_IntVector_Remove (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_IntVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Add (void *jarg1, char *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_StringVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_StringVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_StringVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_StringVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_StringVector__SWIG_2 (int jarg1)
SWIGEXPORT char *SWIGSTDCALL CSharp_StringVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_StringVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_setitem (void *jarg1, int jarg2, char *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_StringVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Insert (void *jarg1, int jarg2, char *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_StringVector_Repeat (char *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_StringVector_Contains (void *jarg1, char *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_StringVector_IndexOf (void *jarg1, char *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_StringVector_LastIndexOf (void *jarg1, char *jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_StringVector_Remove (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_StringVector (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ConfMap__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ConfMap__SWIG_1 (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ConfMap_size (void *jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ConfMap_empty (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ConfMap_Clear (void *jarg1)
SWIGEXPORT char *SWIGSTDCALL CSharp_ConfMap_getitem (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ConfMap_setitem (void *jarg1, void *jarg2, char *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ConfMap_ContainsKey (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ConfMap_Add (void *jarg1, void *jarg2, char *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ConfMap_Remove (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ConfMap_create_iterator_begin (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_ConfMap_get_next_key (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ConfMap (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ConflationPattern_tag_name_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_ConflationPattern_tag_name_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ConflationPattern_attribute_name_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_ConflationPattern_attribute_name_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ConflationPattern_value_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_ConflationPattern_value_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ConflationPattern ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ConflationPattern (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MResults__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MResults__SWIG_1 (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_MResults_size (void *jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MResults_empty (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MResults_Clear (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_MResults_getitem (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MResults_setitem (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MResults_ContainsKey (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MResults_Add (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MResults_Remove (void *jarg1, char *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_MResults_create_iterator_begin (void *jarg1)
SWIGEXPORT char *SWIGSTDCALL CSharp_MResults_get_next_key (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MResults (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_MetadataPairSTDVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_MetadataPairSTDVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MetadataPairSTDVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MetadataPairSTDVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MetadataPairSTDVector__SWIG_2 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairSTDVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairSTDVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairSTDVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairSTDVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MetadataPairSTDVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPair_key_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_MetadataPair_key_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPair_value_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_MetadataPair_value_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPair_valueLength_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_MetadataPair_valueLength_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MetadataPair ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MetadataPair (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ParsedDocumentVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ParsedDocumentVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ParsedDocumentVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ParsedDocumentVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ParsedDocumentVector__SWIG_2 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocumentVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocumentVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocumentVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocumentVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ParsedDocumentVector_Contains (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ParsedDocumentVector_IndexOf (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ParsedDocumentVector_LastIndexOf (void *jarg1, void *jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ParsedDocumentVector_Remove (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParsedDocumentVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_TermExtentVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_TermExtentVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_TermExtentVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_TermExtentVector__SWIG_1 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_TermExtentVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_TermExtentVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_TermExtentVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_TermExtentVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TermExtentVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_MetadataPairVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_MetadataPairVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MetadataPairVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_MetadataPairVector__SWIG_1 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_MetadataPairVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MetadataPairVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_TagExtentVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_TagExtentVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_TagExtentVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_TagExtentVector__SWIG_1 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_TagExtentVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_TagExtentVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_TagExtentVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_TagExtentVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TagExtentVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Add (void *jarg1, char *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_Char_pVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_Char_pVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_Char_pVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_Char_pVector__SWIG_1 (int jarg1)
SWIGEXPORT char *SWIGSTDCALL CSharp_Char_pVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Char_pVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_setitem (void *jarg1, int jarg2, char *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Char_pVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Insert (void *jarg1, int jarg2, char *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_Char_pVector_Repeat (char *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Char_pVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_AttributeValuePairVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_AttributeValuePairVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_AttributeValuePairVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_AttributeValuePairVector__SWIG_1 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_AttributeValuePairVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_AttributeValuePairVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_AttributeValuePairVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_AttributeValuePairVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_AttributeValuePairVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtent_begin_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_TermExtent_begin_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtent_end_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_TermExtent_end_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_TermExtent ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TermExtent (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_name_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_TagExtent_name_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_begin_set (void *jarg1, unsigned int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_TagExtent_begin_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_end_set (void *jarg1, unsigned int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_TagExtent_end_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_number_set (void *jarg1, long long jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_TagExtent_number_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_parent_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_TagExtent_parent_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_attributes_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_TagExtent_attributes_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_TagExtent ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TagExtent (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_attribute_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_AttributeValuePair_attribute_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_value_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_AttributeValuePair_value_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_begin_set (void *jarg1, unsigned int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AttributeValuePair_begin_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_end_set (void *jarg1, unsigned int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AttributeValuePair_end_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_AttributeValuePair ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_AttributeValuePair (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_text_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_ParsedDocument_text_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_textLength_set (void *jarg1, unsigned long jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ParsedDocument_textLength_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_content_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_ParsedDocument_content_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_contentLength_set (void *jarg1, unsigned long jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ParsedDocument_contentLength_get (void *jarg1)
SWIGEXPORT char *SWIGSTDCALL CSharp_ParsedDocument_getContent (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_metadata_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocument_metadata_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_terms_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocument_terms_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_positions_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ParsedDocument_positions_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ParsedDocument ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParsedDocument (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_QueryAnnotationNodeVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_QueryAnnotationNodeVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_QueryAnnotationNodeVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_QueryAnnotationNodeVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_QueryAnnotationNodeVector__SWIG_2 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotationNodeVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotationNodeVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotationNodeVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Contains (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_IndexOf (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_LastIndexOf (void *jarg1, void *jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Remove (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryAnnotationNodeVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_name_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_QueryAnnotationNode_name_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_type_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_QueryAnnotationNode_type_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_queryText_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_QueryAnnotationNode_queryText_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_children_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotationNode_children_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_QueryAnnotationNode ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryAnnotationNode (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotation_getQueryTree (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotation_getAnnotations (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryAnnotation_getResults (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_QueryAnnotation ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryAnnotation (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ScoredExtentResultVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_ScoredExtentResultVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ScoredExtentResultVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ScoredExtentResultVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ScoredExtentResultVector__SWIG_2 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_ScoredExtentResultVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ScoredExtentResultVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_ScoredExtentResultVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_ScoredExtentResultVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ScoredExtentResultVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_score_set (void *jarg1, double jarg2)
SWIGEXPORT double SWIGSTDCALL CSharp_ScoredExtentResult_score_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_document_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_document_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_begin_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_begin_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_end_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_end_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_number_set (void *jarg1, long long jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_ScoredExtentResult_number_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_ordinal_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_ordinal_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_parentOrdinal_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_parentOrdinal_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_ScoredExtentResult ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ScoredExtentResult (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_Parameters ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Parameters (void *jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Parameters_get__SWIG_0 (void *jarg1, char *jarg2, unsigned int jarg3)
SWIGEXPORT int SWIGSTDCALL CSharp_Parameters_get__SWIG_1 (void *jarg1, char *jarg2, int jarg3)
SWIGEXPORT double SWIGSTDCALL CSharp_Parameters_get__SWIG_2 (void *jarg1, char *jarg2, double jarg3)
SWIGEXPORT long long SWIGSTDCALL CSharp_Parameters_get__SWIG_3 (void *jarg1, char *jarg2, long long jarg3)
SWIGEXPORT char *SWIGSTDCALL CSharp_Parameters_get__SWIG_4 (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_remove (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_0 (void *jarg1, char *jarg2, unsigned int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_1 (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_2 (void *jarg1, char *jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_3 (void *jarg1, char *jarg2, long long jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_4 (void *jarg1, char *jarg2, double jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_5 (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_clear (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_Parameters_size (void *jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Parameters_exists__SWIG_0 (void *jarg1, int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Parameters_exists__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_load (void *jarg1, char *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Parameters_instance ()
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_DocumentVectorVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_DocumentVectorVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_DocumentVectorVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_DocumentVectorVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_DocumentVectorVector__SWIG_2 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVectorVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVectorVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVectorVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVectorVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DocumentVectorVector_Contains (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_DocumentVectorVector_IndexOf (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_DocumentVectorVector_LastIndexOf (void *jarg1, void *jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DocumentVectorVector_Remove (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_DocumentVectorVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Clear (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Add (void *jarg1, void *jarg2)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_FieldVector_size (void *jarg1)
SWIGEXPORT unsigned long
SWIGSTDCALL CSharp_FieldVector_capacity (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_reserve (void *jarg1, unsigned long jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_FieldVector__SWIG_0 ()
SWIGEXPORT void *SWIGSTDCALL CSharp_new_FieldVector__SWIG_1 (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_FieldVector__SWIG_2 (int jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_FieldVector_getitemcopy (void *jarg1, int jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_FieldVector_getitem (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_setitem (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_AddRange (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_FieldVector_GetRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Insert (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_InsertRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_RemoveAt (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_RemoveRange (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_FieldVector_Repeat (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Reverse__SWIG_0 (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Reverse__SWIG_1 (void *jarg1, int jarg2, int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_SetRange (void *jarg1, int jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_FieldVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_name_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Field_name_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_begin_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_begin_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_end_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_end_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_number_set (void *jarg1, long long jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_Field_number_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_ordinal_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_ordinal_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_parentOrdinal_set (void *jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_parentOrdinal_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_Field ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Field (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVector_stems (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVector_positions (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_DocumentVector_fields (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_DocumentVector ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_DocumentVector (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_name_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_name_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_parser_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_parser_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_tokenizer_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_tokenizer_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_iterator_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_iterator_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_startDocTag_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_startDocTag_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_endDocTag_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_endDocTag_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_endMetadataTag_set (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_Specification_endMetadataTag_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_include_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Specification_include_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_exclude_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Specification_exclude_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_index_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Specification_index_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_metadata_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Specification_metadata_get (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_conflations_set (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_Specification_conflations_get (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_Specification ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Specification (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_QueryEnvironment ()
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_addServer (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_addIndex (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_removeServer (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_removeIndex (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_close (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setMemory (void *jarg1, long long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setScoringRules (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setStopwords (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_runQuery__SWIG_0 (void *jarg1, char *jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_runQuery__SWIG_1 (void *jarg1, char *jarg2, void *jarg3, int jarg4)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_0 (void *jarg1, char *jarg2, int jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_1 (void *jarg1, char *jarg2, void *jarg3, int jarg4)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documents__SWIG_0 (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documents__SWIG_1 (void *jarg1, void *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documentMetadata__SWIG_0 (void *jarg1, void *jarg2, char *jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documentMetadata__SWIG_1 (void *jarg1, void *jarg2, char *jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documentIDsFromMetadata (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documentsFromMetadata (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termCount__SWIG_0 (void *jarg1)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termCount__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termFieldCount (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_fieldList (void *jarg1)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_documentCount__SWIG_0 (void *jarg1)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_documentCount__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_documentVectors (void *jarg1, void *jarg2)
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_expressionCount__SWIG_0 (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_expressionCount__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_documentExpressionCount__SWIG_0 (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_documentExpressionCount__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_expressionList__SWIG_0 (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryEnvironment_expressionList__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_QueryEnvironment_documentLength (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setFormulationParameters (void *jarg1, void *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_QueryEnvironment_reformulateQuery (void *jarg1, char *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_QueryEnvironment_stemTerm (void *jarg1, char *jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termCountUnique (void *jarg1)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_stemCount (void *jarg1, char *jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_stemFieldCount (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_documentStemCount (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryEnvironment (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryExpander (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryExpander_runExpandedQuery__SWIG_0 (void *jarg1, char *jarg2, int jarg3, unsigned int jarg4)
SWIGEXPORT void *SWIGSTDCALL CSharp_QueryExpander_runExpandedQuery__SWIG_1 (void *jarg1, char *jarg2, int jarg3)
SWIGEXPORT char *SWIGSTDCALL CSharp_QueryExpander_expand (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_RMExpander (void *jarg1, void *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_RMExpander_expand (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_RMExpander (void *jarg1)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_PonteExpander (void *jarg1, void *jarg2)
SWIGEXPORT char *SWIGSTDCALL CSharp_PonteExpander_expand (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_PonteExpander (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_IndexStatus (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexStatus_status (void *jarg1, int jarg2, char *jarg3, char *jarg4, int jarg5, int jarg6)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_IndexStatus ()
SWIGEXPORT void SWIGSTDCALL CSharp_IndexStatus_director_connect (void *objarg, SwigDirector_IndexStatus::SWIG_Callback0_t callback0)
SWIGEXPORT void *SWIGSTDCALL CSharp_new_IndexEnvironment ()
SWIGEXPORT void SWIGSTDCALL CSharp_delete_IndexEnvironment (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setDocumentRoot (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setAnchorTextPath (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setOffsetMetadataPath (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setOffsetAnnotationsPath (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFileClass__SWIG_0 (void *jarg1, char *jarg2, char *jarg3, char *jarg4, char *jarg5, char *jarg6, char *jarg7, char *jarg8, void *jarg9, void *jarg10, void *jarg11, void *jarg12, void *jarg13)
SWIGEXPORT void *SWIGSTDCALL CSharp_IndexEnvironment_getFileClassSpec (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFileClass__SWIG_1 (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_deleteDocument (void *jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setIndexedFields (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setNumericField__SWIG_0 (void *jarg1, char *jarg2, unsigned int jarg3, char *jarg4)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setNumericField__SWIG_1 (void *jarg1, char *jarg2, unsigned int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setOrdinalField (void *jarg1, char *jarg2, unsigned int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setParentalField (void *jarg1, char *jarg2, unsigned int jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setMetadataIndexedFields (void *jarg1, void *jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setStopwords (void *jarg1, void *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setStemmer (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setMemory (void *jarg1, long long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setNormalization (void *jarg1, unsigned int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setStoreDocs (void *jarg1, unsigned int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_create__SWIG_0 (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_create__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_open__SWIG_0 (void *jarg1, char *jarg2, void *jarg3)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_open__SWIG_1 (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_close (void *jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFile__SWIG_0 (void *jarg1, char *jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFile__SWIG_1 (void *jarg1, char *jarg2, char *jarg3)
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_addString (void *jarg1, char *jarg2, char *jarg3, void *jarg4)
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_addParsedDocument (void *jarg1, void *jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_documentsIndexed (void *jarg1)
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_documentsSeen (void *jarg1)
SWIGEXPORT
indri::query::QueryExpander
*SWIGSTDCALL CSharp_RMExpander_SWIGUpcast (indri::query::RMExpander *jarg1)
SWIGEXPORT
indri::query::QueryExpander
*SWIGSTDCALL CSharp_PonteExpander_SWIGUpcast (indri::query::PonteExpander *jarg1)
Variables
static SWIG_CSharpException_t SWIG_csharp_exceptions []
static
SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument []
static
SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL
Define Documentation
#define SWIG_AttributeError -11
#define SWIG_contract_assert (nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else
#define SWIG_DIRECTORS
#define SWIG_DivisionByZero -6
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_IndexError -4
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_IOError -2
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_MemoryError -12
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_NullReferenceError -13
#define SWIG_OverflowError -7
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_RuntimeError -3
Referenced by Java_lemurproject_indri_indriJNI_delete_1IndexEnvironment(), Java_lemurproject_indri_indriJNI_delete_1IndexStatus(), Java_lemurproject_indri_indriJNI_delete_1PonteExpander(), Java_lemurproject_indri_indriJNI_delete_1QueryAnnotation(), Java_lemurproject_indri_indriJNI_delete_1QueryEnvironment(), Java_lemurproject_indri_indriJNI_delete_1QueryExpander(), Java_lemurproject_indri_indriJNI_delete_1RMExpander(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1close(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1deleteDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsIndexed(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsSeen(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setAnchorTextPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setDocumentRoot(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setIndexedFields(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMemory(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMetadataIndexedFields(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNormalization(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetAnnotationsPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetMetadataPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOrdinalField(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setParentalField(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStemmer(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStopwords(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStoreDocs(), Java_lemurproject_indri_indriJNI_IndexStatus_1status(), Java_lemurproject_indri_indriJNI_new_1IndexEnvironment(), Java_lemurproject_indri_indriJNI_new_1IndexStatus(), Java_lemurproject_indri_indriJNI_new_1PonteExpander(), Java_lemurproject_indri_indriJNI_new_1QueryAnnotation(), Java_lemurproject_indri_indriJNI_new_1QueryEnvironment(), Java_lemurproject_indri_indriJNI_new_1RMExpander(), Java_lemurproject_indri_indriJNI_PonteExpander_1expand(), Java_lemurproject_indri_indriJNI_QueryAnnotation_1getAnnotations(), Java_lemurproject_indri_indriJNI_QueryAnnotation_1getQueryTree(), Java_lemurproject_indri_indriJNI_QueryAnnotation_1getResults(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1addIndex(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1addServer(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1close(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentIDsFromMetadata(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentLength(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentStemCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentVectors(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1fieldList(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1reformulateQuery(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeIndex(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeServer(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_12(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setFormulationParameters(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setMemory(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setScoringRules(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setStopwords(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemFieldCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemTerm(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCountUnique(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termFieldCount(), Java_lemurproject_indri_indriJNI_QueryExpander_1expand(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_RMExpander_1expand(), java_parameters_map(), SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_SyntaxError -8
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_SystemError -10
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_TypeError -5
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_UnknownError -1
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIG_ValueError -9
Referenced by SWIG_CSharpException(), and SWIG_JavaException().
#define SWIGCSHARP
#define SWIGEXPORT
#define SWIGINLINE
#define SWIGINTERN static SWIGUNUSED
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#define SWIGSTDCALL
#define SWIGTEMPLATEDISAMBIGUATOR
#define SWIGUNUSED
#define SWIGUNUSEDPARM (p) p SWIGUNUSED
Typedef Documentation
typedef void(SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *)
typedef void(SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *)
typedef char*(SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *)
Enumeration Type Documentation
enum SWIG_CSharpExceptionArgumentCodes
Enumerator:
SWIG_CSharpArgumentException
SWIG_CSharpArgumentNullException
SWIG_CSharpArgumentOutOfRangeException
enum SWIG_CSharpExceptionCodes
Enumerator:
SWIG_CSharpApplicationException
SWIG_CSharpArithmeticException
SWIG_CSharpDivideByZeroException
SWIG_CSharpIndexOutOfRangeException
SWIG_CSharpInvalidCastException
SWIG_CSharpInvalidOperationException
SWIG_CSharpIOException
SWIG_CSharpNullReferenceException
SWIG_CSharpOutOfMemoryException
SWIG_CSharpOverflowException
SWIG_CSharpSystemException
Function Documentation
SWIGEXPORT char* SWIGSTDCALL CSharp_AttributeValuePair_attribute_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_attribute_set (void * jarg1, char * jarg2)
References indri::parse::AttributeValuePair::attribute.
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AttributeValuePair_begin_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_begin_set (void * jarg1, unsigned int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_AttributeValuePair_end_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_end_set (void * jarg1, unsigned int jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_AttributeValuePair_value_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePair_value_set (void * jarg1, char * jarg2)
References indri::parse::AttributeValuePair::value.
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_AddRange (void * jarg1, void * jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_AttributeValuePairVector_capacity (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::capacity().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_AttributeValuePairVector_getitem (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_AttributeValuePairVector_getitemcopy (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_AttributeValuePairVector_GetRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Insert (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_RemoveAt (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_AttributeValuePairVector_Repeat (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Reverse__SWIG_0 (void * jarg1)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_setitem (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_AttributeValuePairVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_AttributeValuePairVector_size (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::size().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Add (void * jarg1, char * jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_AddRange (void * jarg1, void * jarg2)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Char_pVector_capacity (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::capacity().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Clear (void * jarg1)
SWIGEXPORT char* SWIGSTDCALL CSharp_Char_pVector_getitem (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__getitem(), SWIG_csharp_string_callback, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_Char_pVector_getitemcopy (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__getitemcopy(), SWIG_csharp_string_callback, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_Char_pVector_GetRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Insert (void * jarg1, int jarg2, char * jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__Insert(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_RemoveAt (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_Char_pVector_Repeat (char * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__Repeat(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Reverse__SWIG_0 (void * jarg1)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_setitem (void * jarg1, int jarg2, char * jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__setitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Char_pVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_char_Sm__Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Char_pVector_size (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::size().
SWIGEXPORT char* SWIGSTDCALL CSharp_ConflationPattern_attribute_name_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_ConflationPattern_attribute_name_set (void * jarg1, char * jarg2)
References indri::parse::ConflationPattern::attribute_name.
SWIGEXPORT char* SWIGSTDCALL CSharp_ConflationPattern_tag_name_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_ConflationPattern_tag_name_set (void * jarg1, char * jarg2)
References indri::parse::ConflationPattern::tag_name.
SWIGEXPORT char* SWIGSTDCALL CSharp_ConflationPattern_value_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_ConflationPattern_value_set (void * jarg1, char * jarg2)
References indri::parse::ConflationPattern::value.
SWIGEXPORT void SWIGSTDCALL CSharp_ConfMap_Add (void * jarg1, void * jarg2, char * jarg3)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__Add(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ConfMap_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ConfMap_ContainsKey (void * jarg1, void * jarg2)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__ContainsKey().
SWIGEXPORT void* SWIGSTDCALL CSharp_ConfMap_create_iterator_begin (void * jarg1)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__create_iterator_begin().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ConfMap_empty (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_ConfMap_get_next_key (void * jarg1, void * jarg2)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__get_next_key(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_ConfMap_getitem (void * jarg1, void * jarg2)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__getitem(), SWIG_csharp_string_callback, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ConfMap_Remove (void * jarg1, void * jarg2)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__Remove().
SWIGEXPORT void SWIGSTDCALL CSharp_ConfMap_setitem (void * jarg1, void * jarg2, char * jarg3)
References std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__setitem(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ConfMap_size (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_AttributeValuePair (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_AttributeValuePairVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Char_pVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ConflationPattern (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ConfMap (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_DocumentVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_DocumentVectorVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Field (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_FieldVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_IndexEnvironment (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_IndexStatus (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_IntVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MetadataPair (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MetadataPairSTDVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MetadataPairVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_MResults (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Parameters (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParsedDocument (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ParsedDocumentVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_PonteExpander (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryAnnotation (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryAnnotationNode (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryAnnotationNodeVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryEnvironment (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_QueryExpander (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_RMExpander (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ScoredExtentResult (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_ScoredExtentResultVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_Specification (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_StringVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TagExtent (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TagExtentVector (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TermExtent (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_delete_TermExtentVector (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVector_fields (void * jarg1)
References indri::api::DocumentVector::fields().
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVector_positions (void * jarg1)
References indri::api::DocumentVector::positions().
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVector_stems (void * jarg1)
References indri::api::DocumentVector::stems().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Add (void * jarg1, void * jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_DocumentVectorVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DocumentVectorVector_Contains (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Contains().
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVectorVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVectorVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVectorVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_DocumentVectorVector_IndexOf (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__IndexOf().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Insert (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Insert(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_DocumentVectorVector_LastIndexOf (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__LastIndexOf().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_DocumentVectorVector_Remove (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Remove().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_DocumentVectorVector_Repeat (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Repeat(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_setitem (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__setitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_DocumentVectorVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Sm__Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_DocumentVectorVector_size (void * jarg1)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_begin_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_begin_set (void * jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_end_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_end_set (void * jarg1, int jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_Field_name_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Field_name_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_Field_number_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_number_set (void * jarg1, long long jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_ordinal_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_ordinal_set (void * jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_Field_parentOrdinal_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Field_parentOrdinal_set (void * jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_FieldVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_FieldVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_FieldVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_FieldVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Insert (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_FieldVector_Repeat (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_setitem (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_FieldVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_DocumentVector_Field_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_FieldVector_size (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFile__SWIG_0 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFile__SWIG_1 (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFileClass__SWIG_0 (void * jarg1, char * jarg2, char * jarg3, char * jarg4, char * jarg5, char * jarg6, char * jarg7, char * jarg8, void * jarg9, void * jarg10, void * jarg11, void * jarg12, void * jarg13)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_addFileClass__SWIG_1 (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_addParsedDocument (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_addString (void * jarg1, char * jarg2, char * jarg3, void * jarg4)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_close (void * jarg1)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_create__SWIG_0 (void * jarg1, char * jarg2, void * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_create__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_deleteDocument (void * jarg1, int jarg2)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_documentsIndexed (void * jarg1)
References indri::api::IndexEnvironment::documentsIndexed(), SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT int SWIGSTDCALL CSharp_IndexEnvironment_documentsSeen (void * jarg1)
References indri::api::IndexEnvironment::documentsSeen(), SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void* SWIGSTDCALL CSharp_IndexEnvironment_getFileClassSpec (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_open__SWIG_0 (void * jarg1, char * jarg2, void * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_open__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setAnchorTextPath (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setDocumentRoot (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setIndexedFields (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setMemory (void * jarg1, long long jarg2)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setMetadataIndexedFields (void * jarg1, void * jarg2, void * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setNormalization (void * jarg1, unsigned int jarg2)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setNumericField__SWIG_0 (void * jarg1, char * jarg2, unsigned int jarg3, char * jarg4)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setNumericField__SWIG_1 (void * jarg1, char * jarg2, unsigned int jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setOffsetAnnotationsPath (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setOffsetMetadataPath (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setOrdinalField (void * jarg1, char * jarg2, unsigned int jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setParentalField (void * jarg1, char * jarg2, unsigned int jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setStemmer (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setStopwords (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexEnvironment_setStoreDocs (void * jarg1, unsigned int jarg2)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexStatus_director_connect (void * objarg, SwigDirector_IndexStatus::SWIG_Callback0_t callback0)
References SwigDirector_IndexStatus::swig_connect_director().
SWIGEXPORT void SWIGSTDCALL CSharp_IndexStatus_status (void * jarg1, int jarg2, char * jarg3, char * jarg4, int jarg5, int jarg6)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Add (void * jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_int_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_IntVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_IntVector_Contains (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__Contains().
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_IntVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_int_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_IndexOf (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__IndexOf().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Insert (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_int_Sg__Insert(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_int_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_IntVector_LastIndexOf (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__LastIndexOf().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_IntVector_Remove (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__Remove().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_int_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_int_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_IntVector_Repeat (int jarg1, int jarg2)
References std_vector_Sl_int_Sg__Repeat(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_int_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_int_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_setitem (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_int_Sg__setitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_IntVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_int_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_IntVector_size (void * jarg1)
SWIGEXPORT char* SWIGSTDCALL CSharp_MetadataPair_key_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPair_key_set (void * jarg1, char * jarg2)
References indri::parse::MetadataPair::key.
SWIGEXPORT char* SWIGSTDCALL CSharp_MetadataPair_value_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPair_value_set (void * jarg1, char * jarg2)
References indri::parse::MetadataPair::value.
SWIGEXPORT int SWIGSTDCALL CSharp_MetadataPair_valueLength_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPair_valueLength_set (void * jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_indri_parse_MetadataPair_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MetadataPairSTDVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairSTDVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_indri_parse_MetadataPair_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairSTDVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_indri_parse_MetadataPair_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairSTDVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Insert (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_indri_parse_MetadataPair_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairSTDVector_Repeat (void * jarg1, int jarg2)
References std_vector_Sl_indri_parse_MetadataPair_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_setitem (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairSTDVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_parse_MetadataPair_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MetadataPairSTDVector_size (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_AddRange (void * jarg1, void * jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MetadataPairVector_capacity (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::capacity().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairVector_getitem (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairVector_getitemcopy (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairVector_GetRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Insert (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_RemoveAt (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MetadataPairVector_Repeat (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Reverse__SWIG_0 (void * jarg1)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_setitem (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MetadataPairVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MetadataPairVector_size (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::size().
SWIGEXPORT void SWIGSTDCALL CSharp_MResults_Add (void * jarg1, char * jarg2, void * jarg3)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__Add(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MResults_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MResults_ContainsKey (void * jarg1, char * jarg2)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__ContainsKey(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MResults_create_iterator_begin (void * jarg1)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__create_iterator_begin().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MResults_empty (void * jarg1)
SWIGEXPORT char* SWIGSTDCALL CSharp_MResults_get_next_key (void * jarg1, void * jarg2)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__get_next_key(), SWIG_csharp_string_callback, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_MResults_getitem (void * jarg1, char * jarg2)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__getitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MResults_Remove (void * jarg1, char * jarg2)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__Remove(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_MResults_setitem (void * jarg1, char * jarg2, void * jarg3)
References std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__setitem(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MResults_size (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_new_AttributeValuePair ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_AttributeValuePairVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_AttributeValuePairVector__SWIG_1 (int jarg1)
References new_indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg___SWIG_1(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_Char_pVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_Char_pVector__SWIG_1 (int jarg1)
References new_indri_utility_greedy_vector_Sl_char_Sm__Sg___SWIG_1(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ConflationPattern ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ConfMap__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ConfMap__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_DocumentVector ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_DocumentVectorVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_DocumentVectorVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_DocumentVectorVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_indri_api_DocumentVector_Sm__Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_Field ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_FieldVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_FieldVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_FieldVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_indri_api_DocumentVector_Field_Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_IndexEnvironment ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_IndexStatus ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_IntVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_IntVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_IntVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_int_Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MetadataPair ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MetadataPairSTDVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MetadataPairSTDVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MetadataPairSTDVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MetadataPairVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MetadataPairVector__SWIG_1 (int jarg1)
References new_indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_1(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MResults__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_MResults__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_Parameters ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ParsedDocument ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ParsedDocumentVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ParsedDocumentVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ParsedDocumentVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_indri_api_ParsedDocument_Sm__Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_PonteExpander (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_QueryAnnotation ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_QueryAnnotationNode ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_QueryAnnotationNodeVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_QueryAnnotationNodeVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_QueryAnnotationNodeVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_QueryEnvironment ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_RMExpander (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ScoredExtentResult ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ScoredExtentResultVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ScoredExtentResultVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_ScoredExtentResultVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_indri_api_ScoredExtentResult_Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_Specification ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_StringVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_StringVector__SWIG_1 (void * jarg1)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_StringVector__SWIG_2 (int jarg1)
References new_std_vector_Sl_std_string_Sg___SWIG_2(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_TagExtent ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_TagExtentVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_TagExtentVector__SWIG_1 (int jarg1)
References new_indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg___SWIG_1(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_new_TermExtent ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_TermExtentVector__SWIG_0 ()
SWIGEXPORT void* SWIGSTDCALL CSharp_new_TermExtentVector__SWIG_1 (int jarg1)
References new_indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg___SWIG_1(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Parameters_exists__SWIG_0 (void * jarg1, int jarg2)
References indri::api::Parameters::exists().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Parameters_exists__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_Parameters_get__SWIG_0 (void * jarg1, char * jarg2, unsigned int jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_Parameters_get__SWIG_1 (void * jarg1, char * jarg2, int jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT double SWIGSTDCALL CSharp_Parameters_get__SWIG_2 (void * jarg1, char * jarg2, double jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_Parameters_get__SWIG_3 (void * jarg1, char * jarg2, long long jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_Parameters_get__SWIG_4 (void * jarg1, char * jarg2, char * jarg3)
References SWIG_csharp_string_callback, SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_Parameters_instance ()
References indri::api::Parameters::instance().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_load (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_remove (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_0 (void * jarg1, char * jarg2, unsigned int jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_1 (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_2 (void * jarg1, char * jarg2, int jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_3 (void * jarg1, char * jarg2, long long jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_4 (void * jarg1, char * jarg2, double jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_Parameters_set__SWIG_5 (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Parameters_size (void * jarg1)
SWIGEXPORT char* SWIGSTDCALL CSharp_ParsedDocument_content_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_content_set (void * jarg1, char * jarg2)
References indri::api::ParsedDocument::content.
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ParsedDocument_contentLength_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_contentLength_set (void * jarg1, unsigned long jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_ParsedDocument_getContent (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocument_metadata_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_metadata_set (void * jarg1, void * jarg2)
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocument_positions_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_positions_set (void * jarg1, void * jarg2)
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocument_terms_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_terms_set (void * jarg1, void * jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_ParsedDocument_text_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_text_set (void * jarg1, char * jarg2)
References indri::api::ParsedDocument::text.
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ParsedDocument_textLength_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocument_textLength_set (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Add (void * jarg1, void * jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ParsedDocumentVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ParsedDocumentVector_Contains (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Contains().
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocumentVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocumentVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocumentVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_ParsedDocumentVector_IndexOf (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__IndexOf().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Insert (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Insert(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_ParsedDocumentVector_LastIndexOf (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__LastIndexOf().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ParsedDocumentVector_Remove (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Remove().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_ParsedDocumentVector_Repeat (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Repeat(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_setitem (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__setitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ParsedDocumentVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ParsedDocumentVector_size (void * jarg1)
SWIGEXPORT char* SWIGSTDCALL CSharp_PonteExpander_expand (void * jarg1, char * jarg2, void * jarg3)
References SWIG_csharp_string_callback, SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT indri::query::QueryExpander* SWIGSTDCALL CSharp_PonteExpander_SWIGUpcast (indri::query::PonteExpander * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotation_getAnnotations (void * jarg1)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotation_getQueryTree (void * jarg1)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotation_getResults (void * jarg1)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotationNode_children_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_children_set (void * jarg1, void * jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_QueryAnnotationNode_name_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_name_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_QueryAnnotationNode_queryText_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_queryText_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_QueryAnnotationNode_type_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNode_type_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Add (void * jarg1, void * jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_QueryAnnotationNodeVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Contains (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Contains().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotationNodeVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotationNodeVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotationNodeVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_IndexOf (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__IndexOf().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Insert (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Insert(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_LastIndexOf (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__LastIndexOf().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Remove (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Remove().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Repeat (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Repeat(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_setitem (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__setitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryAnnotationNodeVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_QueryAnnotationNodeVector_size (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_addIndex (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_addServer (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_close (void * jarg1)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_documentCount__SWIG_0 (void * jarg1)
References indri::api::QueryEnvironment::documentCount(), SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_documentCount__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_documentExpressionCount__SWIG_0 (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_documentExpressionCount__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documentIDsFromMetadata (void * jarg1, char * jarg2, void * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_QueryEnvironment_documentLength (void * jarg1, int jarg2)
References indri::api::QueryEnvironment::documentLength(), SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documentMetadata__SWIG_0 (void * jarg1, void * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documentMetadata__SWIG_1 (void * jarg1, void * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documents__SWIG_0 (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documents__SWIG_1 (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documentsFromMetadata (void * jarg1, char * jarg2, void * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_documentStemCount (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_documentVectors (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_expressionCount__SWIG_0 (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT double SWIGSTDCALL CSharp_QueryEnvironment_expressionCount__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_expressionList__SWIG_0 (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_expressionList__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_fieldList (void * jarg1)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT char* SWIGSTDCALL CSharp_QueryEnvironment_reformulateQuery (void * jarg1, char * jarg2)
References SWIG_csharp_string_callback, SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_removeIndex (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_removeServer (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_0 (void * jarg1, char * jarg2, int jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_1 (void * jarg1, char * jarg2, void * jarg3, int jarg4)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_runQuery__SWIG_0 (void * jarg1, char * jarg2, int jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryEnvironment_runQuery__SWIG_1 (void * jarg1, char * jarg2, void * jarg3, int jarg4)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setFormulationParameters (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setMemory (void * jarg1, long long jarg2)
References SWIG_CSharpApplicationException, and SWIG_CSharpSetPendingException().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setScoringRules (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_QueryEnvironment_setStopwords (void * jarg1, void * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_stemCount (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_stemFieldCount (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_QueryEnvironment_stemTerm (void * jarg1, char * jarg2)
References SWIG_csharp_string_callback, SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termCount__SWIG_0 (void * jarg1)
References SWIG_CSharpApplicationException, SWIG_CSharpSetPendingException(), and indri::api::QueryEnvironment::termCount().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termCount__SWIG_1 (void * jarg1, char * jarg2)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termCountUnique (void * jarg1)
References indri::api::QueryEnvironment::termCountUnique().
SWIGEXPORT long long SWIGSTDCALL CSharp_QueryEnvironment_termFieldCount (void * jarg1, char * jarg2, char * jarg3)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentNullException, SWIG_CSharpSetPendingException(), and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_QueryExpander_expand (void * jarg1, char * jarg2, void * jarg3)
References SWIG_csharp_string_callback, SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryExpander_runExpandedQuery__SWIG_0 (void * jarg1, char * jarg2, int jarg3, unsigned int jarg4)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_QueryExpander_runExpandedQuery__SWIG_1 (void * jarg1, char * jarg2, int jarg3)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_RMExpander_expand (void * jarg1, char * jarg2, void * jarg3)
References SWIG_csharp_string_callback, SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT indri::query::QueryExpander* SWIGSTDCALL CSharp_RMExpander_SWIGUpcast (indri::query::RMExpander * jarg1)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_begin_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_begin_set (void * jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_document_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_document_set (void * jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_end_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_end_set (void * jarg1, int jarg2)
SWIGEXPORT long long SWIGSTDCALL CSharp_ScoredExtentResult_number_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_number_set (void * jarg1, long long jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_ordinal_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_ordinal_set (void * jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_ScoredExtentResult_parentOrdinal_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_parentOrdinal_set (void * jarg1, int jarg2)
SWIGEXPORT double SWIGSTDCALL CSharp_ScoredExtentResult_score_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResult_score_set (void * jarg1, double jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ScoredExtentResultVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_ScoredExtentResultVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_ScoredExtentResultVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_ScoredExtentResultVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Insert (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_ScoredExtentResultVector_Repeat (void * jarg1, int jarg2)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_setitem (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_ScoredExtentResultVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_indri_api_ScoredExtentResult_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ScoredExtentResultVector_size (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_Specification_conflations_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_conflations_set (void * jarg1, void * jarg2)
References indri::parse::conflations.
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_endDocTag_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_endDocTag_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_endMetadataTag_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_endMetadataTag_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_Specification_exclude_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_exclude_set (void * jarg1, void * jarg2)
SWIGEXPORT void* SWIGSTDCALL CSharp_Specification_include_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_include_set (void * jarg1, void * jarg2)
SWIGEXPORT void* SWIGSTDCALL CSharp_Specification_index_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_index_set (void * jarg1, void * jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_iterator_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_iterator_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_Specification_metadata_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_metadata_set (void * jarg1, void * jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_name_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_name_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_parser_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_parser_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_startDocTag_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_startDocTag_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_Specification_tokenizer_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_Specification_tokenizer_set (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Add (void * jarg1, char * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_AddRange (void * jarg1, void * jarg2)
References std_vector_Sl_std_string_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_StringVector_capacity (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Clear (void * jarg1)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_StringVector_Contains (void * jarg1, char * jarg2)
References std_vector_Sl_std_string_Sg__Contains(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_StringVector_getitem (void * jarg1, int jarg2)
References std_vector_Sl_std_string_Sg__getitem(), SWIG_csharp_string_callback, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT char* SWIGSTDCALL CSharp_StringVector_getitemcopy (void * jarg1, int jarg2)
References std_vector_Sl_std_string_Sg__getitemcopy(), SWIG_csharp_string_callback, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_StringVector_GetRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_std_string_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_StringVector_IndexOf (void * jarg1, char * jarg2)
References std_vector_Sl_std_string_Sg__IndexOf(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Insert (void * jarg1, int jarg2, char * jarg3)
References std_vector_Sl_std_string_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_std_string_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT int SWIGSTDCALL CSharp_StringVector_LastIndexOf (void * jarg1, char * jarg2)
References std_vector_Sl_std_string_Sg__LastIndexOf(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_StringVector_Remove (void * jarg1, char * jarg2)
References std_vector_Sl_std_string_Sg__Remove(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_RemoveAt (void * jarg1, int jarg2)
References std_vector_Sl_std_string_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_std_string_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_StringVector_Repeat (char * jarg1, int jarg2)
References std_vector_Sl_std_string_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Reverse__SWIG_0 (void * jarg1)
References std_vector_Sl_std_string_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References std_vector_Sl_std_string_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_setitem (void * jarg1, int jarg2, char * jarg3)
References std_vector_Sl_std_string_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_StringVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References std_vector_Sl_std_string_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_StringVector_size (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_TagExtent_attributes_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_attributes_set (void * jarg1, void * jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_TagExtent_begin_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_begin_set (void * jarg1, unsigned int jarg2)
SWIGEXPORT unsigned int SWIGSTDCALL CSharp_TagExtent_end_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_end_set (void * jarg1, unsigned int jarg2)
SWIGEXPORT char* SWIGSTDCALL CSharp_TagExtent_name_get (void * jarg1)
References SWIG_csharp_string_callback.
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_name_set (void * jarg1, char * jarg2)
References indri::parse::TagExtent::name.
SWIGEXPORT long long SWIGSTDCALL CSharp_TagExtent_number_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_number_set (void * jarg1, long long jarg2)
SWIGEXPORT void* SWIGSTDCALL CSharp_TagExtent_parent_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtent_parent_set (void * jarg1, void * jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_AddRange (void * jarg1, void * jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_TagExtentVector_capacity (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::capacity().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_TagExtentVector_getitem (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_TagExtentVector_getitemcopy (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_TagExtentVector_GetRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Insert (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_RemoveAt (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_TagExtentVector_Repeat (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Reverse__SWIG_0 (void * jarg1)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_setitem (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TagExtentVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_TagExtentVector_size (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::size().
SWIGEXPORT int SWIGSTDCALL CSharp_TermExtent_begin_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtent_begin_set (void * jarg1, int jarg2)
SWIGEXPORT int SWIGSTDCALL CSharp_TermExtent_end_get (void * jarg1)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtent_end_set (void * jarg1, int jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Add (void * jarg1, void * jarg2)
References SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_AddRange (void * jarg1, void * jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__AddRange(), SWIG_CSharpArgumentNullException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_TermExtentVector_capacity (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::capacity().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Clear (void * jarg1)
SWIGEXPORT void* SWIGSTDCALL CSharp_TermExtentVector_getitem (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__getitem(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_TermExtentVector_getitemcopy (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__getitemcopy(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_TermExtentVector_GetRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__GetRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Insert (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Insert(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_InsertRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__InsertRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_RemoveAt (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__RemoveAt(), SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_RemoveRange (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__RemoveRange(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void* SWIGSTDCALL CSharp_TermExtentVector_Repeat (void * jarg1, int jarg2)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Repeat(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_reserve (void * jarg1, unsigned long jarg2)
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Reverse__SWIG_0 (void * jarg1)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Reverse__SWIG_0().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_Reverse__SWIG_1 (void * jarg1, int jarg2, int jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Reverse__SWIG_1(), SWIG_CSharpArgumentException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_setitem (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__setitem(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT void SWIGSTDCALL CSharp_TermExtentVector_SetRange (void * jarg1, int jarg2, void * jarg3)
References indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__SetRange(), SWIG_CSharpArgumentNullException, SWIG_CSharpArgumentOutOfRangeException, and SWIG_CSharpSetPendingExceptionArgument().
SWIGEXPORT unsigned long SWIGSTDCALL CSharp_TermExtentVector_size (void * jarg1)
References indri::utility::greedy_vector< _Type, _Count >::size().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__AddRange (indri::utility::greedy_vector< char * > * self, indri::utility::greedy_vector< char * > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_Char_pVector_AddRange().
SWIGINTERN indri::utility::greedy_vector< char * >::const_reference indri_utility_greedy_vector_Sl_char_Sm__Sg__getitem (indri::utility::greedy_vector< char * > * self, int index)
Referenced by CSharp_Char_pVector_getitem().
SWIGINTERN char* indri_utility_greedy_vector_Sl_char_Sm__Sg__getitemcopy (indri::utility::greedy_vector< char * > * self, int index)
Referenced by CSharp_Char_pVector_getitemcopy().
SWIGINTERN indri::utility::greedy_vector< char * >* indri_utility_greedy_vector_Sl_char_Sm__Sg__GetRange (indri::utility::greedy_vector< char * > * self, int index, int count)
References indri::utility::greedy_vector< _Type, _Count >::assign().
Referenced by CSharp_Char_pVector_GetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__Insert (indri::utility::greedy_vector< char * > * self, int index, char const *& value)
Referenced by CSharp_Char_pVector_Insert().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__InsertRange (indri::utility::greedy_vector< char * > * self, int index, indri::utility::greedy_vector< char * > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_Char_pVector_InsertRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__RemoveAt (indri::utility::greedy_vector< char * > * self, int index)
Referenced by CSharp_Char_pVector_RemoveAt().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__RemoveRange (indri::utility::greedy_vector< char * > * self, int index, int count)
Referenced by CSharp_Char_pVector_RemoveRange().
SWIGINTERN indri::utility::greedy_vector< char * >* indri_utility_greedy_vector_Sl_char_Sm__Sg__Repeat (char const *& value, int count)
References indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by CSharp_Char_pVector_Repeat().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< char * > * self)
Referenced by CSharp_Char_pVector_Reverse__SWIG_0().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< char * > * self, int index, int count)
Referenced by CSharp_Char_pVector_Reverse__SWIG_1().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__setitem (indri::utility::greedy_vector< char * > * self, int index, char const *& value)
Referenced by CSharp_Char_pVector_setitem().
SWIGINTERN void indri_utility_greedy_vector_Sl_char_Sm__Sg__SetRange (indri::utility::greedy_vector< char * > * self, int index, indri::utility::greedy_vector< char * > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by CSharp_Char_pVector_SetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__AddRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, indri::utility::greedy_vector< indri::parse::AttributeValuePair > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_AttributeValuePairVector_AddRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::AttributeValuePair >::const_reference indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__getitem (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index)
Referenced by CSharp_AttributeValuePairVector_getitem().
SWIGINTERN indri::parse::AttributeValuePair indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index)
Referenced by CSharp_AttributeValuePairVector_getitemcopy().
SWIGINTERN indri::utility::greedy_vector< indri::parse::AttributeValuePair >* indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__GetRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, int count)
References indri::utility::greedy_vector< _Type, _Count >::assign().
Referenced by CSharp_AttributeValuePairVector_GetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Insert (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, indri::parse::AttributeValuePair const & value)
Referenced by CSharp_AttributeValuePairVector_Insert().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, indri::utility::greedy_vector< indri::parse::AttributeValuePair > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_AttributeValuePairVector_InsertRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index)
Referenced by CSharp_AttributeValuePairVector_RemoveAt().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, int count)
Referenced by CSharp_AttributeValuePairVector_RemoveRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::AttributeValuePair >* indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Repeat (indri::parse::AttributeValuePair const & value, int count)
References indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by CSharp_AttributeValuePairVector_Repeat().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self)
Referenced by CSharp_AttributeValuePairVector_Reverse__SWIG_0().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, int count)
Referenced by CSharp_AttributeValuePairVector_Reverse__SWIG_1().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__setitem (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, indri::parse::AttributeValuePair const & value)
Referenced by CSharp_AttributeValuePairVector_setitem().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg__SetRange (indri::utility::greedy_vector< indri::parse::AttributeValuePair > * self, int index, indri::utility::greedy_vector< indri::parse::AttributeValuePair > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by CSharp_AttributeValuePairVector_SetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__AddRange (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, indri::utility::greedy_vector< indri::parse::MetadataPair > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_MetadataPairVector_AddRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::MetadataPair >::const_reference indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__getitem (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index)
Referenced by CSharp_MetadataPairVector_getitem().
SWIGINTERN indri::parse::MetadataPair indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index)
Referenced by CSharp_MetadataPairVector_getitemcopy().
SWIGINTERN indri::utility::greedy_vector< indri::parse::MetadataPair >* indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__GetRange (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, int count)
References indri::utility::greedy_vector< _Type, _Count >::assign().
Referenced by CSharp_MetadataPairVector_GetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Insert (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, indri::parse::MetadataPair const & value)
Referenced by CSharp_MetadataPairVector_Insert().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, indri::utility::greedy_vector< indri::parse::MetadataPair > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_MetadataPairVector_InsertRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index)
Referenced by CSharp_MetadataPairVector_RemoveAt().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, int count)
Referenced by CSharp_MetadataPairVector_RemoveRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::MetadataPair >* indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Repeat (indri::parse::MetadataPair const & value, int count)
References indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by CSharp_MetadataPairVector_Repeat().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::MetadataPair > * self)
Referenced by CSharp_MetadataPairVector_Reverse__SWIG_0().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, int count)
Referenced by CSharp_MetadataPairVector_Reverse__SWIG_1().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__setitem (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, indri::parse::MetadataPair const & value)
Referenced by CSharp_MetadataPairVector_setitem().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg__SetRange (indri::utility::greedy_vector< indri::parse::MetadataPair > * self, int index, indri::utility::greedy_vector< indri::parse::MetadataPair > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by CSharp_MetadataPairVector_SetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__AddRange (indri::utility::greedy_vector< indri::parse::TagExtent > * self, indri::utility::greedy_vector< indri::parse::TagExtent > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_TagExtentVector_AddRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TagExtent >::const_reference indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__getitem (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index)
Referenced by CSharp_TagExtentVector_getitem().
SWIGINTERN indri::parse::TagExtent indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index)
Referenced by CSharp_TagExtentVector_getitemcopy().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TagExtent >* indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__GetRange (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, int count)
References indri::utility::greedy_vector< _Type, _Count >::assign().
Referenced by CSharp_TagExtentVector_GetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Insert (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, indri::parse::TagExtent const & value)
Referenced by CSharp_TagExtentVector_Insert().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, indri::utility::greedy_vector< indri::parse::TagExtent > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_TagExtentVector_InsertRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index)
Referenced by CSharp_TagExtentVector_RemoveAt().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, int count)
Referenced by CSharp_TagExtentVector_RemoveRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TagExtent >* indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Repeat (indri::parse::TagExtent const & value, int count)
References indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by CSharp_TagExtentVector_Repeat().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::TagExtent > * self)
Referenced by CSharp_TagExtentVector_Reverse__SWIG_0().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, int count)
Referenced by CSharp_TagExtentVector_Reverse__SWIG_1().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__setitem (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, indri::parse::TagExtent const & value)
Referenced by CSharp_TagExtentVector_setitem().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg__SetRange (indri::utility::greedy_vector< indri::parse::TagExtent > * self, int index, indri::utility::greedy_vector< indri::parse::TagExtent > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by CSharp_TagExtentVector_SetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__AddRange (indri::utility::greedy_vector< indri::parse::TermExtent > * self, indri::utility::greedy_vector< indri::parse::TermExtent > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_TermExtentVector_AddRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TermExtent >::const_reference indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__getitem (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index)
Referenced by CSharp_TermExtentVector_getitem().
SWIGINTERN indri::parse::TermExtent indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__getitemcopy (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index)
Referenced by CSharp_TermExtentVector_getitemcopy().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TermExtent >* indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__GetRange (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, int count)
References indri::utility::greedy_vector< _Type, _Count >::assign().
Referenced by CSharp_TermExtentVector_GetRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Insert (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, indri::parse::TermExtent const & value)
Referenced by CSharp_TermExtentVector_Insert().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__InsertRange (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, indri::utility::greedy_vector< indri::parse::TermExtent > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by CSharp_TermExtentVector_InsertRange().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__RemoveAt (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index)
Referenced by CSharp_TermExtentVector_RemoveAt().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__RemoveRange (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, int count)
Referenced by CSharp_TermExtentVector_RemoveRange().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TermExtent >* indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Repeat (indri::parse::TermExtent const & value, int count)
References indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by CSharp_TermExtentVector_Repeat().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Reverse__SWIG_0 (indri::utility::greedy_vector< indri::parse::TermExtent > * self)
Referenced by CSharp_TermExtentVector_Reverse__SWIG_0().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__Reverse__SWIG_1 (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, int count)
Referenced by CSharp_TermExtentVector_Reverse__SWIG_1().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__setitem (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, indri::parse::TermExtent const & value)
Referenced by CSharp_TermExtentVector_setitem().
SWIGINTERN void indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg__SetRange (indri::utility::greedy_vector< indri::parse::TermExtent > * self, int index, indri::utility::greedy_vector< indri::parse::TermExtent > const & values)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by CSharp_TermExtentVector_SetRange().
SWIGINTERN indri::utility::greedy_vector< char * >* new_indri_utility_greedy_vector_Sl_char_Sm__Sg___SWIG_1 (int capacity)
References indri::utility::greedy_vector< _Type, _Count >::reserve().
Referenced by CSharp_new_Char_pVector__SWIG_1().
SWIGINTERN indri::utility::greedy_vector< indri::parse::AttributeValuePair >* new_indri_utility_greedy_vector_Sl_indri_parse_AttributeValuePair_Sg___SWIG_1 (int capacity)
References indri::utility::greedy_vector< _Type, _Count >::reserve().
Referenced by CSharp_new_AttributeValuePairVector__SWIG_1().
SWIGINTERN indri::utility::greedy_vector< indri::parse::MetadataPair >* new_indri_utility_greedy_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_1 (int capacity)
References indri::utility::greedy_vector< _Type, _Count >::reserve().
Referenced by CSharp_new_MetadataPairVector__SWIG_1().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TagExtent >* new_indri_utility_greedy_vector_Sl_indri_parse_TagExtent_Sg___SWIG_1 (int capacity)
References indri::utility::greedy_vector< _Type, _Count >::reserve().
Referenced by CSharp_new_TagExtentVector__SWIG_1().
SWIGINTERN indri::utility::greedy_vector< indri::parse::TermExtent >* new_indri_utility_greedy_vector_Sl_indri_parse_TermExtent_Sg___SWIG_1 (int capacity)
References indri::utility::greedy_vector< _Type, _Count >::reserve().
Referenced by CSharp_new_TermExtentVector__SWIG_1().
SWIGINTERN std::vector< indri::api::DocumentVector::Field >* new_std_vector_Sl_indri_api_DocumentVector_Field_Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_FieldVector__SWIG_2().
SWIGINTERN std::vector< indri::api::DocumentVector * >* new_std_vector_Sl_indri_api_DocumentVector_Sm__Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_DocumentVectorVector__SWIG_2().
SWIGINTERN std::vector< indri::api::ParsedDocument * >* new_std_vector_Sl_indri_api_ParsedDocument_Sm__Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_ParsedDocumentVector__SWIG_2().
SWIGINTERN std::vector< indri::api::QueryAnnotationNode * >* new_std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_QueryAnnotationNodeVector__SWIG_2().
SWIGINTERN std::vector< indri::api::ScoredExtentResult >* new_std_vector_Sl_indri_api_ScoredExtentResult_Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_ScoredExtentResultVector__SWIG_2().
SWIGINTERN std::vector< indri::parse::MetadataPair >* new_std_vector_Sl_indri_parse_MetadataPair_Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_MetadataPairSTDVector__SWIG_2().
SWIGINTERN std::vector< int >* new_std_vector_Sl_int_Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_IntVector__SWIG_2().
SWIGINTERN std::vector< std::string >* new_std_vector_Sl_std_string_Sg___SWIG_2 (int capacity)
Referenced by CSharp_new_StringVector__SWIG_2().
SWIGINTERN void std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__Add (std::map< indri::parse::ConflationPattern *, std::string > * self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const & key, std::map< indri::parse::ConflationPattern *, std::string >::mapped_type const & val)
Referenced by CSharp_ConfMap_Add().
SWIGINTERN bool std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__ContainsKey (std::map< indri::parse::ConflationPattern *, std::string > * self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const & key)
Referenced by CSharp_ConfMap_ContainsKey().
SWIGINTERN std::map< indri::parse::ConflationPattern *,std::string >::iterator* std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__create_iterator_begin (std::map< indri::parse::ConflationPattern *, std::string > * self)
Referenced by CSharp_ConfMap_create_iterator_begin().
SWIGINTERN std::map< indri::parse::ConflationPattern *,std::string >::key_type const& std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__get_next_key (std::map< indri::parse::ConflationPattern *, std::string > * self, std::map< indri::parse::ConflationPattern *, std::string >::iterator * swigiterator)
Referenced by CSharp_ConfMap_get_next_key().
SWIGINTERN std::map< indri::parse::ConflationPattern *,std::string >::mapped_type const& std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__getitem (std::map< indri::parse::ConflationPattern *, std::string > * self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const & key)
Referenced by CSharp_ConfMap_getitem().
SWIGINTERN bool std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__Remove (std::map< indri::parse::ConflationPattern *, std::string > * self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const & key)
Referenced by CSharp_ConfMap_Remove().
SWIGINTERN void std_map_Sl_indri_parse_ConflationPattern_Sm__Sc_std_string_Sg__setitem (std::map< indri::parse::ConflationPattern *, std::string > * self, std::map< indri::parse::ConflationPattern *, std::string >::key_type const & key, std::map< indri::parse::ConflationPattern *, std::string >::mapped_type const & x)
Referenced by CSharp_ConfMap_setitem().
SWIGINTERN void std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__Add (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const & key, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::mapped_type const & val)
Referenced by CSharp_MResults_Add().
SWIGINTERN bool std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__ContainsKey (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const & key)
Referenced by CSharp_MResults_ContainsKey().
SWIGINTERN std::map< std::string,std::vector< indri::api::ScoredExtentResult > >::iterator* std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__create_iterator_begin (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self)
Referenced by CSharp_MResults_create_iterator_begin().
SWIGINTERN std::map< std::string,std::vector< indri::api::ScoredExtentResult > >::key_type const& std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__get_next_key (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::iterator * swigiterator)
Referenced by CSharp_MResults_get_next_key().
SWIGINTERN std::map< std::string,std::vector< indri::api::ScoredExtentResult > >::mapped_type const& std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__getitem (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const & key)
Referenced by CSharp_MResults_getitem().
SWIGINTERN bool std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__Remove (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const & key)
Referenced by CSharp_MResults_Remove().
SWIGINTERN void std_map_Sl_std_string_Sc_std_vector_Sl_indri_api_ScoredExtentResult_Sg__Sg__setitem (std::map< std::string, std::vector< indri::api::ScoredExtentResult > > * self, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::key_type const & key, std::map< std::string, std::vector< indri::api::ScoredExtentResult > >::mapped_type const & x)
Referenced by CSharp_MResults_setitem().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__AddRange (std::vector< indri::api::DocumentVector::Field > * self, std::vector< indri::api::DocumentVector::Field > const & values)
Referenced by CSharp_FieldVector_AddRange().
SWIGINTERN std::vector< indri::api::DocumentVector::Field >::const_reference std_vector_Sl_indri_api_DocumentVector_Field_Sg__getitem (std::vector< indri::api::DocumentVector::Field > * self, int index)
Referenced by CSharp_FieldVector_getitem().
SWIGINTERN indri::api::DocumentVector::Field std_vector_Sl_indri_api_DocumentVector_Field_Sg__getitemcopy (std::vector< indri::api::DocumentVector::Field > * self, int index)
Referenced by CSharp_FieldVector_getitemcopy().
SWIGINTERN std::vector< indri::api::DocumentVector::Field >* std_vector_Sl_indri_api_DocumentVector_Field_Sg__GetRange (std::vector< indri::api::DocumentVector::Field > * self, int index, int count)
Referenced by CSharp_FieldVector_GetRange().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__Insert (std::vector< indri::api::DocumentVector::Field > * self, int index, indri::api::DocumentVector::Field const & x)
Referenced by CSharp_FieldVector_Insert().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__InsertRange (std::vector< indri::api::DocumentVector::Field > * self, int index, std::vector< indri::api::DocumentVector::Field > const & values)
Referenced by CSharp_FieldVector_InsertRange().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__RemoveAt (std::vector< indri::api::DocumentVector::Field > * self, int index)
Referenced by CSharp_FieldVector_RemoveAt().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__RemoveRange (std::vector< indri::api::DocumentVector::Field > * self, int index, int count)
Referenced by CSharp_FieldVector_RemoveRange().
SWIGINTERN std::vector< indri::api::DocumentVector::Field >* std_vector_Sl_indri_api_DocumentVector_Field_Sg__Repeat (indri::api::DocumentVector::Field const & value, int count)
Referenced by CSharp_FieldVector_Repeat().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__Reverse__SWIG_0 (std::vector< indri::api::DocumentVector::Field > * self)
Referenced by CSharp_FieldVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__Reverse__SWIG_1 (std::vector< indri::api::DocumentVector::Field > * self, int index, int count)
Referenced by CSharp_FieldVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__setitem (std::vector< indri::api::DocumentVector::Field > * self, int index, indri::api::DocumentVector::Field const & val)
Referenced by CSharp_FieldVector_setitem().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Field_Sg__SetRange (std::vector< indri::api::DocumentVector::Field > * self, int index, std::vector< indri::api::DocumentVector::Field > const & values)
Referenced by CSharp_FieldVector_SetRange().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__AddRange (std::vector< indri::api::DocumentVector * > * self, std::vector< indri::api::DocumentVector * > const & values)
Referenced by CSharp_DocumentVectorVector_AddRange().
SWIGINTERN bool std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Contains (std::vector< indri::api::DocumentVector * > * self, indri::api::DocumentVector *const & value)
Referenced by CSharp_DocumentVectorVector_Contains().
SWIGINTERN std::vector< indri::api::DocumentVector * >::const_reference std_vector_Sl_indri_api_DocumentVector_Sm__Sg__getitem (std::vector< indri::api::DocumentVector * > * self, int index)
Referenced by CSharp_DocumentVectorVector_getitem().
SWIGINTERN indri::api::DocumentVector* std_vector_Sl_indri_api_DocumentVector_Sm__Sg__getitemcopy (std::vector< indri::api::DocumentVector * > * self, int index)
Referenced by CSharp_DocumentVectorVector_getitemcopy().
SWIGINTERN std::vector< indri::api::DocumentVector * >* std_vector_Sl_indri_api_DocumentVector_Sm__Sg__GetRange (std::vector< indri::api::DocumentVector * > * self, int index, int count)
Referenced by CSharp_DocumentVectorVector_GetRange().
SWIGINTERN int std_vector_Sl_indri_api_DocumentVector_Sm__Sg__IndexOf (std::vector< indri::api::DocumentVector * > * self, indri::api::DocumentVector *const & value)
Referenced by CSharp_DocumentVectorVector_IndexOf().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Insert (std::vector< indri::api::DocumentVector * > * self, int index, indri::api::DocumentVector *const & x)
Referenced by CSharp_DocumentVectorVector_Insert().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__InsertRange (std::vector< indri::api::DocumentVector * > * self, int index, std::vector< indri::api::DocumentVector * > const & values)
Referenced by CSharp_DocumentVectorVector_InsertRange().
SWIGINTERN int std_vector_Sl_indri_api_DocumentVector_Sm__Sg__LastIndexOf (std::vector< indri::api::DocumentVector * > * self, indri::api::DocumentVector *const & value)
Referenced by CSharp_DocumentVectorVector_LastIndexOf().
SWIGINTERN bool std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Remove (std::vector< indri::api::DocumentVector * > * self, indri::api::DocumentVector *const & value)
Referenced by CSharp_DocumentVectorVector_Remove().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__RemoveAt (std::vector< indri::api::DocumentVector * > * self, int index)
Referenced by CSharp_DocumentVectorVector_RemoveAt().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__RemoveRange (std::vector< indri::api::DocumentVector * > * self, int index, int count)
Referenced by CSharp_DocumentVectorVector_RemoveRange().
SWIGINTERN std::vector< indri::api::DocumentVector * >* std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Repeat (indri::api::DocumentVector *const & value, int count)
Referenced by CSharp_DocumentVectorVector_Repeat().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Reverse__SWIG_0 (std::vector< indri::api::DocumentVector * > * self)
Referenced by CSharp_DocumentVectorVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__Reverse__SWIG_1 (std::vector< indri::api::DocumentVector * > * self, int index, int count)
Referenced by CSharp_DocumentVectorVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__setitem (std::vector< indri::api::DocumentVector * > * self, int index, indri::api::DocumentVector *const & val)
Referenced by CSharp_DocumentVectorVector_setitem().
SWIGINTERN void std_vector_Sl_indri_api_DocumentVector_Sm__Sg__SetRange (std::vector< indri::api::DocumentVector * > * self, int index, std::vector< indri::api::DocumentVector * > const & values)
Referenced by CSharp_DocumentVectorVector_SetRange().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__AddRange (std::vector< indri::api::ParsedDocument * > * self, std::vector< indri::api::ParsedDocument * > const & values)
Referenced by CSharp_ParsedDocumentVector_AddRange().
SWIGINTERN bool std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Contains (std::vector< indri::api::ParsedDocument * > * self, indri::api::ParsedDocument *const & value)
Referenced by CSharp_ParsedDocumentVector_Contains().
SWIGINTERN std::vector< indri::api::ParsedDocument * >::const_reference std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__getitem (std::vector< indri::api::ParsedDocument * > * self, int index)
Referenced by CSharp_ParsedDocumentVector_getitem().
SWIGINTERN indri::api::ParsedDocument* std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__getitemcopy (std::vector< indri::api::ParsedDocument * > * self, int index)
Referenced by CSharp_ParsedDocumentVector_getitemcopy().
SWIGINTERN std::vector< indri::api::ParsedDocument * >* std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__GetRange (std::vector< indri::api::ParsedDocument * > * self, int index, int count)
Referenced by CSharp_ParsedDocumentVector_GetRange().
SWIGINTERN int std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__IndexOf (std::vector< indri::api::ParsedDocument * > * self, indri::api::ParsedDocument *const & value)
Referenced by CSharp_ParsedDocumentVector_IndexOf().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Insert (std::vector< indri::api::ParsedDocument * > * self, int index, indri::api::ParsedDocument *const & x)
Referenced by CSharp_ParsedDocumentVector_Insert().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__InsertRange (std::vector< indri::api::ParsedDocument * > * self, int index, std::vector< indri::api::ParsedDocument * > const & values)
Referenced by CSharp_ParsedDocumentVector_InsertRange().
SWIGINTERN int std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__LastIndexOf (std::vector< indri::api::ParsedDocument * > * self, indri::api::ParsedDocument *const & value)
Referenced by CSharp_ParsedDocumentVector_LastIndexOf().
SWIGINTERN bool std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Remove (std::vector< indri::api::ParsedDocument * > * self, indri::api::ParsedDocument *const & value)
Referenced by CSharp_ParsedDocumentVector_Remove().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__RemoveAt (std::vector< indri::api::ParsedDocument * > * self, int index)
Referenced by CSharp_ParsedDocumentVector_RemoveAt().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__RemoveRange (std::vector< indri::api::ParsedDocument * > * self, int index, int count)
Referenced by CSharp_ParsedDocumentVector_RemoveRange().
SWIGINTERN std::vector< indri::api::ParsedDocument * >* std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Repeat (indri::api::ParsedDocument *const & value, int count)
Referenced by CSharp_ParsedDocumentVector_Repeat().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Reverse__SWIG_0 (std::vector< indri::api::ParsedDocument * > * self)
Referenced by CSharp_ParsedDocumentVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__Reverse__SWIG_1 (std::vector< indri::api::ParsedDocument * > * self, int index, int count)
Referenced by CSharp_ParsedDocumentVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__setitem (std::vector< indri::api::ParsedDocument * > * self, int index, indri::api::ParsedDocument *const & val)
Referenced by CSharp_ParsedDocumentVector_setitem().
SWIGINTERN void std_vector_Sl_indri_api_ParsedDocument_Sm__Sg__SetRange (std::vector< indri::api::ParsedDocument * > * self, int index, std::vector< indri::api::ParsedDocument * > const & values)
Referenced by CSharp_ParsedDocumentVector_SetRange().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__AddRange (std::vector< indri::api::QueryAnnotationNode * > * self, std::vector< indri::api::QueryAnnotationNode * > const & values)
Referenced by CSharp_QueryAnnotationNodeVector_AddRange().
SWIGINTERN bool std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Contains (std::vector< indri::api::QueryAnnotationNode * > * self, indri::api::QueryAnnotationNode *const & value)
Referenced by CSharp_QueryAnnotationNodeVector_Contains().
SWIGINTERN std::vector< indri::api::QueryAnnotationNode * >::const_reference std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__getitem (std::vector< indri::api::QueryAnnotationNode * > * self, int index)
Referenced by CSharp_QueryAnnotationNodeVector_getitem().
SWIGINTERN indri::api::QueryAnnotationNode* std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__getitemcopy (std::vector< indri::api::QueryAnnotationNode * > * self, int index)
Referenced by CSharp_QueryAnnotationNodeVector_getitemcopy().
SWIGINTERN std::vector< indri::api::QueryAnnotationNode * >* std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__GetRange (std::vector< indri::api::QueryAnnotationNode * > * self, int index, int count)
Referenced by CSharp_QueryAnnotationNodeVector_GetRange().
SWIGINTERN int std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__IndexOf (std::vector< indri::api::QueryAnnotationNode * > * self, indri::api::QueryAnnotationNode *const & value)
Referenced by CSharp_QueryAnnotationNodeVector_IndexOf().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Insert (std::vector< indri::api::QueryAnnotationNode * > * self, int index, indri::api::QueryAnnotationNode *const & x)
Referenced by CSharp_QueryAnnotationNodeVector_Insert().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__InsertRange (std::vector< indri::api::QueryAnnotationNode * > * self, int index, std::vector< indri::api::QueryAnnotationNode * > const & values)
Referenced by CSharp_QueryAnnotationNodeVector_InsertRange().
SWIGINTERN int std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__LastIndexOf (std::vector< indri::api::QueryAnnotationNode * > * self, indri::api::QueryAnnotationNode *const & value)
Referenced by CSharp_QueryAnnotationNodeVector_LastIndexOf().
SWIGINTERN bool std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Remove (std::vector< indri::api::QueryAnnotationNode * > * self, indri::api::QueryAnnotationNode *const & value)
Referenced by CSharp_QueryAnnotationNodeVector_Remove().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__RemoveAt (std::vector< indri::api::QueryAnnotationNode * > * self, int index)
Referenced by CSharp_QueryAnnotationNodeVector_RemoveAt().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__RemoveRange (std::vector< indri::api::QueryAnnotationNode * > * self, int index, int count)
Referenced by CSharp_QueryAnnotationNodeVector_RemoveRange().
SWIGINTERN std::vector< indri::api::QueryAnnotationNode * >* std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Repeat (indri::api::QueryAnnotationNode *const & value, int count)
Referenced by CSharp_QueryAnnotationNodeVector_Repeat().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Reverse__SWIG_0 (std::vector< indri::api::QueryAnnotationNode * > * self)
Referenced by CSharp_QueryAnnotationNodeVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__Reverse__SWIG_1 (std::vector< indri::api::QueryAnnotationNode * > * self, int index, int count)
Referenced by CSharp_QueryAnnotationNodeVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__setitem (std::vector< indri::api::QueryAnnotationNode * > * self, int index, indri::api::QueryAnnotationNode *const & val)
Referenced by CSharp_QueryAnnotationNodeVector_setitem().
SWIGINTERN void std_vector_Sl_indri_api_QueryAnnotationNode_Sm__Sg__SetRange (std::vector< indri::api::QueryAnnotationNode * > * self, int index, std::vector< indri::api::QueryAnnotationNode * > const & values)
Referenced by CSharp_QueryAnnotationNodeVector_SetRange().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__AddRange (std::vector< indri::api::ScoredExtentResult > * self, std::vector< indri::api::ScoredExtentResult > const & values)
Referenced by CSharp_ScoredExtentResultVector_AddRange().
SWIGINTERN std::vector< indri::api::ScoredExtentResult >::const_reference std_vector_Sl_indri_api_ScoredExtentResult_Sg__getitem (std::vector< indri::api::ScoredExtentResult > * self, int index)
Referenced by CSharp_ScoredExtentResultVector_getitem().
SWIGINTERN indri::api::ScoredExtentResult std_vector_Sl_indri_api_ScoredExtentResult_Sg__getitemcopy (std::vector< indri::api::ScoredExtentResult > * self, int index)
Referenced by CSharp_ScoredExtentResultVector_getitemcopy().
SWIGINTERN std::vector< indri::api::ScoredExtentResult >* std_vector_Sl_indri_api_ScoredExtentResult_Sg__GetRange (std::vector< indri::api::ScoredExtentResult > * self, int index, int count)
Referenced by CSharp_ScoredExtentResultVector_GetRange().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__Insert (std::vector< indri::api::ScoredExtentResult > * self, int index, indri::api::ScoredExtentResult const & x)
Referenced by CSharp_ScoredExtentResultVector_Insert().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__InsertRange (std::vector< indri::api::ScoredExtentResult > * self, int index, std::vector< indri::api::ScoredExtentResult > const & values)
Referenced by CSharp_ScoredExtentResultVector_InsertRange().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__RemoveAt (std::vector< indri::api::ScoredExtentResult > * self, int index)
Referenced by CSharp_ScoredExtentResultVector_RemoveAt().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__RemoveRange (std::vector< indri::api::ScoredExtentResult > * self, int index, int count)
Referenced by CSharp_ScoredExtentResultVector_RemoveRange().
SWIGINTERN std::vector< indri::api::ScoredExtentResult >* std_vector_Sl_indri_api_ScoredExtentResult_Sg__Repeat (indri::api::ScoredExtentResult const & value, int count)
Referenced by CSharp_ScoredExtentResultVector_Repeat().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__Reverse__SWIG_0 (std::vector< indri::api::ScoredExtentResult > * self)
Referenced by CSharp_ScoredExtentResultVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__Reverse__SWIG_1 (std::vector< indri::api::ScoredExtentResult > * self, int index, int count)
Referenced by CSharp_ScoredExtentResultVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__setitem (std::vector< indri::api::ScoredExtentResult > * self, int index, indri::api::ScoredExtentResult const & val)
Referenced by CSharp_ScoredExtentResultVector_setitem().
SWIGINTERN void std_vector_Sl_indri_api_ScoredExtentResult_Sg__SetRange (std::vector< indri::api::ScoredExtentResult > * self, int index, std::vector< indri::api::ScoredExtentResult > const & values)
Referenced by CSharp_ScoredExtentResultVector_SetRange().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__AddRange (std::vector< indri::parse::MetadataPair > * self, std::vector< indri::parse::MetadataPair > const & values)
Referenced by CSharp_MetadataPairSTDVector_AddRange().
SWIGINTERN std::vector< indri::parse::MetadataPair >::const_reference std_vector_Sl_indri_parse_MetadataPair_Sg__getitem (std::vector< indri::parse::MetadataPair > * self, int index)
Referenced by CSharp_MetadataPairSTDVector_getitem().
SWIGINTERN indri::parse::MetadataPair std_vector_Sl_indri_parse_MetadataPair_Sg__getitemcopy (std::vector< indri::parse::MetadataPair > * self, int index)
Referenced by CSharp_MetadataPairSTDVector_getitemcopy().
SWIGINTERN std::vector< indri::parse::MetadataPair >* std_vector_Sl_indri_parse_MetadataPair_Sg__GetRange (std::vector< indri::parse::MetadataPair > * self, int index, int count)
Referenced by CSharp_MetadataPairSTDVector_GetRange().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__Insert (std::vector< indri::parse::MetadataPair > * self, int index, indri::parse::MetadataPair const & x)
Referenced by CSharp_MetadataPairSTDVector_Insert().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__InsertRange (std::vector< indri::parse::MetadataPair > * self, int index, std::vector< indri::parse::MetadataPair > const & values)
Referenced by CSharp_MetadataPairSTDVector_InsertRange().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__RemoveAt (std::vector< indri::parse::MetadataPair > * self, int index)
Referenced by CSharp_MetadataPairSTDVector_RemoveAt().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__RemoveRange (std::vector< indri::parse::MetadataPair > * self, int index, int count)
Referenced by CSharp_MetadataPairSTDVector_RemoveRange().
SWIGINTERN std::vector< indri::parse::MetadataPair >* std_vector_Sl_indri_parse_MetadataPair_Sg__Repeat (indri::parse::MetadataPair const & value, int count)
Referenced by CSharp_MetadataPairSTDVector_Repeat().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_0 (std::vector< indri::parse::MetadataPair > * self)
Referenced by CSharp_MetadataPairSTDVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__Reverse__SWIG_1 (std::vector< indri::parse::MetadataPair > * self, int index, int count)
Referenced by CSharp_MetadataPairSTDVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__setitem (std::vector< indri::parse::MetadataPair > * self, int index, indri::parse::MetadataPair const & val)
Referenced by CSharp_MetadataPairSTDVector_setitem().
SWIGINTERN void std_vector_Sl_indri_parse_MetadataPair_Sg__SetRange (std::vector< indri::parse::MetadataPair > * self, int index, std::vector< indri::parse::MetadataPair > const & values)
Referenced by CSharp_MetadataPairSTDVector_SetRange().
SWIGINTERN void std_vector_Sl_int_Sg__AddRange (std::vector< int > * self, std::vector< int > const & values)
Referenced by CSharp_IntVector_AddRange().
SWIGINTERN bool std_vector_Sl_int_Sg__Contains (std::vector< int > * self, int const & value)
Referenced by CSharp_IntVector_Contains().
SWIGINTERN std::vector< int >::const_reference std_vector_Sl_int_Sg__getitem (std::vector< int > * self, int index)
Referenced by CSharp_IntVector_getitem().
SWIGINTERN int std_vector_Sl_int_Sg__getitemcopy (std::vector< int > * self, int index)
Referenced by CSharp_IntVector_getitemcopy().
SWIGINTERN std::vector< int >* std_vector_Sl_int_Sg__GetRange (std::vector< int > * self, int index, int count)
Referenced by CSharp_IntVector_GetRange().
SWIGINTERN int std_vector_Sl_int_Sg__IndexOf (std::vector< int > * self, int const & value)
Referenced by CSharp_IntVector_IndexOf().
SWIGINTERN void std_vector_Sl_int_Sg__Insert (std::vector< int > * self, int index, int const & x)
Referenced by CSharp_IntVector_Insert().
SWIGINTERN void std_vector_Sl_int_Sg__InsertRange (std::vector< int > * self, int index, std::vector< int > const & values)
Referenced by CSharp_IntVector_InsertRange().
SWIGINTERN int std_vector_Sl_int_Sg__LastIndexOf (std::vector< int > * self, int const & value)
Referenced by CSharp_IntVector_LastIndexOf().
SWIGINTERN bool std_vector_Sl_int_Sg__Remove (std::vector< int > * self, int const & value)
Referenced by CSharp_IntVector_Remove().
SWIGINTERN void std_vector_Sl_int_Sg__RemoveAt (std::vector< int > * self, int index)
Referenced by CSharp_IntVector_RemoveAt().
SWIGINTERN void std_vector_Sl_int_Sg__RemoveRange (std::vector< int > * self, int index, int count)
Referenced by CSharp_IntVector_RemoveRange().
SWIGINTERN std::vector< int >* std_vector_Sl_int_Sg__Repeat (int const & value, int count)
Referenced by CSharp_IntVector_Repeat().
SWIGINTERN void std_vector_Sl_int_Sg__Reverse__SWIG_0 (std::vector< int > * self)
Referenced by CSharp_IntVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_int_Sg__Reverse__SWIG_1 (std::vector< int > * self, int index, int count)
Referenced by CSharp_IntVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_int_Sg__setitem (std::vector< int > * self, int index, int const & val)
Referenced by CSharp_IntVector_setitem().
SWIGINTERN void std_vector_Sl_int_Sg__SetRange (std::vector< int > * self, int index, std::vector< int > const & values)
Referenced by CSharp_IntVector_SetRange().
SWIGINTERN void std_vector_Sl_std_string_Sg__AddRange (std::vector< std::string > * self, std::vector< std::string > const & values)
Referenced by CSharp_StringVector_AddRange().
SWIGINTERN bool std_vector_Sl_std_string_Sg__Contains (std::vector< std::string > * self, std::string const & value)
Referenced by CSharp_StringVector_Contains().
SWIGINTERN std::vector< std::string >::const_reference std_vector_Sl_std_string_Sg__getitem (std::vector< std::string > * self, int index)
Referenced by CSharp_StringVector_getitem().
SWIGINTERN std::string std_vector_Sl_std_string_Sg__getitemcopy (std::vector< std::string > * self, int index)
Referenced by CSharp_StringVector_getitemcopy().
SWIGINTERN std::vector< std::string >* std_vector_Sl_std_string_Sg__GetRange (std::vector< std::string > * self, int index, int count)
Referenced by CSharp_StringVector_GetRange().
SWIGINTERN int std_vector_Sl_std_string_Sg__IndexOf (std::vector< std::string > * self, std::string const & value)
Referenced by CSharp_StringVector_IndexOf().
SWIGINTERN void std_vector_Sl_std_string_Sg__Insert (std::vector< std::string > * self, int index, std::string const & x)
Referenced by CSharp_StringVector_Insert().
SWIGINTERN void std_vector_Sl_std_string_Sg__InsertRange (std::vector< std::string > * self, int index, std::vector< std::string > const & values)
Referenced by CSharp_StringVector_InsertRange().
SWIGINTERN int std_vector_Sl_std_string_Sg__LastIndexOf (std::vector< std::string > * self, std::string const & value)
Referenced by CSharp_StringVector_LastIndexOf().
SWIGINTERN bool std_vector_Sl_std_string_Sg__Remove (std::vector< std::string > * self, std::string const & value)
Referenced by CSharp_StringVector_Remove().
SWIGINTERN void std_vector_Sl_std_string_Sg__RemoveAt (std::vector< std::string > * self, int index)
Referenced by CSharp_StringVector_RemoveAt().
SWIGINTERN void std_vector_Sl_std_string_Sg__RemoveRange (std::vector< std::string > * self, int index, int count)
Referenced by CSharp_StringVector_RemoveRange().
SWIGINTERN std::vector< std::string >* std_vector_Sl_std_string_Sg__Repeat (std::string const & value, int count)
Referenced by CSharp_StringVector_Repeat().
SWIGINTERN void std_vector_Sl_std_string_Sg__Reverse__SWIG_0 (std::vector< std::string > * self)
Referenced by CSharp_StringVector_Reverse__SWIG_0().
SWIGINTERN void std_vector_Sl_std_string_Sg__Reverse__SWIG_1 (std::vector< std::string > * self, int index, int count)
Referenced by CSharp_StringVector_Reverse__SWIG_1().
SWIGINTERN void std_vector_Sl_std_string_Sg__setitem (std::vector< std::string > * self, int index, std::string const & val)
Referenced by CSharp_StringVector_setitem().
SWIGINTERN void std_vector_Sl_std_string_Sg__SetRange (std::vector< std::string > * self, int index, std::vector< std::string > const & values)
Referenced by CSharp_StringVector_SetRange().
SWIGINTERN void SWIG_CSharpException (int code, const char * msg)
References SWIG_CSharpApplicationException, SWIG_CSharpArgumentOutOfRangeException, SWIG_CSharpDivideByZeroException, SWIG_CSharpIndexOutOfRangeException, SWIG_CSharpIOException, SWIG_CSharpOutOfMemoryException, SWIG_CSharpOverflowException, SWIG_CSharpSetPendingException(), SWIG_CSharpSetPendingExceptionArgument(), SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_MemoryError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, SWIG_UnknownError, and SWIG_ValueError.
static void SWIGUNUSED SWIG_CSharpSetPendingException (SWIG_CSharpExceptionCodes code, const char * msg) [static]
References SWIG_CSharpException_t::callback, and SWIG_CSharpApplicationException.
Referenced by CSharp_IndexEnvironment_addFile__SWIG_0(), CSharp_IndexEnvironment_addFile__SWIG_1(), CSharp_IndexEnvironment_addFileClass__SWIG_0(), CSharp_IndexEnvironment_addFileClass__SWIG_1(), CSharp_IndexEnvironment_addParsedDocument(), CSharp_IndexEnvironment_addString(), CSharp_IndexEnvironment_close(), CSharp_IndexEnvironment_create__SWIG_0(), CSharp_IndexEnvironment_create__SWIG_1(), CSharp_IndexEnvironment_deleteDocument(), CSharp_IndexEnvironment_documentsIndexed(), CSharp_IndexEnvironment_documentsSeen(), CSharp_IndexEnvironment_getFileClassSpec(), CSharp_IndexEnvironment_open__SWIG_0(), CSharp_IndexEnvironment_open__SWIG_1(), CSharp_IndexEnvironment_setAnchorTextPath(), CSharp_IndexEnvironment_setDocumentRoot(), CSharp_IndexEnvironment_setIndexedFields(), CSharp_IndexEnvironment_setMemory(), CSharp_IndexEnvironment_setMetadataIndexedFields(), CSharp_IndexEnvironment_setNormalization(), CSharp_IndexEnvironment_setNumericField__SWIG_0(), CSharp_IndexEnvironment_setNumericField__SWIG_1(), CSharp_IndexEnvironment_setOffsetAnnotationsPath(), CSharp_IndexEnvironment_setOffsetMetadataPath(), CSharp_IndexEnvironment_setOrdinalField(), CSharp_IndexEnvironment_setParentalField(), CSharp_IndexEnvironment_setStemmer(), CSharp_IndexEnvironment_setStopwords(), CSharp_IndexEnvironment_setStoreDocs(), CSharp_QueryAnnotation_getAnnotations(), CSharp_QueryAnnotation_getQueryTree(), CSharp_QueryAnnotation_getResults(), CSharp_QueryEnvironment_addIndex(), CSharp_QueryEnvironment_addServer(), CSharp_QueryEnvironment_close(), CSharp_QueryEnvironment_documentCount__SWIG_0(), CSharp_QueryEnvironment_documentCount__SWIG_1(), CSharp_QueryEnvironment_documentExpressionCount__SWIG_0(), CSharp_QueryEnvironment_documentExpressionCount__SWIG_1(), CSharp_QueryEnvironment_documentIDsFromMetadata(), CSharp_QueryEnvironment_documentLength(), CSharp_QueryEnvironment_documentMetadata__SWIG_0(), CSharp_QueryEnvironment_documentMetadata__SWIG_1(), CSharp_QueryEnvironment_documents__SWIG_0(), CSharp_QueryEnvironment_documents__SWIG_1(), CSharp_QueryEnvironment_documentsFromMetadata(), CSharp_QueryEnvironment_documentVectors(), CSharp_QueryEnvironment_expressionCount__SWIG_0(), CSharp_QueryEnvironment_expressionCount__SWIG_1(), CSharp_QueryEnvironment_expressionList__SWIG_0(), CSharp_QueryEnvironment_expressionList__SWIG_1(), CSharp_QueryEnvironment_fieldList(), CSharp_QueryEnvironment_removeIndex(), CSharp_QueryEnvironment_removeServer(), CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_0(), CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_1(), CSharp_QueryEnvironment_runQuery__SWIG_0(), CSharp_QueryEnvironment_runQuery__SWIG_1(), CSharp_QueryEnvironment_setMemory(), CSharp_QueryEnvironment_setScoringRules(), CSharp_QueryEnvironment_setStopwords(), CSharp_QueryEnvironment_termCount__SWIG_0(), CSharp_QueryEnvironment_termCount__SWIG_1(), CSharp_QueryEnvironment_termFieldCount(), and SWIG_CSharpException().
static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument (SWIG_CSharpExceptionArgumentCodes code, const char * msg, const char * param_name) [static]
References SWIG_CSharpExceptionArgument_t::callback, and SWIG_CSharpArgumentException.
Referenced by CSharp_AttributeValuePairVector_Add(), CSharp_AttributeValuePairVector_AddRange(), CSharp_AttributeValuePairVector_getitem(), CSharp_AttributeValuePairVector_getitemcopy(), CSharp_AttributeValuePairVector_GetRange(), CSharp_AttributeValuePairVector_Insert(), CSharp_AttributeValuePairVector_InsertRange(), CSharp_AttributeValuePairVector_RemoveAt(), CSharp_AttributeValuePairVector_RemoveRange(), CSharp_AttributeValuePairVector_Repeat(), CSharp_AttributeValuePairVector_Reverse__SWIG_1(), CSharp_AttributeValuePairVector_setitem(), CSharp_AttributeValuePairVector_SetRange(), CSharp_Char_pVector_AddRange(), CSharp_Char_pVector_getitem(), CSharp_Char_pVector_getitemcopy(), CSharp_Char_pVector_GetRange(), CSharp_Char_pVector_Insert(), CSharp_Char_pVector_InsertRange(), CSharp_Char_pVector_RemoveAt(), CSharp_Char_pVector_RemoveRange(), CSharp_Char_pVector_Repeat(), CSharp_Char_pVector_Reverse__SWIG_1(), CSharp_Char_pVector_setitem(), CSharp_Char_pVector_SetRange(), CSharp_ConfMap_Add(), CSharp_ConfMap_get_next_key(), CSharp_ConfMap_getitem(), CSharp_ConfMap_setitem(), CSharp_DocumentVectorVector_AddRange(), CSharp_DocumentVectorVector_getitem(), CSharp_DocumentVectorVector_getitemcopy(), CSharp_DocumentVectorVector_GetRange(), CSharp_DocumentVectorVector_Insert(), CSharp_DocumentVectorVector_InsertRange(), CSharp_DocumentVectorVector_RemoveAt(), CSharp_DocumentVectorVector_RemoveRange(), CSharp_DocumentVectorVector_Repeat(), CSharp_DocumentVectorVector_Reverse__SWIG_1(), CSharp_DocumentVectorVector_setitem(), CSharp_DocumentVectorVector_SetRange(), CSharp_Field_name_set(), CSharp_FieldVector_Add(), CSharp_FieldVector_AddRange(), CSharp_FieldVector_getitem(), CSharp_FieldVector_getitemcopy(), CSharp_FieldVector_GetRange(), CSharp_FieldVector_Insert(), CSharp_FieldVector_InsertRange(), CSharp_FieldVector_RemoveAt(), CSharp_FieldVector_RemoveRange(), CSharp_FieldVector_Repeat(), CSharp_FieldVector_Reverse__SWIG_1(), CSharp_FieldVector_setitem(), CSharp_FieldVector_SetRange(), CSharp_IndexEnvironment_addFile__SWIG_0(), CSharp_IndexEnvironment_addFile__SWIG_1(), CSharp_IndexEnvironment_addFileClass__SWIG_0(), CSharp_IndexEnvironment_addFileClass__SWIG_1(), CSharp_IndexEnvironment_addString(), CSharp_IndexEnvironment_create__SWIG_0(), CSharp_IndexEnvironment_create__SWIG_1(), CSharp_IndexEnvironment_getFileClassSpec(), CSharp_IndexEnvironment_open__SWIG_0(), CSharp_IndexEnvironment_open__SWIG_1(), CSharp_IndexEnvironment_setAnchorTextPath(), CSharp_IndexEnvironment_setDocumentRoot(), CSharp_IndexEnvironment_setIndexedFields(), CSharp_IndexEnvironment_setMetadataIndexedFields(), CSharp_IndexEnvironment_setNumericField__SWIG_0(), CSharp_IndexEnvironment_setNumericField__SWIG_1(), CSharp_IndexEnvironment_setOffsetAnnotationsPath(), CSharp_IndexEnvironment_setOffsetMetadataPath(), CSharp_IndexEnvironment_setOrdinalField(), CSharp_IndexEnvironment_setParentalField(), CSharp_IndexEnvironment_setStemmer(), CSharp_IndexEnvironment_setStopwords(), CSharp_IndexStatus_status(), CSharp_IntVector_AddRange(), CSharp_IntVector_getitem(), CSharp_IntVector_getitemcopy(), CSharp_IntVector_GetRange(), CSharp_IntVector_Insert(), CSharp_IntVector_InsertRange(), CSharp_IntVector_RemoveAt(), CSharp_IntVector_RemoveRange(), CSharp_IntVector_Repeat(), CSharp_IntVector_Reverse__SWIG_1(), CSharp_IntVector_setitem(), CSharp_IntVector_SetRange(), CSharp_MetadataPairSTDVector_Add(), CSharp_MetadataPairSTDVector_AddRange(), CSharp_MetadataPairSTDVector_getitem(), CSharp_MetadataPairSTDVector_getitemcopy(), CSharp_MetadataPairSTDVector_GetRange(), CSharp_MetadataPairSTDVector_Insert(), CSharp_MetadataPairSTDVector_InsertRange(), CSharp_MetadataPairSTDVector_RemoveAt(), CSharp_MetadataPairSTDVector_RemoveRange(), CSharp_MetadataPairSTDVector_Repeat(), CSharp_MetadataPairSTDVector_Reverse__SWIG_1(), CSharp_MetadataPairSTDVector_setitem(), CSharp_MetadataPairSTDVector_SetRange(), CSharp_MetadataPairVector_Add(), CSharp_MetadataPairVector_AddRange(), CSharp_MetadataPairVector_getitem(), CSharp_MetadataPairVector_getitemcopy(), CSharp_MetadataPairVector_GetRange(), CSharp_MetadataPairVector_Insert(), CSharp_MetadataPairVector_InsertRange(), CSharp_MetadataPairVector_RemoveAt(), CSharp_MetadataPairVector_RemoveRange(), CSharp_MetadataPairVector_Repeat(), CSharp_MetadataPairVector_Reverse__SWIG_1(), CSharp_MetadataPairVector_setitem(), CSharp_MetadataPairVector_SetRange(), CSharp_MResults_Add(), CSharp_MResults_ContainsKey(), CSharp_MResults_get_next_key(), CSharp_MResults_getitem(), CSharp_MResults_Remove(), CSharp_MResults_setitem(), CSharp_new_AttributeValuePairVector__SWIG_1(), CSharp_new_Char_pVector__SWIG_1(), CSharp_new_ConfMap__SWIG_1(), CSharp_new_DocumentVectorVector__SWIG_1(), CSharp_new_DocumentVectorVector__SWIG_2(), CSharp_new_FieldVector__SWIG_1(), CSharp_new_FieldVector__SWIG_2(), CSharp_new_IntVector__SWIG_1(), CSharp_new_IntVector__SWIG_2(), CSharp_new_MetadataPairSTDVector__SWIG_1(), CSharp_new_MetadataPairSTDVector__SWIG_2(), CSharp_new_MetadataPairVector__SWIG_1(), CSharp_new_MResults__SWIG_1(), CSharp_new_ParsedDocumentVector__SWIG_1(), CSharp_new_ParsedDocumentVector__SWIG_2(), CSharp_new_PonteExpander(), CSharp_new_QueryAnnotationNodeVector__SWIG_1(), CSharp_new_QueryAnnotationNodeVector__SWIG_2(), CSharp_new_RMExpander(), CSharp_new_ScoredExtentResultVector__SWIG_1(), CSharp_new_ScoredExtentResultVector__SWIG_2(), CSharp_new_StringVector__SWIG_1(), CSharp_new_StringVector__SWIG_2(), CSharp_new_TagExtentVector__SWIG_1(), CSharp_new_TermExtentVector__SWIG_1(), CSharp_Parameters_exists__SWIG_1(), CSharp_Parameters_get__SWIG_0(), CSharp_Parameters_get__SWIG_1(), CSharp_Parameters_get__SWIG_2(), CSharp_Parameters_get__SWIG_3(), CSharp_Parameters_get__SWIG_4(), CSharp_Parameters_load(), CSharp_Parameters_remove(), CSharp_Parameters_set__SWIG_0(), CSharp_Parameters_set__SWIG_1(), CSharp_Parameters_set__SWIG_2(), CSharp_Parameters_set__SWIG_3(), CSharp_Parameters_set__SWIG_4(), CSharp_Parameters_set__SWIG_5(), CSharp_ParsedDocumentVector_AddRange(), CSharp_ParsedDocumentVector_getitem(), CSharp_ParsedDocumentVector_getitemcopy(), CSharp_ParsedDocumentVector_GetRange(), CSharp_ParsedDocumentVector_Insert(), CSharp_ParsedDocumentVector_InsertRange(), CSharp_ParsedDocumentVector_RemoveAt(), CSharp_ParsedDocumentVector_RemoveRange(), CSharp_ParsedDocumentVector_Repeat(), CSharp_ParsedDocumentVector_Reverse__SWIG_1(), CSharp_ParsedDocumentVector_setitem(), CSharp_ParsedDocumentVector_SetRange(), CSharp_PonteExpander_expand(), CSharp_QueryAnnotationNode_name_set(), CSharp_QueryAnnotationNode_queryText_set(), CSharp_QueryAnnotationNode_type_set(), CSharp_QueryAnnotationNodeVector_AddRange(), CSharp_QueryAnnotationNodeVector_getitem(), CSharp_QueryAnnotationNodeVector_getitemcopy(), CSharp_QueryAnnotationNodeVector_GetRange(), CSharp_QueryAnnotationNodeVector_Insert(), CSharp_QueryAnnotationNodeVector_InsertRange(), CSharp_QueryAnnotationNodeVector_RemoveAt(), CSharp_QueryAnnotationNodeVector_RemoveRange(), CSharp_QueryAnnotationNodeVector_Repeat(), CSharp_QueryAnnotationNodeVector_Reverse__SWIG_1(), CSharp_QueryAnnotationNodeVector_setitem(), CSharp_QueryAnnotationNodeVector_SetRange(), CSharp_QueryEnvironment_addIndex(), CSharp_QueryEnvironment_addServer(), CSharp_QueryEnvironment_documentCount__SWIG_1(), CSharp_QueryEnvironment_documentExpressionCount__SWIG_0(), CSharp_QueryEnvironment_documentExpressionCount__SWIG_1(), CSharp_QueryEnvironment_documentIDsFromMetadata(), CSharp_QueryEnvironment_documentMetadata__SWIG_0(), CSharp_QueryEnvironment_documentMetadata__SWIG_1(), CSharp_QueryEnvironment_documents__SWIG_0(), CSharp_QueryEnvironment_documents__SWIG_1(), CSharp_QueryEnvironment_documentsFromMetadata(), CSharp_QueryEnvironment_documentStemCount(), CSharp_QueryEnvironment_documentVectors(), CSharp_QueryEnvironment_expressionCount__SWIG_0(), CSharp_QueryEnvironment_expressionCount__SWIG_1(), CSharp_QueryEnvironment_expressionList__SWIG_0(), CSharp_QueryEnvironment_expressionList__SWIG_1(), CSharp_QueryEnvironment_reformulateQuery(), CSharp_QueryEnvironment_removeIndex(), CSharp_QueryEnvironment_removeServer(), CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_0(), CSharp_QueryEnvironment_runAnnotatedQuery__SWIG_1(), CSharp_QueryEnvironment_runQuery__SWIG_0(), CSharp_QueryEnvironment_runQuery__SWIG_1(), CSharp_QueryEnvironment_setFormulationParameters(), CSharp_QueryEnvironment_setScoringRules(), CSharp_QueryEnvironment_setStopwords(), CSharp_QueryEnvironment_stemCount(), CSharp_QueryEnvironment_stemFieldCount(), CSharp_QueryEnvironment_stemTerm(), CSharp_QueryEnvironment_termCount__SWIG_1(), CSharp_QueryEnvironment_termFieldCount(), CSharp_QueryExpander_expand(), CSharp_QueryExpander_runExpandedQuery__SWIG_0(), CSharp_QueryExpander_runExpandedQuery__SWIG_1(), CSharp_RMExpander_expand(), CSharp_ScoredExtentResultVector_Add(), CSharp_ScoredExtentResultVector_AddRange(), CSharp_ScoredExtentResultVector_getitem(), CSharp_ScoredExtentResultVector_getitemcopy(), CSharp_ScoredExtentResultVector_GetRange(), CSharp_ScoredExtentResultVector_Insert(), CSharp_ScoredExtentResultVector_InsertRange(), CSharp_ScoredExtentResultVector_RemoveAt(), CSharp_ScoredExtentResultVector_RemoveRange(), CSharp_ScoredExtentResultVector_Repeat(), CSharp_ScoredExtentResultVector_Reverse__SWIG_1(), CSharp_ScoredExtentResultVector_setitem(), CSharp_ScoredExtentResultVector_SetRange(), CSharp_Specification_endDocTag_set(), CSharp_Specification_endMetadataTag_set(), CSharp_Specification_iterator_set(), CSharp_Specification_name_set(), CSharp_Specification_parser_set(), CSharp_Specification_startDocTag_set(), CSharp_Specification_tokenizer_set(), CSharp_StringVector_Add(), CSharp_StringVector_AddRange(), CSharp_StringVector_Contains(), CSharp_StringVector_getitem(), CSharp_StringVector_getitemcopy(), CSharp_StringVector_GetRange(), CSharp_StringVector_IndexOf(), CSharp_StringVector_Insert(), CSharp_StringVector_InsertRange(), CSharp_StringVector_LastIndexOf(), CSharp_StringVector_Remove(), CSharp_StringVector_RemoveAt(), CSharp_StringVector_RemoveRange(), CSharp_StringVector_Repeat(), CSharp_StringVector_Reverse__SWIG_1(), CSharp_StringVector_setitem(), CSharp_StringVector_SetRange(), CSharp_TagExtentVector_Add(), CSharp_TagExtentVector_AddRange(), CSharp_TagExtentVector_getitem(), CSharp_TagExtentVector_getitemcopy(), CSharp_TagExtentVector_GetRange(), CSharp_TagExtentVector_Insert(), CSharp_TagExtentVector_InsertRange(), CSharp_TagExtentVector_RemoveAt(), CSharp_TagExtentVector_RemoveRange(), CSharp_TagExtentVector_Repeat(), CSharp_TagExtentVector_Reverse__SWIG_1(), CSharp_TagExtentVector_setitem(), CSharp_TagExtentVector_SetRange(), CSharp_TermExtentVector_Add(), CSharp_TermExtentVector_AddRange(), CSharp_TermExtentVector_getitem(), CSharp_TermExtentVector_getitemcopy(), CSharp_TermExtentVector_GetRange(), CSharp_TermExtentVector_Insert(), CSharp_TermExtentVector_InsertRange(), CSharp_TermExtentVector_RemoveAt(), CSharp_TermExtentVector_RemoveRange(), CSharp_TermExtentVector_Repeat(), CSharp_TermExtentVector_Reverse__SWIG_1(), CSharp_TermExtentVector_setitem(), CSharp_TermExtentVector_SetRange(), and SWIG_CSharpException().
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_indri_csharp (SWIG_CSharpExceptionArgumentCallback_t argumentCallback, SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback, SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback)
References SWIG_CSharpExceptionArgument_t::callback, SWIG_CSharpArgumentException, SWIG_CSharpArgumentNullException, and SWIG_CSharpArgumentOutOfRangeException.
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_indri_csharp (SWIG_CSharpExceptionCallback_t applicationCallback, SWIG_CSharpExceptionCallback_t arithmeticCallback, SWIG_CSharpExceptionCallback_t divideByZeroCallback, SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, SWIG_CSharpExceptionCallback_t invalidCastCallback, SWIG_CSharpExceptionCallback_t invalidOperationCallback, SWIG_CSharpExceptionCallback_t ioCallback, SWIG_CSharpExceptionCallback_t nullReferenceCallback, SWIG_CSharpExceptionCallback_t outOfMemoryCallback, SWIG_CSharpExceptionCallback_t overflowCallback, SWIG_CSharpExceptionCallback_t systemCallback)
References SWIG_CSharpException_t::callback, SWIG_CSharpApplicationException, SWIG_CSharpArithmeticException, SWIG_CSharpDivideByZeroException, SWIG_CSharpIndexOutOfRangeException, SWIG_CSharpInvalidCastException, SWIG_CSharpInvalidOperationException, SWIG_CSharpIOException, SWIG_CSharpNullReferenceException, SWIG_CSharpOutOfMemoryException, SWIG_CSharpOverflowException, and SWIG_CSharpSystemException.
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_indri_csharp (SWIG_CSharpStringHelperCallback callback)
References SWIG_csharp_string_callback.
Variable Documentation
SWIG_CSharpException_t SWIG_csharp_exceptions[] [static]
Initial value:
 {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
}
SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] [static]
Initial value:
 {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
}
SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL [static]
Referenced by CSharp_AttributeValuePair_attribute_get(), CSharp_AttributeValuePair_value_get(), CSharp_Char_pVector_getitem(), CSharp_Char_pVector_getitemcopy(), CSharp_ConflationPattern_attribute_name_get(), CSharp_ConflationPattern_tag_name_get(), CSharp_ConflationPattern_value_get(), CSharp_ConfMap_getitem(), CSharp_Field_name_get(), CSharp_MetadataPair_key_get(), CSharp_MetadataPair_value_get(), CSharp_MResults_get_next_key(), CSharp_Parameters_get__SWIG_4(), CSharp_ParsedDocument_content_get(), CSharp_ParsedDocument_getContent(), CSharp_ParsedDocument_text_get(), CSharp_PonteExpander_expand(), CSharp_QueryAnnotationNode_name_get(), CSharp_QueryAnnotationNode_queryText_get(), CSharp_QueryAnnotationNode_type_get(), CSharp_QueryEnvironment_reformulateQuery(), CSharp_QueryEnvironment_stemTerm(), CSharp_QueryExpander_expand(), CSharp_RMExpander_expand(), CSharp_Specification_endDocTag_get(), CSharp_Specification_endMetadataTag_get(), CSharp_Specification_iterator_get(), CSharp_Specification_name_get(), CSharp_Specification_parser_get(), CSharp_Specification_startDocTag_get(), CSharp_Specification_tokenizer_get(), CSharp_StringVector_getitem(), CSharp_StringVector_getitemcopy(), CSharp_TagExtent_name_get(), SwigDirector_IndexStatus::status(), and SWIGRegisterStringCallback_indri_csharp().