Indri: indri_jni.cpp File Reference
indri_jni.cpp File Reference
#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include "indri/indri-platform.h"
#include "lemur-compat.hpp"
#include "indri/QueryEnvironment.hpp"
#include "indri/QueryExpander.hpp"
#include "indri/RMExpander.hpp"
#include "indri/PonteExpander.hpp"
#include "indri/ScoredExtentResult.hpp"
#include "indri/ParsedDocument.hpp"
#include "indri/IndexEnvironment.hpp"
#include "indri/Parameters.hpp"
#include "indri/ConflationPattern.hpp"
#include "indri/ReformulateQuery.hpp"
#include "Exception.hpp"
#include <string>
#include <stdexcept>
#include "indri/TagList.hpp"
#include "indri_jni.h"
Classes
struct SWIG_JavaExceptions_t
struct jni_parseddocument_info
struct jni_parameters_info
struct jni_specification_info
Namespaces
namespace Swig
Defines
#define SWIGJAVA
#define SWIG_DIRECTORS
#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
Enumerations
enum SWIG_JavaExceptionCodes {
SWIG_JavaOutOfMemoryError = 1, SWIG_JavaIOException, SWIG_JavaRuntimeException, SWIG_JavaIndexOutOfBoundsException,
SWIG_JavaArithmeticException, SWIG_JavaIllegalArgumentException, SWIG_JavaNullPointerException, SWIG_JavaDirectorPureVirtual,
SWIG_JavaUnknownError
}
Functions
static void SWIGUNUSED SWIG_JavaThrowException (JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg)
SWIGINTERN void SWIG_JavaException (JNIEnv *jenv, int code, const char *msg)
jobjectArray java_build_scoredextentresult (JNIEnv *jenv, const std::vector< indri::api::ScoredExtentResult > &input)
void parseddocument_init (JNIEnv *jenv, jni_parseddocument_info &info)
jobject parseddocument_copy (JNIEnv *jenv, jni_parseddocument_info &info, indri::api::ParsedDocument *doc)
jobject java_build_queryannotationnode (indri::api::QueryAnnotationNode *in, JNIEnv *jenv, jclass qanClazz, jmethodID qanConst)
void java_parameters_map (JNIEnv *jenv, jni_parameters_info &info, indri::api::Parameters p, jobject obj)
void java_parameters_array_of_maps (JNIEnv *jenv, jni_parameters_info &info, indri::api::Parameters p, const std::string &key, jobjectArray array)
void java_parameters_init (JNIEnv *jenv, jni_parameters_info &info)
void java_parameters_array_of_strings (JNIEnv *jenv, jni_parameters_info &info, indri::api::Parameters p, const std::string &key, jobjectArray array)
jobject documentvector_copy (JNIEnv *jenv, indri::api::DocumentVector *vec)
void print_info (jni_specification_info &info)
void specification_init (JNIEnv *jenv, jni_specification_info &info)
jobjectArray string_vector_copy (JNIEnv *jenv, std::vector< std::string > &vec)
jobject specification_copy (JNIEnv *jenv, jni_specification_info &info, indri::parse::FileClassEnvironmentFactory::Specification *thisSpec)
void copy_to_string (JNIEnv *jenv, jstring src, std::string &target)
void copy_to_string_vector (JNIEnv *jenv, jobjectArray src, std::vector< std::string > &target)
void copy_to_map (JNIEnv *jenv, jobject src, std::map< indri::parse::ConflationPattern *, std::string > &map)
jobject queryresults_copy (JNIEnv *jenv, indri::api::QueryResults &results)
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_QueryAnnotation_1getQueryTree (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_QueryAnnotation_1getAnnotations (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryAnnotation_1getResults (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1QueryAnnotation (JNIEnv *jenv, jclass jcls)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1QueryAnnotation (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1QueryEnvironment (JNIEnv *jenv, jclass jcls)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1addServer (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1addIndex (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeServer (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeIndex (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1close (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setMemory (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setScoringRules (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setStopwords (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jintArray jarg3, jint jarg4)
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_12 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jintArray jarg3, jint jarg4)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2, jstring jarg3)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2, jstring jarg3)
SWIGEXPORT jintArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentIDsFromMetadata (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termFieldCount (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1fieldList (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentVectors (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2)
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentLength (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setFormulationParameters (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1reformulateQuery (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemTerm (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCountUnique (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemCount (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemFieldCount (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentStemCount (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1QueryEnvironment (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1QueryExpander (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3, jboolean jarg4)
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3)
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_QueryExpander_1expand (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1RMExpander (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_RMExpander_1expand (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1RMExpander (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1PonteExpander (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_PonteExpander_1expand (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1PonteExpander (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1IndexStatus (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexStatus_1status (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jstring jarg4, jint jarg5, jint jarg6)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1IndexStatus (JNIEnv *jenv, jclass jcls)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexStatus_1director_1connect (JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jswig_mem_own, jboolean jweak_global)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexStatus_1change_1ownership (JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jtake_or_release)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1IndexEnvironment (JNIEnv *jenv, jclass jcls)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1IndexEnvironment (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setDocumentRoot (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setAnchorTextPath (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetMetadataPath (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetAnnotationsPath (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4, jstring jarg5, jstring jarg6, jstring jarg7, jstring jarg8, jobjectArray jarg9, jobjectArray jarg10, jobjectArray jarg11, jobjectArray jarg12, jobjectArray jarg13)
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1deleteDocument (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setIndexedFields (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3, jstring jarg4)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOrdinalField (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setParentalField (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMetadataIndexedFields (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2, jobjectArray jarg3)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStopwords (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStemmer (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMemory (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNormalization (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStoreDocs (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1close (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jobjectArray jarg4)
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11 (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jobjectArray jarg4, jobjectArray jarg5)
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsIndexed (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsSeen (JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_RMExpander_1SWIGUpcast (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_PonteExpander_1SWIGUpcast (JNIEnv *jenv, jclass jcls, jlong jarg1)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_swig_1module_1init (JNIEnv *jenv, jclass jcls)
Variables
static jclass Swig::jclass_indriJNI = NULL
static jmethodID Swig::director_methids [1]
Define Documentation
#define SWIG_AttributeError -11
#define SWIG_contract_assert (nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else
#define SWIG_DIRECTORS
#define SWIG_DivisionByZero -6
#define SWIG_IndexError -4
#define SWIG_IOError -2
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define SWIG_OverflowError -7
#define SWIG_RuntimeError -3
#define SWIG_SyntaxError -8
#define SWIG_SystemError -10
#define SWIG_TypeError -5
#define SWIG_UnknownError -1
#define SWIG_ValueError -9
#define SWIGJAVA
Enumeration Type Documentation
enum SWIG_JavaExceptionCodes
Enumerator:
SWIG_JavaOutOfMemoryError
SWIG_JavaIOException
SWIG_JavaRuntimeException
SWIG_JavaIndexOutOfBoundsException
SWIG_JavaArithmeticException
SWIG_JavaIllegalArgumentException
SWIG_JavaNullPointerException
SWIG_JavaDirectorPureVirtual
SWIG_JavaUnknownError
Function Documentation
void copy_to_map (JNIEnv * jenv, jobject src, std::map< indri::parse::ConflationPattern *, std::string > & map)
References indri::parse::ConflationPattern::attribute_name, indri::parse::ConflationPattern::tag_name, and indri::parse::ConflationPattern::value.
Referenced by Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11().
void copy_to_string (JNIEnv * jenv, jstring src, std::string & target)
Referenced by copy_to_string_vector(), and Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11().
void copy_to_string_vector (JNIEnv * jenv, jobjectArray src, std::vector< std::string > & target)
References copy_to_string().
Referenced by Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11().
jobject documentvector_copy (JNIEnv * jenv, indri::api::DocumentVector * vec)
References indri::api::DocumentVector::fields(), indri::api::DocumentVector::positions(), and indri::api::DocumentVector::stems().
Referenced by Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentVectors().
jobject java_build_queryannotationnode (indri::api::QueryAnnotationNode * in, JNIEnv * jenv, jclass qanClazz, jmethodID qanConst)
References indri::api::QueryAnnotationNode::children, indri::api::QueryAnnotationNode::name, indri::api::QueryAnnotationNode::queryText, and indri::api::QueryAnnotationNode::type.
Referenced by Java_lemurproject_indri_indriJNI_QueryAnnotation_1getQueryTree().
jobjectArray java_build_scoredextentresult (JNIEnv * jenv, const std::vector< indri::api::ScoredExtentResult > & input)
Referenced by Java_lemurproject_indri_indriJNI_QueryAnnotation_1getResults(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_10(), and Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_11().
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1IndexEnvironment (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1IndexStatus (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1PonteExpander (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1QueryAnnotation (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1QueryEnvironment (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1QueryExpander (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_delete_1RMExpander (JNIEnv * jenv, jclass jcls, jlong jarg1)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jstring jarg4, jstring jarg5, jstring jarg6, jstring jarg7, jstring jarg8, jobjectArray jarg9, jobjectArray jarg10, jobjectArray jarg11, jobjectArray jarg12, jobjectArray jarg13)
References indri::parse::ConflationPattern::attribute_name, SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), SWIG_RuntimeError, indri::parse::ConflationPattern::tag_name, and indri::parse::ConflationPattern::value.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
References indri::parse::FileClassEnvironmentFactory::Specification::conflations, jni_specification_info::conflationsField, copy_to_map(), copy_to_string(), copy_to_string_vector(), indri::parse::FileClassEnvironmentFactory::Specification::endDocTag, jni_specification_info::endDocTagField, indri::parse::FileClassEnvironmentFactory::Specification::endMetadataTag, jni_specification_info::endMetadataTagField, indri::parse::FileClassEnvironmentFactory::Specification::exclude, jni_specification_info::excludeField, indri::parse::FileClassEnvironmentFactory::Specification::include, jni_specification_info::includeField, indri::parse::FileClassEnvironmentFactory::Specification::index, jni_specification_info::indexField, indri::parse::FileClassEnvironmentFactory::Specification::iterator, jni_specification_info::iteratorField, indri::parse::FileClassEnvironmentFactory::Specification::metadata, jni_specification_info::metadataField, indri::parse::FileClassEnvironmentFactory::Specification::name, jni_specification_info::nameField, indri::parse::FileClassEnvironmentFactory::Specification::parser, jni_specification_info::parserField, specification_init(), indri::parse::FileClassEnvironmentFactory::Specification::startDocTag, jni_specification_info::startDocTagField, SWIG_JavaException(), SWIG_RuntimeError, indri::parse::FileClassEnvironmentFactory::Specification::tokenizer, and jni_specification_info::tokenizerField.
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
References indri::parse::TermExtent::begin, jni_parseddocument_info::beginField, jni_parseddocument_info::byteArrayClazz, indri::api::ParsedDocument::content, jni_parseddocument_info::contentField, indri::api::ParsedDocument::contentLength, indri::parse::TermExtent::end, jni_parseddocument_info::endField, indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::api::ParsedDocument::metadata, jni_parseddocument_info::metadataField, parseddocument_init(), indri::utility::Buffer::position(), indri::api::ParsedDocument::positions, jni_parseddocument_info::positionsField, indri::utility::greedy_vector< _Type, _Count >::push_back(), jni_parseddocument_info::stringClazz, SWIG_JavaException(), SWIG_RuntimeError, indri::api::ParsedDocument::terms, jni_parseddocument_info::termsField, indri::api::ParsedDocument::text, jni_parseddocument_info::textField, indri::api::ParsedDocument::textLength, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jobjectArray jarg4)
References indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::utility::Buffer::position(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), SWIG_RuntimeError, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3, jobjectArray jarg4, jobjectArray jarg5)
References indri::parse::TagList::addTag(), indri::parse::TagList::endTag(), indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::size(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), SWIG_RuntimeError, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, indri::utility::Buffer::write(), and indri::parse::TagList::writeTagList().
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1close (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1deleteDocument (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsIndexed (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References indri::api::IndexEnvironment::documentsIndexed(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsSeen (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References indri::api::IndexEnvironment::documentsSeen(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References specification_copy(), specification_init(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jlong jarg3, jobject jarg3_)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setAnchorTextPath (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setDocumentRoot (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setIndexedFields (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMemory (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMetadataIndexedFields (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2, jobjectArray jarg3)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNormalization (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3, jstring jarg4)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetAnnotationsPath (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetMetadataPath (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOrdinalField (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setParentalField (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jboolean jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStemmer (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStopwords (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStoreDocs (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexStatus_1change_1ownership (JNIEnv * jenv, jclass jcls, jobject jself, jlong objarg, jboolean jtake_or_release)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexStatus_1director_1connect (JNIEnv * jenv, jclass jcls, jobject jself, jlong objarg, jboolean jswig_mem_own, jboolean jweak_global)
References SwigDirector_IndexStatus::swig_connect_director().
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_IndexStatus_1status (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jstring jarg3, jstring jarg4, jint jarg5, jint jarg6)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1IndexEnvironment (JNIEnv * jenv, jclass jcls)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1IndexStatus (JNIEnv * jenv, jclass jcls)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1PonteExpander (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
References java_parameters_init(), java_parameters_map(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1QueryAnnotation (JNIEnv * jenv, jclass jcls)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1QueryEnvironment (JNIEnv * jenv, jclass jcls)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_new_1RMExpander (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
References java_parameters_init(), java_parameters_map(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_PonteExpander_1expand (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
References indri::api::ScoredExtentResult::begin, indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::api::ScoredExtentResult::number, indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, indri::api::ScoredExtentResult::score, SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_PonteExpander_1SWIGUpcast (JNIEnv * jenv, jclass jcls, jlong jarg1)
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_QueryAnnotation_1getAnnotations (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_QueryAnnotation_1getQueryTree (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References java_build_queryannotationnode(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryAnnotation_1getResults (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References java_build_scoredextentresult(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1addIndex (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1addServer (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1close (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References indri::api::QueryEnvironment::documentCount(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jintArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentIDsFromMetadata (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
References input(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jint JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentLength (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2)
References indri::api::QueryEnvironment::documentLength(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2, jstring jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2, jstring jarg3)
References indri::api::ScoredExtentResult::begin, indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::api::ScoredExtentResult::number, indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, indri::api::ScoredExtentResult::score, SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2)
References parseddocument_copy(), parseddocument_init(), jni_parseddocument_info::pdClazz, SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
References indri::api::ScoredExtentResult::begin, indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::api::ScoredExtentResult::number, indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, parseddocument_copy(), parseddocument_init(), jni_parseddocument_info::pdClazz, indri::api::ScoredExtentResult::score, SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
References parseddocument_copy(), parseddocument_init(), jni_parseddocument_info::pdClazz, SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentStemCount (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentVectors (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2)
References documentvector_copy(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jdouble JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
References java_build_scoredextentresult(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References java_build_scoredextentresult(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1fieldList (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1reformulateQuery (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeIndex (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeServer (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jintArray jarg3, jint jarg4)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3)
References java_build_scoredextentresult(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jintArray jarg3, jint jarg4)
References java_build_scoredextentresult(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobject JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_12 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
References indri::api::QueryRequest::formulators, indri::api::QueryRequest::metadata, indri::api::QueryRequest::options, indri::api::QueryRequest::query, queryresults_copy(), indri::api::QueryRequest::resultsRequested, indri::api::QueryRequest::startNum, SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setFormulationParameters (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2)
References java_parameters_init(), java_parameters_map(), SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setMemory (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setScoringRules (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1setStopwords (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobjectArray jarg2)
References SWIG_JavaException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemCount (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemFieldCount (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemTerm (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References SWIG_JavaException(), SWIG_RuntimeError, and indri::api::QueryEnvironment::termCount().
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCountUnique (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_)
References SWIG_JavaException(), SWIG_RuntimeError, and indri::api::QueryEnvironment::termCountUnique().
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_QueryEnvironment_1termFieldCount (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jstring jarg3)
References SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_QueryExpander_1expand (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
References indri::api::ScoredExtentResult::begin, indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::api::ScoredExtentResult::number, indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, indri::api::ScoredExtentResult::score, SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_10 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3, jboolean jarg4)
References java_build_scoredextentresult(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jobjectArray JNICALL Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_11 (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jint jarg3)
References java_build_scoredextentresult(), SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jstring JNICALL Java_lemurproject_indri_indriJNI_RMExpander_1expand (JNIEnv * jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2, jobjectArray jarg3)
References indri::api::ScoredExtentResult::begin, indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::api::ScoredExtentResult::number, indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, indri::api::ScoredExtentResult::score, SWIG_JavaException(), SWIG_JavaNullPointerException, SWIG_JavaThrowException(), and SWIG_RuntimeError.
SWIGEXPORT jlong JNICALL Java_lemurproject_indri_indriJNI_RMExpander_1SWIGUpcast (JNIEnv * jenv, jclass jcls, jlong jarg1)
SWIGEXPORT void JNICALL Java_lemurproject_indri_indriJNI_swig_1module_1init (JNIEnv * jenv, jclass jcls)
References Swig::director_methids, and Swig::jclass_indriJNI.
void java_parameters_array_of_maps (JNIEnv * jenv, jni_parameters_info & info, indri::api::Parameters p, const std::string & key, jobjectArray array)
References java_parameters_map().
Referenced by java_parameters_map().
void java_parameters_array_of_strings (JNIEnv * jenv, jni_parameters_info & info, indri::api::Parameters p, const std::string & key, jobjectArray array)
References indri::api::Parameters::append().
Referenced by java_parameters_map().
void java_parameters_init (JNIEnv * jenv, jni_parameters_info & info)
References jni_parameters_info::arrayOfMaps, jni_parameters_info::arrayOfString, jni_parameters_info::mapClazz, jni_parameters_info::setClazz, and jni_parameters_info::stringClazz.
Referenced by Java_lemurproject_indri_indriJNI_new_1PonteExpander(), Java_lemurproject_indri_indriJNI_new_1RMExpander(), and Java_lemurproject_indri_indriJNI_QueryEnvironment_1setFormulationParameters().
void java_parameters_map (JNIEnv * jenv, jni_parameters_info & info, indri::api::Parameters p, jobject obj)
References indri::api::Parameters::append(), jni_parameters_info::arrayOfMaps, jni_parameters_info::arrayOfString, java_parameters_array_of_maps(), java_parameters_array_of_strings(), jni_parameters_info::mapClazz, indri::api::Parameters::set(), jni_parameters_info::stringClazz, SWIG_JavaException(), and SWIG_RuntimeError.
Referenced by Java_lemurproject_indri_indriJNI_new_1PonteExpander(), Java_lemurproject_indri_indriJNI_new_1RMExpander(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setFormulationParameters(), and java_parameters_array_of_maps().
jobject parseddocument_copy (JNIEnv * jenv, jni_parseddocument_info & info, indri::api::ParsedDocument * doc)
References indri::utility::greedy_vector< _Type, _Count >::begin(), jni_parseddocument_info::contentField, indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::ParsedDocument::getContent(), indri::parse::MetadataPair::key, jni_parseddocument_info::mapClazz, jni_parseddocument_info::mapConstructor, indri::api::ParsedDocument::metadata, jni_parseddocument_info::metadataField, jni_parseddocument_info::pdClazz, jni_parseddocument_info::pdConstructor, indri::api::ParsedDocument::positions, jni_parseddocument_info::positionsField, jni_parseddocument_info::putMethod, indri::utility::greedy_vector< _Type, _Count >::size(), jni_parseddocument_info::stringClazz, jni_parseddocument_info::teClazz, jni_parseddocument_info::teConstructor, indri::api::ParsedDocument::terms, jni_parseddocument_info::termsField, indri::api::ParsedDocument::text, jni_parseddocument_info::textField, indri::parse::MetadataPair::value, and indri::parse::MetadataPair::valueLength.
Referenced by Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_11(), and Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata().
void parseddocument_init (JNIEnv * jenv, jni_parseddocument_info & info)
References jni_parseddocument_info::beginField, jni_parseddocument_info::byteArrayClazz, jni_parseddocument_info::contentField, jni_parseddocument_info::endField, jni_parseddocument_info::mapClazz, jni_parseddocument_info::mapConstructor, jni_parseddocument_info::metadataField, jni_parseddocument_info::pdClazz, jni_parseddocument_info::pdConstructor, jni_parseddocument_info::positionsField, jni_parseddocument_info::putMethod, jni_parseddocument_info::stringClazz, jni_parseddocument_info::teClazz, jni_parseddocument_info::teConstructor, jni_parseddocument_info::termsField, and jni_parseddocument_info::textField.
Referenced by Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_11(), and Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata().
void print_info (jni_specification_info & info)
References jni_specification_info::conflationsField, jni_specification_info::endDocTagField, jni_specification_info::endMetadataTagField, jni_specification_info::excludeField, jni_specification_info::includeField, jni_specification_info::indexField, jni_specification_info::iteratorField, jni_specification_info::mapClazz, jni_specification_info::mapConstructor, jni_specification_info::metadataField, jni_specification_info::nameField, jni_specification_info::parserField, jni_specification_info::putMethod, jni_specification_info::specClazz, jni_specification_info::specConstructor, jni_specification_info::startDocTagField, and jni_specification_info::tokenizerField.
jobject queryresults_copy (JNIEnv * jenv, indri::api::QueryResults & results)
References indri::api::QueryResults::documentsTime, indri::api::QueryResults::estimatedMatches, indri::api::QueryResults::executeTime, indri::api::MetadataPair::key, indri::api::QueryResults::parseTime, indri::api::QueryResults::results, and indri::api::MetadataPair::value.
Referenced by Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_12().
jobject specification_copy (JNIEnv * jenv, jni_specification_info & info, indri::parse::FileClassEnvironmentFactory::Specification * thisSpec)
References indri::parse::ConflationPattern::attribute_name, indri::parse::FileClassEnvironmentFactory::Specification::conflations, jni_specification_info::conflationsField, indri::parse::FileClassEnvironmentFactory::Specification::endDocTag, jni_specification_info::endDocTagField, indri::parse::FileClassEnvironmentFactory::Specification::endMetadataTag, jni_specification_info::endMetadataTagField, indri::parse::FileClassEnvironmentFactory::Specification::exclude, jni_specification_info::excludeField, indri::parse::FileClassEnvironmentFactory::Specification::include, jni_specification_info::includeField, indri::parse::FileClassEnvironmentFactory::Specification::index, jni_specification_info::indexField, indri::parse::FileClassEnvironmentFactory::Specification::iterator, jni_specification_info::iteratorField, jni_specification_info::mapClazz, jni_specification_info::mapConstructor, indri::parse::FileClassEnvironmentFactory::Specification::metadata, jni_specification_info::metadataField, indri::parse::FileClassEnvironmentFactory::Specification::name, jni_specification_info::nameField, indri::parse::FileClassEnvironmentFactory::Specification::parser, jni_specification_info::parserField, jni_specification_info::putMethod, jni_specification_info::specClazz, jni_specification_info::specConstructor, indri::parse::FileClassEnvironmentFactory::Specification::startDocTag, jni_specification_info::startDocTagField, string_vector_copy(), indri::parse::ConflationPattern::tag_name, indri::parse::FileClassEnvironmentFactory::Specification::tokenizer, jni_specification_info::tokenizerField, and indri::parse::ConflationPattern::value.
Referenced by Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec().
void specification_init (JNIEnv * jenv, jni_specification_info & info)
References jni_specification_info::conflationsField, jni_specification_info::endDocTagField, jni_specification_info::endMetadataTagField, jni_specification_info::excludeField, jni_specification_info::includeField, jni_specification_info::indexField, jni_specification_info::iteratorField, jni_specification_info::mapClazz, jni_specification_info::mapConstructor, jni_specification_info::metadataField, jni_specification_info::nameField, jni_specification_info::parserField, jni_specification_info::putMethod, jni_specification_info::specClazz, jni_specification_info::specConstructor, jni_specification_info::startDocTagField, and jni_specification_info::tokenizerField.
Referenced by Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11(), and Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec().
jobjectArray string_vector_copy (JNIEnv * jenv, std::vector< std::string > & vec)
Referenced by specification_copy().
SWIGINTERN void SWIG_JavaException (JNIEnv * jenv, int code, const char * msg)
References SWIG_DivisionByZero, SWIG_IndexError, SWIG_IOError, SWIG_JavaArithmeticException, SWIG_JavaIllegalArgumentException, SWIG_JavaIndexOutOfBoundsException, SWIG_JavaIOException, SWIG_JavaOutOfMemoryError, SWIG_JavaRuntimeException, SWIG_JavaThrowException(), SWIG_JavaUnknownError, SWIG_MemoryError, SWIG_OverflowError, SWIG_RuntimeError, SWIG_SyntaxError, SWIG_SystemError, SWIG_TypeError, SWIG_UnknownError, and SWIG_ValueError.
Referenced by Java_lemurproject_indri_indriJNI_delete_1IndexEnvironment(), Java_lemurproject_indri_indriJNI_delete_1IndexStatus(), Java_lemurproject_indri_indriJNI_delete_1PonteExpander(), Java_lemurproject_indri_indriJNI_delete_1QueryAnnotation(), Java_lemurproject_indri_indriJNI_delete_1QueryEnvironment(), Java_lemurproject_indri_indriJNI_delete_1QueryExpander(), Java_lemurproject_indri_indriJNI_delete_1RMExpander(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addParsedDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1close(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1deleteDocument(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsIndexed(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1documentsSeen(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setAnchorTextPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setDocumentRoot(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setIndexedFields(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMemory(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setMetadataIndexedFields(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNormalization(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetAnnotationsPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetMetadataPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOrdinalField(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setParentalField(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStemmer(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStopwords(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStoreDocs(), Java_lemurproject_indri_indriJNI_IndexStatus_1status(), Java_lemurproject_indri_indriJNI_new_1IndexEnvironment(), Java_lemurproject_indri_indriJNI_new_1IndexStatus(), Java_lemurproject_indri_indriJNI_new_1PonteExpander(), Java_lemurproject_indri_indriJNI_new_1QueryAnnotation(), Java_lemurproject_indri_indriJNI_new_1QueryEnvironment(), Java_lemurproject_indri_indriJNI_new_1RMExpander(), Java_lemurproject_indri_indriJNI_PonteExpander_1expand(), Java_lemurproject_indri_indriJNI_QueryAnnotation_1getAnnotations(), Java_lemurproject_indri_indriJNI_QueryAnnotation_1getQueryTree(), Java_lemurproject_indri_indriJNI_QueryAnnotation_1getResults(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1addIndex(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1addServer(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1close(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentIDsFromMetadata(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentLength(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documents_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentStemCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentVectors(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1fieldList(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1reformulateQuery(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeIndex(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeServer(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_12(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setFormulationParameters(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setMemory(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setScoringRules(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1setStopwords(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemFieldCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemTerm(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCountUnique(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termFieldCount(), Java_lemurproject_indri_indriJNI_QueryExpander_1expand(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_RMExpander_1expand(), and java_parameters_map().
static void SWIGUNUSED SWIG_JavaThrowException (JNIEnv * jenv, SWIG_JavaExceptionCodes code, const char * msg) [static]
References SWIG_JavaExceptions_t::code, SWIG_JavaExceptions_t::java_exception, SWIG_JavaArithmeticException, SWIG_JavaDirectorPureVirtual, SWIG_JavaIllegalArgumentException, SWIG_JavaIndexOutOfBoundsException, SWIG_JavaIOException, SWIG_JavaNullPointerException, SWIG_JavaOutOfMemoryError, SWIG_JavaRuntimeException, and SWIG_JavaUnknownError.
Referenced by Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFile_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addFileClass_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1create_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1getFileClassSpec(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1open_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setAnchorTextPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setDocumentRoot(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setNumericField_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetAnnotationsPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOffsetMetadataPath(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setOrdinalField(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setParentalField(), Java_lemurproject_indri_indriJNI_IndexEnvironment_1setStemmer(), Java_lemurproject_indri_indriJNI_IndexStatus_1status(), Java_lemurproject_indri_indriJNI_PonteExpander_1expand(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1addIndex(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1addServer(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentExpressionCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentIDsFromMetadata(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentMetadata_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentsFromMetadata(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1documentStemCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1expressionList_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1reformulateQuery(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeIndex(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1removeServer(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runAnnotatedQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1runQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemFieldCount(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1stemTerm(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termCount_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_QueryEnvironment_1termFieldCount(), Java_lemurproject_indri_indriJNI_QueryExpander_1expand(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_10(), Java_lemurproject_indri_indriJNI_QueryExpander_1runExpandedQuery_1_1SWIG_11(), Java_lemurproject_indri_indriJNI_RMExpander_1expand(), and SWIG_JavaException().