Indri: indri::infnet Namespace Reference
indri::infnet Namespace Reference
Inference net and inference net node classes.
Classes
class Annotator
class BeliefNode
class BooleanAndNode
class CachedFrequencyBeliefNode
class ContextCountAccumulator
class ContextInclusionAndNode
class ContextSimpleCountAccumulator
class DocListIteratorNode
class DocumentStructureHolderNode
class EvaluatorNode
class ExtentAndNode
class ExtentChildNode
class ExtentDescendantNode
class ExtentEnforcementNode
class ExtentInsideNode
class ExtentOrNode
class ExtentParentNode
class ExtentRestrictionNode
class FieldBetweenNode
class FieldEqualsNode
class FieldGreaterNode
class FieldIteratorNode
class FieldLessNode
class FieldWildcardNode
class FilterNode
class FilterRejectNode
class FilterRequireNode
class FixedPassageNode
class InferenceNetwork
class InferenceNetworkBuilder
class InferenceNetworkNode
class LengthPriorNode
class ListAccumulator
class ListBeliefNode
class ListIteratorNode
class MaxNode
class NestedExtentInsideNode
class NestedListBeliefNode
class NotNode
class NullListNode
class NullScorerNode
class OrderedWindowNode
class OrNode
class PlusNode
class PriorNode
class ScoredExtentAccumulator
class ShrinkageBeliefNode
class SkippingCapableNode
class TermFrequencyBeliefNode
class UnorderedWindowNode
class WeightedAndNode
class WeightedExtentOrNode
class WeightedSumNode
class WPlusNode
Functions
bool UWNodeChildLess (indri::infnet::ListIteratorNode *_child1, indri::infnet::ListIteratorNode *_child2)
Detailed Description
Inference net and inference net node classes.
Function Documentation
bool indri::infnet::UWNodeChildLess (indri::infnet::ListIteratorNode * _child1, indri::infnet::ListIteratorNode * _child2) [inline]
References indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::infnet::UnorderedWindowNode::prepare().