Indri: indri::atomic Namespace Reference
indri::atomic Namespace Reference
Atomic actions for thread support.
Classes
class ref_ptr
Typedefs
typedef _Atomic_word value_type
Functions
void increment (value_type &variable)
void decrement (value_type &variable)
Detailed Description
Atomic actions for thread support.
Typedef Documentation
typedef _Atomic_word indri::atomic::value_type
Function Documentation
void indri::atomic::decrement (value_type & variable) [inline]
Referenced by indri::atomic::ref_ptr< index_vector >::_removeRef().
void indri::atomic::increment (value_type & variable) [inline]
Referenced by indri::atomic::ref_ptr< index_vector >::_addRef(), indri::collection::Repository::_countDocumentAdd(), indri::parse::KrovetzStemmerTransformation::_processTerms(), indri::parse::ArabicStemmerTransformation::_processTerms(), indri::collection::Repository::countQuery(), and QueryParser::extentRestriction().