Indri: indri::utility Namespace Reference
indri::utility Namespace Reference
Utility classes for indri components.
Classes
class Buffer
class VectorDeleter
class StackDeleter
class GenericHash
class GenericComparator
class GenericHash< const char * >
class GenericComparator< const char * >
class GenericHash< std::string >
class GenericComparator< std::string >
struct HashBucket
class HashTableIterator
class HashTable
class IndriTimer
class RegionAllocator
class RVLCompressStream
class RVLDecompressStream
class greedy_vector
class count_iterator
Functions
template<typename VectorType >
void delete_vector_contents (std::vector< VectorType > &vector)
template<typename MapKey , typename MapValue >
void delete_map_contents (std::map< MapKey, MapValue * > &mp)
Detailed Description
Utility classes for indri components.
Function Documentation
template<typename MapKey , typename MapValue > void indri::utility::delete_map_contents (std::map< MapKey, MapValue * > & mp) [inline]
Referenced by indri::api::Parameters::operator=(), and indri::lang::Packer::~Packer().
template<typename VectorType > void indri::utility::delete_vector_contents (std::vector< VectorType > & vector) [inline]
Referenced by indri::collection::Repository::close(), indri::query::QueryExpander::getVocabulary(), main(), indri::api::Parameters::operator=(), indri::index::IndexWriter::write(), indri::lang::ApplyCopiers< T, NodeType >::~ApplyCopiers(), indri::file::BulkTreeWriter::~BulkTreeWriter(), indri::lang::DagCopier::~DagCopier(), indri::lang::ExtentRestrictionModelAnnotatorCopier::~ExtentRestrictionModelAnnotatorCopier(), indri::lang::ListCache::~ListCache(), indri::utility::RegionAllocator::~RegionAllocator(), indri::lang::SimpleCopier::~SimpleCopier(), indri::index::TermBitmap::~TermBitmap(), indri::lang::UnnecessaryNodeRemoverCopier::~UnnecessaryNodeRemoverCopier(), and indri::lang::WeightFoldingCopier::~WeightFoldingCopier().