Indri: pagerank.cpp File Reference
pagerank.cpp File Reference
#include <time.h>
#include "indri/Parameters.hpp"
#include "indri/Repository.hpp"
#include "indri/LocalQueryServer.hpp"
#include "lemur/Exception.hpp"
#include "indri/PageRank.hpp"
#include <cstring>
#include <iostream>
Functions
void require_parameter (const char *name, indri::api::Parameters &p)
void convertPriors (const std::string &dest, const std::string &priorFile, int numDocs)
int main (int argc, char **argv)
Function Documentation
void convertPriors (const std::string & dest, const std::string & priorFile, int numDocs)
convert galago pagerank score (scoreOrder sorted) to log probability for indri makeprior input
Referenced by main().
int main (int argc, char ** argv)
References indri::parse::PageRank::computePageRank(), convertPriors(), indri::api::Parameters::get(), indri::parse::PageRank::indexPageRank(), INDRI_DISTRIBUTION, indri::api::Parameters::instance(), indri::api::Parameters::loadCommandLine(), require_parameter(), indri::parse::PageRank::writePriors(), indri::parse::PageRank::writeRanks(), and indri::parse::PageRank::writeRaw().
void require_parameter (const char * name, indri::api::Parameters & p)
References indri::api::Parameters::exists().