Indri: QueryEnvironment.cpp File Reference
QueryEnvironment.cpp File Reference
#include "indri/indri-platform.h"
#include "indri/QueryEnvironment.hpp"
#include "indri/CompressedCollection.hpp"
#include <vector>
#include <queue>
#include "indri/delete_range.hpp"
#include "indri/InferenceNetwork.hpp"
#include "indri/QuerySpec.hpp"
#include "indri/ScoredExtentResult.hpp"
#include "indri/LocalQueryServer.hpp"
#include "indri/NetworkServerProxy.hpp"
#include "indri/NetworkStream.hpp"
#include "indri/NetworkMessageStream.hpp"
#include "indri/QueryParserFactory.hpp"
#include "indri/DagCopier.hpp"
#include "indri/InferenceNetworkBuilder.hpp"
#include "indri/RawScorerNodeExtractor.hpp"
#include "indri/ContextSimpleCountCollectorCopier.hpp"
#include "indri/TreePrinterWalker.hpp"
#include "indri/ContextCountGraphCopier.hpp"
#include "indri/SmoothingAnnotatorWalker.hpp"
#include "indri/ExtentRestrictionModelAnnotatorCopier.hpp"
#include "indri/Packer.hpp"
#include "indri/Unpacker.hpp"
#include "indri/QueryAnnotation.hpp"
#include "indri/XMLReader.hpp"
#include "indri/IndriTimer.hpp"
#include "indri/IndexEnvironment.hpp"
#include "indri/Index.hpp"
#include <set>
#include <map>
#include "indri/Appliers.hpp"
#include "indri/SnippetBuilder.hpp"
#include "indri/VocabularyIterator.hpp"
#include "indri/QueryTFWalker.hpp"
Classes
class indri::lang::Printer
Namespaces
namespace indri
namespaces within the indri system
namespace indri::lang
Indri query language nodes and support classes.
Defines
#define INIT_TIMER
#define PRINT_TIMER(s)
Functions
void qenv_scatter_document_ids (const std::vector< DOCID_T > &documentIDs, std::vector< std::vector< DOCID_T > > &docIDLists, std::vector< std::vector< DOCID_T > > &docIDPositions, int serverCount)
template<class _ResponseType , class _ResultType >
void qenv_gather_document_results (const std::vector< std::vector< DOCID_T > > &docIDLists, const std::vector< std::vector< DOCID_T > > &docIDPositions, indri::utility::greedy_vector< _ResponseType > &responses, std::vector< _ResultType > &results)
static void _getRawNodes (std::set< std::string > &nodeTerms, const indri::api::QueryAnnotationNode *node)
Define Documentation
#define INIT_TIMER
#define PRINT_TIMER (s)
Function Documentation
static void _getRawNodes (std::set< std::string > & nodeTerms, const indri::api::QueryAnnotationNode * node) [static]
References indri::api::QueryAnnotationNode::children, indri::api::QueryAnnotationNode::queryText, and indri::api::QueryAnnotationNode::type.
Referenced by indri::api::QueryEnvironment::runQuery().
template<class _ResponseType , class _ResultType > void qenv_gather_document_results (const std::vector< std::vector< DOCID_T > > & docIDLists, const std::vector< std::vector< DOCID_T > > & docIDPositions, indri::utility::greedy_vector< _ResponseType > & responses, std::vector< _ResultType > & results) [inline]
Referenced by indri::api::QueryEnvironment::pathNames().
void qenv_scatter_document_ids (const std::vector< DOCID_T > & documentIDs, std::vector< std::vector< DOCID_T > > & docIDLists, std::vector< std::vector< DOCID_T > > & docIDPositions, int serverCount)
Referenced by indri::api::QueryEnvironment::pathNames().