Indri: ReformulateQuery.cpp File Reference
reformulate/ReformulateQuery.cpp File Reference
#include <iostream>
#include <sstream>
#include "indri/QueryEnvironment.hpp"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References indri::api::Parameters::get(), indri::api::Parameters::instance(), indri::api::Parameters::loadCommandLine(), indri::api::QueryEnvironment::reformulateQuery(), indri::api::QueryEnvironment::setFormulationParameters(), and indri::api::Parameters::size().