Indri: RepositoryMaintenanceThread.cpp File Reference
RepositoryMaintenanceThread.cpp File Reference
#include "indri/RepositoryMaintenanceThread.hpp"
#include "indri/Repository.hpp"
#include "indri/ScopedLock.hpp"
#include <iostream>
Functions
static float maintenance_smoothed_load (indri::collection::Repository::Load &load)
static bool maintenance_should_merge (indri::collection::Repository::index_state &state, indri::collection::Repository::Load &documentLoad, indri::collection::Repository::Load &queryLoad, UINT64 lastThrashing)
static bool maintenance_should_trim (indri::collection::Repository::index_state &state, indri::collection::Repository::Load &documentLoad, indri::collection::Repository::Load &queryLoad, UINT64 lastThrashing)
Variables
const UINT64 TIME_DELAY = 10*1000*1000
const UINT64 SHORT_TIME_DELAY = 3*1000*1000
const UINT64 THRASHING_MERGE_DELAY = 300*1000*1000
const int MAXIMUM_INDEX_COUNT = 50
Function Documentation
static bool maintenance_should_merge (indri::collection::Repository::index_state & state, indri::collection::Repository::Load & documentLoad, indri::collection::Repository::Load & queryLoad, UINT64 lastThrashing) [static]
References maintenance_smoothed_load(), and THRASHING_MERGE_DELAY.
Referenced by indri::collection::RepositoryMaintenanceThread::work().
static bool maintenance_should_trim (indri::collection::Repository::index_state & state, indri::collection::Repository::Load & documentLoad, indri::collection::Repository::Load & queryLoad, UINT64 lastThrashing) [static]
References MAXIMUM_INDEX_COUNT.
Referenced by indri::collection::RepositoryMaintenanceThread::work().
static float maintenance_smoothed_load (indri::collection::Repository::Load & load) [static]
References indri::collection::Repository::Load::fifteen, indri::collection::Repository::Load::five, and indri::collection::Repository::Load::one.
Referenced by maintenance_should_merge().
Variable Documentation
const int MAXIMUM_INDEX_COUNT = 50
Referenced by maintenance_should_trim().
const UINT64 SHORT_TIME_DELAY = 3*1000*1000
Referenced by indri::collection::RepositoryMaintenanceThread::work().
const UINT64 THRASHING_MERGE_DELAY = 300*1000*1000
Referenced by maintenance_should_merge().
const UINT64 TIME_DELAY = 10*1000*1000
Referenced by indri::collection::RepositoryMaintenanceThread::initialize(), and indri::collection::RepositoryMaintenanceThread::work().