Indri: rmodel.cpp File Reference
rmodel.cpp File Reference
#include "indri/Parameters.hpp"
#include "indri/RelevanceModel.hpp"
Functions
static bool copy_parameters_to_string_vector (std::vector< std::string > &vec, indri::api::Parameters p, const std::string &parameterName)
static void open_indexes (indri::api::QueryEnvironment &environment, indri::api::Parameters &param)
static void printGrams (const std::string &query, const std::vector< indri::query::RelevanceModel::Gram * > &grams)
static void usage (indri::api::Parameters param)
int main (int argc, char **argv)
Function Documentation
static bool copy_parameters_to_string_vector (std::vector< std::string > & vec, indri::api::Parameters p, const std::string & parameterName) [static]
References indri::api::Parameters::exists(), and indri::api::Parameters::size().
Referenced by open_indexes().
int main (int argc, char ** argv)
References indri::query::RelevanceModel::generate(), indri::api::Parameters::get(), indri::query::RelevanceModel::getGrams(), indri::api::Parameters::instance(), indri::api::Parameters::loadCommandLine(), open_indexes(), printGrams(), indri::api::Parameters::size(), and usage().
static void open_indexes (indri::api::QueryEnvironment & environment, indri::api::Parameters & param) [static]
References indri::api::QueryEnvironment::addIndex(), indri::api::QueryEnvironment::addServer(), copy_parameters_to_string_vector(), indri::api::Parameters::exists(), indri::api::QueryEnvironment::setScoringRules(), and indri::api::Parameters::size().
Referenced by main().
static void printGrams (const std::string & query, const std::vector< indri::query::RelevanceModel::Gram * > & grams) [static]
Referenced by main().
static void usage (indri::api::Parameters param) [static]
References indri::api::Parameters::exists().