Indri: indri::index::WriterIndexContext::greater Struct Reference
indri::index::WriterIndexContext::greater Struct Reference
#include <IndexWriter.hpp>
Public Member Functions
bool operator() (const WriterIndexContext *const &one, const WriterIndexContext *const &two) const
Private Member Functions
int _compareTerms (const WriterIndexContext *const &one, const WriterIndexContext *const &two) const
int _compareDocuments (const WriterIndexContext *const &one, const WriterIndexContext *const &two) const
Private Attributes
indri::index::DocListFileIterator::iterator_greater _iterator_greater
Member Function Documentation
int indri::index::WriterIndexContext::greater::_compareDocuments (const WriterIndexContext *const & one, const WriterIndexContext *const & two) const [inline, private]
References indri::index::DocListFileIterator::currentEntry(), indri::index::DocListIterator::DocumentData::document, indri::index::WriterIndexContext::documentOffset, and indri::index::WriterIndexContext::iterator.
Referenced by operator()().
int indri::index::WriterIndexContext::greater::_compareTerms (const WriterIndexContext *const & one, const WriterIndexContext *const & two) const [inline, private]
References indri::index::DocListFileIterator::currentEntry(), and indri::index::WriterIndexContext::iterator.
Referenced by operator()().
bool indri::index::WriterIndexContext::greater::operator() (const WriterIndexContext *const & one, const WriterIndexContext *const & two) const [inline]
References _compareDocuments(), _compareTerms(), indri::index::DocListFileIterator::finished(), and indri::index::WriterIndexContext::iterator.
Member Data Documentation
indri::index::DocListFileIterator::iterator_greater indri::index::WriterIndexContext::greater::_iterator_greater [private]
The documentation for this struct was generated from the following file:
IndexWriter.hpp