Indri: SwigDirector_IndexStatus Struct Reference
SwigDirector_IndexStatus Struct Reference
#include <indri_csharp.h>
Public Types
typedef void(SWIGSTDCALL * SWIG_Callback0_t)(int, char *, char *, int, int)
Public Member Functions
SwigDirector_IndexStatus ()
virtual ~SwigDirector_IndexStatus ()
virtual void status (int code, std::string const &documentPath, std::string const &error, int documentsIndexed, int documentsSeen)
void swig_connect_director (SWIG_Callback0_t callbackstatus)
void swig_connect_director (JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global)
SwigDirector_IndexStatus (JNIEnv *jenv)
virtual ~SwigDirector_IndexStatus ()
virtual void status (int code, std::string const &documentPath, std::string const &error, int documentsIndexed, int documentsSeen)
bool swig_overrides (int n)
Protected Attributes
bool swig_override [1]
Private Member Functions
void swig_init_callbacks ()
Private Attributes
SWIG_Callback0_t swig_callbackstatus
Member Typedef Documentation
typedef void(SWIGSTDCALL* SwigDirector_IndexStatus::SWIG_Callback0_t)(int, char *, char *, int, int)
Constructor & Destructor Documentation
SwigDirector_IndexStatus::SwigDirector_IndexStatus ()
References swig_init_callbacks().
SwigDirector_IndexStatus::~SwigDirector_IndexStatus () [virtual]
SwigDirector_IndexStatus::SwigDirector_IndexStatus (JNIEnv * jenv)
virtual SwigDirector_IndexStatus::~SwigDirector_IndexStatus () [virtual]
Member Function Documentation
virtual void SwigDirector_IndexStatus::status (int code, std::string const & documentPath, std::string const & error, int documentsIndexed, int documentsSeen) [virtual]
Reimplemented from indri::api::IndexStatus.
void SwigDirector_IndexStatus::status (int code, std::string const & documentPath, std::string const & error, int documentsIndexed, int documentsSeen) [virtual]
Reimplemented from indri::api::IndexStatus.
References swig_callbackstatus, and SWIG_csharp_string_callback.
void SwigDirector_IndexStatus::swig_connect_director (JNIEnv * jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global)
References swig_override.
void SwigDirector_IndexStatus::swig_connect_director (SWIG_Callback0_t callbackstatus)
References swig_callbackstatus.
Referenced by CSharp_IndexStatus_director_connect(), and Java_lemurproject_indri_indriJNI_IndexStatus_1director_1connect().
void SwigDirector_IndexStatus::swig_init_callbacks () [private]
References swig_callbackstatus.
Referenced by SwigDirector_IndexStatus().
bool SwigDirector_IndexStatus::swig_overrides (int n) [inline]
References swig_override.
Member Data Documentation
SWIG_Callback0_t SwigDirector_IndexStatus::swig_callbackstatus [private]
Referenced by status(), swig_connect_director(), and swig_init_callbacks().
bool SwigDirector_IndexStatus::swig_override[1] [protected]
Referenced by swig_connect_director(), and swig_overrides().
The documentation for this struct was generated from the following files:
indri_csharp.h
indri_jni.h
indri_csharp.cpp
indri_jni.cpp