Indri: TermData.hpp File Reference
TermData.hpp File Reference
#include "indri/TermFieldStatistics.hpp"
#include <indri/greedy_vector>
#include "lemur/lemur-compat.hpp"
#include "indri/RVLCompressStream.hpp"
#include "indri/RVLDecompressStream.hpp"
Classes
struct indri::index::TermData
struct indri::index::TermData::term_less
Namespaces
namespace indri
namespaces within the indri system
namespace indri::index
index construction and interaction components
Functions
indri::index::TermData * termdata_construct (void *buffer, int fieldCount)
indri::index::TermData * termdata_create (int fieldCount)
void termdata_destruct (indri::index::TermData *termData, int fieldCount)
void termdata_delete (indri::index::TermData *termData, int fieldCount)
void termdata_clear (indri::index::TermData *termData, int fieldCount)
void termdata_merge (indri::index::TermData *termData, indri::index::TermData *merger, int fieldCount)
int termdata_size (int fieldCount)
void termdata_compress (indri::utility::RVLCompressStream &stream, indri::index::TermData *termData, int fieldCount)
void termdata_decompress (indri::utility::RVLDecompressStream &stream, indri::index::TermData *termData, int fieldCount)
Function Documentation
void termdata_clear (indri::index::TermData * termData, int fieldCount) [inline]
References indri::index::TermData::corpus, indri::index::TermFieldStatistics::documentCount, indri::index::TermData::fields, indri::index::TermFieldStatistics::lastCount, indri::index::TermFieldStatistics::lastDocument, indri::index::TermData::maxDocumentLength, indri::index::TermData::minDocumentLength, and indri::index::TermFieldStatistics::totalCount.
Referenced by indri::index::IndexWriter::_writeStatistics().
void termdata_compress (indri::utility::RVLCompressStream & stream, indri::index::TermData * termData, int fieldCount) [inline]
References indri::index::TermData::corpus, indri::index::TermData::fields, indri::index::TermData::maxDocumentLength, and indri::index::TermData::minDocumentLength.
Referenced by indri::index::IndexWriter::_writeStatistics(), and disktermdata_compress().
indri::index::TermData* termdata_construct (void * buffer, int fieldCount) [inline]
Referenced by indri::index::MemoryIndex::_lookupTerm(), disktermdata_create(), and termdata_create().
indri::index::TermData* termdata_create (int fieldCount) [inline]
References termdata_construct().
Referenced by indri::index::IndexWriter::_writeInvertedLists().
void termdata_decompress (indri::utility::RVLDecompressStream & stream, indri::index::TermData * termData, int fieldCount) [inline]
References indri::index::TermData::corpus, indri::index::TermData::fields, indri::index::TermData::maxDocumentLength, and indri::index::TermData::minDocumentLength.
Referenced by indri::index::DiskDocListFileIterator::_readEntry(), indri::index::DiskDocListIterator::_readTermData(), and disktermdata_decompress().
void termdata_delete (indri::index::TermData * termData, int fieldCount) [inline]
References termdata_destruct().
Referenced by indri::index::IndexWriter::_writeInvertedLists().
void termdata_destruct (indri::index::TermData * termData, int fieldCount) [inline]
References indri::index::TermData::fields.
Referenced by indri::index::MemoryIndex::_destroyTerms(), and termdata_delete().
void termdata_merge (indri::index::TermData * termData, indri::index::TermData * merger, int fieldCount) [inline]
References indri::index::TermData::corpus, indri::index::TermFieldStatistics::documentCount, indri::index::TermData::fields, indri::index::TermData::maxDocumentLength, indri::index::TermData::minDocumentLength, and indri::index::TermFieldStatistics::totalCount.
Referenced by indri::index::IndexWriter::_storeMatchInformation(), and indri::index::IndexWriter::_writeStatistics().
int termdata_size (int fieldCount) [inline]
Referenced by indri::index::MemoryIndex::_lookupTerm(), indri::index::DiskDocListIterator::_readTermData(), indri::index::DiskDocListFileIterator::DiskDocListFileIterator(), disktermdata_create(), disktermdata_decompress(), and disktermdata_size().