Indri: TFIDFExpander.cpp File Reference
TFIDFExpander.cpp File Reference
#include "indri/TFIDFExpander.hpp"
#include <math.h>
#include <stdio.h>
#include <sstream>
#include <string>
#include <algorithm>
#include <vector>
#include "indri/count_iterator"
Classes
struct TFIDFTerm
struct TFIDFTerm::relevance_greater
struct TFIDFTerm::relevance_projection
struct TFIDFTerm::pair_projection
Functions
static void _parseSmoothing (indri::api::Parameters &converted, const std::string &spec)
static double _BM25TF (const double rawTF, const double k1, const double b, const double docLen, const double avgDocLen)
Function Documentation
static double _BM25TF (const double rawTF, const double k1, const double b, const double docLen, const double avgDocLen) [static]
Referenced by indri::query::TFIDFExpander::expand().
static void _parseSmoothing (indri::api::Parameters & converted, const std::string & spec) [static]
References indri::api::Parameters::set().
Referenced by indri::query::TFIDFExpander::expand().