Indri: WARCDocumentIterator.cpp File Reference
WARCDocumentIterator.cpp File Reference
#include "indri/WARCDocumentIterator.hpp"
#include <iostream>
#include "lemur/Exception.hpp"
Defines
#define SPACES " \t\r\n"
Functions
std::string trim_right (const string &s, const string &t=SPACES)
std::string trim_left (const string &s, const string &t=SPACES)
std::string trim (const string &s, const string &t=SPACES)
void split (const std::string &line, std::string &key, std::string &value, char delim= ':')
Define Documentation
#define SPACES " \t\r\n"
Function Documentation
void split (const std::string & line, std::string & key, std::string & value, char delim = ':') [inline]
Referenced by indri::parse::WARCRecord::readHeader().
std::string trim (const string & s, const string & t = SPACES) [inline]
References trim_left(), and trim_right().
Referenced by indri::file::DirectoryIterator::_copyCurrent(), lemurproject::indri::ui::IndexUI::buildIndex(), indri::file::DirectoryIterator::DirectoryIterator(), lemurproject::indri::ui::IndexUI::encodeMem(), lemurproject::indri::ui::GetPaths::getPath(), and indri::collection::RepositoryMaintenanceThread::work().
std::string trim_left (const string & s, const string & t = SPACES) [inline]
Referenced by indri::parse::WARCRecord::readHeader(), and trim().
std::string trim_right (const string & s, const string & t = SPACES) [inline]
Referenced by indri::parse::WARCRecord::readHeader(), and trim().