Indri: XMLNode.hpp File Reference
XMLNode.hpp File Reference
#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <assert.h>
#include <iomanip>
#include <iostream>
#include "indri/indri-platform.h"
#include "lemur/lemur-compat.hpp"
Classes
class indri::xml::XMLNode
Namespaces
namespace indri
namespaces within the indri system
namespace indri::xml
XML support classes.
Functions
std::string i64_to_string (INT64 value)
Convert an INT64 to a string.
INT64 string_to_i64 (const std::string &str)
Convert a string to an INT64.
int string_to_int (const std::string &str)
Convert a string to an int.
std::string base64_encode (const void *input, int length)
int base64_decode (void *output, int outputLength, const std::string &input)
void base64_decode_string (std::string &out, const std::string &in)
Function Documentation
int base64_decode (void * output, int outputLength, const std::string & input) [inline]
Base64 decode a string into an output block of memory
Parameters:
input the input to decode
output the block to decode into
outputLength the length of the output
Returns:
true output length
Referenced by base64_decode_string(), and indri::server::NetworkServerProxyDocumentsResponse::getResults().
void base64_decode_string (std::string & out, const std::string & in) [inline]
Base64 decode a string into a new string
Parameters:
in the input to encode
out the string for the output
References base64_decode().
Referenced by indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyMetadataResponse::getResults(), and QueryParser::rawText().
std::string base64_encode (const void * input, int length) [inline]
Base64 encode an input block of memory into a string
Parameters:
input the input to encode
length the length of the input
Returns:
the encoded string
Referenced by indri::net::NetworkServerStub::_encodeDocument(), indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handleDocumentVectors(), and indri::net::NetworkServerStub::_handlePathNames().
std::string i64_to_string (INT64 value) [inline]
Convert an INT64 to a string.
Referenced by indri::net::NetworkServerStub::_encodeDocument(), indri::net::NetworkServerStub::_handleDocumentIDsFromMetadata(), indri::net::NetworkServerStub::_handleDocumentVectors(), indri::parse::Combiner::_openReadBuckets(), indri::parse::Combiner::_openWriteBuckets(), indri::parse::Combiner::_readRedirects(), indri::net::NetworkServerStub::_sendNumericResponse(), indri::parse::Combiner::_writeCorpusTable(), indri::parse::Combiner::combineBucket(), indri::parse::Combiner::combineRedirectDestinationBucket(), indri::parse::Combiner::createBuckets(), indri::server::NetworkServerProxy::documentLength(), indri::server::NetworkServerProxy::documentMetadata(), indri::server::NetworkServerProxy::documents(), indri::server::NetworkServerProxy::documentVectors(), indri::net::NetworkListener::listen(), indri::collection::Repository::merge(), indri::server::NetworkServerProxy::pathNames(), indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::request(), indri::collection::CompressedCollection::retrieve(), indri::server::NetworkServerProxy::runQuery(), indri::api::Parameters::set(), indri::server::NetworkServerProxy::setMaxWildcardTerms(), and indri::server::NetworkServerProxy::termName().
INT64 string_to_i64 (const std::string & str) [inline]
Convert a string to an INT64.
Referenced by indri::net::NetworkServerStub::_handleDocumentLength(), indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handleDocuments(), indri::net::NetworkServerStub::_handleDocumentVectors(), indri::net::NetworkServerStub::_handlePathNames(), indri::net::NetworkServerStub::_handleQuery(), indri::net::NetworkServerStub::_handleTermName(), indri::server::NetworkServerProxy::_numericRequest(), delete_document(), indri::lang::Unpacker::getInteger(), indri::server::NetworkServerProxyDocumentIDsResponse::getResults(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), QueryParser::number(), NexiParser::number(), indri::api::Parameters::operator INT64(), string_to_int(), and indri::parse::NumericFieldAnnotator::transform().
int string_to_int (const std::string & str) [inline]
Convert a string to an int.
References string_to_i64().
Referenced by indri::net::NetworkServerStub::_handleSetMaxWildcardTerms().