Indri: indri::utility::IndriTimer Class Reference
indri::utility::IndriTimer Class Reference
#include <IndriTimer.hpp>
Public Member Functions
IndriTimer ()
void start ()
start the timer
void stop ()
pause the timer
void reset ()
reset the timer
UINT64 elapsedTime () const
void printElapsedSeconds (std::ostream &out) const
void printElapsedMicroseconds (std::ostream &out) const
Static Public Member Functions
static UINT64 currentTime ()
Private Attributes
UINT64 _elapsed
when did we start.
UINT64 _start
bool _stopped
Detailed Description
Utility class for printing timing statistics to a stream
Constructor & Destructor Documentation
indri::utility::IndriTimer::IndriTimer ()
Member Function Documentation
UINT64 indri::utility::IndriTimer::currentTime () [static]
Returns:
the current time as an unsigned 64 bit integer
Referenced by indri::collection::Repository::_setThrashing(), indri::collection::Repository::_timeSinceThrashing(), elapsedTime(), start(), and stop().
UINT64 indri::utility::IndriTimer::elapsedTime () const
Returns:
elapsed time since started as an unsigned 64 bit integer
References _elapsed, _start, _stopped, and currentTime().
Referenced by printElapsedMicroseconds(), printElapsedSeconds(), and indri::api::QueryEnvironment::runQuery().
void indri::utility::IndriTimer::printElapsedMicroseconds (std::ostream & out) const
Print elapsed microseconds to an output stream.
Parameters:
out the stream to print to.
References elapsedTime().
void indri::utility::IndriTimer::printElapsedSeconds (std::ostream & out) const
Print elapsed seconds to an output stream.
Parameters:
out the stream to print to.
References elapsedTime().
Referenced by buildindex_print_event(), buildindex_print_status(), indri::parse::Combiner::combineBuckets(), main(), and FieldModifier::processFields().
void indri::utility::IndriTimer::reset ()
reset the timer
References _elapsed, _start, and _stopped.
void indri::utility::IndriTimer::start ()
start the timer
References _start, _stopped, and currentTime().
Referenced by buildindex_start_time(), indri::parse::Combiner::combineBuckets(), main(), FieldModifier::processFields(), and indri::api::QueryEnvironment::runQuery().
void indri::utility::IndriTimer::stop ()
pause the timer
References _elapsed, _start, _stopped, and currentTime().
Referenced by indri::api::QueryEnvironment::runQuery().
Member Data Documentation
UINT64 indri::utility::IndriTimer::_elapsed [private]
when did we start.
Referenced by elapsedTime(), reset(), and stop().
UINT64 indri::utility::IndriTimer::_start [private]
Referenced by elapsedTime(), reset(), start(), and stop().
bool indri::utility::IndriTimer::_stopped [private]
Referenced by elapsedTime(), reset(), start(), and stop().
The documentation for this class was generated from the following files:
IndriTimer.hpp
IndriTimer.cpp