Indri: indri::lang::FilRejNode Class Reference
indri::lang::FilRejNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FilRejNode (RawExtentNode *filter, ScoredExtentNode *disallowed)
FilRejNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
RawExtentNode * getFilter ()
ScoredExtentNode * getDisallowed ()
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
RawExtentNode * _filter
ScoredExtentNode * _disallowed
Constructor & Destructor Documentation
indri::lang::FilRejNode::FilRejNode (RawExtentNode * filter, ScoredExtentNode * disallowed) [inline]
References _disallowed, and _filter.
Referenced by copy().
indri::lang::FilRejNode::FilRejNode (Unpacker & unpacker) [inline]
References _disallowed, _filter, indri::lang::Unpacker::getRawExtentNode(), and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
Node* indri::lang::FilRejNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _disallowed, _filter, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and FilRejNode().
ScoredExtentNode* indri::lang::FilRejNode::getDisallowed () [inline]
References _disallowed.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
RawExtentNode* indri::lang::FilRejNode::getFilter () [inline]
References _filter.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), and operator==().
UINT64 indri::lang::FilRejNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _disallowed, _filter, and indri::lang::Node::hashCode().
bool indri::lang::FilRejNode::operator== (Node & node) [inline]
References _disallowed, _filter, getDisallowed(), and getFilter().
void indri::lang::FilRejNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _disallowed, _filter, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::FilRejNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _disallowed, _filter, and indri::lang::Node::queryText().
std::string indri::lang::FilRejNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FilRejNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _disallowed, _filter, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::FilRejNode::_disallowed [private]
Referenced by copy(), FilRejNode(), getDisallowed(), hashCode(), operator==(), pack(), queryText(), and walk().
RawExtentNode* indri::lang::FilRejNode::_filter [private]
Referenced by copy(), FilRejNode(), getFilter(), hashCode(), operator==(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp