Indri: indri::infnet::InferenceNetwork Class Reference
indri::infnet::InferenceNetwork Class Reference
#include <InferenceNetwork.hpp>
Public Types
typedef std::map< std::string,
EvaluatorNode::MResults > MAllResults
Public Member Functions
InferenceNetwork (indri::collection::Repository &repository)
~InferenceNetwork ()
const std::vector
< EvaluatorNode * > & getEvaluators () const
indri::index::DocListIterator * getDocIterator (int index)
indri::index::DocExtentListIterator * getFieldIterator (int index)
indri::collection::PriorListIterator * getPriorIterator (int index)
int addDocIterator (const std::string &term)
int addFieldIterator (const std::string &field)
int addPriorIterator (const std::string &prior)
void addListNode (ListIteratorNode *listNode)
void addBeliefNode (BeliefNode *beliefNode)
void addEvaluatorNode (EvaluatorNode *evaluatorNode)
void addComplexEvaluatorNode (EvaluatorNode *complexEvaluator)
void addScoreFunction (indri::query::TermScoreFunction *scoreFunction)
void addDocumentStructureHolderNode (DocumentStructureHolderNode *docStruct)
const MAllResults & evaluate ()
Private Member Functions
void _indexChanged (indri::index::Index &index)
void _indexFinished (indri::index::Index &index)
void _moveToDocument (lemur::api::DOCID_T candidate)
void _moveDocListIterators (lemur::api::DOCID_T candidate)
lemur::api::DOCID_T _nextCandidateDocument (indri::index::DeletedDocumentList::read_transaction *deleted)
void _evaluateDocument (indri::index::Index &index, lemur::api::DOCID_T document)
void _evaluateIndex (indri::index::Index &index)
Private Attributes
std::vector< std::string > _termNames
std::vector< std::string > _fieldNames
std::vector< std::string > _priorNames
std::vector< class
indri::index::DocExtentListIterator * > _fieldIterators
std::vector< class
indri::index::DocListIterator * > _docIterators
std::vector< class
indri::collection::PriorListIterator * > _priorIterators
std::vector< ListIteratorNode * > _listIteratorNodes
std::vector< BeliefNode * > _beliefNodes
std::vector< EvaluatorNode * > _evaluators
std::vector< EvaluatorNode * > _complexEvaluators
std::vector
< indri::query::TermScoreFunction * > _scoreFunctions
DocumentStructureHolderNode * _documentStructureHolderNode
indri::utility::greedy_vector
< class
indri::index::DocListIterator * > _closeIterators
int _closeIteratorBound
indri::collection::Repository & _repository
MAllResults _results
Member Typedef Documentation
typedef std::map< std::string, EvaluatorNode::MResults > indri::infnet::InferenceNetwork::MAllResults
Constructor & Destructor Documentation
indri::infnet::InferenceNetwork::InferenceNetwork (indri::collection::Repository & repository)
indri::infnet::InferenceNetwork::~InferenceNetwork ()
References _beliefNodes, _docIterators, _documentStructureHolderNode, _evaluators, _fieldIterators, _listIteratorNodes, _priorIterators, and _scoreFunctions.
Member Function Documentation
void indri::infnet::InferenceNetwork::_evaluateDocument (indri::index::Index & index, lemur::api::DOCID_T document) [private]
References _complexEvaluators, and indri::index::Index::documentLength().
Referenced by _evaluateIndex().
void indri::infnet::InferenceNetwork::_evaluateIndex (indri::index::Index & index) [private]
References _complexEvaluators, _evaluateDocument(), _moveToDocument(), _nextCandidateDocument(), _repository, indri::collection::Repository::deletedList(), indri::index::Index::documentBase(), indri::index::Index::documentMaximum(), and indri::index::DeletedDocumentList::getReadTransaction().
Referenced by evaluate().
void indri::infnet::InferenceNetwork::_indexChanged (indri::index::Index & index) [private]
References _beliefNodes, _closeIteratorBound, _closeIterators, _docIterators, _documentStructureHolderNode, _evaluators, _fieldIterators, _fieldNames, _listIteratorNodes, _priorIterators, _priorNames, _repository, _termNames, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Index::docListIterator(), indri::index::Index::fieldListIterator(), indri::infnet::DocumentStructureHolderNode::indexChanged(), indri::collection::Repository::priorListIterator(), indri::collection::PriorListIterator::startIteration(), indri::index::DocExtentListIterator::startIteration(), and indri::index::DocListIterator::startIteration().
Referenced by evaluate().
void indri::infnet::InferenceNetwork::_indexFinished (indri::index::Index & index) [private]
References _docIterators, _fieldIterators, and _priorIterators.
Referenced by evaluate().
void indri::infnet::InferenceNetwork::_moveDocListIterators (lemur::api::DOCID_T candidate) [inline, private]
References _closeIteratorBound, _closeIterators, _docIterators, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), CLOSE_ITERATOR_RANGE, indri::utility::greedy_vector< _Type, _Count >::end(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by _moveToDocument().
void indri::infnet::InferenceNetwork::_moveToDocument (lemur::api::DOCID_T candidate) [private]
References _documentStructureHolderNode, _fieldIterators, _listIteratorNodes, _moveDocListIterators(), _priorIterators, and indri::infnet::DocumentStructureHolderNode::prepare().
Referenced by _evaluateIndex().
lemur::api::DOCID_T indri::infnet::InferenceNetwork::_nextCandidateDocument (indri::index::DeletedDocumentList::read_transaction * deleted) [private]
References _complexEvaluators, and indri::index::DeletedDocumentList::read_transaction::nextCandidateDocument().
Referenced by _evaluateIndex().
void indri::infnet::InferenceNetwork::addBeliefNode (BeliefNode * beliefNode)
References _beliefNodes.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), and indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::InferenceNetwork::addComplexEvaluatorNode (EvaluatorNode * complexEvaluator)
References _complexEvaluators.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::infnet::InferenceNetwork::addDocIterator (const std::string & term)
References _termNames.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::InferenceNetwork::addDocumentStructureHolderNode (DocumentStructureHolderNode * docStruct)
References _documentStructureHolderNode.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::InferenceNetwork::addEvaluatorNode (EvaluatorNode * evaluatorNode)
References _evaluators.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::infnet::InferenceNetwork::addFieldIterator (const std::string & field)
References _fieldNames.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::InferenceNetwork::addListNode (ListIteratorNode * listNode)
References _listIteratorNodes.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::infnet::InferenceNetworkBuilder::after(), inferencenetworkbuilder_build_child_window(), and inferencenetworkbuilder_build_ordered_window().
int indri::infnet::InferenceNetwork::addPriorIterator (const std::string & prior)
References _priorNames.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::InferenceNetwork::addScoreFunction (indri::query::TermScoreFunction * scoreFunction)
References _scoreFunctions.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), and indri::infnet::InferenceNetworkBuilder::after().
const indri::infnet::InferenceNetwork::MAllResults & indri::infnet::InferenceNetwork::evaluate ()
References _evaluateIndex(), _evaluators, _indexChanged(), _indexFinished(), _repository, _results, indri::collection::Repository::countQuery(), indri::collection::Repository::indexes(), indri::index::Index::iteratorLock(), and indri::index::Index::statisticsLock().
Referenced by indri::server::LocalQueryServer::runQuery().
indri::index::DocListIterator * indri::infnet::InferenceNetwork::getDocIterator (int index)
References _docIterators.
Referenced by indri::infnet::TermFrequencyBeliefNode::indexChanged(), and indri::infnet::DocListIteratorNode::indexChanged().
const std::vector< indri::infnet::EvaluatorNode * > & indri::infnet::InferenceNetwork::getEvaluators () const
References _evaluators.
indri::index::DocExtentListIterator * indri::infnet::InferenceNetwork::getFieldIterator (int index)
References _fieldIterators.
Referenced by indri::infnet::FieldIteratorNode::indexChanged().
indri::collection::PriorListIterator * indri::infnet::InferenceNetwork::getPriorIterator (int index)
References _priorIterators.
Referenced by indri::infnet::PriorNode::indexChanged().
Member Data Documentation
std::vector<BeliefNode*> indri::infnet::InferenceNetwork::_beliefNodes [private]
Referenced by _indexChanged(), addBeliefNode(), and ~InferenceNetwork().
int indri::infnet::InferenceNetwork::_closeIteratorBound [private]
Referenced by _indexChanged(), and _moveDocListIterators().
indri::utility::greedy_vector<class indri::index::DocListIterator*> indri::infnet::InferenceNetwork::_closeIterators [private]
Referenced by _indexChanged(), and _moveDocListIterators().
std::vector<EvaluatorNode*> indri::infnet::InferenceNetwork::_complexEvaluators [private]
Referenced by _evaluateDocument(), _evaluateIndex(), _nextCandidateDocument(), and addComplexEvaluatorNode().
std::vector<class indri::index::DocListIterator*> indri::infnet::InferenceNetwork::_docIterators [private]
Referenced by _indexChanged(), _indexFinished(), _moveDocListIterators(), getDocIterator(), and ~InferenceNetwork().
DocumentStructureHolderNode* indri::infnet::InferenceNetwork::_documentStructureHolderNode [private]
Referenced by _indexChanged(), _moveToDocument(), addDocumentStructureHolderNode(), and ~InferenceNetwork().
std::vector<EvaluatorNode*> indri::infnet::InferenceNetwork::_evaluators [private]
Referenced by _indexChanged(), addEvaluatorNode(), evaluate(), getEvaluators(), and ~InferenceNetwork().
std::vector<class indri::index::DocExtentListIterator*> indri::infnet::InferenceNetwork::_fieldIterators [private]
Referenced by _indexChanged(), _indexFinished(), _moveToDocument(), getFieldIterator(), and ~InferenceNetwork().
std::vector<std::string> indri::infnet::InferenceNetwork::_fieldNames [private]
Referenced by _indexChanged(), and addFieldIterator().
std::vector<ListIteratorNode*> indri::infnet::InferenceNetwork::_listIteratorNodes [private]
Referenced by _indexChanged(), _moveToDocument(), addListNode(), and ~InferenceNetwork().
std::vector<class indri::collection::PriorListIterator*> indri::infnet::InferenceNetwork::_priorIterators [private]
Referenced by _indexChanged(), _indexFinished(), _moveToDocument(), getPriorIterator(), and ~InferenceNetwork().
std::vector<std::string> indri::infnet::InferenceNetwork::_priorNames [private]
Referenced by _indexChanged(), and addPriorIterator().
indri::collection::Repository& indri::infnet::InferenceNetwork::_repository [private]
Referenced by _evaluateIndex(), _indexChanged(), and evaluate().
MAllResults indri::infnet::InferenceNetwork::_results [private]
Referenced by evaluate().
std::vector<indri::query::TermScoreFunction*> indri::infnet::InferenceNetwork::_scoreFunctions [private]
Referenced by addScoreFunction(), and ~InferenceNetwork().
std::vector<std::string> indri::infnet::InferenceNetwork::_termNames [private]
Referenced by _indexChanged(), and addDocIterator().
The documentation for this class was generated from the following files:
InferenceNetwork.hpp
InferenceNetwork.cpp