Indri: indri::parse::OffsetMetadataAnnotator Class Reference
indri::parse::OffsetMetadataAnnotator Class Reference
#include <OffsetMetadataAnnotator.hpp>
Public Member Functions
OffsetMetadataAnnotator ()
~OffsetMetadataAnnotator ()
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
void open (const std::string &offsetMetadataFile)
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
Private Member Functions
const char * _getDocno (indri::api::ParsedDocument *document)
void _cleanup ()
Private Attributes
std::string _offsetMetadataFile
indri::utility::HashTable
< const char
*, indri::utility::greedy_vector
< MetadataPair * > * > _annotations
std::vector< char * > _buffers_allocated
bool _first_open
ObjectHandler
< indri::api::ParsedDocument > * _handler
Constructor & Destructor Documentation
indri::parse::OffsetMetadataAnnotator::OffsetMetadataAnnotator () [inline]
References _first_open, and _handler.
indri::parse::OffsetMetadataAnnotator::~OffsetMetadataAnnotator () [inline]
References _buffers_allocated, and _cleanup().
Member Function Documentation
void indri::parse::OffsetMetadataAnnotator::_cleanup () [inline, private]
References _annotations, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Referenced by open(), and ~OffsetMetadataAnnotator().
const char* indri::parse::OffsetMetadataAnnotator::_getDocno (indri::api::ParsedDocument * document) [inline, private]
References indri::api::ParsedDocument::metadata, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by transform().
void indri::parse::OffsetMetadataAnnotator::handle (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::OffsetMetadataAnnotator::open (const std::string & offsetMetadataFile)
References _annotations, _buffers_allocated, _cleanup(), _first_open, _offsetMetadataFile, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::file::Path::isFile(), indri::parse::MetadataPair::key, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::parse::MetadataPair::value, and indri::parse::MetadataPair::valueLength.
Referenced by indri::api::IndexEnvironment::_createAnnotators().
void indri::parse::OffsetMetadataAnnotator::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [inline, virtual]
Implements indri::parse::Transformation.
References _handler.
indri::api::ParsedDocument * indri::parse::OffsetMetadataAnnotator::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _annotations, _getDocno(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::api::ParsedDocument::metadata, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by handle().
Member Data Documentation
indri::utility::HashTable<const char *,indri::utility::greedy_vector<MetadataPair*>*> indri::parse::OffsetMetadataAnnotator::_annotations [private]
Referenced by _cleanup(), open(), and transform().
std::vector<char *> indri::parse::OffsetMetadataAnnotator::_buffers_allocated [private]
Referenced by open(), and ~OffsetMetadataAnnotator().
bool indri::parse::OffsetMetadataAnnotator::_first_open [private]
Referenced by OffsetMetadataAnnotator(), and open().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::OffsetMetadataAnnotator::_handler [private]
Referenced by handle(), OffsetMetadataAnnotator(), and setHandler().
std::string indri::parse::OffsetMetadataAnnotator::_offsetMetadataFile [private]
Referenced by open().
The documentation for this class was generated from the following files:
OffsetMetadataAnnotator.hpp
OffsetMetadataAnnotator.cpp