Indri: indri::parse::AnchorTextWriter Class Reference
indri::parse::AnchorTextWriter Class Reference
#include <AnchorTextWriter.hpp>
Public Member Functions
AnchorTextWriter (const std::string &outputPath)
~AnchorTextWriter ()
void handle (indri::api::ParsedDocument *document)
Private Attributes
std::ofstream _out
Detailed Description
Writes anchor text from a parsed document out to a file.
Constructor & Destructor Documentation
indri::parse::AnchorTextWriter::AnchorTextWriter (const std::string & outputPath) [inline]
References _out, indri::file::Path::directory(), and indri::file::Path::make().
indri::parse::AnchorTextWriter::~AnchorTextWriter () [inline]
References _out.
Member Function Documentation
void indri::parse::AnchorTextWriter::handle (indri::api::ParsedDocument * document) [inline, virtual]
Implements indri::parse::ObjectHandler< indri::api::ParsedDocument >.
References _out, indri::parse::TagExtent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::TagExtent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::ParsedDocument::metadata, indri::parse::TagExtent::name, indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::tags, indri::api::ParsedDocument::terms, and indri::parse::MetadataPair::value.
Member Data Documentation
std::ofstream indri::parse::AnchorTextWriter::_out [private]
Referenced by AnchorTextWriter(), handle(), and ~AnchorTextWriter().
The documentation for this class was generated from the following file:
AnchorTextWriter.hpp