Indri: indri::index::DocListMemoryBuilderIterator Class Reference
indri::index::DocListMemoryBuilderIterator Class Reference
#include <DocListMemoryBuilder.hpp>
Public Member Functions
DocListMemoryBuilderIterator ()
DocListMemoryBuilderIterator (class DocListMemoryBuilder &builder, TermData *termData)
void reset (class DocListMemoryBuilder &builder, TermData *termData)
void reset (const indri::utility::greedy_vector< DocListMemoryBuilderSegment, 4 > &lists, TermData *termData)
void startIteration ()
bool finished ()
bool nextEntry (lemur::api::DOCID_T documentID)
bool nextEntry ()
TermData * termData ()
DocListIterator::DocumentData * currentEntry ()
indri::utility::greedy_vector
< DocListIterator::TopDocument > & topDocuments ()
Private Attributes
const
indri::utility::greedy_vector
< DocListMemoryBuilderSegment, 4 > * _lists
indri::utility::greedy_vector
< DocListMemoryBuilderSegment, 4 >
::const_iterator _current
indri::index::DocListIterator::DocumentData _data
indri::utility::greedy_vector
< DocListIterator::TopDocument > _emptyTopDocuments
const char * _list
const char * _listEnd
bool _finished
TermData * _termData
Constructor & Destructor Documentation
indri::index::DocListMemoryBuilderIterator::DocListMemoryBuilderIterator ()
indri::index::DocListMemoryBuilderIterator::DocListMemoryBuilderIterator (class DocListMemoryBuilder & builder, TermData * termData)
References reset().
Member Function Documentation
indri::index::DocListIterator::DocumentData * indri::index::DocListMemoryBuilderIterator::currentEntry () [virtual]
Implements indri::index::DocListIterator.
References _data, and finished().
bool indri::index::DocListMemoryBuilderIterator::finished () [virtual]
Implements indri::index::DocListIterator.
References _finished.
Referenced by currentEntry().
bool indri::index::DocListMemoryBuilderIterator::nextEntry () [virtual]
Implements indri::index::DocListIterator.
References _current, _data, _finished, _list, _listEnd, _lists, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListIterator::DocumentData::document, indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::DocListIterator::DocumentData::positions, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by nextEntry(), reset(), and startIteration().
bool indri::index::DocListMemoryBuilderIterator::nextEntry (lemur::api::DOCID_T documentID) [virtual]
Implements indri::index::DocListIterator.
References _data, indri::index::DocListIterator::DocumentData::document, and nextEntry().
void indri::index::DocListMemoryBuilderIterator::reset (const indri::utility::greedy_vector< DocListMemoryBuilderSegment, 4 > & lists, TermData * termData)
References _current, _data, _finished, _list, _listEnd, _lists, _termData, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListIterator::DocumentData::document, indri::utility::greedy_vector< _Type, _Count >::end(), nextEntry(), and indri::index::DocListIterator::DocumentData::positions.
void indri::index::DocListMemoryBuilderIterator::reset (class DocListMemoryBuilder & builder, TermData * termData)
References indri::index::DocListMemoryBuilder::_lists, and indri::index::DocListMemoryBuilder::flush().
Referenced by DocListMemoryBuilderIterator(), indri::index::MemoryIndexDocListFileIterator::nextEntry(), and indri::index::MemoryIndexDocListFileIterator::startIteration().
void indri::index::DocListMemoryBuilderIterator::startIteration () [virtual]
Implements indri::index::DocListIterator.
References _current, _data, _list, _listEnd, _lists, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListIterator::DocumentData::document, indri::utility::greedy_vector< _Type, _Count >::end(), nextEntry(), and indri::index::DocListIterator::DocumentData::positions.
indri::index::TermData * indri::index::DocListMemoryBuilderIterator::termData () [virtual]
Implements indri::index::DocListIterator.
References _termData.
indri::utility::greedy_vector< indri::index::DocListIterator::TopDocument > & indri::index::DocListMemoryBuilderIterator::topDocuments () [virtual]
Implements indri::index::DocListIterator.
References _emptyTopDocuments.
Member Data Documentation
indri::utility::greedy_vector< DocListMemoryBuilderSegment, 4 >::const_iterator indri::index::DocListMemoryBuilderIterator::_current [private]
Referenced by nextEntry(), reset(), and startIteration().
indri::index::DocListIterator::DocumentData indri::index::DocListMemoryBuilderIterator::_data [private]
Referenced by currentEntry(), nextEntry(), reset(), and startIteration().
indri::utility::greedy_vector<DocListIterator::TopDocument> indri::index::DocListMemoryBuilderIterator::_emptyTopDocuments [private]
Referenced by topDocuments().
bool indri::index::DocListMemoryBuilderIterator::_finished [private]
Referenced by finished(), nextEntry(), and reset().
const char* indri::index::DocListMemoryBuilderIterator::_list [private]
Referenced by nextEntry(), reset(), and startIteration().
const char* indri::index::DocListMemoryBuilderIterator::_listEnd [private]
Referenced by nextEntry(), reset(), and startIteration().
const indri::utility::greedy_vector< DocListMemoryBuilderSegment, 4 >* indri::index::DocListMemoryBuilderIterator::_lists [private]
Referenced by nextEntry(), reset(), and startIteration().
TermData* indri::index::DocListMemoryBuilderIterator::_termData [private]
Referenced by reset(), and termData().
The documentation for this class was generated from the following files:
DocListMemoryBuilder.hpp
DocListMemoryBuilderIterator.cpp