Indri: indri::parse::TagList Class Reference
indri::parse::TagList Class Reference
#include <TagList.hpp>
Classes
struct tag_entry
Public Member Functions
TagList ()
void setFindParents (bool findParents)
void clear ()
void addTag (const char *name, const char *conflation, int begin)
void endTag (const char *name, const char *conflation, int end)
void writeTagList (indri::utility::greedy_vector< TagExtent * > &tags)
void writeMetadataList (indri::utility::greedy_vector< MetadataPair > &pairs, indri::utility::Buffer &buffer, const char *docText)
Private Attributes
indri::utility::greedy_vector
< tag_entry > _tags
int _openList
bool _findParents
Constructor & Destructor Documentation
indri::parse::TagList::TagList () [inline]
References clear().
Member Function Documentation
void indri::parse::TagList::addTag (const char * name, const char * conflation, int begin) [inline]
References _openList, _tags, indri::parse::TagList::tag_entry::begin, indri::parse::TagList::tag_entry::conflation, indri::parse::TagList::tag_entry::end, indri::parse::TagList::tag_entry::name, indri::parse::TagList::tag_entry::next, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by FieldModifier::_mergeData(), indri::parse::TaggedTextParser::addMetadataTag(), indri::parse::TaggedTextParser::addTag(), and Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11().
void indri::parse::TagList::clear () [inline]
References _openList, _tags, and indri::utility::greedy_vector< _Type, _Count >::clear().
Referenced by FieldModifier::_mergeData(), indri::parse::TaggedTextParser::initialize(), and TagList().
void indri::parse::TagList::endTag (const char * name, const char * conflation, int end) [inline]
References _openList, _tags, indri::parse::TagList::tag_entry::end, indri::parse::TagList::tag_entry::name, and indri::parse::TagList::tag_entry::next.
Referenced by FieldModifier::_mergeData(), indri::parse::TaggedTextParser::endMetadataTag(), indri::parse::TaggedTextParser::endTag(), and Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11().
void indri::parse::TagList::setFindParents (bool findParents) [inline]
References _findParents.
void indri::parse::TagList::writeMetadataList (indri::utility::greedy_vector< MetadataPair > & pairs, indri::utility::Buffer & buffer, const char * docText) [inline]
References _tags, indri::parse::TagList::tag_entry::begin, indri::parse::TagList::tag_entry::conflation, indri::parse::TagList::tag_entry::end, indri::parse::MetadataPair::key, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::parse::MetadataPair::stripValue(), indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
Referenced by indri::parse::TaggedTextParser::cleanup().
void indri::parse::TagList::writeTagList (indri::utility::greedy_vector< TagExtent * > & tags) [inline]
References _findParents, _tags, indri::utility::greedy_vector< _Type, _Count >::back(), indri::parse::TagList::tag_entry::begin, indri::parse::TagExtent::begin, indri::parse::TagList::tag_entry::conflation, indri::parse::TagExtent::end, indri::parse::TagList::tag_entry::end, indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::parse::TagExtent::parent, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by FieldModifier::_mergeData(), indri::parse::TaggedTextParser::cleanup(), and Java_lemurproject_indri_indriJNI_IndexEnvironment_1addString_1_1SWIG_11().
Member Data Documentation
bool indri::parse::TagList::_findParents [private]
Referenced by setFindParents(), and writeTagList().
int indri::parse::TagList::_openList [private]
Referenced by addTag(), clear(), and endTag().
indri::utility::greedy_vector<tag_entry> indri::parse::TagList::_tags [private]
Referenced by addTag(), clear(), endTag(), writeMetadataList(), and writeTagList().
The documentation for this class was generated from the following file:
TagList.hpp