Indri: indri::lang::Printer Class Reference
indri::lang::Printer Class Reference
Public Member Functions
Printer ()
void defaultBefore (indri::lang::Node *n)
void defaultAfter (indri::lang::Node *n)
Private Attributes
int tabs
Constructor & Destructor Documentation
indri::lang::Printer::Printer () [inline]
Member Function Documentation
void indri::lang::Printer::defaultAfter (indri::lang::Node * n) [inline, virtual]
Reimplemented from indri::lang::Walker.
References tabs.
void indri::lang::Printer::defaultBefore (indri::lang::Node * n) [inline, virtual]
Reimplemented from indri::lang::Walker.
References indri::lang::Node::nodeName(), indri::lang::Node::queryText(), tabs, and indri::lang::Node::typeName().
Member Data Documentation
int indri::lang::Printer::tabs [private]
Referenced by defaultAfter(), and defaultBefore().
The documentation for this class was generated from the following file:
QueryEnvironment.cpp