Indri: indri::parse::DocumentIterator Class Reference
indri::parse::DocumentIterator Class Reference
#include <DocumentIterator.hpp>
Public Member Functions
virtual ~DocumentIterator ()
virtual UnparsedDocument * nextDocument ()=0
virtual void open (const std::string &filename)=0
virtual void close ()=0
void cleanDocno ()
Protected Attributes
std::string _docnostring
Constructor & Destructor Documentation
virtual indri::parse::DocumentIterator::~DocumentIterator () [inline, virtual]
Member Function Documentation
void indri::parse::DocumentIterator::cleanDocno () [inline]
References _docnostring.
Referenced by indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), and indri::parse::MboxDocumentIterator::nextDocument().
virtual void indri::parse::DocumentIterator::close () [pure virtual]
Implemented in indri::parse::MboxDocumentIterator, indri::parse::PDFDocumentExtractor, indri::parse::TaggedDocumentIterator, indri::parse::TextDocumentExtractor, and indri::parse::WARCDocumentIterator.
Referenced by indri::api::IndexEnvironment::addFile(), and harvest_anchor_text_file().
virtual UnparsedDocument* indri::parse::DocumentIterator::nextDocument () [pure virtual]
Implemented in indri::parse::MboxDocumentIterator, indri::parse::PDFDocumentExtractor, indri::parse::TaggedDocumentIterator, indri::parse::TextDocumentExtractor, and indri::parse::WARCDocumentIterator.
Referenced by indri::api::IndexEnvironment::addFile(), and harvest_anchor_text_file().
virtual void indri::parse::DocumentIterator::open (const std::string & filename) [pure virtual]
Implemented in indri::parse::MboxDocumentIterator, indri::parse::PDFDocumentExtractor, indri::parse::TaggedDocumentIterator, indri::parse::TextDocumentExtractor, and indri::parse::WARCDocumentIterator.
Referenced by indri::api::IndexEnvironment::addFile(), and harvest_anchor_text_file().
Member Data Documentation
std::string indri::parse::DocumentIterator::_docnostring [protected]
Referenced by cleanDocno(), indri::parse::TextDocumentExtractor::nextDocument(), indri::parse::PDFDocumentExtractor::nextDocument(), and indri::parse::MboxDocumentIterator::nextDocument().
The documentation for this class was generated from the following file:
DocumentIterator.hpp