Indri: indri::xml::XMLNode Class Reference
indri::xml::XMLNode Class Reference
#include <XMLNode.hpp>
Public Types
typedef std::map< std::string,
std::string > MAttributes
Public Member Functions
XMLNode (const std::string &name)
XMLNode (const std::string &name, const std::string &value)
XMLNode (const std::string &name, const MAttributes &attributes)
XMLNode (const std::string &name, const MAttributes &attributes, const std::string &value)
~XMLNode ()
clean up
void addChild (XMLNode *child)
void addAttribute (const std::string &key, const std::string &value)
void setValue (const std::string &value)
const std::string & getName () const
const std::string & getValue () const
const MAttributes & getAttributes () const
std::string getAttribute (const std::string &name) const
const std::vector< XMLNode * > & getChildren () const
const XMLNode * getChild (const std::string &name) const
std::string getChildValue (const std::string &name) const
Private Attributes
std::string _name
MAttributes _attributes
std::vector< XMLNode * > _children
std::string _value
Detailed Description
Internal Representation of an XML node hierarchy.
Member Typedef Documentation
typedef std::map<std::string,std::string> indri::xml::XMLNode::MAttributes
Constructor & Destructor Documentation
indri::xml::XMLNode::XMLNode (const std::string & name)
Create a node with the given name
Parameters:
name the name for the node.
indri::xml::XMLNode::XMLNode (const std::string & name, const std::string & value)
Create a node with the given name and value
Parameters:
name the name for the node.
value the value for the node
indri::xml::XMLNode::XMLNode (const std::string & name, const MAttributes & attributes)
Create a node with the given name and value
Parameters:
name the name for the node.
attributes the map constituting the value for the node
indri::xml::XMLNode::XMLNode (const std::string & name, const MAttributes & attributes, const std::string & value)
Create a node with the given name and value
Parameters:
name the name for the node.
attributes the map constituting the value for the node
value the string value for the node.
indri::xml::XMLNode::~XMLNode ()
clean up
References _children.
Member Function Documentation
void indri::xml::XMLNode::addAttribute (const std::string & key, const std::string & value)
Add an attribute to this node.
Parameters:
key the key for the parameter
value the value for the parameter
References _attributes.
Referenced by indri::lang::Packer::after(), indri::lang::Packer::pack(), and indri::server::NetworkServerProxy::runQuery().
void indri::xml::XMLNode::addChild (XMLNode * child)
Add a child to this node.
Parameters:
child the child to add
References _children.
Referenced by indri::net::NetworkServerStub::_encodeDocument(), indri::api::Parameters::_fillXML(), indri::net::NetworkServerStub::_handleDocumentIDsFromMetadata(), indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handleDocumentVectors(), indri::net::NetworkServerStub::_handleFieldList(), indri::net::NetworkServerStub::_handlePathNames(), indri::lang::Packer::after(), indri::server::NetworkServerProxy::documentIDsFromMetadata(), indri::server::NetworkServerProxy::documentMetadata(), indri::server::NetworkServerProxy::documents(), indri::server::NetworkServerProxy::documentsFromMetadata(), indri::server::NetworkServerProxy::documentVectors(), indri::server::NetworkServerProxy::pathNames(), indri::server::NetworkServerProxy::stemFieldCount(), and indri::server::NetworkServerProxy::termFieldCount().
std::string indri::xml::XMLNode::getAttribute (const std::string & name) const
Get the named attribute value
Parameters:
name the key
Returns:
the value
References _attributes.
Referenced by indri::net::NetworkServerStub::_handleQuery(), indri::api::Parameters::_loadXML(), indri::lang::Unpacker::_unpack(), indri::lang::Unpacker::getDouble(), indri::lang::Unpacker::getInteger(), indri::lang::Unpacker::getString(), and indri::lang::Unpacker::unpack().
const indri::xml::XMLNode::MAttributes & indri::xml::XMLNode::getAttributes () const
Returns:
the attributes of this node
References _attributes.
Referenced by indri::xml::XMLWriter::_writeXML().
const indri::xml::XMLNode * indri::xml::XMLNode::getChild (const std::string & name) const
Get the named child of this node.
Parameters:
name the key
Returns:
the named child node
References _children, and getName().
Referenced by indri::net::NetworkServerStub::_decodeMetadataRequest(), indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handlePathNames(), indri::net::NetworkServerStub::_handleStemFieldCount(), indri::net::NetworkServerStub::_handleTermFieldCount(), getChildValue(), indri::lang::Unpacker::getDocIdVector(), indri::lang::Unpacker::getDoubleVector(), indri::lang::Unpacker::getIntVector(), indri::lang::Unpacker::getNodeVector(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), and indri::lang::Unpacker::getStringVector().
const std::vector< indri::xml::XMLNode * > & indri::xml::XMLNode::getChildren () const
Get the children of this node
Returns:
the vector of child node pointers.
References _children.
Referenced by indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handleDocuments(), indri::net::NetworkServerStub::_handleDocumentVectors(), indri::net::NetworkServerStub::_handlePathNames(), indri::api::Parameters::_loadXML(), indri::xml::XMLWriter::_writeXML(), indri::parse::PDFDocumentExtractor::appendPdfMetaData(), indri::server::NetworkServerProxy::fieldList(), indri::lang::Unpacker::getDocIdVector(), indri::lang::Unpacker::getDoubleVector(), indri::lang::Unpacker::getIntVector(), indri::lang::Unpacker::getNodeVector(), indri::server::NetworkServerProxyDocumentIDsResponse::getResults(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyMetadataResponse::getResults(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::lang::Unpacker::getStringVector(), indri::parse::PDFDocumentExtractor::seekValue(), and indri::lang::Unpacker::unpack().
std::string indri::xml::XMLNode::getChildValue (const std::string & name) const
Get the value of the named child of this node.
Parameters:
name the key
Returns:
the value of the named child node
References getChild(), and getValue().
Referenced by indri::net::NetworkServerStub::_decodeMetadataRequest(), indri::lang::Unpacker::getDocumentStructureNode(), indri::lang::Unpacker::getRawExtentNode(), and indri::lang::Unpacker::getScoredExtentNode().
const std::string & indri::xml::XMLNode::getName () const
Returns:
the name of this node
References _name.
Referenced by indri::api::Parameters::_loadXML(), indri::xml::XMLWriter::_writeXML(), indri::parse::PDFDocumentExtractor::appendPdfMetaData(), getChild(), and indri::net::NetworkServerStub::request().
const std::string & indri::xml::XMLNode::getValue () const
Returns:
the value of this node
References _value.
Referenced by indri::net::NetworkServerStub::_handleDocumentLength(), indri::net::NetworkServerStub::_handleDocumentStemCount(), indri::net::NetworkServerStub::_handleDocumentTermCount(), indri::net::NetworkServerStub::_handleSetMaxWildcardTerms(), indri::net::NetworkServerStub::_handleStemCountText(), indri::net::NetworkServerStub::_handleStemFieldCount(), indri::net::NetworkServerStub::_handleStemTerm(), indri::net::NetworkServerStub::_handleTermCountText(), indri::net::NetworkServerStub::_handleTermFieldCount(), indri::net::NetworkServerStub::_handleTermID(), indri::net::NetworkServerStub::_handleTermName(), indri::api::Parameters::_loadXML(), indri::server::NetworkServerProxy::_numericRequest(), indri::server::NetworkServerProxy::_stringRequest(), indri::xml::XMLWriter::_writeXML(), getChildValue(), indri::lang::Unpacker::getDocIdVector(), indri::lang::Unpacker::getDoubleVector(), indri::lang::Unpacker::getIntVector(), indri::lang::Unpacker::getNodeVector(), indri::server::NetworkServerProxyDocumentIDsResponse::getResults(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyMetadataResponse::getResults(), indri::server::NetworkServerProxyDocumentsResponse::getResults(), indri::lang::Unpacker::getStringVector(), and indri::parse::PDFDocumentExtractor::seekValue().
void indri::xml::XMLNode::setValue (const std::string & value)
Set the value of this node
Parameters:
value the new value
References _value.
Referenced by indri::api::Parameters::_fillXML().
Member Data Documentation
MAttributes indri::xml::XMLNode::_attributes [private]
Referenced by addAttribute(), getAttribute(), and getAttributes().
std::vector<XMLNode*> indri::xml::XMLNode::_children [private]
Referenced by addChild(), getChild(), getChildren(), and ~XMLNode().
std::string indri::xml::XMLNode::_name [private]
Referenced by getName().
std::string indri::xml::XMLNode::_value [private]
Referenced by getValue(), and setValue().
The documentation for this class was generated from the following files:
XMLNode.hpp
XMLNode.cpp