Indri: indri::lang::ListAccumulator Class Reference
indri::lang::ListAccumulator Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ListAccumulator (RawExtentNode *raw)
ListAccumulator (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
RawExtentNode * getRawExtent ()
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
RawExtentNode * _raw
Constructor & Destructor Documentation
indri::lang::ListAccumulator::ListAccumulator (RawExtentNode * raw) [inline]
Referenced by copy().
indri::lang::ListAccumulator::ListAccumulator (Unpacker & unpacker) [inline]
References _raw, and indri::lang::Unpacker::getRawExtentNode().
Member Function Documentation
Node* indri::lang::ListAccumulator::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _raw, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), ListAccumulator(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
RawExtentNode* indri::lang::ListAccumulator::getRawExtent () [inline]
References _raw.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::ListAccumulator::hashCode () const [inline, virtual]
Implements indri::lang::Node.
void indri::lang::ListAccumulator::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _raw, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ListAccumulator::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _raw, and indri::lang::Node::queryText().
std::string indri::lang::ListAccumulator::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ListAccumulator::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _raw, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
RawExtentNode* indri::lang::ListAccumulator::_raw [private]
Referenced by copy(), getRawExtent(), ListAccumulator(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp