Indri: indri::lang::FilterNode Class Reference
indri::lang::FilterNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
FilterNode (ScoredExtentNode *child, std::vector< lemur::api::DOCID_T > &documents)
FilterNode (Unpacker &unpacker)
std::string typeName () const
ScoredExtentNode * getChild ()
const std::vector
< lemur::api::DOCID_T > & getDocuments () const
void pack (Packer &packer)
void walk (Walker &walker)
std::string queryText () const
UINT64 hashCode () const
Node * copy (Copier &copier)
Private Attributes
ScoredExtentNode * _child
std::vector< lemur::api::DOCID_T > _documents
Constructor & Destructor Documentation
indri::lang::FilterNode::FilterNode (ScoredExtentNode * child, std::vector< lemur::api::DOCID_T > & documents) [inline]
Referenced by copy().
indri::lang::FilterNode::FilterNode (Unpacker & unpacker) [inline]
References _child, _documents, indri::lang::Unpacker::getDocIdVector(), and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
Node* indri::lang::FilterNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _child, _documents, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), FilterNode(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
ScoredExtentNode* indri::lang::FilterNode::getChild () [inline]
References _child.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
const std::vector<lemur::api::DOCID_T>& indri::lang::FilterNode::getDocuments () const [inline]
References _documents.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::FilterNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _child, _documents, and indri::lang::Node::hashCode().
void indri::lang::FilterNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _child, _documents, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::FilterNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _child, and indri::lang::Node::queryText().
std::string indri::lang::FilterNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::FilterNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _child, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::FilterNode::_child [private]
Referenced by copy(), FilterNode(), getChild(), hashCode(), pack(), queryText(), and walk().
std::vector<lemur::api::DOCID_T> indri::lang::FilterNode::_documents [private]
Referenced by copy(), FilterNode(), getDocuments(), hashCode(), and pack().
The documentation for this class was generated from the following file:
QuerySpec.hpp