Indri: indri::index::DiskKeyfileVocabularyIterator Class Reference
indri::index::DiskKeyfileVocabularyIterator Class Reference
#include <DiskKeyfileVocabularyIterator.hpp>
Public Member Functions
DiskKeyfileVocabularyIterator (int baseID, indri::file::BulkTreeReader &bulkTree, indri::thread::Mutex &mutex, int fieldCount)
~DiskKeyfileVocabularyIterator ()
void startIteration ()
bool nextEntry ()
bool nextEntry (const char *skipTo)
indri::index::DiskTermData * currentEntry ()
bool finished ()
Private Member Functions
void _acquire ()
void _release ()
bool _readData ()
Private Attributes
DiskTermData * _diskTermData
int _baseID
indri::file::BulkTreeReader & _bulkTree
indri::file::BulkTreeIterator * _bulkIterator
int _fieldCount
char _termString [1024]
indri::utility::Buffer _compressedData
indri::utility::Buffer _decompressedData
indri::thread::Mutex & _mutex
bool _holdingLock
bool _finished
bool _justStartedIteration
Constructor & Destructor Documentation
indri::index::DiskKeyfileVocabularyIterator::DiskKeyfileVocabularyIterator (int baseID, indri::file::BulkTreeReader & bulkTree, indri::thread::Mutex & mutex, int fieldCount)
References _bulkIterator, _bulkTree, _compressedData, _decompressedData, _fieldCount, disktermdata_size(), indri::file::BulkTreeReader::iterator(), and indri::utility::Buffer::write().
indri::index::DiskKeyfileVocabularyIterator::~DiskKeyfileVocabularyIterator ()
References _bulkIterator, and _release().
Member Function Documentation
void indri::index::DiskKeyfileVocabularyIterator::_acquire () [private]
References _holdingLock, _mutex, and indri::thread::Mutex::lock().
Referenced by startIteration().
bool indri::index::DiskKeyfileVocabularyIterator::_readData () [private]
References _bulkIterator, _compressedData, _decompressedData, _diskTermData, _fieldCount, _release(), _termString, disktermdata_decompress(), indri::file::BulkTreeIterator::finished(), indri::utility::Buffer::front(), indri::file::BulkTreeIterator::get(), indri::utility::Buffer::size(), indri::index::TermData::term, indri::index::DiskTermData::termData, indri::index::DiskTermData::WithOffsets, and indri::index::DiskTermData::WithTermID.
Referenced by nextEntry(), and startIteration().
void indri::index::DiskKeyfileVocabularyIterator::_release () [private]
References _holdingLock, _mutex, and indri::thread::Mutex::unlock().
Referenced by _readData(), and ~DiskKeyfileVocabularyIterator().
indri::index::DiskTermData * indri::index::DiskKeyfileVocabularyIterator::currentEntry () [virtual]
Implements indri::index::VocabularyIterator.
References _bulkIterator, _diskTermData, and indri::file::BulkTreeIterator::finished().
Referenced by nextEntry().
bool indri::index::DiskKeyfileVocabularyIterator::finished () [virtual]
Implements indri::index::VocabularyIterator.
References _bulkIterator, and indri::file::BulkTreeIterator::finished().
bool indri::index::DiskKeyfileVocabularyIterator::nextEntry (const char * skipTo) [virtual]
Implements indri::index::VocabularyIterator.
References _bulkIterator, _bulkTree, _justStartedIteration, _readData(), currentEntry(), indri::file::BulkTreeReader::findFirst(), indri::file::BulkTreeIterator::finished(), indri::file::BulkTreeIterator::nextEntry(), indri::index::TermData::term, and indri::index::DiskTermData::termData.
bool indri::index::DiskKeyfileVocabularyIterator::nextEntry () [virtual]
Implements indri::index::VocabularyIterator.
References _bulkIterator, _justStartedIteration, _readData(), and indri::file::BulkTreeIterator::nextEntry().
void indri::index::DiskKeyfileVocabularyIterator::startIteration () [virtual]
Implements indri::index::VocabularyIterator.
References _acquire(), _bulkIterator, _justStartedIteration, _readData(), and indri::file::BulkTreeIterator::startIteration().
Member Data Documentation
int indri::index::DiskKeyfileVocabularyIterator::_baseID [private]
indri::file::BulkTreeIterator* indri::index::DiskKeyfileVocabularyIterator::_bulkIterator [private]
Referenced by _readData(), currentEntry(), DiskKeyfileVocabularyIterator(), finished(), nextEntry(), startIteration(), and ~DiskKeyfileVocabularyIterator().
indri::file::BulkTreeReader& indri::index::DiskKeyfileVocabularyIterator::_bulkTree [private]
Referenced by DiskKeyfileVocabularyIterator(), and nextEntry().
indri::utility::Buffer indri::index::DiskKeyfileVocabularyIterator::_compressedData [private]
Referenced by _readData(), and DiskKeyfileVocabularyIterator().
indri::utility::Buffer indri::index::DiskKeyfileVocabularyIterator::_decompressedData [private]
Referenced by _readData(), and DiskKeyfileVocabularyIterator().
DiskTermData* indri::index::DiskKeyfileVocabularyIterator::_diskTermData [private]
Referenced by _readData(), and currentEntry().
int indri::index::DiskKeyfileVocabularyIterator::_fieldCount [private]
Referenced by _readData(), and DiskKeyfileVocabularyIterator().
bool indri::index::DiskKeyfileVocabularyIterator::_finished [private]
bool indri::index::DiskKeyfileVocabularyIterator::_holdingLock [private]
Referenced by _acquire(), and _release().
bool indri::index::DiskKeyfileVocabularyIterator::_justStartedIteration [private]
Referenced by nextEntry(), and startIteration().
indri::thread::Mutex& indri::index::DiskKeyfileVocabularyIterator::_mutex [private]
Referenced by _acquire(), and _release().
char indri::index::DiskKeyfileVocabularyIterator::_termString[1024] [private]
Referenced by _readData().
The documentation for this class was generated from the following files:
DiskKeyfileVocabularyIterator.hpp
DiskKeyfileVocabularyIterator.cpp