Indri: indri::index::DeletedDocumentList Class Reference
indri::index::DeletedDocumentList Class Reference
#include <DeletedDocumentList.hpp>
Classes
class read_transaction
Public Member Functions
DeletedDocumentList ()
void append (DeletedDocumentList &other, int documentCount)
void markDeleted (lemur::api::DOCID_T documentID)
bool isDeleted (lemur::api::DOCID_T documentID)
UINT64 deletedCount () const
read_transaction * getReadTransaction ()
void read (const std::string &filename)
void write (const std::string &filename)
Private Member Functions
void _grow (lemur::api::DOCID_T documentID)
void _calculateDeletedCount ()
Private Attributes
bool _modified
indri::thread::ReadersWritersLock _lock
indri::thread::ReaderLockable _readLock
indri::thread::WriterLockable _writeLock
UINT64 _deletedCount
indri::utility::Buffer _bitmap
Constructor & Destructor Documentation
indri::index::DeletedDocumentList::DeletedDocumentList ()
Member Function Documentation
void indri::index::DeletedDocumentList::_calculateDeletedCount () [private]
References _bitmap, _deletedCount, indri::utility::Buffer::front(), and indri::utility::Buffer::position().
Referenced by read().
void indri::index::DeletedDocumentList::_grow (lemur::api::DOCID_T documentID) [private]
References _bitmap, indri::utility::Buffer::position(), and indri::utility::Buffer::write().
Referenced by append(), and markDeleted().
void indri::index::DeletedDocumentList::append (DeletedDocumentList & other, int documentCount)
References _bitmap, _deletedCount, _grow(), _writeLock, deletedCount(), indri::utility::Buffer::front(), indri::utility::Buffer::position(), and indri::utility::Buffer::size().
Referenced by indri::collection::Repository::_mergeBitmaps().
UINT64 indri::index::DeletedDocumentList::deletedCount () const
References _deletedCount.
Referenced by _recoverRepository(), append(), indri::server::LocalQueryServer::documentCount(), and FieldModifier::processFields().
indri::index::DeletedDocumentList::read_transaction * indri::index::DeletedDocumentList::getReadTransaction ()
Referenced by indri::collection::CompressedCollection::_copyForwardLookup(), indri::infnet::InferenceNetwork::_evaluateIndex(), indri::collection::CompressedCollection::_removeForwardLookups(), and indri::collection::CompressedCollection::_removeReverseLookups().
bool indri::index::DeletedDocumentList::isDeleted (lemur::api::DOCID_T documentID)
References _bitmap, _deletedCount, _readLock, indri::utility::Buffer::front(), and indri::utility::Buffer::position().
Referenced by indri::collection::CompressedCollection::_copyStorageData(), indri::collection::CompressedCollection::_removeForwardLookups(), indri::index::IndexWriter::_writeDirectLists(), indri::index::IndexWriter::_writeFieldList(), and remove_deleted_entries().
void indri::index::DeletedDocumentList::markDeleted (lemur::api::DOCID_T documentID)
References _bitmap, _deletedCount, _grow(), _modified, _writeLock, indri::utility::Buffer::front(), and indri::utility::Buffer::position().
Referenced by _recoverRepository(), and indri::collection::Repository::deleteDocument().
void indri::index::DeletedDocumentList::read (const std::string & filename)
References _bitmap, _calculateDeletedCount(), indri::utility::Buffer::clear(), indri::file::File::close(), indri::file::File::openRead(), indri::file::File::read(), indri::file::File::size(), and indri::utility::Buffer::write().
Referenced by indri::collection::Repository::_mergeBitmaps(), indri::collection::Repository::_mergeCompressedCollections(), indri::collection::Repository::open(), and indri::collection::Repository::openRead().
void indri::index::DeletedDocumentList::write (const std::string & filename)
References _bitmap, _modified, indri::file::File::close(), indri::file::File::create(), indri::file::Path::exists(), indri::utility::Buffer::front(), indri::utility::Buffer::position(), indri::file::Path::remove(), and indri::file::File::write().
Referenced by indri::collection::Repository::_checkpoint(), indri::collection::Repository::_mergeBitmaps(), and indri::collection::Repository::close().
Member Data Documentation
indri::utility::Buffer indri::index::DeletedDocumentList::_bitmap [private]
Referenced by _calculateDeletedCount(), _grow(), append(), isDeleted(), markDeleted(), read(), and write().
UINT64 indri::index::DeletedDocumentList::_deletedCount [private]
Referenced by _calculateDeletedCount(), append(), deletedCount(), isDeleted(), and markDeleted().
indri::thread::ReadersWritersLock indri::index::DeletedDocumentList::_lock [private]
bool indri::index::DeletedDocumentList::_modified [private]
Referenced by markDeleted(), and write().
indri::thread::ReaderLockable indri::index::DeletedDocumentList::_readLock [private]
Referenced by isDeleted().
indri::thread::WriterLockable indri::index::DeletedDocumentList::_writeLock [private]
Referenced by append(), and markDeleted().
The documentation for this class was generated from the following files:
DeletedDocumentList.hpp
DeletedDocumentList.cpp