Indri: indri::index::TermList Class Reference
indri::index::TermList Class Reference
#include <TermList.hpp>
Public Member Functions
void clear ()
void addField (const indri::index::FieldExtent &field)
void addTerm (const lemur::api::TERMID_T termID)
indri::utility::greedy_vector
< lemur::api::TERMID_T > & terms ()
const
indri::utility::greedy_vector
< lemur::api::TERMID_T > & terms () const
indri::utility::greedy_vector
< indri::index::FieldExtent > & fields ()
const
indri::utility::greedy_vector
< indri::index::FieldExtent > & fields () const
void read (const char *buffer, int size)
void write (indri::utility::Buffer &buffer)
Private Attributes
indri::utility::greedy_vector
< lemur::api::TERMID_T > _terms
indri::utility::greedy_vector
< FieldExtent > _fields
Member Function Documentation
void indri::index::TermList::addField (const indri::index::FieldExtent & field) [inline]
References _fields, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by indri::index::IndexWriter::_writeDirectLists().
void indri::index::TermList::addTerm (const lemur::api::TERMID_T termID) [inline]
References _terms, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by indri::index::IndexWriter::_writeDirectLists(), and indri::index::MemoryIndex::addDocument().
void indri::index::TermList::clear () [inline]
References _fields, _terms, and indri::utility::greedy_vector< _Type, _Count >::clear().
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::index::MemoryIndex::addDocument(), read(), and indri::index::MemoryIndexTermListFileIterator::startIteration().
const indri::utility::greedy_vector<indri::index::FieldExtent>& indri::index::TermList::fields () const [inline]
References _fields.
indri::utility::greedy_vector<indri::index::FieldExtent>& indri::index::TermList::fields () [inline]
References _fields.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::index::MemoryIndex::_writeDocumentTermList(), indri::index::MemoryIndex::_writeFieldExtents(), indri::server::LocalQueryServer::pathNames(), and indri::infnet::FieldWildcardNode::prepare().
void indri::index::TermList::read (const char * buffer, int size) [inline]
References _fields, _terms, indri::index::FieldExtent::begin, clear(), indri::index::FieldExtent::end, indri::index::FieldExtent::id, indri::index::FieldExtent::number, indri::index::FieldExtent::ordinal, indri::index::FieldExtent::parentOrdinal, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by indri::index::MemoryIndexTermListFileIterator::nextEntry(), indri::index::DiskTermListFileIterator::nextEntry(), indri::index::MemoryIndex::termList(), and indri::index::DiskIndex::termList().
const indri::utility::greedy_vector<lemur::api::TERMID_T>& indri::index::TermList::terms () const [inline]
References _terms.
indri::utility::greedy_vector<lemur::api::TERMID_T>& indri::index::TermList::terms () [inline]
References _terms.
Referenced by indri::index::IndexWriter::_writeDirectLists(), indri::index::MemoryIndex::_writeDocumentTermList(), and validate().
void indri::index::TermList::write (indri::utility::Buffer & buffer) [inline]
References _fields, _terms, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::end(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::index::IndexWriter::_writeDirectLists(), and indri::index::MemoryIndex::_writeDocumentTermList().
Member Data Documentation
indri::utility::greedy_vector<FieldExtent> indri::index::TermList::_fields [private]
Referenced by addField(), clear(), fields(), read(), and write().
indri::utility::greedy_vector<lemur::api::TERMID_T> indri::index::TermList::_terms [private]
Referenced by addTerm(), clear(), read(), terms(), and write().
The documentation for this class was generated from the following file:
TermList.hpp