Indri: indri::lang::AnnotatorNode Class Reference
indri::lang::AnnotatorNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
AnnotatorNode (ScoredExtentNode *scoredNode)
AnnotatorNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
ScoredExtentNode * getChild ()
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
ScoredExtentNode * _scoredNode
Constructor & Destructor Documentation
indri::lang::AnnotatorNode::AnnotatorNode (ScoredExtentNode * scoredNode) [inline]
Referenced by copy().
indri::lang::AnnotatorNode::AnnotatorNode (Unpacker & unpacker) [inline]
References _scoredNode, and indri::lang::Unpacker::getScoredExtentNode().
Member Function Documentation
Node* indri::lang::AnnotatorNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, indri::lang::Copier::after(), AnnotatorNode(), indri::lang::Copier::before(), indri::lang::Node::copy(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
ScoredExtentNode* indri::lang::AnnotatorNode::getChild () [inline]
References _scoredNode.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::AnnotatorNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
void indri::lang::AnnotatorNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::AnnotatorNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, and indri::lang::Node::queryText().
std::string indri::lang::AnnotatorNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::AnnotatorNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _scoredNode, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
ScoredExtentNode* indri::lang::AnnotatorNode::_scoredNode [private]
Referenced by AnnotatorNode(), copy(), getChild(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp