Indri: indri::lang::ApplyCopiers< T, NodeType > Class Template Reference
indri::lang::ApplyCopiers< T, NodeType > Class Template Reference
#include <Appliers.hpp>
Public Member Functions
ApplyCopiers (std::vector< NodeType * > &previous)
ApplyCopiers (std::vector< NodeType * > &previous, class indri::collection::Repository &repository)
ApplyCopiers (std::vector< NodeType * > &previous, class ListCache &listCache)
ApplyCopiers (std::vector< NodeType * > &previous, class indri::collection::Repository &repository, class ListCache &listCache)
~ApplyCopiers ()
std::vector< indri::lang::Node * > & roots ()
Private Attributes
std::vector< indri::lang::Node * > _roots
std::vector< T * > _copiers
template<class T, class NodeType = indri::lang::Node>
class indri::lang::ApplyCopiers< T, NodeType >
Constructor & Destructor Documentation
template<class T, class NodeType = indri::lang::Node> indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers (std::vector< NodeType * > & previous) [inline]
References indri::lang::ApplyCopiers< T, NodeType >::_copiers, indri::lang::ApplyCopiers< T, NodeType >::_roots, and indri::lang::Node::copy().
template<class T, class NodeType = indri::lang::Node> indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers (std::vector< NodeType * > & previous, class indri::collection::Repository & repository) [inline]
References indri::lang::ApplyCopiers< T, NodeType >::_copiers, indri::lang::ApplyCopiers< T, NodeType >::_roots, and indri::lang::Node::copy().
template<class T, class NodeType = indri::lang::Node> indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers (std::vector< NodeType * > & previous, class ListCache & listCache) [inline]
References indri::lang::ApplyCopiers< T, NodeType >::_copiers, indri::lang::ApplyCopiers< T, NodeType >::_roots, and indri::lang::Node::copy().
template<class T, class NodeType = indri::lang::Node> indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers (std::vector< NodeType * > & previous, class indri::collection::Repository & repository, class ListCache & listCache) [inline]
References indri::lang::ApplyCopiers< T, NodeType >::_copiers, indri::lang::ApplyCopiers< T, NodeType >::_roots, and indri::lang::Node::copy().
template<class T, class NodeType = indri::lang::Node> indri::lang::ApplyCopiers< T, NodeType >::~ApplyCopiers () [inline]
References indri::lang::ApplyCopiers< T, NodeType >::_copiers, and indri::utility::delete_vector_contents().
Member Function Documentation
template<class T, class NodeType = indri::lang::Node> std::vector<indri::lang::Node*>& indri::lang::ApplyCopiers< T, NodeType >::roots () [inline]
References indri::lang::ApplyCopiers< T, NodeType >::_roots.
Referenced by indri::api::QueryEnvironment::runQuery(), and indri::server::LocalQueryServer::runQuery().
Member Data Documentation
template<class T, class NodeType = indri::lang::Node> std::vector<T*> indri::lang::ApplyCopiers< T, NodeType >::_copiers [private]
Referenced by indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers(), and indri::lang::ApplyCopiers< T, NodeType >::~ApplyCopiers().
template<class T, class NodeType = indri::lang::Node> std::vector<indri::lang::Node*> indri::lang::ApplyCopiers< T, NodeType >::_roots [private]
Referenced by indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers(), and indri::lang::ApplyCopiers< T, NodeType >::roots().
The documentation for this class was generated from the following file:
Appliers.hpp