Indri: indri::thread::Thread Class Reference
indri::thread::Thread Class Reference
#include <Thread.hpp>
Public Member Functions
Thread (void(*function)(void *), void *data)
void execute ()
void join ()
Static Public Member Functions
static int id ()
static void sleep (int milliseconds)
static void yield ()
Private Attributes
pthread_t _thread
void(* _function)(void *data)
void * _data
Constructor & Destructor Documentation
indri::thread::Thread::Thread (void(*)(void *) function, void * data)
References _data, _function, _thread, and pthread_start().
Member Function Documentation
void indri::thread::Thread::execute ()
References _data, and _function.
Referenced by pthread_start().
int indri::thread::Thread::id () [static]
void indri::thread::Thread::join ()
References _thread.
Referenced by clean_connections(), and indri::thread::UtilityThread::join().
void indri::thread::Thread::sleep (int milliseconds) [static]
Referenced by indri::collection::Repository::_mergeStage(), indri::collection::Repository::addDocument(), and yield().
void indri::thread::Thread::yield () [static]
References sleep().
Referenced by wait_connections().
Member Data Documentation
void* indri::thread::Thread::_data [private]
Referenced by execute(), and Thread().
void(* indri::thread::Thread::_function)(void *data) [private]
Referenced by execute(), and Thread().
pthread_t indri::thread::Thread::_thread [private]
Referenced by join(), and Thread().
The documentation for this class was generated from the following files:
Thread.hpp
Thread.cpp