Indri: indri::infnet::PlusNode Class Reference
indri::infnet::PlusNode Class Reference
#include <PlusNode.hpp>
Public Member Functions
PlusNode (const std::string &name, const std::vector< BeliefNode * > &children)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Attributes
std::vector< BeliefNode * > _children
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::PlusNode::PlusNode (const std::string & name, const std::vector< BeliefNode * > & children) [inline]
Member Function Documentation
void indri::infnet::PlusNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _children, and indri::infnet::Annotator::add().
const std::string & indri::infnet::PlusNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::PlusNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::PlusNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _children.
void indri::infnet::PlusNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::PlusNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
double indri::infnet::PlusNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
lemur::api::DOCID_T indri::infnet::PlusNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::PlusNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
std::vector<BeliefNode*> indri::infnet::PlusNode::_children [private]
Referenced by annotate(), hasMatch(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<bool> indri::infnet::PlusNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::PlusNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::PlusNode::_scores [private]
Referenced by score().
The documentation for this class was generated from the following files:
PlusNode.hpp
PlusNode.cpp