Indri: Indri::indri_csharpPINVOKE::SWIGStringHelper Class Reference
Indri::indri_csharpPINVOKE::SWIGStringHelper Class Reference
Public Member Functions
delegate string SWIGStringDelegate (string message)
static void SWIGRegisterStringCallback_indri_csharp (SWIGStringDelegate stringDelegate)
Static Private Member Functions
static string CreateString (string cString)
static SWIGStringHelper ()
Static Private Attributes
static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString)
Constructor & Destructor Documentation
static Indri::indri_csharpPINVOKE::SWIGStringHelper::SWIGStringHelper () [inline, static, private]
References stringDelegate, and SWIGRegisterStringCallback_indri_csharp().
Member Function Documentation
static string Indri::indri_csharpPINVOKE::SWIGStringHelper::CreateString (string cString) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGStringHelper::SWIGRegisterStringCallback_indri_csharp (SWIGStringDelegate stringDelegate)
Referenced by SWIGStringHelper().
delegate string Indri::indri_csharpPINVOKE::SWIGStringHelper::SWIGStringDelegate (string message)
Member Data Documentation
SWIGStringDelegate Indri::indri_csharpPINVOKE::SWIGStringHelper::stringDelegate = new SWIGStringDelegate(CreateString) [static, private]
Referenced by SWIGStringHelper().
The documentation for this class was generated from the following file:
indri_csharpPINVOKE.cs