Indri: indri::lang::UWNode Class Reference
indri::lang::UWNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
UWNode ()
UWNode (int windowSize, std::vector< RawExtentNode * > &children)
UWNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void setWindowSize (int windowSize)
void setWindowSize (const std::string &windowSize)
int getWindowSize () const
const std::vector
< RawExtentNode * > & getChildren () const
void addChild (RawExtentNode *node)
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
std::vector< RawExtentNode * > _children
int _windowSize
Constructor & Destructor Documentation
indri::lang::UWNode::UWNode () [inline]
Referenced by copy().
indri::lang::UWNode::UWNode (int windowSize, std::vector< RawExtentNode * > & children) [inline]
indri::lang::UWNode::UWNode (Unpacker & unpacker) [inline]
References _children, _windowSize, indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getRawExtentVector().
Member Function Documentation
void indri::lang::UWNode::addChild (RawExtentNode * node) [inline]
References _children.
Referenced by copy(), and QueryParser::uwNode().
Node* indri::lang::UWNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _children, _windowSize, addChild(), indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), indri::lang::Node::setNodeName(), setWindowSize(), and UWNode().
const std::vector<RawExtentNode*>& indri::lang::UWNode::getChildren () const [inline]
References _children.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::lang::UWNode::getWindowSize () const [inline]
References _windowSize.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::UWNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _children, and _windowSize.
bool indri::lang::UWNode::operator== (Node & node) [inline]
References _children, _windowSize, and unordered_equal().
void indri::lang::UWNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, _windowSize, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::UWNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _children, and _windowSize.
void indri::lang::UWNode::setWindowSize (const std::string & windowSize) [inline]
References setWindowSize().
void indri::lang::UWNode::setWindowSize (int windowSize) [inline]
References _windowSize.
Referenced by copy(), setWindowSize(), and QueryParser::uwNode().
std::string indri::lang::UWNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::UWNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::UnnecessaryNodeRemoverCopier::after().
Member Data Documentation
std::vector<RawExtentNode*> indri::lang::UWNode::_children [private]
Referenced by addChild(), copy(), getChildren(), hashCode(), operator==(), pack(), queryText(), UWNode(), and walk().
int indri::lang::UWNode::_windowSize [private]
Referenced by copy(), getWindowSize(), hashCode(), operator==(), pack(), queryText(), setWindowSize(), and UWNode().
The documentation for this class was generated from the following file:
QuerySpec.hpp