Indri: indri::parse::TextDocumentExtractor Class Reference
indri::parse::TextDocumentExtractor Class Reference
#include <TextDocumentExtractor.hpp>
Public Member Functions
void open (const std::string &filename)
UnparsedDocument * nextDocument ()
void close ()
Private Attributes
std::string _filename
UnparsedDocument _document
indri::utility::Buffer _buffer
gzFile _in
Member Function Documentation
void indri::parse::TextDocumentExtractor::close () [virtual]
Implements indri::parse::DocumentIterator.
References _in.
indri::parse::UnparsedDocument * indri::parse::TextDocumentExtractor::nextDocument () [virtual]
Implements indri::parse::DocumentIterator.
References _buffer, indri::parse::DocumentIterator::_docnostring, _document, _filename, _in, indri::parse::DocumentIterator::cleanDocno(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::Buffer::clear(), indri::parse::UnparsedDocument::content, indri::parse::UnparsedDocument::contentLength, indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::parse::UnparsedDocument::metadata, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::parse::UnparsedDocument::text, indri::parse::UnparsedDocument::textLength, indri::utility::Buffer::unwrite(), indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
void indri::parse::TextDocumentExtractor::open (const std::string & filename) [virtual]
Implements indri::parse::DocumentIterator.
References _filename, and _in.
Member Data Documentation
indri::utility::Buffer indri::parse::TextDocumentExtractor::_buffer [private]
Referenced by nextDocument().
UnparsedDocument indri::parse::TextDocumentExtractor::_document [private]
Referenced by nextDocument().
std::string indri::parse::TextDocumentExtractor::_filename [private]
Referenced by nextDocument(), and open().
gzFile indri::parse::TextDocumentExtractor::_in [private]
Referenced by close(), nextDocument(), and open().
The documentation for this class was generated from the following files:
TextDocumentExtractor.hpp
TextDocumentExtractor.cpp