Indri: indri::parse::Parser Class Reference
indri::parse::Parser Class Reference
#include <IndriParser.hpp>
Public Member Functions
virtual ~Parser ()
virtual
indri::api::ParsedDocument * parse (TokenizedDocument *document)=0
virtual void setTags (const std::vector< std::string > &include, const std::vector< std::string > &exclude, const std::vector< std::string > &index, const std::vector< std::string > &metadata, const std::map< ConflationPattern *, std::string > &conflations)=0
virtual void handle (TokenizedDocument *document)=0
virtual void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)=0
Constructor & Destructor Documentation
virtual indri::parse::Parser::~Parser () [inline, virtual]
Member Function Documentation
virtual void indri::parse::Parser::handle (TokenizedDocument * document) [pure virtual]
Implements indri::parse::ObjectHandler< TokenizedDocument >.
Implemented in indri::parse::TaggedTextParser, and indri::parse::TextParser.
virtual indri::api::ParsedDocument* indri::parse::Parser::parse (TokenizedDocument * document) [pure virtual]
Implemented in indri::parse::TaggedTextParser, and indri::parse::TextParser.
Referenced by indri::api::IndexEnvironment::addFile(), and indri::api::IndexEnvironment::addString().
virtual void indri::parse::Parser::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [pure virtual]
Implemented in indri::parse::TaggedTextParser, and indri::parse::TextParser.
virtual void indri::parse::Parser::setTags (const std::vector< std::string > & include, const std::vector< std::string > & exclude, const std::vector< std::string > & index, const std::vector< std::string > & metadata, const std::map< ConflationPattern *, std::string > & conflations) [pure virtual]
Implemented in indri::parse::TextParser.
Referenced by indri::parse::ParserFactory::get().
The documentation for this class was generated from the following file:
IndriParser.hpp