Indri: indri::index::DiskDocumentDataIterator Class Reference
indri::index::DiskDocumentDataIterator Class Reference
#include <DiskDocumentDataIterator.hpp>
Public Member Functions
DiskDocumentDataIterator (indri::file::File &documentDataFile)
~DiskDocumentDataIterator ()
void startIteration ()
bool nextEntry ()
const DocumentData * currentEntry ()
bool finished ()
Private Attributes
indri::file::SequentialReadBuffer * _readBuffer
UINT64 _fileSize
DocumentData _documentData
indri::file::File & _documentDataFile
bool _finished
Constructor & Destructor Documentation
indri::index::DiskDocumentDataIterator::DiskDocumentDataIterator (indri::file::File & documentDataFile)
indri::index::DiskDocumentDataIterator::~DiskDocumentDataIterator ()
References _readBuffer.
Member Function Documentation
const indri::index::DocumentData * indri::index::DiskDocumentDataIterator::currentEntry () [virtual]
Implements indri::index::DocumentDataIterator.
References _documentData, and finished().
bool indri::index::DiskDocumentDataIterator::finished () [virtual]
Implements indri::index::DocumentDataIterator.
References _finished.
Referenced by currentEntry().
bool indri::index::DiskDocumentDataIterator::nextEntry () [virtual]
Implements indri::index::DocumentDataIterator.
References _documentData, _fileSize, _finished, _readBuffer, indri::file::SequentialReadBuffer::position(), and indri::file::SequentialReadBuffer::read().
void indri::index::DiskDocumentDataIterator::startIteration () [virtual]
Implements indri::index::DocumentDataIterator.
References _documentData, _documentDataFile, _fileSize, _finished, _readBuffer, indri::file::SequentialReadBuffer::read(), indri::file::SequentialReadBuffer::seek(), and indri::file::File::size().
Member Data Documentation
DocumentData indri::index::DiskDocumentDataIterator::_documentData [private]
Referenced by currentEntry(), nextEntry(), and startIteration().
indri::file::File& indri::index::DiskDocumentDataIterator::_documentDataFile [private]
Referenced by startIteration().
UINT64 indri::index::DiskDocumentDataIterator::_fileSize [private]
Referenced by nextEntry(), and startIteration().
bool indri::index::DiskDocumentDataIterator::_finished [private]
Referenced by finished(), nextEntry(), and startIteration().
indri::file::SequentialReadBuffer* indri::index::DiskDocumentDataIterator::_readBuffer [private]
Referenced by nextEntry(), startIteration(), and ~DiskDocumentDataIterator().
The documentation for this class was generated from the following files:
DiskDocumentDataIterator.hpp
DiskDocumentDataIterator.cpp