Indri: indri::api::SnippetBuilder Class Reference
indri::api::SnippetBuilder Class Reference
#include <SnippetBuilder.hpp>
Classes
struct Region
Public Member Functions
SnippetBuilder (bool html)
std::string build (int documentID, const indri::api::ParsedDocument *document, indri::api::QueryAnnotation *annotation)
Private Member Functions
void _getRawNodes (std::vector< std::string > &nodeNames, const indri::api::QueryAnnotationNode *node)
std::vector< std::pair
< indri::index::Extent, int > > _documentMatches (int document, const std::map< std::string, std::vector< indri::api::ScoredExtentResult > > &annotations, const std::vector< std::string > &nodeNames)
std::vector< Region > _buildRegions (std::vector< std::pair< indri::index::Extent, int > > &extents, int positionCount, int matchWidth, int windowWidth)
Region _bestRegion (const std::vector< std::pair< indri::index::Extent, int > > &extents, const std::vector< indri::api::SnippetBuilder::Region > &skipRegions, int positionCount, int windowWidth)
char * _sanitizeText (const char *text, int begin, int length)
void _addEllipsis (std::string &snippet)
void _addHighlightedRegion (std::string &snippet, char *region)
void _addUnhighlightedRegion (std::string &snippet, char *region)
void _completeSnippet (std::string &snippet)
Private Attributes
bool _HTMLOutput
Constructor & Destructor Documentation
indri::api::SnippetBuilder::SnippetBuilder (bool html) [inline]
Member Function Documentation
void indri::api::SnippetBuilder::_addEllipsis (std::string & snippet) [private]
References _HTMLOutput.
Referenced by build().
void indri::api::SnippetBuilder::_addHighlightedRegion (std::string & snippet, char * region) [private]
References _HTMLOutput.
Referenced by build().
void indri::api::SnippetBuilder::_addUnhighlightedRegion (std::string & snippet, char * region) [private]
References _HTMLOutput.
Referenced by build().
indri::api::SnippetBuilder::Region indri::api::SnippetBuilder::_bestRegion (const std::vector< std::pair< indri::index::Extent, int > > & extents, const std::vector< indri::api::SnippetBuilder::Region > & skipRegions, int positionCount, int windowWidth) [private]
References indri::api::SnippetBuilder::Region::begin, indri::api::SnippetBuilder::Region::end, indri::api::SnippetBuilder::Region::extents, and should_skip().
Referenced by _buildRegions().
std::vector< indri::api::SnippetBuilder::Region > indri::api::SnippetBuilder::_buildRegions (std::vector< std::pair< indri::index::Extent, int > > & extents, int positionCount, int matchWidth, int windowWidth) [private]
References _bestRegion(), indri::api::SnippetBuilder::Region::begin, indri::api::SnippetBuilder::Region::end, and sort_regions().
Referenced by build().
void indri::api::SnippetBuilder::_completeSnippet (std::string & snippet) [private]
References _HTMLOutput.
Referenced by build().
std::vector< std::pair< indri::index::Extent, int > > indri::api::SnippetBuilder::_documentMatches (int document, const std::map< std::string, std::vector< indri::api::ScoredExtentResult > > & annotations, const std::vector< std::string > & nodeNames) [private]
References indri::index::Extent::begin, indri::index::Extent::end, and sort_extent_pairs().
Referenced by build().
void indri::api::SnippetBuilder::_getRawNodes (std::vector< std::string > & nodeNames, const indri::api::QueryAnnotationNode * node) [private]
References indri::api::QueryAnnotationNode::children, indri::api::QueryAnnotationNode::name, and indri::api::QueryAnnotationNode::type.
Referenced by build().
char * indri::api::SnippetBuilder::_sanitizeText (const char * text, int begin, int length) [private]
Referenced by build().
std::string indri::api::SnippetBuilder::build (int documentID, const indri::api::ParsedDocument * document, indri::api::QueryAnnotation * annotation)
References _addEllipsis(), _addHighlightedRegion(), _addUnhighlightedRegion(), _buildRegions(), _completeSnippet(), _documentMatches(), _getRawNodes(), _sanitizeText(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::api::SnippetBuilder::Region::begin, indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::SnippetBuilder::Region::end, indri::api::SnippetBuilder::Region::extents, indri::api::QueryAnnotation::getAnnotations(), indri::api::QueryAnnotation::getQueryTree(), indri::api::ParsedDocument::positions, indri::utility::greedy_vector< _Type, _Count >::size(), and indri::api::ParsedDocument::text.
Referenced by QueryThread::_printResultRegion(), and indri::api::QueryEnvironment::runQuery().
Member Data Documentation
bool indri::api::SnippetBuilder::_HTMLOutput [private]
Referenced by _addEllipsis(), _addHighlightedRegion(), _addUnhighlightedRegion(), and _completeSnippet().
The documentation for this class was generated from the following files:
SnippetBuilder.hpp
SnippetBuilder.cpp