Indri: indri::infnet::BeliefNode Class Reference
indri::infnet::BeliefNode Class Reference
#include <BeliefNode.hpp>
Public Member Functions
virtual double maximumBackgroundScore ()=0
virtual double maximumScore ()=0
virtual const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)=0
virtual bool hasMatch (lemur::api::DOCID_T documentID)=0
virtual const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)=0
virtual void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)=0
virtual void setSiblingsFlag (int f)
Protected Attributes
int bSiblings
flag (and potential counter) for if belief node has siblings
Member Function Documentation
virtual void indri::infnet::BeliefNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [pure virtual]
Implemented in indri::infnet::ContextInclusionAndNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullScorerNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::NotNode::annotate(), indri::infnet::LengthPriorNode::annotate(), indri::infnet::FixedPassageNode::annotate(), indri::infnet::FilterRequireNode::annotate(), indri::infnet::FilterRejectNode::annotate(), indri::infnet::FilterNode::annotate(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ExtentEnforcementNode::annotate(), and indri::infnet::Annotator::evaluate().
virtual const indri::utility::greedy_vector<bool>& indri::infnet::BeliefNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [pure virtual]
Implemented in indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextInclusionAndNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullScorerNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
virtual bool indri::infnet::BeliefNode::hasMatch (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextInclusionAndNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullScorerNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::FixedPassageNode::annotate(), indri::infnet::ExtentRestrictionNode::annotate(), indri::infnet::ScoredExtentAccumulator::evaluate(), indri::infnet::NotNode::hasMatch(), indri::infnet::LengthPriorNode::hasMatch(), indri::infnet::FixedPassageNode::hasMatch(), indri::infnet::FilterRequireNode::hasMatch(), indri::infnet::FilterRejectNode::hasMatch(), indri::infnet::ExtentRestrictionNode::hasMatch(), indri::infnet::ExtentEnforcementNode::hasMatch(), indri::infnet::ContextInclusionAndNode::hasMatch(), indri::infnet::FixedPassageNode::score(), and indri::infnet::ExtentRestrictionNode::score().
virtual double indri::infnet::BeliefNode::maximumBackgroundScore () [pure virtual]
Implemented in indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextInclusionAndNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullScorerNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::WeightedAndNode::addChild(), indri::infnet::ContextInclusionAndNode::addChild(), indri::infnet::NotNode::maximumBackgroundScore(), indri::infnet::FilterRequireNode::maximumBackgroundScore(), indri::infnet::FilterRejectNode::maximumBackgroundScore(), and indri::infnet::FilterNode::maximumBackgroundScore().
virtual double indri::infnet::BeliefNode::maximumScore () [pure virtual]
Implemented in indri::infnet::CachedFrequencyBeliefNode, indri::infnet::ContextInclusionAndNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullScorerNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::WeightedAndNode::addChild(), indri::infnet::ContextInclusionAndNode::addChild(), indri::infnet::FilterRequireNode::maximumScore(), indri::infnet::FilterRejectNode::maximumScore(), and indri::infnet::FilterNode::maximumScore().
virtual const indri::utility::greedy_vector<indri::api::ScoredExtentResult>& indri::infnet::BeliefNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [pure virtual]
Implemented in indri::infnet::ContextInclusionAndNode, indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRejectNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::ListBeliefNode, indri::infnet::MaxNode, indri::infnet::NestedListBeliefNode, indri::infnet::NotNode, indri::infnet::NullScorerNode, indri::infnet::OrNode, indri::infnet::PlusNode, indri::infnet::PriorNode, indri::infnet::ShrinkageBeliefNode, indri::infnet::TermFrequencyBeliefNode, indri::infnet::WeightedAndNode, indri::infnet::WeightedSumNode, and indri::infnet::WPlusNode.
Referenced by indri::infnet::ScoredExtentAccumulator::evaluate(), indri::infnet::NotNode::score(), indri::infnet::LengthPriorNode::score(), indri::infnet::FixedPassageNode::score(), indri::infnet::FilterRequireNode::score(), indri::infnet::FilterRejectNode::score(), indri::infnet::FilterNode::score(), indri::infnet::ExtentRestrictionNode::score(), and indri::infnet::ExtentEnforcementNode::score().
virtual void indri::infnet::BeliefNode::setSiblingsFlag (int f) [inline, virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented in indri::infnet::ExtentEnforcementNode, indri::infnet::ExtentRestrictionNode, indri::infnet::FilterNode, indri::infnet::FilterRequireNode, indri::infnet::FixedPassageNode, indri::infnet::LengthPriorNode, indri::infnet::NotNode, indri::infnet::OrNode, indri::infnet::WeightedAndNode, and indri::infnet::WeightedSumNode.
References bSiblings.
Referenced by indri::infnet::WeightedSumNode::addChild(), indri::infnet::WeightedAndNode::addChild(), indri::infnet::NotNode::setSiblingsFlag(), indri::infnet::LengthPriorNode::setSiblingsFlag(), indri::infnet::FixedPassageNode::setSiblingsFlag(), indri::infnet::FilterRequireNode::setSiblingsFlag(), indri::infnet::FilterNode::setSiblingsFlag(), indri::infnet::ExtentRestrictionNode::setSiblingsFlag(), and indri::infnet::ExtentEnforcementNode::setSiblingsFlag().
Member Data Documentation
int indri::infnet::BeliefNode::bSiblings [protected]
flag (and potential counter) for if belief node has siblings
Referenced by indri::infnet::ExtentRestrictionNode::ExtentRestrictionNode(), indri::infnet::ExtentRestrictionNode::score(), indri::infnet::NotNode::setSiblingsFlag(), indri::infnet::LengthPriorNode::setSiblingsFlag(), indri::infnet::FixedPassageNode::setSiblingsFlag(), indri::infnet::FilterRequireNode::setSiblingsFlag(), indri::infnet::FilterNode::setSiblingsFlag(), indri::infnet::ExtentRestrictionNode::setSiblingsFlag(), indri::infnet::ExtentEnforcementNode::setSiblingsFlag(), and setSiblingsFlag().
The documentation for this class was generated from the following file:
BeliefNode.hpp