Indri: indri::lang::QueryNodeBuilder Class Reference
indri::lang::QueryNodeBuilder Class Reference
Public Member Functions
QueryNodeBuilder ()
void defaultBefore (indri::lang::Node *n)
void defaultAfter (indri::lang::Node *n)
indri::api::QueryAnnotationNode * getRoot ()
Private Attributes
indri::api::QueryAnnotationNode * _root
std::map< indri::lang::Node
*, indri::api::QueryAnnotationNode * > _nodes
std::stack
< indri::api::QueryAnnotationNode * > _stack
Constructor & Destructor Documentation
indri::lang::QueryNodeBuilder::QueryNodeBuilder () [inline]
Member Function Documentation
void indri::lang::QueryNodeBuilder::defaultAfter (indri::lang::Node * n) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _stack.
void indri::lang::QueryNodeBuilder::defaultBefore (indri::lang::Node * n) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _nodes, _root, _stack, indri::api::QueryAnnotationNode::name, indri::lang::Node::nodeName(), indri::lang::Node::queryText(), indri::api::QueryAnnotationNode::queryText, indri::api::QueryAnnotationNode::type, and indri::lang::Node::typeName().
indri::api::QueryAnnotationNode* indri::lang::QueryNodeBuilder::getRoot () [inline]
References _root.
Referenced by indri::api::QueryAnnotation::QueryAnnotation().
Member Data Documentation
std::map< indri::lang::Node*, indri::api::QueryAnnotationNode* > indri::lang::QueryNodeBuilder::_nodes [private]
Referenced by defaultBefore().
indri::api::QueryAnnotationNode* indri::lang::QueryNodeBuilder::_root [private]
Referenced by defaultBefore(), and getRoot().
std::stack< indri::api::QueryAnnotationNode* > indri::lang::QueryNodeBuilder::_stack [private]
Referenced by defaultAfter(), and defaultBefore().
The documentation for this class was generated from the following file:
QueryAnnotation.cpp