Indri: indri::parse::TaggedTextParser Class Reference
indri::parse::TaggedTextParser Class Reference
#include <TaggedTextParser.hpp>
Classes
struct tag_properties
Public Member Functions
TaggedTextParser ()
~TaggedTextParser ()
void setTags (const std::vector< std::string > &include, const std::vector< std::string > &exclude, const std::vector< std::string > &index, const std::vector< std::string > &metadata, const std::map< indri::parse::ConflationPattern *, std::string > &conflations)
indri::api::ParsedDocument * parse (TokenizedDocument *document)
void handle (TokenizedDocument *document)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &h)
Protected Types
typedef
indri::utility::HashTable
< std::string, std::string > StrHashTable
Protected Member Functions
virtual void initialize (TokenizedDocument *document, indri::api::ParsedDocument *parsed)
virtual void cleanup (TokenizedDocument *document, indri::api::ParsedDocument *parsed)
void addTag (const char *s, const char *c, int pos)
void endTag (const char *s, const char *c, int pos)
void addMetadataTag (const char *s, const char *c, int pos)
void endMetadataTag (const char *s, const char *c, int pos)
tag_properties * _findTag (std::string name)
tag_properties * _buildTag (std::string name)
virtual void handleTag (TagEvent *te)
Protected Attributes
Conflater * _p_conflater
TagList * tl
TagList * _metaList
indri::utility::Buffer _termBuffer
indri::utility::HashTable
< const char *, tag_properties * > _tagTable
const tag_properties * _startExcludeRegion
const tag_properties * _startIncludeRegion
bool _exclude
bool _include
bool _defaultInclude
unsigned int token_pos
unsigned int tokens_excluded
indri::api::ParsedDocument _document
Private Attributes
ObjectHandler
< indri::api::ParsedDocument > * _handler
Member Typedef Documentation
typedef indri::utility::HashTable<std::string, std::string> indri::parse::TaggedTextParser::StrHashTable [protected]
Constructor & Destructor Documentation
indri::parse::TaggedTextParser::TaggedTextParser ()
References _defaultInclude, _exclude, _include, _startExcludeRegion, and _startIncludeRegion.
indri::parse::TaggedTextParser::~TaggedTextParser ()
References _document, _metaList, _p_conflater, _tagTable, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::tags, and tl.
Member Function Documentation
indri::parse::TaggedTextParser::tag_properties * indri::parse::TaggedTextParser::_buildTag (std::string name) [protected]
References _findTag(), _tagTable, indri::parse::TaggedTextParser::tag_properties::exclude, indri::parse::TaggedTextParser::tag_properties::include, indri::parse::TaggedTextParser::tag_properties::index, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::parse::TaggedTextParser::tag_properties::metadata, and indri::parse::TaggedTextParser::tag_properties::name.
Referenced by setTags().
indri::parse::TaggedTextParser::tag_properties * indri::parse::TaggedTextParser::_findTag (std::string name) [protected]
References _tagTable, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
Referenced by _buildTag(), handleTag(), and indri::parse::HTMLParser::initialize().
void indri::parse::TaggedTextParser::addMetadataTag (const char * s, const char * c, int pos) [inline, protected]
References _metaList, and indri::parse::TagList::addTag().
Referenced by handleTag().
void indri::parse::TaggedTextParser::addTag (const char * s, const char * c, int pos) [inline, protected]
References indri::parse::TagList::addTag(), and tl.
Referenced by handleTag(), and indri::parse::HTMLParser::handleTag().
void indri::parse::TaggedTextParser::cleanup (TokenizedDocument * document, indri::api::ParsedDocument * parsed) [protected, virtual]
Reimplemented in indri::parse::HTMLParser.
References _metaList, _termBuffer, indri::api::ParsedDocument::metadata, indri::api::ParsedDocument::tags, indri::parse::TokenizedDocument::text, tl, indri::parse::TagList::writeMetadataList(), and indri::parse::TagList::writeTagList().
Referenced by parse().
void indri::parse::TaggedTextParser::endMetadataTag (const char * s, const char * c, int pos) [inline, protected]
References _metaList, and indri::parse::TagList::endTag().
Referenced by handleTag().
void indri::parse::TaggedTextParser::endTag (const char * s, const char * c, int pos) [inline, protected]
References indri::parse::TagList::endTag(), and tl.
Referenced by handleTag(), and indri::parse::HTMLParser::handleTag().
void indri::parse::TaggedTextParser::handle (TokenizedDocument * document) [virtual]
Implements indri::parse::Parser.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and parse().
void indri::parse::TaggedTextParser::handleTag (TagEvent * te) [protected, virtual]
Reimplemented in indri::parse::HTMLParser.
References _exclude, _findTag(), _include, _p_conflater, _startExcludeRegion, _startIncludeRegion, addMetadataTag(), addTag(), indri::parse::TagEvent::begin, indri::parse::Conflater::conflate(), indri::parse::TagEvent::end, endMetadataTag(), endTag(), indri::parse::TaggedTextParser::tag_properties::exclude, indri::parse::TaggedTextParser::tag_properties::include, indri::parse::TaggedTextParser::tag_properties::index, indri::parse::TaggedTextParser::tag_properties::metadata, indri::parse::TaggedTextParser::tag_properties::name, indri::parse::TagEvent::name, indri::parse::TagEvent::open_tag, and indri::parse::TagEvent::pos.
Referenced by parse().
void indri::parse::TaggedTextParser::initialize (TokenizedDocument * document, indri::api::ParsedDocument * parsed) [protected, virtual]
Reimplemented in indri::parse::HTMLParser.
References _defaultInclude, _exclude, _include, _metaList, _startExcludeRegion, _startIncludeRegion, indri::parse::TagList::clear(), and tl.
Referenced by parse().
indri::api::ParsedDocument * indri::parse::TaggedTextParser::parse (TokenizedDocument * document) [virtual]
Implements indri::parse::Parser.
References _document, _exclude, _include, _p_conflater, _termBuffer, indri::parse::TagEvent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), cleanup(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::Buffer::clear(), indri::parse::Conflater::conflate(), indri::parse::TokenizedDocument::content, indri::api::ParsedDocument::content, indri::parse::TokenizedDocument::contentLength, indri::api::ParsedDocument::contentLength, indri::utility::greedy_vector< _Type, _Count >::end(), indri::parse::TagEvent::end, indri::utility::Buffer::grow(), handleTag(), initialize(), indri::parse::TokenizedDocument::metadata, indri::api::ParsedDocument::metadata, indri::parse::TagEvent::name, indri::parse::TagEvent::open_tag, indri::parse::TagEvent::pos, indri::parse::TokenizedDocument::positions, indri::api::ParsedDocument::positions, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::parse::TokenizedDocument::tags, indri::api::ParsedDocument::tags, indri::parse::TokenizedDocument::terms, indri::api::ParsedDocument::terms, indri::parse::TokenizedDocument::text, indri::api::ParsedDocument::text, indri::api::ParsedDocument::textLength, indri::parse::TokenizedDocument::textLength, token_pos, and tokens_excluded.
Referenced by handle(), and harvest_anchor_text_file().
void indri::parse::TaggedTextParser::setHandler (ObjectHandler< indri::api::ParsedDocument > & h) [virtual]
Implements indri::parse::Parser.
References _handler.
void indri::parse::TaggedTextParser::setTags (const std::vector< std::string > & include, const std::vector< std::string > & exclude, const std::vector< std::string > & index, const std::vector< std::string > & metadata, const std::map< indri::parse::ConflationPattern *, std::string > & conflations)
References _buildTag(), _defaultInclude, _p_conflater, indri::parse::TaggedTextParser::tag_properties::exclude, indri::parse::TaggedTextParser::tag_properties::include, indri::parse::TaggedTextParser::tag_properties::index, and indri::parse::TaggedTextParser::tag_properties::metadata.
Referenced by harvest_anchor_text().
Member Data Documentation
bool indri::parse::TaggedTextParser::_defaultInclude [protected]
Referenced by initialize(), setTags(), and TaggedTextParser().
indri::api::ParsedDocument indri::parse::TaggedTextParser::_document [protected]
Referenced by indri::parse::HTMLParser::handleTag(), parse(), and ~TaggedTextParser().
bool indri::parse::TaggedTextParser::_exclude [protected]
Referenced by handleTag(), indri::parse::HTMLParser::handleTag(), initialize(), parse(), and TaggedTextParser().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::TaggedTextParser::_handler [private]
Referenced by handle(), and setHandler().
bool indri::parse::TaggedTextParser::_include [protected]
Referenced by handleTag(), indri::parse::HTMLParser::handleTag(), initialize(), parse(), and TaggedTextParser().
TagList* indri::parse::TaggedTextParser::_metaList [protected]
Referenced by addMetadataTag(), cleanup(), endMetadataTag(), initialize(), and ~TaggedTextParser().
Conflater* indri::parse::TaggedTextParser::_p_conflater [protected]
Referenced by handleTag(), indri::parse::HTMLParser::handleTag(), parse(), setTags(), and ~TaggedTextParser().
const tag_properties* indri::parse::TaggedTextParser::_startExcludeRegion [protected]
Referenced by handleTag(), initialize(), and TaggedTextParser().
const tag_properties* indri::parse::TaggedTextParser::_startIncludeRegion [protected]
Referenced by handleTag(), initialize(), and TaggedTextParser().
indri::utility::HashTable<const char*,tag_properties*> indri::parse::TaggedTextParser::_tagTable [protected]
Referenced by _buildTag(), _findTag(), and ~TaggedTextParser().
indri::utility::Buffer indri::parse::TaggedTextParser::_termBuffer [protected]
Referenced by cleanup(), and parse().
TagList* indri::parse::TaggedTextParser::tl [protected]
Referenced by addTag(), cleanup(), endTag(), initialize(), and ~TaggedTextParser().
unsigned int indri::parse::TaggedTextParser::token_pos [protected]
Referenced by parse().
unsigned int indri::parse::TaggedTextParser::tokens_excluded [protected]
Referenced by indri::parse::HTMLParser::handleTag(), and parse().
The documentation for this class was generated from the following files:
TaggedTextParser.hpp
TaggedTextParser.cpp