Indri: indri::net::XMLReplyReceiver Class Reference
indri::net::XMLReplyReceiver Class Reference
#include <NetworkMessageStream.hpp>
Public Member Functions
XMLReplyReceiver ()
~XMLReplyReceiver ()
void request (indri::xml::XMLNode *node)
void reply (indri::xml::XMLNode *reply)
void reply (const std::string &name, const void *buffer, unsigned int length)
void replyDone ()
void error (const std::string &e)
indri::xml::XMLNode * getReply ()
bool done ()
void wait (class NetworkMessageStream *stream)
Private Attributes
bool _done
std::string _exception
indri::xml::XMLNode * _reply
Constructor & Destructor Documentation
indri::net::XMLReplyReceiver::XMLReplyReceiver () [inline]
indri::net::XMLReplyReceiver::~XMLReplyReceiver ()
References _reply.
Member Function Documentation
bool indri::net::XMLReplyReceiver::done () [inline]
References _done.
Referenced by wait().
void indri::net::XMLReplyReceiver::error (const std::string & e) [inline, virtual]
Implements indri::net::MessageStreamHandler.
References _done, and _exception.
indri::xml::XMLNode* indri::net::XMLReplyReceiver::getReply () [inline]
References _reply.
Referenced by indri::server::NetworkServerProxy::_numericRequest(), indri::server::NetworkServerProxy::_stringRequest(), indri::server::NetworkServerProxy::fieldList(), indri::server::NetworkServerProxyDocumentIDsResponse::getResults(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyMetadataResponse::getResults(), and indri::server::NetworkServerProxyDocumentsResponse::getResults().
void indri::net::XMLReplyReceiver::reply (const std::string & name, const void * buffer, unsigned int length) [inline, virtual]
Implements indri::net::MessageStreamHandler.
References _done, and _exception.
void indri::net::XMLReplyReceiver::reply (indri::xml::XMLNode * reply) [inline, virtual]
Implements indri::net::MessageStreamHandler.
References _reply.
void indri::net::XMLReplyReceiver::replyDone () [inline, virtual]
Implements indri::net::MessageStreamHandler.
References _done.
void indri::net::XMLReplyReceiver::request (indri::xml::XMLNode * node) [inline, virtual]
Implements indri::net::MessageStreamHandler.
References _done, and _exception.
void indri::net::XMLReplyReceiver::wait (class NetworkMessageStream * stream)
References _exception, indri::net::NetworkMessageStream::alive(), done(), and indri::net::NetworkMessageStream::read().
Referenced by indri::server::NetworkServerProxy::_numericRequest(), indri::server::NetworkServerProxy::_stringRequest(), indri::server::NetworkServerProxy::fieldList(), indri::server::NetworkServerProxyDocumentIDsResponse::getResults(), indri::server::NetworkServerProxyVectorsResponse::getResults(), indri::server::NetworkServerProxyMetadataResponse::getResults(), and indri::server::NetworkServerProxyDocumentsResponse::getResults().
Member Data Documentation
bool indri::net::XMLReplyReceiver::_done [private]
Referenced by done(), error(), reply(), replyDone(), and request().
std::string indri::net::XMLReplyReceiver::_exception [private]
Referenced by error(), reply(), request(), and wait().
indri::xml::XMLNode* indri::net::XMLReplyReceiver::_reply [private]
Referenced by getReply(), reply(), and ~XMLReplyReceiver().
The documentation for this class was generated from the following files:
NetworkMessageStream.hpp
NetworkMessageStream.cpp