Indri: indri::infnet::LengthPriorNode Class Reference
indri::infnet::LengthPriorNode Class Reference
#include <LengthPriorNode.hpp>
Public Member Functions
LengthPriorNode (const std::string &name, BeliefNode *child, double exponent)
~LengthPriorNode ()
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
double maximumScore ()
double maximumBackgroundScore ()
const std::string & getName () const
virtual void setSiblingsFlag (int f)
Private Attributes
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
BeliefNode * _child
std::string _name
double _exponent
Constructor & Destructor Documentation
indri::infnet::LengthPriorNode::LengthPriorNode (const std::string & name, BeliefNode * child, double exponent)
indri::infnet::LengthPriorNode::~LengthPriorNode ()
Member Function Documentation
void indri::infnet::LengthPriorNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _child, indri::infnet::Annotator::add(), and indri::infnet::BeliefNode::annotate().
const std::string & indri::infnet::LengthPriorNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::LengthPriorNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::hasMatch().
bool indri::infnet::LengthPriorNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::hasMatch().
void indri::infnet::LengthPriorNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::LengthPriorNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_TINY_SCORE.
double indri::infnet::LengthPriorNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_HUGE_SCORE.
lemur::api::DOCID_T indri::infnet::LengthPriorNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _child, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::LengthPriorNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _exponent, _scores, indri::api::ScoredExtentResult::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::utility::greedy_vector< _Type, _Count >::end(), INDRI_TINY_SCORE, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, indri::infnet::BeliefNode::score(), and indri::utility::greedy_vector< _Type, _Count >::size().
virtual void indri::infnet::LengthPriorNode::setSiblingsFlag (int f) [inline, virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _child, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
BeliefNode* indri::infnet::LengthPriorNode::_child [private]
Referenced by annotate(), hasMatch(), nextCandidateDocument(), score(), and setSiblingsFlag().
double indri::infnet::LengthPriorNode::_exponent [private]
Referenced by score().
std::string indri::infnet::LengthPriorNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::LengthPriorNode::_scores [private]
Referenced by score().
The documentation for this class was generated from the following files:
LengthPriorNode.hpp
LengthPriorNode.cpp