Indri: indri::parse::ObjectHandler< _Type > Class Template Reference
indri::parse::ObjectHandler< _Type > Class Template Reference
#include <ObjectHandler.hpp>
Public Member Functions
virtual ~ObjectHandler ()
virtual void handle (_Type *object)=0
template<class _Type>
class indri::parse::ObjectHandler< _Type >
Constructor & Destructor Documentation
template<class _Type> virtual indri::parse::ObjectHandler< _Type >::~ObjectHandler () [inline, virtual]
Member Function Documentation
template<class _Type> virtual void indri::parse::ObjectHandler< _Type >::handle (_Type * object) [pure virtual]
Implemented in indri::parse::AnchorTextAnnotator, indri::parse::AnchorTextHarvester, indri::parse::AnchorTextWriter, indri::parse::ArabicStemmerTransformation, indri::parse::Parser, indri::parse::Tokenizer, indri::parse::KrovetzStemmerTransformation, indri::parse::NormalizationTransformation, indri::parse::NumericFieldAnnotator, indri::parse::OffsetAnnotationAnnotator, indri::parse::OffsetMetadataAnnotator, indri::parse::PorterStemmerTransformation, indri::parse::StopperTransformation, indri::parse::TaggedTextParser, indri::parse::TextParser, indri::parse::TextTokenizer, indri::parse::Transformation, indri::parse::URLTextAnnotator, and indri::parse::UTF8CaseNormalizationTransformation.
Referenced by indri::parse::UTF8CaseNormalizationTransformation::handle(), indri::parse::URLTextAnnotator::handle(), indri::parse::TaggedTextParser::handle(), indri::parse::StopperTransformation::handle(), indri::parse::PorterStemmerTransformation::handle(), indri::parse::OffsetMetadataAnnotator::handle(), indri::parse::OffsetAnnotationAnnotator::handle(), indri::parse::NumericFieldAnnotator::handle(), indri::parse::NormalizationTransformation::handle(), indri::parse::KrovetzStemmerTransformation::handle(), indri::parse::ArabicStemmerTransformation::handle(), and indri::parse::AnchorTextAnnotator::handle().
The documentation for this class was generated from the following file:
ObjectHandler.hpp