Indri: indri::parse::Uint64Comp Class Reference
indri::parse::Uint64Comp Class Reference
#include <uint64comp.hpp>
Public Member Functions
Uint64Comp ()
Static Public Member Functions
static size_t u_strlen (const UINT64 *s)
static int u_strncmp (const UINT64 *s1, const UINT64 *s2, size_t n)
static int u_strcmp (const UINT64 *s1, const UINT64 *s2)
static UINT64 * u_strcpy (UINT64 *s1, const UINT64 *s2)
static UINT64 * u_strdup (UINT64 *s)
Constructor & Destructor Documentation
indri::parse::Uint64Comp::Uint64Comp ()
Member Function Documentation
int indri::parse::Uint64Comp::u_strcmp (const UINT64 * s1, const UINT64 * s2) [static]
Referenced by indri::parse::Arabic_Stemmer_utf8::ltstr_unicode::operator()().
UINT64 * indri::parse::Uint64Comp::u_strcpy (UINT64 * s1, const UINT64 * s2) [static]
Referenced by indri::parse::Arabic_Stemmer_utf8::arabic_light10_stop_unicode(), indri::parse::Arabic_Stemmer_utf8::arabic_light10_unicode(), indri::parse::Arabic_Stemmer_utf8::arabic_stop_unicode(), indri::parse::Arabic_Stemmer_utf8::no_stem_unicode(), indri::parse::Arabic_Stemmer_utf8::remove_all_suffixes_unicode(), indri::parse::Arabic_Stemmer_utf8::remove_definite_articles_unicode(), and u_strdup().
UINT64 * indri::parse::Uint64Comp::u_strdup (UINT64 * s) [static]
References u_strcpy(), and u_strlen().
Referenced by indri::parse::Arabic_Stemmer_utf8::arabic_light10_stop_unicode(), and indri::parse::Arabic_Stemmer_utf8::arabic_light10_unicode().
size_t indri::parse::Uint64Comp::u_strlen (const UINT64 * s) [static]
Referenced by indri::parse::Arabic_Stemmer_utf8::arabic_light10_stop_unicode(), indri::parse::Arabic_Stemmer_utf8::arabic_light10_unicode(), indri::parse::Arabic_Stemmer_utf8::remove_all_suffixes_unicode(), indri::parse::Arabic_Stemmer_utf8::remove_definite_articles_unicode(), and u_strdup().
int indri::parse::Uint64Comp::u_strncmp (const UINT64 * s1, const UINT64 * s2, size_t n) [static]
Referenced by indri::parse::Arabic_Stemmer_utf8::remove_all_suffixes_unicode(), and indri::parse::Arabic_Stemmer_utf8::remove_definite_articles_unicode().
The documentation for this class was generated from the following files:
uint64comp.hpp
uint64comp.cpp