Indri: indri::infnet::TermFrequencyBeliefNode Class Reference
indri::infnet::TermFrequencyBeliefNode Class Reference
#include <TermFrequencyBeliefNode.hpp>
Public Member Functions
TermFrequencyBeliefNode (const std::string &name, class InferenceNetwork &network, int listID, indri::query::TermScoreFunction &scoreFunction)
~TermFrequencyBeliefNode ()
const
indri::utility::greedy_vector
< indri::index::DocListIterator::TopDocument > & topdocs () const
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumBackgroundScore ()
double maximumScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Attributes
class InferenceNetwork & _network
indri::query::TermScoreFunction & _function
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _extents
indri::utility::greedy_vector
< bool > _matches
indri::index::DocListIterator * _list
double _maximumBackgroundScore
double _maximumScore
std::string _name
int _listID
indri::utility::greedy_vector
< indri::index::DocListIterator::TopDocument > _emptyTopdocs
Constructor & Destructor Documentation
indri::infnet::TermFrequencyBeliefNode::TermFrequencyBeliefNode (const std::string & name, class InferenceNetwork & network, int listID, indri::query::TermScoreFunction & scoreFunction)
References _maximumBackgroundScore, _maximumScore, and INDRI_HUGE_SCORE.
indri::infnet::TermFrequencyBeliefNode::~TermFrequencyBeliefNode ()
Member Function Documentation
void indri::infnet::TermFrequencyBeliefNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
const std::string & indri::infnet::TermFrequencyBeliefNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::TermFrequencyBeliefNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _matches, indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::TermFrequencyBeliefNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _list, indri::index::DocListIterator::currentEntry(), and indri::index::DocListIterator::DocumentData::document.
void indri::infnet::TermFrequencyBeliefNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _function, _list, _listID, _maximumBackgroundScore, _maximumScore, _network, indri::utility::greedy_vector< _Type, _Count >::back(), indri::index::DocListIterator::TopDocument::count, indri::utility::greedy_vector< _Type, _Count >::front(), indri::infnet::InferenceNetwork::getDocIterator(), INDRI_HUGE_SCORE, indri::api::Parameters::instance(), indri::index::DocListIterator::TopDocument::length, indri::index::TermData::maxDocumentLength, indri::query::TermScoreFunction::scoreOccurrence(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DocListIterator::termData(), and indri::index::DocListIterator::topDocuments().
double indri::infnet::TermFrequencyBeliefNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumBackgroundScore.
Referenced by indri::infnet::WeightedAndNode::indexChanged(), and indri::infnet::ContextInclusionAndNode::indexChanged().
double indri::infnet::TermFrequencyBeliefNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _maximumScore.
Referenced by indri::infnet::WeightedAndNode::indexChanged(), and indri::infnet::ContextInclusionAndNode::indexChanged().
lemur::api::DOCID_T indri::infnet::TermFrequencyBeliefNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _list, indri::index::DocListIterator::currentEntry(), and indri::index::DocListIterator::DocumentData::document.
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::TermFrequencyBeliefNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _extents, _function, _list, _maximumBackgroundScore, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListIterator::currentEntry(), indri::api::ScoredExtentResult::document, indri::index::DocListIterator::DocumentData::document, indri::index::Extent::end, indri::index::DocListIterator::DocumentData::positions, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, indri::query::TermScoreFunction::scoreOccurrence(), and indri::utility::greedy_vector< _Type, _Count >::size().
const indri::utility::greedy_vector< indri::index::DocListIterator::TopDocument > & indri::infnet::TermFrequencyBeliefNode::topdocs () const
References _emptyTopdocs, _list, and indri::index::DocListIterator::topDocuments().
Referenced by indri::infnet::WeightedAndNode::indexChanged(), and indri::infnet::ContextInclusionAndNode::indexChanged().
Member Data Documentation
indri::utility::greedy_vector<indri::index::DocListIterator::TopDocument> indri::infnet::TermFrequencyBeliefNode::_emptyTopdocs [private]
Referenced by topdocs().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::TermFrequencyBeliefNode::_extents [private]
Referenced by score().
indri::query::TermScoreFunction& indri::infnet::TermFrequencyBeliefNode::_function [private]
Referenced by indexChanged(), and score().
indri::index::DocListIterator* indri::infnet::TermFrequencyBeliefNode::_list [private]
Referenced by hasMatch(), indexChanged(), nextCandidateDocument(), score(), and topdocs().
int indri::infnet::TermFrequencyBeliefNode::_listID [private]
Referenced by indexChanged().
indri::utility::greedy_vector<bool> indri::infnet::TermFrequencyBeliefNode::_matches [private]
Referenced by hasMatch().
double indri::infnet::TermFrequencyBeliefNode::_maximumBackgroundScore [private]
Referenced by indexChanged(), maximumBackgroundScore(), score(), and TermFrequencyBeliefNode().
double indri::infnet::TermFrequencyBeliefNode::_maximumScore [private]
Referenced by indexChanged(), maximumScore(), and TermFrequencyBeliefNode().
std::string indri::infnet::TermFrequencyBeliefNode::_name [private]
Referenced by getName().
class InferenceNetwork& indri::infnet::TermFrequencyBeliefNode::_network [private]
Referenced by indexChanged().
The documentation for this class was generated from the following files:
TermFrequencyBeliefNode.hpp
TermFrequencyBeliefNode.cpp