Indri: indri::file::SequentialWriteBuffer Class Reference
indri::file::SequentialWriteBuffer Class Reference
#include <SequentialWriteBuffer.hpp>
Public Member Functions
SequentialWriteBuffer (File &file, size_t length)
void seek (UINT64 position)
char * write (size_t length)
void write (const void *buffer, size_t length)
void unwrite (size_t length)
UINT64 tell () const
void flush ()
void flushRegion (UINT64 start, UINT64 length)
Private Attributes
File & _file
InternalFileBuffer _current
UINT64 _position
UINT64 _eof
Detailed Description
Wraps an instance of indri::file::File, and provides buffering support. This class works much like the BufferedWriter class in Java; every write is stored in a memory buffer until that buffer fills, then the data is transferred to disk en masse.
There are at least two good reasons to buffer data before writing. The first is to avoid system call overhead for little tiny writes. If this is all you care about, you can keep this write buffer fairly small; perhaps a few kilobytes.
However, a write buffer can also keep the disk from seeking unnecessarily if you're writing to a few files simultaenously. For this kind of application, consider using a megabyte or so. This also helps keep file fragmentation down.
Constructor & Destructor Documentation
indri::file::SequentialWriteBuffer::SequentialWriteBuffer (File & file, size_t length) [inline]
Constructs a new instance of the SequentialWriteBuffer class. The file pointer is set to the end of the file.
Parameters:
file The File object to wrap.
length Number of bytes to buffer.
References _eof, _file, _position, and indri::file::File::size().
Member Function Documentation
void indri::file::SequentialWriteBuffer::flush () [inline]
Flushes data in the buffer out to the file.
References _current, _eof, _file, indri::file::InternalFileBuffer::buffer, indri::utility::Buffer::clear(), indri::file::InternalFileBuffer::filePosition, indri::utility::Buffer::front(), indri::utility::Buffer::position(), and indri::file::File::write().
Referenced by indri::collection::CompressedCollection::_copyStorageData(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_writeDirectLists(), indri::index::IndexWriter::_writeFieldLists(), indri::index::IndexWriter::_writeInvertedLists(), indri::collection::CompressedCollection::append(), indri::collection::CompressedCollection::close(), indri::file::BulkTreeWriter::close(), indri::collection::CompressedCollection::compact(), compress_file(), convert_docnoscore_to_binary(), convert_intscore_to_long_binary(), indri::file::BulkTreeWriter::flush(), flushRegion(), indri::parse::PageRank::indexPageRank(), merge_sorted_runs(), indri::collection::CompressedCollection::retrieve(), and write().
void indri::file::SequentialWriteBuffer::flushRegion (UINT64 start, UINT64 length) [inline]
References _current, indri::file::InternalFileBuffer::buffer, indri::file::InternalFileBuffer::filePosition, flush(), and indri::utility::Buffer::position().
void indri::file::SequentialWriteBuffer::seek (UINT64 position) [inline]
Seek to position bytes into the file.
References _position.
Referenced by indri::index::IndexWriter::_addInvertedListData().
UINT64 indri::file::SequentialWriteBuffer::tell () const [inline]
Returns:
Current file position.
References _position.
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::collection::CompressedCollection::_copyStorageEntry(), indri::index::IndexWriter::_writeDirectLists(), indri::index::IndexWriter::_writeFieldLists(), indri::index::IndexWriter::_writeStatistics(), indri::collection::CompressedCollection::addDocument(), and indri::parse::PageRank::indexPageRank().
void indri::file::SequentialWriteBuffer::unwrite (size_t length) [inline]
Move the file pointer back by length bytes, and remove all of those bytes from the buffer. It's as if you didn't write those length bytes at all.
Parameters:
length Number of bytes to unwrite.
References _current, _position, indri::file::InternalFileBuffer::buffer, indri::utility::Buffer::position(), and indri::utility::Buffer::unwrite().
Referenced by zlib_deflate_finish().
void indri::file::SequentialWriteBuffer::write (const void * buffer, size_t length) [inline]
Writes length bytes of data from buffer into the file.
Parameters:
buffer Buffer containing data to be written to the file.
length Bytes to copy from the buffer into the file.
References write().
char* indri::file::SequentialWriteBuffer::write (size_t length) [inline]
Allocate space in the buffer for some new data. This is roughly equivalent to memory-mapping the next length bytes of the file.
This buffer space is valid until your next call to a SequentialWriteBuffer method.
Parameters:
length Number of bytes to write.
Returns:
Returns a pointer to memory where you can write your data.
References _current, _position, indri::file::InternalFileBuffer::buffer, indri::file::InternalFileBuffer::filePosition, flush(), indri::utility::Buffer::front(), indri::utility::Buffer::position(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
Referenced by indri::index::IndexWriter::_addInvertedListData(), indri::collection::CompressedCollection::_copyStorageEntry(), indri::file::BulkTreeWriter::_flush(), indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_writeBatch(), indri::index::IndexWriter::_writeDirectLists(), indri::index::IndexWriter::_writeFieldList(), indri::index::IndexWriter::_writeSkip(), indri::index::IndexWriter::_writeStatistics(), compress_file(), convert_docnoscore_to_binary(), convert_intscore_to_long_binary(), indri::parse::PageRank::indexPageRank(), merge_sorted_runs(), write(), zlib_deflate(), and zlib_deflate_finish().
Member Data Documentation
InternalFileBuffer indri::file::SequentialWriteBuffer::_current [private]
Referenced by flush(), flushRegion(), unwrite(), and write().
UINT64 indri::file::SequentialWriteBuffer::_eof [private]
Referenced by flush(), and SequentialWriteBuffer().
File& indri::file::SequentialWriteBuffer::_file [private]
Referenced by flush(), and SequentialWriteBuffer().
UINT64 indri::file::SequentialWriteBuffer::_position [private]
Referenced by seek(), SequentialWriteBuffer(), tell(), unwrite(), and write().
The documentation for this class was generated from the following file:
SequentialWriteBuffer.hpp