Indri: indri::infnet::ExtentChildNode Class Reference
indri::infnet::ExtentChildNode Class Reference
#include <ExtentChildNode.hpp>
Public Member Functions
ExtentChildNode (const std::string &name, ListIteratorNode *inner, ListIteratorNode *outer, DocumentStructureHolderNode &documentStructureHolderNode)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
const
indri::utility::greedy_vector
< indri::index::Extent > & matches (indri::index::Extent &extent)
Private Attributes
ListIteratorNode * _inner
ListIteratorNode * _outer
DocumentStructureHolderNode & _docStructHolder
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
std::set< int > _ancestors
std::set< int > _leafs
Constructor & Destructor Documentation
indri::infnet::ExtentChildNode::ExtentChildNode (const std::string & name, ListIteratorNode * inner, ListIteratorNode * outer, DocumentStructureHolderNode & documentStructureHolderNode)
Member Function Documentation
void indri::infnet::ExtentChildNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, _inner, indri::infnet::ListIteratorNode::_lastExtent, _outer, indri::infnet::Annotator::addMatches(), indri::infnet::ListIteratorNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, and indri::utility::greedy_vector< _Type, _Count >::size().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::ExtentChildNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::ExtentChildNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::ExtentChildNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, indri::index::Extent::begin, and indri::index::Extent::end.
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::ExtentChildNode::matches (indri::index::Extent & extent) [virtual]
Reimplemented from indri::infnet::ListIteratorNode.
References _ancestors, _docStructHolder, _extents, indri::infnet::ListIteratorNode::_lastpos, _leafs, indri::infnet::ListIteratorNode::_matches, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::index::DocumentStructure::findLeafs(), indri::infnet::DocumentStructureHolderNode::getDocumentStructure(), indri::index::Extent::ordinal, indri::index::DocumentStructure::parent(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::index::Extent::weight.
lemur::api::DOCID_T indri::infnet::ExtentChildNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _inner, _outer, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
void indri::infnet::ExtentChildNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _ancestors, _docStructHolder, _extents, _inner, indri::infnet::ListIteratorNode::_lastExtent, _leafs, _outer, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::infnet::ListIteratorNode::extents(), indri::index::DocumentStructure::findLeafs(), indri::infnet::DocumentStructureHolderNode::getDocumentStructure(), indri::infnet::ListIteratorNode::initpointer(), indri::index::Extent::number, indri::index::Extent::ordinal, indri::index::DocumentStructure::parent(), indri::index::Extent::parent, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::infnet::ListIteratorNode::sortparent(), and indri::index::Extent::weight.
Member Data Documentation
std::set<int> indri::infnet::ExtentChildNode::_ancestors [private]
Referenced by matches(), and prepare().
DocumentStructureHolderNode& indri::infnet::ExtentChildNode::_docStructHolder [private]
Referenced by matches(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::ExtentChildNode::_extents [private]
Referenced by annotate(), extents(), matches(), and prepare().
ListIteratorNode* indri::infnet::ExtentChildNode::_inner [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
std::set<int> indri::infnet::ExtentChildNode::_leafs [private]
Referenced by matches(), and prepare().
std::string indri::infnet::ExtentChildNode::_name [private]
Referenced by getName().
ListIteratorNode* indri::infnet::ExtentChildNode::_outer [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
The documentation for this class was generated from the following files:
ExtentChildNode.hpp
ExtentChildNode.cpp