Indri: indri::infnet::ContextInclusionAndNode Class Reference
indri::infnet::ContextInclusionAndNode Class Reference
#include <ContextInclusionAndNode.hpp>
Classes
struct child_type
Public Member Functions
ContextInclusionAndNode (const std::string &name)
void addChild (double weight, BeliefNode *node, bool preserveExtents=false)
void doneAddingChildren ()
void setThreshold (double threshold)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
Private Member Functions
void _computeQuorum ()
double _computeMaxScore (unsigned int start)
Private Attributes
std::vector< child_type > _children
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
indri::utility::greedy_vector
< lemur::api::DOCID_T > _candidates
size_t _candidatesIndex
double _threshold
double _recomputeThreshold
int _quorumIndex
BeliefNode * _preserveExtentsChild
Constructor & Destructor Documentation
indri::infnet::ContextInclusionAndNode::ContextInclusionAndNode (const std::string & name) [inline]
Member Function Documentation
double indri::infnet::ContextInclusionAndNode::_computeMaxScore (unsigned int start) [private]
References _children.
Referenced by _computeQuorum().
void indri::infnet::ContextInclusionAndNode::_computeQuorum () [private]
References _children, _computeMaxScore(), _quorumIndex, _recomputeThreshold, _threshold, and maximumScore().
Referenced by addChild(), indexChanged(), and setThreshold().
void indri::infnet::ContextInclusionAndNode::addChild (double weight, BeliefNode * node, bool preserveExtents = false)
References _children, _computeQuorum(), _preserveExtentsChild, indri::infnet::ContextInclusionAndNode::child_type::backgroundWeightedScore, indri::infnet::BeliefNode::maximumBackgroundScore(), indri::infnet::BeliefNode::maximumScore(), indri::infnet::ContextInclusionAndNode::child_type::maximumWeightedScore, indri::infnet::ContextInclusionAndNode::child_type::node, and indri::infnet::ContextInclusionAndNode::child_type::weight.
void indri::infnet::ContextInclusionAndNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _children, and indri::infnet::Annotator::add().
void indri::infnet::ContextInclusionAndNode::doneAddingChildren ()
const std::string & indri::infnet::ContextInclusionAndNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::ContextInclusionAndNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _candidates, _candidatesIndex, _matches, _preserveExtentsChild, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::infnet::BeliefNode::hasMatch(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::ContextInclusionAndNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _candidates, _candidatesIndex, _preserveExtentsChild, indri::infnet::BeliefNode::hasMatch(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::ContextInclusionAndNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _candidates, _candidatesIndex, _children, _computeQuorum(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::Parameters::instance(), indri::infnet::TermFrequencyBeliefNode::maximumBackgroundScore(), indri::infnet::TermFrequencyBeliefNode::maximumScore(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::infnet::TermFrequencyBeliefNode::topdocs().
double indri::infnet::ContextInclusionAndNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
double indri::infnet::ContextInclusionAndNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children.
Referenced by _computeQuorum().
lemur::api::DOCID_T indri::infnet::ContextInclusionAndNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _candidates, _candidatesIndex, _children, _quorumIndex, and indri::utility::greedy_vector< _Type, _Count >::size().
indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::ContextInclusionAndNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _candidates, _candidatesIndex, _children, _preserveExtentsChild, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::ContextInclusionAndNode::setThreshold (double threshold) [virtual]
Implements indri::infnet::SkippingCapableNode.
References _computeQuorum(), _recomputeThreshold, and _threshold.
Member Data Documentation
indri::utility::greedy_vector<lemur::api::DOCID_T> indri::infnet::ContextInclusionAndNode::_candidates [private]
Referenced by hasMatch(), indexChanged(), nextCandidateDocument(), and score().
size_t indri::infnet::ContextInclusionAndNode::_candidatesIndex [private]
Referenced by hasMatch(), indexChanged(), nextCandidateDocument(), and score().
std::vector<child_type> indri::infnet::ContextInclusionAndNode::_children [private]
Referenced by _computeMaxScore(), _computeQuorum(), addChild(), annotate(), indexChanged(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<bool> indri::infnet::ContextInclusionAndNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::ContextInclusionAndNode::_name [private]
Referenced by getName().
BeliefNode* indri::infnet::ContextInclusionAndNode::_preserveExtentsChild [private]
Referenced by addChild(), hasMatch(), and score().
int indri::infnet::ContextInclusionAndNode::_quorumIndex [private]
Referenced by _computeQuorum(), and nextCandidateDocument().
double indri::infnet::ContextInclusionAndNode::_recomputeThreshold [private]
Referenced by _computeQuorum(), and setThreshold().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::ContextInclusionAndNode::_scores [private]
Referenced by score().
double indri::infnet::ContextInclusionAndNode::_threshold [private]
Referenced by _computeQuorum(), and setThreshold().
The documentation for this class was generated from the following files:
ContextInclusionAndNode.hpp
ContextInclusionAndNode.cpp