Indri: indri::server::NetworkServerProxyVectorsResponse Class Reference
indri::server::NetworkServerProxyVectorsResponse Class Reference
Public Member Functions
NetworkServerProxyVectorsResponse (indri::net::NetworkMessageStream *stream)
~NetworkServerProxyVectorsResponse ()
std::vector
< indri::api::DocumentVector * > & getResults ()
Public Attributes
std::vector
< indri::api::DocumentVector * > _vectors
indri::net::NetworkMessageStream * _stream
bool _readResponse
Constructor & Destructor Documentation
indri::server::NetworkServerProxyVectorsResponse::NetworkServerProxyVectorsResponse (indri::net::NetworkMessageStream * stream) [inline]
indri::server::NetworkServerProxyVectorsResponse::~NetworkServerProxyVectorsResponse () [inline]
References _stream, indri::net::NetworkMessageStream::mutex(), and indri::thread::Lockable::unlock().
Member Function Documentation
std::vector<indri::api::DocumentVector*>& indri::server::NetworkServerProxyVectorsResponse::getResults () [inline, virtual]
Implements indri::server::QueryServerVectorsResponse.
References _readResponse, _stream, _vectors, base64_decode_string(), indri::api::DocumentVector::Field::begin, indri::api::DocumentVector::Field::end, indri::api::DocumentVector::fields(), indri::xml::XMLNode::getChild(), indri::xml::XMLNode::getChildren(), indri::net::XMLReplyReceiver::getReply(), indri::xml::XMLNode::getValue(), indri::api::DocumentVector::Field::name, indri::api::DocumentVector::Field::number, indri::api::DocumentVector::Field::ordinal, indri::api::DocumentVector::Field::parentOrdinal, indri::api::DocumentVector::positions(), indri::api::DocumentVector::stems(), string_to_i64(), and indri::net::XMLReplyReceiver::wait().
Member Data Documentation
bool indri::server::NetworkServerProxyVectorsResponse::_readResponse
Referenced by getResults().
indri::net::NetworkMessageStream* indri::server::NetworkServerProxyVectorsResponse::_stream
Referenced by getResults(), and ~NetworkServerProxyVectorsResponse().
std::vector<indri::api::DocumentVector*> indri::server::NetworkServerProxyVectorsResponse::_vectors
Referenced by getResults().
The documentation for this class was generated from the following file:
NetworkServerProxy.cpp