Indri: indri::parse::WARCDocumentIterator Class Reference
indri::parse::WARCDocumentIterator Class Reference
#include <WARCDocumentIterator.hpp>
Public Member Functions
WARCDocumentIterator ()
~WARCDocumentIterator ()
void open (const std::string &filename)
void close ()
UnparsedDocument * nextDocument ()
Private Attributes
WARCRecord * _record
UnparsedDocument _document
gzFile _gzin
indri::utility::Buffer _buffer
indri::utility::Buffer _metaBuffer
std::string _warcUUID
const char * _warcMeta
const char * _dochdr
const char * _docnoString
char _docno [512]
Constructor & Destructor Documentation
indri::parse::WARCDocumentIterator::WARCDocumentIterator ()
References _dochdr, _docnoString, _gzin, _metaBuffer, _record, _warcMeta, and indri::utility::Buffer::grow().
indri::parse::WARCDocumentIterator::~WARCDocumentIterator ()
References close().
Member Function Documentation
void indri::parse::WARCDocumentIterator::close () [virtual]
Implements indri::parse::DocumentIterator.
References _gzin, and _record.
Referenced by ~WARCDocumentIterator().
indri::parse::UnparsedDocument * indri::parse::WARCDocumentIterator::nextDocument () [virtual]
Implements indri::parse::DocumentIterator.
References _dochdr, _docno, _docnoString, _document, _metaBuffer, _record, _warcMeta, _warcUUID, indri::utility::Buffer::clear(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::parse::UnparsedDocument::content, indri::parse::UnparsedDocument::contentLength, indri::utility::Buffer::front(), indri::parse::WARCRecord::getContent(), indri::parse::WARCRecord::getHeader(), indri::parse::WARCRecord::getTargetURI(), indri::parse::WARCRecord::getTrecID(), indri::parse::WARCRecord::getUUID(), indri::parse::WARCRecord::getWarcType(), indri::parse::MetadataPair::key, indri::parse::UnparsedDocument::metadata, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::parse::WARCRecord::readRecord(), indri::parse::UnparsedDocument::text, indri::parse::UnparsedDocument::textLength, indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
void indri::parse::WARCDocumentIterator::open (const std::string & filename) [virtual]
Implements indri::parse::DocumentIterator.
References _buffer, _gzin, _record, _warcUUID, indri::parse::WARCRecord::getUUID(), indri::parse::WARCRecord::getWarcType(), and indri::parse::WARCRecord::readRecord().
Member Data Documentation
indri::utility::Buffer indri::parse::WARCDocumentIterator::_buffer [private]
Referenced by open().
const char* indri::parse::WARCDocumentIterator::_dochdr [private]
Referenced by nextDocument(), and WARCDocumentIterator().
char indri::parse::WARCDocumentIterator::_docno[512] [private]
Referenced by nextDocument().
const char* indri::parse::WARCDocumentIterator::_docnoString [private]
Referenced by nextDocument(), and WARCDocumentIterator().
UnparsedDocument indri::parse::WARCDocumentIterator::_document [private]
Referenced by nextDocument().
gzFile indri::parse::WARCDocumentIterator::_gzin [private]
Referenced by close(), open(), and WARCDocumentIterator().
indri::utility::Buffer indri::parse::WARCDocumentIterator::_metaBuffer [private]
Referenced by nextDocument(), and WARCDocumentIterator().
WARCRecord* indri::parse::WARCDocumentIterator::_record [private]
Referenced by close(), nextDocument(), open(), and WARCDocumentIterator().
const char* indri::parse::WARCDocumentIterator::_warcMeta [private]
Referenced by nextDocument(), and WARCDocumentIterator().
std::string indri::parse::WARCDocumentIterator::_warcUUID [private]
Referenced by nextDocument(), and open().
The documentation for this class was generated from the following files:
WARCDocumentIterator.hpp
WARCDocumentIterator.cpp