Indri: indri::index::IndexWriter Class Reference
indri::index::IndexWriter Class Reference
#include <IndexWriter.hpp>
Classes
struct disktermdata_alpha_less
struct disktermdata_count_greater
struct keyfile_pair
Public Member Functions
IndexWriter ()
void write (indri::index::Index &index, std::vector< indri::index::Index::FieldDescription > &fields, indri::index::DeletedDocumentList &deletedList, const std::string &fileName)
void write (std::vector< indri::index::Index * > &indexes, std::vector< indri::index::Index::FieldDescription > &fields, indri::index::DeletedDocumentList &deletedList, const std::string &fileName)
void write (std::vector< indri::index::Index * > &indexes, std::vector< indri::index::Index::FieldDescription > &fields, std::vector< indri::index::DeletedDocumentList * > &deletedLists, const std::vector< lemur::api::DOCID_T > &documentMaximums, const std::string &path)
Private Types
enum { TOPDOCS_DOCUMENT_COUNT = 1000, FREQUENT_TERM_COUNT = 1000 }
Private Member Functions
void _writeManifest (const std::string &path)
void _writeSkip (indri::file::SequentialWriteBuffer *buffer, lemur::api::DOCID_T document, int length)
void _writeBatch (indri::file::SequentialWriteBuffer *buffer, lemur::api::DOCID_T document, int length, indri::utility::Buffer &data)
void _writeFieldLists (std::vector< WriterIndexContext * > &contexts, const std::string &path)
void _writeFieldList (indri::file::SequentialWriteBuffer &output, int fieldIndex, std::vector< indri::index::DocExtentListIterator * > &iterators, std::vector< WriterIndexContext * > &contexts)
void _pushInvertedLists (indri::utility::greedy_vector< WriterIndexContext * > &lists, invertedlist_pqueue &queue)
void _fetchMatchingInvertedLists (indri::utility::greedy_vector< WriterIndexContext * > &lists, invertedlist_pqueue &queue)
void _writeStatistics (indri::utility::greedy_vector< WriterIndexContext * > &lists, indri::index::TermData *termData, UINT64 &startOffset)
void _writeInvertedLists (std::vector< WriterIndexContext * > &contexts)
void _storeIdEntry (IndexWriter::keyfile_pair &pair, indri::index::DiskTermData *diskTermData)
void _storeStringEntry (IndexWriter::keyfile_pair &pair, indri::index::DiskTermData *diskTermData)
void _storeTermEntry (IndexWriter::keyfile_pair &pair, indri::index::DiskTermData *diskTermData)
void _storeFrequentTerms ()
void _addInvertedListData (indri::utility::greedy_vector< WriterIndexContext * > &lists, indri::index::TermData *termData, indri::utility::Buffer &listBuffer, UINT64 &endOffset)
void _storeMatchInformation (indri::utility::greedy_vector< WriterIndexContext * > &lists, int sequence, indri::index::TermData *termData, UINT64 startOffset, UINT64 endOffset)
lemur::api::TERMID_T _lookupTermID (indri::file::BulkTreeReader &keyfile, const char *term)
void _buildIndexContexts (std::vector< WriterIndexContext * > &contexts, std::vector< indri::index::Index * > &indexes, indri::index::DeletedDocumentList &deletedList)
void _buildIndexContexts (std::vector< WriterIndexContext * > &contexts, std::vector< indri::index::Index * > &indexes, std::vector< indri::index::DeletedDocumentList * > &deletedLists, const std::vector< lemur::api::DOCID_T > &documentOffsets)
void _writeDirectLists (std::vector< WriterIndexContext * > &contexts)
void _writeDirectLists (WriterIndexContext *context, indri::file::SequentialWriteBuffer *directOutput, indri::file::SequentialWriteBuffer *lengthsOutput, indri::file::SequentialWriteBuffer *dataOutput)
void _constructFiles (const std::string &path)
void _closeFiles (const std::string &path)
void _openTermsReaders (const std::string &path)
indri::index::TermTranslator * _buildTermTranslator (indri::file::BulkTreeReader &newInfrequentTerms, indri::file::BulkTreeReader &newFrequentTerms, indri::index::TermRecorder &oldFrequentTermsRecorder, indri::utility::HashTable< lemur::api::TERMID_T, lemur::api::TERMID_T > *oldInfrequent, indri::index::TermRecorder &newFrequentTermsRecorder, indri::index::Index *index, indri::index::TermBitmap *bitmap)
Private Attributes
keyfile_pair _infrequentTerms
keyfile_pair _frequentTerms
indri::file::File _frequentTermsData
indri::file::BulkTreeReader _infrequentTermsReader
indri::file::BulkTreeReader _frequentTermsReader
indri::file::File _documentStatistics
indri::file::File _documentLengths
indri::file::File _invertedFile
indri::file::File _directFile
indri::file::File _fieldsFile
indri::file::SequentialWriteBuffer * _invertedOutput
indri::utility::greedy_vector
< indri::index::DiskTermData * > _topTerms
int _topTermsCount
indri::utility::Buffer _termDataBuffer
int _isFrequentCount
lemur::api::DOCID_T _documentBase
indri::index::CorpusStatistics _corpus
std::vector
< indri::index::Index::FieldDescription > _fields
std::vector
< indri::index::FieldStatistics > _fieldData
char * _compressedData
char * _uncompressedData
int _dataSize
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
TOPDOCS_DOCUMENT_COUNT
FREQUENT_TERM_COUNT
Constructor & Destructor Documentation
IndexWriter::IndexWriter ()
Member Function Documentation
void IndexWriter::_addInvertedListData (indri::utility::greedy_vector< WriterIndexContext * > & lists, indri::index::TermData * termData, indri::utility::Buffer & listBuffer, UINT64 & endOffset) [private]
References _invertedOutput, _writeBatch(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::CharClass::control, indri::index::TermData::corpus, indri::index::DocListIterator::TopDocument::count, indri::index::DocListIterator::currentEntry(), indri::index::DocListIterator::TopDocument::document, indri::index::DocListIterator::DocumentData::document, indri::index::TermFieldStatistics::documentCount, indri::index::Index::documentLength(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::DocListIterator::finished(), FREQUENT_TERM_COUNT, indri::index::DocListFileIterator::DocListData::iterator, indri::index::DocListIterator::TopDocument::length, indri::index::DocListIterator::nextEntry(), indri::utility::Buffer::position(), indri::index::DocListIterator::DocumentData::positions, indri::file::SequentialWriteBuffer::seek(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::file::SequentialWriteBuffer::tell(), TOPDOCS_DOCUMENT_COUNT, indri::index::TermFieldStatistics::totalCount, and indri::file::SequentialWriteBuffer::write().
Referenced by _writeInvertedLists().
void IndexWriter::_buildIndexContexts (std::vector< WriterIndexContext * > & contexts, std::vector< indri::index::Index * > & indexes, std::vector< indri::index::DeletedDocumentList * > & deletedLists, const std::vector< lemur::api::DOCID_T > & documentOffsets) [private]
void IndexWriter::_buildIndexContexts (std::vector< WriterIndexContext * > & contexts, std::vector< indri::index::Index * > & indexes, indri::index::DeletedDocumentList & deletedList) [private]
Referenced by write().
indri::index::TermTranslator * IndexWriter::_buildTermTranslator (indri::file::BulkTreeReader & newInfrequentTerms, indri::file::BulkTreeReader & newFrequentTerms, indri::index::TermRecorder & oldFrequentTermsRecorder, indri::utility::HashTable< lemur::api::TERMID_T, lemur::api::TERMID_T > * oldInfrequent, indri::index::TermRecorder & newFrequentTermsRecorder, indri::index::Index * index, indri::index::TermBitmap * bitmap) [private]
References _corpus, _isFrequentCount, _lookupTermID(), indri::index::TermRecorder::buffer(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::Buffer::front(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::index::TermRecorder::pairs(), indri::index::TermRecorder::sort(), indri::index::Index::uniqueTermCount(), and indri::index::CorpusStatistics::uniqueTerms.
Referenced by _writeDirectLists().
void IndexWriter::_closeFiles (const std::string & path) [private]
References _directFile, _documentLengths, _documentStatistics, _fieldsFile, _frequentTerms, _frequentTermsData, _frequentTermsReader, _infrequentTerms, _infrequentTermsReader, _invertedFile, _writeManifest(), indri::file::File::close(), indri::file::BulkTreeReader::close(), indri::file::Path::combine(), indri::index::IndexWriter::keyfile_pair::idMap, and indri::index::IndexWriter::keyfile_pair::stringMap.
Referenced by write().
void IndexWriter::_constructFiles (const std::string & path) [private]
References _directFile, _documentLengths, _documentStatistics, _fieldsFile, _frequentTerms, _frequentTermsData, _infrequentTerms, _invertedFile, _invertedOutput, indri::file::Path::combine(), indri::file::File::create(), indri::file::BulkTreeWriter::create(), indri::file::Path::create(), indri::index::IndexWriter::keyfile_pair::idMap, OUTPUT_BUFFER_SIZE, and indri::index::IndexWriter::keyfile_pair::stringMap.
Referenced by write().
void IndexWriter::_fetchMatchingInvertedLists (indri::utility::greedy_vector< WriterIndexContext * > & lists, invertedlist_pqueue & queue) [private]
References indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::DocListFileIterator::currentEntry(), indri::index::WriterIndexContext::iterator, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by _writeInvertedLists().
lemur::api::TERMID_T IndexWriter::_lookupTermID (indri::file::BulkTreeReader & keyfile, const char * term) [private]
References _compressedData, _dataSize, _fields, _uncompressedData, disktermdata_decompress(), indri::file::BulkTreeReader::get(), indri::index::DiskTermData::termID, and indri::index::DiskTermData::WithTermID.
Referenced by _buildTermTranslator().
void IndexWriter::_openTermsReaders (const std::string & path) [private]
References _frequentTermsReader, _infrequentTermsReader, indri::file::Path::combine(), and indri::file::BulkTreeReader::openRead().
Referenced by write().
void IndexWriter::_pushInvertedLists (indri::utility::greedy_vector< WriterIndexContext * > & lists, invertedlist_pqueue & queue) [private]
References indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by _writeInvertedLists().
void IndexWriter::_storeFrequentTerms () [private]
References _fields, _frequentTerms, _frequentTermsData, _storeIdEntry(), _storeStringEntry(), _topTerms, _topTermsCount, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::Buffer::clear(), disktermdata_compress(), disktermdata_delete(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::file::SequentialWriteBuffer::flush(), indri::utility::Buffer::front(), indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DiskTermData::WithOffsets, indri::index::DiskTermData::WithString, indri::index::DiskTermData::WithTermID, and indri::file::SequentialWriteBuffer::write().
Referenced by _writeInvertedLists().
void IndexWriter::_storeIdEntry (IndexWriter::keyfile_pair & pair, indri::index::DiskTermData * diskTermData) [private]
References _fields, _termDataBuffer, indri::utility::Buffer::clear(), indri::utility::RVLCompressStream::data(), indri::utility::RVLCompressStream::dataSize(), disktermdata_compress(), indri::index::IndexWriter::keyfile_pair::idMap, indri::file::BulkTreeWriter::put(), indri::index::DiskTermData::termID, indri::index::DiskTermData::WithOffsets, and indri::index::DiskTermData::WithString.
Referenced by _storeFrequentTerms(), and _storeTermEntry().
void IndexWriter::_storeMatchInformation (indri::utility::greedy_vector< WriterIndexContext * > & lists, int sequence, indri::index::TermData * termData, UINT64 startOffset, UINT64 endOffset) [private]
References _corpus, _fields, _infrequentTerms, _isFrequentCount, _storeTermEntry(), _topTerms, indri::index::TermRecorder::add(), indri::index::TermBitmap::add(), indri::index::WriterIndexContext::bitmap, indri::index::TermData::corpus, disktermdata_create(), FREQUENT_TERM_COUNT, indri::index::DiskDocListIterator::isFrequent(), indri::index::WriterIndexContext::iterator, indri::index::DiskTermData::length, indri::index::WriterIndexContext::newlyFrequent, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::index::WriterIndexContext::sequenceCount, indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DiskTermData::startOffset, indri::index::TermData::term, indri::index::DiskTermData::termData, termdata_merge(), indri::index::DiskTermData::termID, indri::index::TermFieldStatistics::totalCount, indri::index::CorpusStatistics::uniqueTerms, indri::index::WriterIndexContext::wasFrequentCount, and indri::index::WriterIndexContext::wasInfrequentCount.
Referenced by _writeInvertedLists().
void IndexWriter::_storeStringEntry (IndexWriter::keyfile_pair & pair, indri::index::DiskTermData * diskTermData) [private]
References _fields, _termDataBuffer, indri::utility::Buffer::clear(), indri::utility::RVLCompressStream::data(), indri::utility::RVLCompressStream::dataSize(), disktermdata_compress(), indri::file::BulkTreeWriter::put(), indri::index::IndexWriter::keyfile_pair::stringMap, indri::index::TermData::term, indri::index::DiskTermData::termData, indri::index::DiskTermData::WithOffsets, and indri::index::DiskTermData::WithTermID.
Referenced by _storeFrequentTerms(), and _storeTermEntry().
void IndexWriter::_storeTermEntry (IndexWriter::keyfile_pair & pair, indri::index::DiskTermData * diskTermData) [private]
References _storeIdEntry(), and _storeStringEntry().
Referenced by _storeMatchInformation().
void IndexWriter::_writeBatch (indri::file::SequentialWriteBuffer * buffer, lemur::api::DOCID_T document, int length, indri::utility::Buffer & data) [private]
References _writeSkip(), indri::utility::Buffer::clear(), indri::utility::Buffer::front(), indri::utility::Buffer::position(), and indri::file::SequentialWriteBuffer::write().
Referenced by _addInvertedListData(), and _writeFieldList().
void IndexWriter::_writeDirectLists (WriterIndexContext * context, indri::file::SequentialWriteBuffer * directOutput, indri::file::SequentialWriteBuffer * lengthsOutput, indri::file::SequentialWriteBuffer * dataOutput) [private]
References _buildTermTranslator(), _frequentTermsReader, _infrequentTermsReader, indri::index::TermRecorder::add(), indri::index::TermList::addField(), indri::index::TermList::addTerm(), indri::index::WriterIndexContext::bitmap, indri::index::DocumentData::byteLength, indri::utility::Buffer::clear(), indri::index::TermList::clear(), indri::index::DocumentDataIterator::currentEntry(), indri::index::TermListFileIterator::currentEntry(), indri::index::VocabularyIterator::currentEntry(), indri::index::WriterIndexContext::deletedList, indri::index::Index::documentBase(), indri::index::Index::documentDataIterator(), indri::index::TermList::fields(), indri::index::DocumentDataIterator::finished(), indri::index::TermListFileIterator::finished(), indri::index::VocabularyIterator::finished(), indri::file::SequentialWriteBuffer::flush(), indri::index::Index::frequentVocabularyIterator(), indri::utility::Buffer::front(), indri::index::WriterIndexContext::index, indri::index::DeletedDocumentList::isDeleted(), indri::index::WriterIndexContext::newlyFrequent, indri::index::DocumentDataIterator::nextEntry(), indri::index::TermListFileIterator::nextEntry(), indri::index::VocabularyIterator::nextEntry(), indri::index::WriterIndexContext::oldFrequent, indri::index::WriterIndexContext::oldInfrequent, OUTPUT_BUFFER_SIZE, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DocumentDataIterator::startIteration(), indri::index::TermListFileIterator::startIteration(), indri::index::VocabularyIterator::startIteration(), indri::file::SequentialWriteBuffer::tell(), indri::index::TermData::term, indri::index::DiskTermData::termData, indri::index::DiskTermData::termID, indri::index::Index::termListFileIterator(), indri::index::TermList::terms(), indri::file::SequentialWriteBuffer::write(), indri::index::TermList::write(), and indri::utility::Buffer::write().
void IndexWriter::_writeDirectLists (std::vector< WriterIndexContext * > & contexts) [private]
References _directFile, _documentLengths, _documentStatistics, and indri::file::SequentialWriteBuffer::flush().
Referenced by write().
void IndexWriter::_writeFieldList (indri::file::SequentialWriteBuffer & output, int fieldIndex, std::vector< indri::index::DocExtentListIterator * > & iterators, std::vector< WriterIndexContext * > & contexts) [private]
References _fieldData, _fields, _writeBatch(), indri::index::Extent::begin, indri::parse::CharClass::control, indri::index::DocExtentListIterator::currentEntry(), indri::index::WriterIndexContext::deletedList, indri::index::DocExtentListIterator::DocumentExtentData::document, indri::index::WriterIndexContext::documentOffset, indri::index::Extent::end, indri::index::DocExtentListIterator::DocumentExtentData::extents, indri::index::DocExtentListIterator::finished(), indri::index::DeletedDocumentList::isDeleted(), indri::index::DocExtentListIterator::nextEntry(), indri::index::DocExtentListIterator::DocumentExtentData::numbers, indri::index::Extent::ordinal, indri::index::Extent::parent, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DocExtentListIterator::startIteration(), and indri::file::SequentialWriteBuffer::write().
Referenced by _writeFieldLists().
void IndexWriter::_writeFieldLists (std::vector< WriterIndexContext * > & contexts, const std::string & path) [private]
References _fieldData, _fields, _fieldsFile, _writeFieldList(), indri::file::SequentialWriteBuffer::flush(), OUTPUT_BUFFER_SIZE, and indri::file::SequentialWriteBuffer::tell().
Referenced by write().
void IndexWriter::_writeInvertedLists (std::vector< WriterIndexContext * > & contexts) [private]
References _addInvertedListData(), _corpus, _documentBase, _fetchMatchingInvertedLists(), _fields, _frequentTerms, _infrequentTerms, _invertedFile, _invertedOutput, _isFrequentCount, _pushInvertedLists(), _storeFrequentTerms(), _storeMatchInformation(), _writeStatistics(), indri::file::File::close(), indri::file::BulkTreeWriter::close(), indri::file::SequentialWriteBuffer::flush(), indri::index::IndexWriter::keyfile_pair::idMap, indri::index::CorpusStatistics::maximumDocument, indri::index::IndexWriter::keyfile_pair::stringMap, indri::index::TermData::term, termdata_create(), termdata_delete(), indri::index::CorpusStatistics::totalDocuments, indri::index::CorpusStatistics::totalTerms, and indri::index::CorpusStatistics::uniqueTerms.
Referenced by write().
void IndexWriter::_writeManifest (const std::string & path) [private]
References _corpus, _documentBase, _fieldData, _fields, _topTermsCount, indri::api::Parameters::append(), INDRI_DISTRIBUTION, indri::index::CorpusStatistics::maximumDocument, indri::api::Parameters::set(), indri::index::CorpusStatistics::totalDocuments, indri::index::CorpusStatistics::totalTerms, indri::index::CorpusStatistics::uniqueTerms, and indri::api::Parameters::writeFile().
Referenced by _closeFiles().
void IndexWriter::_writeSkip (indri::file::SequentialWriteBuffer * buffer, lemur::api::DOCID_T document, int length) [private]
References indri::file::SequentialWriteBuffer::write().
Referenced by _writeBatch().
void IndexWriter::_writeStatistics (indri::utility::greedy_vector< WriterIndexContext * > & lists, indri::index::TermData * termData, UINT64 & startOffset) [private]
References _fields, _invertedOutput, _termDataBuffer, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::Buffer::clear(), indri::utility::RVLCompressStream::data(), indri::utility::RVLCompressStream::dataSize(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::file::SequentialWriteBuffer::tell(), indri::index::TermData::term, indri::index::DocListFileIterator::DocListData::termData, termdata_clear(), termdata_compress(), termdata_merge(), and indri::file::SequentialWriteBuffer::write().
Referenced by _writeInvertedLists().
void IndexWriter::write (std::vector< indri::index::Index * > & indexes, std::vector< indri::index::Index::FieldDescription > & fields, std::vector< indri::index::DeletedDocumentList * > & deletedLists, const std::vector< lemur::api::DOCID_T > & documentMaximums, const std::string & path)
References _buildIndexContexts(), _closeFiles(), _compressedData, _constructFiles(), _dataSize, _fields, _openTermsReaders(), _uncompressedData, _writeDirectLists(), _writeFieldLists(), _writeInvertedLists(), indri::utility::delete_vector_contents(), disktermdata_size(), LOGMESSAGE, and LOGSTART.
void indri::index::IndexWriter::write (std::vector< indri::index::Index * > & indexes, std::vector< indri::index::Index::FieldDescription > & fields, indri::index::DeletedDocumentList & deletedList, const std::string & fileName)
void IndexWriter::write (indri::index::Index & index, std::vector< indri::index::Index::FieldDescription > & fields, indri::index::DeletedDocumentList & deletedList, const std::string & fileName)
Referenced by indri::collection::Repository::_mergeClosedIndexes().
Member Data Documentation
char* indri::index::IndexWriter::_compressedData [private]
Referenced by _lookupTermID(), and write().
indri::index::CorpusStatistics indri::index::IndexWriter::_corpus [private]
Referenced by _buildTermTranslator(), _storeMatchInformation(), _writeInvertedLists(), and _writeManifest().
int indri::index::IndexWriter::_dataSize [private]
Referenced by _lookupTermID(), and write().
indri::file::File indri::index::IndexWriter::_directFile [private]
Referenced by _closeFiles(), _constructFiles(), and _writeDirectLists().
lemur::api::DOCID_T indri::index::IndexWriter::_documentBase [private]
Referenced by _writeInvertedLists(), and _writeManifest().
indri::file::File indri::index::IndexWriter::_documentLengths [private]
Referenced by _closeFiles(), _constructFiles(), and _writeDirectLists().
indri::file::File indri::index::IndexWriter::_documentStatistics [private]
Referenced by _closeFiles(), _constructFiles(), and _writeDirectLists().
std::vector<indri::index::FieldStatistics> indri::index::IndexWriter::_fieldData [private]
Referenced by _writeFieldList(), _writeFieldLists(), and _writeManifest().
std::vector<indri::index::Index::FieldDescription> indri::index::IndexWriter::_fields [private]
Referenced by _lookupTermID(), _storeFrequentTerms(), _storeIdEntry(), _storeMatchInformation(), _storeStringEntry(), _writeFieldList(), _writeFieldLists(), _writeInvertedLists(), _writeManifest(), _writeStatistics(), and write().
indri::file::File indri::index::IndexWriter::_fieldsFile [private]
Referenced by _closeFiles(), _constructFiles(), and _writeFieldLists().
keyfile_pair indri::index::IndexWriter::_frequentTerms [private]
Referenced by _closeFiles(), _constructFiles(), _storeFrequentTerms(), and _writeInvertedLists().
indri::file::File indri::index::IndexWriter::_frequentTermsData [private]
Referenced by _closeFiles(), _constructFiles(), and _storeFrequentTerms().
indri::file::BulkTreeReader indri::index::IndexWriter::_frequentTermsReader [private]
Referenced by _closeFiles(), _openTermsReaders(), and _writeDirectLists().
keyfile_pair indri::index::IndexWriter::_infrequentTerms [private]
Referenced by _closeFiles(), _constructFiles(), _storeMatchInformation(), and _writeInvertedLists().
indri::file::BulkTreeReader indri::index::IndexWriter::_infrequentTermsReader [private]
Referenced by _closeFiles(), _openTermsReaders(), and _writeDirectLists().
indri::file::File indri::index::IndexWriter::_invertedFile [private]
Referenced by _closeFiles(), _constructFiles(), and _writeInvertedLists().
indri::file::SequentialWriteBuffer* indri::index::IndexWriter::_invertedOutput [private]
Referenced by _addInvertedListData(), _constructFiles(), _writeInvertedLists(), and _writeStatistics().
int indri::index::IndexWriter::_isFrequentCount [private]
Referenced by _buildTermTranslator(), _storeMatchInformation(), and _writeInvertedLists().
indri::utility::Buffer indri::index::IndexWriter::_termDataBuffer [private]
Referenced by _storeIdEntry(), _storeStringEntry(), and _writeStatistics().
indri::utility::greedy_vector<indri::index::DiskTermData*> indri::index::IndexWriter::_topTerms [private]
Referenced by _storeFrequentTerms(), and _storeMatchInformation().
int indri::index::IndexWriter::_topTermsCount [private]
Referenced by _storeFrequentTerms(), and _writeManifest().
char* indri::index::IndexWriter::_uncompressedData [private]
Referenced by _lookupTermID(), and write().
The documentation for this class was generated from the following files:
IndexWriter.hpp
IndexWriter.cpp