Indri: indri::infnet::FilterRejectNode Class Reference
indri::infnet::FilterRejectNode Class Reference
#include <FilterRejectNode.hpp>
Public Member Functions
FilterRejectNode (const std::string &name, ListIteratorNode *filter, BeliefNode *disallowed)
double maximumBackgroundScore ()
double maximumScore ()
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
Private Attributes
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _extents
indri::utility::greedy_vector
< bool > _matches
ListIteratorNode * _filter
BeliefNode * _disallowed
std::string _name
Constructor & Destructor Documentation
indri::infnet::FilterRejectNode::FilterRejectNode (const std::string & name, ListIteratorNode * filter, BeliefNode * disallowed)
References _disallowed, _filter, and _name.
Member Function Documentation
void indri::infnet::FilterRejectNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _disallowed, _filter, indri::infnet::BeliefNode::annotate(), indri::infnet::ListIteratorNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::FilterRejectNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::FilterRejectNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _filter, _matches, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::FilterRejectNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _disallowed, and indri::infnet::BeliefNode::hasMatch().
void indri::infnet::FilterRejectNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::FilterRejectNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _disallowed, and indri::infnet::BeliefNode::maximumBackgroundScore().
double indri::infnet::FilterRejectNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _disallowed, and indri::infnet::BeliefNode::maximumScore().
lemur::api::DOCID_T indri::infnet::FilterRejectNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _disallowed, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::FilterRejectNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _disallowed, _extents, _filter, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::ListIteratorNode::extents(), indri::infnet::BeliefNode::score(), and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
BeliefNode* indri::infnet::FilterRejectNode::_disallowed [private]
Referenced by annotate(), FilterRejectNode(), hasMatch(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::FilterRejectNode::_extents [private]
Referenced by score().
ListIteratorNode* indri::infnet::FilterRejectNode::_filter [private]
Referenced by annotate(), FilterRejectNode(), hasMatch(), and score().
indri::utility::greedy_vector<bool> indri::infnet::FilterRejectNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::FilterRejectNode::_name [private]
Referenced by FilterRejectNode(), and getName().
The documentation for this class was generated from the following files:
FilterRejectNode.hpp
FilterRejectNode.cpp