Indri: indri::lang::CombineNode Class Reference
indri::lang::CombineNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
CombineNode ()
CombineNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::CombineNode::CombineNode () [inline]
indri::lang::CombineNode::CombineNode (Unpacker & unpacker) [inline]
References indri::lang::UnweightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::CombineNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_copy().
UINT64 indri::lang::CombineNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_hashCode().
std::string indri::lang::CombineNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_childText().
std::string indri::lang::CombineNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::CombineNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp