Indri: indri::parse::WARCRecord Class Reference
indri::parse::WARCRecord Class Reference
#include <WARCDocumentIterator.hpp>
Public Member Functions
WARCRecord (gzFile &in, indri::utility::Buffer &buf)
~WARCRecord ()
std::string getWarcType ()
std::string getUUID ()
std::string getTrecID ()
std::string getTargetURI ()
const char * getHeader ()
const char * getContent ()
std::string getMetadata (const char *key)
bool readRecord ()
Static Public Attributes
static const char * WARCTYPE = "WARC-Type"
static const char * WARCRECORDID = "WARC-Record-ID"
static const char * CONTENTLENGTH = "Content-Length"
static const char * WARCTARGETURI = "WARC-Target-URI"
static const char * WARCTRECID = "WARC-TREC-ID"
Private Member Functions
bool _readLine (char *&beginLine, size_t &lineLength)
bool readHeader ()
bool readContent ()
Private Attributes
std::string warcType
std::string uuid
std::string trecID
std::string targetURI
int contentLength
indri::utility::HashTable
< std::string, std::string > metadata
std::string header
const char * content
gzFile & _gzin
indri::utility::Buffer & _buffer
Constructor & Destructor Documentation
indri::parse::WARCRecord::WARCRecord (gzFile & in, indri::utility::Buffer & buf) [inline]
indri::parse::WARCRecord::~WARCRecord ()
Member Function Documentation
bool indri::parse::WARCRecord::_readLine (char *& beginLine, size_t & lineLength) [private]
References _buffer, _gzin, indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::utility::Buffer::position(), indri::utility::Buffer::size(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by readHeader().
const char* indri::parse::WARCRecord::getContent () [inline]
References content.
Referenced by indri::parse::WARCDocumentIterator::nextDocument().
const char* indri::parse::WARCRecord::getHeader () [inline]
References header.
Referenced by indri::parse::WARCDocumentIterator::nextDocument().
std::string indri::parse::WARCRecord::getMetadata (const char * key)
References indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), and metadata.
std::string indri::parse::WARCRecord::getTargetURI () [inline]
References targetURI.
Referenced by indri::parse::WARCDocumentIterator::nextDocument().
std::string indri::parse::WARCRecord::getTrecID () [inline]
References trecID.
Referenced by indri::parse::WARCDocumentIterator::nextDocument().
std::string indri::parse::WARCRecord::getUUID () [inline]
References uuid.
Referenced by indri::parse::WARCDocumentIterator::nextDocument(), and indri::parse::WARCDocumentIterator::open().
std::string indri::parse::WARCRecord::getWarcType () [inline]
References warcType.
Referenced by indri::parse::WARCDocumentIterator::nextDocument(), and indri::parse::WARCDocumentIterator::open().
bool indri::parse::WARCRecord::readContent () [private]
References _buffer, _gzin, indri::utility::Buffer::clear(), content, contentLength, indri::utility::Buffer::front(), indri::utility::Buffer::grow(), and indri::utility::Buffer::write().
Referenced by readRecord().
bool indri::parse::WARCRecord::readHeader () [private]
References _buffer, _readLine(), indri::utility::Buffer::clear(), contentLength, CONTENTLENGTH, header, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), metadata, split(), targetURI, trecID, trim_left(), trim_right(), uuid, WARCRECORDID, WARCTARGETURI, WARCTRECID, warcType, and WARCTYPE.
Referenced by readRecord().
bool indri::parse::WARCRecord::readRecord ()
References indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::clear(), contentLength, header, metadata, readContent(), readHeader(), targetURI, trecID, uuid, and warcType.
Referenced by indri::parse::WARCDocumentIterator::nextDocument(), and indri::parse::WARCDocumentIterator::open().
Member Data Documentation
indri::utility::Buffer& indri::parse::WARCRecord::_buffer [private]
Referenced by _readLine(), readContent(), and readHeader().
gzFile& indri::parse::WARCRecord::_gzin [private]
Referenced by _readLine(), and readContent().
const char* indri::parse::WARCRecord::content [private]
Referenced by getContent(), and readContent().
const char * indri::parse::WARCRecord::CONTENTLENGTH = "Content-Length" [static]
Referenced by readHeader().
int indri::parse::WARCRecord::contentLength [private]
Referenced by readContent(), readHeader(), and readRecord().
std::string indri::parse::WARCRecord::header [private]
Referenced by getHeader(), readHeader(), and readRecord().
indri::utility::HashTable< std::string, std::string > indri::parse::WARCRecord::metadata [private]
Referenced by getMetadata(), readHeader(), and readRecord().
std::string indri::parse::WARCRecord::targetURI [private]
Referenced by getTargetURI(), readHeader(), and readRecord().
std::string indri::parse::WARCRecord::trecID [private]
Referenced by getTrecID(), readHeader(), and readRecord().
std::string indri::parse::WARCRecord::uuid [private]
Referenced by getUUID(), readHeader(), and readRecord().
const char * indri::parse::WARCRecord::WARCRECORDID = "WARC-Record-ID" [static]
Referenced by readHeader().
const char * indri::parse::WARCRecord::WARCTARGETURI = "WARC-Target-URI" [static]
Referenced by readHeader().
const char * indri::parse::WARCRecord::WARCTRECID = "WARC-TREC-ID" [static]
Referenced by readHeader().
const char * indri::parse::WARCRecord::WARCTYPE = "WARC-Type" [static]
Referenced by readHeader().
std::string indri::parse::WARCRecord::warcType [private]
Referenced by getWarcType(), readHeader(), and readRecord().
The documentation for this class was generated from the following files:
WARCDocumentIterator.hpp
WARCDocumentIterator.cpp