Indri: indri::infnet::UnorderedWindowNode Class Reference
indri::infnet::UnorderedWindowNode Class Reference
#include <UnorderedWindowNode.hpp>
Classes
struct term_position
Public Member Functions
UnorderedWindowNode (const std::string &name, std::vector< ListIteratorNode * > &children)
UnorderedWindowNode (const std::string &name, std::vector< ListIteratorNode * > &children, int windowSize)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
const std::string & getName () const
void annotate (Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
int _windowSize
std::vector< ListIteratorNode * > _children
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
bool _childrenAlreadySorted
Constructor & Destructor Documentation
indri::infnet::UnorderedWindowNode::UnorderedWindowNode (const std::string & name, std::vector< ListIteratorNode * > & children)
indri::infnet::UnorderedWindowNode::UnorderedWindowNode (const std::string & name, std::vector< ListIteratorNode * > & children, int windowSize)
Member Function Documentation
void indri::infnet::UnorderedWindowNode::annotate (Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, indri::infnet::Annotator::addMatches(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::contains(), and indri::utility::greedy_vector< _Type, _Count >::end().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::UnorderedWindowNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::UnorderedWindowNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::UnorderedWindowNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, indri::index::Extent::begin, and indri::index::Extent::end.
lemur::api::DOCID_T indri::infnet::UnorderedWindowNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
void indri::infnet::UnorderedWindowNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _children, _childrenAlreadySorted, _extents, indri::infnet::ListIteratorNode::_lastExtent, _windowSize, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::infnet::UnorderedWindowNode::term_position::begin, indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::UnorderedWindowNode::term_position::end, indri::index::Extent::end, indri::infnet::ListIteratorNode::initpointer(), indri::infnet::UnorderedWindowNode::term_position::last, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::infnet::UnorderedWindowNode::term_position::type, indri::infnet::UWNodeChildLess(), and indri::infnet::UnorderedWindowNode::term_position::weight.
Member Data Documentation
std::vector<ListIteratorNode*> indri::infnet::UnorderedWindowNode::_children [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
bool indri::infnet::UnorderedWindowNode::_childrenAlreadySorted [private]
Referenced by prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::UnorderedWindowNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
std::string indri::infnet::UnorderedWindowNode::_name [private]
Referenced by getName().
int indri::infnet::UnorderedWindowNode::_windowSize [private]
Referenced by prepare().
The documentation for this class was generated from the following files:
UnorderedWindowNode.hpp
UnorderedWindowNode.cpp