Indri: indri::infnet::NestedExtentInsideNode Class Reference
indri::infnet::NestedExtentInsideNode Class Reference
#include <NestedExtentInsideNode.hpp>
Public Member Functions
NestedExtentInsideNode (const std::string &name, ListIteratorNode *inner, ListIteratorNode *outer)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
ListIteratorNode * _inner
ListIteratorNode * _outer
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
Constructor & Destructor Documentation
indri::infnet::NestedExtentInsideNode::NestedExtentInsideNode (const std::string & name, ListIteratorNode * inner, ListIteratorNode * outer)
Member Function Documentation
void indri::infnet::NestedExtentInsideNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, _inner, indri::infnet::ListIteratorNode::_lastExtent, _outer, indri::infnet::Annotator::addMatches(), indri::infnet::ListIteratorNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::index::Extent::contains(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, and indri::utility::greedy_vector< _Type, _Count >::size().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::NestedExtentInsideNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
const std::string & indri::infnet::NestedExtentInsideNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::NestedExtentInsideNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, indri::index::Extent::begin, and indri::index::Extent::end.
lemur::api::DOCID_T indri::infnet::NestedExtentInsideNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _inner, _outer, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
void indri::infnet::NestedExtentInsideNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _extents, _inner, indri::infnet::ListIteratorNode::_lastExtent, _outer, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, indri::infnet::ListIteratorNode::extents(), indri::infnet::ListIteratorNode::initpointer(), indri::index::Extent::ordinal, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::index::Extent::weight.
Member Data Documentation
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::NestedExtentInsideNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
ListIteratorNode* indri::infnet::NestedExtentInsideNode::_inner [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
std::string indri::infnet::NestedExtentInsideNode::_name [private]
Referenced by getName().
ListIteratorNode* indri::infnet::NestedExtentInsideNode::_outer [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
The documentation for this class was generated from the following files:
NestedExtentInsideNode.hpp
NestedExtentInsideNode.cpp