Indri: indri::server::QueryServer Class Reference
indri::server::QueryServer Class Reference
#include <QueryServer.hpp>
Public Member Functions
virtual ~QueryServer ()
virtual QueryServerResponse * runQuery (std::vector< indri::lang::Node * > &roots, int resultsRequested, bool optimize)=0
virtual
QueryServerDocumentsResponse * documents (const std::vector< lemur::api::DOCID_T > &documentIDs)=0
virtual
QueryServerMetadataResponse * documentMetadata (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::string &attributeName)=0
virtual
QueryServerDocumentsResponse * documentsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)=0
virtual
QueryServerDocumentIDsResponse * documentIDsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)=0
virtual
QueryServerMetadataResponse * pathNames (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::vector< int > &pathBegins, const std::vector< int > &pathEnds)=0
virtual INT64 termCount ()=0
virtual INT64 termCount (const std::string &term)=0
virtual INT64 termCountUnique ()=0
virtual INT64 stemCount (const std::string &stem)=0
virtual std::string termName (lemur::api::TERMID_T term)=0
virtual lemur::api::TERMID_T termID (const std::string &term)=0
virtual std::string stemTerm (const std::string &term)=0
virtual std::vector< std::string > fieldList ()=0
virtual INT64 termFieldCount (const std::string &term, const std::string &field)=0
virtual INT64 stemFieldCount (const std::string &stem, const std::string &field)=0
virtual int documentLength (lemur::api::DOCID_T documentID)=0
virtual INT64 documentCount ()=0
virtual INT64 documentCount (const std::string &term)=0
virtual INT64 documentStemCount (const std::string &term)=0
virtual
QueryServerVectorsResponse * documentVectors (const std::vector< lemur::api::DOCID_T > &documentIDs)=0
virtual void setMaxWildcardTerms (int maxTerms)=0
Constructor & Destructor Documentation
virtual indri::server::QueryServer::~QueryServer () [inline, virtual]
Member Function Documentation
virtual INT64 indri::server::QueryServer::documentCount (const std::string & term) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
virtual INT64 indri::server::QueryServer::documentCount () [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentCount(), and indri::net::NetworkServerStub::_handleDocumentTermCount().
virtual QueryServerDocumentIDsResponse* indri::server::QueryServer::documentIDsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentIDsFromMetadata().
virtual int indri::server::QueryServer::documentLength (lemur::api::DOCID_T documentID) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentLength().
virtual QueryServerMetadataResponse* indri::server::QueryServer::documentMetadata (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::string & attributeName) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentMetadata().
virtual QueryServerDocumentsResponse* indri::server::QueryServer::documents (const std::vector< lemur::api::DOCID_T > & documentIDs) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocuments().
virtual QueryServerDocumentsResponse* indri::server::QueryServer::documentsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentsFromMetadata().
virtual INT64 indri::server::QueryServer::documentStemCount (const std::string & term) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentStemCount().
virtual QueryServerVectorsResponse* indri::server::QueryServer::documentVectors (const std::vector< lemur::api::DOCID_T > & documentIDs) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleDocumentVectors().
virtual std::vector<std::string> indri::server::QueryServer::fieldList () [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleFieldList().
virtual QueryServerMetadataResponse* indri::server::QueryServer::pathNames (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::vector< int > & pathBegins, const std::vector< int > & pathEnds) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handlePathNames().
virtual QueryServerResponse* indri::server::QueryServer::runQuery (std::vector< indri::lang::Node * > & roots, int resultsRequested, bool optimize) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleQuery().
virtual void indri::server::QueryServer::setMaxWildcardTerms (int maxTerms) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleSetMaxWildcardTerms().
virtual INT64 indri::server::QueryServer::stemCount (const std::string & stem) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleStemCountText().
virtual INT64 indri::server::QueryServer::stemFieldCount (const std::string & stem, const std::string & field) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleStemFieldCount().
virtual std::string indri::server::QueryServer::stemTerm (const std::string & term) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleStemTerm().
virtual INT64 indri::server::QueryServer::termCount (const std::string & term) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
virtual INT64 indri::server::QueryServer::termCount () [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleTermCount(), and indri::net::NetworkServerStub::_handleTermCountText().
virtual INT64 indri::server::QueryServer::termCountUnique () [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleTermCountUnique().
virtual INT64 indri::server::QueryServer::termFieldCount (const std::string & term, const std::string & field) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleTermFieldCount().
virtual lemur::api::TERMID_T indri::server::QueryServer::termID (const std::string & term) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleTermID().
virtual std::string indri::server::QueryServer::termName (lemur::api::TERMID_T term) [pure virtual]
Implemented in indri::server::LocalQueryServer, and indri::server::NetworkServerProxy.
Referenced by indri::net::NetworkServerStub::_handleTermName().
The documentation for this class was generated from the following file:
QueryServer.hpp