Indri: indri::lang::TreePrinterWalker Class Reference
indri::lang::TreePrinterWalker Class Reference
#include <TreePrinterWalker.hpp>
Public Member Functions
TreePrinterWalker ()
void before (indri::lang::IndexTerm *node)
void before (indri::lang::Field *node)
void defaultBefore (indri::lang::Node *node)
void defaultAfter (indri::lang::Node *node)
Private Attributes
unsigned int _tabs
Constructor & Destructor Documentation
indri::lang::TreePrinterWalker::TreePrinterWalker () [inline]
Member Function Documentation
void indri::lang::TreePrinterWalker::before (indri::lang::Field * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _tabs, indri::lang::Field::getFieldName(), and indri::lang::Node::nodeName().
void indri::lang::TreePrinterWalker::before (indri::lang::IndexTerm * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _tabs, indri::lang::IndexTerm::getText(), and indri::lang::Node::nodeName().
void indri::lang::TreePrinterWalker::defaultAfter (indri::lang::Node * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _tabs.
void indri::lang::TreePrinterWalker::defaultBefore (indri::lang::Node * node) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _tabs, indri::lang::Node::queryText(), and indri::lang::Node::typeName().
Member Data Documentation
unsigned int indri::lang::TreePrinterWalker::_tabs [private]
Referenced by before(), defaultAfter(), and defaultBefore().
The documentation for this class was generated from the following file:
TreePrinterWalker.hpp