Indri: indri::lang::ExtentRestrictionModelAnnotatorCopier Class Reference
indri::lang::ExtentRestrictionModelAnnotatorCopier Class Reference
#include <ExtentRestrictionModelAnnotatorCopier.hpp>
Public Member Functions
~ExtentRestrictionModelAnnotatorCopier ()
indri::lang::Node * defaultAfter (indri::lang::Node *old, indri::lang::Node *newNode)
void before (indri::lang::ExtentRestriction *old)
void before (indri::lang::ExtentEnforcement *old)
indri::lang::Node * after (indri::lang::ExtentRestriction *oldNode, indri::lang::ExtentRestriction *newNode)
indri::lang::Node * after (indri::lang::ExtentEnforcement *oldNode, indri::lang::ExtentEnforcement *newNode)
indri::lang::Node * after (indri::lang::RawScorerNode *oldNode, indri::lang::RawScorerNode *newNode)
indri::lang::Node * after (indri::lang::NestedRawScorerNode *oldNode, indri::lang::NestedRawScorerNode *newNode)
Private Attributes
std::vector< indri::lang::Node * > _nodes
std::stack
< indri::lang::ExtentRestriction * > _restrictions
Constructor & Destructor Documentation
indri::lang::ExtentRestrictionModelAnnotatorCopier::~ExtentRestrictionModelAnnotatorCopier () [inline]
References _nodes, and indri::utility::delete_vector_contents().
Member Function Documentation
indri::lang::Node* indri::lang::ExtentRestrictionModelAnnotatorCopier::after (indri::lang::NestedRawScorerNode * oldNode, indri::lang::NestedRawScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References after().
indri::lang::Node* indri::lang::ExtentRestrictionModelAnnotatorCopier::after (indri::lang::RawScorerNode * oldNode, indri::lang::RawScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, _restrictions, indri::lang::RawScorerNode::getContext(), and indri::lang::RawScorerNode::setContext().
indri::lang::Node* indri::lang::ExtentRestrictionModelAnnotatorCopier::after (indri::lang::ExtentEnforcement * oldNode, indri::lang::ExtentEnforcement * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References after().
indri::lang::Node* indri::lang::ExtentRestrictionModelAnnotatorCopier::after (indri::lang::ExtentRestriction * oldNode, indri::lang::ExtentRestriction * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes, and _restrictions.
Referenced by after().
void indri::lang::ExtentRestrictionModelAnnotatorCopier::before (indri::lang::ExtentEnforcement * old) [inline, virtual]
Reimplemented from indri::lang::Copier.
References before().
void indri::lang::ExtentRestrictionModelAnnotatorCopier::before (indri::lang::ExtentRestriction * old) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _restrictions.
Referenced by before().
indri::lang::Node* indri::lang::ExtentRestrictionModelAnnotatorCopier::defaultAfter (indri::lang::Node * old, indri::lang::Node * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _nodes.
Member Data Documentation
std::vector<indri::lang::Node*> indri::lang::ExtentRestrictionModelAnnotatorCopier::_nodes [private]
Referenced by after(), defaultAfter(), and ~ExtentRestrictionModelAnnotatorCopier().
std::stack< indri::lang::ExtentRestriction* > indri::lang::ExtentRestrictionModelAnnotatorCopier::_restrictions [private]
Referenced by after(), and before().
The documentation for this class was generated from the following file:
ExtentRestrictionModelAnnotatorCopier.hpp