Indri: indri::lang::ExtentInside Class Reference
indri::lang::ExtentInside Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ExtentInside (RawExtentNode *inner, RawExtentNode *outer)
ExtentInside (Unpacker &unpacker)
virtual bool operator== (Node &o)
virtual std::string typeName () const
virtual UINT64 hashCode () const
std::string queryText () const
void setInner (RawExtentNode *inner)
void setOuter (RawExtentNode *outer)
RawExtentNode * getInner ()
RawExtentNode * getOuter ()
void pack (Packer &packer)
void walk (Walker &walker)
virtual Node * copy (Copier &copier)
Protected Attributes
RawExtentNode * _inner
RawExtentNode * _outer
Constructor & Destructor Documentation
indri::lang::ExtentInside::ExtentInside (RawExtentNode * inner, RawExtentNode * outer) [inline]
Referenced by copy().
indri::lang::ExtentInside::ExtentInside (Unpacker & unpacker) [inline]
References _inner, _outer, and indri::lang::Unpacker::getRawExtentNode().
Member Function Documentation
virtual Node* indri::lang::ExtentInside::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::NestedExtentInside, indri::lang::ExtentDescendant, indri::lang::ExtentChild, and indri::lang::ExtentParent.
References _inner, _outer, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), ExtentInside(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
RawExtentNode* indri::lang::ExtentInside::getInner () [inline]
References _inner.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), NexiParser::aboutClause(), indri::infnet::InferenceNetworkBuilder::after(), NexiParser::arithmeticClause(), QueryParser::innerMost(), QueryParser::path(), and NexiParser::query().
RawExtentNode* indri::lang::ExtentInside::getOuter () [inline]
References _outer.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), and indri::infnet::InferenceNetworkBuilder::after().
virtual UINT64 indri::lang::ExtentInside::hashCode () const [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::NestedExtentInside, indri::lang::ExtentDescendant, indri::lang::ExtentChild, and indri::lang::ExtentParent.
References _inner, and indri::lang::Node::hashCode().
virtual bool indri::lang::ExtentInside::operator== (Node & o) [inline, virtual]
Reimplemented in indri::lang::NestedExtentInside, indri::lang::ExtentDescendant, indri::lang::ExtentChild, and indri::lang::ExtentParent.
References _inner, and _outer.
void indri::lang::ExtentInside::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _inner, _outer, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ExtentInside::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _inner, _outer, and indri::lang::Node::queryText().
void indri::lang::ExtentInside::setInner (RawExtentNode * inner) [inline]
References _inner.
Referenced by NexiParser::aboutClause(), NexiParser::arithmeticClause(), QueryParser::path(), NexiParser::path(), and NexiParser::query().
void indri::lang::ExtentInside::setOuter (RawExtentNode * outer) [inline]
References _outer.
Referenced by QueryParser::context_list(), QueryParser::extentRestriction(), and QueryParser::path().
virtual std::string indri::lang::ExtentInside::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
Reimplemented in indri::lang::NestedExtentInside, indri::lang::ExtentDescendant, indri::lang::ExtentChild, and indri::lang::ExtentParent.
void indri::lang::ExtentInside::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
Reimplemented in indri::lang::ExtentDescendant, indri::lang::ExtentChild, and indri::lang::ExtentParent.
References _inner, _outer, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Referenced by indri::infnet::InferenceNetworkBuilder::after().
Member Data Documentation
RawExtentNode* indri::lang::ExtentInside::_inner [protected]
Referenced by indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::NestedExtentInside::copy(), copy(), ExtentInside(), getInner(), indri::lang::ExtentParent::hashCode(), indri::lang::ExtentChild::hashCode(), indri::lang::ExtentDescendant::hashCode(), indri::lang::NestedExtentInside::hashCode(), hashCode(), indri::lang::ExtentParent::operator==(), indri::lang::ExtentChild::operator==(), indri::lang::ExtentDescendant::operator==(), indri::lang::NestedExtentInside::operator==(), operator==(), pack(), queryText(), setInner(), indri::lang::ExtentParent::walk(), indri::lang::ExtentChild::walk(), indri::lang::ExtentDescendant::walk(), and walk().
RawExtentNode* indri::lang::ExtentInside::_outer [protected]
Referenced by indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::NestedExtentInside::copy(), copy(), ExtentInside(), getOuter(), indri::lang::ExtentParent::operator==(), indri::lang::ExtentChild::operator==(), indri::lang::ExtentDescendant::operator==(), indri::lang::NestedExtentInside::operator==(), operator==(), pack(), queryText(), setOuter(), indri::lang::ExtentParent::walk(), indri::lang::ExtentChild::walk(), indri::lang::ExtentDescendant::walk(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp