Indri: indri::lang::TermFrequencyScorerNode Class Reference
indri::lang::TermFrequencyScorerNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
TermFrequencyScorerNode (const std::string &text, bool stemmed)
TermFrequencyScorerNode (Unpacker &unpacker)
const std::string & getText () const
bool getStemmed () const
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
double getOccurrences () const
double getContextSize () const
int getDocumentOccurrences () const
int getDocumentCount () const
const std::string & getSmoothing () const
void setStatistics (double occurrences, double contextSize, int documentOccurrences, int documentCount)
void setSmoothing (const std::string &smoothing)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
double _occurrences
double _contextSize
int _documentOccurrences
int _documentCount
std::string _text
std::string _smoothing
bool _stemmed
Constructor & Destructor Documentation
indri::lang::TermFrequencyScorerNode::TermFrequencyScorerNode (const std::string & text, bool stemmed) [inline]
References _contextSize, _documentCount, _documentOccurrences, _occurrences, _smoothing, _stemmed, and _text.
Referenced by copy().
indri::lang::TermFrequencyScorerNode::TermFrequencyScorerNode (Unpacker & unpacker) [inline]
References _contextSize, _documentCount, _documentOccurrences, _occurrences, _smoothing, _stemmed, _text, indri::lang::Unpacker::getBoolean(), indri::lang::Unpacker::getDouble(), indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getString().
Member Function Documentation
Node* indri::lang::TermFrequencyScorerNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Copier::after(), indri::lang::Copier::before(), and TermFrequencyScorerNode().
double indri::lang::TermFrequencyScorerNode::getContextSize () const [inline]
References _contextSize.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::lang::TermFrequencyScorerNode::getDocumentCount () const [inline]
References _documentCount.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
int indri::lang::TermFrequencyScorerNode::getDocumentOccurrences () const [inline]
References _documentOccurrences.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
double indri::lang::TermFrequencyScorerNode::getOccurrences () const [inline]
References _occurrences.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
const std::string& indri::lang::TermFrequencyScorerNode::getSmoothing () const [inline]
References _smoothing.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
bool indri::lang::TermFrequencyScorerNode::getStemmed () const [inline]
References _stemmed.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
const std::string& indri::lang::TermFrequencyScorerNode::getText () const [inline]
References _text.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::TermFrequencyScorerNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _smoothing, _stemmed, and _text.
void indri::lang::TermFrequencyScorerNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _contextSize, _documentCount, _documentOccurrences, _occurrences, _smoothing, _stemmed, _text, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::TermFrequencyScorerNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _stemmed, and _text.
void indri::lang::TermFrequencyScorerNode::setSmoothing (const std::string & smoothing) [inline]
References _smoothing.
Referenced by indri::lang::FrequencyListCopier::after().
void indri::lang::TermFrequencyScorerNode::setStatistics (double occurrences, double contextSize, int documentOccurrences, int documentCount) [inline]
References _contextSize, _documentCount, _documentOccurrences, and _occurrences.
Referenced by indri::lang::FrequencyListCopier::after().
std::string indri::lang::TermFrequencyScorerNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::TermFrequencyScorerNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
double indri::lang::TermFrequencyScorerNode::_contextSize [private]
Referenced by getContextSize(), pack(), setStatistics(), and TermFrequencyScorerNode().
int indri::lang::TermFrequencyScorerNode::_documentCount [private]
Referenced by getDocumentCount(), pack(), setStatistics(), and TermFrequencyScorerNode().
int indri::lang::TermFrequencyScorerNode::_documentOccurrences [private]
Referenced by getDocumentOccurrences(), pack(), setStatistics(), and TermFrequencyScorerNode().
double indri::lang::TermFrequencyScorerNode::_occurrences [private]
Referenced by getOccurrences(), pack(), setStatistics(), and TermFrequencyScorerNode().
std::string indri::lang::TermFrequencyScorerNode::_smoothing [private]
Referenced by getSmoothing(), hashCode(), pack(), setSmoothing(), and TermFrequencyScorerNode().
bool indri::lang::TermFrequencyScorerNode::_stemmed [private]
Referenced by getStemmed(), hashCode(), pack(), queryText(), and TermFrequencyScorerNode().
std::string indri::lang::TermFrequencyScorerNode::_text [private]
Referenced by getText(), hashCode(), pack(), queryText(), and TermFrequencyScorerNode().
The documentation for this class was generated from the following file:
QuerySpec.hpp