Indri: indri::thread::ReadersWritersLock Class Reference
indri::thread::ReadersWritersLock Class Reference
#include <ReadersWritersLock.hpp>
Classes
struct wait_queue_entry
Public Member Functions
ReadersWritersLock ()
void lockRead ()
void lockWrite ()
void unlockWrite ()
void unlockRead ()
void yieldWrite ()
void yieldRead ()
Private Member Functions
void _enqueue (wait_queue_entry &entry)
void _wakeOthers ()
Private Attributes
Mutex _mutex
wait_queue_entry * _head
wait_queue_entry * _tail
int _readers
int _writers
Constructor & Destructor Documentation
indri::thread::ReadersWritersLock::ReadersWritersLock () [inline]
Member Function Documentation
void indri::thread::ReadersWritersLock::_enqueue (wait_queue_entry & entry) [inline, private]
References _head, _tail, indri::thread::ReadersWritersLock::wait_queue_entry::awakened, and indri::thread::ReadersWritersLock::wait_queue_entry::next.
Referenced by lockRead(), and lockWrite().
void indri::thread::ReadersWritersLock::_wakeOthers () [inline, private]
References _head, _tail, indri::thread::ReadersWritersLock::wait_queue_entry::awakened, indri::thread::ReadersWritersLock::wait_queue_entry::next, indri::thread::ConditionVariable::notifyOne(), indri::thread::ReadersWritersLock::wait_queue_entry::wakeup, and indri::thread::ReadersWritersLock::wait_queue_entry::writing.
Referenced by unlockRead(), and unlockWrite().
void indri::thread::ReadersWritersLock::lockRead () [inline]
References _enqueue(), _head, _mutex, _readers, _writers, indri::thread::Mutex::lock(), indri::thread::ReadersWritersLock::wait_queue_entry::next, indri::thread::Mutex::unlock(), indri::thread::ConditionVariable::wait(), indri::thread::ReadersWritersLock::wait_queue_entry::wakeup, and indri::thread::ReadersWritersLock::wait_queue_entry::writing.
Referenced by indri::thread::ReaderLockable::lock(), indri::index::DeletedDocumentList::read_transaction::read_transaction(), and yieldRead().
void indri::thread::ReadersWritersLock::lockWrite () [inline]
References _enqueue(), _head, _mutex, _readers, _writers, indri::thread::Mutex::lock(), indri::thread::ReadersWritersLock::wait_queue_entry::next, indri::thread::Mutex::unlock(), indri::thread::ConditionVariable::wait(), indri::thread::ReadersWritersLock::wait_queue_entry::wakeup, and indri::thread::ReadersWritersLock::wait_queue_entry::writing.
Referenced by indri::thread::WriterLockable::lock(), and yieldWrite().
void indri::thread::ReadersWritersLock::unlockRead () [inline]
References _mutex, _readers, _wakeOthers(), _writers, indri::thread::Mutex::lock(), and indri::thread::Mutex::unlock().
Referenced by indri::thread::ReaderLockable::unlock(), yieldRead(), and indri::index::DeletedDocumentList::read_transaction::~read_transaction().
void indri::thread::ReadersWritersLock::unlockWrite () [inline]
References _mutex, _readers, _wakeOthers(), _writers, indri::thread::Mutex::lock(), and indri::thread::Mutex::unlock().
Referenced by indri::thread::WriterLockable::unlock(), and yieldWrite().
void indri::thread::ReadersWritersLock::yieldRead () [inline]
References _head, _readers, _writers, lockRead(), and unlockRead().
Referenced by indri::index::DeletedDocumentList::read_transaction::nextCandidateDocument().
void indri::thread::ReadersWritersLock::yieldWrite () [inline]
References _head, _readers, _writers, lockWrite(), and unlockWrite().
Member Data Documentation
wait_queue_entry* indri::thread::ReadersWritersLock::_head [private]
Referenced by _enqueue(), _wakeOthers(), lockRead(), lockWrite(), yieldRead(), and yieldWrite().
Mutex indri::thread::ReadersWritersLock::_mutex [private]
Referenced by lockRead(), lockWrite(), unlockRead(), and unlockWrite().
int indri::thread::ReadersWritersLock::_readers [private]
Referenced by lockRead(), lockWrite(), unlockRead(), unlockWrite(), yieldRead(), and yieldWrite().
wait_queue_entry* indri::thread::ReadersWritersLock::_tail [private]
Referenced by _enqueue(), and _wakeOthers().
int indri::thread::ReadersWritersLock::_writers [private]
Referenced by lockRead(), lockWrite(), unlockRead(), unlockWrite(), yieldRead(), and yieldWrite().
The documentation for this class was generated from the following file:
ReadersWritersLock.hpp