Indri: indri::lang::IndexTerm Class Reference
indri::lang::IndexTerm Class Reference
#include <QuerySpec.hpp>
Public Member Functions
IndexTerm (const std::string &text, bool stemmed=false)
IndexTerm (Unpacker &unpacker)
const std::string & getText ()
bool operator== (Node &node)
std::string typeName () const
std::string queryText () const
void setStemmed (bool stemmed)
bool getStemmed () const
UINT64 hashCode () const
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
std::string _text
bool _stemmed
Constructor & Destructor Documentation
indri::lang::IndexTerm::IndexTerm (const std::string & text, bool stemmed = false) [inline]
Referenced by copy().
indri::lang::IndexTerm::IndexTerm (Unpacker & unpacker) [inline]
References _stemmed, _text, indri::lang::Unpacker::getBoolean(), and indri::lang::Unpacker::getString().
Member Function Documentation
Node* indri::lang::IndexTerm::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Copier::after(), indri::lang::Copier::before(), and IndexTerm().
bool indri::lang::IndexTerm::getStemmed () const [inline]
References _stemmed.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), indri::lang::FrequencyListCopier::after(), and indri::lang::ContextSimpleCountCollectorCopier::after().
const std::string& indri::lang::IndexTerm::getText () [inline]
References _text.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), indri::lang::FrequencyListCopier::after(), indri::lang::ContextSimpleCountCollectorCopier::after(), indri::lang::TreePrinterWalker::before(), QueryParser::unqualifiedTerm(), and QueryParser::wildcardOpNode().
UINT64 indri::lang::IndexTerm::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _stemmed, and _text.
bool indri::lang::IndexTerm::operator== (Node & node) [inline]
References _text.
void indri::lang::IndexTerm::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _stemmed, _text, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::IndexTerm::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _stemmed, and _text.
void indri::lang::IndexTerm::setStemmed (bool stemmed) [inline]
References _stemmed.
Referenced by QueryParser::rawText().
std::string indri::lang::IndexTerm::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::IndexTerm::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
bool indri::lang::IndexTerm::_stemmed [private]
Referenced by getStemmed(), hashCode(), IndexTerm(), pack(), queryText(), and setStemmed().
std::string indri::lang::IndexTerm::_text [private]
Referenced by getText(), hashCode(), IndexTerm(), operator==(), pack(), and queryText().
The documentation for this class was generated from the following file:
QuerySpec.hpp