Indri: Indri::Char_pVector Class Reference
Indri::Char_pVector Class Reference
Classes
class Char_pVectorEnumerator
Public Member Functions
virtual void Dispose ()
Char_pVector (System.Collections.ICollection c)
void CopyTo (System.Array array)
void CopyTo (System.Array array, int arrayIndex)
void CopyTo (int index, System.Array array, int arrayIndex, int count)
Char_pVectorEnumerator GetEnumerator ()
void Clear ()
void Add (string value)
Char_pVector ()
Char_pVector (int capacity)
void AddRange (Char_pVector values)
Char_pVector GetRange (int index, int count)
void Insert (int index, string value)
void InsertRange (int index, Char_pVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, Char_pVector values)
Static Public Member Functions
static Char_pVector Repeat (string value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
string this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal Char_pVector (IntPtr cPtr, bool cMemoryOwn)
~Char_pVector ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
string getitemcopy (int index)
string getitem (int index)
void setitem (int index, string value)
Static Private Member Functions
static internal HandleRef getCPtr (Char_pVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::Char_pVector::Char_pVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::Char_pVector::~Char_pVector () [inline, private]
References Dispose().
Indri::Char_pVector::Char_pVector (System.Collections.ICollection c) [inline]
References Add().
Indri::Char_pVector::Char_pVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::Char_pVector::Char_pVector (int capacity) [inline]
Member Function Documentation
void Indri::Char_pVector::Add (string value) [inline]
References swigCPtr.
Referenced by Char_pVector().
void Indri::Char_pVector::AddRange (Char_pVector values) [inline]
References swigCPtr.
uint Indri::Char_pVector::capacity () [inline, private]
References swigCPtr.
void Indri::Char_pVector::Clear () [inline]
References swigCPtr.
void Indri::Char_pVector::CopyTo (int index, System.Array array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::Char_pVector::CopyTo (System.Array array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::Char_pVector::CopyTo (System.Array array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::Char_pVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~Char_pVector().
static internal HandleRef Indri::Char_pVector::getCPtr (Char_pVector obj) [inline, static, private]
References swigCPtr.
Char_pVectorEnumerator Indri::Char_pVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::Char_pVector::GetEnumerator () [inline, private]
string Indri::Char_pVector::getitem (int index) [inline, private]
References swigCPtr.
string Indri::Char_pVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
Char_pVector Indri::Char_pVector::GetRange (int index, int count) [inline]
References Char_pVector(), and swigCPtr.
void Indri::Char_pVector::Insert (int index, string value) [inline]
References swigCPtr.
void Indri::Char_pVector::InsertRange (int index, Char_pVector values) [inline]
References swigCPtr.
void Indri::Char_pVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::Char_pVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static Char_pVector Indri::Char_pVector::Repeat (string value, int count) [inline, static]
References Char_pVector().
void Indri::Char_pVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::Char_pVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::Char_pVector::Reverse () [inline]
References swigCPtr.
void Indri::Char_pVector::setitem (int index, string value) [inline, private]
References swigCPtr.
void Indri::Char_pVector::SetRange (int index, Char_pVector values) [inline]
References swigCPtr.
uint Indri::Char_pVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::Char_pVector::Char_pVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::Char_pVector::swigCMemOwn [protected]
Referenced by Char_pVector(), and Dispose().
HandleRef Indri::Char_pVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Char_pVector(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::Char_pVector::Capacity [get, set]
int Indri::Char_pVector::Count [get]
Referenced by Indri::Char_pVector::Char_pVectorEnumerator::Char_pVectorEnumerator(), CopyTo(), Indri::Char_pVector::Char_pVectorEnumerator::MoveNext(), and Indri::Char_pVector::Char_pVectorEnumerator::Reset().
bool Indri::Char_pVector::IsFixedSize [get]
bool Indri::Char_pVector::IsReadOnly [get]
bool Indri::Char_pVector::IsSynchronized [get]
string Indri::Char_pVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
Char_pVector.cs