Indri: indri::lang::MaxNode Class Reference
indri::lang::MaxNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
MaxNode ()
MaxNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::MaxNode::MaxNode () [inline]
indri::lang::MaxNode::MaxNode (Unpacker & unpacker) [inline]
References indri::lang::UnweightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::MaxNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_copy().
UINT64 indri::lang::MaxNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_hashCode().
std::string indri::lang::MaxNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_childText().
std::string indri::lang::MaxNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::MaxNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp