Indri: indri::net::NetworkMessageStream Class Reference
indri::net::NetworkMessageStream Class Reference
#include <NetworkMessageStream.hpp>
Public Member Functions
NetworkMessageStream (NetworkStream *stream)
void read (MessageStreamHandler &handler)
void request (indri::xml::XMLNode *messageNode)
void reply (indri::xml::XMLNode *replyNode)
void reply (const std::string &name, const void *buffer, unsigned int size)
void replyDone ()
void error (const std::string &errorMessage)
bool alive ()
indri::thread::Lockable & mutex ()
Private Member Functions
int _findEOL ()
void _cleanBuffer ()
int _bufferLength ()
Private Attributes
indri::thread::Mutex _lock
indri::utility::Buffer _buffer
NetworkStream * _stream
int _readPosition
int _writePosition
Constructor & Destructor Documentation
indri::net::NetworkMessageStream::NetworkMessageStream (NetworkStream * stream)
References _buffer, _readPosition, _writePosition, and indri::utility::Buffer::grow().
Member Function Documentation
int indri::net::NetworkMessageStream::_bufferLength () [private]
References _readPosition, and _writePosition.
Referenced by read().
void indri::net::NetworkMessageStream::_cleanBuffer () [private]
References _buffer, _readPosition, _writePosition, and indri::utility::Buffer::remove().
Referenced by read().
int indri::net::NetworkMessageStream::_findEOL () [private]
References _buffer, _readPosition, _writePosition, and indri::utility::Buffer::front().
Referenced by read().
bool indri::net::NetworkMessageStream::alive ()
References _stream, and indri::net::NetworkStream::alive().
Referenced by connection_thread(), indri::net::QueryResponseUnpacker::getResults(), indri::net::NetworkServerStub::run(), and indri::net::XMLReplyReceiver::wait().
void indri::net::NetworkMessageStream::error (const std::string & errorMessage)
References _stream, and indri::net::NetworkStream::write().
Referenced by indri::net::NetworkServerStub::request().
indri::thread::Lockable & indri::net::NetworkMessageStream::mutex ()
References _lock.
Referenced by indri::server::NetworkServerProxy::_numericRequest(), indri::server::NetworkServerProxy::_stringRequest(), indri::server::NetworkServerProxy::documentIDsFromMetadata(), indri::server::NetworkServerProxy::documentMetadata(), indri::server::NetworkServerProxy::documents(), indri::server::NetworkServerProxy::documentsFromMetadata(), indri::server::NetworkServerProxy::documentVectors(), indri::server::NetworkServerProxy::fieldList(), indri::server::NetworkServerProxy::pathNames(), indri::server::NetworkServerProxy::runQuery(), indri::server::NetworkServerProxyDocumentIDsResponse::~NetworkServerProxyDocumentIDsResponse(), indri::server::NetworkServerProxyDocumentsResponse::~NetworkServerProxyDocumentsResponse(), indri::server::NetworkServerProxyMetadataResponse::~NetworkServerProxyMetadataResponse(), indri::server::NetworkServerProxyResponse::~NetworkServerProxyResponse(), and indri::server::NetworkServerProxyVectorsResponse::~NetworkServerProxyVectorsResponse().
void indri::net::NetworkMessageStream::read (MessageStreamHandler & handler)
References _buffer, _bufferLength(), _cleanBuffer(), _findEOL(), _readPosition, _stream, _writePosition, indri::net::NetworkStream::blockingRead(), indri::net::NetworkStream::close(), indri::net::MessageStreamHandler::error(), indri::utility::Buffer::front(), indri::utility::Buffer::grow(), indri::xml::XMLReader::read(), indri::net::NetworkStream::read(), indri::net::MessageStreamHandler::reply(), indri::net::MessageStreamHandler::replyDone(), indri::net::MessageStreamHandler::request(), indri::utility::Buffer::size(), and indri::utility::Buffer::write().
Referenced by connection_thread(), indri::net::QueryResponseUnpacker::getResults(), indri::net::NetworkServerStub::run(), and indri::net::XMLReplyReceiver::wait().
void indri::net::NetworkMessageStream::reply (const std::string & name, const void * buffer, unsigned int size)
References _stream, indri::net::NetworkStream::blockingWrite(), i64_to_string(), and indri::net::NetworkStream::write().
void indri::net::NetworkMessageStream::reply (indri::xml::XMLNode * replyNode)
References _stream, indri::net::NetworkStream::blockingWrite(), i64_to_string(), indri::net::NetworkStream::write(), and indri::xml::XMLWriter::write().
Referenced by indri::net::NetworkServerStub::_handleDocumentIDsFromMetadata(), indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handleDocumentVectors(), indri::net::NetworkServerStub::_handleFieldList(), indri::net::NetworkServerStub::_handlePathNames(), indri::net::NetworkServerStub::_handleStemTerm(), indri::net::NetworkServerStub::_handleTermName(), indri::net::NetworkServerStub::_sendDocumentsResponse(), indri::net::NetworkServerStub::_sendNumericResponse(), and indri::net::QueryResponsePacker::write().
void indri::net::NetworkMessageStream::replyDone ()
References _stream, and indri::net::NetworkStream::write().
Referenced by indri::net::NetworkServerStub::_handleDocumentIDsFromMetadata(), indri::net::NetworkServerStub::_handleDocumentMetadata(), indri::net::NetworkServerStub::_handleDocumentVectors(), indri::net::NetworkServerStub::_handleFieldList(), indri::net::NetworkServerStub::_handlePathNames(), indri::net::NetworkServerStub::_handleStemTerm(), indri::net::NetworkServerStub::_handleTermName(), indri::net::NetworkServerStub::_sendDocumentsResponse(), indri::net::NetworkServerStub::_sendNumericResponse(), and indri::net::QueryResponsePacker::write().
void indri::net::NetworkMessageStream::request (indri::xml::XMLNode * messageNode)
References _stream, indri::net::NetworkStream::blockingWrite(), i64_to_string(), indri::net::NetworkStream::write(), and indri::xml::XMLWriter::write().
Referenced by indri::server::NetworkServerProxy::_numericRequest(), indri::server::NetworkServerProxy::_stringRequest(), indri::server::NetworkServerProxy::documentIDsFromMetadata(), indri::server::NetworkServerProxy::documentMetadata(), indri::server::NetworkServerProxy::documents(), indri::server::NetworkServerProxy::documentsFromMetadata(), indri::server::NetworkServerProxy::documentVectors(), indri::server::NetworkServerProxy::fieldList(), indri::server::NetworkServerProxy::pathNames(), and indri::server::NetworkServerProxy::runQuery().
Member Data Documentation
indri::utility::Buffer indri::net::NetworkMessageStream::_buffer [private]
Referenced by _cleanBuffer(), _findEOL(), NetworkMessageStream(), and read().
indri::thread::Mutex indri::net::NetworkMessageStream::_lock [private]
Referenced by mutex().
int indri::net::NetworkMessageStream::_readPosition [private]
Referenced by _bufferLength(), _cleanBuffer(), _findEOL(), NetworkMessageStream(), and read().
NetworkStream* indri::net::NetworkMessageStream::_stream [private]
Referenced by alive(), error(), read(), reply(), replyDone(), and request().
int indri::net::NetworkMessageStream::_writePosition [private]
Referenced by _bufferLength(), _cleanBuffer(), _findEOL(), NetworkMessageStream(), and read().
The documentation for this class was generated from the following files:
NetworkMessageStream.hpp
NetworkMessageStream.cpp