Indri: Indri::DocumentVectorVector Class Reference
Indri::DocumentVectorVector Class Reference
Classes
class DocumentVectorVectorEnumerator
Public Member Functions
virtual void Dispose ()
DocumentVectorVector (System.Collections.ICollection c)
void CopyTo (DocumentVector[] array)
void CopyTo (DocumentVector[] array, int arrayIndex)
void CopyTo (int index, DocumentVector[] array, int arrayIndex, int count)
DocumentVectorVectorEnumerator GetEnumerator ()
void Clear ()
void Add (DocumentVector x)
DocumentVectorVector ()
DocumentVectorVector (DocumentVectorVector other)
DocumentVectorVector (int capacity)
void AddRange (DocumentVectorVector values)
DocumentVectorVector GetRange (int index, int count)
void Insert (int index, DocumentVector x)
void InsertRange (int index, DocumentVectorVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, DocumentVectorVector values)
bool Contains (DocumentVector value)
int IndexOf (DocumentVector value)
int LastIndexOf (DocumentVector value)
bool Remove (DocumentVector value)
Static Public Member Functions
static DocumentVectorVector Repeat (DocumentVector value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
DocumentVector this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal DocumentVectorVector (IntPtr cPtr, bool cMemoryOwn)
~DocumentVectorVector ()
System.Collections.Generic.IEnumerator
< DocumentVector >
System.Collections.Generic.IEnumerable
< DocumentVector >. GetEnumerator ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
DocumentVector getitemcopy (int index)
DocumentVector getitem (int index)
void setitem (int index, DocumentVector val)
Static Private Member Functions
static internal HandleRef getCPtr (DocumentVectorVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::DocumentVectorVector::DocumentVectorVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::DocumentVectorVector::~DocumentVectorVector () [inline, private]
References Dispose().
Indri::DocumentVectorVector::DocumentVectorVector (System.Collections.ICollection c) [inline]
References Add().
Indri::DocumentVectorVector::DocumentVectorVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::DocumentVectorVector::DocumentVectorVector (DocumentVectorVector other) [inline]
Indri::DocumentVectorVector::DocumentVectorVector (int capacity) [inline]
Member Function Documentation
void Indri::DocumentVectorVector::Add (DocumentVector x) [inline]
References swigCPtr.
Referenced by DocumentVectorVector().
void Indri::DocumentVectorVector::AddRange (DocumentVectorVector values) [inline]
References swigCPtr.
uint Indri::DocumentVectorVector::capacity () [inline, private]
References swigCPtr.
void Indri::DocumentVectorVector::Clear () [inline]
References swigCPtr.
bool Indri::DocumentVectorVector::Contains (DocumentVector value) [inline]
References swigCPtr.
void Indri::DocumentVectorVector::CopyTo (int index, DocumentVector[] array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::DocumentVectorVector::CopyTo (DocumentVector[] array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::DocumentVectorVector::CopyTo (DocumentVector[] array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::DocumentVectorVector::Dispose () [inline, virtual]
References Count, getitem(), swigCMemOwn, and swigCPtr.
Referenced by ~DocumentVectorVector().
static internal HandleRef Indri::DocumentVectorVector::getCPtr (DocumentVectorVector obj) [inline, static, private]
References swigCPtr.
DocumentVectorVectorEnumerator Indri::DocumentVectorVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::DocumentVectorVector::GetEnumerator () [inline, private]
System.Collections.Generic.IEnumerator<DocumentVector> System.Collections.Generic.IEnumerable<DocumentVector>. Indri::DocumentVectorVector::GetEnumerator () [inline, private]
DocumentVector Indri::DocumentVectorVector::getitem (int index) [inline, private]
References swigCPtr.
Referenced by Dispose().
DocumentVector Indri::DocumentVectorVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
DocumentVectorVector Indri::DocumentVectorVector::GetRange (int index, int count) [inline]
References DocumentVectorVector(), and swigCPtr.
int Indri::DocumentVectorVector::IndexOf (DocumentVector value) [inline]
References swigCPtr.
void Indri::DocumentVectorVector::Insert (int index, DocumentVector x) [inline]
References swigCPtr.
void Indri::DocumentVectorVector::InsertRange (int index, DocumentVectorVector values) [inline]
References swigCPtr.
int Indri::DocumentVectorVector::LastIndexOf (DocumentVector value) [inline]
References swigCPtr.
bool Indri::DocumentVectorVector::Remove (DocumentVector value) [inline]
References swigCPtr.
void Indri::DocumentVectorVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::DocumentVectorVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static DocumentVectorVector Indri::DocumentVectorVector::Repeat (DocumentVector value, int count) [inline, static]
References DocumentVectorVector().
void Indri::DocumentVectorVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::DocumentVectorVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::DocumentVectorVector::Reverse () [inline]
References swigCPtr.
void Indri::DocumentVectorVector::setitem (int index, DocumentVector val) [inline, private]
References swigCPtr.
void Indri::DocumentVectorVector::SetRange (int index, DocumentVectorVector values) [inline]
References swigCPtr.
uint Indri::DocumentVectorVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::DocumentVectorVector::DocumentVectorVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::DocumentVectorVector::swigCMemOwn [protected]
Referenced by Dispose(), and DocumentVectorVector().
HandleRef Indri::DocumentVectorVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Contains(), Dispose(), DocumentVectorVector(), getCPtr(), getitem(), getitemcopy(), GetRange(), IndexOf(), Insert(), InsertRange(), LastIndexOf(), Remove(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::DocumentVectorVector::Capacity [get, set]
int Indri::DocumentVectorVector::Count [get]
Referenced by CopyTo(), Dispose(), Indri::DocumentVectorVector::DocumentVectorVectorEnumerator::DocumentVectorVectorEnumerator(), Indri::DocumentVectorVector::DocumentVectorVectorEnumerator::MoveNext(), and Indri::DocumentVectorVector::DocumentVectorVectorEnumerator::Reset().
bool Indri::DocumentVectorVector::IsFixedSize [get]
bool Indri::DocumentVectorVector::IsReadOnly [get]
bool Indri::DocumentVectorVector::IsSynchronized [get]
DocumentVector Indri::DocumentVectorVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
DocumentVectorVector.cs