Indri: indri::infnet::ExtentOrNode Class Reference
indri::infnet::ExtentOrNode Class Reference
#include <ExtentOrNode.hpp>
Public Member Functions
ExtentOrNode (const std::string &name, std::vector< ListIteratorNode * > &children)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
void indexChanged (indri::index::Index &index)
lemur::api::DOCID_T nextCandidateDocument ()
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
std::vector< ListIteratorNode * > _children
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::string _name
Constructor & Destructor Documentation
indri::infnet::ExtentOrNode::ExtentOrNode (const std::string & name, std::vector< ListIteratorNode * > & children)
Member Function Documentation
void indri::infnet::ExtentOrNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, indri::infnet::Annotator::addMatches(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::contains(), and indri::utility::greedy_vector< _Type, _Count >::end().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::ExtentOrNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
Referenced by prepare().
const std::string & indri::infnet::ExtentOrNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::ExtentOrNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, indri::index::Extent::begin, and indri::index::Extent::end.
lemur::api::DOCID_T indri::infnet::ExtentOrNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
void indri::infnet::ExtentOrNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, indri::utility::greedy_vector< _Type, _Count >::append(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, extents(), and indri::infnet::ListIteratorNode::initpointer().
Member Data Documentation
std::vector<ListIteratorNode*> indri::infnet::ExtentOrNode::_children [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::ExtentOrNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
std::string indri::infnet::ExtentOrNode::_name [private]
Referenced by getName().
The documentation for this class was generated from the following files:
ExtentOrNode.hpp
ExtentOrNode.cpp