Indri: indri::thread::Mutex Class Reference
indri::thread::Mutex Class Reference
#include <Mutex.hpp>
Public Member Functions
Mutex ()
~Mutex ()
void lock ()
bool tryLock ()
void unlock ()
Private Member Functions
Mutex (Mutex &m)
Private Attributes
pthread_mutex_t _mutex
Friends
class ConditionVariable
Constructor & Destructor Documentation
indri::thread::Mutex::Mutex (Mutex & m) [inline, explicit, private]
indri::thread::Mutex::Mutex () [inline]
References _mutex.
indri::thread::Mutex::~Mutex () [inline]
References _mutex.
Member Function Documentation
void indri::thread::Mutex::lock () [inline, virtual]
Implements indri::thread::Lockable.
References _mutex.
Referenced by indri::index::DiskKeyfileVocabularyIterator::_acquire(), indri::thread::ReadersWritersLock::lockRead(), indri::thread::ReadersWritersLock::lockWrite(), main(), indri::thread::ScopedMonitor::ScopedMonitor(), indri::thread::ReadersWritersLock::unlockRead(), indri::thread::ReadersWritersLock::unlockWrite(), and indri::thread::ConditionVariable::wait().
bool indri::thread::Mutex::tryLock () [inline]
References _mutex.
void indri::thread::Mutex::unlock () [inline, virtual]
Implements indri::thread::Lockable.
References _mutex.
Referenced by indri::index::DiskKeyfileVocabularyIterator::_release(), indri::thread::ReadersWritersLock::lockRead(), indri::thread::ReadersWritersLock::lockWrite(), main(), indri::thread::ReadersWritersLock::unlockRead(), indri::thread::ReadersWritersLock::unlockWrite(), and indri::thread::ScopedMonitor::~ScopedMonitor().
Friends And Related Function Documentation
friend class ConditionVariable [friend]
Member Data Documentation
pthread_mutex_t indri::thread::Mutex::_mutex [private]
Referenced by lock(), Mutex(), tryLock(), unlock(), indri::thread::ConditionVariable::wait(), and ~Mutex().
The documentation for this class was generated from the following file:
Mutex.hpp