Indri: Indri::TermExtentVector Class Reference
Indri::TermExtentVector Class Reference
Classes
class TermExtentVectorEnumerator
Public Member Functions
virtual void Dispose ()
TermExtentVector (System.Collections.ICollection c)
void CopyTo (System.Array array)
void CopyTo (System.Array array, int arrayIndex)
void CopyTo (int index, System.Array array, int arrayIndex, int count)
TermExtentVectorEnumerator GetEnumerator ()
void Clear ()
void Add (TermExtent value)
TermExtentVector ()
TermExtentVector (int capacity)
void AddRange (TermExtentVector values)
TermExtentVector GetRange (int index, int count)
void Insert (int index, TermExtent value)
void InsertRange (int index, TermExtentVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, TermExtentVector values)
Static Public Member Functions
static TermExtentVector Repeat (TermExtent value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
TermExtent this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal TermExtentVector (IntPtr cPtr, bool cMemoryOwn)
~TermExtentVector ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
TermExtent getitemcopy (int index)
TermExtent getitem (int index)
void setitem (int index, TermExtent value)
Static Private Member Functions
static internal HandleRef getCPtr (TermExtentVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::TermExtentVector::TermExtentVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::TermExtentVector::~TermExtentVector () [inline, private]
References Dispose().
Indri::TermExtentVector::TermExtentVector (System.Collections.ICollection c) [inline]
References Add().
Indri::TermExtentVector::TermExtentVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::TermExtentVector::TermExtentVector (int capacity) [inline]
Member Function Documentation
void Indri::TermExtentVector::Add (TermExtent value) [inline]
References swigCPtr.
Referenced by TermExtentVector().
void Indri::TermExtentVector::AddRange (TermExtentVector values) [inline]
References swigCPtr.
uint Indri::TermExtentVector::capacity () [inline, private]
References swigCPtr.
void Indri::TermExtentVector::Clear () [inline]
References swigCPtr.
void Indri::TermExtentVector::CopyTo (int index, System.Array array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::TermExtentVector::CopyTo (System.Array array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::TermExtentVector::CopyTo (System.Array array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::TermExtentVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~TermExtentVector().
static internal HandleRef Indri::TermExtentVector::getCPtr (TermExtentVector obj) [inline, static, private]
References swigCPtr.
TermExtentVectorEnumerator Indri::TermExtentVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::TermExtentVector::GetEnumerator () [inline, private]
TermExtent Indri::TermExtentVector::getitem (int index) [inline, private]
References swigCPtr.
TermExtent Indri::TermExtentVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
TermExtentVector Indri::TermExtentVector::GetRange (int index, int count) [inline]
References swigCPtr, and TermExtentVector().
void Indri::TermExtentVector::Insert (int index, TermExtent value) [inline]
References swigCPtr.
void Indri::TermExtentVector::InsertRange (int index, TermExtentVector values) [inline]
References swigCPtr.
void Indri::TermExtentVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::TermExtentVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static TermExtentVector Indri::TermExtentVector::Repeat (TermExtent value, int count) [inline, static]
References TermExtentVector().
void Indri::TermExtentVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::TermExtentVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::TermExtentVector::Reverse () [inline]
References swigCPtr.
void Indri::TermExtentVector::setitem (int index, TermExtent value) [inline, private]
References swigCPtr.
void Indri::TermExtentVector::SetRange (int index, TermExtentVector values) [inline]
References swigCPtr.
uint Indri::TermExtentVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::TermExtentVector::TermExtentVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::TermExtentVector::swigCMemOwn [protected]
Referenced by Dispose(), and TermExtentVector().
HandleRef Indri::TermExtentVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), size(), and TermExtentVector().
Property Documentation
int Indri::TermExtentVector::Capacity [get, set]
int Indri::TermExtentVector::Count [get]
Referenced by CopyTo(), Indri::TermExtentVector::TermExtentVectorEnumerator::MoveNext(), Indri::TermExtentVector::TermExtentVectorEnumerator::Reset(), and Indri::TermExtentVector::TermExtentVectorEnumerator::TermExtentVectorEnumerator().
bool Indri::TermExtentVector::IsFixedSize [get]
bool Indri::TermExtentVector::IsReadOnly [get]
bool Indri::TermExtentVector::IsSynchronized [get]
TermExtent Indri::TermExtentVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
TermExtentVector.cs