Indri: NexiLexer Class Reference
NexiLexer Class Reference
#include <NexiLexer.hpp>
Public Member Functions
void init ()
void setNumbers (bool f)
bool getCaseSensitiveLiterals () const
NexiLexer (ANTLR_USE_NAMESPACE(std) istream &in)
NexiLexer (ANTLR_USE_NAMESPACE(antlr) InputBuffer &ib)
NexiLexer (const ANTLR_USE_NAMESPACE(antlr) LexerSharedInputState &state)
ANTLR_USE_NAMESPACE (antlr) RefToken nextToken()
void mSTAR (bool _createToken)
void mO_PAREN (bool _createToken)
void mC_PAREN (bool _createToken)
void mO_SQUARE (bool _createToken)
void mC_SQUARE (bool _createToken)
void mDBL_QUOTE (bool _createToken)
void mQUOTE (bool _createToken)
void mDOT (bool _createToken)
void mCOMMA (bool _createToken)
void mSLASH (bool _createToken)
void mMINUS (bool _createToken)
void mPLUS (bool _createToken)
void mTERM (bool _createToken)
void mOPERATORS (bool _createToken)
void mLESS (bool _createToken)
void mGREATER (bool _createToken)
void mLESSEQ (bool _createToken)
void mGREATEREQ (bool _createToken)
void mEQUALS (bool _createToken)
void mJUNK (bool _createToken)
Protected Member Functions
void mTAB (bool _createToken)
void mCR (bool _createToken)
void mLF (bool _createToken)
void mSPACE (bool _createToken)
void mHIGH_CHAR (bool _createToken)
void mDIGIT (bool _createToken)
void mASCII_LETTER (bool _createToken)
void mSAFE_LETTER (bool _createToken)
void mSAFE_CHAR (bool _createToken)
void mTEXT_TERM (bool _createToken)
void mNUMBER (bool _createToken)
void mFLOAT (bool _createToken)
Private Member Functions
void initLiterals ()
Static Private Member Functions
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_0
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_1
static const ANTLR_USE_NAMESPACE (antlr) BitSet _tokenSet_2
Private Attributes
bool _numbers
Static Private Attributes
static const unsigned long _tokenSet_0_data_ [] = { 0UL, 67043328UL, 134217726UL, 134217726UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL }
static const unsigned long _tokenSet_1_data_ []
static const unsigned long _tokenSet_2_data_ []
Constructor & Destructor Documentation
NexiLexer::NexiLexer (ANTLR_USE_NAMESPACE(std) istream & in)
References initLiterals().
NexiLexer::NexiLexer (ANTLR_USE_NAMESPACE(antlr) InputBuffer & ib)
References initLiterals().
NexiLexer::NexiLexer (const ANTLR_USE_NAMESPACE(antlr) LexerSharedInputState & state)
References initLiterals().
Member Function Documentation
static const NexiLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const NexiLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
static const NexiLexer::ANTLR_USE_NAMESPACE (antlr) [static, private]
NexiLexer::ANTLR_USE_NAMESPACE (antlr)
Referenced by mASCII_LETTER(), mC_PAREN(), mC_SQUARE(), mCOMMA(), mCR(), mDBL_QUOTE(), mDIGIT(), mDOT(), mEQUALS(), mFLOAT(), mGREATER(), mGREATEREQ(), mHIGH_CHAR(), mJUNK(), mLESS(), mLESSEQ(), mLF(), mMINUS(), mNUMBER(), mO_PAREN(), mO_SQUARE(), mOPERATORS(), mPLUS(), mQUOTE(), mSAFE_CHAR(), mSAFE_LETTER(), mSLASH(), mSPACE(), mSTAR(), mTAB(), mTERM(), and mTEXT_TERM().
bool NexiLexer::getCaseSensitiveLiterals () const [inline]
void NexiLexer::init () [inline]
void NexiLexer::initLiterals () [private]
Referenced by NexiLexer().
void NexiLexer::mASCII_LETTER (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and ASCII_LETTER.
Referenced by mTEXT_TERM().
void NexiLexer::mC_PAREN (bool _createToken)
References ANTLR_USE_NAMESPACE(), and C_PAREN.
void NexiLexer::mC_SQUARE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and C_SQUARE.
void NexiLexer::mCOMMA (bool _createToken)
References ANTLR_USE_NAMESPACE(), and COMMA.
void NexiLexer::mCR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and CR.
Referenced by mJUNK().
void NexiLexer::mDBL_QUOTE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and DBL_QUOTE.
void NexiLexer::mDIGIT (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and DIGIT.
Referenced by mTERM(), and mTEXT_TERM().
void NexiLexer::mDOT (bool _createToken)
References ANTLR_USE_NAMESPACE(), and DOT.
Referenced by mFLOAT(), and mTERM().
void NexiLexer::mEQUALS (bool _createToken)
References ANTLR_USE_NAMESPACE(), and EQUALS.
void NexiLexer::mFLOAT (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), FLOAT, and mDOT().
Referenced by mTERM().
void NexiLexer::mGREATER (bool _createToken)
References ANTLR_USE_NAMESPACE(), and GREATER.
void NexiLexer::mGREATEREQ (bool _createToken)
References ANTLR_USE_NAMESPACE(), and GREATEREQ.
void NexiLexer::mHIGH_CHAR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and HIGH_CHAR.
Referenced by mTEXT_TERM().
void NexiLexer::mJUNK (bool _createToken)
References ANTLR_USE_NAMESPACE(), JUNK, mCR(), mLF(), mSPACE(), and mTAB().
void NexiLexer::mLESS (bool _createToken)
References ANTLR_USE_NAMESPACE(), and LESS.
void NexiLexer::mLESSEQ (bool _createToken)
References ANTLR_USE_NAMESPACE(), and LESSEQ.
void NexiLexer::mLF (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and LF.
Referenced by mJUNK().
void NexiLexer::mMINUS (bool _createToken)
References ANTLR_USE_NAMESPACE(), and MINUS.
void NexiLexer::mNUMBER (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and NUMBER.
Referenced by mTERM().
void NexiLexer::mO_PAREN (bool _createToken)
References ANTLR_USE_NAMESPACE(), and O_PAREN.
void NexiLexer::mO_SQUARE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and O_SQUARE.
void NexiLexer::mOPERATORS (bool _createToken)
References ANTLR_USE_NAMESPACE(), mTERM(), and OPERATORS.
void NexiLexer::mPLUS (bool _createToken)
References ANTLR_USE_NAMESPACE(), and PLUS.
void NexiLexer::mQUOTE (bool _createToken)
References ANTLR_USE_NAMESPACE(), and QUOTE.
void NexiLexer::mSAFE_CHAR (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and SAFE_CHAR.
Referenced by mTEXT_TERM().
void NexiLexer::mSAFE_LETTER (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and SAFE_LETTER.
Referenced by mTERM().
void NexiLexer::mSLASH (bool _createToken)
References ANTLR_USE_NAMESPACE(), and SLASH.
void NexiLexer::mSPACE (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and SPACE.
Referenced by mJUNK().
void NexiLexer::mSTAR (bool _createToken)
References ANTLR_USE_NAMESPACE(), and STAR.
void NexiLexer::mTAB (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), and TAB.
Referenced by mJUNK().
void NexiLexer::mTERM (bool _createToken)
References ANTLR_USE_NAMESPACE(), FLOAT, mDIGIT(), mDOT(), mFLOAT(), mNUMBER(), mSAFE_LETTER(), mTEXT_TERM(), NUMBER, and TERM.
Referenced by mOPERATORS().
void NexiLexer::mTEXT_TERM (bool _createToken) [protected]
References ANTLR_USE_NAMESPACE(), mASCII_LETTER(), mDIGIT(), mHIGH_CHAR(), mSAFE_CHAR(), and TEXT_TERM.
Referenced by mTERM().
void NexiLexer::setNumbers (bool f) [inline]
Member Data Documentation
bool NexiLexer::_numbers [private]
const unsigned long NexiLexer::_tokenSet_0_data_ = { 0UL, 67043328UL, 134217726UL, 134217726UL, 4294967295UL, 4294967295UL, 4294967295UL, 4294967295UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL, 0UL } [static, private]
const unsigned long NexiLexer::_tokenSet_1_data_[] [static, private]
const unsigned long NexiLexer::_tokenSet_2_data_[] [static, private]
The documentation for this class was generated from the following files:
NexiLexer.hpp
NexiLexer.cpp