Indri: StatusMonitor Class Reference
StatusMonitor Class Reference
Private Member Functions
void operator() (int code, const std::string &documentFile, const std::string &error, int documentsParsed, int documentsSeen)
Member Function Documentation
void StatusMonitor::operator() (int code, const std::string & documentFile, const std::string & error, int documentsParsed, int documentsSeen) [inline, private, virtual]
Reimplemented from indri::api::IndexStatus.
References buildindex_flush_status(), buildindex_print_event(), buildindex_print_status(), indri::api::IndexStatus::DocumentCount, indri::api::IndexStatus::FileClose, indri::api::IndexStatus::FileError, indri::api::IndexStatus::FileOpen, and indri::api::IndexStatus::FileSkip.
The documentation for this class was generated from the following file:
IndriBuildIndex.cpp