Indri: indri::parse::HTMLParser Class Reference
indri::parse::HTMLParser Class Reference
#include <HTMLParser.hpp>
Public Member Functions
HTMLParser ()
~HTMLParser ()
Protected Member Functions
virtual void initialize (TokenizedDocument *tokenized, indri::api::ParsedDocument *parsed)
virtual void cleanup (TokenizedDocument *tokenized, indri::api::ParsedDocument *parsed)
virtual void handleTag (TagEvent *te)
void prepURL (char *s)
bool normalizeURL (char *s)
Protected Attributes
char url [MAX_URL_LENGTH]
char base_url [MAX_URL_LENGTH]
tag_properties * _relativeUrlTag
tag_properties * _absoluteUrlTag
tag_properties * _anchorTag
indri::utility::Buffer _urlBuffer
Constructor & Destructor Documentation
indri::parse::HTMLParser::HTMLParser () [inline]
indri::parse::HTMLParser::~HTMLParser () [inline]
Member Function Documentation
void indri::parse::HTMLParser::cleanup (TokenizedDocument * tokenized, indri::api::ParsedDocument * parsed) [protected, virtual]
Reimplemented from indri::parse::TaggedTextParser.
void indri::parse::HTMLParser::handleTag (TagEvent * te) [protected, virtual]
Reimplemented from indri::parse::TaggedTextParser.
References _absoluteUrlTag, _anchorTag, indri::parse::TaggedTextParser::_document, indri::parse::TaggedTextParser::_exclude, indri::parse::TaggedTextParser::_include, indri::parse::TaggedTextParser::_p_conflater, _relativeUrlTag, _urlBuffer, indri::parse::TaggedTextParser::addTag(), indri::parse::TagEvent::attributes, base_url, indri::parse::TermExtent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::Conflater::conflate(), indri::parse::TermExtent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::parse::TaggedTextParser::endTag(), indri::parse::TaggedTextParser::tag_properties::exclude, MAX_URL_LENGTH, indri::parse::TaggedTextParser::tag_properties::name, indri::parse::TagEvent::name, normalizeURL(), indri::parse::TagEvent::pos, indri::api::ParsedDocument::positions, prepURL(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::terms, indri::parse::TaggedTextParser::tokens_excluded, and indri::utility::Buffer::write().
void indri::parse::HTMLParser::initialize (TokenizedDocument * tokenized, indri::api::ParsedDocument * parsed) [protected, virtual]
Reimplemented from indri::parse::TaggedTextParser.
References _absoluteUrlTag, _anchorTag, indri::parse::TaggedTextParser::_findTag(), _relativeUrlTag, _urlBuffer, base_url, indri::utility::Buffer::clear(), indri::utility::Buffer::grow(), indri::parse::MetadataPair::key, indri::api::ParsedDocument::metadata, indri::parse::TokenizedDocument::metadata, normalizeURL(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), url, indri::parse::MetadataPair::value, and indri::parse::MetadataPair::valueLength.
bool indri::parse::HTMLParser::normalizeURL (char * s) [protected]
References base_url, MAX_URL_LENGTH, indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by handleTag(), and initialize().
void indri::parse::HTMLParser::prepURL (char * s) [protected]
Referenced by handleTag().
Member Data Documentation
tag_properties* indri::parse::HTMLParser::_absoluteUrlTag [protected]
Referenced by handleTag(), and initialize().
tag_properties* indri::parse::HTMLParser::_anchorTag [protected]
Referenced by handleTag(), and initialize().
tag_properties* indri::parse::HTMLParser::_relativeUrlTag [protected]
Referenced by handleTag(), and initialize().
indri::utility::Buffer indri::parse::HTMLParser::_urlBuffer [protected]
Referenced by handleTag(), and initialize().
char indri::parse::HTMLParser::base_url[MAX_URL_LENGTH] [protected]
Referenced by handleTag(), initialize(), and normalizeURL().
char indri::parse::HTMLParser::url[MAX_URL_LENGTH] [protected]
Referenced by initialize().
The documentation for this class was generated from the following files:
HTMLParser.hpp
HTMLParser.cpp