Indri: indri::file::FileTreeIterator Class Reference
indri::file::FileTreeIterator Class Reference
#include <FileTreeIterator.hpp>
Public Member Functions
FileTreeIterator ()
FileTreeIterator (const std::string &path)
~FileTreeIterator ()
void operator++ (int)
Moves to the next file within the directory tree.
void operator++ ()
Moves to the next file within the directory tree.
bool operator== (const FileTreeIterator &other) const
bool operator!= (const FileTreeIterator &other) const
const std::string & operator* ()
Returns the full path to a file within the directory tree.
Static Public Member Functions
static const FileTreeIterator & end ()
Private Member Functions
void _nextCandidate ()
void _next ()
Private Attributes
std::stack< DirectoryIterator * > _stack
std::string _current
Static Private Attributes
static FileTreeIterator _end
Detailed Description
Provides iteration over the files in a directory tree.
Constructor & Destructor Documentation
indri::file::FileTreeIterator::FileTreeIterator ()
indri::file::FileTreeIterator::FileTreeIterator (const std::string & path)
References _nextCandidate(), _stack, indri::file::DirectoryIterator::end(), and indri::file::Path::isDirectory().
indri::file::FileTreeIterator::~FileTreeIterator ()
References _stack.
Member Function Documentation
void indri::file::FileTreeIterator::_next () [private]
References _nextCandidate(), _stack, indri::file::DirectoryIterator::end(), indri::file::Path::isDirectory(), and indri::file::Path::isFile().
Referenced by operator++().
void indri::file::FileTreeIterator::_nextCandidate () [private]
References _stack, and indri::file::DirectoryIterator::end().
Referenced by _next(), and FileTreeIterator().
const indri::file::FileTreeIterator & indri::file::FileTreeIterator::end () [static]
Placeholder object that indicates a finished iteration. Use this with operator != to tell when iteration is finished.
References _end.
Referenced by indri::parse::PageRank::_computeColLen(), indri::parse::PageRank::_computeOutDegrees(), indri::parse::PageRank::_doPageRankIter(), collect_harvest_paths(), combineSortedFiles(), harvest_anchor_text(), indri::parse::Combiner::hashToBuckets(), indri::parse::PageRank::indexPageRank(), main(), and indri::parse::Combiner::sortCorpusFiles().
bool indri::file::FileTreeIterator::operator!= (const FileTreeIterator & other) const
Used only for comparison with FileTreeIterator::end. If true, the iteration is complete.
References operator==().
const std::string & indri::file::FileTreeIterator::operator* ()
Returns the full path to a file within the directory tree.
References _stack.
void indri::file::FileTreeIterator::operator++ ()
Moves to the next file within the directory tree.
References _next().
void indri::file::FileTreeIterator::operator++ (int)
Moves to the next file within the directory tree.
References _next().
bool indri::file::FileTreeIterator::operator== (const FileTreeIterator & other) const
Used only for comparison with FileTreeIterator::end. If false, the iteration is complete.
References _end, and _stack.
Referenced by operator!=().
Member Data Documentation
std::string indri::file::FileTreeIterator::_current [private]
indri::file::FileTreeIterator indri::file::FileTreeIterator::_end [static, private]
Referenced by end(), and operator==().
std::stack<DirectoryIterator*> indri::file::FileTreeIterator::_stack [private]
Referenced by _next(), _nextCandidate(), FileTreeIterator(), operator*(), operator==(), and ~FileTreeIterator().
The documentation for this class was generated from the following files:
FileTreeIterator.hpp
FileTreeIterator.cpp