Indri: indri::server::NetworkServerProxyResponse Class Reference
indri::server::NetworkServerProxyResponse Class Reference
Public Member Functions
NetworkServerProxyResponse (indri::net::NetworkMessageStream *stream)
~NetworkServerProxyResponse ()
indri::infnet::InferenceNetwork::MAllResults & getResults ()
Private Attributes
indri::net::QueryResponseUnpacker _unpacker
indri::net::NetworkMessageStream * _stream
Constructor & Destructor Documentation
indri::server::NetworkServerProxyResponse::NetworkServerProxyResponse (indri::net::NetworkMessageStream * stream) [inline]
indri::server::NetworkServerProxyResponse::~NetworkServerProxyResponse () [inline]
References _stream, indri::net::NetworkMessageStream::mutex(), and indri::thread::Lockable::unlock().
Member Function Documentation
indri::infnet::InferenceNetwork::MAllResults& indri::server::NetworkServerProxyResponse::getResults () [inline, virtual]
Implements indri::server::QueryServerResponse.
References _unpacker, and indri::net::QueryResponseUnpacker::getResults().
Member Data Documentation
indri::net::NetworkMessageStream* indri::server::NetworkServerProxyResponse::_stream [private]
Referenced by ~NetworkServerProxyResponse().
indri::net::QueryResponseUnpacker indri::server::NetworkServerProxyResponse::_unpacker [private]
Referenced by getResults().
The documentation for this class was generated from the following file:
NetworkServerProxy.cpp