Indri: Indri::FieldVector Class Reference
Indri::FieldVector Class Reference
Classes
class FieldVectorEnumerator
Public Member Functions
virtual void Dispose ()
FieldVector (System.Collections.ICollection c)
void CopyTo (Field[] array)
void CopyTo (Field[] array, int arrayIndex)
void CopyTo (int index, Field[] array, int arrayIndex, int count)
FieldVectorEnumerator GetEnumerator ()
void Clear ()
void Add (Field x)
FieldVector ()
FieldVector (FieldVector other)
FieldVector (int capacity)
void AddRange (FieldVector values)
FieldVector GetRange (int index, int count)
void Insert (int index, Field x)
void InsertRange (int index, FieldVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, FieldVector values)
Static Public Member Functions
static FieldVector Repeat (Field value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
Field this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal FieldVector (IntPtr cPtr, bool cMemoryOwn)
~FieldVector ()
System.Collections.Generic.IEnumerator
< Field >
System.Collections.Generic.IEnumerable
< Field >. GetEnumerator ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
Field getitemcopy (int index)
Field getitem (int index)
void setitem (int index, Field val)
Static Private Member Functions
static internal HandleRef getCPtr (FieldVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::FieldVector::FieldVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::FieldVector::~FieldVector () [inline, private]
References Dispose().
Indri::FieldVector::FieldVector (System.Collections.ICollection c) [inline]
References Add().
Indri::FieldVector::FieldVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::FieldVector::FieldVector (FieldVector other) [inline]
Indri::FieldVector::FieldVector (int capacity) [inline]
Member Function Documentation
void Indri::FieldVector::Add (Field x) [inline]
References swigCPtr.
Referenced by FieldVector().
void Indri::FieldVector::AddRange (FieldVector values) [inline]
References swigCPtr.
uint Indri::FieldVector::capacity () [inline, private]
References swigCPtr.
void Indri::FieldVector::Clear () [inline]
References swigCPtr.
void Indri::FieldVector::CopyTo (int index, Field[] array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::FieldVector::CopyTo (Field[] array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::FieldVector::CopyTo (Field[] array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::FieldVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~FieldVector().
static internal HandleRef Indri::FieldVector::getCPtr (FieldVector obj) [inline, static, private]
References swigCPtr.
FieldVectorEnumerator Indri::FieldVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::FieldVector::GetEnumerator () [inline, private]
System.Collections.Generic.IEnumerator<Field> System.Collections.Generic.IEnumerable<Field>. Indri::FieldVector::GetEnumerator () [inline, private]
Field Indri::FieldVector::getitem (int index) [inline, private]
References swigCPtr.
Field Indri::FieldVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
FieldVector Indri::FieldVector::GetRange (int index, int count) [inline]
References FieldVector(), and swigCPtr.
void Indri::FieldVector::Insert (int index, Field x) [inline]
References swigCPtr.
void Indri::FieldVector::InsertRange (int index, FieldVector values) [inline]
References swigCPtr.
void Indri::FieldVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::FieldVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static FieldVector Indri::FieldVector::Repeat (Field value, int count) [inline, static]
References FieldVector().
void Indri::FieldVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::FieldVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::FieldVector::Reverse () [inline]
References swigCPtr.
void Indri::FieldVector::setitem (int index, Field val) [inline, private]
References swigCPtr.
void Indri::FieldVector::SetRange (int index, FieldVector values) [inline]
References swigCPtr.
uint Indri::FieldVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::FieldVector::FieldVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::FieldVector::swigCMemOwn [protected]
Referenced by Dispose(), and FieldVector().
HandleRef Indri::FieldVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Dispose(), FieldVector(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::FieldVector::Capacity [get, set]
int Indri::FieldVector::Count [get]
Referenced by CopyTo(), Indri::FieldVector::FieldVectorEnumerator::FieldVectorEnumerator(), Indri::FieldVector::FieldVectorEnumerator::MoveNext(), and Indri::FieldVector::FieldVectorEnumerator::Reset().
bool Indri::FieldVector::IsFixedSize [get]
bool Indri::FieldVector::IsReadOnly [get]
bool Indri::FieldVector::IsSynchronized [get]
Field Indri::FieldVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
FieldVector.cs