Indri: indri::infnet::OrderedWindowNode Class Reference
indri::infnet::OrderedWindowNode Class Reference
#include <OrderedWindowNode.hpp>
Classes
struct extents_pointer
Public Member Functions
OrderedWindowNode (const std::string &name, const std::vector< ListIteratorNode * > &children)
OrderedWindowNode (const std::string &name, const std::vector< ListIteratorNode * > &children, int windowSize)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
const
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Member Functions
bool findNextPossibleOccurrence (int i, bool &fail)
Private Attributes
int _windowSize
std::vector< ListIteratorNode * > _children
indri::utility::greedy_vector
< indri::index::Extent > _extents
std::vector< extents_pointer > _pointers
std::string _name
Constructor & Destructor Documentation
indri::infnet::OrderedWindowNode::OrderedWindowNode (const std::string & name, const std::vector< ListIteratorNode * > & children)
indri::infnet::OrderedWindowNode::OrderedWindowNode (const std::string & name, const std::vector< ListIteratorNode * > & children, int windowSize)
Member Function Documentation
void indri::infnet::OrderedWindowNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, indri::infnet::Annotator::addMatches(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::contains(), and indri::utility::greedy_vector< _Type, _Count >::end().
const indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::OrderedWindowNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
bool indri::infnet::OrderedWindowNode::findNextPossibleOccurrence (int i, bool & fail) [private]
References _pointers.
Referenced by prepare().
const std::string & indri::infnet::OrderedWindowNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::OrderedWindowNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
References indri::infnet::ListIteratorNode::_lastExtent, indri::index::Extent::begin, and indri::index::Extent::end.
lemur::api::DOCID_T indri::infnet::OrderedWindowNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
void indri::infnet::OrderedWindowNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _children, _extents, indri::infnet::ListIteratorNode::_lastExtent, _pointers, _windowSize, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::Extent::begin, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::Extent::end, findNextPossibleOccurrence(), indri::infnet::ListIteratorNode::initpointer(), and indri::utility::greedy_vector< _Type, _Count >::push_back().
Member Data Documentation
std::vector<ListIteratorNode*> indri::infnet::OrderedWindowNode::_children [private]
Referenced by annotate(), nextCandidateDocument(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::OrderedWindowNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
std::string indri::infnet::OrderedWindowNode::_name [private]
Referenced by getName().
std::vector<extents_pointer> indri::infnet::OrderedWindowNode::_pointers [private]
Referenced by findNextPossibleOccurrence(), and prepare().
int indri::infnet::OrderedWindowNode::_windowSize [private]
Referenced by prepare().
The documentation for this class was generated from the following files:
OrderedWindowNode.hpp
OrderedWindowNode.cpp