Indri: indri::index::DocumentDataIterator Class Reference
indri::index::DocumentDataIterator Class Reference
#include <DocumentDataIterator.hpp>
Public Member Functions
virtual ~DocumentDataIterator ()
virtual void startIteration ()=0
virtual bool nextEntry ()=0
virtual const DocumentData * currentEntry ()=0
virtual bool finished ()=0
Constructor & Destructor Documentation
virtual indri::index::DocumentDataIterator::~DocumentDataIterator () [inline, virtual]
Member Function Documentation
virtual const DocumentData* indri::index::DocumentDataIterator::currentEntry () [pure virtual]
Implemented in indri::index::DiskDocumentDataIterator, and indri::index::MemoryDocumentDataIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists().
virtual bool indri::index::DocumentDataIterator::finished () [pure virtual]
Implemented in indri::index::DiskDocumentDataIterator, and indri::index::MemoryDocumentDataIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists().
virtual bool indri::index::DocumentDataIterator::nextEntry () [pure virtual]
Implemented in indri::index::DiskDocumentDataIterator, and indri::index::MemoryDocumentDataIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists().
virtual void indri::index::DocumentDataIterator::startIteration () [pure virtual]
Implemented in indri::index::DiskDocumentDataIterator, and indri::index::MemoryDocumentDataIterator.
Referenced by indri::index::IndexWriter::_writeDirectLists().
The documentation for this class was generated from the following file:
DocumentDataIterator.hpp