Indri: indri::parse::StemmerFactory Class Reference
indri::parse::StemmerFactory Class Reference
#include <StemmerFactory.hpp>
Static Public Member Functions
static Transformation * get (const std::string &stemmerName, indri::api::Parameters &stemmerParams)
The idea here is to admit as many names as possible (including possibly misspellings).
static std::string preferredName (const std::string &stemmerName)
Member Function Documentation
indri::parse::Transformation * indri::parse::StemmerFactory::get (const std::string & stemmerName, indri::api::Parameters & stemmerParams) [static]
The idea here is to admit as many names as possible (including possibly misspellings).
References preferredName(), STEMMER_ARABIC, STEMMER_KROVETZ, and STEMMER_PORTER.
Referenced by indri::collection::Repository::_buildChain().
std::string indri::parse::StemmerFactory::preferredName (const std::string & stemmerName) [static]
References STEMMER_ARABIC, STEMMER_KROVETZ, and STEMMER_PORTER.
Referenced by get().
The documentation for this class was generated from the following files:
StemmerFactory.hpp
StemmerFactory.cpp