Indri: indri::net::QueryResponsePacker Class Reference
indri::net::QueryResponsePacker Class Reference
#include <QueryResponsePacker.hpp>
Public Member Functions
QueryResponsePacker (indri::infnet::InferenceNetwork::MAllResults &results)
void write (NetworkMessageStream *stream)
Private Attributes
indri::infnet::InferenceNetwork::MAllResults & _results
Constructor & Destructor Documentation
indri::net::QueryResponsePacker::QueryResponsePacker (indri::infnet::InferenceNetwork::MAllResults & results) [inline]
Member Function Documentation
void indri::net::QueryResponsePacker::write (NetworkMessageStream * stream) [inline]
References _results, indri::api::ScoredExtentResult::begin, indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::api::ScoredExtentResult::number, indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, indri::net::NetworkMessageStream::reply(), indri::net::NetworkMessageStream::replyDone(), and indri::api::ScoredExtentResult::score.
Referenced by indri::net::NetworkServerStub::_handleQuery().
Member Data Documentation
indri::infnet::InferenceNetwork::MAllResults& indri::net::QueryResponsePacker::_results [private]
Referenced by write().
The documentation for this class was generated from the following file:
QueryResponsePacker.hpp