Indri: indri::parse::MboxDocumentIterator Class Reference
indri::parse::MboxDocumentIterator Class Reference
#include <MboxDocumentIterator.hpp>
Public Member Functions
void open (const std::string &filename)
UnparsedDocument * nextDocument ()
void close ()
Private Member Functions
void _copyMetadata (const char *headerLine, int ignoreBytes, const char *tagName)
Private Attributes
std::string _filename
UnparsedDocument _document
indri::utility::Buffer _buffer
indri::utility::Buffer _metaBuffer
std::ifstream _in
Member Function Documentation
void indri::parse::MboxDocumentIterator::_copyMetadata (const char * headerLine, int ignoreBytes, const char * tagName) [private]
References _buffer, _document, _metaBuffer, indri::utility::Buffer::front(), indri::parse::MetadataPair::key, indri::parse::UnparsedDocument::metadata, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
Referenced by nextDocument().
void indri::parse::MboxDocumentIterator::close () [virtual]
Implements indri::parse::DocumentIterator.
References _in.
indri::parse::UnparsedDocument * indri::parse::MboxDocumentIterator::nextDocument () [virtual]
Implements indri::parse::DocumentIterator.
References _buffer, _copyMetadata(), indri::parse::DocumentIterator::_docnostring, _document, _in, _metaBuffer, indri::parse::DocumentIterator::cleanDocno(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::Buffer::clear(), indri::parse::UnparsedDocument::content, indri::parse::UnparsedDocument::contentLength, indri::utility::Buffer::front(), indri::parse::MetadataPair::key, MBOX_EMPTY_LINE, MBOX_MAX_HEADER_LINE_LENGTH, indri::parse::UnparsedDocument::metadata, indri::utility::Buffer::position(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::parse::UnparsedDocument::text, indri::parse::UnparsedDocument::textLength, indri::utility::Buffer::unwrite(), indri::parse::MetadataPair::value, indri::parse::MetadataPair::valueLength, and indri::utility::Buffer::write().
void indri::parse::MboxDocumentIterator::open (const std::string & filename) [virtual]
Implements indri::parse::DocumentIterator.
References _filename, and _in.
Member Data Documentation
indri::utility::Buffer indri::parse::MboxDocumentIterator::_buffer [private]
Referenced by _copyMetadata(), and nextDocument().
UnparsedDocument indri::parse::MboxDocumentIterator::_document [private]
Referenced by _copyMetadata(), and nextDocument().
std::string indri::parse::MboxDocumentIterator::_filename [private]
Referenced by open().
std::ifstream indri::parse::MboxDocumentIterator::_in [private]
Referenced by close(), nextDocument(), and open().
indri::utility::Buffer indri::parse::MboxDocumentIterator::_metaBuffer [private]
Referenced by _copyMetadata(), and nextDocument().
The documentation for this class was generated from the following files:
MboxDocumentIterator.hpp
MboxDocumentIterator.cpp