Indri: indri::utility::RegionAllocator Class Reference
indri::utility::RegionAllocator Class Reference
#include <RegionAllocator.hpp>
Public Member Functions
RegionAllocator ()
~RegionAllocator ()
void * allocate (size_t bytes)
size_t allocatedBytes ()
Private Attributes
std::vector< Buffer * > _buffers
std::vector< void * > _malloced
size_t _mallocBytes
Constructor & Destructor Documentation
indri::utility::RegionAllocator::RegionAllocator () [inline]
indri::utility::RegionAllocator::~RegionAllocator () [inline]
References _buffers, _malloced, and indri::utility::delete_vector_contents().
Member Function Documentation
void* indri::utility::RegionAllocator::allocate (size_t bytes) [inline]
References _buffers, _mallocBytes, and _malloced.
Referenced by indri::index::DocListMemoryBuilder::_grow(), indri::index::MemoryIndex::_lookupTerm(), and indri::utility::HashTable< const char *, term_entry * >::_newBucket().
size_t indri::utility::RegionAllocator::allocatedBytes () [inline]
References _buffers, and _mallocBytes.
Referenced by indri::index::MemoryIndex::memorySize().
Member Data Documentation
std::vector<Buffer*> indri::utility::RegionAllocator::_buffers [private]
Referenced by allocate(), allocatedBytes(), and ~RegionAllocator().
size_t indri::utility::RegionAllocator::_mallocBytes [private]
Referenced by allocate(), and allocatedBytes().
std::vector<void*> indri::utility::RegionAllocator::_malloced [private]
Referenced by allocate(), and ~RegionAllocator().
The documentation for this class was generated from the following file:
RegionAllocator.hpp