Indri: indri::parse::Conflater Class Reference
indri::parse::Conflater Class Reference
#include <Conflater.hpp>
Classes
struct attribute_pattern
struct tag_pattern
Public Member Functions
Conflater (const std::map< ConflationPattern *, std::string > &conflations)
~Conflater ()
void conflate (TagEvent *tev)
void conflate (TagExtent *tex)
const char * conflate (const char *tagname)
Protected Member Functions
const char * _lookup (const char *name, indri::utility::greedy_vector< indri::parse::AttributeValuePair, 2 > &attributes)
Protected Attributes
indri::utility::HashTable
< const char *, tag_pattern * > _pattern_table
Private Member Functions
const char * _strdup (const char *token)
Private Attributes
indri::utility::Buffer _stringBuf
Constructor & Destructor Documentation
indri::parse::Conflater::Conflater (const std::map< ConflationPattern *, std::string > & conflations) [inline]
References _pattern_table, _strdup(), _stringBuf, indri::parse::ConflationPattern::attribute_name, indri::parse::Conflater::tag_pattern::attributes, indri::parse::Conflater::attribute_pattern::conflation, indri::parse::Conflater::tag_pattern::conflation, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::Buffer::grow(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::parse::Conflater::attribute_pattern::match_attribute_name, indri::parse::Conflater::tag_pattern::match_tag_name, indri::parse::ConflationPattern::tag_name, indri::parse::ConflationPattern::value, and indri::parse::Conflater::attribute_pattern::values.
indri::parse::Conflater::~Conflater () [inline]
References _pattern_table, indri::parse::Conflater::tag_pattern::attributes, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Member Function Documentation
const char* indri::parse::Conflater::_lookup (const char * name, indri::utility::greedy_vector< indri::parse::AttributeValuePair, 2 > & attributes) [inline, protected]
References _pattern_table, indri::parse::Conflater::tag_pattern::attributes, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::Conflater::tag_pattern::conflation, indri::parse::Conflater::attribute_pattern::conflation, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::parse::Conflater::attribute_pattern::match_attribute_name, indri::parse::Conflater::tag_pattern::match_tag_name, and indri::parse::Conflater::attribute_pattern::values.
Referenced by conflate().
const char* indri::parse::Conflater::_strdup (const char * token) [inline, private]
References _stringBuf, and indri::utility::Buffer::write().
Referenced by Conflater().
const char* indri::parse::Conflater::conflate (const char * tagname) [inline]
return the conflation for this tag name, if one exists. otherwise, return input argument. Does not handle the case of attribute dependent conflations
References _lookup().
void indri::parse::Conflater::conflate (TagExtent * tex) [inline]
References _lookup(), indri::parse::TagExtent::attributes, indri::utility::greedy_vector< _Type, _Count >::clear(), and indri::parse::TagExtent::name.
void indri::parse::Conflater::conflate (TagEvent * tev) [inline]
References _lookup(), indri::parse::TagEvent::attributes, indri::utility::greedy_vector< _Type, _Count >::clear(), and indri::parse::TagEvent::name.
Referenced by indri::parse::TaggedTextParser::handleTag(), indri::parse::HTMLParser::handleTag(), indri::parse::OffsetAnnotationAnnotator::open(), indri::parse::TaggedTextParser::parse(), indri::parse::OffsetAnnotationAnnotator::readAnnotationTags(), and indri::parse::OffsetAnnotationAnnotator::setTags().
Member Data Documentation
indri::utility::HashTable<const char *,tag_pattern*> indri::parse::Conflater::_pattern_table [protected]
Referenced by _lookup(), Conflater(), and ~Conflater().
indri::utility::Buffer indri::parse::Conflater::_stringBuf [private]
Referenced by _strdup(), and Conflater().
The documentation for this class was generated from the following file:
Conflater.hpp