Indri: indri::query::TermScoreFunction Class Reference
indri::query::TermScoreFunction Class Reference
#include <TermScoreFunction.hpp>
Public Member Functions
virtual double scoreOccurrence (double occurrences, int contextLength)=0
virtual double scoreOccurrence (double occurrences, int contextLength, double documentOccurrences, int documentLength)=0
Detailed Description
Abstract base class for all term scoring and smoothing functions. See the rule parameter format for a description of the rule parameter format.
See also:
TermScoreFunctionFactory for a description of how to add a new scoring function.
Member Function Documentation
virtual double indri::query::TermScoreFunction::scoreOccurrence (double occurrences, int contextLength, double documentOccurrences, int documentLength) [pure virtual]
Implemented in indri::query::DirichletTermScoreFunction, indri::query::JelinekMercerTermScoreFunction, indri::query::TFIDFTermScoreFunction, and indri::query::TwoStageTermScoreFunction.
virtual double indri::query::TermScoreFunction::scoreOccurrence (double occurrences, int contextLength) [pure virtual]
Implemented in indri::query::DirichletTermScoreFunction, indri::query::JelinekMercerTermScoreFunction, indri::query::TFIDFTermScoreFunction, and indri::query::TwoStageTermScoreFunction.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), indri::query::RelevanceModel::_scoreGrams(), indri::infnet::TermFrequencyBeliefNode::indexChanged(), indri::infnet::TermFrequencyBeliefNode::score(), indri::infnet::NullScorerNode::score(), indri::infnet::NestedListBeliefNode::score(), indri::infnet::ListBeliefNode::score(), and indri::infnet::CachedFrequencyBeliefNode::score().
The documentation for this class was generated from the following file:
TermScoreFunction.hpp