Indri: Indri::TagExtentVector Class Reference
Indri::TagExtentVector Class Reference
Classes
class TagExtentVectorEnumerator
Public Member Functions
virtual void Dispose ()
TagExtentVector (System.Collections.ICollection c)
void CopyTo (System.Array array)
void CopyTo (System.Array array, int arrayIndex)
void CopyTo (int index, System.Array array, int arrayIndex, int count)
TagExtentVectorEnumerator GetEnumerator ()
void Clear ()
void Add (TagExtent value)
TagExtentVector ()
TagExtentVector (int capacity)
void AddRange (TagExtentVector values)
TagExtentVector GetRange (int index, int count)
void Insert (int index, TagExtent value)
void InsertRange (int index, TagExtentVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, TagExtentVector values)
Static Public Member Functions
static TagExtentVector Repeat (TagExtent value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
TagExtent this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal TagExtentVector (IntPtr cPtr, bool cMemoryOwn)
~TagExtentVector ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
TagExtent getitemcopy (int index)
TagExtent getitem (int index)
void setitem (int index, TagExtent value)
Static Private Member Functions
static internal HandleRef getCPtr (TagExtentVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::TagExtentVector::TagExtentVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::TagExtentVector::~TagExtentVector () [inline, private]
References Dispose().
Indri::TagExtentVector::TagExtentVector (System.Collections.ICollection c) [inline]
References Add().
Indri::TagExtentVector::TagExtentVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::TagExtentVector::TagExtentVector (int capacity) [inline]
Member Function Documentation
void Indri::TagExtentVector::Add (TagExtent value) [inline]
References swigCPtr.
Referenced by TagExtentVector().
void Indri::TagExtentVector::AddRange (TagExtentVector values) [inline]
References swigCPtr.
uint Indri::TagExtentVector::capacity () [inline, private]
References swigCPtr.
void Indri::TagExtentVector::Clear () [inline]
References swigCPtr.
void Indri::TagExtentVector::CopyTo (int index, System.Array array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::TagExtentVector::CopyTo (System.Array array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::TagExtentVector::CopyTo (System.Array array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::TagExtentVector::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~TagExtentVector().
static internal HandleRef Indri::TagExtentVector::getCPtr (TagExtentVector obj) [inline, static, private]
References swigCPtr.
TagExtentVectorEnumerator Indri::TagExtentVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::TagExtentVector::GetEnumerator () [inline, private]
TagExtent Indri::TagExtentVector::getitem (int index) [inline, private]
References swigCPtr.
TagExtent Indri::TagExtentVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
TagExtentVector Indri::TagExtentVector::GetRange (int index, int count) [inline]
References swigCPtr, and TagExtentVector().
void Indri::TagExtentVector::Insert (int index, TagExtent value) [inline]
References swigCPtr.
void Indri::TagExtentVector::InsertRange (int index, TagExtentVector values) [inline]
References swigCPtr.
void Indri::TagExtentVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::TagExtentVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static TagExtentVector Indri::TagExtentVector::Repeat (TagExtent value, int count) [inline, static]
References TagExtentVector().
void Indri::TagExtentVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::TagExtentVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::TagExtentVector::Reverse () [inline]
References swigCPtr.
void Indri::TagExtentVector::setitem (int index, TagExtent value) [inline, private]
References swigCPtr.
void Indri::TagExtentVector::SetRange (int index, TagExtentVector values) [inline]
References swigCPtr.
uint Indri::TagExtentVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::TagExtentVector::TagExtentVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::TagExtentVector::swigCMemOwn [protected]
Referenced by Dispose(), and TagExtentVector().
HandleRef Indri::TagExtentVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), Insert(), InsertRange(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), size(), and TagExtentVector().
Property Documentation
int Indri::TagExtentVector::Capacity [get, set]
int Indri::TagExtentVector::Count [get]
Referenced by CopyTo(), Indri::TagExtentVector::TagExtentVectorEnumerator::MoveNext(), Indri::TagExtentVector::TagExtentVectorEnumerator::Reset(), and Indri::TagExtentVector::TagExtentVectorEnumerator::TagExtentVectorEnumerator().
bool Indri::TagExtentVector::IsFixedSize [get]
bool Indri::TagExtentVector::IsReadOnly [get]
bool Indri::TagExtentVector::IsSynchronized [get]
TagExtent Indri::TagExtentVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
TagExtentVector.cs