Indri: indri::api::QueryAnnotation Class Reference
indri::api::QueryAnnotation Class Reference
#include <QueryAnnotation.hpp>
Public Member Functions
QueryAnnotation ()
QueryAnnotation (indri::lang::Node *queryRoot, indri::infnet::EvaluatorNode::MResults &annotations, std::vector< indri::api::ScoredExtentResult > &results)
~QueryAnnotation ()
const QueryAnnotationNode * getQueryTree () const
const std::map< std::string,
std::vector
< indri::api::ScoredExtentResult > > & getAnnotations () const
const std::vector
< indri::api::ScoredExtentResult > & getResults () const
Private Attributes
QueryAnnotationNode * _queryTree
indri::infnet::EvaluatorNode::MResults _annotations
std::vector
< indri::api::ScoredExtentResult > _results
Constructor & Destructor Documentation
indri::api::QueryAnnotation::QueryAnnotation ()
indri::api::QueryAnnotation::QueryAnnotation (indri::lang::Node * queryRoot, indri::infnet::EvaluatorNode::MResults & annotations, std::vector< indri::api::ScoredExtentResult > & results)
References _annotations, _queryTree, _results, indri::lang::QueryNodeBuilder::getRoot(), and indri::lang::Node::walk().
indri::api::QueryAnnotation::~QueryAnnotation ()
References _queryTree, and delete_query_node().
Member Function Documentation
const indri::infnet::EvaluatorNode::MResults & indri::api::QueryAnnotation::getAnnotations () const
References _annotations.
Referenced by indri::api::SnippetBuilder::build().
const indri::api::QueryAnnotationNode * indri::api::QueryAnnotation::getQueryTree () const
References _queryTree.
Referenced by indri::api::SnippetBuilder::build(), and indri::api::QueryEnvironment::runQuery().
const std::vector< indri::api::ScoredExtentResult > & indri::api::QueryAnnotation::getResults () const
References _results.
Referenced by QueryThread::_runQuery(), and indri::api::QueryEnvironment::runQuery().
Member Data Documentation
indri::infnet::EvaluatorNode::MResults indri::api::QueryAnnotation::_annotations [private]
Referenced by getAnnotations(), and QueryAnnotation().
QueryAnnotationNode* indri::api::QueryAnnotation::_queryTree [private]
Referenced by getQueryTree(), QueryAnnotation(), and ~QueryAnnotation().
std::vector<indri::api::ScoredExtentResult> indri::api::QueryAnnotation::_results [private]
Referenced by getResults(), and QueryAnnotation().
The documentation for this class was generated from the following files:
QueryAnnotation.hpp
QueryAnnotation.cpp