Indri: indri::query::TFIDFExpander Class Reference
indri::query::TFIDFExpander Class Reference
#include <TFIDFExpander.hpp>
Public Member Functions
TFIDFExpander (indri::api::QueryEnvironment *env, indri::api::Parameters &param)
virtual std::string expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > &results)
Private Member Functions
std::string _buildQuery (double originalWeight, const std::vector< std::pair< std::string, double > > &expansionTerms)
Constructor & Destructor Documentation
indri::query::TFIDFExpander::TFIDFExpander (indri::api::QueryEnvironment * env, indri::api::Parameters & param)
Member Function Documentation
std::string indri::query::TFIDFExpander::_buildQuery (double originalWeight, const std::vector< std::pair< std::string, double > > & expansionTerms) [private]
References indri::query::QueryExpander::_stopwords.
Referenced by expand().
std::string indri::query::TFIDFExpander::expand (std::string originalQuery, std::vector< indri::api::ScoredExtentResult > & results) [virtual]
Implements indri::query::QueryExpander.
References _BM25TF(), _buildQuery(), indri::query::QueryExpander::_env, indri::query::QueryExpander::_param, _parseSmoothing(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::api::QueryEnvironment::documentCount(), indri::api::QueryEnvironment::documentStemCount(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::Parameters::get(), indri::query::QueryExpander::getDocumentVectors(), indri::api::QueryEnvironment::getServers(), indri::query::QueryExpander::getVocabulary(), indri::api::DocumentVector::positions(), TFIDFTerm::relevance, indri::utility::greedy_vector< _Type, _Count >::size(), TFIDFTerm::stem, indri::api::DocumentVector::stems(), and indri::api::QueryEnvironment::termCount().
The documentation for this class was generated from the following files:
TFIDFExpander.hpp
TFIDFExpander.cpp