Indri: indri::lang::Node Class Reference
indri::lang::Node Class Reference
#include <QuerySpec.hpp>
Public Member Functions
Node ()
virtual ~Node ()
void setNodeName (const std::string &name)
const std::string & nodeName () const
virtual std::string typeName () const
virtual std::string queryText () const =0
virtual bool operator< (Node &other)
virtual bool operator== (Node &other)
virtual UINT64 hashCode () const =0
virtual void pack (Packer &packer)=0
virtual void walk (Walker &walker)=0
virtual Node * copy (Copier &copier)=0
Protected Attributes
std::string _name
Constructor & Destructor Documentation
indri::lang::Node::Node () [inline]
References _name.
virtual indri::lang::Node::~Node () [inline, virtual]
Member Function Documentation
virtual Node* indri::lang::Node::copy (Copier & copier) [pure virtual]
Implemented in indri::lang::IndexTerm, indri::lang::Field, indri::lang::ExtentInside, indri::lang::WeightedExtentOr, indri::lang::ExtentOr, indri::lang::ExtentAnd, indri::lang::BAndNode, indri::lang::UWNode, indri::lang::ODNode, indri::lang::FilReqNode, indri::lang::FilRejNode, indri::lang::FieldLessNode, indri::lang::FieldGreaterNode, indri::lang::FieldBetweenNode, indri::lang::FieldEqualsNode, indri::lang::RawScorerNode, indri::lang::TermFrequencyScorerNode, indri::lang::CachedFrequencyScorerNode, indri::lang::PriorNode, indri::lang::OrNode, indri::lang::NotNode, indri::lang::MaxNode, indri::lang::CombineNode, indri::lang::WAndNode, indri::lang::WSumNode, indri::lang::WeightNode, indri::lang::ExtentRestriction, indri::lang::FixedPassage, indri::lang::FilterNode, indri::lang::ListAccumulator, indri::lang::ContextCounterNode, indri::lang::ContextSimpleCounterNode, indri::lang::ScoreAccumulatorNode, indri::lang::AnnotatorNode, indri::lang::FieldWildcard, indri::lang::NestedExtentInside, indri::lang::NestedRawScorerNode, indri::lang::ExtentEnforcement, indri::lang::ContextInclusionNode, indri::lang::LengthPrior, indri::lang::DocumentStructureNode, indri::lang::ShrinkageScorerNode, indri::lang::ExtentDescendant, indri::lang::ExtentChild, indri::lang::ExtentParent, indri::lang::WildcardTerm, indri::lang::PlusNode, and indri::lang::WPlusNode.
Referenced by indri::lang::UnweightedCombinationNode::_copy(), indri::lang::ApplyCopiers< T, NodeType >::ApplyCopiers(), indri::lang::ApplySingleCopier< T, NodeType >::ApplySingleCopier(), indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::ShrinkageScorerNode::copy(), indri::lang::LengthPrior::copy(), indri::lang::ExtentEnforcement::copy(), indri::lang::NestedRawScorerNode::copy(), indri::lang::NestedExtentInside::copy(), indri::lang::AnnotatorNode::copy(), indri::lang::ScoreAccumulatorNode::copy(), indri::lang::ContextCounterNode::copy(), indri::lang::ListAccumulator::copy(), indri::lang::FilterNode::copy(), indri::lang::FixedPassage::copy(), indri::lang::ExtentRestriction::copy(), indri::lang::NotNode::copy(), indri::lang::CachedFrequencyScorerNode::copy(), indri::lang::RawScorerNode::copy(), indri::lang::FieldEqualsNode::copy(), indri::lang::FieldBetweenNode::copy(), indri::lang::FieldGreaterNode::copy(), indri::lang::FieldLessNode::copy(), indri::lang::FilRejNode::copy(), indri::lang::FilReqNode::copy(), indri::lang::ExtentInside::copy(), and indri::api::QueryEnvironment::runQuery().
virtual UINT64 indri::lang::Node::hashCode () const [pure virtual]
Implemented in indri::lang::IndexTerm, indri::lang::Field, indri::lang::ExtentInside, indri::lang::WeightedExtentOr, indri::lang::ExtentOr, indri::lang::ExtentAnd, indri::lang::BAndNode, indri::lang::UWNode, indri::lang::ODNode, indri::lang::FilReqNode, indri::lang::FilRejNode, indri::lang::FieldLessNode, indri::lang::FieldGreaterNode, indri::lang::FieldBetweenNode, indri::lang::FieldEqualsNode, indri::lang::RawScorerNode, indri::lang::TermFrequencyScorerNode, indri::lang::CachedFrequencyScorerNode, indri::lang::PriorNode, indri::lang::OrNode, indri::lang::NotNode, indri::lang::MaxNode, indri::lang::CombineNode, indri::lang::WAndNode, indri::lang::WSumNode, indri::lang::WeightNode, indri::lang::ExtentRestriction, indri::lang::FixedPassage, indri::lang::FilterNode, indri::lang::ListAccumulator, indri::lang::ContextCounterNode, indri::lang::ContextSimpleCounterNode, indri::lang::ScoreAccumulatorNode, indri::lang::AnnotatorNode, indri::lang::FieldWildcard, indri::lang::NestedExtentInside, indri::lang::NestedRawScorerNode, indri::lang::ExtentEnforcement, indri::lang::ContextInclusionNode, indri::lang::LengthPrior, indri::lang::DocumentStructureNode, indri::lang::ShrinkageScorerNode, indri::lang::ExtentDescendant, indri::lang::ExtentChild, indri::lang::ExtentParent, indri::lang::WildcardTerm, indri::lang::PlusNode, and indri::lang::WPlusNode.
Referenced by indri::lang::ExtentParent::hashCode(), indri::lang::ExtentChild::hashCode(), indri::lang::ExtentDescendant::hashCode(), indri::lang::ShrinkageScorerNode::hashCode(), indri::lang::ExtentEnforcement::hashCode(), indri::lang::NestedRawScorerNode::hashCode(), indri::lang::NestedExtentInside::hashCode(), indri::lang::FilterNode::hashCode(), indri::lang::FixedPassage::hashCode(), indri::lang::ExtentRestriction::hashCode(), indri::lang::NotNode::hashCode(), indri::lang::CachedFrequencyScorerNode::hashCode(), indri::lang::RawScorerNode::hashCode(), indri::lang::FieldEqualsNode::hashCode(), indri::lang::FieldBetweenNode::hashCode(), indri::lang::FieldGreaterNode::hashCode(), indri::lang::FieldLessNode::hashCode(), indri::lang::FilRejNode::hashCode(), indri::lang::FilReqNode::hashCode(), and indri::lang::ExtentInside::hashCode().
const std::string& indri::lang::Node::nodeName () const [inline]
References _name.
Referenced by indri::infnet::InferenceNetworkBuilder::_after(), indri::lang::ContextInclusionNode::_copy(), indri::lang::WeightedCombinationNode::_copy(), indri::lang::UnweightedCombinationNode::_copy(), indri::api::QueryEnvironment::_expCount(), indri::lang::WeightFoldingCopier::after(), indri::lang::Packer::after(), indri::infnet::InferenceNetworkBuilder::after(), indri::lang::FrequencyListCopier::after(), indri::lang::ContextSimpleCountCollectorCopier::after(), indri::lang::NoContextCountGraphCopier::after(), indri::lang::ContextCountGraphCopier::after(), indri::lang::TreePrinterWalker::before(), indri::lang::WildcardTerm::copy(), indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::DocumentStructureNode::copy(), indri::lang::ExtentEnforcement::copy(), indri::lang::NestedExtentInside::copy(), indri::lang::FieldWildcard::copy(), indri::lang::AnnotatorNode::copy(), indri::lang::ScoreAccumulatorNode::copy(), indri::lang::ListAccumulator::copy(), indri::lang::FilterNode::copy(), indri::lang::FixedPassage::copy(), indri::lang::ExtentRestriction::copy(), indri::lang::NotNode::copy(), indri::lang::PriorNode::copy(), indri::lang::CachedFrequencyScorerNode::copy(), indri::lang::ODNode::copy(), indri::lang::UWNode::copy(), indri::lang::BAndNode::copy(), indri::lang::ExtentAnd::copy(), indri::lang::ExtentOr::copy(), indri::lang::ExtentInside::copy(), indri::lang::Printer::defaultBefore(), indri::lang::QueryNodeBuilder::defaultBefore(), indri::api::QueryEnvironment::expressionList(), and indri::lang::Unpacker::unpack().
virtual bool indri::lang::Node::operator< (Node & other) [inline, virtual]
References queryText(), and typeName().
virtual bool indri::lang::Node::operator== (Node & other) [inline, virtual]
virtual void indri::lang::Node::pack (Packer & packer) [pure virtual]
Implemented in indri::lang::IndexTerm, indri::lang::Field, indri::lang::ExtentInside, indri::lang::WeightedExtentOr, indri::lang::ExtentOr, indri::lang::ExtentAnd, indri::lang::BAndNode, indri::lang::UWNode, indri::lang::ODNode, indri::lang::FilReqNode, indri::lang::FilRejNode, indri::lang::FieldLessNode, indri::lang::FieldGreaterNode, indri::lang::FieldBetweenNode, indri::lang::FieldEqualsNode, indri::lang::RawScorerNode, indri::lang::TermFrequencyScorerNode, indri::lang::CachedFrequencyScorerNode, indri::lang::PriorNode, indri::lang::UnweightedCombinationNode, indri::lang::WeightedCombinationNode, indri::lang::NotNode, indri::lang::ExtentRestriction, indri::lang::FixedPassage, indri::lang::FilterNode, indri::lang::ListAccumulator, indri::lang::ContextCounterNode, indri::lang::ContextSimpleCounterNode, indri::lang::ScoreAccumulatorNode, indri::lang::AnnotatorNode, indri::lang::FieldWildcard, indri::lang::ContextInclusionNode, indri::lang::LengthPrior, indri::lang::DocumentStructureNode, indri::lang::ShrinkageScorerNode, and indri::lang::WildcardTerm.
Referenced by indri::lang::Packer::pack().
virtual std::string indri::lang::Node::queryText () const [pure virtual]
Implemented in indri::lang::IndexTerm, indri::lang::Field, indri::lang::ExtentInside, indri::lang::WeightedExtentOr, indri::lang::ExtentOr, indri::lang::ExtentAnd, indri::lang::BAndNode, indri::lang::UWNode, indri::lang::ODNode, indri::lang::FilReqNode, indri::lang::FilRejNode, indri::lang::FieldLessNode, indri::lang::FieldGreaterNode, indri::lang::FieldBetweenNode, indri::lang::FieldEqualsNode, indri::lang::RawScorerNode, indri::lang::TermFrequencyScorerNode, indri::lang::CachedFrequencyScorerNode, indri::lang::PriorNode, indri::lang::OrNode, indri::lang::NotNode, indri::lang::MaxNode, indri::lang::CombineNode, indri::lang::WAndNode, indri::lang::WSumNode, indri::lang::WeightNode, indri::lang::ExtentRestriction, indri::lang::FixedPassage, indri::lang::FilterNode, indri::lang::ListAccumulator, indri::lang::ContextCounterNode, indri::lang::ContextSimpleCounterNode, indri::lang::ScoreAccumulatorNode, indri::lang::AnnotatorNode, indri::lang::FieldWildcard, indri::lang::ContextInclusionNode, indri::lang::LengthPrior, indri::lang::DocumentStructureNode, indri::lang::ShrinkageScorerNode, indri::lang::WildcardTerm, indri::lang::PlusNode, and indri::lang::WPlusNode.
Referenced by indri::lang::ContextInclusionNode::_childText(), indri::lang::TreePrinterWalker::defaultBefore(), indri::lang::Printer::defaultBefore(), indri::lang::QueryNodeBuilder::defaultBefore(), operator<(), indri::lang::ShrinkageScorerNode::queryText(), indri::lang::AnnotatorNode::queryText(), indri::lang::ScoreAccumulatorNode::queryText(), indri::lang::ContextCounterNode::queryText(), indri::lang::ListAccumulator::queryText(), indri::lang::FilterNode::queryText(), indri::lang::FixedPassage::queryText(), indri::lang::ExtentRestriction::queryText(), indri::lang::NotNode::queryText(), indri::lang::CachedFrequencyScorerNode::queryText(), indri::lang::RawScorerNode::queryText(), indri::lang::FieldEqualsNode::queryText(), indri::lang::FieldBetweenNode::queryText(), indri::lang::FieldGreaterNode::queryText(), indri::lang::FieldLessNode::queryText(), indri::lang::FilRejNode::queryText(), indri::lang::FilReqNode::queryText(), and indri::lang::ExtentInside::queryText().
void indri::lang::Node::setNodeName (const std::string & name) [inline]
References _name.
Referenced by indri::api::QueryEnvironment::_expCount(), indri::lang::Unpacker::_unpack(), indri::lang::WeightFoldingCopier::after(), indri::lang::FrequencyListCopier::after(), indri::lang::ContextSimpleCountCollectorCopier::after(), indri::lang::NoContextCountGraphCopier::after(), indri::lang::ContextCountGraphCopier::after(), indri::lang::WildcardTerm::copy(), indri::lang::ExtentParent::copy(), indri::lang::ExtentChild::copy(), indri::lang::ExtentDescendant::copy(), indri::lang::DocumentStructureNode::copy(), indri::lang::ExtentEnforcement::copy(), indri::lang::NestedExtentInside::copy(), indri::lang::FieldWildcard::copy(), indri::lang::AnnotatorNode::copy(), indri::lang::ScoreAccumulatorNode::copy(), indri::lang::ListAccumulator::copy(), indri::lang::FilterNode::copy(), indri::lang::FixedPassage::copy(), indri::lang::ExtentRestriction::copy(), indri::lang::NotNode::copy(), indri::lang::PriorNode::copy(), indri::lang::CachedFrequencyScorerNode::copy(), indri::lang::ODNode::copy(), indri::lang::UWNode::copy(), indri::lang::BAndNode::copy(), indri::lang::ExtentAnd::copy(), indri::lang::ExtentOr::copy(), indri::lang::ExtentInside::copy(), and indri::api::QueryEnvironment::expressionList().
virtual std::string indri::lang::Node::typeName () const [inline, virtual]
Reimplemented in indri::lang::IndexTerm, indri::lang::Field, indri::lang::ExtentInside, indri::lang::WeightedExtentOr, indri::lang::ExtentOr, indri::lang::ExtentAnd, indri::lang::BAndNode, indri::lang::UWNode, indri::lang::ODNode, indri::lang::FilReqNode, indri::lang::FilRejNode, indri::lang::FieldLessNode, indri::lang::FieldGreaterNode, indri::lang::FieldBetweenNode, indri::lang::FieldEqualsNode, indri::lang::RawScorerNode, indri::lang::TermFrequencyScorerNode, indri::lang::CachedFrequencyScorerNode, indri::lang::PriorNode, indri::lang::OrNode, indri::lang::NotNode, indri::lang::MaxNode, indri::lang::CombineNode, indri::lang::WAndNode, indri::lang::WSumNode, indri::lang::WeightNode, indri::lang::ExtentRestriction, indri::lang::FixedPassage, indri::lang::FilterNode, indri::lang::ListAccumulator, indri::lang::ContextCounterNode, indri::lang::ContextSimpleCounterNode, indri::lang::ScoreAccumulatorNode, indri::lang::AnnotatorNode, indri::lang::FieldWildcard, indri::lang::NestedExtentInside, indri::lang::NestedRawScorerNode, indri::lang::ExtentEnforcement, indri::lang::ContextInclusionNode, indri::lang::DocumentStructureNode, indri::lang::ShrinkageScorerNode, indri::lang::ExtentDescendant, indri::lang::ExtentChild, indri::lang::ExtentParent, indri::lang::WildcardTerm, indri::lang::PlusNode, and indri::lang::WPlusNode.
Referenced by indri::lang::Packer::after(), indri::lang::TreePrinterWalker::defaultBefore(), indri::lang::Printer::defaultBefore(), indri::lang::QueryNodeBuilder::defaultBefore(), and operator<().
virtual void indri::lang::Node::walk (Walker & walker) [pure virtual]
Implemented in indri::lang::IndexTerm, indri::lang::Field, indri::lang::ExtentInside, indri::lang::WeightedExtentOr, indri::lang::ExtentOr, indri::lang::ExtentAnd, indri::lang::BAndNode, indri::lang::UWNode, indri::lang::ODNode, indri::lang::FilReqNode, indri::lang::FilRejNode, indri::lang::FieldLessNode, indri::lang::FieldGreaterNode, indri::lang::FieldBetweenNode, indri::lang::FieldEqualsNode, indri::lang::RawScorerNode, indri::lang::TermFrequencyScorerNode, indri::lang::CachedFrequencyScorerNode, indri::lang::PriorNode, indri::lang::OrNode, indri::lang::NotNode, indri::lang::MaxNode, indri::lang::CombineNode, indri::lang::WAndNode, indri::lang::WSumNode, indri::lang::WeightNode, indri::lang::ExtentRestriction, indri::lang::FixedPassage, indri::lang::FilterNode, indri::lang::ListAccumulator, indri::lang::ContextCounterNode, indri::lang::ContextSimpleCounterNode, indri::lang::ScoreAccumulatorNode, indri::lang::AnnotatorNode, indri::lang::FieldWildcard, indri::lang::ContextInclusionNode, indri::lang::LengthPrior, indri::lang::DocumentStructureNode, indri::lang::ShrinkageScorerNode, indri::lang::ExtentDescendant, indri::lang::ExtentChild, indri::lang::ExtentParent, indri::lang::WildcardTerm, indri::lang::PlusNode, and indri::lang::WPlusNode.
Referenced by indri::api::QueryAnnotation::QueryAnnotation(), indri::api::QueryEnvironment::runQuery(), indri::lang::ExtentParent::walk(), indri::lang::ExtentChild::walk(), indri::lang::ExtentDescendant::walk(), indri::lang::ShrinkageScorerNode::walk(), indri::lang::LengthPrior::walk(), indri::lang::AnnotatorNode::walk(), indri::lang::ScoreAccumulatorNode::walk(), indri::lang::ContextCounterNode::walk(), indri::lang::ListAccumulator::walk(), indri::lang::FilterNode::walk(), indri::lang::FixedPassage::walk(), indri::lang::ExtentRestriction::walk(), indri::lang::NotNode::walk(), indri::lang::CachedFrequencyScorerNode::walk(), indri::lang::RawScorerNode::walk(), indri::lang::FieldEqualsNode::walk(), indri::lang::FieldBetweenNode::walk(), indri::lang::FieldGreaterNode::walk(), indri::lang::FieldLessNode::walk(), indri::lang::FilRejNode::walk(), indri::lang::FilReqNode::walk(), and indri::lang::ExtentInside::walk().
Member Data Documentation
std::string indri::lang::Node::_name [protected]
Referenced by Node(), nodeName(), and setNodeName().
The documentation for this class was generated from the following file:
QuerySpec.hpp