Indri: indri::collection::Repository Class Reference
indri::collection::Repository Class Reference
#include <Repository.hpp>
Classes
struct Field
struct Load
Public Types
typedef std::vector
< indri::index::Index * > index_vector
typedef indri::atomic::ref_ptr
< index_vector > index_state
Public Member Functions
Repository ()
~Repository ()
int addDocument (indri::api::ParsedDocument *document, bool inCollection=true)
void deleteDocument (int documentID)
const std::vector< Field > & fields () const
std::vector< std::string > tags () const
std::vector< std::string > priors () const
std::string processTerm (const std::string &term)
class CompressedCollection * collection ()
void create (const std::string &path, indri::api::Parameters *options=0)
void open (const std::string &path, indri::api::Parameters *options=0)
void openRead (const std::string &path, indri::api::Parameters *options=0)
void close ()
Close the repository.
void compact ()
index_state indexes ()
Indexes in this repository.
indri::collection::PriorListIterator * priorListIterator (const std::string &priorName)
Return a prior iterator.
void countQuery ()
Notify the repository that a query has happened.
void write ()
Write the most recent state out to disk.
void merge ()
Merge all internal indexes together.
indri::index::DeletedDocumentList & deletedList ()
List of deleted documents in this repository.
Load queryLoad ()
Returns the average number of documents added each minute in the last 1, 5 and 15 minutes.
Load documentLoad ()
Returns the average number of documents added each minute in the last 1, 5 and 15 minutes.
Static Public Member Functions
static bool exists (const std::string &path)
static void makeEmpty (const std::string &path)
Make an empty repository directory on disk.
static void merge (const std::string &outputIndex, const std::vector< std::string > &inputIndexes)
Merge two or more repositories together.
Private Types
enum { LOAD_MINUTES = 15, LOAD_MINUTE_FRACTION = 12 }
Private Member Functions
void _writeParameters (const std::string &path)
void _checkpoint ()
void _incrementLoad ()
void _countDocumentAdd ()
Load _computeLoad (indri::atomic::value_type *loadArray)
void _openPriors (const std::string &path)
void _closePriors ()
void _buildFields ()
void _buildChain (indri::api::Parameters &parameters, indri::api::Parameters *options)
void _copyParameters (indri::api::Parameters &options)
void _removeStates (std::vector< index_state > &toRemove)
void _remove (const std::string &path)
void _openIndexes (indri::api::Parameters &params, const std::string &parentPath)
std::vector< index_state > _statesContaining (std::vector< indri::index::Index * > &indexes)
bool _stateContains (index_state &state, std::vector< indri::index::Index * > &indexes)
void _swapState (std::vector< indri::index::Index * > &oldIndexes, indri::index::Index *newIndex)
void _closeIndexes ()
void _merge (index_state &state)
indri::index::Index * _mergeStage (index_state &state)
UINT64 _mergeMemory (const std::vector< indri::index::Index * > &indexes)
unsigned int _mergeFiles (const std::vector< indri::index::Index * > &indexes)
void _merge ()
merge all known indexes together
void _write ()
write the active index to disk
void _trim ()
merge together some of the more recent indexes
void _startThreads ()
void _stopThreads ()
void _setThrashing (bool flag)
UINT64 _timeSinceThrashing ()
void _addMemoryIndex ()
Static Private Member Functions
static std::vector< std::string > _fieldNames (indri::api::Parameters &parameters)
static std::string _stemmerName (indri::api::Parameters &parameters)
static void _mergeClosedIndexes (const std::string &outputPath, const std::vector< std::string > &repositories, const std::vector< indri::collection::Repository::Field > &indexFields, const std::vector< lemur::api::DOCID_T > &documentMaximums)
static void _writeMergedManifest (const std::string &path, indri::api::Parameters &firstManifest)
static void _mergeBitmaps (const std::string &outputPath, const std::vector< std::string > &repositories, const std::vector< lemur::api::DOCID_T > &documentCounts)
static void _mergeCompressedCollections (const std::string &outputPath, const std::vector< std::string > &repositories, const std::vector< lemur::api::DOCID_T > &documentMaximums)
static void _cleanAndCreateDirectory (const std::string &path)
static std::vector
< indri::index::Index::FieldDescription > _fieldsForIndex (const std::vector< Repository::Field > &_fields)
Private Attributes
class RepositoryMaintenanceThread * _maintenanceThread
class RepositoryLoadThread * _loadThread
indri::thread::Mutex _stateLock
std::vector< index_state > _states
protects against state changes
index_state _active
int _indexCount
volatile bool _maintenanceRunning
volatile bool _loadThreadRunning
indri::thread::Mutex _addLock
class CompressedCollection * _collection
protects addDocument
indri::index::DeletedDocumentList _deletedList
indri::api::Parameters _parameters
std::vector
< indri::parse::Transformation * > _transformations
std::vector< Field > _fields
std::vector
< indri::index::Index::FieldDescription > _indexFields
std::map< std::string,
indri::file::File * > _priorFiles
std::string _path
bool _readOnly
INT64 _memory
UINT64 _lastThrashTime
volatile bool _thrashing
indri::atomic::value_type _queryLoad [LOAD_MINUTES *LOAD_MINUTE_FRACTION]
indri::atomic::value_type _documentLoad [LOAD_MINUTES *LOAD_MINUTE_FRACTION]
Friends
class RepositoryMaintenanceThread
class RepositoryLoadThread
Detailed Description
Encapsulates document manager, index, and field indexes. Provides access to collection for both IndexEnvironment and QueryEnvironment.
Member Typedef Documentation
typedef indri::atomic::ref_ptr<index_vector> indri::collection::Repository::index_state
typedef std::vector<indri::index::Index*> indri::collection::Repository::index_vector
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
LOAD_MINUTES
LOAD_MINUTE_FRACTION
Constructor & Destructor Documentation
indri::collection::Repository::Repository () [inline]
References _collection, _documentLoad, _lastThrashTime, _queryLoad, _readOnly, _thrashing, LOAD_MINUTE_FRACTION, and LOAD_MINUTES.
Referenced by _mergeClosedIndexes().
indri::collection::Repository::~Repository () [inline]
References close().
Member Function Documentation
void indri::collection::Repository::_addMemoryIndex () [private]
References _active, _addLock, _indexFields, _stateLock, _states, and indri::index::Index::documentMaximum().
Referenced by _merge(), _trim(), _write(), and open().
void indri::collection::Repository::_buildChain (indri::api::Parameters & parameters, indri::api::Parameters * options) [private]
References _parameters, _transformations, indri::api::Parameters::exists(), indri::parse::StemmerFactory::get(), and indri::api::Parameters::get().
Referenced by create(), open(), and openRead().
void indri::collection::Repository::_buildFields () [private]
References _fieldsForIndex(), _indexFields, _parameters, indri::api::Parameters::exists(), fields(), indri::api::Parameters::get(), indri::collection::Repository::Field::name, indri::collection::Repository::Field::numeric, indri::collection::Repository::Field::ordinal, indri::collection::Repository::Field::parental, indri::collection::Repository::Field::parserName, and indri::api::Parameters::size().
Referenced by create(), open(), and openRead().
void indri::collection::Repository::_checkpoint () [private]
References _collection, _deletedList, _path, _readOnly, _writeParameters(), indri::file::Path::combine(), indri::file::Path::exists(), indri::collection::CompressedCollection::reopen(), and indri::index::DeletedDocumentList::write().
Referenced by _merge(), _trim(), and _write().
void indri::collection::Repository::_cleanAndCreateDirectory (const std::string & path) [static, private]
References create(), indri::file::Path::exists(), and indri::file::Path::remove().
Referenced by create(), and merge().
void indri::collection::Repository::_closeIndexes () [private]
References _active, and _states.
Referenced by close().
void indri::collection::Repository::_closePriors () [private]
References _priorFiles.
Referenced by close().
indri::collection::Repository::Load indri::collection::Repository::_computeLoad (indri::atomic::value_type * loadArray) [private]
References indri::collection::Repository::Load::fifteen, indri::collection::Repository::Load::five, LOAD_MINUTE_FRACTION, and indri::collection::Repository::Load::one.
Referenced by documentLoad(), and queryLoad().
void indri::collection::Repository::_copyParameters (indri::api::Parameters & options) [private]
References _parameters, indri::api::Parameters::exists(), and indri::api::Parameters::set().
Referenced by create().
void indri::collection::Repository::_countDocumentAdd () [private]
References _documentLoad, and indri::atomic::increment().
Referenced by addDocument().
std::vector< std::string > indri::collection::Repository::_fieldNames (indri::api::Parameters & parameters) [static, private]
References indri::api::Parameters::exists(), fields(), and indri::api::Parameters::size().
Referenced by merge().
static std::vector<indri::index::Index::FieldDescription> indri::collection::Repository::_fieldsForIndex (const std::vector< Repository::Field > & _fields) [static, private]
Referenced by _buildFields(), and _mergeClosedIndexes().
void indri::collection::Repository::_incrementLoad () [private]
References _documentLoad, _queryLoad, LOAD_MINUTE_FRACTION, and LOAD_MINUTES.
Referenced by indri::collection::RepositoryLoadThread::work().
void indri::collection::Repository::_merge () [private]
merge all known indexes together
References _addMemoryIndex(), _checkpoint(), _readOnly, and indexes().
Referenced by _merge(), _trim(), and _write().
void indri::collection::Repository::_merge (index_state & state) [private]
References _memory, _merge(), _mergeFiles(), _mergeMemory(), _mergeStage(), _readOnly, and MERGE_FILE_LIMIT.
Referenced by indri::collection::RepositoryMaintenanceThread::work().
void indri::collection::Repository::_mergeBitmaps (const std::string & outputPath, const std::vector< std::string > & repositories, const std::vector< lemur::api::DOCID_T > & documentCounts) [static, private]
References indri::index::DeletedDocumentList::append(), indri::file::Path::combine(), deletedList(), indri::index::DeletedDocumentList::read(), and indri::index::DeletedDocumentList::write().
Referenced by merge().
void indri::collection::Repository::_mergeClosedIndexes (const std::string & outputPath, const std::vector< std::string > & repositories, const std::vector< indri::collection::Repository::Field > & indexFields, const std::vector< lemur::api::DOCID_T > & documentMaximums) [static, private]
References _deletedList, _fieldsForIndex(), indri::file::Path::combine(), create(), fields(), indexes(), openRead(), Repository(), and indri::index::IndexWriter::write().
Referenced by merge().
void indri::collection::Repository::_mergeCompressedCollections (const std::string & outputPath, const std::vector< std::string > & repositories, const std::vector< lemur::api::DOCID_T > & documentMaximums) [static, private]
References indri::collection::CompressedCollection::close(), collection(), indri::file::Path::combine(), create(), deletedList(), indri::collection::CompressedCollection::forwardFields(), indri::collection::CompressedCollection::openRead(), indri::index::DeletedDocumentList::read(), and indri::collection::CompressedCollection::reverseFields().
Referenced by merge().
unsigned int indri::collection::Repository::_mergeFiles (const std::vector< indri::index::Index * > & indexes) [private]
Referenced by _merge(), and indri::collection::RepositoryMaintenanceThread::work().
UINT64 indri::collection::Repository::_mergeMemory (const std::vector< indri::index::Index * > & indexes) [private]
References indri::index::Index::uniqueTermCount().
Referenced by _merge().
indri::index::Index * indri::collection::Repository::_mergeStage (index_state & state) [private]
References _deletedList, _indexCount, _indexFields, _path, _readOnly, _removeStates(), _statesContaining(), _swapState(), indri::file::Path::combine(), indri::atomic::ref_ptr< T >::get(), indexes(), indri::index::DiskIndex::open(), indri::index::DiskIndex::path(), indri::file::Path::remove(), and indri::thread::Thread::sleep().
Referenced by _merge().
void indri::collection::Repository::_openIndexes (indri::api::Parameters & params, const std::string & parentPath) [private]
References _active, _indexCount, _states, indri::api::Parameters::exists(), indri::api::Parameters::get(), indexes(), indri::index::DiskIndex::open(), and indri::api::Parameters::size().
Referenced by open(), and openRead().
void indri::collection::Repository::_openPriors (const std::string & path) [private]
References _priorFiles, indri::file::Path::combine(), indri::file::DirectoryIterator::end(), indri::file::Path::isDirectory(), and indri::file::File::openRead().
Referenced by open(), and openRead().
void indri::collection::Repository::_remove (const std::string & path) [private]
References indri::file::Path::remove().
void indri::collection::Repository::_removeStates (std::vector< index_state > & toRemove) [private]
References _states.
Referenced by _mergeStage().
void indri::collection::Repository::_setThrashing (bool flag) [private]
References _lastThrashTime, _thrashing, and indri::utility::IndriTimer::currentTime().
Referenced by indri::collection::RepositoryMaintenanceThread::work(), and indri::collection::RepositoryLoadThread::work().
void indri::collection::Repository::_startThreads () [private]
References _loadThread, _maintenanceThread, _memory, _readOnly, RepositoryLoadThread, RepositoryMaintenanceThread, and indri::thread::UtilityThread::start().
Referenced by create(), open(), and openRead().
bool indri::collection::Repository::_stateContains (index_state & state, std::vector< indri::index::Index * > & indexes) [private]
Referenced by _statesContaining().
std::vector< indri::collection::Repository::index_state > indri::collection::Repository::_statesContaining (std::vector< indri::index::Index * > & indexes) [private]
References _stateContains(), _stateLock, and _states.
Referenced by _mergeStage().
std::string indri::collection::Repository::_stemmerName (indri::api::Parameters & parameters) [static, private]
References indri::api::Parameters::get().
Referenced by merge().
void indri::collection::Repository::_stopThreads () [private]
References _loadThread, _maintenanceThread, indri::thread::UtilityThread::join(), and indri::thread::UtilityThread::signal().
Referenced by close().
void indri::collection::Repository::_swapState (std::vector< indri::index::Index * > & oldIndexes, indri::index::Index * newIndex) [private]
References _active, _stateLock, and _states.
Referenced by _mergeStage().
UINT64 indri::collection::Repository::_timeSinceThrashing () [private]
References _lastThrashTime, and indri::utility::IndriTimer::currentTime().
Referenced by indri::collection::RepositoryMaintenanceThread::work().
void indri::collection::Repository::_trim () [private]
merge together some of the more recent indexes
References _addMemoryIndex(), _checkpoint(), _merge(), _readOnly, and indexes().
Referenced by indri::collection::RepositoryMaintenanceThread::work().
void indri::collection::Repository::_write () [private]
write the active index to disk
References _addMemoryIndex(), _checkpoint(), _merge(), _readOnly, and indexes().
Referenced by indri::collection::RepositoryMaintenanceThread::work().
void indri::collection::Repository::_writeMergedManifest (const std::string & path, indri::api::Parameters & firstManifest) [static, private]
References indri::file::Path::combine(), indri::api::Parameters::set(), and indri::api::Parameters::writeFile().
Referenced by merge().
void indri::collection::Repository::_writeParameters (const std::string & path) [private]
References _active, _indexCount, _parameters, _stateLock, indri::api::Parameters::append(), indri::api::Parameters::clear(), indexes(), indri::index::DiskIndex::path(), indri::api::Parameters::set(), and indri::api::Parameters::writeFile().
Referenced by _checkpoint(), and close().
int indri::collection::Repository::addDocument (indri::api::ParsedDocument * document, bool inCollection = true)
add a parsed document to the repository.
Parameters:
document the document to add.
inCollection if true, add the document to the CompressedCollection.
References _active, _addLock, _collection, _countDocumentAdd(), _readOnly, _stateLock, _thrashing, _transformations, indri::collection::CompressedCollection::addDocument(), and indri::thread::Thread::sleep().
Referenced by indri::api::IndexEnvironment::addFile(), indri::api::IndexEnvironment::addParsedDocument(), indri::api::IndexEnvironment::addString(), and FieldModifier::processFields().
void indri::collection::Repository::close ()
Close the repository.
References _closeIndexes(), _closePriors(), _collection, _deletedList, _parameters, _path, _readOnly, _stopThreads(), _transformations, _writeParameters(), indri::api::Parameters::clear(), indri::file::Path::combine(), indri::utility::delete_vector_contents(), indri::file::Path::exists(), merge(), indri::index::DeletedDocumentList::write(), and write().
Referenced by _recoverRepository(), indri::api::IndexEnvironment::close(), compact_repository(), delete_document(), main(), makeEmpty(), merge(), FieldModifier::processFields(), and ~Repository().
indri::collection::CompressedCollection * indri::collection::Repository::collection ()
Returns:
the compressed document collection
References _collection.
Referenced by _mergeCompressedCollections(), _recoverRepository(), indri::api::IndexEnvironment::addFile(), indri::server::LocalQueryServer::document(), indri::server::LocalQueryServer::documentIDsFromMetadata(), indri::server::LocalQueryServer::documentMetadatum(), indri::server::LocalQueryServer::documentsFromMetadata(), indri::parse::PageRank::indexPageRank(), print_document_data(), print_document_id(), print_document_name(), print_document_text(), FieldModifier::processFields(), indri::parse::PageRank::writePriors(), indri::parse::PageRank::writeRanks(), and indri::parse::PageRank::writeRaw().
void indri::collection::Repository::compact ()
Compact the repository by removing all information about deleted documents from disk.
References _collection, _deletedList, indri::collection::CompressedCollection::compact(), and merge().
Referenced by indri::api::IndexEnvironment::compact(), and compact_repository().
void indri::collection::Repository::countQuery ()
Notify the repository that a query has happened.
References _queryLoad, and indri::atomic::increment().
Referenced by indri::infnet::InferenceNetwork::evaluate().
void indri::collection::Repository::create (const std::string & path, indri::api::Parameters * options = 0)
Create a new empty repository.
Parameters:
path the directory to create the repository in
options additional parameters
References _active, _buildChain(), _buildFields(), _cleanAndCreateDirectory(), _collection, _copyParameters(), _indexCount, _indexFields, _memory, _parameters, _path, _readOnly, _startThreads(), _states, indri::file::Path::combine(), indri::collection::CompressedCollection::create(), defaultMemory, indri::api::Parameters::exists(), indri::file::Path::exists(), indri::api::Parameters::get(), and indri::api::Parameters::size().
Referenced by _cleanAndCreateDirectory(), _mergeClosedIndexes(), _mergeCompressedCollections(), indri::api::IndexEnvironment::create(), makeEmpty(), and FieldModifier::processFields().
indri::index::DeletedDocumentList & indri::collection::Repository::deletedList ()
List of deleted documents in this repository.
References _deletedList.
Referenced by indri::infnet::InferenceNetwork::_evaluateIndex(), _mergeBitmaps(), _mergeCompressedCollections(), _recoverRepository(), indri::server::LocalQueryServer::documentCount(), and FieldModifier::processFields().
void indri::collection::Repository::deleteDocument (int documentID)
delete a document from the repository
Parameters:
documentID the internal ID of the document to delete
References _deletedList, and indri::index::DeletedDocumentList::markDeleted().
Referenced by delete_document(), and indri::api::IndexEnvironment::deleteDocument().
indri::collection::Repository::Load indri::collection::Repository::documentLoad ()
Returns the average number of documents added each minute in the last 1, 5 and 15 minutes.
References _computeLoad(), and _documentLoad.
Referenced by indri::collection::RepositoryMaintenanceThread::work().
bool indri::collection::Repository::exists (const std::string & path) [static]
Returns:
true if a valid Indri Repository resides in the named path false otherwise.
Parameters:
path the directory to open the repository from
References indri::file::Path::combine().
Referenced by main().
const std::vector< indri::collection::Repository::Field > & indri::collection::Repository::fields () const
Returns:
the indexed fields for this collection
Referenced by _buildFields(), _fieldNames(), _mergeClosedIndexes(), indri::server::LocalQueryServer::fieldList(), and merge().
indri::collection::Repository::index_state indri::collection::Repository::indexes ()
Indexes in this repository.
References _active.
Referenced by _merge(), _mergeClosedIndexes(), _mergeStage(), _openIndexes(), _recoverRepository(), _trim(), _write(), _writeParameters(), indri::infnet::InferenceNetworkBuilder::after(), indri::server::LocalQueryServer::documentCount(), indri::server::LocalQueryServer::documentLength(), indri::server::LocalQueryServer::documentStemCount(), indri::server::LocalQueryServer::documentVectors(), indri::infnet::InferenceNetwork::evaluate(), main(), indri::parse::PageRank::PageRank(), indri::server::LocalQueryServer::pathNames(), print_field_positions(), print_invfile(), print_repository_stats(), print_term_counts(), print_term_positions(), print_vocabulary(), FieldModifier::processFields(), indri::server::LocalQueryServer::stemCount(), indri::server::LocalQueryServer::stemFieldCount(), indri::server::LocalQueryServer::termCount(), indri::server::LocalQueryServer::termCountUnique(), indri::server::LocalQueryServer::termID(), indri::server::LocalQueryServer::termName(), validate(), indri::collection::RepositoryMaintenanceThread::work(), and indri::collection::RepositoryLoadThread::work().
void indri::collection::Repository::makeEmpty (const std::string & path) [static]
Make an empty repository directory on disk.
References close(), and create().
Referenced by merge().
void indri::collection::Repository::merge (const std::string & outputIndex, const std::vector< std::string > & inputIndexes) [static]
Merge two or more repositories together.
References _cleanAndCreateDirectory(), _fieldNames(), _mergeBitmaps(), _mergeClosedIndexes(), _mergeCompressedCollections(), _stemmerName(), _writeMergedManifest(), indri::index::DiskIndex::close(), close(), indri::file::Path::combine(), indri::index::DiskIndex::documentMaximum(), indri::api::Parameters::exists(), fields(), i64_to_string(), indri::api::Parameters::loadFile(), makeEmpty(), indri::index::DiskIndex::open(), openRead(), and indri::api::Parameters::size().
void indri::collection::Repository::merge ()
Merge all internal indexes together.
References _maintenanceThread, and indri::collection::RepositoryMaintenanceThread::merge().
Referenced by close(), compact(), and merge_repositories().
void indri::collection::Repository::open (const std::string & path, indri::api::Parameters * options = 0)
Open an existing repository.
Parameters:
path the directory to open the repository from
options additional parameters
References _addMemoryIndex(), _buildChain(), _buildFields(), _collection, _deletedList, _memory, _openIndexes(), _openPriors(), _parameters, _path, _readOnly, _startThreads(), _states, indri::file::Path::combine(), defaultMemory, indri::api::Parameters::get(), indri::api::Parameters::loadFile(), indri::collection::CompressedCollection::open(), and indri::index::DeletedDocumentList::read().
Referenced by _recoverRepository(), compact_repository(), delete_document(), and indri::api::IndexEnvironment::open().
void indri::collection::Repository::openRead (const std::string & path, indri::api::Parameters * options = 0)
Open an existing repository in read only mode.
Parameters:
path the directory to open the repository from
options additional parameters
References _buildChain(), _buildFields(), _collection, _deletedList, _memory, _openIndexes(), _openPriors(), _parameters, _path, _readOnly, _startThreads(), indri::file::Path::combine(), defaultMemory, indri::api::Parameters::get(), indri::api::Parameters::loadFile(), indri::collection::CompressedCollection::openRead(), and indri::index::DeletedDocumentList::read().
Referenced by _mergeClosedIndexes(), indri::api::QueryEnvironment::addIndex(), main(), merge(), indri::parse::PageRank::PageRank(), and FieldModifier::processFields().
indri::collection::PriorListIterator * indri::collection::Repository::priorListIterator (const std::string & priorName)
Return a prior iterator.
References _priorFiles.
Referenced by indri::infnet::InferenceNetwork::_indexChanged().
std::vector< std::string > indri::collection::Repository::priors () const
Returns:
the named priors list for this collection
References _priorFiles.
std::string indri::collection::Repository::processTerm (const std::string & term)
Process, possibly transforming, the given term
Parameters:
term the term to process
Returns:
the processed term
References _addLock, _transformations, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ParsedDocument::terms, indri::api::ParsedDocument::text, and indri::api::ParsedDocument::textLength.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), indri::lang::ContextSimpleCountCollectorCopier::after(), indri::server::LocalQueryServer::documentCount(), print_term_counts(), print_term_positions(), indri::server::LocalQueryServer::stemTerm(), indri::server::LocalQueryServer::termCount(), indri::server::LocalQueryServer::termFieldCount(), and indri::server::LocalQueryServer::termID().
indri::collection::Repository::Load indri::collection::Repository::queryLoad ()
Returns the average number of documents added each minute in the last 1, 5 and 15 minutes.
References _computeLoad(), and _queryLoad.
Referenced by indri::collection::RepositoryMaintenanceThread::work().
std::vector< std::string > indri::collection::Repository::tags () const
Returns:
the tags for this collection
void indri::collection::Repository::write ()
Write the most recent state out to disk.
References _maintenanceThread, and indri::collection::RepositoryMaintenanceThread::write().
Referenced by close().
Friends And Related Function Documentation
friend class RepositoryLoadThread [friend]
Referenced by _startThreads().
friend class RepositoryMaintenanceThread [friend]
Referenced by _startThreads().
Member Data Documentation
index_state indri::collection::Repository::_active [private]
Referenced by _addMemoryIndex(), _closeIndexes(), _openIndexes(), _swapState(), _writeParameters(), addDocument(), create(), and indexes().
indri::thread::Mutex indri::collection::Repository::_addLock [private]
Referenced by _addMemoryIndex(), addDocument(), and processTerm().
class CompressedCollection* indri::collection::Repository::_collection [private]
protects addDocument
Referenced by _checkpoint(), addDocument(), close(), collection(), compact(), create(), open(), openRead(), and Repository().
indri::index::DeletedDocumentList indri::collection::Repository::_deletedList [private]
Referenced by _checkpoint(), _mergeClosedIndexes(), _mergeStage(), close(), compact(), deletedList(), deleteDocument(), open(), and openRead().
indri::atomic::value_type indri::collection::Repository::_documentLoad[LOAD_MINUTES *LOAD_MINUTE_FRACTION] [private]
Referenced by _countDocumentAdd(), _incrementLoad(), documentLoad(), and Repository().
std::vector<Field> indri::collection::Repository::_fields [private]
int indri::collection::Repository::_indexCount [private]
Referenced by _mergeStage(), _openIndexes(), _writeParameters(), and create().
std::vector<indri::index::Index::FieldDescription> indri::collection::Repository::_indexFields [private]
Referenced by _addMemoryIndex(), _buildFields(), _mergeStage(), and create().
UINT64 indri::collection::Repository::_lastThrashTime [private]
Referenced by _setThrashing(), _timeSinceThrashing(), and Repository().
class RepositoryLoadThread* indri::collection::Repository::_loadThread [private]
Referenced by _startThreads(), and _stopThreads().
volatile bool indri::collection::Repository::_loadThreadRunning [private]
volatile bool indri::collection::Repository::_maintenanceRunning [private]
class RepositoryMaintenanceThread* indri::collection::Repository::_maintenanceThread [private]
Referenced by _startThreads(), _stopThreads(), merge(), and write().
INT64 indri::collection::Repository::_memory [private]
Referenced by _merge(), _startThreads(), create(), open(), and openRead().
indri::api::Parameters indri::collection::Repository::_parameters [private]
Referenced by _buildChain(), _buildFields(), _copyParameters(), _writeParameters(), close(), create(), open(), and openRead().
std::string indri::collection::Repository::_path [private]
Referenced by _checkpoint(), _mergeStage(), close(), create(), open(), and openRead().
std::map<std::string, indri::file::File*> indri::collection::Repository::_priorFiles [private]
Referenced by _closePriors(), _openPriors(), priorListIterator(), and priors().
indri::atomic::value_type indri::collection::Repository::_queryLoad[LOAD_MINUTES *LOAD_MINUTE_FRACTION] [private]
Referenced by _incrementLoad(), countQuery(), queryLoad(), and Repository().
bool indri::collection::Repository::_readOnly [private]
Referenced by _checkpoint(), _merge(), _mergeStage(), _startThreads(), _trim(), _write(), addDocument(), close(), create(), open(), openRead(), and Repository().
indri::thread::Mutex indri::collection::Repository::_stateLock [private]
Referenced by _addMemoryIndex(), _statesContaining(), _swapState(), _writeParameters(), and addDocument().
std::vector<index_state> indri::collection::Repository::_states [private]
protects against state changes
Referenced by _addMemoryIndex(), _closeIndexes(), _openIndexes(), _removeStates(), _statesContaining(), _swapState(), create(), and open().
volatile bool indri::collection::Repository::_thrashing [private]
Referenced by _setThrashing(), addDocument(), and Repository().
std::vector<indri::parse::Transformation*> indri::collection::Repository::_transformations [private]
Referenced by _buildChain(), addDocument(), close(), and processTerm().
The documentation for this class was generated from the following files:
Repository.hpp
Repository.cpp