Indri: indri::infnet::FieldEqualsNode Class Reference
indri::infnet::FieldEqualsNode Class Reference
#include <FieldEqualsNode.hpp>
Public Member Functions
FieldEqualsNode (const std::string &name, class FieldIteratorNode *iterator, INT64 constant)
void prepare (lemur::api::DOCID_T documentID)
sets up as much as we can with just the document ID
indri::utility::greedy_vector
< indri::index::Extent > & extents ()
returns a list of intervals describing positions of children
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
const std::string & getName () const
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
annotate any results from this node from position begin to position end
Private Attributes
class FieldIteratorNode * _field
indri::utility::greedy_vector
< indri::index::Extent > _extents
INT64 _constant
std::string _name
Constructor & Destructor Documentation
indri::infnet::FieldEqualsNode::FieldEqualsNode (const std::string & name, class FieldIteratorNode * iterator, INT64 constant)
References _constant, _field, and _name.
Member Function Documentation
void indri::infnet::FieldEqualsNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
annotate any results from this node from position begin to position end
Implements indri::infnet::ListIteratorNode.
References _extents, and indri::infnet::Annotator::addMatches().
indri::utility::greedy_vector< indri::index::Extent > & indri::infnet::FieldEqualsNode::extents () [virtual]
returns a list of intervals describing positions of children
Implements indri::infnet::ListIteratorNode.
References _extents.
Referenced by prepare().
const std::string & indri::infnet::FieldEqualsNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
void indri::infnet::FieldEqualsNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
lemur::api::DOCID_T indri::infnet::FieldEqualsNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _field, and indri::infnet::FieldIteratorNode::nextCandidateDocument().
void indri::infnet::FieldEqualsNode::prepare (lemur::api::DOCID_T documentID) [virtual]
sets up as much as we can with just the document ID
Implements indri::infnet::ListIteratorNode.
References _constant, _extents, _field, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::infnet::FieldIteratorNode::extents(), extents(), indri::infnet::ListIteratorNode::initpointer(), indri::infnet::FieldIteratorNode::numbers(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
INT64 indri::infnet::FieldEqualsNode::_constant [private]
Referenced by FieldEqualsNode(), and prepare().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::FieldEqualsNode::_extents [private]
Referenced by annotate(), extents(), and prepare().
class FieldIteratorNode* indri::infnet::FieldEqualsNode::_field [private]
Referenced by FieldEqualsNode(), nextCandidateDocument(), and prepare().
std::string indri::infnet::FieldEqualsNode::_name [private]
Referenced by FieldEqualsNode(), and getName().
The documentation for this class was generated from the following files:
FieldEqualsNode.hpp
FieldEqualsNode.cpp