Indri: indri::atomic::ref_ptr< T > Class Template Reference
indri::atomic::ref_ptr< T > Class Template Reference
#include <ref_ptr.hpp>
Classes
struct object_ref
Public Member Functions
ref_ptr ()
~ref_ptr ()
ref_ptr (const my_type &other)
ref_ptr (T *object)
my_type & operator= (T *object)
my_type & operator= (const ref_ptr &other)
bool operator== (T *other)
bool operator== (ref_ptr &other)
atomic::value_type references ()
T & operator* ()
T * operator-> ()
T * get ()
Private Types
typedef ref_ptr< T > my_type
Private Member Functions
void _removeRef ()
void _addRef ()
my_type & _refAssign (const my_type &other)
Private Attributes
object_ref< T > * _ref
template<class T>
class indri::atomic::ref_ptr< T >
Member Typedef Documentation
template<class T> typedef ref_ptr<T> indri::atomic::ref_ptr< T >::my_type [private]
Constructor & Destructor Documentation
template<class T> indri::atomic::ref_ptr< T >::ref_ptr () [inline]
template<class T> indri::atomic::ref_ptr< T >::~ref_ptr () [inline]
template<class T> indri::atomic::ref_ptr< T >::ref_ptr (const my_type & other) [inline]
template<class T> indri::atomic::ref_ptr< T >::ref_ptr (T * object) [inline]
Member Function Documentation
template<class T> void indri::atomic::ref_ptr< T >::_addRef () [inline, private]
Referenced by indri::atomic::ref_ptr< index_vector >::_refAssign().
template<class T> my_type& indri::atomic::ref_ptr< T >::_refAssign (const my_type & other) [inline, private]
Referenced by indri::atomic::ref_ptr< index_vector >::operator=(), and indri::atomic::ref_ptr< index_vector >::ref_ptr().
template<class T> void indri::atomic::ref_ptr< T >::_removeRef () [inline, private]
Referenced by indri::atomic::ref_ptr< index_vector >::_refAssign(), indri::atomic::ref_ptr< index_vector >::operator=(), and indri::atomic::ref_ptr< index_vector >::~ref_ptr().
template<class T> T* indri::atomic::ref_ptr< T >::get () [inline]
Referenced by indri::collection::Repository::_mergeStage().
template<class T> T& indri::atomic::ref_ptr< T >::operator* () [inline]
template<class T> T* indri::atomic::ref_ptr< T >::operator-> () [inline]
template<class T> my_type& indri::atomic::ref_ptr< T >::operator= (const ref_ptr< T > & other) [inline]
template<class T> my_type& indri::atomic::ref_ptr< T >::operator= (T * object) [inline]
template<class T> bool indri::atomic::ref_ptr< T >::operator== (ref_ptr< T > & other) [inline]
template<class T> bool indri::atomic::ref_ptr< T >::operator== (T * other) [inline]
template<class T> atomic::value_type indri::atomic::ref_ptr< T >::references () [inline]
Member Data Documentation
template<class T> object_ref<T>* indri::atomic::ref_ptr< T >::_ref [mutable, private]
Referenced by indri::atomic::ref_ptr< index_vector >::_addRef(), indri::atomic::ref_ptr< index_vector >::_refAssign(), indri::atomic::ref_ptr< index_vector >::_removeRef(), indri::atomic::ref_ptr< index_vector >::get(), indri::atomic::ref_ptr< index_vector >::operator*(), indri::atomic::ref_ptr< index_vector >::operator->(), indri::atomic::ref_ptr< index_vector >::operator=(), indri::atomic::ref_ptr< index_vector >::operator==(), indri::atomic::ref_ptr< index_vector >::ref_ptr(), and indri::atomic::ref_ptr< index_vector >::references().
The documentation for this class was generated from the following file:
ref_ptr.hpp