Indri: indri::infnet::FixedPassageNode Class Reference
indri::infnet::FixedPassageNode Class Reference
#include <FixedPassageNode.hpp>
Public Member Functions
FixedPassageNode (const std::string &name, BeliefNode *child, int windowSize, int increment)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
bool hasMatch (lemur::api::DOCID_T documentID)
const std::string & getName () const
virtual void setSiblingsFlag (int f)
Private Member Functions
void _addSubextents (const indri::index::Extent &extent)
void _buildSubextents (const indri::index::Extent &extent)
void _buildSubextents (const indri::utility::greedy_vector< indri::index::Extent > &extents)
Private Attributes
BeliefNode * _child
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
indri::utility::greedy_vector
< indri::index::Extent > _subextents
std::string _name
int _windowSize
int _increment
Constructor & Destructor Documentation
indri::infnet::FixedPassageNode::FixedPassageNode (const std::string & name, BeliefNode * child, int windowSize, int increment)
Member Function Documentation
void indri::infnet::FixedPassageNode::_addSubextents (const indri::index::Extent & extent) [private]
References _increment, _subextents, _windowSize, indri::index::Extent::begin, indri::index::Extent::end, and indri::utility::greedy_vector< _Type, _Count >::push_back().
Referenced by _buildSubextents().
void indri::infnet::FixedPassageNode::_buildSubextents (const indri::utility::greedy_vector< indri::index::Extent > & extents) [private]
References _addSubextents(), _subextents, indri::utility::greedy_vector< _Type, _Count >::clear(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::FixedPassageNode::_buildSubextents (const indri::index::Extent & extent) [private]
References _addSubextents(), _subextents, and indri::utility::greedy_vector< _Type, _Count >::clear().
Referenced by annotate(), hasMatch(), and score().
void indri::infnet::FixedPassageNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _buildSubextents(), _child, _subextents, indri::infnet::Annotator::add(), indri::infnet::BeliefNode::annotate(), indri::infnet::BeliefNode::hasMatch(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::FixedPassageNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
bool indri::infnet::FixedPassageNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::hasMatch().
const indri::utility::greedy_vector< bool > & indri::infnet::FixedPassageNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _buildSubextents(), _child, _matches, _subextents, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::infnet::BeliefNode::hasMatch(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::FixedPassageNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::FixedPassageNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_TINY_SCORE.
double indri::infnet::FixedPassageNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_HUGE_SCORE.
lemur::api::DOCID_T indri::infnet::FixedPassageNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _child, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::FixedPassageNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _buildSubextents(), _child, _scores, _subextents, indri::api::ScoredExtentResult::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::api::ScoredExtentResult::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::BeliefNode::hasMatch(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::infnet::BeliefNode::score(), and indri::utility::greedy_vector< _Type, _Count >::size().
virtual void indri::infnet::FixedPassageNode::setSiblingsFlag (int f) [inline, virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _child, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
BeliefNode* indri::infnet::FixedPassageNode::_child [private]
Referenced by annotate(), hasMatch(), nextCandidateDocument(), score(), and setSiblingsFlag().
int indri::infnet::FixedPassageNode::_increment [private]
Referenced by _addSubextents().
indri::utility::greedy_vector<bool> indri::infnet::FixedPassageNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::FixedPassageNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::FixedPassageNode::_scores [private]
Referenced by score().
indri::utility::greedy_vector<indri::index::Extent> indri::infnet::FixedPassageNode::_subextents [private]
Referenced by _addSubextents(), _buildSubextents(), annotate(), hasMatch(), and score().
int indri::infnet::FixedPassageNode::_windowSize [private]
Referenced by _addSubextents().
The documentation for this class was generated from the following files:
FixedPassageNode.hpp
FixedPassageNode.cpp