Indri: Indri::IndexStatus Class Reference
Indri::IndexStatus Class Reference
Public Types
enum action_code {
FileOpen, FileSkip, FileError, FileClose,
DocumentCount
}
Public Member Functions
virtual void Dispose ()
virtual void status (int code, string documentPath, string error, int documentsIndexed, int documentsSeen)
IndexStatus ()
delegate void SwigDelegateIndexStatus_0 (int code, string documentPath, string error, int documentsIndexed, int documentsSeen)
Protected Attributes
bool swigCMemOwn
Private Member Functions
internal IndexStatus (IntPtr cPtr, bool cMemoryOwn)
~IndexStatus ()
void SwigDirectorConnect ()
bool SwigDerivedClassHasMethod (string methodName, Type[] methodTypes)
void SwigDirectorstatus (int code, string documentPath, string error, int documentsIndexed, int documentsSeen)
Static Private Member Functions
static internal HandleRef getCPtr (IndexStatus obj)
Private Attributes
HandleRef swigCPtr
SwigDelegateIndexStatus_0 swigDelegate0
Static Private Attributes
static Type[] swigMethodTypes0 = new Type[] { typeof(int), typeof(string), typeof(string), typeof(int), typeof(int) }
Member Enumeration Documentation
enum Indri::IndexStatus::action_code
Enumerator:
FileOpen
FileSkip
FileError
FileClose
DocumentCount
Constructor & Destructor Documentation
internal Indri::IndexStatus::IndexStatus (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::IndexStatus::~IndexStatus () [inline, private]
References Dispose().
Indri::IndexStatus::IndexStatus () [inline]
References SwigDirectorConnect().
Member Function Documentation
virtual void Indri::IndexStatus::Dispose () [inline, virtual]
References swigCMemOwn, and swigCPtr.
Referenced by ~IndexStatus().
static internal HandleRef Indri::IndexStatus::getCPtr (IndexStatus obj) [inline, static, private]
References swigCPtr.
virtual void Indri::IndexStatus::status (int code, string documentPath, string error, int documentsIndexed, int documentsSeen) [inline, virtual]
References swigCPtr.
Referenced by SwigDirectorstatus().
delegate void Indri::IndexStatus::SwigDelegateIndexStatus_0 (int code, string documentPath, string error, int documentsIndexed, int documentsSeen)
Referenced by SwigDirectorConnect().
bool Indri::IndexStatus::SwigDerivedClassHasMethod (string methodName, Type[] methodTypes) [inline, private]
Referenced by SwigDirectorConnect().
void Indri::IndexStatus::SwigDirectorConnect () [inline, private]
References swigCPtr, swigDelegate0, SwigDelegateIndexStatus_0(), SwigDerivedClassHasMethod(), SwigDirectorstatus(), and swigMethodTypes0.
Referenced by IndexStatus().
void Indri::IndexStatus::SwigDirectorstatus (int code, string documentPath, string error, int documentsIndexed, int documentsSeen) [inline, private]
References status().
Referenced by SwigDirectorConnect().
Member Data Documentation
bool Indri::IndexStatus::swigCMemOwn [protected]
Referenced by Dispose(), and IndexStatus().
HandleRef Indri::IndexStatus::swigCPtr [private]
Referenced by Dispose(), getCPtr(), IndexStatus(), status(), and SwigDirectorConnect().
SwigDelegateIndexStatus_0 Indri::IndexStatus::swigDelegate0 [private]
Referenced by SwigDirectorConnect().
Type [] Indri::IndexStatus::swigMethodTypes0 = new Type[] { typeof(int), typeof(string), typeof(string), typeof(int), typeof(int) } [static, private]
Referenced by SwigDirectorConnect().
The documentation for this class was generated from the following file:
IndexStatus.cs