Indri: indri::lang::ContextCounterNode Class Reference
indri::lang::ContextCounterNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ContextCounterNode (RawExtentNode *raw, RawExtentNode *context)
ContextCounterNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
RawExtentNode * getContext ()
RawExtentNode * getRawExtent ()
void setRawExtent (RawExtentNode *rawExtent)
void setContext (RawExtentNode *context)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
bool hasCounts () const
bool hasContextSize () const
double getOccurrences () const
double getContextSize () const
int getDocumentOccurrences () const
int getDocumentCount () const
void setContextSize (double contextSize)
void setCounts (double occurrences, double contextSize, int documentOccurrences, int documentCount)
Private Attributes
RawExtentNode * _raw
RawExtentNode * _context
bool _hasCounts
bool _hasContextSize
double _occurrences
double _contextSize
int _documentOccurrences
int _documentCount
Constructor & Destructor Documentation
indri::lang::ContextCounterNode::ContextCounterNode (RawExtentNode * raw, RawExtentNode * context) [inline]
References _context, and _raw.
Referenced by copy().
indri::lang::ContextCounterNode::ContextCounterNode (Unpacker & unpacker) [inline]
References _context, _contextSize, _documentCount, _documentOccurrences, _hasContextSize, _hasCounts, _occurrences, _raw, indri::lang::Unpacker::getBoolean(), indri::lang::Unpacker::getDouble(), indri::lang::Unpacker::getInteger(), and indri::lang::Unpacker::getRawExtentNode().
Member Function Documentation
Node* indri::lang::ContextCounterNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, indri::lang::Copier::after(), indri::lang::Copier::before(), ContextCounterNode(), and indri::lang::Node::copy().
RawExtentNode* indri::lang::ContextCounterNode::getContext () [inline]
References _context.
Referenced by indri::infnet::InferenceNetworkBuilder::after(), indri::lang::FrequencyListCopier::before(), and indri::lang::ContextSimpleCountCollectorCopier::SubtreeWalker::before().
double indri::lang::ContextCounterNode::getContextSize () const [inline]
References _contextSize.
int indri::lang::ContextCounterNode::getDocumentCount () const [inline]
References _documentCount.
int indri::lang::ContextCounterNode::getDocumentOccurrences () const [inline]
References _documentOccurrences.
double indri::lang::ContextCounterNode::getOccurrences () const [inline]
References _occurrences.
RawExtentNode* indri::lang::ContextCounterNode::getRawExtent () [inline]
References _raw.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
bool indri::lang::ContextCounterNode::hasContextSize () const [inline]
References _hasContextSize.
bool indri::lang::ContextCounterNode::hasCounts () const [inline]
References _hasCounts.
UINT64 indri::lang::ContextCounterNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
void indri::lang::ContextCounterNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _context, _contextSize, _documentCount, _documentOccurrences, _hasContextSize, _hasCounts, _occurrences, _raw, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ContextCounterNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, and indri::lang::Node::queryText().
void indri::lang::ContextCounterNode::setContext (RawExtentNode * context) [inline]
References _context.
void indri::lang::ContextCounterNode::setContextSize (double contextSize) [inline]
References _contextSize, and _hasContextSize.
Referenced by setCounts().
void indri::lang::ContextCounterNode::setCounts (double occurrences, double contextSize, int documentOccurrences, int documentCount) [inline]
References _documentCount, _documentOccurrences, _hasCounts, _occurrences, and setContextSize().
void indri::lang::ContextCounterNode::setRawExtent (RawExtentNode * rawExtent) [inline]
References _raw.
std::string indri::lang::ContextCounterNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ContextCounterNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Referenced by indri::lang::ContextSimpleCountCollectorCopier::after().
Member Data Documentation
RawExtentNode* indri::lang::ContextCounterNode::_context [private]
Referenced by ContextCounterNode(), copy(), getContext(), pack(), queryText(), setContext(), and walk().
double indri::lang::ContextCounterNode::_contextSize [private]
Referenced by ContextCounterNode(), getContextSize(), pack(), and setContextSize().
int indri::lang::ContextCounterNode::_documentCount [private]
Referenced by ContextCounterNode(), getDocumentCount(), pack(), and setCounts().
int indri::lang::ContextCounterNode::_documentOccurrences [private]
Referenced by ContextCounterNode(), getDocumentOccurrences(), pack(), and setCounts().
bool indri::lang::ContextCounterNode::_hasContextSize [private]
Referenced by ContextCounterNode(), hasContextSize(), pack(), and setContextSize().
bool indri::lang::ContextCounterNode::_hasCounts [private]
Referenced by ContextCounterNode(), hasCounts(), pack(), and setCounts().
double indri::lang::ContextCounterNode::_occurrences [private]
Referenced by ContextCounterNode(), getOccurrences(), pack(), and setCounts().
RawExtentNode* indri::lang::ContextCounterNode::_raw [private]
Referenced by ContextCounterNode(), copy(), getRawExtent(), pack(), queryText(), setRawExtent(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp