Indri: indri::infnet::WeightedSumNode Class Reference
indri::infnet::WeightedSumNode Class Reference
#include <WeightedSumNode.hpp>
Public Member Functions
WeightedSumNode (const std::string &name)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
void addChild (double weight, BeliefNode *child)
const std::string & getName () const
virtual void setSiblingsFlag (int f)
Private Attributes
std::vector< BeliefNode * > _children
std::vector< double > _weights
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::WeightedSumNode::WeightedSumNode (const std::string & name)
Member Function Documentation
void indri::infnet::WeightedSumNode::addChild (double weight, BeliefNode * child)
References _children, _weights, and indri::infnet::BeliefNode::setSiblingsFlag().
Referenced by indri::infnet::InferenceNetworkBuilder::after().
void indri::infnet::WeightedSumNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _children, and indri::infnet::Annotator::add().
const std::string & indri::infnet::WeightedSumNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::WeightedSumNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::WeightedSumNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _children.
void indri::infnet::WeightedSumNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::WeightedSumNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children, and _weights.
double indri::infnet::WeightedSumNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References _children, and _weights.
lemur::api::DOCID_T indri::infnet::WeightedSumNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::WeightedSumNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
Implements indri::infnet::BeliefNode.
References _children, _scores, _weights, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::WeightedSumNode::setSiblingsFlag (int f) [virtual]
sets the siblings flag (and counter) if the belief node has siblings
Reimplemented from indri::infnet::BeliefNode.
References _children.
Member Data Documentation
std::vector<BeliefNode*> indri::infnet::WeightedSumNode::_children [private]
Referenced by addChild(), annotate(), hasMatch(), maximumBackgroundScore(), maximumScore(), nextCandidateDocument(), score(), and setSiblingsFlag().
indri::utility::greedy_vector<bool> indri::infnet::WeightedSumNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::WeightedSumNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::WeightedSumNode::_scores [private]
Referenced by score().
std::vector<double> indri::infnet::WeightedSumNode::_weights [private]
Referenced by addChild(), maximumBackgroundScore(), maximumScore(), and score().
The documentation for this class was generated from the following files:
WeightedSumNode.hpp
WeightedSumNode.cpp