Indri: lemurproject::indri::ui::RetUI Class Reference
lemurproject::indri::ui::RetUI Class Reference
Inherits javax::swing::JPanel.
Classes
class DocTableListener
class QueryTreeListener
class UIQueryNode
Public Member Functions
RetUI ()
void init ()
void actionPerformed (ActionEvent e)
void removeIndex ()
void openIndex ()
void openServer ()
void runQuestion ()
void altgetDocText ()
void getDocText ()
void getDocHtml ()
void error (String s)
Static Public Member Functions
static void main (String[] args)
Static Protected Member Functions
static ImageIcon createImageIcon (String path)
Package Attributes
JButton go
JButton stop
JButton scoreDisplay
JLabel status
JLabel progress
JTextField query
JTextField numDocs
JTable answerAll
JFrame docTextFrame
JTextPane docTextPane
JFrame docHtmlFrame
JTextPane docHtmlPane
JTree docQueryTree
QueryEnvironment env
Map annotations = null
QueryAnnotation results = null
ScoredExtentResult[] scored = null
ParsedDocument currentParsedDoc = null
int currentDocId = 0
String[] names = null
String[] titles = null
int[] docids = null
int currentDoc = -1
int maxDocs = 10
boolean envInit = false
String wordProg
String powerpointProg
String acroreadProg
boolean showScores = false
volatile Thread getDocTextThread
volatile Thread getDocHtmlThread
volatile Thread runQuestionThread
Private Member Functions
void clearAll ()
void setPaths ()
void makeHelp ()
void makeDocTextFrame ()
void makeDocHtmlFrame ()
void spawnViewer ()
void highlight (DefaultMutableTreeNode query) throws InterruptedException
void clearHighlight (StyledDocument myDoc, MutableAttributeSet highlight)
void highlight (UIQueryNode q, StyledDocument myDoc, MutableAttributeSet highlight) throws InterruptedException
DefaultTreeModel makeTreeModel (QueryAnnotationNode query)
DefaultMutableTreeNode makeChildNode (QueryAnnotationNode query)
Thread blinker (final String s1, final String s2)
String trim (String s)
JTable makeDocsTable ()
JMenuItem makeMenuItem (String label)
Static Private Member Functions
static void createAndShowGUI ()
Private Attributes
final JFileChooser fc
JFrame helpFrame
JList documents
DefaultListModel documentsModel
JList indexes
DefaultListModel indexesModel
volatile boolean blinking = false
Static Private Attributes
static final String aboutText
static final String helpFile = "properties/IndriRetrieval.html"
static final String iconFile = "properties/lemur_head_32.gif"
static final Color lightYellow = new Color(255, 255, 224)
static final Color navyBlue = new Color(0, 0, 128)
static final Color linen = new Color(250, 240, 230)
static Cursor wait = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)
static Cursor def = Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)
Detailed Description
User interface for indri retrieval.
Author:
David Fisher
Version:
1.0
Constructor & Destructor Documentation
lemurproject::indri::ui::RetUI::RetUI () [inline]
Initialize the query environment and indexes model.
References env, getDocHtmlThread, getDocTextThread, indexesModel, and runQuestionThread.
Referenced by createAndShowGUI().
Member Function Documentation
void lemurproject::indri::ui::RetUI::actionPerformed (ActionEvent e) [inline]
References aboutText, answerAll, clearAll(), createImageIcon(), lemurproject::indri::ui::DocsTableModel::displayScores(), envInit, error(), getDocHtml(), go, helpFrame, iconFile, openIndex(), openServer(), query, removeIndex(), runQuestion(), scoreDisplay, showScores, spawnViewer(), and status.
void lemurproject::indri::ui::RetUI::altgetDocText () [inline]
Populate the document text frame with the selected document. Highlight the document based on query matches.
References answerAll, currentDocId, currentParsedDoc, def, docids, docQueryTree, docTextFrame, docTextPane, lemurproject::indri::QueryEnvironment::documents(), env, getDocTextThread, highlight(), names, query, status, lemurproject::indri::ParsedDocument::text, and wait.
Thread lemurproject::indri::ui::RetUI::blinker (final String s1, final String s2) [inline, private]
Blink a pair of messages on the status line
Parameters:
s1 The first message to display
s2 The second message to display
Returns:
The Thread doing the blinking
References blinking, and status.
Referenced by runQuestion().
void lemurproject::indri::ui::RetUI::clearAll () [inline, private]
Clear everything
References answerAll, lemurproject::indri::ui::DocsTableModel::clear(), docHtmlFrame, docHtmlPane, docQueryTree, docTextFrame, docTextPane, query, and status.
Referenced by actionPerformed().
void lemurproject::indri::ui::RetUI::clearHighlight (StyledDocument myDoc, MutableAttributeSet highlight) [inline, private]
Clear all highlighting markup in a styled document.
Parameters:
myDoc The StyledDocument to highlight
highlight The highlighting attributes
Referenced by highlight().
static void lemurproject::indri::ui::RetUI::createAndShowGUI () [inline, static, private]
Make the containing frame, menubar, and an instance of RetUI. Initialize.
References createImageIcon(), iconFile, init(), lightYellow, makeMenuItem(), navyBlue, and RetUI().
Referenced by main().
static ImageIcon lemurproject::indri::ui::RetUI::createImageIcon (String path) [inline, static, protected]
Returns an ImageIcon, or null if the path was invalid.
Parameters:
path the image file to load.
Returns:
an ImageIcon, or null if the path was invalid.
Referenced by actionPerformed(), createAndShowGUI(), makeDocHtmlFrame(), makeDocTextFrame(), and makeHelp().
void lemurproject::indri::ui::RetUI::error (String s) [inline]
Display an error message in the progress label.
Parameters:
s The error message to display.
References progress.
Referenced by actionPerformed(), getDocHtml(), getDocText(), openIndex(), openServer(), runQuestion(), and spawnViewer().
void lemurproject::indri::ui::RetUI::getDocHtml () [inline]
Populate a document text frame with html -- no highlighting.
References answerAll, lemurproject::indri::ParsedDocument::content, currentDocId, currentParsedDoc, def, docHtmlFrame, docHtmlPane, docids, lemurproject::indri::QueryEnvironment::documents(), env, error(), names, query, status, and wait.
Referenced by actionPerformed().
void lemurproject::indri::ui::RetUI::getDocText () [inline]
References answerAll, currentDocId, currentParsedDoc, def, docids, docQueryTree, docTextFrame, docTextPane, lemurproject::indri::QueryEnvironment::documents(), env, error(), getDocTextThread, highlight(), names, query, status, lemurproject::indri::ParsedDocument::text, and wait.
Referenced by lemurproject::indri::ui::RetUI::DocTableListener::valueChanged().
void lemurproject::indri::ui::RetUI::highlight (UIQueryNode q, StyledDocument myDoc, MutableAttributeSet highlight) throws InterruptedException [inline, private]
Highlight the current document in the document text pane with respect to the given query node.
Parameters:
q The query node to highlight extents for
myDoc The StyledDocument to highlight
highlight The highlighting attributes
References annotations, lemurproject::indri::ScoredExtentResult::begin, currentDocId, currentParsedDoc, lemurproject::indri::ScoredExtentResult::end, highlight(), lemurproject::indri::QueryAnnotationNode::name, and lemurproject::indri::ParsedDocument::positions.
void lemurproject::indri::ui::RetUI::highlight (DefaultMutableTreeNode query) throws InterruptedException [inline, private]
Insert highlighting markup into a styled document, starting from the given node of the query tree. If the node is the root of the tree, recurse through the entire tree.
Parameters:
query The query tree node to highlight
References clearHighlight(), docQueryTree, docTextPane, lemurproject::indri::ui::RetUI::UIQueryNode::getNode(), linen, query, and lemurproject::indri::QueryAnnotationNode::type.
Referenced by altgetDocText(), getDocText(), highlight(), and lemurproject::indri::ui::RetUI::QueryTreeListener::valueChanged().
void lemurproject::indri::ui::RetUI::init () [inline]
Create the gui elements, including the help frame.
References answerAll, envInit, go, indexes, indexesModel, lightYellow, linen, makeDocHtmlFrame(), makeDocsTable(), makeDocTextFrame(), makeHelp(), maxDocs, navyBlue, numDocs, progress, query, scoreDisplay, setPaths(), status, and stop.
Referenced by createAndShowGUI().
static void lemurproject::indri::ui::RetUI::main (String[] args) [inline, static]
Fire it up.
Parameters:
args ignored
References createAndShowGUI().
DefaultMutableTreeNode lemurproject::indri::ui::RetUI::makeChildNode (QueryAnnotationNode query) [inline, private]
Make a DefaultMutableTreeNode out of a QueryAnnotationNode. Recursively insert all children of the query into the tree.
Parameters:
query The QueryAnnotationNode to insert into the tree.
Returns:
a DefaultMutableTreeNode for this query.
References lemurproject::indri::QueryAnnotationNode::children.
Referenced by makeTreeModel().
void lemurproject::indri::ui::RetUI::makeDocHtmlFrame () [inline, private]
Make the frame for displaying html documents
References createImageIcon(), docHtmlFrame, docHtmlPane, iconFile, and linen.
Referenced by init().
JTable lemurproject::indri::ui::RetUI::makeDocsTable () [inline, private]
Make a JTable and associated DocsTableModel for containing query result sets.
Returns:
The JTable with its model and listener initialized.
References names, and showScores.
Referenced by init().
void lemurproject::indri::ui::RetUI::makeDocTextFrame () [inline, private]
Make the frame for displaying highlighted retrieved documents with both document text and the query tree.
References createImageIcon(), docQueryTree, docTextFrame, docTextPane, iconFile, lightYellow, linen, makeMenuItem(), and navyBlue.
Referenced by init().
void lemurproject::indri::ui::RetUI::makeHelp () [inline, private]
Create the frame that shows the help file and render the html. Saves time when the user opens the help.
References createImageIcon(), helpFile, helpFrame, and iconFile.
Referenced by init().
JMenuItem lemurproject::indri::ui::RetUI::makeMenuItem (String label) [inline, private]
Make a menu item with appropriate colors and this</end> as its listener.
Parameters:
label The label for the menu item
Returns:
The menu item
References lightYellow, and navyBlue.
Referenced by createAndShowGUI(), and makeDocTextFrame().
DefaultTreeModel lemurproject::indri::ui::RetUI::makeTreeModel (QueryAnnotationNode query) [inline, private]
Create a TreeModel from a QueryAnnotationNode.
Parameters:
query The QueryAnnotationNode to use as the root of the tree
Returns:
A DefaultTreeModel rooted in query
References makeChildNode().
Referenced by runQuestion().
void lemurproject::indri::ui::RetUI::openIndex () [inline]
Present a file chooser to select an index to open. Open the index in the query environment.
References lemurproject::indri::QueryEnvironment::addIndex(), env, envInit, error(), fc, and indexesModel.
Referenced by actionPerformed().
void lemurproject::indri::ui::RetUI::openServer () [inline]
Present an input dialog to obtain a hostname and optional port number. Open the given server in the query environment.
References lemurproject::indri::QueryEnvironment::addServer(), env, envInit, error(), and indexesModel.
Referenced by actionPerformed().
void lemurproject::indri::ui::RetUI::removeIndex () [inline]
Remove the selected index from the list.
References env, indexes, indexesModel, lemurproject::indri::QueryEnvironment::removeIndex(), and lemurproject::indri::QueryEnvironment::removeServer().
Referenced by actionPerformed().
void lemurproject::indri::ui::RetUI::runQuestion () [inline]
Run the given query in a separate thread.
References annotations, answerAll, blinker(), blinking, lemurproject::indri::ui::DocsTableModel::clear(), docids, docQueryTree, docTextFrame, docTextPane, lemurproject::indri::QueryEnvironment::documentMetadata(), env, error(), lemurproject::indri::QueryAnnotation::getAnnotations(), lemurproject::indri::QueryAnnotation::getQueryTree(), lemurproject::indri::QueryAnnotation::getResults(), makeTreeModel(), maxDocs, names, numDocs, query, lemurproject::indri::ui::DocsTableModel::resize(), results, lemurproject::indri::QueryEnvironment::runAnnotatedQuery(), scored, lemurproject::indri::ui::DocsTableModel::setValueAt(), status, titles, and trim().
Referenced by actionPerformed().
void lemurproject::indri::ui::RetUI::setPaths () [inline, private]
Set the paths to the external viewer programs
References acroreadProg, powerpointProg, and wordProg.
Referenced by init().
void lemurproject::indri::ui::RetUI::spawnViewer () [inline, private]
Spawn an external viewer for pdf, doc, or ppt (Win only)
References acroreadProg, answerAll, error(), names, powerpointProg, and wordProg.
Referenced by actionPerformed().
String lemurproject::indri::ui::RetUI::trim (String s) [inline, private]
Strip leading pathname, if any.
Referenced by runQuestion().
Member Data Documentation
final String lemurproject::indri::ui::RetUI::aboutText [static, private]
Initial value:
 "Indri Retrieval UI 1.0\n" +
        "Copyright (c) 2004 University of Massachusetts\n"
About the GUI.
Referenced by actionPerformed().
String lemurproject::indri::ui::RetUI::acroreadProg [package]
external viewers Acrobat.exe or AcroRd32.exe
Referenced by setPaths(), and spawnViewer().
Map lemurproject::indri::ui::RetUI::annotations = null [package]
Map containing query annotations for highlighting.
Referenced by highlight(), and runQuestion().
JTable lemurproject::indri::ui::RetUI::answerAll [package]
Retrieved documents table
Referenced by actionPerformed(), altgetDocText(), clearAll(), getDocHtml(), getDocText(), init(), runQuestion(), and spawnViewer().
volatile boolean lemurproject::indri::ui::RetUI::blinking = false [private]
Semaphore for the blinker thread
Referenced by blinker(), and runQuestion().
int lemurproject::indri::ui::RetUI::currentDoc = -1 [package]
Index into result holders for the current document
int lemurproject::indri::ui::RetUI::currentDocId = 0 [package]
Result holder for currently selected document id
Referenced by altgetDocText(), getDocHtml(), getDocText(), and highlight().
ParsedDocument lemurproject::indri::ui::RetUI::currentParsedDoc = null [package]
Result holder for parsed documents
Referenced by altgetDocText(), getDocHtml(), getDocText(), and highlight().
Cursor lemurproject::indri::ui::RetUI::def = Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR) [static, private]
cursors
Referenced by altgetDocText(), getDocHtml(), and getDocText().
JFrame lemurproject::indri::ui::RetUI::docHtmlFrame [package]
Frame for showing document html document
Referenced by clearAll(), getDocHtml(), and makeDocHtmlFrame().
JTextPane lemurproject::indri::ui::RetUI::docHtmlPane [package]
Document html pane.
Referenced by clearAll(), getDocHtml(), and makeDocHtmlFrame().
int [] lemurproject::indri::ui::RetUI::docids = null [package]
Result holder for document internal ids
Referenced by altgetDocText(), getDocHtml(), getDocText(), and runQuestion().
JTree lemurproject::indri::ui::RetUI::docQueryTree [package]
Query tree display
Referenced by altgetDocText(), clearAll(), getDocText(), highlight(), makeDocTextFrame(), runQuestion(), and lemurproject::indri::ui::RetUI::QueryTreeListener::valueChanged().
JFrame lemurproject::indri::ui::RetUI::docTextFrame [package]
Frame for showing document text and query tree.
Referenced by altgetDocText(), clearAll(), getDocText(), makeDocTextFrame(), and runQuestion().
JTextPane lemurproject::indri::ui::RetUI::docTextPane [package]
Document text pane.
Referenced by altgetDocText(), clearAll(), getDocText(), highlight(), makeDocTextFrame(), and runQuestion().
JList lemurproject::indri::ui::RetUI::documents [private]
Enable multiple indexes
DefaultListModel lemurproject::indri::ui::RetUI::documentsModel [private]
hold the file names
QueryEnvironment lemurproject::indri::ui::RetUI::env [package]
Indri query environment for retrieval.
Referenced by altgetDocText(), getDocHtml(), getDocText(), openIndex(), openServer(), removeIndex(), RetUI(), and runQuestion().
boolean lemurproject::indri::ui::RetUI::envInit = false [package]
Flag for whether or not the query environment has been initialized.
Referenced by actionPerformed(), init(), openIndex(), and openServer().
final JFileChooser lemurproject::indri::ui::RetUI::fc [private]
Initial value:
        new JFileChooser(System.getProperties().getProperty("user.dir"))
File chooser starting in current directory
Referenced by openIndex().
volatile Thread lemurproject::indri::ui::RetUI::getDocHtmlThread [package]
getDocHtml Thread
Referenced by RetUI().
volatile Thread lemurproject::indri::ui::RetUI::getDocTextThread [package]
getDocText Thread
Referenced by altgetDocText(), getDocText(), and RetUI().
JButton lemurproject::indri::ui::RetUI::go [package]
Search and Clear buttons
Referenced by actionPerformed(), and init().
final String lemurproject::indri::ui::RetUI::helpFile = "properties/IndriRetrieval.html" [static, private]
Help file for the application
Referenced by makeHelp().
JFrame lemurproject::indri::ui::RetUI::helpFrame [private]
Frame for help window
Referenced by actionPerformed(), and makeHelp().
final String lemurproject::indri::ui::RetUI::iconFile = "properties/lemur_head_32.gif" [static, private]
Little lemur icon
Referenced by actionPerformed(), createAndShowGUI(), makeDocHtmlFrame(), makeDocTextFrame(), and makeHelp().
JList lemurproject::indri::ui::RetUI::indexes [private]
Enable multiple indexes
Referenced by init(), and removeIndex().
DefaultListModel lemurproject::indri::ui::RetUI::indexesModel [private]
hold the file names
Referenced by init(), openIndex(), openServer(), removeIndex(), and RetUI().
final Color lemurproject::indri::ui::RetUI::lightYellow = new Color(255, 255, 224) [static, private]
colors
Referenced by createAndShowGUI(), init(), makeDocTextFrame(), and makeMenuItem().
final Color lemurproject::indri::ui::RetUI::linen = new Color(250, 240, 230) [static, private]
colors
Referenced by highlight(), init(), makeDocHtmlFrame(), and makeDocTextFrame().
int lemurproject::indri::ui::RetUI::maxDocs = 10 [package]
Maximum number of documents to retrieve for a query
Referenced by init(), and runQuestion().
String [] lemurproject::indri::ui::RetUI::names = null [package]
Result holder for document external ids
Referenced by altgetDocText(), getDocHtml(), getDocText(), makeDocsTable(), runQuestion(), and spawnViewer().
final Color lemurproject::indri::ui::RetUI::navyBlue = new Color(0, 0, 128) [static, private]
colors
Referenced by createAndShowGUI(), init(), makeDocTextFrame(), and makeMenuItem().
JTextField lemurproject::indri::ui::RetUI::numDocs [package]
Number of documents to retrieve input
Referenced by init(), and runQuestion().
String lemurproject::indri::ui::RetUI::powerpointProg [package]
external viewers Powerpnt.exe
Referenced by setPaths(), and spawnViewer().
JLabel lemurproject::indri::ui::RetUI::progress [package]
Progress indicator output
Referenced by error(), and init().
JTextField lemurproject::indri::ui::RetUI::query [package]
Query input
Referenced by actionPerformed(), altgetDocText(), clearAll(), getDocHtml(), getDocText(), highlight(), init(), and runQuestion().
QueryAnnotation lemurproject::indri::ui::RetUI::results = null [package]
Result holder for query retrieval.
Referenced by runQuestion().
volatile Thread lemurproject::indri::ui::RetUI::runQuestionThread [package]
runQuestion Thread
Referenced by RetUI().
ScoredExtentResult [] lemurproject::indri::ui::RetUI::scored = null [package]
Result holder for document scored extents
Referenced by runQuestion().
JButton lemurproject::indri::ui::RetUI::scoreDisplay [package]
Referenced by actionPerformed(), and init().
boolean lemurproject::indri::ui::RetUI::showScores = false [package]
Are we showing scores?
Referenced by actionPerformed(), and makeDocsTable().
JLabel lemurproject::indri::ui::RetUI::status [package]
Status line output
Referenced by actionPerformed(), altgetDocText(), blinker(), clearAll(), getDocHtml(), getDocText(), init(), and runQuestion().
JButton lemurproject::indri::ui::RetUI::stop [package]
Referenced by init().
String [] lemurproject::indri::ui::RetUI::titles = null [package]
Result holder for document titles
Referenced by runQuestion().
Cursor lemurproject::indri::ui::RetUI::wait = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR) [static, private]
cursors
Referenced by altgetDocText(), getDocHtml(), and getDocText().
String lemurproject::indri::ui::RetUI::wordProg [package]
external viewers Word.exe
Referenced by setPaths(), and spawnViewer().
The documentation for this class was generated from the following file:
RetUI.java