Indri: indri::lang::FrequencyListCopier Class Reference
indri::lang::FrequencyListCopier Class Reference
#include <FrequencyListCopier.hpp>
Public Member Functions
FrequencyListCopier (ListCache *listCache)
indri::lang::Node * defaultAfter (indri::lang::Node *oldNode, indri::lang::Node *newNode)
~FrequencyListCopier ()
void before (indri::lang::ExtentAnd *exAnd)
void before (indri::lang::ExtentOr *exOr)
void before (indri::lang::ExtentInside *exInside)
void before (indri::lang::NestedExtentInside *nestExInside)
void before (indri::lang::ExtentRestriction *exRestrict)
void before (indri::lang::ExtentEnforcement *exEnforce)
void before (indri::lang::FixedPassage *fixedPassage)
void before (indri::lang::FieldGreaterNode *fieldGreater)
void before (indri::lang::FieldLessNode *fieldLess)
void before (indri::lang::FieldEqualsNode *fieldEquals)
void before (indri::lang::FieldBetweenNode *fieldBetween)
void before (indri::lang::ContextCounterNode *context)
void before (indri::lang::WeightedExtentOr *wExOr)
void before (indri::lang::ODNode *odNode)
void before (indri::lang::UWNode *uwNode)
void before (indri::lang::BAndNode *bandNode)
indri::lang::Node * after (indri::lang::IndexTerm *oldNode, indri::lang::IndexTerm *newNode)
void before (indri::lang::RawScorerNode *oldNode, indri::lang::RawScorerNode *newNode)
void before (indri::lang::NestedRawScorerNode *oldNode, indri::lang::NestedRawScorerNode *newNode)
indri::lang::Node * after (indri::lang::RawScorerNode *oldNode, indri::lang::RawScorerNode *newNode)
indri::lang::Node * after (indri::lang::NestedRawScorerNode *oldNode, indri::lang::NestedRawScorerNode *newNode)
Private Attributes
std::vector< indri::lang::Node * > _nodes
std::stack< indri::lang::Node * > _disqualifiers
indri::lang::IndexTerm * _lastTerm
bool _disqualifiedTree
ListCache * _listCache
Constructor & Destructor Documentation
indri::lang::FrequencyListCopier::FrequencyListCopier (ListCache * listCache) [inline]
indri::lang::FrequencyListCopier::~FrequencyListCopier () [inline]
References _nodes.
Member Function Documentation
indri::lang::Node* indri::lang::FrequencyListCopier::after (indri::lang::NestedRawScorerNode * oldNode, indri::lang::NestedRawScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References after().
indri::lang::Node* indri::lang::FrequencyListCopier::after (indri::lang::RawScorerNode * oldNode, indri::lang::RawScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, _disqualifiers, _lastTerm, _listCache, defaultAfter(), indri::lang::ListCache::find(), indri::lang::RawScorerNode::getContext(), indri::lang::RawScorerNode::getContextSize(), indri::lang::RawScorerNode::getDocumentCount(), indri::lang::RawScorerNode::getDocumentOccurrences(), indri::lang::RawScorerNode::getOccurrences(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::RawScorerNode::getSmoothing(), indri::lang::IndexTerm::getStemmed(), indri::lang::IndexTerm::getText(), indri::lang::Node::nodeName(), indri::lang::CachedFrequencyScorerNode::setList(), indri::lang::Node::setNodeName(), indri::lang::CachedFrequencyScorerNode::setSmoothing(), indri::lang::TermFrequencyScorerNode::setSmoothing(), and indri::lang::TermFrequencyScorerNode::setStatistics().
indri::lang::Node* indri::lang::FrequencyListCopier::after (indri::lang::IndexTerm * oldNode, indri::lang::IndexTerm * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _lastTerm, and defaultAfter().
Referenced by after().
void indri::lang::FrequencyListCopier::before (indri::lang::NestedRawScorerNode * oldNode, indri::lang::NestedRawScorerNode * newNode) [inline]
References before().
void indri::lang::FrequencyListCopier::before (indri::lang::RawScorerNode * oldNode, indri::lang::RawScorerNode * newNode) [inline]
References _disqualifiedTree, and _lastTerm.
void indri::lang::FrequencyListCopier::before (indri::lang::BAndNode * bandNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::UWNode * uwNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::ODNode * odNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::WeightedExtentOr * wExOr) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::ContextCounterNode * context) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and indri::lang::ContextCounterNode::getContext().
void indri::lang::FrequencyListCopier::before (indri::lang::FieldBetweenNode * fieldBetween) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::FieldEqualsNode * fieldEquals) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::FieldLessNode * fieldLess) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::FieldGreaterNode * fieldGreater) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::FixedPassage * fixedPassage) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::ExtentEnforcement * exEnforce) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::ExtentRestriction * exRestrict) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
void indri::lang::FrequencyListCopier::before (indri::lang::NestedExtentInside * nestExInside) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::ExtentInside * exInside) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::ExtentOr * exOr) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree.
void indri::lang::FrequencyListCopier::before (indri::lang::ExtentAnd * exAnd) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiedTree, and _disqualifiers.
Referenced by before().
indri::lang::Node* indri::lang::FrequencyListCopier::defaultAfter (indri::lang::Node * oldNode, indri::lang::Node * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _disqualifiers, and _nodes.
Referenced by after().
Member Data Documentation
bool indri::lang::FrequencyListCopier::_disqualifiedTree [private]
Referenced by after(), and before().
std::stack<indri::lang::Node*> indri::lang::FrequencyListCopier::_disqualifiers [private]
Referenced by after(), before(), and defaultAfter().
indri::lang::IndexTerm* indri::lang::FrequencyListCopier::_lastTerm [private]
Referenced by after(), and before().
ListCache* indri::lang::FrequencyListCopier::_listCache [private]
Referenced by after().
std::vector<indri::lang::Node*> indri::lang::FrequencyListCopier::_nodes [private]
Referenced by defaultAfter(), and ~FrequencyListCopier().
The documentation for this class was generated from the following file:
FrequencyListCopier.hpp