Indri: indri::lang::NoContextCountGraphCopier Class Reference
indri::lang::NoContextCountGraphCopier Class Reference
#include <ContextCountGraphCopier.hpp>
Public Member Functions
~NoContextCountGraphCopier ()
indri::lang::Node * defaultAfter (indri::lang::Node *oldNode, indri::lang::Node *newNode)
indri::lang::Node * after (indri::lang::RawScorerNode *oldNode, indri::lang::RawScorerNode *newNode)
indri::lang::Node * after (indri::lang::NestedRawScorerNode *oldNode, indri::lang::NestedRawScorerNode *newNode)
indri::lang::Node * after (indri::lang::ShrinkageScorerNode *oldNode, indri::lang::ShrinkageScorerNode *newNode)
indri::lang::Node * after (indri::lang::ExtentRestriction *oldNode, indri::lang::ExtentRestriction *newNode)
std::vector< indri::lang::Node * > & getNodes ()
std::vector
< indri::lang::ContextCounterNode * > & getContextCounterNodes ()
Private Attributes
std::vector< indri::lang::Node * > _newNodes
std::vector
< indri::lang::ContextCounterNode * > _contextCounters
Constructor & Destructor Documentation
indri::lang::NoContextCountGraphCopier::~NoContextCountGraphCopier () [inline]
References _newNodes.
Member Function Documentation
indri::lang::Node* indri::lang::NoContextCountGraphCopier::after (indri::lang::ExtentRestriction * oldNode, indri::lang::ExtentRestriction * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References indri::lang::ExtentRestriction::getChild().
indri::lang::Node* indri::lang::NoContextCountGraphCopier::after (indri::lang::ShrinkageScorerNode * oldNode, indri::lang::ShrinkageScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References after().
indri::lang::Node* indri::lang::NoContextCountGraphCopier::after (indri::lang::NestedRawScorerNode * oldNode, indri::lang::NestedRawScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References after().
indri::lang::Node* indri::lang::NoContextCountGraphCopier::after (indri::lang::RawScorerNode * oldNode, indri::lang::RawScorerNode * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _contextCounters, _newNodes, indri::lang::RawScorerNode::getContext(), indri::lang::RawScorerNode::getRawExtent(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
Referenced by after().
indri::lang::Node* indri::lang::NoContextCountGraphCopier::defaultAfter (indri::lang::Node * oldNode, indri::lang::Node * newNode) [inline, virtual]
Reimplemented from indri::lang::Copier.
References _newNodes.
std::vector<indri::lang::ContextCounterNode*>& indri::lang::NoContextCountGraphCopier::getContextCounterNodes () [inline]
References _contextCounters.
std::vector<indri::lang::Node*>& indri::lang::NoContextCountGraphCopier::getNodes () [inline]
References _newNodes.
Member Data Documentation
std::vector<indri::lang::ContextCounterNode*> indri::lang::NoContextCountGraphCopier::_contextCounters [private]
Referenced by after(), and getContextCounterNodes().
std::vector<indri::lang::Node*> indri::lang::NoContextCountGraphCopier::_newNodes [private]
Referenced by after(), defaultAfter(), getNodes(), and ~NoContextCountGraphCopier().
The documentation for this class was generated from the following file:
ContextCountGraphCopier.hpp