Indri: Indri::ParsedDocumentVector Class Reference
Indri::ParsedDocumentVector Class Reference
Classes
class ParsedDocumentVectorEnumerator
Public Member Functions
virtual void Dispose ()
ParsedDocumentVector (System.Collections.ICollection c)
void CopyTo (ParsedDocument[] array)
void CopyTo (ParsedDocument[] array, int arrayIndex)
void CopyTo (int index, ParsedDocument[] array, int arrayIndex, int count)
ParsedDocumentVectorEnumerator GetEnumerator ()
void Clear ()
void Add (ParsedDocument x)
ParsedDocumentVector ()
ParsedDocumentVector (ParsedDocumentVector other)
ParsedDocumentVector (int capacity)
void AddRange (ParsedDocumentVector values)
ParsedDocumentVector GetRange (int index, int count)
void Insert (int index, ParsedDocument x)
void InsertRange (int index, ParsedDocumentVector values)
void RemoveAt (int index)
void RemoveRange (int index, int count)
void Reverse ()
void Reverse (int index, int count)
void SetRange (int index, ParsedDocumentVector values)
bool Contains (ParsedDocument value)
int IndexOf (ParsedDocument value)
int LastIndexOf (ParsedDocument value)
bool Remove (ParsedDocument value)
Static Public Member Functions
static ParsedDocumentVector Repeat (ParsedDocument value, int count)
Protected Attributes
bool swigCMemOwn
Properties
bool IsFixedSize [get]
bool IsReadOnly [get]
ParsedDocument this [int index] [get, set]
int Capacity [get, set]
int Count [get]
bool IsSynchronized [get]
Private Member Functions
internal ParsedDocumentVector (IntPtr cPtr, bool cMemoryOwn)
~ParsedDocumentVector ()
System.Collections.Generic.IEnumerator
< ParsedDocument >
System.Collections.Generic.IEnumerable
< ParsedDocument >. GetEnumerator ()
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
uint size ()
uint capacity ()
void reserve (uint n)
ParsedDocument getitemcopy (int index)
ParsedDocument getitem (int index)
void setitem (int index, ParsedDocument val)
Static Private Member Functions
static internal HandleRef getCPtr (ParsedDocumentVector obj)
Private Attributes
HandleRef swigCPtr
Constructor & Destructor Documentation
internal Indri::ParsedDocumentVector::ParsedDocumentVector (IntPtr cPtr, bool cMemoryOwn) [inline, private]
References swigCMemOwn, and swigCPtr.
Indri::ParsedDocumentVector::~ParsedDocumentVector () [inline, private]
References Dispose().
Indri::ParsedDocumentVector::ParsedDocumentVector (System.Collections.ICollection c) [inline]
References Add().
Indri::ParsedDocumentVector::ParsedDocumentVector () [inline]
Referenced by GetRange(), and Repeat().
Indri::ParsedDocumentVector::ParsedDocumentVector (ParsedDocumentVector other) [inline]
Indri::ParsedDocumentVector::ParsedDocumentVector (int capacity) [inline]
Member Function Documentation
void Indri::ParsedDocumentVector::Add (ParsedDocument x) [inline]
References swigCPtr.
Referenced by ParsedDocumentVector().
void Indri::ParsedDocumentVector::AddRange (ParsedDocumentVector values) [inline]
References swigCPtr.
uint Indri::ParsedDocumentVector::capacity () [inline, private]
References swigCPtr.
void Indri::ParsedDocumentVector::Clear () [inline]
References swigCPtr.
bool Indri::ParsedDocumentVector::Contains (ParsedDocument value) [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::CopyTo (int index, ParsedDocument[] array, int arrayIndex, int count) [inline]
References Count, and getitemcopy().
void Indri::ParsedDocumentVector::CopyTo (ParsedDocument[] array, int arrayIndex) [inline]
References CopyTo(), and Count.
void Indri::ParsedDocumentVector::CopyTo (ParsedDocument[] array) [inline]
References Count.
Referenced by CopyTo().
virtual void Indri::ParsedDocumentVector::Dispose () [inline, virtual]
References Count, getitem(), swigCMemOwn, and swigCPtr.
Referenced by ~ParsedDocumentVector().
static internal HandleRef Indri::ParsedDocumentVector::getCPtr (ParsedDocumentVector obj) [inline, static, private]
References swigCPtr.
ParsedDocumentVectorEnumerator Indri::ParsedDocumentVector::GetEnumerator () [inline]
System.Collections.IEnumerator System.Collections.IEnumerable. Indri::ParsedDocumentVector::GetEnumerator () [inline, private]
System.Collections.Generic.IEnumerator<ParsedDocument> System.Collections.Generic.IEnumerable<ParsedDocument>. Indri::ParsedDocumentVector::GetEnumerator () [inline, private]
ParsedDocument Indri::ParsedDocumentVector::getitem (int index) [inline, private]
References swigCPtr.
Referenced by Dispose().
ParsedDocument Indri::ParsedDocumentVector::getitemcopy (int index) [inline, private]
References swigCPtr.
Referenced by CopyTo().
ParsedDocumentVector Indri::ParsedDocumentVector::GetRange (int index, int count) [inline]
References ParsedDocumentVector(), and swigCPtr.
int Indri::ParsedDocumentVector::IndexOf (ParsedDocument value) [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::Insert (int index, ParsedDocument x) [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::InsertRange (int index, ParsedDocumentVector values) [inline]
References swigCPtr.
int Indri::ParsedDocumentVector::LastIndexOf (ParsedDocument value) [inline]
References swigCPtr.
bool Indri::ParsedDocumentVector::Remove (ParsedDocument value) [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::RemoveAt (int index) [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::RemoveRange (int index, int count) [inline]
References swigCPtr.
static ParsedDocumentVector Indri::ParsedDocumentVector::Repeat (ParsedDocument value, int count) [inline, static]
References ParsedDocumentVector().
void Indri::ParsedDocumentVector::reserve (uint n) [inline, private]
References swigCPtr.
void Indri::ParsedDocumentVector::Reverse (int index, int count) [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::Reverse () [inline]
References swigCPtr.
void Indri::ParsedDocumentVector::setitem (int index, ParsedDocument val) [inline, private]
References swigCPtr.
void Indri::ParsedDocumentVector::SetRange (int index, ParsedDocumentVector values) [inline]
References swigCPtr.
uint Indri::ParsedDocumentVector::size () [inline, private]
References swigCPtr.
Referenced by Indri::ParsedDocumentVector::ParsedDocumentVectorEnumerator::MoveNext().
Member Data Documentation
bool Indri::ParsedDocumentVector::swigCMemOwn [protected]
Referenced by Dispose(), and ParsedDocumentVector().
HandleRef Indri::ParsedDocumentVector::swigCPtr [private]
Referenced by Add(), AddRange(), capacity(), Clear(), Contains(), Dispose(), getCPtr(), getitem(), getitemcopy(), GetRange(), IndexOf(), Insert(), InsertRange(), LastIndexOf(), ParsedDocumentVector(), Remove(), RemoveAt(), RemoveRange(), reserve(), Reverse(), setitem(), SetRange(), and size().
Property Documentation
int Indri::ParsedDocumentVector::Capacity [get, set]
int Indri::ParsedDocumentVector::Count [get]
Referenced by CopyTo(), Dispose(), Indri::ParsedDocumentVector::ParsedDocumentVectorEnumerator::MoveNext(), Indri::ParsedDocumentVector::ParsedDocumentVectorEnumerator::ParsedDocumentVectorEnumerator(), and Indri::ParsedDocumentVector::ParsedDocumentVectorEnumerator::Reset().
bool Indri::ParsedDocumentVector::IsFixedSize [get]
bool Indri::ParsedDocumentVector::IsReadOnly [get]
bool Indri::ParsedDocumentVector::IsSynchronized [get]
ParsedDocument Indri::ParsedDocumentVector::this[int index] [get, set]
The documentation for this class was generated from the following file:
ParsedDocumentVector.cs