Indri: indri::lang::PriorNode Class Reference
indri::lang::PriorNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
PriorNode (const std::string &priorName)
std::string queryText () const
PriorNode (Unpacker &unpacker)
std::string typeName () const
UINT64 hashCode () const
const std::string & getPriorName () const
void walk (Walker &walker)
indri::lang::Node * copy (Copier &copier)
void pack (Packer &packer)
Private Attributes
std::string _priorName
Constructor & Destructor Documentation
indri::lang::PriorNode::PriorNode (const std::string & priorName) [inline]
Referenced by copy().
indri::lang::PriorNode::PriorNode (Unpacker & unpacker) [inline]
References _priorName, and indri::lang::Unpacker::getString().
Member Function Documentation
indri::lang::Node* indri::lang::PriorNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _priorName, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::nodeName(), PriorNode(), and indri::lang::Node::setNodeName().
const std::string& indri::lang::PriorNode::getPriorName () const [inline]
References _priorName.
Referenced by indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::PriorNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _priorName.
void indri::lang::PriorNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _priorName, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::PriorNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _priorName.
std::string indri::lang::PriorNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::PriorNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
std::string indri::lang::PriorNode::_priorName [private]
Referenced by copy(), getPriorName(), hashCode(), pack(), PriorNode(), and queryText().
The documentation for this class was generated from the following file:
QuerySpec.hpp