Indri: indri::lang::CachedFrequencyScorerNode Class Reference
indri::lang::CachedFrequencyScorerNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
CachedFrequencyScorerNode (indri::lang::Node *raw, indri::lang::Node *context)
CachedFrequencyScorerNode (Unpacker &unpacker)
void setList (void *list)
void * getList ()
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void setSmoothing (const std::string &smoothing)
const std::string & getSmoothing () const
indri::lang::Node * getRaw ()
indri::lang::Node * getContext ()
void pack (Packer &packer)
void walk (Walker &walker)
indri::lang::Node * copy (Copier &copier)
Private Attributes
indri::lang::Node * _raw
indri::lang::Node * _context
std::string _smoothing
void * _list
Constructor & Destructor Documentation
indri::lang::CachedFrequencyScorerNode::CachedFrequencyScorerNode (indri::lang::Node * raw, indri::lang::Node * context) [inline]
Referenced by copy().
indri::lang::CachedFrequencyScorerNode::CachedFrequencyScorerNode (Unpacker & unpacker) [inline]
References _context, _raw, _smoothing, indri::lang::Unpacker::getRawExtentNode(), and indri::lang::Unpacker::getString().
Member Function Documentation
indri::lang::Node* indri::lang::CachedFrequencyScorerNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, _smoothing, indri::lang::Copier::after(), indri::lang::Copier::before(), CachedFrequencyScorerNode(), indri::lang::Node::copy(), getList(), indri::lang::Node::nodeName(), setList(), indri::lang::Node::setNodeName(), and setSmoothing().
indri::lang::Node* indri::lang::CachedFrequencyScorerNode::getContext () [inline]
References _context.
void* indri::lang::CachedFrequencyScorerNode::getList () [inline]
References _list.
Referenced by copy().
indri::lang::Node* indri::lang::CachedFrequencyScorerNode::getRaw () [inline]
References _raw.
const std::string& indri::lang::CachedFrequencyScorerNode::getSmoothing () const [inline]
References _smoothing.
UINT64 indri::lang::CachedFrequencyScorerNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, _smoothing, and indri::lang::Node::hashCode().
void indri::lang::CachedFrequencyScorerNode::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, _smoothing, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::CachedFrequencyScorerNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, and indri::lang::Node::queryText().
void indri::lang::CachedFrequencyScorerNode::setList (void * list) [inline]
References _list.
Referenced by indri::lang::FrequencyListCopier::after(), and copy().
void indri::lang::CachedFrequencyScorerNode::setSmoothing (const std::string & smoothing) [inline]
References _smoothing.
Referenced by indri::lang::FrequencyListCopier::after(), and copy().
std::string indri::lang::CachedFrequencyScorerNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::CachedFrequencyScorerNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _context, _raw, indri::lang::Walker::after(), indri::lang::Walker::before(), and indri::lang::Node::walk().
Member Data Documentation
indri::lang::Node* indri::lang::CachedFrequencyScorerNode::_context [private]
Referenced by CachedFrequencyScorerNode(), copy(), getContext(), hashCode(), pack(), queryText(), and walk().
void* indri::lang::CachedFrequencyScorerNode::_list [private]
Referenced by getList(), and setList().
indri::lang::Node* indri::lang::CachedFrequencyScorerNode::_raw [private]
Referenced by CachedFrequencyScorerNode(), copy(), getRaw(), hashCode(), pack(), queryText(), and walk().
std::string indri::lang::CachedFrequencyScorerNode::_smoothing [private]
Referenced by CachedFrequencyScorerNode(), copy(), getSmoothing(), hashCode(), pack(), and setSmoothing().
The documentation for this class was generated from the following file:
QuerySpec.hpp