Indri: indri::parse::Tokenizer Class Reference
indri::parse::Tokenizer Class Reference
#include <IndriTokenizer.hpp>
Public Member Functions
Tokenizer ()
virtual ~Tokenizer ()
virtual TokenizedDocument * tokenize (UnparsedDocument *document)=0
virtual void handle (UnparsedDocument *document)=0
virtual void setHandler (ObjectHandler< TokenizedDocument > &handler)=0
Constructor & Destructor Documentation
indri::parse::Tokenizer::Tokenizer () [inline]
virtual indri::parse::Tokenizer::~Tokenizer () [inline, virtual]
Member Function Documentation
virtual void indri::parse::Tokenizer::handle (UnparsedDocument * document) [pure virtual]
Implements indri::parse::ObjectHandler< UnparsedDocument >.
Implemented in indri::parse::TextTokenizer.
virtual void indri::parse::Tokenizer::setHandler (ObjectHandler< TokenizedDocument > & handler) [pure virtual]
Implemented in indri::parse::TextTokenizer.
virtual TokenizedDocument* indri::parse::Tokenizer::tokenize (UnparsedDocument * document) [pure virtual]
Implemented in indri::parse::TextTokenizer.
Referenced by indri::parse::AnchorTextAnnotator::_fetchText(), indri::api::IndexEnvironment::addFile(), indri::api::IndexEnvironment::addString(), and harvest_anchor_text_file().
The documentation for this class was generated from the following file:
IndriTokenizer.hpp