Indri: indri::thread::ScopedLock Class Reference
indri::thread::ScopedLock Class Reference
#include <ScopedLock.hpp>
Public Member Functions
ScopedLock (Lockable &lockable)
ScopedLock (Lockable *lockable)
~ScopedLock ()
void unlock ()
Private Attributes
Lockable * _lockable
Constructor & Destructor Documentation
indri::thread::ScopedLock::ScopedLock (Lockable & lockable) [inline]
References _lockable, and indri::thread::Lockable::lock().
indri::thread::ScopedLock::ScopedLock (Lockable * lockable) [inline]
References _lockable, and indri::thread::Lockable::lock().
indri::thread::ScopedLock::~ScopedLock () [inline]
References _lockable, and indri::thread::Lockable::unlock().
Member Function Documentation
void indri::thread::ScopedLock::unlock () [inline]
References _lockable, and indri::thread::Lockable::unlock().
Referenced by indri::collection::CompressedCollection::retrieveMetadatum().
Member Data Documentation
Lockable* indri::thread::ScopedLock::_lockable [private]
Referenced by ScopedLock(), unlock(), and ~ScopedLock().
The documentation for this class was generated from the following file:
ScopedLock.hpp