Indri: indri::net::MessageStreamHandler Class Reference
indri::net::MessageStreamHandler Class Reference
#include <NetworkMessageStream.hpp>
Public Member Functions
virtual void request (indri::xml::XMLNode *node)=0
virtual void reply (indri::xml::XMLNode *node)=0
virtual void reply (const std::string &name, const void *buffer, unsigned int length)=0
virtual void replyDone ()=0
virtual void error (const std::string &e)=0
Member Function Documentation
virtual void indri::net::MessageStreamHandler::error (const std::string & e) [pure virtual]
Implemented in indri::net::XMLReplyReceiver, indri::net::NetworkServerStub, and indri::net::QueryResponseUnpacker.
Referenced by indri::net::NetworkMessageStream::read().
virtual void indri::net::MessageStreamHandler::reply (const std::string & name, const void * buffer, unsigned int length) [pure virtual]
Implemented in indri::net::XMLReplyReceiver, indri::net::NetworkServerStub, and indri::net::QueryResponseUnpacker.
virtual void indri::net::MessageStreamHandler::reply (indri::xml::XMLNode * node) [pure virtual]
Implemented in indri::net::XMLReplyReceiver, indri::net::NetworkServerStub, and indri::net::QueryResponseUnpacker.
Referenced by indri::net::NetworkMessageStream::read().
virtual void indri::net::MessageStreamHandler::replyDone () [pure virtual]
Implemented in indri::net::XMLReplyReceiver, indri::net::NetworkServerStub, and indri::net::QueryResponseUnpacker.
Referenced by indri::net::NetworkMessageStream::read().
virtual void indri::net::MessageStreamHandler::request (indri::xml::XMLNode * node) [pure virtual]
Implemented in indri::net::XMLReplyReceiver, indri::net::NetworkServerStub, and indri::net::QueryResponseUnpacker.
Referenced by indri::net::NetworkMessageStream::read().
The documentation for this class was generated from the following file:
NetworkMessageStream.hpp