Indri: Indri::indri_csharpPINVOKE::SWIGExceptionHelper Class Reference
Indri::indri_csharpPINVOKE::SWIGExceptionHelper Class Reference
Public Member Functions
delegate void ExceptionDelegate (string message)
delegate void ExceptionArgumentDelegate (string message, string paramName)
static void SWIGRegisterExceptionCallbacks_indri_csharp (ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
static void SWIGRegisterExceptionCallbacksArgument_indri_csharp (ExceptionArgumentDelegate argumentDelegate, ExceptionArgumentDelegate argumentNullDelegate, ExceptionArgumentDelegate argumentOutOfRangeDelegate)
Static Private Member Functions
static void SetPendingApplicationException (string message)
static void SetPendingArithmeticException (string message)
static void SetPendingDivideByZeroException (string message)
static void SetPendingIndexOutOfRangeException (string message)
static void SetPendingInvalidCastException (string message)
static void SetPendingInvalidOperationException (string message)
static void SetPendingIOException (string message)
static void SetPendingNullReferenceException (string message)
static void SetPendingOutOfMemoryException (string message)
static void SetPendingOverflowException (string message)
static void SetPendingSystemException (string message)
static void SetPendingArgumentException (string message, string paramName)
static void SetPendingArgumentNullException (string message, string paramName)
static void SetPendingArgumentOutOfRangeException (string message, string paramName)
static SWIGExceptionHelper ()
Static Private Attributes
static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException)
static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException)
static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException)
static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException)
static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException)
static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException)
static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException)
static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException)
static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException)
static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException)
static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException)
static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException)
static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException)
static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException)
Constructor & Destructor Documentation
static Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SWIGExceptionHelper () [inline, static, private]
References applicationDelegate, argumentDelegate, argumentNullDelegate, argumentOutOfRangeDelegate, arithmeticDelegate, divideByZeroDelegate, indexOutOfRangeDelegate, invalidCastDelegate, invalidOperationDelegate, ioDelegate, nullReferenceDelegate, outOfMemoryDelegate, overflowDelegate, SWIGRegisterExceptionCallbacks_indri_csharp(), SWIGRegisterExceptionCallbacksArgument_indri_csharp(), and systemDelegate.
Member Function Documentation
delegate void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::ExceptionArgumentDelegate (string message, string paramName)
delegate void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::ExceptionDelegate (string message)
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingApplicationException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingArgumentException (string message, string paramName) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingArgumentNullException (string message, string paramName) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingArgumentOutOfRangeException (string message, string paramName) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingArithmeticException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingDivideByZeroException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingIndexOutOfRangeException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingInvalidCastException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingInvalidOperationException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingIOException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingNullReferenceException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingOutOfMemoryException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingOverflowException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SetPendingSystemException (string message) [inline, static, private]
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SWIGRegisterExceptionCallbacks_indri_csharp (ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
Referenced by SWIGExceptionHelper().
static void Indri::indri_csharpPINVOKE::SWIGExceptionHelper::SWIGRegisterExceptionCallbacksArgument_indri_csharp (ExceptionArgumentDelegate argumentDelegate, ExceptionArgumentDelegate argumentNullDelegate, ExceptionArgumentDelegate argumentOutOfRangeDelegate)
Referenced by SWIGExceptionHelper().
Member Data Documentation
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::applicationDelegate = new ExceptionDelegate(SetPendingApplicationException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionArgumentDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionArgumentDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionArgumentDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::ioDelegate = new ExceptionDelegate(SetPendingIOException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::overflowDelegate = new ExceptionDelegate(SetPendingOverflowException) [static, private]
Referenced by SWIGExceptionHelper().
ExceptionDelegate Indri::indri_csharpPINVOKE::SWIGExceptionHelper::systemDelegate = new ExceptionDelegate(SetPendingSystemException) [static, private]
Referenced by SWIGExceptionHelper().
The documentation for this class was generated from the following file:
indri_csharpPINVOKE.cs