Indri: indri::index::DocumentStructure Class Reference
indri::index::DocumentStructure Class Reference
#include <DocumentStructure.hpp>
Public Types
typedef
indri::utility::greedy_vector
< int >::iterator child_iterator
Public Member Functions
DocumentStructure (Index &index, const indri::utility::greedy_vector< indri::index::FieldExtent > &fields)
DocumentStructure (Index &index)
DocumentStructure ()
void loadStructure (const indri::utility::greedy_vector< indri::index::FieldExtent > &fields)
void setIndex (indri::index::Index &index)
indri::index::Index * getIndex ()
~DocumentStructure ()
int parent (int node)
int length (int node)
int begin (int node)
int end (int node)
int accumulatedLength (int node)
int type (int node)
UINT64 number (int node)
child_iterator childrenBegin (int node)
child_iterator childrenEnd (int node)
int nodeCount ()
int findLeaf (int begin, int end, int root=-1)
std::set< int > * findLeafs (int begin, int end, bool exact=false)
void findLeafs (std::set< int > *leafs, int begin, int end, bool exact=false)
bool ancestor (int node, int possibleAncestor)
std::string path (int node)
int fieldId (const std::string path)
indri::utility::greedy_vector
< int > & topDownOrder ()
void topDownOrder (std::set< int > &roots, indri::utility::greedy_vector< int > &order)
Protected Member Functions
void _constructNodePath (std::stringstream &path, int node)
void _computeTopDownOrder ()
bool _findLeafs (int node, int begin, int end, bool exact, std::set< int > *leafs)
Protected Attributes
int _numNodes
indri::utility::greedy_vector
< nodeinfo_t > _nodes
indri::utility::greedy_vector
< int > _childrenBuff
Index * _index
indri::utility::greedy_vector
< int > _topDownOrder
Member Typedef Documentation
typedef indri::utility::greedy_vector<int>::iterator indri::index::DocumentStructure::child_iterator
Constructor & Destructor Documentation
indri::index::DocumentStructure::DocumentStructure (Index & index, const indri::utility::greedy_vector< indri::index::FieldExtent > & fields) [inline]
References loadStructure().
indri::index::DocumentStructure::DocumentStructure (Index & index) [inline]
indri::index::DocumentStructure::DocumentStructure () [inline]
indri::index::DocumentStructure::~DocumentStructure ()
Member Function Documentation
void indri::index::DocumentStructure::_computeTopDownOrder () [protected]
References _numNodes, _topDownOrder, begin(), childrenBegin(), childrenEnd(), indri::utility::greedy_vector< _Type, _Count >::clear(), end(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by topDownOrder().
void indri::index::DocumentStructure::_constructNodePath (std::stringstream & path, int node) [protected]
References _index, childrenBegin(), childrenEnd(), indri::index::Index::field(), parent(), and type().
Referenced by path().
bool indri::index::DocumentStructure::_findLeafs (int node, int begin, int end, bool exact, std::set< int > * leafs) [protected]
References begin(), childrenBegin(), childrenEnd(), and end().
int indri::index::DocumentStructure::accumulatedLength (int node)
References _nodes, and _numNodes.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache().
bool indri::index::DocumentStructure::ancestor (int node, int possibleAncestor)
References parent().
Referenced by indri::infnet::ExtentDescendantNode::matches(), and indri::infnet::ExtentDescendantNode::prepare().
int indri::index::DocumentStructure::begin (int node)
References _nodes, _numNodes, and indri::utility::greedy_vector< _Type, _Count >::begin().
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), _computeTopDownOrder(), _findLeafs(), findLeaf(), findLeafs(), loadStructure(), and topDownOrder().
indri::index::DocumentStructure::child_iterator indri::index::DocumentStructure::childrenBegin (int node)
References _childrenBuff, _nodes, _numNodes, indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), _computeTopDownOrder(), _constructNodePath(), _findLeafs(), fieldId(), findLeaf(), loadStructure(), and topDownOrder().
indri::index::DocumentStructure::child_iterator indri::index::DocumentStructure::childrenEnd (int node)
References _childrenBuff, _nodes, _numNodes, indri::utility::greedy_vector< _Type, _Count >::begin(), and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), _computeTopDownOrder(), _constructNodePath(), _findLeafs(), fieldId(), findLeaf(), loadStructure(), and topDownOrder().
int indri::index::DocumentStructure::end (int node)
References _nodes, _numNodes, and indri::utility::greedy_vector< _Type, _Count >::end().
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), _computeTopDownOrder(), _findLeafs(), findLeaf(), findLeafs(), loadStructure(), and topDownOrder().
int indri::index::DocumentStructure::fieldId (const std::string path)
References _index, childrenBegin(), childrenEnd(), indri::index::Index::field(), and type().
int indri::index::DocumentStructure::findLeaf (int begin, int end, int root = -1)
References begin(), childrenBegin(), childrenEnd(), and end().
Referenced by indri::server::LocalQueryServer::pathNames().
void indri::index::DocumentStructure::findLeafs (std::set< int > * leafs, int begin, int end, bool exact = false)
References _numNodes, begin(), and end().
std::set< int > * indri::index::DocumentStructure::findLeafs (int begin, int end, bool exact = false)
Referenced by indri::infnet::ShrinkageBeliefNode::hasMatch(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentDescendantNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::infnet::ExtentParentNode::prepare(), indri::infnet::ExtentDescendantNode::prepare(), indri::infnet::ExtentChildNode::prepare(), and indri::infnet::ShrinkageBeliefNode::score().
indri::index::Index* indri::index::DocumentStructure::getIndex () [inline]
References _index.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache().
int indri::index::DocumentStructure::length (int node)
References _nodes, and _numNodes.
Referenced by loadStructure().
void indri::index::DocumentStructure::loadStructure (const indri::utility::greedy_vector< indri::index::FieldExtent > & fields)
References _childrenBuff, _nodes, _numNodes, _topDownOrder, begin(), indri::utility::greedy_vector< _Type, _Count >::begin(), childrenBegin(), childrenEnd(), indri::utility::greedy_vector< _Type, _Count >::clear(), end(), indri::utility::greedy_vector< _Type, _Count >::end(), length(), number(), parent(), indri::utility::greedy_vector< _Type, _Count >::resize(), indri::utility::greedy_vector< _Type, _Count >::size(), and type().
Referenced by DocumentStructure(), indri::server::LocalQueryServer::pathNames(), and indri::infnet::DocumentStructureHolderNode::prepare().
int indri::index::DocumentStructure::nodeCount () [inline]
References _numNodes.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), and indri::infnet::ShrinkageBeliefNode::score().
UINT64 indri::index::DocumentStructure::number (int node)
References _nodes, and _numNodes.
Referenced by loadStructure().
int indri::index::DocumentStructure::parent (int node)
References _nodes, and _numNodes.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), _constructNodePath(), ancestor(), loadStructure(), indri::infnet::ExtentParentNode::matches(), indri::infnet::ExtentChildNode::matches(), indri::infnet::ExtentParentNode::prepare(), and indri::infnet::ExtentChildNode::prepare().
std::string indri::index::DocumentStructure::path (int node)
References _constructNodePath().
Referenced by indri::server::LocalQueryServer::pathNames().
void indri::index::DocumentStructure::setIndex (indri::index::Index & index)
References _index.
Referenced by indri::server::LocalQueryServer::pathNames().
void indri::index::DocumentStructure::topDownOrder (std::set< int > & roots, indri::utility::greedy_vector< int > & order)
References _numNodes, begin(), childrenBegin(), childrenEnd(), indri::utility::greedy_vector< _Type, _Count >::clear(), end(), indri::utility::greedy_vector< _Type, _Count >::push_back(), and indri::utility::greedy_vector< _Type, _Count >::size().
indri::utility::greedy_vector< int > & indri::index::DocumentStructure::topDownOrder ()
References _computeTopDownOrder(), _topDownOrder, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache().
int indri::index::DocumentStructure::type (int node)
References _nodes, and _numNodes.
Referenced by indri::infnet::ShrinkageBeliefNode::_buildScoreCache(), _constructNodePath(), fieldId(), and loadStructure().
Member Data Documentation
indri::utility::greedy_vector<int> indri::index::DocumentStructure::_childrenBuff [protected]
Referenced by childrenBegin(), childrenEnd(), and loadStructure().
Index* indri::index::DocumentStructure::_index [protected]
Referenced by _constructNodePath(), fieldId(), getIndex(), and setIndex().
indri::utility::greedy_vector<nodeinfo_t> indri::index::DocumentStructure::_nodes [protected]
Referenced by accumulatedLength(), begin(), childrenBegin(), childrenEnd(), end(), length(), loadStructure(), number(), parent(), and type().
int indri::index::DocumentStructure::_numNodes [protected]
Referenced by _computeTopDownOrder(), accumulatedLength(), begin(), childrenBegin(), childrenEnd(), end(), findLeafs(), length(), loadStructure(), nodeCount(), number(), parent(), topDownOrder(), and type().
indri::utility::greedy_vector<int> indri::index::DocumentStructure::_topDownOrder [protected]
Referenced by _computeTopDownOrder(), loadStructure(), and topDownOrder().
The documentation for this class was generated from the following files:
DocumentStructure.hpp
DocumentStructure.cpp