Indri: indri::lang::PlusNode Class Reference
indri::lang::PlusNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
PlusNode ()
PlusNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::PlusNode::PlusNode () [inline]
indri::lang::PlusNode::PlusNode (Unpacker & unpacker) [inline]
References indri::lang::UnweightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::PlusNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_copy().
UINT64 indri::lang::PlusNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_hashCode().
std::string indri::lang::PlusNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_childText().
std::string indri::lang::PlusNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::PlusNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::UnweightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp