Indri: indri::index::DiskDocListFileIterator Class Reference
indri::index::DiskDocListFileIterator Class Reference
#include <DiskDocListFileIterator.hpp>
Public Member Functions
DiskDocListFileIterator (indri::file::File &docListFile, int fieldCount)
~DiskDocListFileIterator ()
bool finished () const
void startIteration ()
bool nextEntry ()
DocListData * currentEntry ()
const DocListData * currentEntry () const
Private Member Functions
void _readEntry ()
Private Attributes
indri::file::SequentialReadBuffer * _file
UINT64 _fileLength
int _fieldCount
indri::utility::Buffer _header
char _term [lemur::file::Keyfile::MAX_KEY_LENGTH+1]
TermData * _termData
DiskDocListIterator _iterator
DocListData _docListData
bool _finished
Constructor & Destructor Documentation
indri::index::DiskDocListFileIterator::DiskDocListFileIterator (indri::file::File & docListFile, int fieldCount)
References _termData, and termdata_size().
indri::index::DiskDocListFileIterator::~DiskDocListFileIterator ()
References _termData.
Member Function Documentation
void indri::index::DiskDocListFileIterator::_readEntry () [private]
References _docListData, _fieldCount, _file, _header, _iterator, _term, _termData, indri::utility::Buffer::clear(), indri::utility::Buffer::front(), indri::index::DocListFileIterator::DocListData::iterator, indri::utility::Buffer::position(), indri::file::SequentialReadBuffer::position(), indri::file::SequentialReadBuffer::read(), indri::index::DiskDocListIterator::setStartOffset(), indri::index::DiskDocListIterator::startIteration(), indri::index::DocListFileIterator::DocListData::termData, termdata_decompress(), and indri::utility::Buffer::write().
Referenced by nextEntry(), and startIteration().
const indri::index::DocListFileIterator::DocListData * indri::index::DiskDocListFileIterator::currentEntry () const [virtual]
Implements indri::index::DocListFileIterator.
References _docListData.
indri::index::DocListFileIterator::DocListData * indri::index::DiskDocListFileIterator::currentEntry () [virtual]
Implements indri::index::DocListFileIterator.
References _docListData.
bool indri::index::DiskDocListFileIterator::finished () const [virtual]
Implements indri::index::DocListFileIterator.
References _finished.
bool indri::index::DiskDocListFileIterator::nextEntry () [virtual]
Implements indri::index::DocListFileIterator.
References _file, _fileLength, _finished, _readEntry(), and indri::file::SequentialReadBuffer::position().
void indri::index::DiskDocListFileIterator::startIteration () [virtual]
Implements indri::index::DocListFileIterator.
References _finished, and _readEntry().
Member Data Documentation
DocListData indri::index::DiskDocListFileIterator::_docListData [private]
Referenced by _readEntry(), and currentEntry().
int indri::index::DiskDocListFileIterator::_fieldCount [private]
Referenced by _readEntry().
indri::file::SequentialReadBuffer* indri::index::DiskDocListFileIterator::_file [private]
Referenced by _readEntry(), and nextEntry().
UINT64 indri::index::DiskDocListFileIterator::_fileLength [private]
Referenced by nextEntry().
bool indri::index::DiskDocListFileIterator::_finished [private]
Referenced by finished(), nextEntry(), and startIteration().
indri::utility::Buffer indri::index::DiskDocListFileIterator::_header [private]
Referenced by _readEntry().
DiskDocListIterator indri::index::DiskDocListFileIterator::_iterator [private]
Referenced by _readEntry().
char indri::index::DiskDocListFileIterator::_term[lemur::file::Keyfile::MAX_KEY_LENGTH+1] [private]
Referenced by _readEntry().
TermData* indri::index::DiskDocListFileIterator::_termData [private]
Referenced by _readEntry(), DiskDocListFileIterator(), and ~DiskDocListFileIterator().
The documentation for this class was generated from the following files:
DiskDocListFileIterator.hpp
DiskDocListFileIterator.cpp