Indri: indri::index::DeletedDocumentList::read_transaction Class Reference
indri::index::DeletedDocumentList::read_transaction Class Reference
#include <DeletedDocumentList.hpp>
Public Member Functions
read_transaction (DeletedDocumentList &list)
~read_transaction ()
lemur::api::DOCID_T nextCandidateDocument (lemur::api::DOCID_T documentID)
bool isDeleted (lemur::api::DOCID_T documentID) const
Private Attributes
indri::thread::ReadersWritersLock & _lock
indri::utility::Buffer & _bitmap
Constructor & Destructor Documentation
indri::index::DeletedDocumentList::read_transaction::read_transaction (DeletedDocumentList & list)
References _lock, and indri::thread::ReadersWritersLock::lockRead().
indri::index::DeletedDocumentList::read_transaction::~read_transaction ()
References _lock, and indri::thread::ReadersWritersLock::unlockRead().
Member Function Documentation
bool indri::index::DeletedDocumentList::read_transaction::isDeleted (lemur::api::DOCID_T documentID) const
References _bitmap, indri::utility::Buffer::front(), and indri::utility::Buffer::position().
Referenced by indri::collection::CompressedCollection::_copyForwardLookup().
lemur::api::DOCID_T indri::index::DeletedDocumentList::read_transaction::nextCandidateDocument (lemur::api::DOCID_T documentID)
References _bitmap, _lock, indri::utility::Buffer::front(), indri::utility::Buffer::position(), and indri::thread::ReadersWritersLock::yieldRead().
Referenced by indri::infnet::InferenceNetwork::_nextCandidateDocument().
Member Data Documentation
indri::utility::Buffer& indri::index::DeletedDocumentList::read_transaction::_bitmap [private]
Referenced by isDeleted(), and nextCandidateDocument().
indri::thread::ReadersWritersLock& indri::index::DeletedDocumentList::read_transaction::_lock [private]
Referenced by nextCandidateDocument(), read_transaction(), and ~read_transaction().
The documentation for this class was generated from the following files:
DeletedDocumentList.hpp
DeletedDocumentList.cpp