Indri: indri::query::ReformulateQuery Class Reference
indri::query::ReformulateQuery Class Reference
#include <ReformulateQuery.hpp>
Classes
struct weighted_field
Public Member Functions
ReformulateQuery (indri::api::Parameters &p)
ReformulateQuery ()
~ReformulateQuery ()
void setParameters (indri::api::Parameters &p)
std::string transform (std::string queryTerms)
std::string downcase_string (const std::string &str)
std::vector< std::string > split (std::string q, char d)
std::string replaceAll (std::string result, const std::string &replaceWhat, const std::string &replaceWithWhat)
std::string trim (std::string text)
std::string makeIndriFriendly (std::string query)
std::string generateSDMQuery (std::vector< std::string > strs, std::vector< indri::query::ReformulateQuery::weighted_field > fields)
std::string generateSDMQuery (std::vector< std::string > strs)
std::string generateSDMQuery (std::string q)
std::string generateFDMQuery (std::vector< std::string > strs, std::vector< indri::query::ReformulateQuery::weighted_field > fields)
std::string generateFDMQuery (std::vector< std::string > strs)
std::string generateFDMQuery (std::string q)
std::string generateCombineQuery (std::vector< std::string > strs)
std::string generateCombineQuery (std::string q)
std::string generateCMUFDMQuery (std::vector< std::string > strs)
std::string generateCMUFDMQuery (std::string q)
Private Attributes
indri::api::Parameters * params
Constructor & Destructor Documentation
indri::query::ReformulateQuery::ReformulateQuery (indri::api::Parameters & p) [inline]
References params.
indri::query::ReformulateQuery::ReformulateQuery () [inline]
References params.
indri::query::ReformulateQuery::~ReformulateQuery () [inline]
Member Function Documentation
std::string indri::query::ReformulateQuery::downcase_string (const std::string & str)
Referenced by transform().
std::string indri::query::ReformulateQuery::generateCMUFDMQuery (std::string q)
References generateCMUFDMQuery(), and split().
std::string indri::query::ReformulateQuery::generateCMUFDMQuery (std::vector< std::string > strs)
References generateFDMQuery(), indri::api::Parameters::get(), and params.
Referenced by generateCMUFDMQuery(), and transform().
std::string indri::query::ReformulateQuery::generateCombineQuery (std::string q)
References generateCombineQuery(), and split().
std::string indri::query::ReformulateQuery::generateCombineQuery (std::vector< std::string > strs)
Referenced by generateCombineQuery(), and transform().
std::string indri::query::ReformulateQuery::generateFDMQuery (std::string q)
References generateFDMQuery(), and split().
std::string indri::query::ReformulateQuery::generateFDMQuery (std::vector< std::string > strs)
References indri::api::Parameters::get(), and params.
std::string indri::query::ReformulateQuery::generateFDMQuery (std::vector< std::string > strs, std::vector< indri::query::ReformulateQuery::weighted_field > fields)
References indri::api::Parameters::get(), and params.
Referenced by generateCMUFDMQuery(), generateFDMQuery(), and transform().
std::string indri::query::ReformulateQuery::generateSDMQuery (std::string q)
References generateSDMQuery(), and split().
std::string indri::query::ReformulateQuery::generateSDMQuery (std::vector< std::string > strs)
References indri::api::Parameters::get(), and params.
std::string indri::query::ReformulateQuery::generateSDMQuery (std::vector< std::string > strs, std::vector< indri::query::ReformulateQuery::weighted_field > fields)
References indri::api::Parameters::get(), and params.
Referenced by generateSDMQuery(), and transform().
std::string indri::query::ReformulateQuery::makeIndriFriendly (std::string query)
std::string indri::query::ReformulateQuery::replaceAll (std::string result, const std::string & replaceWhat, const std::string & replaceWithWhat)
Referenced by trim().
void indri::query::ReformulateQuery::setParameters (indri::api::Parameters & p) [inline]
References params.
Referenced by indri::api::QueryEnvironment::setFormulationParameters().
std::vector< std::string > indri::query::ReformulateQuery::split (std::string q, char d)
Referenced by generateCMUFDMQuery(), generateCombineQuery(), generateFDMQuery(), generateSDMQuery(), and transform().
std::string indri::query::ReformulateQuery::transform (std::string queryTerms)
References downcase_string(), indri::api::Parameters::exists(), generateCMUFDMQuery(), generateCombineQuery(), generateFDMQuery(), generateSDMQuery(), indri::api::Parameters::get(), params, indri::api::Parameters::size(), and split().
Referenced by indri::api::QueryEnvironment::reformulateQuery().
std::string indri::query::ReformulateQuery::trim (std::string text)
References replaceAll().
Member Data Documentation
indri::api::Parameters* indri::query::ReformulateQuery::params [private]
Referenced by generateCMUFDMQuery(), generateFDMQuery(), generateSDMQuery(), ReformulateQuery(), setParameters(), and transform().
The documentation for this class was generated from the following files:
ReformulateQuery.hpp
src/ReformulateQuery.cpp