Indri: indri::lang::Field Class Reference
indri::lang::Field Class Reference
#include <QuerySpec.hpp>
Public Member Functions
Field (const std::string &name)
Field (Unpacker &unpacker)
const std::string & getFieldName () const
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
bool operator== (Node &other)
Private Attributes
std::string _fieldName
Constructor & Destructor Documentation
indri::lang::Field::Field (const std::string & name) [inline]
Referenced by copy().
indri::lang::Field::Field (Unpacker & unpacker) [inline]
References _fieldName, and indri::lang::Unpacker::getString().
Member Function Documentation
Node* indri::lang::Field::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Copier::after(), indri::lang::Copier::before(), and Field().
const std::string& indri::lang::Field::getFieldName () const [inline]
References _fieldName.
Referenced by indri::lang::SmoothingAnnotatorWalker::after(), indri::infnet::InferenceNetworkBuilder::after(), indri::lang::ContextSimpleCountCollectorCopier::after(), indri::lang::TreePrinterWalker::before(), and operator==().
UINT64 indri::lang::Field::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _fieldName.
bool indri::lang::Field::operator== (Node & other) [inline]
References getFieldName().
void indri::lang::Field::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _fieldName, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::Field::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _fieldName.
std::string indri::lang::Field::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::Field::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::Walker::after(), and indri::lang::Walker::before().
Member Data Documentation
std::string indri::lang::Field::_fieldName [private]
Referenced by Field(), getFieldName(), hashCode(), pack(), and queryText().
The documentation for this class was generated from the following file:
QuerySpec.hpp