Indri: indri::lang::ExtentParent Class Reference
indri::lang::ExtentParent Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ExtentParent (RawExtentNode *inner, RawExtentNode *outer, DocumentStructureNode *docStruct)
ExtentParent (Unpacker &unpacker)
bool operator== (Node &o)
void setDocumentStructure (DocumentStructureNode *docStruct)
DocumentStructureNode * getDocumentStructure ()
std::string typeName () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Protected Attributes
DocumentStructureNode * _documentStructure
Constructor & Destructor Documentation
indri::lang::ExtentParent::ExtentParent (RawExtentNode * inner, RawExtentNode * outer, DocumentStructureNode * docStruct) [inline]
Referenced by copy().
indri::lang::ExtentParent::ExtentParent (Unpacker & unpacker) [inline]
References _documentStructure, and indri::lang::Unpacker::getDocumentStructureNode().
Member Function Documentation
Node* indri::lang::ExtentParent::copy (Copier & copier) [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References _documentStructure, indri::lang::ExtentInside::_inner, indri::lang::ExtentInside::_outer, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::DocumentStructureNode::copy(), indri::lang::Node::copy(), ExtentParent(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
DocumentStructureNode* indri::lang::ExtentParent::getDocumentStructure () [inline]
References _documentStructure.
Referenced by indri::infnet::InferenceNetworkBuilder::_after().
UINT64 indri::lang::ExtentParent::hashCode () const [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References indri::lang::ExtentInside::_inner, and indri::lang::Node::hashCode().
bool indri::lang::ExtentParent::operator== (Node & o) [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References _documentStructure, indri::lang::ExtentInside::_inner, and indri::lang::ExtentInside::_outer.
void indri::lang::ExtentParent::setDocumentStructure (DocumentStructureNode * docStruct) [inline]
References _documentStructure.
std::string indri::lang::ExtentParent::typeName () const [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
void indri::lang::ExtentParent::walk (Walker & walker) [inline, virtual]
Reimplemented from indri::lang::ExtentInside.
References _documentStructure, indri::lang::ExtentInside::_inner, indri::lang::ExtentInside::_outer, indri::lang::Walker::after(), indri::lang::Walker::before(), indri::lang::DocumentStructureNode::walk(), and indri::lang::Node::walk().
Member Data Documentation
DocumentStructureNode* indri::lang::ExtentParent::_documentStructure [protected]
Referenced by copy(), ExtentParent(), getDocumentStructure(), operator==(), setDocumentStructure(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp