Indri: QueryThread Class Reference
QueryThread Class Reference
Public Member Functions
QueryThread (std::queue< query_t * > &queries, std::priority_queue< query_t *, std::vector< query_t * >, query_t::greater > &output, indri::thread::Lockable &queueLock, indri::thread::ConditionVariable &queueEvent, indri::api::Parameters &params)
~QueryThread ()
UINT64 initialize ()
void deinitialize ()
bool hasWork ()
UINT64 work ()
Private Member Functions
void _runQuery (std::stringstream &output, const std::string &query, const std::string &queryType, const std::vector< std::string > &workingSet, std::vector< std::string > relFBDocs)
void _printResultRegion (std::stringstream &output, std::string queryIndex, int start, int end)
void _printResults (std::stringstream &output, std::string queryNumber)
Private Attributes
indri::thread::Lockable & _queueLock
indri::thread::ConditionVariable & _queueEvent
std::queue< query_t * > & _queries
std::priority_queue< query_t
*, std::vector< query_t * >
, query_t::greater > & _output
indri::api::QueryEnvironment _environment
indri::api::Parameters & _parameters
int _requested
int _initialRequested
bool _printDocuments
bool _printPassages
bool _printSnippets
bool _printQuery
std::string _runID
bool _trecFormat
bool _inexFormat
indri::query::QueryExpander * _expander
std::vector
< indri::api::ScoredExtentResult > _results
indri::api::QueryAnnotation * _annotation
Constructor & Destructor Documentation
QueryThread::QueryThread (std::queue< query_t * > & queries, std::priority_queue< query_t *, std::vector< query_t * >, query_t::greater > & output, indri::thread::Lockable & queueLock, indri::thread::ConditionVariable & queueEvent, indri::api::Parameters & params) [inline]
QueryThread::~QueryThread () [inline]
Member Function Documentation
void QueryThread::_printResultRegion (std::stringstream & output, std::string queryIndex, int start, int end) [inline, private]
References _annotation, _environment, _inexFormat, _printDocuments, _printPassages, _printSnippets, _results, _runID, _trecFormat, indri::api::SnippetBuilder::build(), indri::api::QueryEnvironment::documentMetadata(), indri::api::QueryEnvironment::documents(), indri::api::QueryEnvironment::pathNames(), and indri::parse::MetadataPair::value.
Referenced by _printResults().
void QueryThread::_printResults (std::stringstream & output, std::string queryNumber) [inline, private]
References _annotation, _inexFormat, _printResultRegion(), _results, and indri::thread::UtilityThread::start().
Referenced by work().
void QueryThread::_runQuery (std::stringstream & output, const std::string & query, const std::string & queryType, const std::vector< std::string > & workingSet, std::vector< std::string > relFBDocs) [inline, private]
References _annotation, _environment, _expander, _initialRequested, _printQuery, _printSnippets, _requested, _results, indri::api::QueryEnvironment::documentIDsFromMetadata(), indri::query::QueryExpander::expand(), indri::api::QueryAnnotation::getResults(), indri::api::QueryEnvironment::runAnnotatedQuery(), and indri::api::QueryEnvironment::runQuery().
Referenced by work().
void QueryThread::deinitialize () [inline, virtual]
Implements indri::thread::UtilityThread.
References _environment, _expander, and indri::api::QueryEnvironment::close().
bool QueryThread::hasWork () [inline, virtual]
Implements indri::thread::UtilityThread.
References _queries, and _queueLock.
UINT64 QueryThread::initialize () [inline, virtual]
Implements indri::thread::UtilityThread.
References _environment, _expander, _inexFormat, _initialRequested, _output, _parameters, _printDocuments, _printPassages, _printQuery, _printSnippets, _queries, _queueEvent, _requested, _runID, _trecFormat, indri::api::QueryEnvironment::addIndex(), indri::api::QueryEnvironment::addServer(), copy_parameters_to_string_vector(), indri::api::Parameters::exists(), indri::api::Parameters::get(), query_t::index, indri::thread::ConditionVariable::notifyAll(), query_t::number, indri::api::Parameters::set(), indri::api::QueryEnvironment::setBaseline(), indri::api::QueryEnvironment::setMaxWildcardTerms(), indri::api::QueryEnvironment::setScoringRules(), indri::api::QueryEnvironment::setSingleBackgroundModel(), indri::api::QueryEnvironment::setStopwords(), and indri::api::Parameters::size().
UINT64 QueryThread::work () [inline, virtual]
Implements indri::thread::UtilityThread.
References _output, _parameters, _printResults(), _queries, _queueEvent, _queueLock, _runQuery(), indri::api::Parameters::exists(), query_t::index, indri::thread::ConditionVariable::notifyAll(), query_t::number, query_t::qType, query_t::relFBDocs, query_t::text, and query_t::workingSet.
Member Data Documentation
indri::api::QueryAnnotation* QueryThread::_annotation [private]
Referenced by _printResultRegion(), _printResults(), and _runQuery().
indri::api::QueryEnvironment QueryThread::_environment [private]
Referenced by _printResultRegion(), _runQuery(), deinitialize(), and initialize().
indri::query::QueryExpander* QueryThread::_expander [private]
Referenced by _runQuery(), deinitialize(), and initialize().
bool QueryThread::_inexFormat [private]
Referenced by _printResultRegion(), _printResults(), and initialize().
int QueryThread::_initialRequested [private]
Referenced by _runQuery(), and initialize().
std::priority_queue< query_t*, std::vector< query_t* >, query_t::greater >& QueryThread::_output [private]
Referenced by initialize(), and work().
indri::api::Parameters& QueryThread::_parameters [private]
Referenced by initialize(), and work().
bool QueryThread::_printDocuments [private]
Referenced by _printResultRegion(), and initialize().
bool QueryThread::_printPassages [private]
Referenced by _printResultRegion(), and initialize().
bool QueryThread::_printQuery [private]
Referenced by _runQuery(), and initialize().
bool QueryThread::_printSnippets [private]
Referenced by _printResultRegion(), _runQuery(), and initialize().
std::queue< query_t* >& QueryThread::_queries [private]
Referenced by hasWork(), initialize(), and work().
indri::thread::ConditionVariable& QueryThread::_queueEvent [private]
Referenced by initialize(), and work().
indri::thread::Lockable& QueryThread::_queueLock [private]
Referenced by hasWork(), and work().
int QueryThread::_requested [private]
Referenced by _runQuery(), and initialize().
std::vector<indri::api::ScoredExtentResult> QueryThread::_results [private]
Referenced by _printResultRegion(), _printResults(), and _runQuery().
std::string QueryThread::_runID [private]
Referenced by _printResultRegion(), and initialize().
bool QueryThread::_trecFormat [private]
Referenced by _printResultRegion(), and initialize().
The documentation for this class was generated from the following file:
IndriRunQuery.cpp