Indri: indri::parse::OffsetAnnotationAnnotator Class Reference
indri::parse::OffsetAnnotationAnnotator Class Reference
#include <OffsetAnnotationAnnotator.hpp>
Classes
struct ReadAnnotationTag
Public Member Functions
OffsetAnnotationAnnotator (Conflater *p_conflater)
OffsetAnnotationAnnotator ()
~OffsetAnnotationAnnotator ()
void setTags (const char *docno, const std::vector< indri::parse::TagExtent * > &tagset)
void setConflater (Conflater *p_conflater)
void setHandler (ObjectHandler< indri::api::ParsedDocument > &handler)
void handle (indri::api::ParsedDocument *document)
void setHint (indri::parse::OffsetAnnotationIndexHint hintType)
void open (const std::string &offsetAnnotationsFile)
indri::api::ParsedDocument * transform (indri::api::ParsedDocument *document)
Private Member Functions
const char * _getDocno (indri::api::ParsedDocument *document)
TagExtent * _getTag (UINT64 id)
AttributeValuePair * _getAttribute (UINT64 id)
bool _is_unique_id (UINT64 id, int line)
UINT64 parse_UINT64 (const char *str, int n)
void _cleanup ()
ReadAnnotationTag parseLine (char *readLine, int lineCounter)
void readAnnotationTags (const char *docno)
void convert_annotations (std::set< indri::parse::TagExtent * > *raw_tags, std::set< indri::parse::TagExtent * > *converted_tags, indri::api::ParsedDocument *document)
Private Attributes
OffsetAnnotationIndexHint _indexHintType
std::string _offsetAnnotationsFile
int lastBufferAllocationSize
indri::utility::HashTable
< const char *, std::set
< TagExtent * > * > * _annotations
indri::utility::HashTable
< const char *, std::set
< TagExtent * > * > * _converted_annotations
indri::utility::HashTable
< UINT64, TagExtent * > * _tag_id_map
indri::utility::HashTable
< UINT64, AttributeValuePair * > * _attribute_id_map
std::vector< char * > * _buffers_allocated
bool _first_open
ObjectHandler
< indri::api::ParsedDocument > * _handler
Conflater * _p_conflater
std::ifstream annotationFile
int offsetAnnotationFileLine
ReadAnnotationTag lastReadTag
Constructor & Destructor Documentation
indri::parse::OffsetAnnotationAnnotator::OffsetAnnotationAnnotator (Conflater * p_conflater)
Construction / Destruction
References _annotations, _attribute_id_map, _buffers_allocated, _converted_annotations, _first_open, _handler, _indexHintType, _p_conflater, _tag_id_map, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::docno, lastBufferAllocationSize, lastReadTag, and indri::parse::OAHintDefault.
indri::parse::OffsetAnnotationAnnotator::OffsetAnnotationAnnotator ()
References _annotations, _attribute_id_map, _buffers_allocated, _converted_annotations, _first_open, _handler, _indexHintType, _p_conflater, _tag_id_map, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::docno, lastBufferAllocationSize, lastReadTag, and indri::parse::OAHintDefault.
indri::parse::OffsetAnnotationAnnotator::~OffsetAnnotationAnnotator ()
References _annotations, _attribute_id_map, _buffers_allocated, _cleanup(), _converted_annotations, _tag_id_map, and annotationFile.
Member Function Documentation
void indri::parse::OffsetAnnotationAnnotator::_cleanup () [private]
References _annotations, _attribute_id_map, _buffers_allocated, _converted_annotations, _tag_id_map, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::begin(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::clear(), and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::end().
Referenced by open(), readAnnotationTags(), and ~OffsetAnnotationAnnotator().
indri::parse::AttributeValuePair * indri::parse::OffsetAnnotationAnnotator::_getAttribute (UINT64 id) [private]
References _attribute_id_map, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
Referenced by _is_unique_id().
const char * indri::parse::OffsetAnnotationAnnotator::_getDocno (indri::api::ParsedDocument * document) [private]
References indri::api::ParsedDocument::metadata, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by transform().
indri::parse::TagExtent * indri::parse::OffsetAnnotationAnnotator::_getTag (UINT64 id) [private]
References _tag_id_map, and indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find().
Referenced by _is_unique_id(), open(), and readAnnotationTags().
bool indri::parse::OffsetAnnotationAnnotator::_is_unique_id (UINT64 id, int line) [private]
References _getAttribute(), and _getTag().
Referenced by open(), and readAnnotationTags().
void indri::parse::OffsetAnnotationAnnotator::convert_annotations (std::set< indri::parse::TagExtent * > * raw_tags, std::set< indri::parse::TagExtent * > * converted_tags, indri::api::ParsedDocument * document) [private]
References indri::parse::TagExtent::attributes, indri::parse::TagExtent::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::parse::TagExtent::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::parse::TagExtent::parent, indri::api::ParsedDocument::positions, and indri::utility::greedy_vector< _Type, _Count >::size().
Referenced by transform().
void indri::parse::OffsetAnnotationAnnotator::handle (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _handler, indri::parse::ObjectHandler< _Type >::handle(), and transform().
void indri::parse::OffsetAnnotationAnnotator::open (const std::string & offsetAnnotationsFile)
References _annotations, _attribute_id_map, _buffers_allocated, _cleanup(), _converted_annotations, _first_open, _getTag(), _indexHintType, _is_unique_id(), _offsetAnnotationsFile, _p_conflater, _tag_id_map, annotationFile, indri::parse::AttributeValuePair::attribute, indri::parse::TagExtent::attributes, indri::parse::TagExtent::begin, indri::parse::Conflater::conflate(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::docno, indri::parse::TagExtent::end, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::i_value, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::id, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), lastBufferAllocationSize, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::length, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::name, indri::parse::TagExtent::name, indri::parse::TagExtent::number, indri::parse::OAHintOrderedAnnotations, offsetAnnotationFileLine, indri::parse::TagExtent::parent, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::parent, parseLine(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::s_value, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::start, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::type, and indri::parse::AttributeValuePair::value.
Referenced by indri::api::IndexEnvironment::_createAnnotators(), and FieldModifier::processFields().
UINT64 indri::parse::OffsetAnnotationAnnotator::parse_UINT64 (const char * str, int n) [private]
Referenced by parseLine().
indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag indri::parse::OffsetAnnotationAnnotator::parseLine (char * readLine, int lineCounter) [private]
References _buffers_allocated, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::docno, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::i_value, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::id, lastReadTag, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::length, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::name, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::parent, parse_UINT64(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::s_value, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::start, and indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::type.
Referenced by open(), and readAnnotationTags().
void indri::parse::OffsetAnnotationAnnotator::readAnnotationTags (const char * docno) [private]
References _annotations, _attribute_id_map, _cleanup(), _getTag(), _is_unique_id(), _p_conflater, _tag_id_map, annotationFile, indri::parse::AttributeValuePair::attribute, indri::parse::TagExtent::attributes, indri::parse::TagExtent::begin, indri::parse::Conflater::conflate(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::docno, indri::parse::TagExtent::end, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::i_value, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::id, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), lastReadTag, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::length, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::name, indri::parse::TagExtent::name, indri::parse::TagExtent::number, offsetAnnotationFileLine, indri::parse::TagExtent::parent, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::parent, parseLine(), indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::s_value, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::start, indri::parse::OffsetAnnotationAnnotator::ReadAnnotationTag::type, and indri::parse::AttributeValuePair::value.
Referenced by transform().
void indri::parse::OffsetAnnotationAnnotator::setConflater (Conflater * p_conflater)
References _p_conflater.
Referenced by indri::api::IndexEnvironment::_createAnnotators(), and FieldModifier::processFields().
void indri::parse::OffsetAnnotationAnnotator::setHandler (ObjectHandler< indri::api::ParsedDocument > & handler) [virtual]
Implements indri::parse::Transformation.
References _handler.
void indri::parse::OffsetAnnotationAnnotator::setHint (indri::parse::OffsetAnnotationIndexHint hintType)
References _indexHintType.
Referenced by indri::api::IndexEnvironment::setOffsetAnnotationIndexHint().
void indri::parse::OffsetAnnotationAnnotator::setTags (const char * docno, const std::vector< indri::parse::TagExtent * > & tagset)
References _annotations, _buffers_allocated, _p_conflater, indri::parse::TagExtent::begin, indri::parse::Conflater::conflate(), indri::parse::TagExtent::end, indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::insert(), indri::parse::TagExtent::name, indri::parse::TagExtent::number, and indri::parse::TagExtent::parent.
Referenced by indri::api::IndexEnvironment::addString().
indri::api::ParsedDocument * indri::parse::OffsetAnnotationAnnotator::transform (indri::api::ParsedDocument * document) [virtual]
Implements indri::parse::Transformation.
References _annotations, _converted_annotations, _getDocno(), _indexHintType, indri::utility::greedy_vector< _Type, _Count >::begin(), convert_annotations(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::utility::HashTable< _Key, _Value, _HashFunction, _Comparator >::find(), indri::parse::OAHintOrderedAnnotations, indri::utility::greedy_vector< _Type, _Count >::push_back(), readAnnotationTags(), and indri::api::ParsedDocument::tags.
Referenced by indri::api::IndexEnvironment::addString(), handle(), and FieldModifier::processFields().
Member Data Documentation
indri::utility::HashTable<const char *,std::set<TagExtent*>*>* indri::parse::OffsetAnnotationAnnotator::_annotations [private]
Referenced by _cleanup(), OffsetAnnotationAnnotator(), open(), readAnnotationTags(), setTags(), transform(), and ~OffsetAnnotationAnnotator().
indri::utility::HashTable<UINT64,AttributeValuePair*>* indri::parse::OffsetAnnotationAnnotator::_attribute_id_map [private]
Referenced by _cleanup(), _getAttribute(), OffsetAnnotationAnnotator(), open(), readAnnotationTags(), and ~OffsetAnnotationAnnotator().
std::vector<char *>* indri::parse::OffsetAnnotationAnnotator::_buffers_allocated [private]
Referenced by _cleanup(), OffsetAnnotationAnnotator(), open(), parseLine(), setTags(), and ~OffsetAnnotationAnnotator().
indri::utility::HashTable<const char *,std::set<TagExtent*>*>* indri::parse::OffsetAnnotationAnnotator::_converted_annotations [private]
Referenced by _cleanup(), OffsetAnnotationAnnotator(), open(), transform(), and ~OffsetAnnotationAnnotator().
bool indri::parse::OffsetAnnotationAnnotator::_first_open [private]
Referenced by OffsetAnnotationAnnotator(), and open().
ObjectHandler<indri::api::ParsedDocument>* indri::parse::OffsetAnnotationAnnotator::_handler [private]
Referenced by handle(), OffsetAnnotationAnnotator(), and setHandler().
OffsetAnnotationIndexHint indri::parse::OffsetAnnotationAnnotator::_indexHintType [private]
Referenced by OffsetAnnotationAnnotator(), open(), setHint(), and transform().
std::string indri::parse::OffsetAnnotationAnnotator::_offsetAnnotationsFile [private]
Referenced by open().
Conflater* indri::parse::OffsetAnnotationAnnotator::_p_conflater [private]
Referenced by OffsetAnnotationAnnotator(), open(), readAnnotationTags(), setConflater(), and setTags().
indri::utility::HashTable<UINT64,TagExtent*>* indri::parse::OffsetAnnotationAnnotator::_tag_id_map [private]
Referenced by _cleanup(), _getTag(), OffsetAnnotationAnnotator(), open(), readAnnotationTags(), and ~OffsetAnnotationAnnotator().
std::ifstream indri::parse::OffsetAnnotationAnnotator::annotationFile [private]
Referenced by open(), readAnnotationTags(), and ~OffsetAnnotationAnnotator().
int indri::parse::OffsetAnnotationAnnotator::lastBufferAllocationSize [private]
Referenced by OffsetAnnotationAnnotator(), and open().
ReadAnnotationTag indri::parse::OffsetAnnotationAnnotator::lastReadTag [private]
Referenced by OffsetAnnotationAnnotator(), parseLine(), and readAnnotationTags().
int indri::parse::OffsetAnnotationAnnotator::offsetAnnotationFileLine [private]
Referenced by open(), and readAnnotationTags().
The documentation for this class was generated from the following files:
OffsetAnnotationAnnotator.hpp
OffsetAnnotationAnnotator.cpp