Indri: indri::infnet::MaxNode Class Reference
indri::infnet::MaxNode Class Reference
#include <MaxNode.hpp>
Public Member Functions
MaxNode (const std::string &name)
MaxNode (const std::string &name, const std::vector< BeliefNode * > &children)
lemur::api::DOCID_T nextCandidateDocument ()
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
double maximumScore ()
double maximumBackgroundScore ()
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
void indexChanged (indri::index::Index &index)
const std::string & getName () const
Private Attributes
std::vector< BeliefNode * > _children
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::MaxNode::MaxNode (const std::string & name) [inline]
indri::infnet::MaxNode::MaxNode (const std::string & name, const std::vector< BeliefNode * > & children) [inline]
References _children.
Member Function Documentation
void indri::infnet::MaxNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _children, indri::infnet::Annotator::add(), indri::api::ScoredExtentResult::begin, indri::index::Extent::begin, indri::api::ScoredExtentResult::end, indri::index::Extent::end, INDRI_TINY_SCORE, indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string& indri::infnet::MaxNode::getName () const [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector<bool>& indri::infnet::MaxNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _children, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::MaxNode::hasMatch (lemur::api::DOCID_T documentID) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _children.
void indri::infnet::MaxNode::indexChanged (indri::index::Index & index) [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::MaxNode::maximumBackgroundScore () [inline, virtual]
Implements indri::infnet::BeliefNode.
References _children, and INDRI_TINY_SCORE.
double indri::infnet::MaxNode::maximumScore () [inline, virtual]
Implements indri::infnet::BeliefNode.
References _children, and INDRI_TINY_SCORE.
lemur::api::DOCID_T indri::infnet::MaxNode::nextCandidateDocument () [inline, virtual]
Implements indri::infnet::InferenceNetworkNode.
References _children.
indri::utility::greedy_vector<indri::api::ScoredExtentResult>& indri::infnet::MaxNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [inline, virtual]
Implements indri::infnet::BeliefNode.
References _children, _scores, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, INDRI_TINY_SCORE, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, and indri::utility::greedy_vector< _Type, _Count >::size().
Member Data Documentation
std::vector<BeliefNode*> indri::infnet::MaxNode::_children [private]
Referenced by annotate(), hasMatch(), maximumBackgroundScore(), maximumScore(), MaxNode(), nextCandidateDocument(), and score().
indri::utility::greedy_vector<bool> indri::infnet::MaxNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::MaxNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::MaxNode::_scores [private]
Referenced by score().
The documentation for this class was generated from the following file:
MaxNode.hpp