Indri: indri::infnet::ExtentRestrictionNode Class Reference
indri::infnet::ExtentRestrictionNode Class Reference
#include <ExtentRestrictionNode.hpp>
Public Member Functions
ExtentRestrictionNode (const std::string &name, BeliefNode *child, ListIteratorNode *field)
lemur::api::DOCID_T nextCandidateDocument ()
void indexChanged (indri::index::Index &index)
double maximumScore ()
double maximumBackgroundScore ()
const
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > & score (lemur::api::DOCID_T documentID, indri::index::Extent &extent, int documentLength)
void annotate (class Annotator &annotator, lemur::api::DOCID_T documentID, indri::index::Extent &extent)
bool hasMatch (lemur::api::DOCID_T documentID)
const
indri::utility::greedy_vector
< bool > & hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > &extents)
const std::string & getName () const
void setSiblingsFlag (int f)
over-ridden to set child nodes too
Private Attributes
BeliefNode * _child
ListIteratorNode * _field
indri::utility::greedy_vector
< indri::api::ScoredExtentResult > _scores
indri::utility::greedy_vector
< bool > _matches
std::string _name
Constructor & Destructor Documentation
indri::infnet::ExtentRestrictionNode::ExtentRestrictionNode (const std::string & name, BeliefNode * child, ListIteratorNode * field)
References indri::infnet::BeliefNode::bSiblings.
Member Function Documentation
void indri::infnet::ExtentRestrictionNode::annotate (class Annotator & annotator, lemur::api::DOCID_T documentID, indri::index::Extent & extent) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _field, _scores, indri::infnet::Annotator::add(), indri::infnet::BeliefNode::annotate(), indri::utility::greedy_vector< _Type, _Count >::append(), indri::utility::greedy_vector< _Type, _Count >::begin(), indri::utility::greedy_vector< _Type, _Count >::clear(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::BeliefNode::hasMatch(), indri::infnet::ListIteratorNode::matches(), and indri::utility::greedy_vector< _Type, _Count >::size().
const std::string & indri::infnet::ExtentRestrictionNode::getName () const [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _name.
const indri::utility::greedy_vector< bool > & indri::infnet::ExtentRestrictionNode::hasMatch (lemur::api::DOCID_T documentID, const indri::utility::greedy_vector< indri::index::Extent > & extents) [virtual]
Implements indri::infnet::BeliefNode.
References _child, _field, _matches, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::infnet::BeliefNode::hasMatch(), indri::infnet::ListIteratorNode::matches(), indri::utility::greedy_vector< _Type, _Count >::resize(), and indri::utility::greedy_vector< _Type, _Count >::size().
bool indri::infnet::ExtentRestrictionNode::hasMatch (lemur::api::DOCID_T documentID) [virtual]
Implements indri::infnet::BeliefNode.
References _child, and indri::infnet::BeliefNode::hasMatch().
void indri::infnet::ExtentRestrictionNode::indexChanged (indri::index::Index & index) [virtual]
Implements indri::infnet::InferenceNetworkNode.
double indri::infnet::ExtentRestrictionNode::maximumBackgroundScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_TINY_SCORE.
double indri::infnet::ExtentRestrictionNode::maximumScore () [virtual]
Implements indri::infnet::BeliefNode.
References INDRI_HUGE_SCORE.
lemur::api::DOCID_T indri::infnet::ExtentRestrictionNode::nextCandidateDocument () [virtual]
Implements indri::infnet::InferenceNetworkNode.
References _child, and indri::infnet::InferenceNetworkNode::nextCandidateDocument().
const indri::utility::greedy_vector< indri::api::ScoredExtentResult > & indri::infnet::ExtentRestrictionNode::score (lemur::api::DOCID_T documentID, indri::index::Extent & extent, int documentLength) [virtual]
score all, but also all siblings if no matches...
Implements indri::infnet::BeliefNode.
References _child, _field, _scores, indri::utility::greedy_vector< _Type, _Count >::append(), indri::index::Extent::begin, indri::api::ScoredExtentResult::begin, indri::utility::greedy_vector< _Type, _Count >::begin(), indri::infnet::BeliefNode::bSiblings, indri::utility::greedy_vector< _Type, _Count >::clear(), indri::api::ScoredExtentResult::document, indri::index::Extent::end, indri::api::ScoredExtentResult::end, indri::utility::greedy_vector< _Type, _Count >::end(), indri::infnet::BeliefNode::hasMatch(), indri::infnet::ListIteratorNode::matches(), indri::api::ScoredExtentResult::ordinal, indri::api::ScoredExtentResult::parentOrdinal, indri::utility::greedy_vector< _Type, _Count >::push_back(), indri::api::ScoredExtentResult::score, indri::infnet::BeliefNode::score(), and indri::utility::greedy_vector< _Type, _Count >::size().
void indri::infnet::ExtentRestrictionNode::setSiblingsFlag (int f) [virtual]
over-ridden to set child nodes too
Reimplemented from indri::infnet::BeliefNode.
References _child, indri::infnet::BeliefNode::bSiblings, and indri::infnet::BeliefNode::setSiblingsFlag().
Member Data Documentation
BeliefNode* indri::infnet::ExtentRestrictionNode::_child [private]
Referenced by annotate(), hasMatch(), nextCandidateDocument(), score(), and setSiblingsFlag().
ListIteratorNode* indri::infnet::ExtentRestrictionNode::_field [private]
Referenced by annotate(), hasMatch(), and score().
indri::utility::greedy_vector<bool> indri::infnet::ExtentRestrictionNode::_matches [private]
Referenced by hasMatch().
std::string indri::infnet::ExtentRestrictionNode::_name [private]
Referenced by getName().
indri::utility::greedy_vector<indri::api::ScoredExtentResult> indri::infnet::ExtentRestrictionNode::_scores [private]
Referenced by annotate(), and score().
The documentation for this class was generated from the following files:
ExtentRestrictionNode.hpp
ExtentRestrictionNode.cpp