Indri: indri::lang::WPlusNode Class Reference
indri::lang::WPlusNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
WPlusNode ()
WPlusNode (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void walk (Walker &walker)
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::WPlusNode::WPlusNode () [inline]
indri::lang::WPlusNode::WPlusNode (Unpacker & unpacker) [inline]
References indri::lang::WeightedCombinationNode::_unpack().
Member Function Documentation
Node* indri::lang::WPlusNode::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_copy().
UINT64 indri::lang::WPlusNode::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_hashCode().
std::string indri::lang::WPlusNode::queryText () const [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_childText().
std::string indri::lang::WPlusNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::WPlusNode::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References indri::lang::WeightedCombinationNode::_walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp