Indri: indri::server::NetworkServerProxy Class Reference
indri::server::NetworkServerProxy Class Reference
#include <NetworkServerProxy.hpp>
Public Member Functions
NetworkServerProxy (indri::net::NetworkMessageStream *stream)
QueryServerResponse * runQuery (std::vector< indri::lang::Node * > &roots, int resultsRequested, bool optimize)
QueryServerDocumentsResponse * documents (const std::vector< lemur::api::DOCID_T > &documentIDs)
QueryServerMetadataResponse * documentMetadata (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::string &attributeName)
QueryServerDocumentIDsResponse * documentIDsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)
QueryServerDocumentsResponse * documentsFromMetadata (const std::string &attributeName, const std::vector< std::string > &attributeValues)
QueryServerMetadataResponse * pathNames (const std::vector< lemur::api::DOCID_T > &documentIDs, const std::vector< int > &pathBegins, const std::vector< int > &pathEnds)
INT64 termCount ()
INT64 termCount (int term)
INT64 termCount (const std::string &term)
INT64 termCountUnique ()
INT64 stemCount (const std::string &stem)
std::string termName (lemur::api::TERMID_T term)
lemur::api::TERMID_T termID (const std::string &term)
std::string stemTerm (const std::string &term)
std::vector< std::string > fieldList ()
INT64 termFieldCount (const std::string &term, const std::string &field)
INT64 stemFieldCount (const std::string &stem, const std::string &field)
int documentLength (lemur::api::DOCID_T documentID)
INT64 documentCount ()
INT64 documentCount (const std::string &term)
INT64 documentStemCount (const std::string &term)
QueryServerVectorsResponse * documentVectors (const std::vector< lemur::api::DOCID_T > &documentIDs)
void setMaxWildcardTerms (int maxTerms)
Private Member Functions
INT64 _numericRequest (indri::xml::XMLNode *node)
std::string _stringRequest (indri::xml::XMLNode *node)
Private Attributes
indri::net::NetworkMessageStream * _stream
Constructor & Destructor Documentation
indri::server::NetworkServerProxy::NetworkServerProxy (indri::net::NetworkMessageStream * stream)
Member Function Documentation
INT64 indri::server::NetworkServerProxy::_numericRequest (indri::xml::XMLNode * node) [private]
References _stream, indri::net::XMLReplyReceiver::getReply(), indri::xml::XMLNode::getValue(), indri::net::NetworkMessageStream::mutex(), indri::net::NetworkMessageStream::request(), string_to_i64(), and indri::net::XMLReplyReceiver::wait().
Referenced by documentCount(), documentLength(), documentStemCount(), setMaxWildcardTerms(), stemCount(), stemFieldCount(), termCount(), termCountUnique(), termFieldCount(), and termID().
std::string indri::server::NetworkServerProxy::_stringRequest (indri::xml::XMLNode * node) [private]
References _stream, indri::net::XMLReplyReceiver::getReply(), indri::xml::XMLNode::getValue(), indri::net::NetworkMessageStream::mutex(), indri::net::NetworkMessageStream::request(), and indri::net::XMLReplyReceiver::wait().
Referenced by stemTerm(), and termName().
INT64 indri::server::NetworkServerProxy::documentCount (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
INT64 indri::server::NetworkServerProxy::documentCount () [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
indri::server::QueryServerDocumentIDsResponse * indri::server::NetworkServerProxy::documentIDsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addChild(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), and indri::net::NetworkMessageStream::request().
int indri::server::NetworkServerProxy::documentLength (lemur::api::DOCID_T documentID) [virtual]
Implements indri::server::QueryServer.
References _numericRequest(), and i64_to_string().
indri::server::QueryServerMetadataResponse * indri::server::NetworkServerProxy::documentMetadata (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::string & attributeName) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addChild(), documents(), i64_to_string(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), and indri::net::NetworkMessageStream::request().
indri::server::QueryServerDocumentsResponse * indri::server::NetworkServerProxy::documents (const std::vector< lemur::api::DOCID_T > & documentIDs) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addChild(), i64_to_string(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), and indri::net::NetworkMessageStream::request().
Referenced by documentMetadata(), and pathNames().
indri::server::QueryServerDocumentsResponse * indri::server::NetworkServerProxy::documentsFromMetadata (const std::string & attributeName, const std::vector< std::string > & attributeValues) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addChild(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), and indri::net::NetworkMessageStream::request().
INT64 indri::server::NetworkServerProxy::documentStemCount (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
indri::server::QueryServerVectorsResponse * indri::server::NetworkServerProxy::documentVectors (const std::vector< lemur::api::DOCID_T > & documentIDs) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addChild(), i64_to_string(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), and indri::net::NetworkMessageStream::request().
std::vector< std::string > indri::server::NetworkServerProxy::fieldList () [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::getChildren(), indri::net::XMLReplyReceiver::getReply(), indri::net::NetworkMessageStream::mutex(), indri::net::NetworkMessageStream::request(), and indri::net::XMLReplyReceiver::wait().
indri::server::QueryServerMetadataResponse * indri::server::NetworkServerProxy::pathNames (const std::vector< lemur::api::DOCID_T > & documentIDs, const std::vector< int > & pathBegins, const std::vector< int > & pathEnds) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addChild(), documents(), i64_to_string(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), and indri::net::NetworkMessageStream::request().
indri::server::QueryServerResponse * indri::server::NetworkServerProxy::runQuery (std::vector< indri::lang::Node * > & roots, int resultsRequested, bool optimize) [virtual]
Implements indri::server::QueryServer.
References _stream, indri::xml::XMLNode::addAttribute(), i64_to_string(), indri::thread::Lockable::lock(), indri::net::NetworkMessageStream::mutex(), indri::lang::Packer::pack(), indri::net::NetworkMessageStream::request(), and indri::lang::Packer::xml().
void indri::server::NetworkServerProxy::setMaxWildcardTerms (int maxTerms) [virtual]
Implements indri::server::QueryServer.
References _numericRequest(), and i64_to_string().
INT64 indri::server::NetworkServerProxy::stemCount (const std::string & stem) [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
INT64 indri::server::NetworkServerProxy::stemFieldCount (const std::string & stem, const std::string & field) [virtual]
Implements indri::server::QueryServer.
References _numericRequest(), and indri::xml::XMLNode::addChild().
std::string indri::server::NetworkServerProxy::stemTerm (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _stringRequest().
INT64 indri::server::NetworkServerProxy::termCount (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
INT64 indri::server::NetworkServerProxy::termCount (int term)
INT64 indri::server::NetworkServerProxy::termCount () [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
INT64 indri::server::NetworkServerProxy::termCountUnique () [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
INT64 indri::server::NetworkServerProxy::termFieldCount (const std::string & term, const std::string & field) [virtual]
Implements indri::server::QueryServer.
References _numericRequest(), and indri::xml::XMLNode::addChild().
lemur::api::TERMID_T indri::server::NetworkServerProxy::termID (const std::string & term) [virtual]
Implements indri::server::QueryServer.
References _numericRequest().
std::string indri::server::NetworkServerProxy::termName (lemur::api::TERMID_T term) [virtual]
Implements indri::server::QueryServer.
References _stringRequest(), and i64_to_string().
Member Data Documentation
indri::net::NetworkMessageStream* indri::server::NetworkServerProxy::_stream [private]
Referenced by _numericRequest(), _stringRequest(), documentIDsFromMetadata(), documentMetadata(), documents(), documentsFromMetadata(), documentVectors(), fieldList(), pathNames(), and runQuery().
The documentation for this class was generated from the following files:
NetworkServerProxy.hpp
NetworkServerProxy.cpp