Indri: indri::lang::ExtentOr Class Reference
indri::lang::ExtentOr Class Reference
#include <QuerySpec.hpp>
Public Member Functions
ExtentOr ()
ExtentOr (const std::vector< RawExtentNode * > &children)
ExtentOr (Unpacker &unpacker)
std::string typeName () const
std::string queryText () const
UINT64 hashCode () const
void addChild (RawExtentNode *node)
std::vector< RawExtentNode * > & getChildren ()
bool operator== (Node &node)
void pack (Packer &packer)
void walk (Walker &walker)
Node * copy (Copier &copier)
Private Attributes
std::vector< RawExtentNode * > _children
Constructor & Destructor Documentation
indri::lang::ExtentOr::ExtentOr () [inline]
Referenced by copy().
indri::lang::ExtentOr::ExtentOr (const std::vector< RawExtentNode * > & children) [inline]
indri::lang::ExtentOr::ExtentOr (Unpacker & unpacker) [inline]
References _children, and indri::lang::Unpacker::getRawExtentVector().
Member Function Documentation
void indri::lang::ExtentOr::addChild (RawExtentNode * node) [inline]
References _children.
Referenced by copy(), NexiParser::field(), QueryParser::synonym_list(), QueryParser::synonym_list_alt(), and QueryParser::synonym_list_brace().
Node* indri::lang::ExtentOr::copy (Copier & copier) [inline, virtual]
Implements indri::lang::Node.
References _children, addChild(), indri::lang::Copier::after(), indri::lang::Copier::before(), ExtentOr(), indri::lang::Node::nodeName(), and indri::lang::Node::setNodeName().
std::vector<RawExtentNode*>& indri::lang::ExtentOr::getChildren () [inline]
References _children.
Referenced by indri::lang::SmoothingAnnotatorWalker::after(), and indri::infnet::InferenceNetworkBuilder::after().
UINT64 indri::lang::ExtentOr::hashCode () const [inline, virtual]
Implements indri::lang::Node.
References _children.
bool indri::lang::ExtentOr::operator== (Node & node) [inline]
References _children, and unordered_equal().
void indri::lang::ExtentOr::pack (Packer & packer) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Packer::after(), indri::lang::Packer::before(), and indri::lang::Packer::put().
std::string indri::lang::ExtentOr::queryText () const [inline, virtual]
Implements indri::lang::Node.
References _children.
std::string indri::lang::ExtentOr::typeName () const [inline, virtual]
Reimplemented from indri::lang::Node.
void indri::lang::ExtentOr::walk (Walker & walker) [inline, virtual]
Implements indri::lang::Node.
References _children, indri::lang::Walker::after(), and indri::lang::Walker::before().
Referenced by indri::lang::UnnecessaryNodeRemoverCopier::after().
Member Data Documentation
std::vector<RawExtentNode*> indri::lang::ExtentOr::_children [private]
Referenced by addChild(), copy(), ExtentOr(), getChildren(), hashCode(), operator==(), pack(), queryText(), and walk().
The documentation for this class was generated from the following file:
QuerySpec.hpp