Indri: indri::lang::NestedRawScorerNode Class Reference
indri::lang::NestedRawScorerNode Class Reference
#include <QuerySpec.hpp>
Public Member Functions
NestedRawScorerNode (RawExtentNode *raw, RawExtentNode *context, std::string smoothing="method:dirichlet,mu:2500")
NestedRawScorerNode (Unpacker &unpacker)
std::string typeName () const
UINT64 hashCode () const
Node * copy (Copier &copier)
Constructor & Destructor Documentation
indri::lang::NestedRawScorerNode::NestedRawScorerNode (RawExtentNode * raw, RawExtentNode * context, std::string smoothing = "method:dirichlet,mu:2500") [inline]
Referenced by copy().
indri::lang::NestedRawScorerNode::NestedRawScorerNode (Unpacker & unpacker) [inline]
Member Function Documentation
Node* indri::lang::NestedRawScorerNode::copy (Copier & copier) [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References indri::lang::RawScorerNode::_context, indri::lang::RawScorerNode::_raw, indri::lang::Copier::after(), indri::lang::Copier::before(), indri::lang::Node::copy(), and NestedRawScorerNode().
UINT64 indri::lang::NestedRawScorerNode::hashCode () const [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
References indri::lang::RawScorerNode::_context, indri::lang::RawScorerNode::_raw, indri::lang::RawScorerNode::_smoothing, and indri::lang::Node::hashCode().
std::string indri::lang::NestedRawScorerNode::typeName () const [inline, virtual]
Reimplemented from indri::lang::RawScorerNode.
The documentation for this class was generated from the following file:
QuerySpec.hpp