Indri: indri::lang::SmoothingAnnotatorWalker Class Reference
indri::lang::SmoothingAnnotatorWalker Class Reference
#include <SmoothingAnnotatorWalker.hpp>
Classes
struct rule_type
Public Member Functions
SmoothingAnnotatorWalker (indri::api::Parameters &parameters)
~SmoothingAnnotatorWalker ()
void after (indri::lang::RawScorerNode *scorer)
void after (indri::lang::NestedRawScorerNode *scorer)
void after (indri::lang::ShrinkageScorerNode *scorer)
void after (indri::lang::LengthPrior *prior)
Private Member Functions
void _loadSmoothingRules (indri::api::Parameters &parameters)
const std::string & _matchSmoothingRule (const std::string &node, const std::string &field, const std::string &op)
Private Attributes
std::vector< rule_type * > _rules
std::string _defaultSmoothing
Constructor & Destructor Documentation
indri::lang::SmoothingAnnotatorWalker::SmoothingAnnotatorWalker (indri::api::Parameters & parameters) [inline]
References _defaultSmoothing, and _loadSmoothingRules().
indri::lang::SmoothingAnnotatorWalker::~SmoothingAnnotatorWalker () [inline]
References _rules.
Member Function Documentation
void indri::lang::SmoothingAnnotatorWalker::_loadSmoothingRules (indri::api::Parameters & parameters) [inline, private]
References _rules, indri::api::Parameters::exists(), indri::lang::SmoothingAnnotatorWalker::rule_type::field, indri::lang::SmoothingAnnotatorWalker::rule_type::node, indri::lang::SmoothingAnnotatorWalker::rule_type::op, indri::api::Parameters::size(), and indri::lang::SmoothingAnnotatorWalker::rule_type::smoothing.
Referenced by SmoothingAnnotatorWalker().
const std::string& indri::lang::SmoothingAnnotatorWalker::_matchSmoothingRule (const std::string & node, const std::string & field, const std::string & op) [inline, private]
References _defaultSmoothing, _rules, indri::lang::SmoothingAnnotatorWalker::rule_type::field, indri::lang::SmoothingAnnotatorWalker::rule_type::node, indri::lang::SmoothingAnnotatorWalker::rule_type::op, and indri::lang::SmoothingAnnotatorWalker::rule_type::smoothing.
Referenced by after().
void indri::lang::SmoothingAnnotatorWalker::after (indri::lang::LengthPrior * prior) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _matchSmoothingRule(), and indri::lang::LengthPrior::setExponent().
void indri::lang::SmoothingAnnotatorWalker::after (indri::lang::ShrinkageScorerNode * scorer) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _rules, after(), indri::lang::SmoothingAnnotatorWalker::rule_type::field, indri::lang::SmoothingAnnotatorWalker::rule_type::node, indri::lang::SmoothingAnnotatorWalker::rule_type::op, and indri::lang::SmoothingAnnotatorWalker::rule_type::smoothing.
void indri::lang::SmoothingAnnotatorWalker::after (indri::lang::NestedRawScorerNode * scorer) [inline, virtual]
Reimplemented from indri::lang::Walker.
References after().
void indri::lang::SmoothingAnnotatorWalker::after (indri::lang::RawScorerNode * scorer) [inline, virtual]
Reimplemented from indri::lang::Walker.
References _matchSmoothingRule(), indri::lang::ExtentOr::getChildren(), indri::lang::RawScorerNode::getContext(), indri::lang::Field::getFieldName(), indri::lang::RawScorerNode::getRawExtent(), and indri::lang::RawScorerNode::setSmoothing().
Referenced by after().
Member Data Documentation
std::string indri::lang::SmoothingAnnotatorWalker::_defaultSmoothing [private]
Referenced by _matchSmoothingRule(), and SmoothingAnnotatorWalker().
std::vector<rule_type*> indri::lang::SmoothingAnnotatorWalker::_rules [private]
Referenced by _loadSmoothingRules(), _matchSmoothingRule(), after(), and ~SmoothingAnnotatorWalker().
The documentation for this class was generated from the following file:
SmoothingAnnotatorWalker.hpp