Indri: DirectoryIterator.cpp File Reference
DirectoryIterator.cpp File Reference
#include "indri/DirectoryIterator.hpp"
#include "lemur/lemur-platform.h"
#include <assert.h>
#include "indri/Path.hpp"
#include <vector>
#include <iostream>
#include <cstdlib>
#include <sys/types.h>
#include <dirent.h>
#include <limits.h>
Classes
struct unix_iter_data
Functions
void * directoryiterator_init (const std::string &path)
void directoryiterator_destroy (void *opaque)
std::string directoryiterator_current ()
bool directoryiterator_next (void *opaque)
bool directoryiterator_done (void *opaque)
void directoryiterator_dirent_init (unix_iter_data &d)
void directoryiterator_dirent_destroy (unix_iter_data &d)
std::string directoryiterator_current (void *opaque)
Function Documentation
std::string directoryiterator_current (void * opaque)
References unix_iter_data::entry.
std::string directoryiterator_current ()
Referenced by indri::file::DirectoryIterator::_copyCurrent(), indri::file::DirectoryIterator::_next(), and indri::file::DirectoryIterator::DirectoryIterator().
void directoryiterator_destroy (void * opaque)
References unix_iter_data::directory, and unix_iter_data::entry.
Referenced by indri::file::DirectoryIterator::close().
void directoryiterator_dirent_destroy (unix_iter_data & d)
void directoryiterator_dirent_init (unix_iter_data & d)
References unix_iter_data::entry.
bool directoryiterator_done (void * opaque)
References unix_iter_data::done.
Referenced by indri::file::DirectoryIterator::_next(), indri::file::DirectoryIterator::DirectoryIterator(), indri::file::DirectoryIterator::operator++(), and indri::file::DirectoryIterator::operator==().
void * directoryiterator_init (const std::string & path)
References unix_iter_data::directory, directoryiterator_next(), unix_iter_data::done, and unix_iter_data::entry.
Referenced by indri::file::DirectoryIterator::DirectoryIterator().
bool directoryiterator_next (void * opaque)
References unix_iter_data::directory, unix_iter_data::done, and unix_iter_data::entry.
Referenced by indri::file::DirectoryIterator::_next(), and directoryiterator_init().