Indri: DiskTermData.hpp File Reference
DiskTermData.hpp File Reference
#include "indri/TermData.hpp"
#include "lemur/Keyfile.hpp"
#include "lemur/IndexTypes.hpp"
Classes
struct indri::index::DiskTermData
Namespaces
namespace indri
namespaces within the indri system
namespace indri::index
index construction and interaction components
Functions
void disktermdata_compress (indri::utility::RVLCompressStream &stream, indri::index::DiskTermData *diskData, int fieldCount, int mode)
indri::index::DiskTermData * disktermdata_decompress (indri::utility::RVLDecompressStream &stream, void *buffer, int fieldCount, int mode)
int disktermdata_size (int fieldCount)
indri::index::DiskTermData * disktermdata_create (int fieldCount)
indri::index::DiskTermData * disktermdata_decompress (indri::utility::RVLDecompressStream &stream, int fieldCount, int mode)
void disktermdata_delete (indri::index::DiskTermData *diskData)
Function Documentation
void disktermdata_compress (indri::utility::RVLCompressStream & stream, indri::index::DiskTermData * diskData, int fieldCount, int mode) [inline]
References indri::index::DiskTermData::length, indri::index::DiskTermData::startOffset, indri::index::DiskTermData::termData, termdata_compress(), indri::index::DiskTermData::termID, indri::index::DiskTermData::WithOffsets, indri::index::DiskTermData::WithString, and indri::index::DiskTermData::WithTermID.
Referenced by indri::index::IndexWriter::_storeFrequentTerms(), indri::index::IndexWriter::_storeIdEntry(), and indri::index::IndexWriter::_storeStringEntry().
indri::index::DiskTermData* disktermdata_create (int fieldCount) [inline]
References disktermdata_size(), indri::index::DiskTermData::termData, termdata_construct(), and termdata_size().
Referenced by indri::index::IndexWriter::_storeMatchInformation().
indri::index::DiskTermData* disktermdata_decompress (indri::utility::RVLDecompressStream & stream, int fieldCount, int mode) [inline]
References disktermdata_decompress(), and disktermdata_size().
indri::index::DiskTermData* disktermdata_decompress (indri::utility::RVLDecompressStream & stream, void * buffer, int fieldCount, int mode) [inline]
References indri::index::DiskTermData::length, indri::index::DiskTermData::startOffset, indri::index::DiskTermData::termData, termdata_decompress(), termdata_size(), indri::index::DiskTermData::termID, indri::index::DiskTermData::WithOffsets, indri::index::DiskTermData::WithString, and indri::index::DiskTermData::WithTermID.
Referenced by indri::index::DiskIndex::_fetchTermData(), indri::index::IndexWriter::_lookupTermID(), indri::index::DiskKeyfileVocabularyIterator::_readData(), disktermdata_decompress(), and indri::index::DiskFrequentVocabularyIterator::nextEntry().
void disktermdata_delete (indri::index::DiskTermData * diskData) [inline]
Referenced by indri::index::IndexWriter::_storeFrequentTerms(), indri::index::DiskIndex::docListIterator(), indri::index::DiskIndex::documentCount(), indri::index::DiskIndex::fieldDocumentCount(), indri::index::DiskIndex::fieldTermCount(), indri::index::DiskIndex::term(), and indri::index::DiskIndex::termCount().
int disktermdata_size (int fieldCount) [inline]
References termdata_size().
Referenced by indri::index::DiskIndex::_fetchTermData(), indri::index::DiskFrequentVocabularyIterator::DiskFrequentVocabularyIterator(), indri::index::DiskKeyfileVocabularyIterator::DiskKeyfileVocabularyIterator(), disktermdata_create(), disktermdata_decompress(), and indri::index::IndexWriter::write().