Indri: dumpindex.cpp File Reference
dumpindex.cpp File Reference
#include "indri/Repository.hpp"
#include "indri/CompressedCollection.hpp"
#include "indri/LocalQueryServer.hpp"
#include "indri/ScopedLock.hpp"
#include "indri/QueryEnvironment.hpp"
#include <iostream>
Defines
#define REQUIRE_ARGS(n) { if(argc < n) { usage(); return -1; } }
Functions
void print_document_expression_count (const std::string &indexName, const std::string &expression)
void print_expression_count (const std::string &indexName, const std::string &expression)
void print_expression_list (const std::string &indexName, const std::string &expression)
void validate (indri::collection::Repository &r)
void print_invfile (indri::collection::Repository &r)
void print_vocabulary (indri::collection::Repository &r)
void print_field_positions (indri::collection::Repository &r, const std::string &fieldString)
void print_term_positions (indri::collection::Repository &r, const std::string &termString)
void print_term_counts (indri::collection::Repository &r, const std::string &termString)
void print_document_name (indri::collection::Repository &r, const char *number)
void print_document_text (indri::collection::Repository &r, const char *number)
void print_document_data (indri::collection::Repository &r, const char *number)
void print_document_vector (indri::collection::Repository &r, const char *number)
void print_document_id (indri::collection::Repository &r, const char *an, const char *av)
void print_repository_stats (indri::collection::Repository &r)
void merge_repositories (const std::string &outputPath, int argc, char **argv)
void compact_repository (const std::string &repositoryPath)
void delete_document (const std::string &repositoryPath, const char *stringDocumentID)
void usage ()
int main (int argc, char **argv)
Define Documentation
#define REQUIRE_ARGS (n) { if(argc < n) { usage(); return -1; } }
Referenced by main().
Function Documentation
void compact_repository (const std::string & repositoryPath)
References indri::collection::Repository::close(), indri::collection::Repository::compact(), and indri::collection::Repository::open().
Referenced by main().
void delete_document (const std::string & repositoryPath, const char * stringDocumentID)
References indri::collection::Repository::close(), indri::collection::Repository::deleteDocument(), indri::collection::Repository::open(), and string_to_i64().
Referenced by main().
int main (int argc, char ** argv)
References indri::collection::Repository::close(), compact_repository(), delete_document(), merge_repositories(), indri::collection::Repository::openRead(), print_document_data(), print_document_expression_count(), print_document_id(), print_document_name(), print_document_text(), print_document_vector(), print_expression_count(), print_expression_list(), print_field_positions(), print_invfile(), print_repository_stats(), print_term_counts(), print_term_positions(), print_vocabulary(), REQUIRE_ARGS, usage(), and validate().
void merge_repositories (const std::string & outputPath, int argc, char ** argv)
References indri::collection::Repository::merge().
Referenced by main().
void print_document_data (indri::collection::Repository & r, const char * number)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::collection::Repository::collection(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::api::ParsedDocument::getContent(), indri::api::ParsedDocument::metadata, indri::api::ParsedDocument::positions, indri::collection::CompressedCollection::retrieve(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::api::ParsedDocument::tags, and indri::api::ParsedDocument::text.
Referenced by main().
void print_document_expression_count (const std::string & indexName, const std::string & expression)
References indri::api::QueryEnvironment::addIndex(), indri::api::QueryEnvironment::close(), and indri::api::QueryEnvironment::documentExpressionCount().
Referenced by main().
void print_document_id (indri::collection::Repository & r, const char * an, const char * av)
References indri::collection::Repository::collection(), and indri::collection::CompressedCollection::retrieveIDByMetadatum().
Referenced by main().
void print_document_name (indri::collection::Repository & r, const char * number)
References indri::collection::Repository::collection(), and indri::collection::CompressedCollection::retrieveMetadatum().
Referenced by main().
void print_document_text (indri::collection::Repository & r, const char * number)
References indri::collection::Repository::collection(), indri::collection::CompressedCollection::retrieve(), and indri::api::ParsedDocument::text.
Referenced by main().
void print_document_vector (indri::collection::Repository & r, const char * number)
References indri::api::DocumentVector::Field::begin, indri::server::LocalQueryServer::documentVectors(), indri::api::DocumentVector::Field::end, indri::api::DocumentVector::fields(), indri::server::QueryServerVectorsResponse::getResults(), indri::api::DocumentVector::Field::name, indri::api::DocumentVector::Field::number, indri::api::DocumentVector::positions(), and indri::api::DocumentVector::stems().
Referenced by main().
void print_expression_count (const std::string & indexName, const std::string & expression)
References indri::api::QueryEnvironment::addIndex(), indri::api::QueryEnvironment::close(), and indri::api::QueryEnvironment::expressionCount().
Referenced by main().
void print_expression_list (const std::string & indexName, const std::string & expression)
References indri::api::QueryEnvironment::addIndex(), indri::api::QueryEnvironment::close(), indri::api::QueryEnvironment::documentCount(), indri::api::QueryEnvironment::expressionList(), and indri::api::QueryEnvironment::termCount().
Referenced by main().
void print_field_positions (indri::collection::Repository & r, const std::string & fieldString)
References indri::utility::greedy_vector< _Type, _Count >::begin(), indri::index::DocExtentListIterator::DocumentExtentData::document, indri::index::Index::documentLength(), indri::utility::greedy_vector< _Type, _Count >::end(), indri::index::DocExtentListIterator::DocumentExtentData::extents, indri::index::Index::fieldListIterator(), indri::collection::Repository::indexes(), indri::index::Index::iteratorLock(), indri::index::DocExtentListIterator::DocumentExtentData::numbers, indri::utility::greedy_vector< _Type, _Count >::size(), and indri::server::LocalQueryServer::termCount().
Referenced by main().
void print_invfile (indri::collection::Repository & r)
References indri::index::TermData::corpus, indri::index::DocListFileIterator::currentEntry(), indri::index::Index::docListFileIterator(), indri::index::DocListIterator::DocumentData::document, indri::index::Index::documentCount(), indri::index::DocListFileIterator::finished(), indri::collection::Repository::indexes(), indri::index::DocListFileIterator::DocListData::iterator, indri::index::DocListFileIterator::nextEntry(), indri::index::DocListIterator::DocumentData::positions, indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::DocListFileIterator::startIteration(), indri::index::TermData::term, indri::index::Index::termCount(), and indri::index::DocListFileIterator::DocListData::termData.
Referenced by main().
void print_repository_stats (indri::collection::Repository & r)
References indri::server::LocalQueryServer::documentCount(), indri::server::LocalQueryServer::fieldList(), indri::collection::Repository::indexes(), indri::server::LocalQueryServer::termCount(), and indri::index::Index::uniqueTermCount().
Referenced by main().
void print_term_counts (indri::collection::Repository & r, const std::string & termString)
References indri::index::Index::docListIterator(), indri::index::DocListIterator::DocumentData::document, indri::index::Index::documentLength(), indri::collection::Repository::indexes(), indri::index::Index::iteratorLock(), indri::index::DocListIterator::DocumentData::positions, indri::collection::Repository::processTerm(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::server::LocalQueryServer::termCount().
Referenced by main().
void print_term_positions (indri::collection::Repository & r, const std::string & termString)
References indri::index::Index::docListIterator(), indri::index::DocListIterator::DocumentData::document, indri::index::Index::documentLength(), indri::collection::Repository::indexes(), indri::index::Index::iteratorLock(), indri::index::DocListIterator::DocumentData::positions, indri::collection::Repository::processTerm(), indri::utility::greedy_vector< _Type, _Count >::size(), and indri::server::LocalQueryServer::termCount().
Referenced by main().
void print_vocabulary (indri::collection::Repository & r)
References indri::index::TermData::corpus, indri::index::VocabularyIterator::currentEntry(), indri::index::Index::documentCount(), indri::index::VocabularyIterator::finished(), indri::collection::Repository::indexes(), indri::index::VocabularyIterator::nextEntry(), indri::index::VocabularyIterator::startIteration(), indri::index::TermData::term, indri::index::Index::termCount(), indri::index::DiskTermData::termData, and indri::index::Index::vocabularyIterator().
Referenced by main().
void usage ()
void validate (indri::collection::Repository & r)
References indri::index::TermListFileIterator::currentEntry(), indri::index::Index::documentCount(), indri::index::Index::documentLength(), indri::index::TermListFileIterator::finished(), indri::collection::Repository::indexes(), indri::index::TermListFileIterator::nextEntry(), indri::utility::greedy_vector< _Type, _Count >::size(), indri::index::TermListFileIterator::startIteration(), indri::index::Index::termList(), indri::index::Index::termListFileIterator(), and indri::index::TermList::terms().
Referenced by main().