Indri: IndriBuildIndex.cpp File Reference
IndriBuildIndex.cpp File Reference
#include <algorithm>
#include <cstring>
#include <string>
#include <cctype>
#include "indri/Parameters.hpp"
#include "indri/IndexEnvironment.hpp"
#include <time.h>
#include "indri/Path.hpp"
#include "indri/ConflationPattern.hpp"
#include "lemur/Exception.hpp"
#include "indri/FileTreeIterator.hpp"
#include <vector>
#include <map>
#include "indri/IndriTimer.hpp"
#include "indri/QueryEnvironment.hpp"
#include "indri/Thread.hpp"
#include "indri/SequentialWriteBuffer.hpp"
#include <math.h>
#include "indri/Repository.hpp"
#include "indri/CompressedCollection.hpp"
#include "indri/ScopedLock.hpp"
#include "indri/DirectoryIterator.hpp"
Classes
class StatusMonitor
Functions
static bool _recoverRepository (const std::string &path)
static void buildindex_start_time ()
static void buildindex_print_status (const char *status, int count)
static void buildindex_print_status (const char *status, int count, const char *status2, INT64 count2)
static void buildindex_flush_status ()
static void buildindex_print_event (const char *event)
static void buildindex_print_event (std::string event)
static std::string downcase_string (const std::string &str)
static void downcase_string_vector (std::vector< std::string > &vec)
static bool copy_parameters_to_string_vector (std::vector< std::string > &vec, indri::api::Parameters p, const std::string &parameterName, const std::string *subName=0)
static std::vector< std::string > findConflations (indri::parse::FileClassEnvironmentFactory::Specification *spec, std::string &name)
static bool addNew (std::vector< std::string > &orig, std::vector< std::string > &vec, string &name, std::string &specName, const char *msg)
static bool augmentSpec (indri::parse::FileClassEnvironmentFactory::Specification *spec, std::vector< std::string > &fields, std::vector< std::string > &metadata, std::vector< std::string > &metadataForward, std::vector< std::string > &metadataBackward)
static void process_numeric_fields (indri::api::Parameters parameters, indri::api::IndexEnvironment &env)
static void process_ordinal_fields (indri::api::Parameters parameters, indri::api::IndexEnvironment &env)
static void process_parental_fields (indri::api::Parameters parameters, indri::api::IndexEnvironment &env)
void require_parameter (const char *name, indri::api::Parameters &p)
int main (int argc, char *argv[])
Variables
static indri::utility::IndriTimer g_timer
Function Documentation
static bool _recoverRepository (const std::string & path) [static]
References indri::collection::Repository::close(), indri::collection::Repository::collection(), indri::file::Path::combine(), indri::collection::CompressedCollection::compact(), indri::index::DeletedDocumentList::deletedCount(), indri::collection::Repository::deletedList(), indri::file::DirectoryIterator::end(), indri::file::Path::exists(), indri::collection::CompressedCollection::exists(), indri::collection::Repository::indexes(), indri::index::DeletedDocumentList::markDeleted(), indri::collection::Repository::open(), and indri::file::Path::remove().
Referenced by main().
static bool addNew (std::vector< std::string > & orig, std::vector< std::string > & vec, string & name, std::string & specName, const char * msg) [static]
Add a string to a vector if not already present.
Returns:
true if the string was added.
Referenced by augmentSpec().
static bool augmentSpec (indri::parse::FileClassEnvironmentFactory::Specification * spec, std::vector< std::string > & fields, std::vector< std::string > & metadata, std::vector< std::string > & metadataForward, std::vector< std::string > & metadataBackward) [static]
Add field names to index or metadata for an existing file class specification.
References addNew(), indri::parse::conflations, findConflations(), indri::parse::FileClassEnvironmentFactory::Specification::include, indri::parse::FileClassEnvironmentFactory::Specification::index, indri::parse::FileClassEnvironmentFactory::Specification::metadata, and indri::parse::FileClassEnvironmentFactory::Specification::name.
Referenced by main().
static void buildindex_flush_status () [static]
Referenced by StatusMonitor::operator()().
static void buildindex_print_event (std::string event) [static]
References buildindex_print_event().
static void buildindex_print_event (const char * event) [static]
References indri::utility::IndriTimer::printElapsedSeconds().
Referenced by buildindex_print_event(), main(), and StatusMonitor::operator()().
static void buildindex_print_status (const char * status, int count, const char * status2, INT64 count2) [static]
References indri::utility::IndriTimer::printElapsedSeconds().
static void buildindex_print_status (const char * status, int count) [static]
References indri::utility::IndriTimer::printElapsedSeconds().
Referenced by StatusMonitor::operator()().
static void buildindex_start_time () [static]
References indri::utility::IndriTimer::start().
Referenced by main().
static bool copy_parameters_to_string_vector (std::vector< std::string > & vec, indri::api::Parameters p, const std::string & parameterName, const std::string * subName = 0) [static]
References indri::api::Parameters::exists(), and indri::api::Parameters::size().
Referenced by main().
static std::string downcase_string (const std::string & str) [static]
Referenced by downcase_string_vector(), process_numeric_fields(), process_ordinal_fields(), and process_parental_fields().
static void downcase_string_vector (std::vector< std::string > & vec) [static]
References downcase_string().
Referenced by main().
static std::vector<std::string> findConflations (indri::parse::FileClassEnvironmentFactory::Specification * spec, std::string & name) [static]
Given a Specification and a field name, return a vector containing all of the field names that conflate to that name as well as the original name.
Parameters:
spec The indri::parse::FileClassEnvironmentFactory::Specification to inspect.
name The field name to look for.
Returns:
a vector containing all of the field names that conflate to that name as well as the original name.
References indri::parse::FileClassEnvironmentFactory::Specification::conflations.
Referenced by augmentSpec().
int main (int argc, char * argv[])
References _recoverRepository(), indri::api::IndexEnvironment::addFile(), indri::api::IndexEnvironment::addFileClass(), indri::api::Parameters::append(), augmentSpec(), buildindex_print_event(), buildindex_start_time(), indri::api::IndexEnvironment::close(), copy_parameters_to_string_vector(), indri::api::IndexEnvironment::create(), downcase_string_vector(), indri::file::FileTreeIterator::end(), indri::collection::Repository::exists(), indri::file::Path::extension(), indri::api::Parameters::get(), indri::api::IndexEnvironment::getFileClassSpec(), INDRI_DISTRIBUTION, indri::api::Parameters::instance(), indri::file::Path::isDirectory(), indri::api::Parameters::loadCommandLine(), indri::parse::OAHintDefault, indri::parse::OAHintOrderedAnnotations, indri::parse::OAHintSizeBuffers, indri::api::IndexEnvironment::open(), process_numeric_fields(), process_ordinal_fields(), process_parental_fields(), require_parameter(), indri::api::Parameters::set(), indri::api::IndexEnvironment::setAnchorTextPath(), indri::api::IndexEnvironment::setBlackList(), indri::api::IndexEnvironment::setDocumentRoot(), indri::api::IndexEnvironment::setIndexedFields(), indri::api::IndexEnvironment::setInjectURL(), indri::api::IndexEnvironment::setMemory(), indri::api::IndexEnvironment::setMetadataIndexedFields(), indri::api::IndexEnvironment::setNormalization(), indri::api::IndexEnvironment::setOffsetAnnotationIndexHint(), indri::api::IndexEnvironment::setOffsetAnnotationsPath(), indri::api::IndexEnvironment::setOffsetMetadataPath(), indri::api::IndexEnvironment::setStemmer(), indri::api::IndexEnvironment::setStopwords(), indri::api::IndexEnvironment::setStoreDocs(), and indri::api::Parameters::size().
static void process_numeric_fields (indri::api::Parameters parameters, indri::api::IndexEnvironment & env) [static]
References downcase_string(), indri::api::Parameters::get(), indri::api::IndexEnvironment::setNumericField(), and indri::api::Parameters::size().
Referenced by main().
static void process_ordinal_fields (indri::api::Parameters parameters, indri::api::IndexEnvironment & env) [static]
References downcase_string(), indri::api::Parameters::get(), indri::api::IndexEnvironment::setOrdinalField(), and indri::api::Parameters::size().
Referenced by main().
static void process_parental_fields (indri::api::Parameters parameters, indri::api::IndexEnvironment & env) [static]
References downcase_string(), indri::api::Parameters::get(), indri::api::IndexEnvironment::setParentalField(), and indri::api::Parameters::size().
Referenced by main().
void require_parameter (const char * name, indri::api::Parameters & p)
References indri::api::Parameters::exists().
Referenced by main().
Variable Documentation
indri::utility::IndriTimer g_timer [static]