Indri: IndriDaemon.cpp File Reference
IndriDaemon.cpp File Reference
#include "indri/indri-platform.h"
#include "lemur/lemur-compat.hpp"
#include "indri/LocalQueryServer.hpp"
#include "indri/NetworkStream.hpp"
#include "indri/NetworkListener.hpp"
#include "indri/NetworkServerStub.hpp"
#include "indri/Parameters.hpp"
#include "lemur/Exception.hpp"
#include "indri/Mutex.hpp"
#include "indri/ScopedLock.hpp"
#include <time.h>
Classes
struct connection_info
Functions
void log_message (const char *peer, const char *message)
void connection_thread (void *c)
connection_info * build_connection (indri::net::NetworkStream *stream, indri::server::LocalQueryServer *server)
void clean_connections (std::list< connection_info * > &connections)
void wait_connections (std::list< connection_info * > &connections)
int main (int argc, char *argv[])
Variables
static bool verbose = false
static indri::thread::Mutex loglock
Function Documentation
connection_info* build_connection (indri::net::NetworkStream * stream, indri::server::LocalQueryServer * server)
References connection_info::active, connection_thread(), connection_info::server, connection_info::stream, and connection_info::thread.
Referenced by main().
void clean_connections (std::list< connection_info * > & connections)
References indri::thread::Thread::join(), connection_info::stream, and connection_info::thread.
Referenced by main(), and wait_connections().
void connection_thread (void * c)
References connection_info::active, indri::net::NetworkMessageStream::alive(), log_message(), indri::net::NetworkStream::peer(), indri::net::NetworkMessageStream::read(), connection_info::server, and connection_info::stream.
Referenced by build_connection().
void log_message (const char * peer, const char * message)
Referenced by connection_thread().
int main (int argc, char * argv[])
References indri::net::NetworkListener::accept(), build_connection(), clean_connections(), indri::collection::Repository::close(), indri::api::Parameters::get(), INDRID_PORT, indri::api::Parameters::instance(), indri::net::NetworkListener::listen(), indri::api::Parameters::loadCommandLine(), indri::collection::Repository::openRead(), verbose, and wait_connections().
void wait_connections (std::list< connection_info * > & connections)
References clean_connections(), and indri::thread::Thread::yield().
Referenced by main().
Variable Documentation
indri::thread::Mutex loglock [static]
bool verbose = false [static]
Referenced by main().