Indri: indri_phpwrap.cpp File Reference
indri_phpwrap.cpp File Reference
#include <string.h>
#include "zend.h"
#include "zend_API.h"
#include "zend_exceptions.h"
#include "php.h"
#include "ext/standard/php_string.h"
#include "php_ini.h"
#include "ext/standard/info.h"
#include "php_libindri_php.h"
#include "indri/indri-platform.h"
#include "lemur-compat.hpp"
#include "indri/QueryEnvironment.hpp"
#include "indri/QueryExpander.hpp"
#include "indri/RMExpander.hpp"
#include "indri/PonteExpander.hpp"
#include "indri/ScoredExtentResult.hpp"
#include "indri/ParsedDocument.hpp"
#include "indri/IndexEnvironment.hpp"
#include "indri/Parameters.hpp"
#include "indri/ConflationPattern.hpp"
#include "indri/ReformulateQuery.hpp"
#include "Exception.hpp"
#include <stdexcept>
#include <string>
#include <vector>
Classes
struct swig_type_info
struct swig_cast_info
struct swig_module_info
struct swig_object_wrapper
Defines
#define SWIGPHP
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_TYPE_TABLE_NAME
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIG_BUFFER_SIZE 1024
#define SWIG_POINTER_DISOWN 0x1
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_POINTER_OWN 0x1
#define SWIG_OK (0)
#define SWIG_ERROR (-1)
#define SWIG_IsOK(r) (r >= 0)
#define SWIG_ArgError(r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_AddNewMask(r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_AddCast
#define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#define SWIG_ZEND_NAMED_FE(ZN, N, A) ZEND_NAMED_FE(ZN, N, A)
#define Z_SET_ISREF_P(z) (z)->is_ref = 1
#define Z_SET_REFCOUNT_P(z, rc) (z)->refcount = (rc)
#define SWIG_LONG_CONSTANT(N, V) zend_register_long_constant((char*)#N, sizeof(#N), V, CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC)
#define SWIG_DOUBLE_CONSTANT(N, V) zend_register_double_constant((char*)#N, sizeof(#N), V, CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC)
#define SWIG_STRING_CONSTANT(N, V) zend_register_stringl_constant((char*)#N, sizeof(#N), (char*)(V), strlen(V), CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC)
#define SWIG_CHAR_CONSTANT(N, V)
#define SWIG_ConvertPtr(obj, pp, type, flags) SWIG_ZTS_ConvertPtr(obj,pp,type,flags TSRMLS_CC)
#define SWIG_fail goto fail
#define SWIG_PHP_Arg_Error_Msg(argnum, extramsg) "Error in argument " #argnum " "#extramsg
#define SWIG_PHP_Error(code, msg) do { SWIG_ErrorCode() = code; SWIG_ErrorMsg() = msg; SWIG_fail; } while (0)
#define SWIG_contract_assert(expr, msg) if (!(expr)) { zend_printf("Contract Assert Failed %s\n",msg); } else
#define SWIG_GetModule(clientdata) SWIG_Php_GetModule()
#define SWIG_SetModule(clientdata, pointer) SWIG_Php_SetModule(pointer)
#define SWIG_SetPointerZval(a, b, c, d) SWIG_ZTS_SetPointerZval(a,b,c,d TSRMLS_CC)
#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a))
#define SWIG_MEMBER_PTR ((char*)"CLASS::*")
#define SWIG_UnknownError -1
#define SWIG_IOError -2
#define SWIG_RuntimeError -3
#define SWIG_IndexError -4
#define SWIG_TypeError -5
#define SWIG_DivisionByZero -6
#define SWIG_OverflowError -7
#define SWIG_SyntaxError -8
#define SWIG_ValueError -9
#define SWIG_SystemError -10
#define SWIG_AttributeError -11
#define SWIG_MemoryError -12
#define SWIG_NullReferenceError -13
#define SWIGTYPE_p_indri__api__Parameters swig_types[0]
#define SWIGTYPE_p_indri__api__ParsedDocument swig_types[1]
#define SWIGTYPE_p_indri__api__QueryAnnotation swig_types[2]
#define SWIGTYPE_p_indri__api__QueryAnnotationNode swig_types[3]
#define SWIGTYPE_p_indri__api__QueryEnvironment swig_types[4]
#define SWIGTYPE_p_indri__api__ScoredExtentResult swig_types[5]
#define SWIGTYPE_p_indri__parse__TermExtent swig_types[6]
#define SWIGTYPE_p_indri__query__PonteExpander swig_types[7]
#define SWIGTYPE_p_indri__query__QueryExpander swig_types[8]
#define SWIGTYPE_p_indri__query__RMExpander swig_types[9]
#define SWIGTYPE_p_long_long swig_types[10]
#define SWIGTYPE_p_std__vectorT_indri__api__ScoredExtentResult_t swig_types[11]
#define SWIGTYPE_p_std__vectorT_lemur__api__DOCID_T_t swig_types[12]
#define SWIGTYPE_p_std__vectorT_std__string_t swig_types[13]
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_ErrorMsg() (libindri_php_globals.error_msg)
#define SWIG_ErrorCode() (libindri_php_globals.error_code)
#define SWIG_name "libindri_php"
#define SWIG_exception(code, msg) { zend_error(E_ERROR, msg); }
#define onetermCount termCount
#define onedocumentCount documentCount
#define runQuerydocset runQuery
#define runAnnotatedQuerydocset runAnnotatedQuery
#define documentsdocids documents
#define documentMetadatadocids documentMetadata
#define set_int set
#define set_bool set
#define set_string set
#define set_UINT64 set
#define set_double set
#define get_bool get
#define get_int get
#define get_string get
#define get_INT64 get
#define get_double get
#define ZEND_MODULE_BUILD_ID (char*)"API" ZEND_TOSTR(ZEND_MODULE_API_NO) ZEND_BUILD_TS ZEND_BUILD_DEBUG ZEND_BUILD_SYSTEM ZEND_BUILD_EXTRA
#define SWIG_php_minit PHP_MINIT_FUNCTION(libindri_php)
Typedefs
typedef void *(* swig_converter_func)(void *, int *)
typedef struct swig_type_info *(* swig_dycast_func)(void **)
Functions
SWIGRUNTIME int SWIG_TypeNameComp (const char *f1, const char *l1, const char *f2, const char *l2)
SWIGRUNTIME int SWIG_TypeEquiv (const char *nb, const char *tb)
SWIGRUNTIME int SWIG_TypeCompare (const char *nb, const char *tb)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheck (const char *c, swig_type_info *ty)
SWIGRUNTIME swig_cast_info * SWIG_TypeCheckStruct (swig_type_info *from, swig_type_info *ty)
SWIGRUNTIMEINLINE void * SWIG_TypeCast (swig_cast_info *ty, void *ptr, int *newmemory)
SWIGRUNTIME swig_type_info * SWIG_TypeDynamicCast (swig_type_info *ty, void **ptr)
SWIGRUNTIMEINLINE const char * SWIG_TypeName (const swig_type_info *ty)
SWIGRUNTIME const char * SWIG_TypePrettyName (const swig_type_info *type)
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info *ti, void *clientdata)
SWIGRUNTIME swig_type_info * SWIG_MangledTypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME swig_type_info * SWIG_TypeQueryModule (swig_module_info *start, swig_module_info *end, const char *name)
SWIGRUNTIME char * SWIG_PackData (char *c, void *ptr, size_t sz)
SWIGRUNTIME const char * SWIG_UnpackData (const char *c, void *ptr, size_t sz)
SWIGRUNTIME char * SWIG_PackVoidPtr (char *buff, void *ptr, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackVoidPtr (const char *c, void **ptr, const char *name)
SWIGRUNTIME char * SWIG_PackDataName (char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
SWIGRUNTIME const char * SWIG_UnpackDataName (const char *c, void *ptr, size_t sz, const char *name)
static ZEND_RSRC_DTOR_FUNC (SWIG_landfill)
static void SWIG_ZTS_SetPointerZval (zval *z, void *ptr, swig_type_info *type, int newobject TSRMLS_DC)
static void * SWIG_ZTS_ConvertResourceData (void *p, const char *type_name, swig_type_info *ty TSRMLS_DC)
static void * SWIG_ZTS_ConvertResourcePtr (zval *z, swig_type_info *ty, int flags TSRMLS_DC)
static int SWIG_ZTS_ConvertPtr (zval *z, void **ptr, swig_type_info *ty, int flags TSRMLS_DC)
static swig_module_info * SWIG_Php_GetModule ()
static void SWIG_Php_SetModule (swig_module_info *pointer)
static void member_ptr_dtor (zend_rsrc_list_entry *rsrc TSRMLS_DC)
static void libindri_php_init_globals (zend_libindri_php_globals *globals)
static void libindri_php_destroy_globals (zend_libindri_php_globals *globals)
static void SWIG_ResetError ()
ZEND_NAMED_FUNCTION (_wrap_swig_libindri_php_alter_newobject)
ZEND_NAMED_FUNCTION (_wrap_swig_libindri_php_get_newobject)
static void * _p_indri__query__RMExpanderTo_p_indri__query__QueryExpander (void *x, int *SWIGUNUSEDPARM(newmemory))
static void * _p_indri__query__PonteExpanderTo_p_indri__query__QueryExpander (void *x, int *SWIGUNUSEDPARM(newmemory))
zval * php_makeQueryAnnotationNode (indri::api::QueryAnnotationNode *inNode)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_set)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_get)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_set)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_get)
static void __wrap_delete_TermExtent (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_new_TermExtent)
ZEND_NAMED_FUNCTION (_wrap_new_Parameters)
static void __wrap_delete_Parameters (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_bool)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_int)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_double)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_INT64)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_string)
ZEND_NAMED_FUNCTION (_wrap_Parameters_remove)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_bool)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_string)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_int)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_UINT64)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_double)
ZEND_NAMED_FUNCTION (_wrap_Parameters_clear)
ZEND_NAMED_FUNCTION (_wrap_Parameters_size)
ZEND_NAMED_FUNCTION (_wrap_Parameters_exists)
ZEND_NAMED_FUNCTION (_wrap_Parameters_load)
static void __wrap_delete_ScoredExtentResult (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_new_ScoredExtentResult)
static void __wrap_delete_ParsedDocument (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_ParsedDocument_getContent)
ZEND_NAMED_FUNCTION (_wrap_new_ParsedDocument)
ZEND_NAMED_FUNCTION (_wrap_new_QueryAnnotationNode)
static void __wrap_delete_QueryAnnotationNode (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getQueryTree)
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getAnnotations)
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getResults)
static void __wrap_delete_QueryAnnotation (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
static void __wrap_delete_QueryEnvironment (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addServer)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addIndex)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_close)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setMemory)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setScoringRules)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setStopwords)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuery)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuerydocset)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuery)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuerydocset)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentsdocids)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documents)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadatadocids)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadata)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentIDsFromMetadata)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onetermCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termFieldCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemFieldCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_fieldList)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onedocumentCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount__SWIG_0)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount__SWIG_1)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount__SWIG_0)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount__SWIG_1)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList__SWIG_0)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList__SWIG_1)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentLength)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setFormulationParameters)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_reformulateQuery)
ZEND_NAMED_FUNCTION (_wrap_new_QueryEnvironment)
static void __wrap_delete_QueryExpander (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery__SWIG_0)
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery__SWIG_1)
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery)
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_expand)
ZEND_NAMED_FUNCTION (_wrap_new_RMExpander)
ZEND_NAMED_FUNCTION (_wrap_RMExpander_expand)
static void __wrap_delete_RMExpander (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
ZEND_NAMED_FUNCTION (_wrap_new_PonteExpander)
ZEND_NAMED_FUNCTION (_wrap_PonteExpander_expand)
static void __wrap_delete_PonteExpander (zend_rsrc_list_entry *rsrc, const char *type_name TSRMLS_DC)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__Parameters)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__QueryAnnotation)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__parse__TermExtent)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__QueryEnvironment)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_long_long)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_std__vectorT_indri__api__ScoredExtentResult_t)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__query__PonteExpander)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__query__RMExpander)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__query__QueryExpander)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_std__vectorT_lemur__api__DOCID_T_t)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__ScoredExtentResult)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__ParsedDocument)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_std__vectorT_std__string_t)
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__QueryAnnotationNode)
SWIGEXPORT zend_module_entry * get_module (void)
SWIGRUNTIME void SWIG_InitializeModule (void *clientdata)
SWIGRUNTIME void SWIG_PropagateClientData (void)
Variables
static const char * default_error_msg = "Unknown error occurred"
static int default_error_code = E_ERROR
static char const_name [] = "swig_runtime_data_type_pointer"
static int le_member_ptr
static swig_type_info * swig_types [15]
static swig_module_info swig_module = {swig_types, 14, 0, 0, 0, 0}
const char * error_msg
int error_code
static swig_type_info _swigt__p_indri__api__Parameters = {"_p_indri__api__Parameters", "indri::api::Parameters *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__api__ParsedDocument = {"_p_indri__api__ParsedDocument", "indri::api::ParsedDocument *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__api__QueryAnnotation = {"_p_indri__api__QueryAnnotation", "indri::api::QueryAnnotation *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__api__QueryAnnotationNode = {"_p_indri__api__QueryAnnotationNode", "indri::api::QueryAnnotationNode *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__api__QueryEnvironment = {"_p_indri__api__QueryEnvironment", "indri::api::QueryEnvironment *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__api__ScoredExtentResult = {"_p_indri__api__ScoredExtentResult", "indri::api::ScoredExtentResult *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__parse__TermExtent = {"_p_indri__parse__TermExtent", "indri::parse::TermExtent *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__query__PonteExpander = {"_p_indri__query__PonteExpander", "indri::query::PonteExpander *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__query__QueryExpander = {"_p_indri__query__QueryExpander", "indri::query::QueryExpander *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_indri__query__RMExpander = {"_p_indri__query__RMExpander", "indri::query::RMExpander *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_long_long = {"_p_long_long", "UINT64 *|INT64 *|long long *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_std__vectorT_indri__api__ScoredExtentResult_t = {"_p_std__vectorT_indri__api__ScoredExtentResult_t", "std::vector< indri::api::ScoredExtentResult > *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_std__vectorT_lemur__api__DOCID_T_t = {"_p_std__vectorT_lemur__api__DOCID_T_t", "std::vector< lemur::api::DOCID_T > *", 0, 0, (void*)0, 0}
static swig_type_info _swigt__p_std__vectorT_std__string_t = {"_p_std__vectorT_std__string_t", "std::vector< std::string > *", 0, 0, (void*)0, 0}
static swig_type_info * swig_type_initial []
static swig_cast_info _swigc__p_indri__api__Parameters [] = { {&_swigt__p_indri__api__Parameters, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__api__ParsedDocument [] = { {&_swigt__p_indri__api__ParsedDocument, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__api__QueryAnnotation [] = { {&_swigt__p_indri__api__QueryAnnotation, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__api__QueryAnnotationNode [] = { {&_swigt__p_indri__api__QueryAnnotationNode, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__api__QueryEnvironment [] = { {&_swigt__p_indri__api__QueryEnvironment, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__api__ScoredExtentResult [] = { {&_swigt__p_indri__api__ScoredExtentResult, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__parse__TermExtent [] = { {&_swigt__p_indri__parse__TermExtent, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__query__PonteExpander [] = { {&_swigt__p_indri__query__PonteExpander, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__query__QueryExpander [] = { {&_swigt__p_indri__query__QueryExpander, 0, 0, 0}, {&_swigt__p_indri__query__RMExpander, _p_indri__query__RMExpanderTo_p_indri__query__QueryExpander, 0, 0}, {&_swigt__p_indri__query__PonteExpander, _p_indri__query__PonteExpanderTo_p_indri__query__QueryExpander, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_indri__query__RMExpander [] = { {&_swigt__p_indri__query__RMExpander, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_long_long [] = { {&_swigt__p_long_long, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_std__vectorT_indri__api__ScoredExtentResult_t [] = { {&_swigt__p_std__vectorT_indri__api__ScoredExtentResult_t, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_std__vectorT_lemur__api__DOCID_T_t [] = { {&_swigt__p_std__vectorT_lemur__api__DOCID_T_t, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info _swigc__p_std__vectorT_std__string_t [] = { {&_swigt__p_std__vectorT_std__string_t, 0, 0, 0},{0, 0, 0, 0}}
static swig_cast_info * swig_cast_initial []
static int le_swig__p_indri__api__Parameters = 0
static int le_swig__p_indri__api__QueryAnnotation = 0
static int le_swig__p_indri__parse__TermExtent = 0
static int le_swig__p_indri__api__QueryEnvironment = 0
static int le_swig__p_long_long = 0
static int le_swig__p_std__vectorT_indri__api__ScoredExtentResult_t = 0
static int le_swig__p_indri__query__PonteExpander = 0
static int le_swig__p_indri__query__RMExpander = 0
static int le_swig__p_indri__query__QueryExpander = 0
static int le_swig__p_std__vectorT_lemur__api__DOCID_T_t = 0
static int le_swig__p_indri__api__ScoredExtentResult = 0
static int le_swig__p_indri__api__ParsedDocument = 0
static int le_swig__p_std__vectorT_std__string_t = 0
static int le_swig__p_indri__api__QueryAnnotationNode = 0
static zend_function_entry libindri_php_functions []
zend_module_entry libindri_php_module_entry
zend_module_entry * SWIG_module_entry = &libindri_php_module_entry
Define Documentation
#define documentMetadatadocids documentMetadata
Referenced by ZEND_NAMED_FUNCTION().
#define documentsdocids documents
Referenced by ZEND_NAMED_FUNCTION().
#define get_bool get
#define get_double get
#define get_int get
#define get_INT64 get
#define get_string get
Referenced by ZEND_NAMED_FUNCTION().
#define onedocumentCount documentCount
#define onetermCount termCount
#define runAnnotatedQuerydocset runAnnotatedQuery
#define runQuerydocset runQuery
Referenced by ZEND_NAMED_FUNCTION().
#define set_bool set
Referenced by ZEND_NAMED_FUNCTION().
#define set_double set
Referenced by ZEND_NAMED_FUNCTION().
#define set_int set
Referenced by ZEND_NAMED_FUNCTION().
#define set_string set
Referenced by ZEND_NAMED_FUNCTION().
#define set_UINT64 set
Referenced by ZEND_NAMED_FUNCTION().
#define SWIG_AddCast
#define SWIG_AddNewMask (r) (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_AddTmpMask (r) (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_ArgError (r) ((r != SWIG_ERROR) ? r : SWIG_TypeError)
#define SWIG_as_voidptr (a) const_cast< void * >(static_cast< const void * >(a))
#define SWIG_AttributeError -11
#define SWIG_BADOBJ (SWIG_ERROR)
#define SWIG_BUFFER_SIZE 1024
#define SWIG_CAST_NEW_MEMORY 0x2
#define SWIG_CASTRANKLIMIT (1 << 8)
#define SWIG_CHAR_CONSTANT (N, V)
Value:
do {\
    static char swig_char = (V);\
    zend_register_stringl_constant((char*)#N, sizeof(#N), &swig_char, 1, CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC);\
} while (0)
#define SWIG_CheckState (r) (SWIG_IsOK(r) ? 1 : 0)
#define SWIG_contract_assert (expr, msg) if (!(expr)) { zend_printf("Contract Assert Failed %s\n",msg); } else
#define SWIG_ConvertPtr (obj, pp, type, flags) SWIG_ZTS_ConvertPtr(obj,pp,type,flags TSRMLS_CC)
Referenced by ZEND_NAMED_FUNCTION().
#define SWIG_DelNewMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_DelTmpMask (r) (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_DivisionByZero -6
#define SWIG_DOUBLE_CONSTANT (N, V) zend_register_double_constant((char*)#N, sizeof(#N), V, CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC)
#define SWIG_ERROR (-1)
#define SWIG_ErrorCode () (libindri_php_globals.error_code)
Referenced by __wrap_delete_Parameters(), __wrap_delete_ParsedDocument(), __wrap_delete_PonteExpander(), __wrap_delete_QueryAnnotation(), __wrap_delete_QueryAnnotationNode(), __wrap_delete_QueryEnvironment(), __wrap_delete_QueryExpander(), __wrap_delete_RMExpander(), __wrap_delete_ScoredExtentResult(), __wrap_delete_TermExtent(), SWIG_ResetError(), and ZEND_NAMED_FUNCTION().
#define SWIG_ErrorMsg () (libindri_php_globals.error_msg)
Referenced by __wrap_delete_Parameters(), __wrap_delete_ParsedDocument(), __wrap_delete_PonteExpander(), __wrap_delete_QueryAnnotation(), __wrap_delete_QueryAnnotationNode(), __wrap_delete_QueryEnvironment(), __wrap_delete_QueryExpander(), __wrap_delete_RMExpander(), __wrap_delete_ScoredExtentResult(), __wrap_delete_TermExtent(), SWIG_ResetError(), and ZEND_NAMED_FUNCTION().
#define SWIG_exception (code, msg) { zend_error(E_ERROR, msg); }
#define SWIG_fail goto fail
#define SWIG_GetModule (clientdata) SWIG_Php_GetModule()
Referenced by SWIG_InitializeModule().
#define SWIG_IndexError -4
#define SWIG_IOError -2
#define SWIG_IsNewObj (r) (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_IsOK (r) (r >= 0)
#define SWIG_IsTmpObj (r) (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))
#define SWIG_LONG_CONSTANT (N, V) zend_register_long_constant((char*)#N, sizeof(#N), V, CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC)
#define SWIG_MangledTypeQuery (name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MEMBER_PTR ((char*)"CLASS::*")
#define SWIG_MemoryError -12
#define SWIG_name "libindri_php"
#define SWIG_NEWOBJ (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_NEWOBJMASK (SWIG_CASTRANKLIMIT << 1)
#define SWIG_NullReferenceError -13
#define SWIG_OK (0)
#define SWIG_OLDOBJ (SWIG_OK)
#define SWIG_OverflowError -7
#define SWIG_PHP_Arg_Error_Msg (argnum, extramsg) "Error in argument " #argnum " "#extramsg
#define SWIG_PHP_Error (code, msg) do { SWIG_ErrorCode() = code; SWIG_ErrorMsg() = msg; SWIG_fail; } while (0)
Referenced by ZEND_NAMED_FUNCTION().
#define SWIG_php_minit PHP_MINIT_FUNCTION(libindri_php)
#define SWIG_POINTER_DISOWN 0x1
Referenced by SWIG_ZTS_ConvertResourcePtr().
#define SWIG_POINTER_OWN 0x1
#define SWIG_RUNTIME_VERSION "4"
#define SWIG_RuntimeError -3
#define SWIG_SetModule (clientdata, pointer) SWIG_Php_SetModule(pointer)
Referenced by SWIG_InitializeModule().
#define SWIG_SetPointerZval (a, b, c, d) SWIG_ZTS_SetPointerZval(a,b,c,d TSRMLS_CC)
Referenced by php_makeQueryAnnotationNode(), and ZEND_NAMED_FUNCTION().
#define SWIG_STRING_CONSTANT (N, V) zend_register_stringl_constant((char*)#N, sizeof(#N), (char*)(V), strlen(V), CONST_CS | CONST_PERSISTENT, module_number TSRMLS_CC)
#define SWIG_SyntaxError -8
#define SWIG_SystemError -10
#define SWIG_TMPOBJ (SWIG_OK | SWIG_TMPOBJMASK)
#define SWIG_TMPOBJMASK (SWIG_NEWOBJMASK << 1)
#define SWIG_TYPE_TABLE_NAME
#define SWIG_TypeError -5
#define SWIG_TypeQuery (name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_UnknownError -1
#define SWIG_ValueError -9
#define SWIG_ZEND_NAMED_FE (ZN, N, A) ZEND_NAMED_FE(ZN, N, A)
#define SWIGPHP
#define SWIGRUNTIME SWIGINTERN
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#define SWIGTYPE_p_indri__api__Parameters swig_types[0]
Referenced by __wrap_delete_Parameters(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__api__ParsedDocument swig_types[1]
Referenced by __wrap_delete_ParsedDocument(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__api__QueryAnnotation swig_types[2]
Referenced by __wrap_delete_QueryAnnotation(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__api__QueryAnnotationNode swig_types[3]
Referenced by __wrap_delete_QueryAnnotationNode(), php_makeQueryAnnotationNode(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__api__QueryEnvironment swig_types[4]
Referenced by __wrap_delete_QueryEnvironment(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__api__ScoredExtentResult swig_types[5]
Referenced by __wrap_delete_ScoredExtentResult(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__parse__TermExtent swig_types[6]
Referenced by __wrap_delete_TermExtent(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__query__PonteExpander swig_types[7]
Referenced by __wrap_delete_PonteExpander(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__query__QueryExpander swig_types[8]
Referenced by __wrap_delete_QueryExpander(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_indri__query__RMExpander swig_types[9]
Referenced by __wrap_delete_RMExpander(), ZEND_NAMED_FUNCTION(), and ZEND_RSRC_DTOR_FUNC().
#define SWIGTYPE_p_long_long swig_types[10]
#define SWIGTYPE_p_std__vectorT_indri__api__ScoredExtentResult_t swig_types[11]
#define SWIGTYPE_p_std__vectorT_lemur__api__DOCID_T_t swig_types[12]
#define SWIGTYPE_p_std__vectorT_std__string_t swig_types[13]
#define Z_SET_ISREF_P (z) (z)->is_ref = 1
Referenced by SWIG_ZTS_SetPointerZval().
#define Z_SET_REFCOUNT_P (z, rc) (z)->refcount = (rc)
Referenced by SWIG_ZTS_SetPointerZval().
#define ZEND_MODULE_BUILD_ID (char*)"API" ZEND_TOSTR(ZEND_MODULE_API_NO) ZEND_BUILD_TS ZEND_BUILD_DEBUG ZEND_BUILD_SYSTEM ZEND_BUILD_EXTRA
Typedef Documentation
typedef void*(* swig_converter_func)(void *, int *)
typedef struct swig_type_info*(* swig_dycast_func)(void **)
Function Documentation
static void __wrap_delete_Parameters (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__api__Parameters.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_ParsedDocument (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__api__ParsedDocument.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_PonteExpander (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__query__PonteExpander.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_QueryAnnotation (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__api__QueryAnnotation.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_QueryAnnotationNode (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__api__QueryAnnotationNode.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_QueryEnvironment (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__api__QueryEnvironment.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_QueryExpander (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__query__QueryExpander.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_RMExpander (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__query__RMExpander.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_ScoredExtentResult (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__api__ScoredExtentResult.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void __wrap_delete_TermExtent (zend_rsrc_list_entry * rsrc, const char *type_name TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ZTS_ConvertResourceData(), and SWIGTYPE_p_indri__parse__TermExtent.
Referenced by ZEND_RSRC_DTOR_FUNC().
static void* _p_indri__query__PonteExpanderTo_p_indri__query__QueryExpander (void * x, int * SWIGUNUSEDPARMnewmemory) [static]
static void* _p_indri__query__RMExpanderTo_p_indri__query__QueryExpander (void * x, int * SWIGUNUSEDPARMnewmemory) [static]
SWIGEXPORT zend_module_entry* get_module (void)
static void libindri_php_destroy_globals (zend_libindri_php_globals * globals) [static]
static void libindri_php_init_globals (zend_libindri_php_globals * globals) [static]
References default_error_code, and default_error_msg.
static void member_ptr_dtor (zend_rsrc_list_entry *rsrc TSRMLS_DC) [static]
zval* php_makeQueryAnnotationNode (indri::api::QueryAnnotationNode * inNode)
References SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__QueryAnnotationNode.
Referenced by ZEND_NAMED_FUNCTION().
SWIGRUNTIME void SWIG_InitializeModule (void * clientdata)
References swig_type_info::cast, swig_module_info::cast_initial, swig_type_info::clientdata, swig_type_info::name, swig_cast_info::next, swig_module_info::next, swig_cast_info::prev, swig_module_info::size, SWIG_GetModule, SWIG_MangledTypeQueryModule(), SWIG_SetModule, SWIG_TypeCheck(), swig_cast_info::type, swig_module_info::type_initial, and swig_module_info::types.
SWIGRUNTIME swig_type_info* SWIG_MangledTypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_type_info::name, swig_module_info::next, swig_module_info::size, and swig_module_info::types.
Referenced by SWIG_InitializeModule(), and SWIG_TypeQueryModule().
SWIGRUNTIME char* SWIG_PackData (char * c, void * ptr, size_t sz)
Referenced by SWIG_PackDataName(), and SWIG_PackVoidPtr().
SWIGRUNTIME char* SWIG_PackDataName (char * buff, void * ptr, size_t sz, const char * name, size_t bsz)
References SWIG_PackData().
SWIGRUNTIME char* SWIG_PackVoidPtr (char * buff, void * ptr, const char * name, size_t bsz)
References SWIG_PackData().
static swig_module_info* SWIG_Php_GetModule () [static]
References const_name.
static void SWIG_Php_SetModule (swig_module_info * pointer) [static]
References const_name.
SWIGRUNTIME void SWIG_PropagateClientData (void)
References swig_type_info::cast, swig_type_info::clientdata, swig_cast_info::converter, swig_cast_info::next, swig_module_info::size, SWIG_TypeClientData(), swig_cast_info::type, and swig_module_info::types.
static void SWIG_ResetError () [static]
References default_error_code, default_error_msg, SWIG_ErrorCode, and SWIG_ErrorMsg.
Referenced by ZEND_NAMED_FUNCTION().
SWIGRUNTIMEINLINE void* SWIG_TypeCast (swig_cast_info * ty, void * ptr, int * newmemory)
References swig_cast_info::converter.
Referenced by SWIG_ZTS_ConvertResourceData().
SWIGRUNTIME swig_cast_info* SWIG_TypeCheck (const char * c, swig_type_info * ty)
References swig_type_info::cast, swig_type_info::name, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
Referenced by SWIG_InitializeModule(), and SWIG_ZTS_ConvertResourceData().
SWIGRUNTIME swig_cast_info* SWIG_TypeCheckStruct (swig_type_info * from, swig_type_info * ty)
References swig_type_info::cast, swig_cast_info::next, swig_cast_info::prev, and swig_cast_info::type.
SWIGRUNTIME void SWIG_TypeClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::cast, swig_type_info::clientdata, swig_cast_info::converter, swig_cast_info::next, and swig_cast_info::type.
Referenced by SWIG_PropagateClientData(), and SWIG_TypeNewClientData().
SWIGRUNTIME int SWIG_TypeCompare (const char * nb, const char * tb)
References SWIG_TypeNameComp().
SWIGRUNTIME swig_type_info* SWIG_TypeDynamicCast (swig_type_info * ty, void ** ptr)
References swig_type_info::dcast.
SWIGRUNTIME int SWIG_TypeEquiv (const char * nb, const char * tb)
References SWIG_TypeNameComp().
Referenced by SWIG_TypeQueryModule().
SWIGRUNTIMEINLINE const char* SWIG_TypeName (const swig_type_info * ty)
References swig_type_info::name.
SWIGRUNTIME int SWIG_TypeNameComp (const char * f1, const char * l1, const char * f2, const char * l2)
Referenced by SWIG_TypeCompare(), and SWIG_TypeEquiv().
SWIGRUNTIME void SWIG_TypeNewClientData (swig_type_info * ti, void * clientdata)
References swig_type_info::owndata, and SWIG_TypeClientData().
SWIGRUNTIME const char* SWIG_TypePrettyName (const swig_type_info * type)
References swig_type_info::name, and swig_type_info::str.
SWIGRUNTIME swig_type_info* SWIG_TypeQueryModule (swig_module_info * start, swig_module_info * end, const char * name)
References swig_module_info::next, swig_module_info::size, swig_type_info::str, SWIG_MangledTypeQueryModule(), SWIG_TypeEquiv(), and swig_module_info::types.
SWIGRUNTIME const char* SWIG_UnpackData (const char * c, void * ptr, size_t sz)
Referenced by SWIG_UnpackDataName(), and SWIG_UnpackVoidPtr().
SWIGRUNTIME const char* SWIG_UnpackDataName (const char * c, void * ptr, size_t sz, const char * name)
References SWIG_UnpackData().
SWIGRUNTIME const char* SWIG_UnpackVoidPtr (const char * c, void ** ptr, const char * name)
References SWIG_UnpackData().
static int SWIG_ZTS_ConvertPtr (zval * z, void ** ptr, swig_type_info * ty, int flags TSRMLS_DC) [static]
References SWIG_ZTS_ConvertResourcePtr().
static void* SWIG_ZTS_ConvertResourceData (void * p, const char * type_name, swig_type_info *ty TSRMLS_DC) [static]
References SWIG_TypeCast(), and SWIG_TypeCheck().
Referenced by __wrap_delete_Parameters(), __wrap_delete_ParsedDocument(), __wrap_delete_PonteExpander(), __wrap_delete_QueryAnnotation(), __wrap_delete_QueryAnnotationNode(), __wrap_delete_QueryEnvironment(), __wrap_delete_QueryExpander(), __wrap_delete_RMExpander(), __wrap_delete_ScoredExtentResult(), __wrap_delete_TermExtent(), and SWIG_ZTS_ConvertResourcePtr().
static void* SWIG_ZTS_ConvertResourcePtr (zval * z, swig_type_info * ty, int flags TSRMLS_DC) [static]
References swig_object_wrapper::newobject, swig_object_wrapper::ptr, SWIG_POINTER_DISOWN, and SWIG_ZTS_ConvertResourceData().
Referenced by SWIG_ZTS_ConvertPtr().
static void SWIG_ZTS_SetPointerZval (zval * z, void * ptr, swig_type_info * type, int newobject TSRMLS_DC) [static]
References swig_type_info::clientdata, swig_type_info::name, swig_object_wrapper::newobject, swig_object_wrapper::ptr, Z_SET_ISREF_P, and Z_SET_REFCOUNT_P.
ZEND_NAMED_FUNCTION (_wrap_PonteExpander_expand)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__PonteExpander.
ZEND_NAMED_FUNCTION (_wrap_new_PonteExpander)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__Parameters, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__query__PonteExpander.
ZEND_NAMED_FUNCTION (_wrap_RMExpander_expand)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__RMExpander.
ZEND_NAMED_FUNCTION (_wrap_new_RMExpander)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__Parameters, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__query__RMExpander.
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_expand)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__QueryExpander.
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__query__QueryExpander.
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery__SWIG_1)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__QueryExpander.
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery__SWIG_0)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__QueryExpander.
ZEND_NAMED_FUNCTION (_wrap_new_QueryEnvironment)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_reformulateQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setFormulationParameters)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__Parameters, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentLength)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList__SWIG_1)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList__SWIG_0)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount__SWIG_1)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount__SWIG_0)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount__SWIG_1)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount__SWIG_0)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onedocumentCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_fieldList)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemFieldCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termFieldCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onetermCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentIDsFromMetadata)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadata)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadatadocids)
References documentMetadatadocids, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documents)
References indri::parse::TermExtent::begin, indri::parse::TermExtent::end, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__ParsedDocument, SWIGTYPE_p_indri__api__QueryEnvironment, SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentsdocids)
References indri::parse::TermExtent::begin, documentsdocids, indri::parse::TermExtent::end, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__ParsedDocument, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuerydocset)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuerydocset)
References runQuerydocset, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setStopwords)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setScoringRules)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setMemory)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_close)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addIndex)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addServer)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getResults)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getAnnotations)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getQueryTree)
References php_makeQueryAnnotationNode(), SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryAnnotation.
ZEND_NAMED_FUNCTION (_wrap_new_QueryAnnotationNode)
References php_makeQueryAnnotationNode(), SWIG_ErrorCode, SWIG_ErrorMsg, and SWIG_ResetError().
ZEND_NAMED_FUNCTION (_wrap_new_ParsedDocument)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__ParsedDocument.
ZEND_NAMED_FUNCTION (_wrap_ParsedDocument_getContent)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__ParsedDocument.
ZEND_NAMED_FUNCTION (_wrap_new_ScoredExtentResult)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_Parameters_load)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_exists)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_size)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_clear)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_double)
References set_double, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_UINT64)
References set_UINT64, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_int)
References set_int, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_string)
References set_string, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_bool)
References set_bool, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_remove)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_string)
References get_string, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_INT64)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_double)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_int)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_bool)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_new_Parameters)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_new_TermExtent)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_get)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_set)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_get)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_set)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_swig_libindri_php_get_newobject)
References swig_object_wrapper::newobject, and SWIG_ResetError().
ZEND_NAMED_FUNCTION (_wrap_swig_libindri_php_alter_newobject)
References swig_object_wrapper::newobject, and SWIG_ResetError().
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__QueryAnnotationNode) [static]
References __wrap_delete_QueryAnnotationNode(), and SWIGTYPE_p_indri__api__QueryAnnotationNode.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_std__vectorT_std__string_t) [static]
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__ParsedDocument) [static]
References __wrap_delete_ParsedDocument(), and SWIGTYPE_p_indri__api__ParsedDocument.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__ScoredExtentResult) [static]
References __wrap_delete_ScoredExtentResult(), and SWIGTYPE_p_indri__api__ScoredExtentResult.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_std__vectorT_lemur__api__DOCID_T_t) [static]
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__query__QueryExpander) [static]
References __wrap_delete_QueryExpander(), and SWIGTYPE_p_indri__query__QueryExpander.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__query__RMExpander) [static]
References __wrap_delete_RMExpander(), and SWIGTYPE_p_indri__query__RMExpander.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__query__PonteExpander) [static]
References __wrap_delete_PonteExpander(), and SWIGTYPE_p_indri__query__PonteExpander.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_std__vectorT_indri__api__ScoredExtentResult_t) [static]
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_long_long) [static]
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__QueryEnvironment) [static]
References __wrap_delete_QueryEnvironment(), and SWIGTYPE_p_indri__api__QueryEnvironment.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__parse__TermExtent) [static]
References __wrap_delete_TermExtent(), and SWIGTYPE_p_indri__parse__TermExtent.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__QueryAnnotation) [static]
References __wrap_delete_QueryAnnotation(), and SWIGTYPE_p_indri__api__QueryAnnotation.
static ZEND_RSRC_DTOR_FUNC (_wrap_destroy_p_indri__api__Parameters) [static]
References __wrap_delete_Parameters(), and SWIGTYPE_p_indri__api__Parameters.
static ZEND_RSRC_DTOR_FUNC (SWIG_landfill) [static]
Variable Documentation
swig_cast_info _swigc__p_indri__api__Parameters[] = { {&_swigt__p_indri__api__Parameters, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__api__ParsedDocument[] = { {&_swigt__p_indri__api__ParsedDocument, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__api__QueryAnnotation[] = { {&_swigt__p_indri__api__QueryAnnotation, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__api__QueryAnnotationNode[] = { {&_swigt__p_indri__api__QueryAnnotationNode, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__api__QueryEnvironment[] = { {&_swigt__p_indri__api__QueryEnvironment, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__api__ScoredExtentResult[] = { {&_swigt__p_indri__api__ScoredExtentResult, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__parse__TermExtent[] = { {&_swigt__p_indri__parse__TermExtent, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__query__PonteExpander[] = { {&_swigt__p_indri__query__PonteExpander, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__query__QueryExpander[] = { {&_swigt__p_indri__query__QueryExpander, 0, 0, 0}, {&_swigt__p_indri__query__RMExpander, _p_indri__query__RMExpanderTo_p_indri__query__QueryExpander, 0, 0}, {&_swigt__p_indri__query__PonteExpander, _p_indri__query__PonteExpanderTo_p_indri__query__QueryExpander, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_indri__query__RMExpander[] = { {&_swigt__p_indri__query__RMExpander, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_long_long[] = { {&_swigt__p_long_long, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_std__vectorT_indri__api__ScoredExtentResult_t[] = { {&_swigt__p_std__vectorT_indri__api__ScoredExtentResult_t, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_std__vectorT_lemur__api__DOCID_T_t[] = { {&_swigt__p_std__vectorT_lemur__api__DOCID_T_t, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_cast_info _swigc__p_std__vectorT_std__string_t[] = { {&_swigt__p_std__vectorT_std__string_t, 0, 0, 0},{0, 0, 0, 0}} [static]
swig_type_info _swigt__p_indri__api__Parameters = {"_p_indri__api__Parameters", "indri::api::Parameters *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__api__ParsedDocument = {"_p_indri__api__ParsedDocument", "indri::api::ParsedDocument *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__api__QueryAnnotation = {"_p_indri__api__QueryAnnotation", "indri::api::QueryAnnotation *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__api__QueryAnnotationNode = {"_p_indri__api__QueryAnnotationNode", "indri::api::QueryAnnotationNode *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__api__QueryEnvironment = {"_p_indri__api__QueryEnvironment", "indri::api::QueryEnvironment *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__api__ScoredExtentResult = {"_p_indri__api__ScoredExtentResult", "indri::api::ScoredExtentResult *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__parse__TermExtent = {"_p_indri__parse__TermExtent", "indri::parse::TermExtent *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__query__PonteExpander = {"_p_indri__query__PonteExpander", "indri::query::PonteExpander *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__query__QueryExpander = {"_p_indri__query__QueryExpander", "indri::query::QueryExpander *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_indri__query__RMExpander = {"_p_indri__query__RMExpander", "indri::query::RMExpander *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_long_long = {"_p_long_long", "UINT64 *|INT64 *|long long *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_std__vectorT_indri__api__ScoredExtentResult_t = {"_p_std__vectorT_indri__api__ScoredExtentResult_t", "std::vector< indri::api::ScoredExtentResult > *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_std__vectorT_lemur__api__DOCID_T_t = {"_p_std__vectorT_lemur__api__DOCID_T_t", "std::vector< lemur::api::DOCID_T > *", 0, 0, (void*)0, 0} [static]
swig_type_info _swigt__p_std__vectorT_std__string_t = {"_p_std__vectorT_std__string_t", "std::vector< std::string > *", 0, 0, (void*)0, 0} [static]
char const_name[] = "swig_runtime_data_type_pointer" [static]
Referenced by SWIG_Php_GetModule(), and SWIG_Php_SetModule().
int default_error_code = E_ERROR [static]
Referenced by libindri_php_init_globals(), and SWIG_ResetError().
const char* default_error_msg = "Unknown error occurred" [static]
Referenced by libindri_php_init_globals(), and SWIG_ResetError().
int error_code
const char* error_msg
int le_member_ptr [static]
int le_swig__p_indri__api__Parameters = 0 [static]
int le_swig__p_indri__api__ParsedDocument = 0 [static]
int le_swig__p_indri__api__QueryAnnotation = 0 [static]
int le_swig__p_indri__api__QueryAnnotationNode = 0 [static]
int le_swig__p_indri__api__QueryEnvironment = 0 [static]
int le_swig__p_indri__api__ScoredExtentResult = 0 [static]
int le_swig__p_indri__parse__TermExtent = 0 [static]
int le_swig__p_indri__query__PonteExpander = 0 [static]
int le_swig__p_indri__query__QueryExpander = 0 [static]
int le_swig__p_indri__query__RMExpander = 0 [static]
int le_swig__p_long_long = 0 [static]
int le_swig__p_std__vectorT_indri__api__ScoredExtentResult_t = 0 [static]
int le_swig__p_std__vectorT_lemur__api__DOCID_T_t = 0 [static]
int le_swig__p_std__vectorT_std__string_t = 0 [static]
zend_function_entry libindri_php_functions[] [static]
zend_module_entry libindri_php_module_entry
Initial value:
 {
    (char*)"libindri_php",
    libindri_php_functions,
    PHP_MINIT(libindri_php),
    PHP_MSHUTDOWN(libindri_php),
    PHP_RINIT(libindri_php),
    PHP_RSHUTDOWN(libindri_php),
    PHP_MINFO(libindri_php),
    STANDARD_MODULE_PROPERTIES
}
swig_cast_info* swig_cast_initial[] [static]
Initial value:
 {
  _swigc__p_indri__api__Parameters,
  _swigc__p_indri__api__ParsedDocument,
  _swigc__p_indri__api__QueryAnnotation,
  _swigc__p_indri__api__QueryAnnotationNode,
  _swigc__p_indri__api__QueryEnvironment,
  _swigc__p_indri__api__ScoredExtentResult,
  _swigc__p_indri__parse__TermExtent,
  _swigc__p_indri__query__PonteExpander,
  _swigc__p_indri__query__QueryExpander,
  _swigc__p_indri__query__RMExpander,
  _swigc__p_long_long,
  _swigc__p_std__vectorT_indri__api__ScoredExtentResult_t,
  _swigc__p_std__vectorT_lemur__api__DOCID_T_t,
  _swigc__p_std__vectorT_std__string_t,
}
swig_module_info swig_module = {swig_types, 14, 0, 0, 0, 0} [static]
zend_module_entry* SWIG_module_entry = &libindri_php_module_entry
swig_type_info* swig_type_initial[] [static]
Initial value:
 {
  &_swigt__p_indri__api__Parameters,
  &_swigt__p_indri__api__ParsedDocument,
  &_swigt__p_indri__api__QueryAnnotation,
  &_swigt__p_indri__api__QueryAnnotationNode,
  &_swigt__p_indri__api__QueryEnvironment,
  &_swigt__p_indri__api__ScoredExtentResult,
  &_swigt__p_indri__parse__TermExtent,
  &_swigt__p_indri__query__PonteExpander,
  &_swigt__p_indri__query__QueryExpander,
  &_swigt__p_indri__query__RMExpander,
  &_swigt__p_long_long,
  &_swigt__p_std__vectorT_indri__api__ScoredExtentResult_t,
  &_swigt__p_std__vectorT_lemur__api__DOCID_T_t,
  &_swigt__p_std__vectorT_std__string_t,
}
swig_type_info* swig_types[15] [static]