Indri: IndriRunQuery.cpp File Reference
IndriRunQuery.cpp File Reference
#include <time.h>
#include "indri/QueryEnvironment.hpp"
#include "indri/LocalQueryServer.hpp"
#include "indri/delete_range.hpp"
#include "indri/NetworkStream.hpp"
#include "indri/NetworkMessageStream.hpp"
#include "indri/NetworkServerProxy.hpp"
#include "indri/ListIteratorNode.hpp"
#include "indri/ExtentInsideNode.hpp"
#include "indri/DocListIteratorNode.hpp"
#include "indri/FieldIteratorNode.hpp"
#include "indri/Parameters.hpp"
#include "indri/ParsedDocument.hpp"
#include "indri/Collection.hpp"
#include "indri/CompressedCollection.hpp"
#include "indri/TaggedDocumentIterator.hpp"
#include "indri/XMLNode.hpp"
#include "indri/QueryExpander.hpp"
#include "indri/RMExpander.hpp"
#include "indri/PonteExpander.hpp"
#include "indri/TFIDFExpander.hpp"
#include "indri/IndriTimer.hpp"
#include "indri/UtilityThread.hpp"
#include "indri/ScopedLock.hpp"
#include "indri/SnippetBuilder.hpp"
#include <queue>
Classes
struct query_t
struct query_t::greater
class QueryThread
Functions
static bool copy_parameters_to_string_vector (std::vector< std::string > &vec, indri::api::Parameters p, const std::string &parameterName)
void push_queue (std::queue< query_t * > &q, indri::api::Parameters &queries, int queryOffset)
int main (int argc, char *argv[])
Function Documentation
static bool copy_parameters_to_string_vector (std::vector< std::string > & vec, indri::api::Parameters p, const std::string & parameterName) [static]
References indri::api::Parameters::exists(), and indri::api::Parameters::size().
Referenced by QueryThread::initialize(), and push_queue().
int main (int argc, char * argv[])
References indri::utility::delete_vector_contents(), indri::api::Parameters::exists(), indri::api::Parameters::get(), INDRI_DISTRIBUTION, indri::api::Parameters::instance(), indri::api::Parameters::loadCommandLine(), indri::thread::Mutex::lock(), push_queue(), query_t::text, indri::thread::Mutex::unlock(), and indri::thread::ConditionVariable::wait().
void push_queue (std::queue< query_t * > & q, indri::api::Parameters & queries, int queryOffset)
References copy_parameters_to_string_vector(), and indri::api::Parameters::size().
Referenced by main().