Indri: InferenceNetworkBuilder.cpp File Reference
InferenceNetworkBuilder.cpp File Reference
#include "indri/InferenceNetworkBuilder.hpp"
#include "indri/ContextCountAccumulator.hpp"
#include "indri/ContextSimpleCountAccumulator.hpp"
#include "indri/ListAccumulator.hpp"
#include "indri/DocListIteratorNode.hpp"
#include "indri/ExtentInsideNode.hpp"
#include "indri/ExtentAndNode.hpp"
#include "indri/ExtentOrNode.hpp"
#include "indri/WeightedExtentOrNode.hpp"
#include "indri/OrderedWindowNode.hpp"
#include "indri/UnorderedWindowNode.hpp"
#include "indri/FieldIteratorNode.hpp"
#include "indri/ListBeliefNode.hpp"
#include "indri/ScoredExtentAccumulator.hpp"
#include "indri/WeightedAndNode.hpp"
#include "indri/NullScorerNode.hpp"
#include "indri/OrNode.hpp"
#include "indri/NotNode.hpp"
#include "indri/WeightedSumNode.hpp"
#include "indri/FilterRejectNode.hpp"
#include "indri/FilterRequireNode.hpp"
#include "indri/FieldBetweenNode.hpp"
#include "indri/FieldEqualsNode.hpp"
#include "indri/FieldLessNode.hpp"
#include "indri/FieldGreaterNode.hpp"
#include "indri/MaxNode.hpp"
#include "indri/PriorNode.hpp"
#include "indri/ExtentRestrictionNode.hpp"
#include "indri/FixedPassageNode.hpp"
#include "indri/FilterNode.hpp"
#include "indri/NullListNode.hpp"
#include "indri/PlusNode.hpp"
#include "indri/WPlusNode.hpp"
#include "indri/TermScoreFunctionFactory.hpp"
#include "indri/TermFrequencyBeliefNode.hpp"
#include "indri/CachedFrequencyBeliefNode.hpp"
#include "indri/BooleanAndNode.hpp"
#include "indri/FieldWildcardNode.hpp"
#include "indri/NestedExtentInsideNode.hpp"
#include "indri/NestedListBeliefNode.hpp"
#include "indri/ExtentEnforcementNode.hpp"
#include "indri/ContextInclusionAndNode.hpp"
#include "indri/LengthPriorNode.hpp"
#include "indri/DocumentStructureHolderNode.hpp"
#include "indri/ShrinkageBeliefNode.hpp"
#include "indri/ExtentParentNode.hpp"
#include "indri/ExtentChildNode.hpp"
#include "indri/ExtentDescendantNode.hpp"
#include "indri/FieldBelowWalker.hpp"
#include <cmath>
#include <stdexcept>
Functions
static bool inferencenetworkbuilder_is_stopword (indri::infnet::ListIteratorNode *node)
static bool inferencenetworkbuilder_contains_stopwords (const std::vector< indri::infnet::ListIteratorNode * > &nodes)
static int inferencenetworkbuilder_find_stopwords_left (const std::vector< indri::infnet::ListIteratorNode * > &nodes)
static int inferencenetworkbuilder_find_stopwords_right (const std::vector< indri::infnet::ListIteratorNode * > &nodes)
static void inferencenetworkbuilder_find_stopwords_stretch (const std::vector< indri::infnet::ListIteratorNode * > &nodes, int &begin, int &end)
static
indri::infnet::ListIteratorNode * inferencenetworkbuilder_build_child_window (indri::infnet::InferenceNetwork *network, const std::vector< indri::infnet::ListIteratorNode * > &nodes, int windowSize)
static
indri::infnet::ListIteratorNode * inferencenetworkbuilder_build_ordered_window (indri::infnet::InferenceNetwork *network, const std::string &nodeName, const std::vector< indri::infnet::ListIteratorNode * > &nodes, int windowSize)
Function Documentation
static indri::infnet::ListIteratorNode* inferencenetworkbuilder_build_child_window (indri::infnet::InferenceNetwork * network, const std::vector< indri::infnet::ListIteratorNode * > & nodes, int windowSize) [static]
References indri::infnet::InferenceNetwork::addListNode(), inferencenetworkbuilder_contains_stopwords(), inferencenetworkbuilder_find_stopwords_stretch(), and inferencenetworkbuilder_is_stopword().
Referenced by inferencenetworkbuilder_build_ordered_window().
static indri::infnet::ListIteratorNode* inferencenetworkbuilder_build_ordered_window (indri::infnet::InferenceNetwork * network, const std::string & nodeName, const std::vector< indri::infnet::ListIteratorNode * > & nodes, int windowSize) [static]
References indri::infnet::InferenceNetwork::addListNode(), inferencenetworkbuilder_build_child_window(), inferencenetworkbuilder_contains_stopwords(), inferencenetworkbuilder_find_stopwords_left(), inferencenetworkbuilder_find_stopwords_right(), and inferencenetworkbuilder_find_stopwords_stretch().
Referenced by indri::infnet::InferenceNetworkBuilder::after().
static bool inferencenetworkbuilder_contains_stopwords (const std::vector< indri::infnet::ListIteratorNode * > & nodes) [static]
References inferencenetworkbuilder_is_stopword().
Referenced by inferencenetworkbuilder_build_child_window(), and inferencenetworkbuilder_build_ordered_window().
static int inferencenetworkbuilder_find_stopwords_left (const std::vector< indri::infnet::ListIteratorNode * > & nodes) [static]
References inferencenetworkbuilder_is_stopword().
Referenced by inferencenetworkbuilder_build_ordered_window().
static int inferencenetworkbuilder_find_stopwords_right (const std::vector< indri::infnet::ListIteratorNode * > & nodes) [static]
References inferencenetworkbuilder_is_stopword().
Referenced by inferencenetworkbuilder_build_ordered_window().
static void inferencenetworkbuilder_find_stopwords_stretch (const std::vector< indri::infnet::ListIteratorNode * > & nodes, int & begin, int & end) [static]
References inferencenetworkbuilder_is_stopword().
Referenced by inferencenetworkbuilder_build_child_window(), and inferencenetworkbuilder_build_ordered_window().
static bool inferencenetworkbuilder_is_stopword (indri::infnet::ListIteratorNode * node) [static]
References indri::infnet::NullListNode::isStopword().
Referenced by inferencenetworkbuilder_build_child_window(), inferencenetworkbuilder_contains_stopwords(), inferencenetworkbuilder_find_stopwords_left(), inferencenetworkbuilder_find_stopwords_right(), and inferencenetworkbuilder_find_stopwords_stretch().