Indri: makeprior.cpp File Reference
makeprior.cpp File Reference
#include "indri/QueryEnvironment.hpp"
#include "indri/Parameters.hpp"
#include "indri/File.hpp"
#include "indri/SequentialReadBuffer.hpp"
#include "indri/SequentialWriteBuffer.hpp"
#include "indri/Path.hpp"
#include "indri/ScopedLock.hpp"
#include <queue>
#include <fstream>
Classes
struct MergeFile
Functions
void copy_region (indri::file::File &out, indri::file::File &in, UINT64 position, UINT64 length)
void merge_sorted_runs (indri::file::File &out, std::vector< std::string > &inputs, int totalDocuments)
int sort_comparator (const void *one, const void *two)
void sort_run (indri::file::File &out, indri::file::File &in, size_t memory)
void sort_file (indri::file::File &out, indri::file::File &in, size_t memory, int totalDocuments)
void convert_intscore_to_long_binary (indri::file::File &outfile, const char *infile)
void convert_docnoscore_to_binary (indri::file::File &outfile, const std::string &infile, indri::api::QueryEnvironment &env)
void invert_map (std::map< int, double > &out, const std::map< double, int > &in)
void compress_file (indri::file::File &out, indri::file::File &in, const std::map< double, int > &values)
bool extract_compression_table (std::map< double, int > &values, indri::file::File &in)
void install_prior (const std::string &indexPath, const std::string &priorName, indri::file::File &priorFile)
int main (int argc, char **argv)
Function Documentation
void compress_file (indri::file::File & out, indri::file::File & in, const std::map< double, int > & values)
References indri::file::SequentialWriteBuffer::flush(), invert_map(), indri::file::SequentialReadBuffer::read(), and indri::file::SequentialWriteBuffer::write().
Referenced by main().
void convert_docnoscore_to_binary (indri::file::File & outfile, const std::string & infile, indri::api::QueryEnvironment & env)
References indri::api::QueryEnvironment::documentIDsFromMetadata(), indri::file::SequentialWriteBuffer::flush(), and indri::file::SequentialWriteBuffer::write().
Referenced by main().
void convert_intscore_to_long_binary (indri::file::File & outfile, const char * infile)
References indri::file::File::close(), indri::file::SequentialWriteBuffer::flush(), and indri::file::SequentialWriteBuffer::write().
void copy_region (indri::file::File & out, indri::file::File & in, UINT64 position, UINT64 length)
References indri::file::File::read(), and indri::file::File::write().
Referenced by install_prior(), and sort_file().
bool extract_compression_table (std::map< double, int > & values, indri::file::File & in)
References MergeFile::buffer, MergeFile::file, MergeFile::finished(), MergeFile::length, MergeFile::readScore(), MergeFile::score, indri::file::SequentialReadBuffer::seek(), and indri::file::File::size().
Referenced by main().
void install_prior (const std::string & indexPath, const std::string & priorName, indri::file::File & priorFile)
References indri::file::File::close(), indri::file::Path::combine(), copy_region(), indri::file::File::create(), indri::file::Path::exists(), indri::file::Path::make(), and indri::file::File::size().
Referenced by main().
void invert_map (std::map< int, double > & out, const std::map< double, int > & in)
Referenced by compress_file().
int main (int argc, char ** argv)
References indri::api::QueryEnvironment::addIndex(), indri::file::File::close(), compress_file(), convert_docnoscore_to_binary(), indri::api::Parameters::exists(), extract_compression_table(), indri::api::Parameters::get(), indri::collection::Repository::indexes(), input(), install_prior(), indri::api::Parameters::instance(), indri::api::Parameters::loadCommandLine(), indri::collection::Repository::openRead(), indri::file::File::openTemporary(), and sort_file().
void merge_sorted_runs (indri::file::File & out, std::vector< std::string > & inputs, int totalDocuments)
References MergeFile::buffer, indri::file::File::close(), MergeFile::document, MergeFile::file, MergeFile::finished(), indri::file::SequentialWriteBuffer::flush(), MergeFile::length, indri::file::File::openRead(), MergeFile::read(), MergeFile::score, indri::file::File::size(), and indri::file::SequentialWriteBuffer::write().
Referenced by sort_file().
int sort_comparator (const void * one, const void * two)
Referenced by sort_run().
void sort_file (indri::file::File & out, indri::file::File & in, size_t memory, int totalDocuments)
References indri::file::File::close(), copy_region(), merge_sorted_runs(), indri::file::File::openTemporary(), indri::file::File::size(), and sort_run().
Referenced by main().
void sort_run (indri::file::File & out, indri::file::File & in, size_t memory)
References indri::file::File::close(), indri::file::File::read(), indri::file::File::size(), sort_comparator(), and indri::file::File::write().
Referenced by sort_file().