Indri: Path.cpp File Reference
Path.cpp File Reference
#include <string>
#include "indri/Path.hpp"
#include "lemur/Exception.hpp"
#include "lemur/lemur-compat.hpp"
#include <sys/stat.h>
#include <errno.h>
#include <iostream>
#include <stack>
#include "indri/DirectoryIterator.hpp"
#include "indri/delete_range.hpp"
#include "indri/XMLNode.hpp"
#include "indri/XMLReader.hpp"
Defines
#define PATH_SEPARATOR '/'
Functions
static int path_last_separator (const std::string &path)
Define Documentation
#define PATH_SEPARATOR '/'
Referenced by indri::file::Path::combine(), path_last_separator(), indri::file::Path::pathSeparator(), indri::file::Path::relative(), and indri::file::Path::trim().
Function Documentation
static int path_last_separator (const std::string & path) [static]
References PATH_SEPARATOR.
Referenced by indri::file::Path::basename(), indri::file::Path::directory(), indri::file::Path::extension(), and indri::file::Path::filename().