Indri: PDFDocumentExtractor.cpp File Reference
PDFDocumentExtractor.cpp File Reference
#include "indri/PDFDocumentExtractor.hpp"
#include "indri/Buffer.hpp"
#include "GString.h"
#include "TextOutputDev.h"
#include "PDFDoc.h"
#include "Object.h"
#include "Stream.h"
#include "Array.h"
#include "Dict.h"
#include "XRef.h"
#include "Page.h"
#include "CharTypes.h"
#include "GlobalParams.h"
#include "lemur/Exception.hpp"
Functions
static void buffer_write (void *stream, char *text, int len)
Function Documentation
static void buffer_write (void * stream, char * text, int len) [static]
References indri::utility::Buffer::position(), indri::utility::Buffer::unwrite(), and indri::utility::Buffer::write().
Referenced by indri::parse::PDFDocumentExtractor::nextDocument().