Indri: php_libindri_php.h File Reference
php_libindri_php.h File Reference
Defines
#define phpext_libindri_php_ptr &libindri_php_module_entry
#define PHP_LIBINDRI_PHP_API
Functions
PHP_MINIT_FUNCTION (libindri_php)
PHP_MSHUTDOWN_FUNCTION (libindri_php)
PHP_RINIT_FUNCTION (libindri_php)
PHP_RSHUTDOWN_FUNCTION (libindri_php)
PHP_MINFO_FUNCTION (libindri_php)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_set)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_get)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_set)
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_get)
ZEND_NAMED_FUNCTION (_wrap_new_TermExtent)
ZEND_NAMED_FUNCTION (_wrap_new_Parameters)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_bool)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_int)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_double)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_INT64)
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_string)
ZEND_NAMED_FUNCTION (_wrap_Parameters_remove)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_bool)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_string)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_int)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_UINT64)
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_double)
ZEND_NAMED_FUNCTION (_wrap_Parameters_clear)
ZEND_NAMED_FUNCTION (_wrap_Parameters_size)
ZEND_NAMED_FUNCTION (_wrap_Parameters_exists)
ZEND_NAMED_FUNCTION (_wrap_Parameters_load)
ZEND_NAMED_FUNCTION (_wrap_new_ScoredExtentResult)
ZEND_NAMED_FUNCTION (_wrap_ParsedDocument_getContent)
ZEND_NAMED_FUNCTION (_wrap_new_ParsedDocument)
ZEND_NAMED_FUNCTION (_wrap_new_QueryAnnotationNode)
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getQueryTree)
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getAnnotations)
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getResults)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addServer)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addIndex)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_close)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setMemory)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setScoringRules)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setStopwords)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuery)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuerydocset)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuery)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuerydocset)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentsdocids)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documents)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadatadocids)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadata)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentIDsFromMetadata)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onetermCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termFieldCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemFieldCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_fieldList)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onedocumentCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentLength)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setFormulationParameters)
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_reformulateQuery)
ZEND_NAMED_FUNCTION (_wrap_new_QueryEnvironment)
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery)
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_expand)
ZEND_NAMED_FUNCTION (_wrap_new_RMExpander)
ZEND_NAMED_FUNCTION (_wrap_RMExpander_expand)
ZEND_NAMED_FUNCTION (_wrap_new_PonteExpander)
ZEND_NAMED_FUNCTION (_wrap_PonteExpander_expand)
Variables
zend_module_entry libindri_php_module_entry
Define Documentation
#define PHP_LIBINDRI_PHP_API
#define phpext_libindri_php_ptr &libindri_php_module_entry
Function Documentation
PHP_MINFO_FUNCTION (libindri_php)
PHP_MINIT_FUNCTION (libindri_php)
PHP_MSHUTDOWN_FUNCTION (libindri_php)
PHP_RINIT_FUNCTION (libindri_php)
PHP_RSHUTDOWN_FUNCTION (libindri_php)
ZEND_NAMED_FUNCTION (_wrap_PonteExpander_expand)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__PonteExpander.
ZEND_NAMED_FUNCTION (_wrap_new_PonteExpander)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__Parameters, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__query__PonteExpander.
ZEND_NAMED_FUNCTION (_wrap_RMExpander_expand)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__RMExpander.
ZEND_NAMED_FUNCTION (_wrap_new_RMExpander)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__Parameters, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__query__RMExpander.
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_expand)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__query__QueryExpander.
ZEND_NAMED_FUNCTION (_wrap_QueryExpander_runExpandedQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__query__QueryExpander.
ZEND_NAMED_FUNCTION (_wrap_new_QueryEnvironment)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_reformulateQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setFormulationParameters)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__Parameters, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentLength)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionList)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentExpressionCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_expressionCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onedocumentCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_fieldList)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemFieldCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termFieldCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_stemCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_onetermCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_termCount)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentIDsFromMetadata)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadata)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentMetadatadocids)
References documentMetadatadocids, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documents)
References indri::parse::TermExtent::begin, indri::parse::TermExtent::end, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__ParsedDocument, SWIGTYPE_p_indri__api__QueryEnvironment, SWIGTYPE_p_indri__api__ScoredExtentResult, and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_documentsdocids)
References indri::parse::TermExtent::begin, documentsdocids, indri::parse::TermExtent::end, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__ParsedDocument, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuerydocset)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runAnnotatedQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuerydocset)
References runQuerydocset, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_runQuery)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryEnvironment, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setStopwords)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setScoringRules)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_setMemory)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_close)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addIndex)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryEnvironment_addServer)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryEnvironment.
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getResults)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getAnnotations)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), SWIG_SetPointerZval, SWIGTYPE_p_indri__api__QueryAnnotation, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_QueryAnnotation_getQueryTree)
References php_makeQueryAnnotationNode(), SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__QueryAnnotation.
ZEND_NAMED_FUNCTION (_wrap_new_QueryAnnotationNode)
References php_makeQueryAnnotationNode(), SWIG_ErrorCode, SWIG_ErrorMsg, and SWIG_ResetError().
ZEND_NAMED_FUNCTION (_wrap_new_ParsedDocument)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__ParsedDocument.
ZEND_NAMED_FUNCTION (_wrap_ParsedDocument_getContent)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__ParsedDocument.
ZEND_NAMED_FUNCTION (_wrap_new_ScoredExtentResult)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__ScoredExtentResult.
ZEND_NAMED_FUNCTION (_wrap_Parameters_load)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_exists)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_size)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_clear)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_double)
References set_double, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_UINT64)
References set_UINT64, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_int)
References set_int, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_string)
References set_string, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set_bool)
References set_bool, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_remove)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_string)
References get_string, SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_INT64)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_double)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_int)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_get_bool)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_Parameters_set)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_new_Parameters)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__api__Parameters.
ZEND_NAMED_FUNCTION (_wrap_new_TermExtent)
References SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_ResetError(), SWIG_SetPointerZval, and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_get)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_end_set)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_get)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
ZEND_NAMED_FUNCTION (_wrap_TermExtent_begin_set)
References SWIG_ConvertPtr, SWIG_ErrorCode, SWIG_ErrorMsg, SWIG_PHP_Error, SWIG_ResetError(), and SWIGTYPE_p_indri__parse__TermExtent.
Variable Documentation
zend_module_entry libindri_php_module_entry