Indri: QuerySpec.hpp File Reference
QuerySpec.hpp File Reference
#include <vector>
#include <string>
#include <sstream>
#include <indri/greedy_vector>
#include <algorithm>
#include "lemur/lemur-platform.h"
#include "indri/Walker.hpp"
#include "indri/Copier.hpp"
#include "indri/Packer.hpp"
#include "indri/Unpacker.hpp"
#include "lemur/Exception.hpp"
#include "indri/HashTable.hpp"
#include "indri/ref_ptr.hpp"
Classes
class indri::lang::Node
class indri::lang::RawExtentNode
class indri::lang::ScoredExtentNode
class indri::lang::AccumulatorNode
class indri::lang::IndexTerm
class indri::lang::Field
class indri::lang::ExtentInside
class indri::lang::WeightedExtentOr
class indri::lang::ExtentOr
class indri::lang::ExtentAnd
class indri::lang::BAndNode
class indri::lang::UWNode
class indri::lang::ODNode
class indri::lang::FilReqNode
class indri::lang::FilRejNode
class indri::lang::FieldLessNode
class indri::lang::FieldGreaterNode
class indri::lang::FieldBetweenNode
class indri::lang::FieldEqualsNode
class indri::lang::RawScorerNode
class indri::lang::TermFrequencyScorerNode
class indri::lang::CachedFrequencyScorerNode
class indri::lang::PriorNode
class indri::lang::UnweightedCombinationNode
class indri::lang::WeightedCombinationNode
class indri::lang::OrNode
class indri::lang::NotNode
class indri::lang::MaxNode
class indri::lang::CombineNode
class indri::lang::WAndNode
class indri::lang::WSumNode
class indri::lang::WeightNode
class indri::lang::ExtentRestriction
class indri::lang::FixedPassage
class indri::lang::FilterNode
class indri::lang::ListAccumulator
class indri::lang::ContextCounterNode
class indri::lang::ContextSimpleCounterNode
class indri::lang::ScoreAccumulatorNode
class indri::lang::AnnotatorNode
class indri::lang::FieldWildcard
class indri::lang::NestedExtentInside
class indri::lang::NestedRawScorerNode
class indri::lang::ExtentEnforcement
class indri::lang::ContextInclusionNode
class indri::lang::LengthPrior
class indri::lang::DocumentStructureNode
class indri::lang::ShrinkageScorerNode
class indri::lang::ExtentDescendant
class indri::lang::ExtentChild
class indri::lang::ExtentParent
class indri::lang::WildcardTerm
class indri::lang::PlusNode
class indri::lang::WPlusNode
Namespaces
namespace indri
namespaces within the indri system
namespace indri::lang
Indri query language nodes and support classes.
Functions
template<class T >
bool equal (const std::vector< T > &one, const std::vector< T > &two)
template<class T >
bool unordered_equal (std::vector< T > &one, std::vector< T > &two)
Function Documentation
template<class T > bool equal (const std::vector< T > & one, const std::vector< T > & two) [inline]
Referenced by indri::lang::ODNode::operator==().
template<class T > bool unordered_equal (std::vector< T > & one, std::vector< T > & two) [inline]
Referenced by indri::lang::UWNode::operator==(), indri::lang::ExtentAnd::operator==(), and indri::lang::ExtentOr::operator==().