Indri: SnippetBuilder.cpp File Reference
SnippetBuilder.cpp File Reference
#include "indri/SnippetBuilder.hpp"
#include <algorithm>
#include <set>
Functions
bool sort_extent_pairs (const std::pair< indri::index::Extent, int > &one, const std::pair< indri::index::Extent, int > &two)
bool sort_regions (const indri::api::SnippetBuilder::Region &one, const indri::api::SnippetBuilder::Region &two)
bool should_skip (const std::vector< indri::api::SnippetBuilder::Region > &skips, int begin, int end)
Function Documentation
bool should_skip (const std::vector< indri::api::SnippetBuilder::Region > & skips, int begin, int end)
Referenced by indri::api::SnippetBuilder::_bestRegion().
bool sort_extent_pairs (const std::pair< indri::index::Extent, int > & one, const std::pair< indri::index::Extent, int > & two)
Referenced by indri::api::SnippetBuilder::_documentMatches().
bool sort_regions (const indri::api::SnippetBuilder::Region & one, const indri::api::SnippetBuilder::Region & two)
References indri::api::SnippetBuilder::Region::begin.
Referenced by indri::api::SnippetBuilder::_buildRegions().