Indri: indri::index::DocListFileIterator::iterator_greater Struct Reference
indri::index::DocListFileIterator::iterator_greater Struct Reference
#include <DocListFileIterator.hpp>
Public Member Functions
bool operator() (const DocListFileIterator *const &one, const DocListFileIterator *const &two) const
Member Function Documentation
bool indri::index::DocListFileIterator::iterator_greater::operator() (const DocListFileIterator *const & one, const DocListFileIterator *const & two) const [inline]
References indri::index::DocListIterator::currentEntry(), indri::index::DocListFileIterator::currentEntry(), indri::index::DocListFileIterator::finished(), indri::index::DocListFileIterator::DocListData::iterator, indri::index::TermData::term, and indri::index::DocListFileIterator::DocListData::termData.
The documentation for this struct was generated from the following file:
DocListFileIterator.hpp